In [98]:
import pandas as pd
import json
import ast

In [111]:
%pwd

'/data/resources/weichel-llama3/work'

In [112]:
a = "projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/dataset__stoxx_600_sentence_len_6__nace_level_1/Antofagasta plc1.txt/Antofagasta plc1.txt_classifications.csv"
a = "projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/dataset__stoxx_600_sentence_len_6__nace_level_1/Hannover Rueck SE1.txt/Hannover Rueck SE1.txt_classifications.csv"

In [113]:
df = pd.read_csv(a, index_col=0)
scores = df.columns.drop("Sentences")

In [114]:
sentences = df["Sentences"]

In [115]:
df

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,0.191897,-0.124444,-0.287198,0.633856,-0.276671,1.099860,-0.654853,-0.676771,-0.146036,0.629135,-0.011204,-0.727258,-0.811592,0.598488,0.052703,-0.165861,0.353671,as at december the company held shares in affi...
1,0.155103,-0.145598,-0.299084,0.540321,-0.193305,1.090008,-0.848602,-0.589157,-0.264598,0.566950,-0.030418,-0.687971,-0.833102,0.520925,-0.000365,-0.310725,0.112661,chairwoman of the board of directors hannover ...
2,-0.097350,-0.160960,-0.086333,-0.549700,-0.236412,0.065483,-0.301351,0.649644,-0.216021,0.474014,0.820925,0.229852,0.104849,-0.406195,0.257582,-0.439735,-0.294503,on march hannover re placed further subordinat...
3,0.263075,0.792267,-0.828495,-0.139517,0.361331,-0.380324,-0.429904,0.065207,-0.593262,0.221486,0.339534,-0.356140,0.013242,-0.102916,-0.377389,-0.153239,-0.355435,we have performed assurance work in accordance...
4,-0.101012,-0.128166,0.079305,-0.036931,-0.442384,-0.308575,-0.117051,0.216605,0.056395,0.096633,0.048609,-0.083820,0.483068,-0.143563,-0.154515,-0.315368,-0.593597,details of the remuneration systems can be fou...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,0.430432,0.144562,-0.305678,-0.167963,-0.575168,-0.566713,0.216612,0.076034,-0.170257,0.751549,1.208563,0.663282,-0.694872,-0.174470,0.160286,-0.478944,0.336585,with womenhr our company offers female employe...
307,0.045939,-0.067887,-0.274500,0.648892,-0.299638,1.064378,-0.630490,-0.725866,-0.130819,0.544327,-0.021380,-0.811103,-0.803566,0.572896,0.091027,-0.090289,0.320123,the executive directors calculate the amount o...
308,0.078355,-0.156455,-0.360638,-0.090083,-0.198462,0.335942,-0.630833,0.059404,-0.328543,0.170279,-0.059474,-0.299028,0.133634,0.208675,-0.091059,-0.378323,-0.434744,bearer debt securities and other fixedincome s...
309,-0.098156,-0.226462,0.223122,-0.342644,-0.550392,-0.380272,-0.347808,0.491536,0.006598,-0.051433,0.310545,-0.100136,0.131067,-0.229777,0.400582,-0.222315,-0.832760,pricewaterhousecoopers gmbh wirtschaftsprüfung...
310,0.107621,-0.231704,-0.308495,-0.245243,-0.456187,0.223237,-0.530745,0.134370,-0.238553,0.261504,0.023300,0.014721,0.122936,0.209819,-0.026740,-0.488119,-0.372102,we conducted our audit of the annual financial...

In [126]:
df[scores].max(1).sort_values(ascending=False)

224    1.292845
226    1.232839
185    1.230628
306    1.208563
188    1.192064
         ...
310    0.261504
289    0.256446
77     0.248624
31     0.237087
222    0.225997
Length: 311, dtype: float64

In [117]:
df

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,0.191897,-0.124444,-0.287198,0.633856,-0.276671,1.099860,-0.654853,-0.676771,-0.146036,0.629135,-0.011204,-0.727258,-0.811592,0.598488,0.052703,-0.165861,0.353671,as at december the company held shares in affi...
1,0.155103,-0.145598,-0.299084,0.540321,-0.193305,1.090008,-0.848602,-0.589157,-0.264598,0.566950,-0.030418,-0.687971,-0.833102,0.520925,-0.000365,-0.310725,0.112661,chairwoman of the board of directors hannover ...
2,-0.097350,-0.160960,-0.086333,-0.549700,-0.236412,0.065483,-0.301351,0.649644,-0.216021,0.474014,0.820925,0.229852,0.104849,-0.406195,0.257582,-0.439735,-0.294503,on march hannover re placed further subordinat...
3,0.263075,0.792267,-0.828495,-0.139517,0.361331,-0.380324,-0.429904,0.065207,-0.593262,0.221486,0.339534,-0.356140,0.013242,-0.102916,-0.377389,-0.153239,-0.355435,we have performed assurance work in accordance...
4,-0.101012,-0.128166,0.079305,-0.036931,-0.442384,-0.308575,-0.117051,0.216605,0.056395,0.096633,0.048609,-0.083820,0.483068,-0.143563,-0.154515,-0.315368,-0.593597,details of the remuneration systems can be fou...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,0.430432,0.144562,-0.305678,-0.167963,-0.575168,-0.566713,0.216612,0.076034,-0.170257,0.751549,1.208563,0.663282,-0.694872,-0.174470,0.160286,-0.478944,0.336585,with womenhr our company offers female employe...
307,0.045939,-0.067887,-0.274500,0.648892,-0.299638,1.064378,-0.630490,-0.725866,-0.130819,0.544327,-0.021380,-0.811103,-0.803566,0.572896,0.091027,-0.090289,0.320123,the executive directors calculate the amount o...
308,0.078355,-0.156455,-0.360638,-0.090083,-0.198462,0.335942,-0.630833,0.059404,-0.328543,0.170279,-0.059474,-0.299028,0.133634,0.208675,-0.091059,-0.378323,-0.434744,bearer debt securities and other fixedincome s...
309,-0.098156,-0.226462,0.223122,-0.342644,-0.550392,-0.380272,-0.347808,0.491536,0.006598,-0.051433,0.310545,-0.100136,0.131067,-0.229777,0.400582,-0.222315,-0.832760,pricewaterhousecoopers gmbh wirtschaftsprüfung...
310,0.107621,-0.231704,-0.308495,-0.245243,-0.456187,0.223237,-0.530745,0.134370,-0.238553,0.261504,0.023300,0.014721,0.122936,0.209819,-0.026740,-0.488119,-0.372102,we conducted our audit of the annual financial...

In [118]:
df[scores].max(1).shape

(311,)

In [119]:
df[scores].T.shape

(17, 311)

In [120]:
df[(df[scores].T == df[scores].max(1)).T]

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,NaN,NaN,NaN,NaN,NaN,1.099860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,1.090008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.820925,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,0.792267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.483068,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.208563,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,NaN,NaN,NaN,NaN,NaN,1.064378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,NaN,NaN,NaN,NaN,NaN,0.335942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.491536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.261504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df = df[(df[scores].T == df[scores].max(1)).T]
df["Sentences"] = sentences
df

,F,C,NO_CLASS,M,L,H,P,G,D,J,Q,I,N,E,K,A,B,Sentences
0,NaN,NaN,NaN,NaN,NaN,1.099860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,as at december the company held shares in affi...
1,NaN,NaN,NaN,NaN,NaN,1.090008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chairwoman of the board of directors hannover ...
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.820925,NaN,NaN,NaN,NaN,NaN,NaN,on march hannover re placed further subordinat...
3,NaN,0.792267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,we have performed assurance work in accordance...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.483068,NaN,NaN,NaN,NaN,details of the remuneration systems can be fou...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.208563,NaN,NaN,NaN,NaN,NaN,NaN,with womenhr our company offers female employe...
307,NaN,NaN,NaN,NaN,NaN,1.064378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,the executive directors calculate the amount o...
308,NaN,NaN,NaN,NaN,NaN,0.335942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bearer debt securities and other fixedincome s...
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.491536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pricewaterhousecoopers gmbh wirtschaftsprüfung...
310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.261504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,we conducted our audit of the annual financial...

In [ ]:
df.mean()

F            0.548879
C            0.664623
NO_CLASS          NaN
M                 NaN
L                 NaN
H            0.804783
P            0.689872
G            0.583012
D                 NaN
J            0.484441
Q            0.696842
I            0.604747
N            0.603874
E                 NaN
K            0.342283
A                 NaN
B            0.757923
Sentences         NaN
dtype: object

In [88]:
scores = df.columns.drop("Sentences")

In [89]:
df[scores].mean(0).sort_values(ascending=False)

H           0.804783
B           0.757923
Q           0.696842
P           0.689872
C           0.664623
I           0.604747
N           0.603874
G           0.583012
F           0.548879
J           0.484441
K           0.342283
NO_CLASS         NaN
M                NaN
L                NaN
D                NaN
E                NaN
A                NaN
dtype: float64

In [90]:
recordings = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/results/BERT_classification/dataset__stoxx_600_sentence_len_6__nace_level_1/recordings.csv")

In [91]:
json.loads(recordings["classification_lvl_1"][0])

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [ ]:
l = []
for i in range(len(recordings)): 
    d = ast.literal_eval(recordings["classification_lvl_1"][i])
    print(list(d.items())[0][0][0])
    l.append(list(d.items())[0][0][0])

J
J
J
H
G
H
J
Q
Q
Q
Q
H
Q
Q
H
Q
J
J
H
Q
N
Q
Q
H
H
G
Q
Q
H
Q
H
Q
N
Q
N
H
G
Q
H
Q
Q
H
Q
Q
H
J
Q
H
H
Q
J
J
N
Q
Q
Q
Q
G
G
Q
G
N
Q
H
Q
H
K
Q
H
Q
Q
Q
Q
G
Q
H
Q
J
Q
Q
Q
G
Q
Q
Q
G
H
J
J
Q
H
Q
N
J
Q
H
H
Q
Q
N
J
N
Q
Q
N
Q
J

In [ ]:
pd.Series(l).value_counts()

Q    50
H    23
J    15
G     9
N     9
K     1
Name: count, dtype: int64

In [ ]:
recordings["classification_lvl_1"]

0      {'J_INFORMATION AND COMMUNICATION': 0.39629662...
1      {'J_INFORMATION AND COMMUNICATION': 0.33750051...
2      {'J_INFORMATION AND COMMUNICATION': 0.35369017...
3      {'H_TRANSPORTATION AND STORAGE': 0.38912087678...
4      {'G_WHOLESALE AND RETAIL TRADE; REPAIR OF MOTO...
                             ...
102    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
103    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
104    {'N_ADMINISTRATIVE AND SUPPORT SERVICE ACTIVIT...
105    {'Q_HUMAN HEALTH AND SOCIAL WORK ACTIVITIES': ...
106    {'J_INFORMATION AND COMMUNICATION': 0.39572551...
Name: classification_lvl_1, Length: 107, dtype: object