In [2]:
import numpy as np
import pandas as pd
import os
import sys
import glob
import tqdm
import re
import json
from typing import List
wor_dir = "/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis"
os.chdir(wor_dir)
sys.path.append("../../benchmark")
import test_base
from sentence_splitter import split_text_into_sentences
from BERT_classifier.Classify_report_with_BERT import classification_report_BERT
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [3]:
sentence_length = 6

## Test using a BERT-Classification Model trained on paragraphs to classify an entire report.

**Function:** pdf -> NACE Class

In [4]:
dataset_path = "data/datasets/german_annual_reports"
dataset_path = "data/datasets/stoxx_600_extended"
dataset_path = "data/datasets/reports_subset_from_full_data_1"
dataset_path = "data/datasets/reports_subset_from_full_data_3"
dataset_path = "data/datasets/stoxx_600"

In [5]:
over_view_df_path = os.path.join(dataset_path, os.path.basename(dataset_path) + "_overview.csv")

dataset_path_texts = os.path.join(dataset_path, "TXTs")

dataset_name = os.path.basename(dataset_path)

In [6]:
nace_classes = pd.read_csv(over_view_df_path, index_col=0, sep=";")
nace_classes.head()

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
483,3i Group plc,III-GB,III-GB,701.210162,1276.962137,NaN,66.30,K,NaN,NaN
354,A.P. Moller - Maersk A/S Class B,MAERSK.B-DK,MAERSK.B-DK,77568.022858,47226.219381,51288.2262335699,50.20,H,NaN,NaN
275,A2A S.p.A.,A2A-IT,A2A-IT,22938.000000,14492.000000,NaN,35.11,D,NaN,NaN
107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
122,Aalberts N.V.,AALB-NL,AALB-NL,3230.000000,3324.000000,3148.6,25.93,C,Aalberts N.V.1.pdf,NaN

In [7]:

nace_classes

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
483,3i Group plc,III-GB,III-GB,701.210162,1276.962137,NaN,66.30,K,NaN,NaN
354,A.P. Moller - Maersk A/S Class B,MAERSK.B-DK,MAERSK.B-DK,77568.022858,47226.219381,51288.2262335699,50.20,H,NaN,NaN
275,A2A S.p.A.,A2A-IT,A2A-IT,22938.000000,14492.000000,NaN,35.11,D,NaN,NaN
107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
122,Aalberts N.V.,AALB-NL,AALB-NL,3230.000000,3324.000000,3148.6,25.93,C,Aalberts N.V.1.pdf,NaN
...,...,...,...,...,...,...,...,...,...,...
577,WPP Plc,WPP-GB,WPP-GB,16910.961740,17068.346685,17413.6933169365,73.11,M,NaN,NaN
114,Yara International ASA,YAR-NO,YAR-NO,22742.705923,14273.219511,12820.6705029309,20.15,C,Yara International ASA2.pdf,NaN
344,Zalando SE,ZAL-DE,ZAL-DE,10344.800000,10143.100000,10572.5,47.91,G,NaN,NaN
246,Zealand Pharma A/S,ZEAL-DK,ZEAL-DK,13.977698,46.005625,8.40500161716342,21.20,C,NaN,NaN
442,Zurich Insurance Group Ltd,ZURN-CH,ZURN-CH,41393.017468,72341.013163,78985.6071849965,65.11,K,Zurich Insurance Group Ltd2.pdf,NaN

In [8]:
report_to_nace_class = nace_classes.dropna(subset=["Report"]).set_index('Report').to_dict()["NACE"]
report_to_nace_class = {report[0][:-4] + ".txt": report[1] for report in report_to_nace_class.items()}
len(report_to_nace_class)

291

In [9]:
reports_path = glob.glob(os.path.join(dataset_path, "PDFs/*.pdf"))
len(reports_path)

261

In [10]:
reports_path = glob.glob(os.path.join(dataset_path_texts, "*.txt"))
len(reports_path)

263

In [11]:
## ! Only filter the description pages !

nace_classes_description_pages = nace_classes.dropna(subset="description_page")
nace_classes_description_pages
description_page_path = "data/datasets/stoxx_600/company_descriptions_txt/"
reports_path = [description_page_path + name.replace("pdf", "txt") for name in nace_classes_description_pages["Report"].to_list()]

In [12]:
def get_tables(lines: list): 
    tables = []
    current_table = []

    for line in lines:
        if line.strip().startswith("|"):  # line belongs to a table
            current_table.append(line.strip())
        else:
            if current_table:  # table ended
                tables.append("\n".join(current_table))
                current_table = []

    # catch last table if file ends without empty lines
    if current_table:
        tables.append("\n".join(current_table))

    return tables

def preprocess_report(pdf_path: str) -> List[str]:

    with open(pdf_path, "r") as f: 
        text = f.read()
    
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]

    tables = get_tables(lines)

    # drop if condidtion is True
    conditions = [
        # filter images
        lambda line: line == '<!-- image -->',
        
        #filter tables 
        lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False, 

        # filter headers
        #lambda line: line.strip()[0] == "#" if len(line) > 0 else True,

        # filter sentences
        #lambda line: "." not in line,
        
        # more than 50% is numbers
        lambda line: sum(ch.isalpha() for ch in line) / len(line) < 0.5,

        # minimum 3 words 
        lambda line: len(re.sub(r"[^a-zA-ZäöüÄÖÜß\s]", '', line).strip().split(" ")) < 3,

        # Minimum 2 Sentences
        #lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

    ]
    accepted_lines = [line for line in lines if not any(condition(line) for condition in conditions)]
    accepted_lines += tables

    chunks = []

    for line in accepted_lines: 
        sentences = split_text_into_sentences(line, language='en')
        sentences = [sentence.strip() for sentence in sentences]
        sentences = [sentence for sentence in sentences if sentence != ""]
        new_chunks = [(" ".join(sentences[i:i+sentence_length])).strip() for i in range(0, len(sentences), 3)]

        chunks += new_chunks
    
    if len(chunks) == 0: 
        return []
    elif len(chunks) == 1: 
        return chunks

    # if there is only one sentence in the last chunk, balance the two last chunks
    if len(split_text_into_sentences(chunks[-1], language = "en")) == 1: 
        last_two_chunks = chunks[-2] + " " + chunks[-1]
        chunks[-2] = last_two_chunks[0:(len(last_two_chunks) + 1) // 2]
        chunks[-1] = last_two_chunks[(len(last_two_chunks) + 1) // 2: (len(last_two_chunks)) - (len(last_two_chunks) + 1) // 2]

    chunks = [re.sub(r'\b\d+\.\d+\b', '', chunk) for chunk in chunks]
    chunks = [re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", '', chunk) for chunk in chunks]
    chunks = [re.sub(r"\s+", " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'\.{2,}', " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'^\d+\.\s*', " ", chunk) for chunk in chunks]
    chunks = [chunk.lower() for chunk in chunks]
    chunks = [chunk.strip() for chunk in chunks]

    return chunks

In [13]:
model_version = "2_1"
model_version = "1_0"
model_version = "1_1"
if model_version == "1_0":
    ckpt = wor_dir + "/results/BERT_models/results_null_classifiers__cos_thres_0.5__bert-base-uncased__train_full_model__some_labels/checkpoint-2331"
    num_layers = 1
elif model_version == "1_1":
    ckpt = wor_dir + "/results/BERT_models/results__new_approach_data__num_layers_2__cos_thres_0.5bert-base-uncased__train_full_model__some_labels__only_labels/checkpoint-6240"
    num_layers = 2
elif model_version == "2_1":
    ckpt = wor_dir + "/results/BERT_models/_best_2nd_results__new_approach_data__num_layers_2__cos_thres_0.5bert-base-uncased__train_full_model__some_labels/checkpoint-4800"
    num_layers = 2

model = classification_report_BERT.load_custom_bert_from_checkpoint(ckpt_path=ckpt, num_layers_base=num_layers)
tokenizer = AutoTokenizer.from_pretrained(ckpt)

In [14]:
for i in range(1,2):
    nace_level = i
    result_path = wor_dir + f"/results/BERT_classification/model_{model_version}__desc_pages__with_relevancy__dataset__{dataset_name}_sentence_len_{sentence_length}__nace_level_{nace_level}"
    os.makedirs(result_path, exist_ok=True)
    config = {"model": ckpt, "dataset": dataset_name}
    with open(os.path.join(result_path, "config.json"), "w") as f: 
        json.dump(config, f)

    res = test_base.test_report_classification(
        reports_path=reports_path,
        preprocess_report=preprocess_report, 
        report_to_nace_class=report_to_nace_class, 
        result_path = result_path,
        level=i,
        overwrite=True, 
        classification_function=classification_report_BERT.classify_report, 
        path_nace_code_descriptions="data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", 
        model=model,
        tokenizer=tokenizer)

  0%|                                                                                                                                                                                          | 0/63 [00:00<?, ?it/s]

data/datasets/stoxx_600/company_descriptions_txt/AAK AB1.txt

  2%|██▊                                                                                                                                                                               | 1/63 [00:01<01:25,  1.37s/it]

data/datasets/stoxx_600/company_descriptions_txt/ABB Ltd.2.txt

  3%|█████▋                                                                                                                                                                            | 2/63 [00:02<01:11,  1.16s/it]

data/datasets/stoxx_600/company_descriptions_txt/Accelleron Industries AG1.txt

  5%|████████▍                                                                                                                                                                         | 3/63 [00:02<00:46,  1.30it/s]

data/datasets/stoxx_600/company_descriptions_txt/Acciona SA2.txt
data/datasets/stoxx_600/company_descriptions_txt/Accor SA1.txt

  8%|██████████████▏                                                                                                                                                                   | 5/63 [00:03<00:29,  2.00it/s]

data/datasets/stoxx_600/company_descriptions_txt/Ackermans & van Haaren NV1.txt

 10%|████████████████▉                                                                                                                                                                 | 6/63 [00:04<00:38,  1.48it/s]

data/datasets/stoxx_600/company_descriptions_txt/Adecco Group AG1.txt

 11%|███████████████████▊                                                                                                                                                              | 7/63 [00:04<00:35,  1.56it/s]

data/datasets/stoxx_600/company_descriptions_txt/Admiral Group plc1.txt

 13%|██████████████████████▌                                                                                                                                                           | 8/63 [00:07<01:04,  1.17s/it]

data/datasets/stoxx_600/company_descriptions_txt/Airbus SE1.txt

 14%|█████████████████████████▍                                                                                                                                                        | 9/63 [00:10<01:30,  1.67s/it]

data/datasets/stoxx_600/company_descriptions_txt/Alcon AG1.txt

 16%|████████████████████████████                                                                                                                                                     | 10/63 [00:10<01:11,  1.35s/it]

data/datasets/stoxx_600/company_descriptions_txt/Allfunds Group plc1.txt

 17%|██████████████████████████████▉                                                                                                                                                  | 11/63 [00:11<01:01,  1.19s/it]

data/datasets/stoxx_600/company_descriptions_txt/Allreal Holding AG1.txt

 19%|█████████████████████████████████▋                                                                                                                                               | 12/63 [00:12<01:02,  1.22s/it]

data/datasets/stoxx_600/company_descriptions_txt/ANDRITZ AG1.txt

 21%|████████████████████████████████████▌                                                                                                                                            | 13/63 [00:14<01:01,  1.22s/it]

data/datasets/stoxx_600/company_descriptions_txt/Anglo American plc1.txt

 22%|███████████████████████████████████████▎                                                                                                                                         | 14/63 [00:15<01:01,  1.26s/it]

data/datasets/stoxx_600/company_descriptions_txt/Anheuser-Busch InBev SANV3.txt

 24%|██████████████████████████████████████████▏                                                                                                                                      | 15/63 [00:16<00:58,  1.22s/it]

data/datasets/stoxx_600/company_descriptions_txt/Antofagasta plc1.txt

 25%|████████████████████████████████████████████▉                                                                                                                                    | 16/63 [00:17<00:48,  1.03s/it]

data/datasets/stoxx_600/company_descriptions_txt/Arcadis NV1.txt

 27%|███████████████████████████████████████████████▊                                                                                                                                 | 17/63 [00:17<00:41,  1.12it/s]

data/datasets/stoxx_600/company_descriptions_txt/argenx SE1.txt

 29%|██████████████████████████████████████████████████▌                                                                                                                              | 18/63 [00:18<00:33,  1.33it/s]

data/datasets/stoxx_600/company_descriptions_txt/Arkema SA1.txt

 32%|████████████████████████████████████████████████████████▏                                                                                                                        | 20/63 [00:19<00:24,  1.73it/s]

data/datasets/stoxx_600/company_descriptions_txt/Ashtead Group plc1.txt
data/datasets/stoxx_600/company_descriptions_txt/ASM International N.V.1.txt
data/datasets/stoxx_600/company_descriptions_txt/ASR Nederland N.V.1.txt

 35%|█████████████████████████████████████████████████████████████▊                                                                                                                   | 22/63 [00:20<00:25,  1.62it/s]

data/datasets/stoxx_600/company_descriptions_txt/Assicurazioni Generali S.p.A.1.txt
data/datasets/stoxx_600/company_descriptions_txt/Associated British Foods plc1.txt

 38%|███████████████████████████████████████████████████████████████████▍                                                                                                             | 24/63 [00:20<00:18,  2.14it/s]

data/datasets/stoxx_600/company_descriptions_txt/AstraZeneca PLC1.txt
data/datasets/stoxx_600/company_descriptions_txt/Auto Trader Group PLC3.txt

 41%|█████████████████████████████████████████████████████████████████████████                                                                                                        | 26/63 [00:21<00:13,  2.72it/s]

data/datasets/stoxx_600/company_descriptions_txt/Avanza Bank Holding AB1.txt

 43%|███████████████████████████████████████████████████████████████████████████▊                                                                                                     | 27/63 [00:21<00:14,  2.56it/s]

data/datasets/stoxx_600/company_descriptions_txt/Aviva plc1.txt

 44%|██████████████████████████████████████████████████████████████████████████████▋                                                                                                  | 28/63 [00:22<00:13,  2.64it/s]

data/datasets/stoxx_600/company_descriptions_txt/AXA SA1.txt

 48%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                            | 30/63 [00:23<00:12,  2.60it/s]

data/datasets/stoxx_600/company_descriptions_txt/BAE Systems plc1.txt
data/datasets/stoxx_600/company_descriptions_txt/Bakkafrost PF2.txt

 49%|███████████████████████████████████████████████████████████████████████████████████████                                                                                          | 31/63 [00:23<00:12,  2.58it/s]

data/datasets/stoxx_600/company_descriptions_txt/Balfour Beatty plc1.txt

 51%|█████████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 32/63 [00:24<00:14,  2.21it/s]

data/datasets/stoxx_600/company_descriptions_txt/Bank of Ireland Group Plc1.txt

 52%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 33/63 [00:25<00:21,  1.39it/s]

data/datasets/stoxx_600/company_descriptions_txt/Banque Cantonale Vaudoise1.txt

 54%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 34/63 [00:26<00:21,  1.37it/s]

data/datasets/stoxx_600/company_descriptions_txt/Barry Callebaut AG3.txt

 57%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                           | 36/63 [00:27<00:15,  1.72it/s]

data/datasets/stoxx_600/company_descriptions_txt/Bavarian Nordic AS1.txt
data/datasets/stoxx_600/company_descriptions_txt/Bellway p.l.c.1.txt

 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                         | 37/63 [00:27<00:16,  1.62it/s]

data/datasets/stoxx_600/company_descriptions_txt/BKW AG1.txt

 60%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 38/63 [00:28<00:14,  1.77it/s]

data/datasets/stoxx_600/company_descriptions_txt/Boliden AB1.txt

 62%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                   | 39/63 [00:28<00:12,  1.86it/s]

data/datasets/stoxx_600/company_descriptions_txt/Bollore SE1.txt

 63%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                | 40/63 [00:29<00:15,  1.44it/s]

data/datasets/stoxx_600/company_descriptions_txt/Brenntag Societas Europaea1.txt

 65%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 41/63 [00:30<00:12,  1.79it/s]

data/datasets/stoxx_600/company_descriptions_txt/Bridgepoint Group Plc1.txt
data/datasets/stoxx_600/company_descriptions_txt/Cembra Money Bank AG1.txt

 68%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 43/63 [00:30<00:09,  2.06it/s]

data/datasets/stoxx_600/company_descriptions_txt/Chocoladefabriken Lindt & Spruengli AG2.txt

 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                     | 44/63 [00:32<00:12,  1.46it/s]

data/datasets/stoxx_600/company_descriptions_txt/Coca-Cola HBC AG2.txt

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 45/63 [00:32<00:12,  1.41it/s]

data/datasets/stoxx_600/company_descriptions_txt/COMET Holding AG1.txt
data/datasets/stoxx_600/company_descriptions_txt/ConvaTec Group Plc1.txt

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                             | 47/63 [00:33<00:08,  1.97it/s]

data/datasets/stoxx_600/company_descriptions_txt/Danone SA1.txt

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 48/63 [00:34<00:08,  1.84it/s]

data/datasets/stoxx_600/company_descriptions_txt/Dassault Aviation SA1.txt

 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 49/63 [00:34<00:07,  1.82it/s]

data/datasets/stoxx_600/company_descriptions_txt/DCC Plc1.txt

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 50/63 [00:35<00:08,  1.58it/s]

data/datasets/stoxx_600/company_descriptions_txt/Derwent London PLC REIT1.txt

 81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 51/63 [00:36<00:07,  1.69it/s]

data/datasets/stoxx_600/company_descriptions_txt/Deutsche Bank Aktiengesellschaft1.txt

 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 52/63 [00:37<00:09,  1.10it/s]

data/datasets/stoxx_600/company_descriptions_txt/Deutsche Lufthansa AG1.txt

 84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 53/63 [00:38<00:08,  1.12it/s]

data/datasets/stoxx_600/company_descriptions_txt/Diageo PLC1.txt

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 54/63 [00:39<00:07,  1.15it/s]

data/datasets/stoxx_600/company_descriptions_txt/DiaSorin S.p.A.1.txt

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 55/63 [00:40<00:08,  1.06s/it]

data/datasets/stoxx_600/company_descriptions_txt/Direct Line Insurance Group Plc1.txt

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 56/63 [00:41<00:06,  1.06it/s]

data/datasets/stoxx_600/company_descriptions_txt/DSM-Firmenich AG1.txt

 90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 57/63 [00:42<00:05,  1.03it/s]

data/datasets/stoxx_600/company_descriptions_txt/Merck KGaA2.txt

 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 59/63 [00:43<00:02,  1.51it/s]

data/datasets/stoxx_600/company_descriptions_txt/Orkla ASA1.txt
data/datasets/stoxx_600/company_descriptions_txt/Scout24 SE3.txt

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 60/63 [00:44<00:02,  1.10it/s]

data/datasets/stoxx_600/company_descriptions_txt/Severn Trent Plc1.txt

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 61/63 [00:45<00:01,  1.26it/s]

data/datasets/stoxx_600/company_descriptions_txt/Siemens Energy AG1.txt

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 62/63 [00:46<00:00,  1.30it/s]

data/datasets/stoxx_600/company_descriptions_txt/Signify NV3.txt

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:46<00:00,  1.34it/s]

In [15]:
def softmax(x):
    e = np.exp(x - np.max(x))   # subtract max for numerical stability
    return e / e.sum()

In [16]:
df = pd.read_csv("results/BERT_classification/model_1_1__desc_pages__with_relevancy__dataset__stoxx_600_sentence_len_6__nace_level_1/Siemens Energy AG1.txt/Siemens Energy AG1.txt_classifications.csv")

In [17]:
scores = ['K', 'P', 'I', 'F', 'L', 'J', 'E', 'Q', 'B', 'D', 'A', 'H', 'M', 'G', 'C']

In [18]:
df.loc[:,"classification"] = [str(row.sort_values(ascending=False).to_dict()) for i, row in df[scores].apply(softmax, axis=1).iterrows()]

In [19]:
df.loc[0,"classification"]

"{'M': 0.9923605928892378, 'F': 0.0029998710186998974, 'C': 0.0009449491860713078, 'K': 0.0008007685486060554, 'J': 0.0004997021788788219, 'G': 0.000495891890189294, 'P': 0.00046945749140778865, 'Q': 0.0003521442087661222, 'E': 0.0002670324855598185, 'I': 0.00025786005714058057, 'D': 0.00018081801673530733, 'B': 0.00016571749330049446, 'H': 0.0001286617154597945, 'L': 6.741033246666465e-05, 'A': 9.122487480155394e-06}"