### Create Training data for binary classification: description of business sector - True False

In [98]:
import pandas as pd
import glob
import os
import ast
import json

import numpy as np
import pandas as pd
import os
import sys
import glob
import tqdm
import re
import random
from typing import List
from sklearn.model_selection import train_test_split

sys.path.append("../../")
from sentence_splitter import split_text_into_sentences
#from BERT_classifier.Classify_report_with_BERT import classification_report_BERT
#from transformers import AutoModelForSequenceClassification, AutoTokenizer

#### Load Positives

In [10]:
positives_json_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/JSONs"

In [11]:
df_overview = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/stoxx_600_overview.csv", sep=";")
df_positives = df_overview[df_overview["description_page"].notna()]
df_positives

,Unnamed: 0,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
3,107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
6,94,ABB Ltd.,ABBN-CH,ABBN-CH,28073.948473,29665.651960,30586.3762461154,27.11,C,ABB Ltd.2.pdf,18
9,135,Accelleron Industries AG,ACLN-CH,ACLN-CH,742.680345,846.217532,NaN,28.11,C,Accelleron Industries AG1.pdf,7
10,296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7
11,365,Accor SA,AC-FR,AC-FR,4224.000000,5056.000000,5606,55.10,I,Accor SA1.pdf,5
...,...,...,...,...,...,...,...,...,...,...,...
394,69,Orkla ASA,ORK-NO,ORK-NO,5774.960695,5932.590483,6073.67720031738,10.89,C,Orkla ASA1.pdf,11
466,598,Scout24 SE,G24-DE,G24-DE,447.539000,509.114000,s,96.09,S,Scout24 SE3.pdf,41
472,286,Severn Trent Plc,SVT-GB,SVT-GB,2505.264229,2709.430915,NaN,36.00,E,Severn Trent Plc1.pdf,8
479,133,Siemens Energy AG,ENR-DE,ENR-DE,29005.000000,31119.000000,34465,27.33,C,Siemens Energy AG1.pdf,5
482,30,Signify NV,LIGHT-NL,LIGHT-NL,7514.000000,6704.000000,6143,27.40,C,Signify NV3.pdf,6

In [12]:
for i, row in df_positives.iterrows(): 
    path = row["Report"].replace(".pdf", ".json")
    with open(os.path.join(positives_json_path, path), "r") as f: 
        report_json = json.load(f)
    
    description_pages = ast.literal_eval(row["description_page"])
    description_pages = [description_pages] if isinstance(description_pages, int) else description_pages

    description_text = ""
    for description_page in description_pages:

        description_text += list(filter(lambda x: x["page"] == description_page + 1, report_json["pages"]))[0]["markdown"]

    print(row["Report"])
    print(description_text)
    print("-----" * 5 + "\n"*6)

    df_positives.loc[i, "Description"] = description_text

AAK AB1.pdf
## we do is about Making Better Happen ™ Everything

AAK specializes in plant-based oils and fats, the value-adding ingredients in many products people love to consume. We make these products better tasting, healthier, and more sustainable. In addition, we enhance their sensory experience - by giving the silkier mouthfeel in premium chocolate, the juicier texture in a plant-based burger, and a puffier appearance in a lower-fat pastry.

We can also optimize our customers' production and processes by substituting existing ingredients with plantbased equivalents that improve efficiency and enhance the performance and sustainability of the end product. AAK's value-adding solutions enable our customers to Making Better Happen ™ .

At the heart of AAK's offer is customer co-development, combining our desire to understand what Making Better Happen ™  means for each customer with the unique flexibility of our production assets and deep knowledge of products and industries, including Chocolate &amp; Confectionery, Bakery, Dairy, Plant-based Foods, Special Nutrition, Foodservice, and Personal Care. Our 4,000 employees support our close collaboration with customers through 25 regional sales offices, 16 dedicated Customer Innovation Centers, and with the support of more than 20 production facilities.

Listed on Nasdaq Stockholm and headquartered in Malmö, Sweden, AAK has been Making Better Happen ™ for 150 years.
-------------------------






ABB Ltd.2.pdf
-

## Who we are

ABB has a history of innovation excellence stretching back more than 130 years with 70+ years of manufacturing in India. Today, we are a leading global technology company that enables a more sustainable and resource-efficient future with our technology leadership in electrification and automation.

Our strong heritage as a technology pioneer has led to long-lasting relationships with many of our customers and given us a deep understanding of market needs and the ability to anticipate and drive trends.

Our solutions connect engineering know-how and software to optimize how things are manufactured, moved, powered and operated. Building on our heritage of excellence, ABB's ~105,000 employees are committed to driving innovations that accelerate industrial transformation.

## Our Electrification business area

provides leading electrical distribution and management technologies, solutions and services to electrify the world in a safe, smart and sustainable way. The portfolio includes mediumand low-  voltage electrical components, switchgear, digital devices, enclosures, breakers, power conversion products and charging solutions for electric vehicles, among others. With our products, solutions and services, we collaborate with customers to improve power delivery and security, enhance energy management, efficiency and operational reliability, as we seek to achieve a lowcarbon society for the benefit of society and the planet.

Our Motion business area keeps the world turning - while saving energy every day. We innovate and push the boundaries of technology to enable the low-carbon future for customers, industries and societies. With our digitally enabled drives, motors and services our customers and   partners achieve better performance, safety and reliability. We offer a combination of domain expertise and technology to deliver the optimum drive and motor solution for a wide range of applications in all   industrial segments.

## Our Process Automation business area

is the leading supplier of integrated automation, electrical and digital solutions for the process, hybrid and maritime industries. It enables customers to operate some of the largest and most complex industrial infrastructure essential to modern life and run them more safely, intelligently and sustainably. The portfolio includes ABB's market-leading distributed control system, industrial software, advanced sensing, as well as industry-specific anchor products.

## Our Robotics &amp; Discrete Automation

business area is the only business that offers a comprehensive and integrated portfolio covering robots, autonomous mobile robots and machine automation solutions, designed and orchestrated by our value-  creating software. The business area helps companies of all sizes and sectors - from auto  motive to electronics and   logistics - become more resilient, flexible and efficient.
-------------------------






Accelleron Industries AG1.pdf
## Accelleron at a glance

Accelleron's technology gives engines an extra boost in performance with the main purpose of improving their fuel efficiency and thus reducing their environmental impact by generating fewer emissions. The Company designs, manufactures, sells and services highly customized turbochargers for heavy-duty applications.

<!-- image -->

Accelleron reports its business in two segments: Medium &amp; Low Speed and High Speed. They both cover product business as well as the integrated service business. From an operating perspective, the business is organized in four operating divisions: two product divisions, one service division and one digital customer solutions division.

As a focused specialist with a comprehensive product and service range, Accelleron produces heavy-duty turbochargers varying from 100kg to 10 metric tons, from 500 kW to 30,000 kW. All main markets from Marine and Energy to

Off-Highway Vehicles are exposed to the megatrends of decarbonization and digitalization, both of which provide vast opportunities.

With its products, Accelleron is the undisputed leader in turbocharging mission-critical applications. The Company's operations are based on a foundation of almost a century of making significant and continuous investments in technology, partnerships with original equipment manufacturers (OEMs) and end-users and an unrivalled global service network with a unique service culture that will never let customers down.

<!-- image -->
-------------------------






Acciona SA2.pdf
## 2. BUSINESS MODEL: BUSINESS AS UNUSUAL

ACCIONA's business model is reflected in  every  action  and  project  the  company undertakes. Applying the Business as Unusual approach to infrastructure development,  it  responds  to  the  challenges  facing  our  planet  with  a  long-term vision, always seeking a positive impact on both people and the planet.

<!-- image -->

<!-- image -->

## Energy

- -Over 300 TWh produced
- -EBITDA €1,653 billion (+52% vs. 2021)
- -13.2 million tCO 2 avoided through renewable generation
- -23,910 GWh of renewable electricity generated

<!-- image -->

## Infraestructures

- -Total portfolio €22.02 billion
- -EBITDA €369 million (+14,2% vs. 2021)
- -1,149 Hm³ of treated water
- -Management of 85 water treatment plants
- -6,000 km of roads built in the last ten years
- -600 bridges built

## PERFORMANCE

<!-- image -->

## Real Estate

- -Portfolio of 617 units (+39,2% vs. 2021)
- -Total assests valued at €1,541 billion (+13,2% vs. 2021)
- -10 millionde m² of residential, commercial industrial and office buildings

<!-- image -->

## Urban Mobility

- -+12,000 Silence vehicles sold (43% vs. 2021)
- -+12,400 scooters shared

<!-- image -->

## Bestinver

- -€5,472 billion of assets managed

## IMPACT

Shareholders

- Skateholders

1

3

A new sector

<!-- image -->

4

The world in constant transformation

5

ACCIONA Solutions in 2022

<!-- image -->

6

Governance

7

About this report

<!-- image -->

8

Annex: Cash fiows social 2022

Index

Letter from the Chairman

2

## Business model: Business as unusual
-------------------------






Accor SA1.pdf
## Message from Sébastien Bazin, Chairman and Chief Executive Officer

2022 was the year optimism returned for the travel industry, and Accor thrived. Leisure and domestic travel are back stronger than ever, international travel is gathering momentum, and Accor's own activity was very strong, outpacing 2019 levels. This is a tribute to the fundamental strengths of the Group, to our solid partnership with our owners and partners, and above all, a tribute to our teams' incredible spirit and tenacity, which drive the Accor vision.

Our brand portfolio remains unmatched and we pursued our global expansion in 2022, signing significant development agreements in China, unveiling the Orient Express train and opening 300 new hotels. We are continuously evolving to best accelerate our growth and support our owners and network, and our decision to organize the Group into two dedicated divisions reinforces our focus and positions us to fully reap the benefits of our expertise, brands, and market leadership.

The future of hospitality goes far beyond the hotel room, it's also about unlocking inspired experiences and capturing ever-changing guest needs, and we continued to create unique moments and diversify our offerings in 2022. We enriched our F&amp;B concepts, participated in major events such as the 2022 World Cup with The Living Adventure, reopened the famous Lido in Paris, strengthened our powerful loyalty program ALL and booking platform, and made exciting plans for the Olympic and Paralympic Games Paris 2024. Our augmented hospitality vision naturally extends to our owners and partners' experiences, and we continued investing in our fully holistic ecosystem to deliver and support their needs.

The future of hospitality must also be responsible, respectful and with sustainability at its heart. Accor is committed to building a hospitality model where we contribute more than we take. In 2022, we delivered great achievements in our sustainable journey, including eliminating single-use plastic in the guest experience in more than 80% of our hotels, and are working hand in hand with all stakeholders to achieve meaningful change. It's a question of mindset, vision, and determination. I'm convinced we share these.

Also more than ever critical to hospitality is our people. We are continuing to focus on what matters most to me, taking care of and empowering our 290,000+ Talents, and we are deeply committed to recruitment, development and training. To care for one another is the very essence of hospitality, and at Accor we embrace this purpose wholeheartedly.

## We are poised to boldly move forward and further strengthen our leadership as the most attractive and innovative hospitality Group.

I am proud of Accor's achievements and saluting them would not be complete without a tribute to Accor co-founder Gérard Pélisson. His recent passing filled us with great sadness - Gérard was a true entrepreneur, reinventing hospitality and making a global impact that continues to live on and be a source of inspiration.

Looking ahead, I am confident that, together, we can go even further in 2023 and build on these tailwinds and on the legacy of Accor's founders. We are poised to boldly move forward to further strengthen our leadership as the most attractive and innovative hospitality Group. We have the people, we have the brands, we have the ambition and the focus. Now is the time to do what we do best, seize the opportunity and build an even stronger future ahead.
-------------------------






Ackermans & van Haaren NV1.pdf
## Ackermans &amp; van Haaren

-  is an independent, diversified group established in 1876,
-  listed on Euronext Brussels since 1984 (BEL20 and BEL ESG) and with solid family ties,
-  led by an experienced, multidisciplinary team,
-  using its own resources to invest,
-  in a balanced combination of a limited number of strategic longterm participations and a diversified portfolio of growth capital investments.

## Long-term perspective

-  We make clear agreements with our participations regarding strategic, operational and financial goals;
-  guided by our long-term strategy, we are prepared to help finance strategic projects of our participations through capital increases;
-  our participations remain responsible for their own financial position;
-  we strive for annual recurring growth of the results of each participation and of the group as a whole.

## Growth

-  We are a group of entrepreneurs with the ambition to build leading companies through internationalisation, innovation and diversification in the long term;
-  we  create  long-term  shareholder  value  thanks  to  a  recurring  increase  of  the  consolidated  shareholders'  equity,  supported  by  a steady long-term dividend growth;
-  we focus on recurring growth of the activities, long-term growth of the operating cash flow and shareholders' equity of the participations, rather than on absolute profitability targets or short-term dividend maximisation.

## Active ownership

-  We are proud of a successful track record of partnerships with families, co-shareholders and management teams;
-  we invest in both majority and minority interests on the basis of balanced shareholder agreements;
-  our experienced investment managers are actively involved in the governing bodies of the participations, assisted where necessary by external consultants and/or independent directors;
-  we are a networked organisation, based on a diversity of personalities and backgrounds and on a permanent exchange of best practices between the group companies;
-  we are in constant dialogue with the management teams of the participations and are involved in:
-  selecting the senior management,
-  defining the long-term strategy,
-  actively supporting strategic projects (M&amp;A, internationalisation, innovation and operational improvements).

## Sustainable

-  We pay particular attention to sustainable development and growth of the activities of our participations, with respect for people, environment and society;
-  we have developed an ESG policy based on UN Sustainable Development Goals and UN PRI guidelines, and we apply this policy within the group and to our own investment decisions;
-  our investment philosophy is based on transparent reporting and communication, clear agreements in terms of corporate governance and business ethics, and strict financial discipline and healthy balance sheets;
-  we want to help build a more sustainable world by investing in line with  societal  trends  such  as  climate  change,  reduction  of  greenhouse gases (e.g. through renewable energy projects), sustainable food chain, population growth and ageing and digitalisation.
-------------------------






Adecco Group AG1.pdf
## Our business at a glance

## OUR GLOBAL FOOTPRINT

<!-- image -->

## OUR SERVICE LINES

## PP  Permanent Placement

## Approximately

39,000 FTE employees globally /pluslining 30,000

FTE Akkodis consultants

## Approximately

## 100,000

clients

Approximately 2 million

associates on assignment  every day/commalining including in our  joint ventures

## FP  Flexible Placement

<!-- image -->

<!-- image -->

We place associates with organisations  on a temporary basis/commalining providing flexibility  to employers and new opportunities to  candidates/periodlining We manage the entire  recruitment process from candidate search  and screening/commalining through onboarding and  training/commalining to payroll and administration/periodlining  Associates are employed by the Group  while on assignments/commalining which often run  consecutively to provide continuous  employment/periodlining In some countries/commalining associates  are employed by the Adecco Group on a  permanent basis and seconded to clients/periodlining

We help employers to recruit talent for  permanent roles/commalining securing the skills needed  for an organisation's ongoing success/periodlining  We source candidates/commalining screen CVs/commalining conduct  interviews and assessments/commalining and advise  hiring managers/periodlining We have access to a wide  range of talent/commalining including hard-to-reach  professionals who are not actively looking  for a new job/periodlining

## OC Outsourcing/commalining Consulting &amp; Other Services

## Contribution to  Group revenues

Europe/commalining Middle East  &amp; Africa 67% Americas 21% Asia Pacific 12%

## CT Career Transition

<!-- image -->

We support organisations and their  employees through changes that require  individuals to transition out of their existing  roles/periodlining Through our expert coaching and  training/commalining we help individuals find new  opportunities both within and outside their  existing company/commalining ensuring positive  outcomes for all/periodlining Our LHH Career Transition  business is the global leader in its market/periodlining

## TR  Training/commalining Up-skilling &amp; Re-skilling

<!-- image -->

We also offer a full spectrum of complementary HR solutions/commalining  including/colonlining Outsourcing - staffing and managing the entirety of  a labour-intensive activity/commalining such as warehouse logistics or IT support/semicolonlining  Consulting - providing technical experts for project-related work/semicolonlining  Managed Service Programmes /parenleftliningMSPs/parenrightlining - managing all parts of the  flexible workforce at organisations using a large number of contingent  workers/semicolonlining and Recruitment Process Outsourcing /parenleftliningRPO/parenrightlining - handling  the entire hiring process for employers recruiting large numbers  of permanent employees/periodlining

## Gross profit  /parenleftlining/percentlining/parenrightlining

<!-- image -->

We offer training/commalining up-skilling and re-skilling both as standalone services  and in combination with other solutions/commalining such as placements or as  part of a broader workforce transformation offering/periodlining Adecco is  a leading provider of work-based training/periodlining Our General Assembly  brand is a leader in up-skilling and re-skilling in high-demand digital  skills/commalining while our Akkodis Tech Academy offers candidates the  opportunity to upskill in technology and digital engineering-related  fields to increase their employability and to create a supply of  in-demand candidates for our clients/periodlining

<!-- image -->
-------------------------






Admiral Group plc1.pdf
## Our Business Model What we do

## Insurance underwriting

<!-- image -->

<!-- image -->

Admiral Group's primary business is to sell car, van, home, travel, and pet insurance in the UK, Europe (Spain, France, Italy), and the US. The majority of our customers buy our products through the price comparison channel, with a smaller proportion of customers buying directly from us, as well as the broker and agency channels. In addition to our core insurance products, we generate other revenue from the sale of ancillary add-ons and from fees generated over the life cycle of a policy.

Read more about our Co-insurance and reinsurance on page 66

Read more about our Investing on page 65

The Group's core market is the UK, where we estimate we have 17% share of the private car insurance market and a 7% share of the private home insurance market 7 . Outside of the UK, we leverage the knowledge, skills, and resources from our established UK business to promote expansion overseas and grow both our international businesses and new ventures outside of insurance underwriting.

<!-- image -->

## Risk sharing

A key feature of our business model and success is the use of extensive reinsurance and co-insurance partnerships. These are proportional risk-sharing agreements, where insurers outside of the Group underwrite the majority of the risk generated, either through co-insurance or quota share reinsurance contracts. These arrangements include profit commission terms which allow Admiral to retain a significant portion of the profit generated.

## Investing premiums


/var/folders/fp/yhl61lbj3m73x3_17tsp1vrr0000gn/T/ipykernel_70545/2710329527.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_positives.loc[i, "Description"] = description_text

In [13]:
# # store page

# to_folder = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/company_descriptions_txt"

# for i, row in df_positives.iterrows(): 
#     print(row["Description"])
#     print(row["Report"])
#     with open(to_folder + "/" + row["Report"].replace("pdf", "txt") , "w") as f: 
#         f.write(row["Description"])

In [14]:
def get_tables(lines: list): 
    tables = []
    current_table = []

    for line in lines:
        if line.strip().startswith("|"):  # line belongs to a table
            current_table.append(line.strip())
        else:
            if current_table:  # table ended
                tables.append("\n".join(current_table))
                current_table = []

    # catch last table if file ends without empty lines
    if current_table:
        tables.append("\n".join(current_table))

    return tables

def preprocess_report(text: str) -> List[str]:

    # with open(pdf_path, "r") as f: 
    #     text = f.read()

    sentence_length = 1
    
    lines = text.split("\n")

    tables = get_tables(lines)

    # drop if condidtion is True
    conditions = [
        # filter images
        #lambda line: line == '<!-- image -->',
        
        #filter tables 
        #lambda line: (line[0] == "|" and line[-1] == "|") if len(line) > 1 else False, 

        # filter headers
        lambda line: line.strip()[0] == "#" if len(line) > 0 else True,

        # filter sentences
        #lambda line: "." not in line,
        
        # more than 50% is numbers
        #lambda line: sum(ch.isalpha() for ch in line) / len(line) < 0.5,

        # minimum 3 words 
        #lambda line: len(re.sub(r"[^a-zA-ZäöüÄÖÜß\s]", '', line).strip().split(" ")) < 3,

        # Minimum 2 Sentences
        #lambda line: sum([0 if len(sentence.split(" ")) < 3 else 1 for sentence in split_text_into_sentences(line, "en")]) < 2

    ]
    accepted_lines = [line for line in lines if not any(condition(line) for condition in conditions)]
    accepted_lines += tables

    chunks = []

    for line in accepted_lines: 
        sentences = split_text_into_sentences(line, language='en')
        sentences = [sentence.strip() for sentence in sentences]
        sentences = [sentence for sentence in sentences if sentence != ""]
        new_chunks = [(" ".join(sentences[i:i+sentence_length])).strip() for i in range(0, len(sentences), 3)]

        chunks += new_chunks
    
    if len(chunks) <= 1: 
        return chunks

    # if there is only one sentence in the last chunk, balance the two last chunks
    if len(split_text_into_sentences(chunks[-1], language = "en")) == 1: 
        last_two_chunks = chunks[-2] + " " + chunks[-1]
        chunks[-2] = last_two_chunks[0:(len(last_two_chunks) + 1) // 2]
        chunks[-1] = last_two_chunks[(len(last_two_chunks) + 1) // 2: (len(last_two_chunks)) - (len(last_two_chunks) + 1) // 2]

    chunks = [re.sub(r'\b\d+\.\d+\b', '', chunk) for chunk in chunks]
    chunks = [re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", '', chunk) for chunk in chunks]
    chunks = [re.sub(r"\s+", " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'\.{2,}', " ", chunk) for chunk in chunks]
    chunks = [re.sub(r'^\d+\.\s*', " ", chunk) for chunk in chunks]
    chunks = [chunk.lower() for chunk in chunks]
    chunks = [chunk.strip() for chunk in chunks]

    return chunks

In [15]:
df_positives.loc[:,"lenght_desc"] = df_positives["Description"].apply(len)
df_positives

/var/folders/fp/yhl61lbj3m73x3_17tsp1vrr0000gn/T/ipykernel_70545/3719149439.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_positives.loc[:,"lenght_desc"] = df_positives["Description"].apply(len)

,Unnamed: 0,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page,Description,lenght_desc
3,107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3,## we do is about Making Better Happen ™ Every...,1424
6,94,ABB Ltd.,ABBN-CH,ABBN-CH,28073.948473,29665.651960,30586.3762461154,27.11,C,ABB Ltd.2.pdf,18,-\n\n## Who we are\n\nABB has a history of inn...,2907
9,135,Accelleron Industries AG,ACLN-CH,ACLN-CH,742.680345,846.217532,NaN,28.11,C,Accelleron Industries AG1.pdf,7,## Accelleron at a glance\n\nAccelleron's tech...,1491
10,296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7,## 2. BUSINESS MODEL: BUSINESS AS UNUSUAL\n\nA...,1569
11,365,Accor SA,AC-FR,AC-FR,4224.000000,5056.000000,5606,55.10,I,Accor SA1.pdf,5,"## Message from Sébastien Bazin, Chairman and ...",3503
...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,69,Orkla ASA,ORK-NO,ORK-NO,5774.960695,5932.590483,6073.67720031738,10.89,C,Orkla ASA1.pdf,11,"## Orkla's business areas in 2022\n\nIn 2022, ...",753
466,598,Scout24 SE,G24-DE,G24-DE,447.539000,509.114000,s,96.09,S,Scout24 SE3.pdf,41,≡\n\n## Grundlagen des Konzerns\n\n## Geschäft...,3264
472,286,Severn Trent Plc,SVT-GB,SVT-GB,2505.264229,2709.430915,NaN,36.00,E,Severn Trent Plc1.pdf,8,## OUR BUSINESS MODEL UNDERSTANDING OUR WORLD\...,2100
479,133,Siemens Energy AG,ENR-DE,ENR-DE,29005.000000,31119.000000,34465,27.33,C,Siemens Energy AG1.pdf,5,## Our business areas\n\n## Digital Industries...,4527
482,30,Signify NV,LIGHT-NL,LIGHT-NL,7514.000000,6704.000000,6143,27.40,C,Signify NV3.pdf,6,## Creating Value\n\n## Our strategic focus\n\...,2289

In [32]:
paragraphs = pd.DataFrame(columns=["text", "report"])
for i, row in df_positives.iterrows():
    df_temp = pd.DataFrame(data=preprocess_report(row["Description"]), columns=["text"])
    df_temp["report"] = row["Report"]
    paragraphs = pd.concat([paragraphs, df_temp], ignore_index=True)

In [42]:
paragraphs.drop_duplicates()
paragraphs = paragraphs[paragraphs["text"] != ""]
paragraphs = paragraphs[paragraphs["text"].apply(len) > 30]
paragraphs

                                                   text           report
0     aak specializes in plantbased oils and fats th...      AAK AB1.pdf
1     we can also optimize our customers production ...      AAK AB1.pdf
2     at the heart of aaks offer is customer codevel...      AAK AB1.pdf
5     abb has a history of innovation excellence str...    ABB Ltd.2.pdf
6     our strong heritage as a technology pioneer ha...    ABB Ltd.2.pdf
...                                                 ...              ...
1516  we are building a customerfocused organization...  Signify NV3.pdf
1517  we are developing tiered offerings with multip...  Signify NV3.pdf
1518  we are driving new sustainable growth areas to...  Signify NV3.pdf
1519  we are creating a digital front and backend em...  Signify NV3.pdf
1520  we are further investing in our people creatin...  Signify NV3.pdf

[759 rows x 2 columns]

In [41]:
# these have been selected by hand!
positive_paragraphs_selected = pd.read_csv("/Users/hendrikweichel/Desktop/positive_data_selected.csv", sep=";", index_col=0)
positive_paragraphs_selected = positive_paragraphs_selected.dropna()
positive_paragraphs_selected

                                                     0
0    aak specializes in plantbased oils and fats th...
1    we can also optimize our customers production ...
2    at the heart of aaks offer is customer codevel...
3    abb has a history of innovation excellence str...
4    our strong heritage as a technology pioneer ha...
..                                                 ...
754  we are building a customerfocused organization...
755  we are developing tiered offerings with multip...
756  we are driving new sustainable growth areas to...
757  we are creating a digital front and backend em...
758  we are further investing in our people creatin...

[511 rows x 1 columns]

In [50]:
positive_paragraphs = pd.merge(paragraphs, positive_paragraphs_selected, left_on="text", right_on="0", how="inner")
positive_paragraphs = positive_paragraphs.drop(columns="0")
positive_paragraphs = positive_paragraphs.drop_duplicates(subset="text")

#### Load Negatives

In [65]:
negative_paragraphs = pd.DataFrame(columns=["text", "report"])

for i, row in df_positives.iterrows(): 
    path = row["Report"].replace(".pdf", ".json")
    with open(os.path.join(positives_json_path, path), "r") as f: 
        report_json = json.load(f)
    description_pages = ast.literal_eval(row["description_page"])
    description_pages = [description_pages] if isinstance(description_pages, int) else description_pages

    description_text = ""
    for description_page in description_pages:

        description_text += list(filter(lambda x: x["page"] != description_page + 1, report_json["pages"]))[np.random.randint(len(report_json["pages"])-1)]["markdown"]

    df_temp = pd.DataFrame(data=preprocess_report(description_text), columns=["text"])
    df_temp["report"] = row["Report"]

    print(row["Report"])
    print(description_text)
    print("-----" * 5 + "\n"*6)

    negative_paragraphs = pd.concat([negative_paragraphs, df_temp], ignore_index=True)

AAK AB1.pdf
Annual Report 2022

## The Multi-oil Ingredient House

<!-- image -->
-------------------------






ABB Ltd.2.pdf
Given the macro landscape, the Company continued its focus on solid growth fundamentals whilst reinforcing the highest ESG standards with resilience. ABB India remains vigilant on risks emanating from COVID19 and its variants with a focus on employee well-being.  The Company's agile business model and portfolio ensured conversion of opportunities, maximally optimizing  the  country's  conducive  and  relatively  stable environment in an otherwise volatile global weather, leading to a quantum leap in performance, back to pre-pandemic and preportfolio realignment levels. Cost efficiency programs together with strategic investments for new facilities, product launches, and launch of online business models supported this journey of profitable growth.

## Operational performance

Though the year started off with the Omicron scare, 2022 was the year that characterized true return to the normal with most sectors resuming activities full throttle.  It was also the year in which, buoyed by the opening of markets, ABB India continued its journey of consistent value creation for various stakeholders. This comprised investing in state-of-the-art facilities across businesses to make in India for India and the world squarely targeting both the domestic as well as global demand. During the year, three milestone facilities were inaugurated across divisions from electrification to process automation. In 2022, the Company also achieved significant sustainability milestones as  committed  in  the  sustainability  strategy  2030,  across manufacturing locations.

ABB's  portfolio  of  sustainable  technology  solutions  was deployed  across  a  wide  range  of  sectors,  during  the  year rendering efficiency &amp; productivity. For instance:

- Rectifiers for a global diversified natural resources major
- Electrification  panels  and  building  automation  for  IT (Information Technology) campuses in Hyderabad
- Doubly fed induction generator for the wind sector, solar SCADA automation and switchgears for solar projects
- Automation package for cold rolling mills for continuous galvanizing line from one of the global majors in Process Industries
- Power handling systems order from paint industry for Process Automation Energy Industries division
- Traction converter orders from locomotive companies and Electric traction motors for high-capacity electric multiple unit trains
- Robotic palletizing for a paints major, robotic handling in mining and construction industry, robotic lean palletizer by an FMCG major
- System drives and motors solutions for tyre and metals (tier 1 and 2) majors
- Advanced process control solution for a large integrated pulp and paper manufacturer, for efficiency of the highly interactive lime kiln production process
- LV (Low Voltage) MNS and ArTuK boards for data centers and document management companies
- Tool  design,  simulation,  manufacturing,  installation, commissioning, cycle time prove out in ABB Robotic line for an Indian auto major
- MV and LV switchgears, UPS (Uninterruptible Power Supply), automatic  transfer  switching  and  power  distribution packages for the one of the biggest data center companies in the country
- Distributed  control  systems  (DCS)  for  greenfield  and brownfield paints major

<!-- image -->

ABB's electrification, motion, automation, and robotics solutions continued to partner the industrial growth journey of the nation.

While serving our customers, the Company functioned tirelessly to maintain the highest level of safety and sustainability in our processes. With the focus on safer operations, the Company has improved its hazard reporting and thus have shifted focus to resolving them to the tune of 98.64 percent in 2022. To inculcate a culture of safety vigilance, Safety Observation Tours (SOTs) are
-------------------------






Accelleron Industries AG1.pdf
## Elections and term of office

Members of the Board of Directors, the Chair, and the members of the Nomination and Compensation Committee (NCC) are elected individually by the General Meeting for a one-year term ending upon completion of the next Annual General Meeting. Re-election is possible, and there is no limitation on the number of terms a member can serve. According to Art. 3.3 of Accelleron's Board Governance Rules (Governance Rules), after the year in which an individual reaches the age of 70, he or she will not be proposed for election to the Board of Directors.

## Independence

No member of the Board of Directors has any significant business relations with the Accelleron Group. Other than Oliver Riemenschneider, who led the ABB Turbocharging division, i.e. the organizational unit that operated the Accelleron business prior to the separation from ABB, all members of the Board of Directors, including Accelleron's Vice-Chair Monika Krüsi, are independent.

## Definition of areas of responsibility

The Board of Directors is responsible for the ultimate direction of the Company. Such direction and responsibility include the duty to select carefully, to instruct properly and to supervise diligently the CEO and the other members of the Executive Committee.

The Board of Directors has the non-transferable and inalienable duties as provided for by Swiss corporate law and the Articles of Association. In particular and in accordance with Art. 21 of the Articles of Association in conjunction with Art. 6.1 of the Governance Rules, the Board of Directors has delegated the operational management of the Company, within the limits permitted by and subject to the powers and duties remaining with the Board of Directors, to the CEO. The Board of Directors remains entitled to resolve on any matters that are not delegated to or reserved for the General Meeting of Shareholders or another executive body of the Company by law, the Articles of Association or the Governance Rules.

The regulation and distribution of authority between the Board of Directors and the Executive Committee are set forth in the Governance Rules, in particular in Art. 2 and Art. 6.1.

## Additional mandates

All members of the Board of Directors comply with the requirements regarding additional mandates as laid down in Art. 32 of the Articles of Association, and no exceptions were granted in the reporting year.

## Internal organizational structure

The Board of Directors constitutes itself, except for the Chair and the members of the NCC, who are elected by the General Meeting. The Board of Directors appoints from among its members its Vice-Chair, the Chair of the NCC and the Chair and members of the Audit Committee (AC). In addition, the Board of Directors appoints a secretary, who does not need to be a member of the Board. Art. 17 to 19 of the Articles of Association and Art. 4 of the Governance Rules describe the Board procedures.

The Board of Directors meets whenever the need arises. During 2022 1 , six meetings took place, with participation of all Board members at all meetings (participation rate of 100%). The meetings had an average duration of 3.2 hours. The General Counsel holding a degree in law attends the Board meetings in his capacity as Company Secretary.

The CEO and the CFO attended these Board meetings or parts thereof. The meetings were conducted either physically, remotely by online conference, or in hybrid mode (i.e., participation is in person or remote).

Neither internal auditors, external auditors nor external consultants took part in any meetings of the Board of Directors.

In addition to the above meetings, members of the Board of Directors participated in working groups, workshops, and discussion panels on various topics with senior and other management of the Group.

## Committees

The Board of Directors has two permanent committees: the Nomination and Compensation Committee and the Audit Committee. The Board Chair has the right to attend the committee meetings.

## Audit Committee

The Audit Committee (AC) is composed of at least two members of the Board of Directors appointed annually by the Board of Directors. The Board of Directors shall appoint non-executive and independent (within the meaning of the Swiss Code of Best Practice) members of the Board of Directors who have a thorough understanding of finance, accounting, and auditing, including the ability to read and understand corporate accounts and financial statements. The term of office of the AC members ends at the closing of the next Annual General Meeting. Re-appointment is possible.

The AC meets at least three times each year or more frequently if deemed necessary or appropriate. During 2022 2 , three meetings took place, with participation of all AC members at all meetings (participation rate of 100%). The meetings had an average duration of 2.3 hours. The Board Chair, the CEO and the CFO participated in all the meetings.

The AC supports the Board of Directors in overseeing (i) the integrity of the financial statements, (ii) the Company's compliance with legal, tax and regulatory requirements, (iii) the external auditor's qualifications and independence, (iv) the performance and role of the Company's internal controls system, the internal audit function, and the external auditors, (v) the Company's capital structure, funding requirements, and financial and risk policies, and (vi) the Company's implementation and maintenance of an integrity program and internal controls designed to mitigate integrity risk.

## Nomination and Compensation Committee

The Nomination and Compensation Committee (NCC) is composed of at least two non-executive members of the Board of Directors, who are each elected annually and individually by the General Meeting of the Shareholders (Art. 23 and Art. 24 of the Articles of Association and Art. 3.5 of the Governance Rules). Their term of office ends at the close of the next Annual General Meeting; re-election is possible.

The NCC meets at least two times each year, or more frequently if deemed necessary or appropriate. During 2022 3 , five meetings took

1 The current Board of Directors has been elected and subsequently constituted itself (and its committees) only in July 2022, following ABB's decision to carve-out the Accelleron Group and to have it operate as a stand-alone business. Prior to the carve-out, the Company and its management were integrated in the overall group structure of ABB. Therefore, the meetings prior to July 2022 are not considered to be material within the meaning of Art. 5 of the SIX Directive on Information relating to Corporate Governance and are not considered in this report. Consequently, the above disclosed number of meetings represents only those meetings held by the Board of Directors since July 2022.

2 See preceding footnote. Prior to the carve-out, the Company and its management were integrated in the overall group structure of ABB, and no Audit Committee was established.

3 See preceding footnote. Prior to the carve-out, the Company and its management were integrated in the overall group structure of ABB, and no Nomination and Compensation Committee was established.
-------------------------






Acciona SA2.pdf
| Risks   | 25   | Elements of change   | 26   |
|---------|------|----------------------|------|

## America

Both the United States and Canada are stepping up their efforts to further invest in and promote renewable energy and climate-friendly infrastructure.

In the US the Inflation Reduction Act (IRA) was passed in the second half of the year and will allocate more than 700 billion dollars to fighting inflation through clean industry and energy, cutting emissions by 40% by 2040.

In Canada, the Greenhouse Gas Pollution Pricing Act, which sets prices on greenhouse gas emissions, was promulgated in 2018. This price is expected to increase from 2023 onwards. The Canadian taxonomy, which, as in Europe, aims to direct investment towards sustainable businesses, is also expected to be published in mid-2023.

## More information: a boost for sustainable infrastructure in growth markets

## Asia-Pacific

In September 2022, Australia passed a law which aims to cut pollutant emissions by 43% by 2030 and achieve climate neutrality by 2050. The country also undertook to protect at least 30% of the country's land area as a way to preserve biodiversity.

## Promoting sustainable infrastructure in emerging markets.

Some of the most relevant developments in 2022 are:

## European Union

In  2022,  the  European  Union  launched  RePowerEU,  a  plan  to  rapidly  reduce  the continent's dependence on Russian fossil fuels through renewable energy.

The  European  Commission's  REPowerEU  proposal  seeks  to  raise  the  proportion of  electricity  generated  from  renewables  in  Europe  to  45%  by  2030,  up  from the  current  target  of  40%.  Ambitious  measures  have  been  put  in  place,  such  as banning the sale of combustion cars by 2035 and implementing the aforementioned Corporate Sustainability Reporting Directive (CSRD).

The Green Deal Industrial Plan launches in 2023, seeking to streamline and simplify the awarding of permits for energy farms that help meet this target.

## Canada

The  Green  Taxonomy,  which  serves  as  a  guide  for  sustainable  investment,  is  being proposed to encourage the financing of renewable energy and clean energy projects. Furthermore, the 2023 federal budget includes a new tax credit for renewable energy investment, making the country's financial conditions among the most favourable for green energy projects.

## United States

The Inflation Reduction Act (IRA) aims to install 100 GW of PV per year from 2030, in addition to investment earmarked for renewables and ensuring climate resilience.

## Asia-Pacific

The Climate  Change  Act came  into  force  in  Australia  on  15th  September  2022.  The federal  government  aims  to  have  82%  of  the  electricity  grid  powered  by  renewable energy, with a view to meeting its 43% emissions reduction target by 2030.

Index

## 1

Letter from the Chairman

2

Business model: Business as unusual

3

A new sector

<!-- image -->

The world in constant transformation

## 5

ACCIONA Solutions in 2022

<!-- image -->

Governance

7

About this report

<!-- image -->

Annex: Cash flows social 2022
-------------------------






Accor SA1.pdf
<!-- image -->

World's most diverse hospitality group continues to accelerate growth across Greater China - surpassing the 500 hotels milestone with a robust pipeline of  new hotels opening in 2022 and beyond -

Accor is advancing through 2022 with a continued focus on expanding its presence across Greater China, offering more hotels to travelers and loyalty members than ever before, from acclaimed brands such as Raffles, Fairmont, Sofitel, MGallery, Pullman, Grand Mercure, Novotel, Mercure, and ibis. Accor's new project signings in China reached an all-time high in 2022 - leading to more than 590 hotels now in operation and an additional 285 under development. Accor is also on track to drive even greater momentum and growth success this year.

## Accor adds legendary Queen Elizabeth 2 to its

portfolio Taking over operations from May 2022, the world-renowned cruise ship will undergo further up-grades and renovations prior to joining the MGallery Hotel Collection. Once fully rebranded, Queen Elizabeth 2 will undoubtedly become a landmark property for the MGallery brand and Dubai overall. Once the renovation is completed, the new MGallery Queen Elizabeth 2 will feature 447 hotel rooms, nine food &amp; beverage outlets, ten meeting rooms, 5,620 sqm area for outdoor events, six retail outlets, a swimming pool and a gym.

## Accor debuts Novotel Mexico City World Trade

Center The Group celebrates the Novotel brand's 20 th year anniversary since its arrival in Mexico with the opening of this new modern hotel featuring Novotel's new global design concept and as the second flagship for the brand in the region. Situated in a prime location in front of the World Trade Center in Mexico City, one of the most important business centers in the region, and nearby several of the city's main attractions, the energizing urban haven will cater to business and leisure travelers.

<!-- image -->
-------------------------






Ackermans & van Haaren NV1.pdf
restore the ecosystem of Lake Bardawil and to make the Northern Sinai peninsula greener. This project will help to restore the water cycle and boost fish production in Lake Bardawil.

To realise DEME's ambitious sustainability goals in all aspects of its activities, the group converted all its long-term financing into sustainability-linked loans in February 2022. This major commitment underlines DEME's vision of achieving a sustainable future and at December 31, 2022 represented a total credit value of 842.9 million euros. The commercial terms of those loans are directly linked to DEME's sustainability performance in two areas: (1) safety at work and (2) low-carbon fuel, which are in line with two material topics of its materiality matrix. Changes in key performance indicators (KPIs) will trigger adjustments on the interest margins applied to the loans. In 2022, DEME achieved the goal for low-carbon fuel.

In 2022, DEME Offshore was able to further improve its EcoVadis score, resulting in a golden medal. DEME Offshore also obtained a score B in CDP for 2022.

DEME's approach is also appreciated outside its sector.

<!-- image -->

On November 30, 2022, DEME won the Trends Global Impact  Awards,  the  most  prestigious  awards  in  Belgium for companies whose projects create sustainable value for our society. Impact is something that DEME stands for. This is a valuable recognition of the efforts and way of working of everyone at DEME. The award encourages DEME to continue on the path to a more sustainable future.

DEME  also  received  the  International  Marine  Contractors  Association  (IMCA) Award for its internal environmental campaign. The aim of this campaign was to increase environmental awareness and encouraged project locations, vessels and offices worldwide to take action on 7 topics, from energy consumption to preventing water or soil emissions.

More information about sustainability is available in the integrated annual  report  of  DEME  and  on  the  website  Sustainability  |  DEME  Group (www.deme-group.com/sustainability)

Luc Vandenbulcke CEO DEME Group

<!-- image -->

DEME I From left to right: Orion - Top: SeaMade - Bottom: Port La Nouvelle

<!-- image -->

'Many of the segment's projects support the energy transition and the move to a more sustainable planet.'
-------------------------






Adecco Group AG1.pdf
## /fivelining/periodlining/twolining EC remuneration for the financial year /twolining/zerolining/twolining/twolining


In [80]:
negative_paragraphs.drop_duplicates()
negative_paragraphs = negative_paragraphs[negative_paragraphs["text"] != ""]
negative_paragraphs = negative_paragraphs[negative_paragraphs["text"].apply(len) > 30]
negative_paragraphs

                                                   text           report
2     given the macro landscape the company continue...    ABB Ltd.2.pdf
3     cost efficiency programs together with strateg...    ABB Ltd.2.pdf
4     though the year started off with the omicron s...    ABB Ltd.2.pdf
5     during the year three milestone facilities wer...    ABB Ltd.2.pdf
6     abbs portfolio of sustainable technology solut...    ABB Ltd.2.pdf
...                                                 ...              ...
1697              these are fully paid ordinary shares.  Signify NV3.pdf
1701               issued subscribed and paidup capital  Signify NV3.pdf
1705          shares fully paid for consideration other  Signify NV3.pdf
1712          less allowance for expected credit losses  Signify NV3.pdf
1714               issued subscribed and paidup capital  Signify NV3.pdf

[995 rows x 2 columns]

In [81]:
df_negative_paragraphs = negative_paragraphs.copy()

### Combine

In [82]:
df_negative_paragraphs["label"] = False
positive_paragraphs["label"] = True

In [83]:
df_negative_paragraphs.columns, positive_paragraphs.columns

(Index(['text', 'report', 'label'], dtype='object'),
 Index(['text', 'report', 'label'], dtype='object'))

In [84]:
df_negative_paragraphs = df_negative_paragraphs.rename(columns={0:"text"})
positive_paragraphs = positive_paragraphs.rename(columns={"0":"text"})

In [85]:
df_full = pd.concat((df_negative_paragraphs, positive_paragraphs), axis=0)

In [86]:
df_full = df_full.reset_index(drop=True)
df_full

,text,report,label
0,given the macro landscape the company continue...,ABB Ltd.2.pdf,False
1,cost efficiency programs together with strateg...,ABB Ltd.2.pdf,False
2,though the year started off with the omicron s...,ABB Ltd.2.pdf,False
3,during the year three milestone facilities wer...,ABB Ltd.2.pdf,False
4,abbs portfolio of sustainable technology solut...,ABB Ltd.2.pdf,False
...,...,...,...
1500,we are building a customerfocused organization...,Signify NV3.pdf,True
1501,we are developing tiered offerings with multip...,Signify NV3.pdf,True
1502,we are driving new sustainable growth areas to...,Signify NV3.pdf,True
1503,we are creating a digital front and backend em...,Signify NV3.pdf,True
1504,we are further investing in our people creatin...,Signify NV3.pdf,True

In [109]:
#df_full.to_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/training_data/company_description_2/full_data.csv")
df_full = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/training_data/company_description_2/full_data.csv", sep=";")

### Split

In [110]:
df_full
reports = df_full["report"].unique()

In [111]:
train_reports, temp_reports = train_test_split(
    reports,
    test_size=0.40,
    random_state=42,
    shuffle=True
)

In [112]:
val_reports, test_reports = train_test_split(
    temp_reports,
    test_size=0.50,
    random_state=42,
    shuffle=True
)

In [113]:
train_df = df_full[df_full["report"].isin(train_reports)]
val_df   = df_full[df_full["report"].isin(val_reports)]
test_df  = df_full[df_full["report"].isin(test_reports)]

In [119]:
len(train_reports), len(val_reports), len(test_reports)

(37, 13, 13)

In [120]:
len(train_df), len(val_df), len(test_df)

(903, 301, 301)

In [121]:
train_df = train_df.dropna()
val_df = val_df.dropna()
test_df = test_df.dropna()

In [122]:
len(train_df), len(val_df), len(test_df)

(869, 291, 292)

In [123]:
train_df.to_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/training_data/company_description_2" + "/train_data.csv", index=False)
val_df.to_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/training_data/company_description_2" + "/val_data.csv", index=False)
test_df.to_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/training_data/company_description_2" + "/test_data.csv", index=False)