In [73]:
from tqdm import tqdm
import torch.nn as nn
import torch
from safetensors.torch import load_file  # comes with HF if safetensors installed
import time
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
import numpy as np, time
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from scipy.special import softmax
import os
from typing import List
os.chdir("/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis")

from NACE_helper import NACE_code_structure, NACE_helper
import pandas as pd

np.random.seed(7)

In [74]:
sections_full = NACE_code_structure.level_1 
divisions_full = NACE_code_structure.level_2
classes_full = NACE_code_structure.level_3

In [98]:
# ------------------------------
# 1) Hierarchy
# ------------------------------
sections = {"A": "Agriculture", "B": "Mining"}# "C": "Manufacturing", "K": "Financials"
divisions = {
    "A": ["1", "2", "3"],  
    "B": ['5', '6', '7'],
    "C": ['20', '21'], 
    "F": ["41", "42", "43"], 
    "J": ["58", "63"],
    }
classes = {
    "1": ["01.1","01.2","01.3","01.4"],
    "2": ['02.1', '02.2', '02.3'],
    "3": ['03.1', '03.2'],
    "5": ['05.1', '05.2'],
    "6": ['06.1', '06.2'],
    "7": ['07.1', '07.2'],
    "20": ['20.1', '20.2', '20.3', '20.4', '20.5', '20.6'],
    "21": ['21.1', '21.2'],
    "41": ["41.1", "41.2"], 
    "42": ["42.1", "42.2","42.9"], 
    "43": ["43.1", "43.2", "43.3","43.9"], 
    "58": ['58.1', '58.2'],
    "63": ['63.1', '63.9'],
    }

division_of_class = {}
section_of_division = {}
all_divisions = []
for sec, divs in divisions.items():
    all_divisions.extend(divs)
    for d in divs:
        section_of_division[d] = sec
        for c in classes[d]:
            division_of_class[c] = d
all_classes = list(division_of_class.keys())
all_classes

['1.1',
 '1.2',
 '1.3',
 '1.4',
 '2.1',
 '2.2',
 '2.3',
 '3.1',
 '3.2',
 '5.1',
 '5.2',
 '6.1',
 '6.2',
 '7.1',
 '7.2']

In [76]:
nace_descriptions = pd.read_csv("data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv", sep="\t")

get_description = lambda code: nace_descriptions[nace_descriptions["CODE"] == code]["NAME"].iloc[0]

In [ ]:
### Load real data 

df_overview_2_with_description = pd.read_csv("data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview_with_description.csv")
df_overview_2_with_description = df_overview_2_with_description[df_overview_2_with_description["Description_clean"].notna()]
#df_overview_2_with_description = df_overview_2_with_description[df_overview_2_with_description["NACE_letter"].isin(sections.keys())]
#df_overview_2_with_description = df_overview_2_with_description[df_overview_2_with_description["NACE_lvl_3"].isin(list(map(float, all_classes)))]
df_overview_2_with_description

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Symbol,Description_page,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,...,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description,Description_clean,Tested_Class
2,2,2,2,ID1000167901,NaN,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,...,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,## Riwayat Singkat Perseroan\n\nThe Company at...,PT Dharma Samudera Fishing Industries Tbk or '...,True
11,11,11,11,LU0611262873,NaN,KSG Agro SA,1,2010.0,POL,L5903L107,...,1,SHARE,B42XFB0,A,KSG Agro SA1.pdf,1.5,1,"## PRINCIPAL ACTIVITIES\n\nKSG Agro S.A., sepa...","KSG Agro S.A., together with its subsidiaries,...",False
21,21,21,21,AU000000CSS3,NaN,Clean Seas Seafood Limited,1,2000.0,AUS,Q2508T119,...,1,SHARE,B0PFW92,A,Clean Seas Seafood Limited2.pdf,3.2,3,For personal use only\n\n<!-- image -->\n\n## ...,Clean Seas is the global leader in the full cy...,True
85,85,85,85,KR7086060001,5.0,"Gene Bio Tech Co., Ltd.",1,2000.0,KOR,Y2684U105,...,1,SHARE,B11R103,A,"Gene Bio Tech Co., Ltd.1.pdf",1.6,1,## WHO WE ARE\n\nBio-Gene is an Australian ...,Bio-Gene is an Australian agtech development c...,False

In [99]:
df_val_3 = []

for path in [
    "data/synthetic_data/data_20251218__level_3__subclasses_1",
    "data/synthetic_data/data_20251219__level_3__subclasses_2",
    "data/synthetic_data/data_20251219__level_3__subclasses_3",
    "data/synthetic_data/data_20251219__level_3__subclasses_5",
    "data/synthetic_data/data_20251219__level_3__subclasses_6",
    "data/synthetic_data/data_20251219__level_3__subclasses_7",
]: 

    df_val_3.append(pd.read_csv(path+"/val_data.csv"))

df_val_3 = pd.concat(df_val_3, ignore_index=True)
#df_val_3["label"] = df_val_3["label"].astype(str).apply(lambda x: "0" + x if len(x) == 3 else x)
df_val_3["label"] = df_val_3["label"].astype(str)

df_val_2 = []

for path in [
    "data/synthetic_data/data_20251219__level_2__subclasses_B",
    "data/synthetic_data/data_20251218__level_2__subclasses_A"
]: 

    df_val_2.append(pd.read_csv(path+"/val_data.csv"))

df_val_2 = pd.concat(df_val_2, ignore_index=True)
df_val_2["label"] = df_val_2["label"].astype(str)
df_val_2 = df_val_2[df_val_2["label"].apply(lambda x: x in list(all_divisions))]

dataset_path_1 = "data/synthetic_data/data_20251219__level_1__subclasses_None/val_data.csv"
df_val_1 = pd.read_csv(dataset_path_1)

df_val_1 = df_val_1[df_val_1["label"].apply(lambda x: x in list(sections.keys()))]

X_lvl_1_cal = df_val_1["text"].to_numpy()
y_lvl_1_cal = df_val_1["label"].to_numpy()

X_lvl_2_cal = df_val_2["text"].to_numpy()
y_lvl_2_cal = df_val_2["label"].to_numpy()

X_lvl_3_cal = df_val_3["text"].to_numpy()
y_lvl_3_cal = df_val_3["label"].to_numpy()

# X_lvl_3_test and y_lvl_3_test is the data to test
X_lvl_3_cal, X_lvl_3_test, y_lvl_3_cal, y_lvl_3_test = train_test_split(X_lvl_3_cal, y_lvl_3_cal, test_size=0.3, random_state=0, stratify=y_lvl_3_cal)

len(X_lvl_1_cal), len(X_lvl_2_cal), len(X_lvl_3_cal)

(403, 1082, 1838)

In [79]:
# def build_tree_str(sections, divisions, classes, indent="  "):
#     lines = []
#     for sec_code, sec_name in sorted(sections.items()):
#         try: 
#             num_sentences = df_statistics_1[df_statistics_1["NACE_Code"] == sec_code]["Sentences"].iloc[0]
#         except IndexError:
#             num_sentences = 0

#         lines.append(f"{sec_code} — {sec_name}: {num_sentences} training samples")

#         for div_code in sorted(divisions.get(sec_code, []), key=lambda x: (len(x), x)):
#             try: 
#                 num_sentences = df_statistics_2[df_statistics_2['NACE_Code'] == div_code]['Sentences'].iloc[0]
#             except IndexError:
#                 num_sentences = 0
#             lines.append(f"{indent}{div_code}: {get_description(div_code)} {num_sentences}")

#             for cls_code in sorted(classes.get(div_code, []), key=lambda x: tuple(map(int, x.split(".")))):
#                 try: 
#                     num_sentences = df_statistics_3[df_statistics_3['NACE_Code'] == cls_code]['Sentences'].iloc[0]
#                 except IndexError:
#                     num_sentences = 0
#                 lines.append(f"{indent}{indent}{cls_code}: {get_description(cls_code)} {num_sentences}")
#     return "\n".join(lines)


# print(build_tree_str(sections, divisions, classes))

# print(build_tree_str(sections_full, divisions_full, classes_full))

In [107]:
f = lambda x : "0"+x
y_lvl_3_cal_lvl_2 = np.vectorize(lambda x: NACE_helper.get_all_level(f(x))[2])(y_lvl_3_cal)
y_lvl_3_cal_lvl_2

array(['1', '1', '3', ..., '6', '3', '5'], dtype='<U1')

In [108]:
y_lvl_2_cal_lvl_1 = np.vectorize(NACE_helper.get_level_1_nace)(y_lvl_2_cal)
y_lvl_2_cal_lvl_1

array(['B', 'B', 'B', ..., 'A', 'A', 'A'], dtype='<U1')

In [91]:
# ------------------------------
# 2) Import BERT Models
# ------------------------------

def load_custom_bert_from_checkpoint(ckpt_path: str, num_layers_base: int = 1, num_labels_base: int = None):
    # 1. Load the saved config (includes custom_hidden, custom_num_layers)
    config = AutoConfig.from_pretrained(ckpt_path)

    full_config = AutoConfig.from_pretrained(ckpt_path.replace(os.path.basename(ckpt_path), "training_config.json"))

    # 2. Build a model from config (bare BertForSequenceClassification)
    model = AutoModelForSequenceClassification.from_config(config)

    # 3. Rebuild the SAME classifier architecture as in training
    hidden = getattr(config, "custom_hidden", 512)  # fallback if not in config
    num_layers = getattr(full_config, "num_layers", num_layers_base)
    num_labels = getattr(config, "num_labels", num_labels_base)

    layers = []
    for i in range(num_layers):
        in_dim = config.hidden_size if i == 0 else hidden
        layers.append(nn.Linear(in_dim, hidden))
        layers.append(nn.GELU())
        layers.append(nn.Dropout(0.2))

    layers.append(nn.Linear(hidden, num_labels))
    model.classifier = nn.Sequential(*layers)

    # 4. Load weights from model.safetensors
    state_dict = load_file(os.path.join(ckpt_path, "model.safetensors"))
    model.load_state_dict(state_dict, strict=True)  # will fail loudly if mismatch

    # 5. Inference mode
    model.eval()
    return model


ckpt_path_sec = "results/BERT_models/NACE_synthetic_data/006_results__synthetic_data_1__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-380"
ckpt_path_sec = "results/BERT_models/NACE_synthetic_data/047_results__level_1__subclasses_None__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-760"

sec_clf = load_custom_bert_from_checkpoint(ckpt_path_sec)

ckpt_path_div = {
    "A":"results/BERT_models/NACE_synthetic_data/062_results__level_2__subclasses_A__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-102", 
    "B": "results/BERT_models/NACE_synthetic_data/059_results__level_2__subclasses_B__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-4080",
    # This one is for K -> [64,65,66]
    #"K": "results/BERT_models/NACE_classification/NACE_level_2/NACE_class_K/001_results__data_approach_2__num_layers_2__cos_thres_0.4bert-base-uncased__train_full_model__some_labels_no_G__only_labels/checkpoint-634",
    # This one is for K -> [64,66]
    #"K": "results/BERT_models/NACE_classification/NACE_level_2/NACE_class_K/002_results__data_approach_2__num_layers_2__cos_thres_0.35bert-base-uncased__train_full_model__some_labels_no_G__only_labels/checkpoint-69",
    # "F": "results/BERT_models/NACE_classification/NACE_level_2/NACE_class_F/001_results__data_approach_2__num_layers_2__cos_thres_0.35bert-base-uncased__train_full_model__some_labels_no_G__only_labels/checkpoint-260",
    # "J": "results/BERT_models/NACE_classification/NACE_level_2/NACE_class_J/001_results__data_approach_2__num_layers_2__cos_thres_0.35bert-base-uncased__train_full_model__some_labels_no_G__only_labels/checkpoint-48",
    # "N": "results/BERT_models/NACE_classification/NACE_level_2/NACE_class_N/001_results__data_approach_2__num_layers_2__cos_thres_0.35bert-base-uncased__train_full_model__some_labels_no_G__only_labels/checkpoint-300", 
} 
div_clf_dict = {k: load_custom_bert_from_checkpoint(v) for k,v in ckpt_path_div.items()}
ckpt_path_cls = {
    "1": "results/BERT_models/NACE_synthetic_data/056_results__level_3__subclasses_1__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-726",
    "2": "results/BERT_models/NACE_synthetic_data/055_results__level_3__subclasses_2__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-102",
    "3": "results/BERT_models/NACE_synthetic_data/058_results__level_3__subclasses_3__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-68",
    "5": "results/BERT_models/NACE_synthetic_data/057_results__level_3__subclasses_5__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-2720",
    "6": "results/BERT_models/NACE_synthetic_data/060_results__level_3__subclasses_6__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-2720",
    "7": "results/BERT_models/NACE_synthetic_data/061_results__level_3__subclasses_7__num_layers_2__model_namebert-base-uncased__train_full_model/checkpoint-68", 
} 
cls_clf_dict = {k: load_custom_bert_from_checkpoint(v) for k,v in ckpt_path_cls.items()}

# tokenizer is used for all models
tokenizer = AutoTokenizer.from_pretrained(ckpt_path_sec) 

idx_sec = sec_clf.config.label2id
idx_div_dict = {k: v.config.label2id for k, v in div_clf_dict.items()}
idx_cls_dict = {k: v.config.label2id for k, v in cls_clf_dict.items()}

In [84]:
import numpy as np

def softmax(x, temperature=1.0):
    """
    Softmax with temperature.

    Args:
        x (array-like): input logits
        temperature (float): temperature parameter (T > 0)

    Returns:
        np.ndarray: probability distribution
    """
    x = np.asarray(x, dtype=np.float64)

    # scale by temperature
    x = x / temperature

    # numerical stability
    x = x - np.max(x)

    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

In [85]:
TEMPERATURE = 1.0
def BERT_classification_chunk(chunks: List[str], model, tokenizer=tokenizer, temperature=TEMPERATURE, waitbar=False) -> List:

    probas = []

    if waitbar:
        chunks = tqdm(chunks)

    for chunk in chunks: 
        inputs = tokenizer(chunk, return_tensors="pt", truncation=True)
        with torch.no_grad():
            outputs = model(**inputs)
            logits = outputs.logits.squeeze(0)

        probas.append(softmax(logits, temperature=temperature))
    return np.array(probas)

In [86]:
# import matplotlib.pyplot as plt

# for i in [0.1, 0.5, 1.0, 2.0, 5.0]:
#     probas = BERT_classification_chunk(X_lvl_1_cal[:2], model=sec_clf, temperature=i)
#     probas
#     plt.figure()
#     plt.title(f"Temperature: {i}")
#     plt.bar(range(len(probas[0])), probas[0])

In [87]:
# ------------------------------
# 5) RAPS + reject calibration
# ------------------------------
K_FREE = 1
LAMBDA = 0.05

def renorm_rows(v):
    s = v.sum(axis=1, keepdims=True)
    return np.divide(v, s, out=np.full_like(v, 1.0 / v.shape[1]), where=(s > 0))

def raps_score_rowwise_argsort(P, true_idx, k_free=K_FREE, lam=LAMBDA):
    order = np.argsort(-P, axis=1)
    P_sorted = np.take_along_axis(P, order, axis=1)
    true_mask = (order == true_idx[:, None])
    rank_pos = true_mask.argmax(axis=1)   # exact argsort rank, 0-based
    r = rank_pos + 1
    cumsum = np.cumsum(P_sorted, axis=1)
    cum = cumsum[np.arange(P.shape[0]), rank_pos]
    penalty = lam * np.maximum(0, r - k_free)
    return cum + penalty

def reject_score(P_sec):
    return 1.0 - P_sec.max(axis=1)

def qthr(a, eps):
    return float(np.quantile(a, 1.0-eps, method="higher"))

# Predict probabilities on calibration in batch
t0 = time.time()
print(f"Predict {len(X_lvl_1_cal)} Sections.")
P_sec_cal = BERT_classification_chunk(X_lvl_1_cal, sec_clf, waitbar=True)

Predict 403 Sections.

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 403/403 [00:14<00:00, 28.26it/s]

In [92]:
print(f"Predict {len(X_lvl_2_cal)} Divisions.")
P_div_cal_dict = {k: BERT_classification_chunk(X_lvl_2_cal, v, waitbar=True) for k, v in div_clf_dict.items()}

Predict 1082 Divisions.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1082/1082 [00:42<00:00, 25.41it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1082/1082 [00:42<00:00, 25.56it/s]

In [88]:
print(f"Predict {len(X_lvl_3_cal)} Classes.")
P_cls_cal_dict = {k: BERT_classification_chunk(X_lvl_3_cal, v, waitbar=True) for k, v in cls_clf_dict.items()}
t_prob = time.time() - t0

Predict 1082 Divisions.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1082/1082 [00:41<00:00, 26.12it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1082/1082 [00:41<00:00, 26.16it/s]

Predict 1838 Classes.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:10<00:00, 25.92it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:10<00:00, 25.97it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:10<00:00, 25.96it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:11<00:00, 25.75it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:11<00:00, 25.58it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1838/1838 [01:11<00:00, 25.57it/s]

In [144]:
# --- thresholds ---
EPS_SEC = EPS_DIV = EPS_CLS = 0.1
EPS_REJECT = 0.15
MAX_LEAF_SIZE = 3

true_sec_idx = np.array([idx_sec[s] for s in y_lvl_1_cal])
raps_sec_scores = raps_score_rowwise_argsort(P_sec_cal, true_sec_idx)
tau_sec = qthr(raps_sec_scores, EPS_SEC)

In [94]:
# Division threshold: Mondrian-by-parent (true section)
tau_div_dict = {}
for div, _ in div_clf_dict.items():

    #print(f"Get tau for classifier {div}: {idx_div_dict[div].keys()}")

    # Only take correctly chosen sections (lvl 1)
    mask = (y_lvl_2_cal_lvl_1 == div)
    div_scores = np.empty(len(X_lvl_2_cal[mask]))
    if not np.any(mask):
        continue
    
    child = list(idx_div_dict[div].keys())
    child_idx = np.array([idx_div_dict[div][d] for d in child], dtype=int)

    # Probs of the highest scoring class
    P_child = renorm_rows(P_div_cal_dict[div][mask][:, child_idx])
    
    # Right division
    true_div_local = np.array([child.index(d) for d in y_lvl_2_cal[mask]], dtype=int)
    
    # S scores
    div_scores = raps_score_rowwise_argsort(P_child, true_div_local)
    
    # get tau 
    tau_div_temp = qthr(div_scores, EPS_DIV)
    tau_div_dict[div] = tau_div_temp

tau_div_dict

{'A': 0.9983499253968631, 'B': 0.9999964528256468}

In [109]:
# Class threshold: Mondrian-by-parent (true division)
tau_cls_dict = {}
for cls_, _ in cls_clf_dict.items(): 
    
    mask = (y_lvl_3_cal_lvl_2 == cls_)
    cls_scores = np.empty(len(X_lvl_3_cal[mask]))
    if not np.any(mask):
        continue
    
    child = list(idx_cls_dict[cls_].keys())
    child_idx = np.array([idx_cls_dict[cls_][c] for c in child], dtype=int)
    
    P_child = renorm_rows(P_cls_cal_dict[cls_][mask][:, child_idx])
    true_cls_local = np.array([child.index(c) for c in y_lvl_3_cal[mask]], dtype=int)

    cls_scores = raps_score_rowwise_argsort(P_child, true_cls_local)
    tau_cls_temp = qthr(cls_scores, EPS_CLS)
    tau_cls_dict[cls_] = tau_cls_temp

tau_cls_dict

{'1': 0.9999305095900259,
 '2': 0.9977539484266309,
 '3': 0.9981449882194333,
 '5': 0.999994429873988,
 '6': 0.9999958902468339,
 '7': 0.9988939890929355}

In [169]:
EPS_REJECT=0.1

In [170]:
# Reject threshold calibrated on in-dist calibration points only
rej_scores_in = reject_score(P_sec_cal)
tau_rej = float(np.quantile(rej_scores_in, 1.0 - EPS_REJECT, method="higher"))
tau_rej

0.00010944197119011623

In [146]:
print("Tau for section:", tau_sec)
print("Tau for each division: ", tau_div_dict)
print("Tau for each class: ", tau_cls_dict)

Tau for section: 0.9999104718964527
Tau for each division:  {'A': 0.9983499253968631, 'B': 0.9999964528256468}
Tau for each class:  {'1': 0.9999305095900259, '2': 0.9977539484266309, '3': 0.9981449882194333, '5': 0.999994429873988, '6': 0.9999958902468339, '7': 0.9988939890929355}

In [ ]:
# # ------------------------------
# # 6) EXACT set-based metrics (vectorized)
# # ------------------------------
# t0 = time.time()

# rej_cal = (reject_score(P_sec_cal) > tau_rej)
# kept = ~rej_cal

# # Section membership + size
# sec_in_set = (raps_score_rowwise_argsort(P_sec_cal, true_sec_idx) <= tau_sec)
# sec_membership = np.column_stack([
#     (raps_score_rowwise_argsort(P_sec_cal, np.full(len(X_cal), j, dtype=int)) <= tau_sec)
#     for j in range(P_sec_cal.shape[1])
# ])
# sec_set_size = sec_membership.sum(axis=1)

# # Division membership + size (Mondrian true parent)
# div_in_set_mondrian = np.empty(len(X_cal), dtype=bool)
# div_set_size_mondrian = np.empty(len(X_cal), dtype=int)
# for s in sections.keys():
#     mask = (y_sec_cal == s)
#     if not np.any(mask):
#         continue
#     child = divisions[s]
#     child_idx = np.array([idx_div_dict[d] for d in child], dtype=int)
#     P_child = renorm_rows(P_div_cal[mask][:, child_idx])
#     true_div_local = np.array([child.index(d) for d in y_div_cal[mask]], dtype=int)

#     div_in_set_mondrian[mask] = (raps_score_rowwise_argsort(P_child, true_div_local) <= tau_div)
#     memb = np.column_stack([
#         (raps_score_rowwise_argsort(P_child, np.full(P_child.shape[0], j, dtype=int)) <= tau_div)
#         for j in range(P_child.shape[1])
#     ])
#     div_set_size_mondrian[mask] = memb.sum(axis=1)

# # Class membership + size (Mondrian true parent)
# cls_in_set_mondrian = np.empty(len(X_cal), dtype=bool)
# cls_set_size_mondrian = np.empty(len(X_cal), dtype=int)
# for d, child in classes.items():
#     mask = (y_div_cal == d)
#     if not np.any(mask):
#         continue
#     child_idx = np.array([idx_cls_dict[c] for c in child], dtype=int)
#     P_child = renorm_rows(P_cls_cal[mask][:, child_idx])
#     true_cls_local = np.array([child.index(c) for c in y_cls_cal[mask]], dtype=int)

#     cls_in_set_mondrian[mask] = (raps_score_rowwise_argsort(P_child, true_cls_local) <= tau_cls)
#     memb = np.column_stack([
#         (raps_score_rowwise_argsort(P_child, np.full(P_child.shape[0], j, dtype=int)) <= tau_cls)
#         for j in range(P_child.shape[1])
#     ])
#     cls_set_size_mondrian[mask] = memb.sum(axis=1)

# # Hierarchical propagated membership along TRUE path
# div_in_set_hier = sec_in_set & div_in_set_mondrian
# cls_in_set_hier = div_in_set_hier & cls_in_set_mondrian

# # Output-level stats (exact for this tiny hierarchy)
# cls_size_by_div = {}
# for d, child in classes.items():
#     child_idx = np.array([idx_cls_dict[c] for c in child], dtype=int)
#     P_child = renorm_rows(P_cls_cal[:, child_idx])
#     memb = np.column_stack([
#         (raps_score_rowwise_argsort(P_child, np.full(P_child.shape[0], j, dtype=int)) <= tau_cls)
#         for j in range(P_child.shape[1])
#     ])
#     cls_size_by_div[d] = memb.sum(axis=1)

# leaf_union_size = np.zeros(len(X_cal), dtype=int)
# for s, divs_s in divisions.items():
#     s_idx = idx_sec[s]
#     s_in = sec_membership[:, s_idx]
#     add = np.zeros(len(X_cal), dtype=int)
#     for d in divs_s:
#         add += cls_size_by_div[d]
#     leaf_union_size += s_in.astype(int) * add

# reported_level = np.full(len(X_cal), "class_level", dtype=object)
# reported_level[leaf_union_size > MAX_LEAF_SIZE] = "division_level"
# reported_level[rej_cal] = "reject"

# t_exact = time.time() - t0

In [113]:
# # ------------------------------
# # 7) Print results
# # ------------------------------
# print(f"=== FULLY UNIFIED EXACT METRICS (argsort-identical RAPS), N={N:,} (cal size={len(X_cal):,}) ===")
# print(f"Data generation: {t_gen:.2f}s | Fit: {t_fit:.2f}s | predict_proba: {t_prob:.2f}s | exact-metrics: {t_exact:.2f}s\n")

# print("Thresholds:")
# print("  tau_sec:", tau_sec)
# print("  tau_div:", tau_div)
# print("  tau_cls:", tau_cls)
# print("  tau_rej (1-maxp):", tau_rej, "=> reject if max p_sec <", float(1 - tau_rej))
# print()

# print("Reject stats:")
# print("  reject_rate (all cal):", float(rej_cal.mean()))
# print("  reject_rate on flagged OOD cal points:", float(rej_cal[is_ood_cal].mean()))
# print("  reject_rate on flagged in-dist cal points:", float(rej_cal[~is_ood_cal].mean()))
# print()

# def mean_if(mask, arr_bool):
#     return float(arr_bool[mask].mean()) if np.any(mask) else float("nan")

# def avg_if(mask, arr_num):
#     return float(arr_num[mask].mean()) if np.any(mask) else float("nan")

# print("Coverage (exact set membership):")
# print("  Section coverage (unconditional):", float(sec_in_set.mean()))
# print("  Division coverage (Mondrian, unconditional):", float(div_in_set_mondrian.mean()))
# print("  Class   coverage (Mondrian, unconditional):", float(cls_in_set_mondrian.mean()))
# print("  Division coverage (hierarchical propagated):", float(div_in_set_hier.mean()))
# print("  Class   coverage (hierarchical propagated):", float(cls_in_set_hier.mean()))
# print()

# print("Coverage among KEPT (not rejected):")
# print("  Section coverage | kept:", mean_if(kept, sec_in_set))
# print("  Division Mondrian coverage | kept:", mean_if(kept, div_in_set_mondrian))
# print("  Class   Mondrian coverage | kept:", mean_if(kept, cls_in_set_mondrian))
# print("  Division hierarchical coverage | kept:", mean_if(kept, div_in_set_hier))
# print("  Class   hierarchical coverage | kept:", mean_if(kept, cls_in_set_hier))
# print()

# print("Average set sizes (all cal / kept):")
# print("  |Gamma_sec|:", float(sec_set_size.mean()), "/", avg_if(kept, sec_set_size))
# print("  |Gamma_div(true-parent)|:", float(div_set_size_mondrian.mean()), "/", avg_if(kept, div_set_size_mondrian))
# print("  |Gamma_cls(true-parent)|:", float(cls_set_size_mondrian.mean()), "/", avg_if(kept, cls_set_size_mondrian))
# print()

# print("Backtracking / output-level stats (using MAX_LEAF_SIZE=%d):" % MAX_LEAF_SIZE)
# print("  P(output=reject):", float((reported_level=="reject").mean()))
# print("  P(output=division_level):", float((reported_level=="division_level").mean()))
# print("  P(output=class_level):", float((reported_level=="class_level").mean()))

In [114]:
sec_labels = sec_clf.config.id2label
div_labels = {k2: v2.config.id2label for k2, v2 in div_clf_dict.items()}
cls_labels = {k2: v2.config.id2label for k2, v2 in cls_clf_dict.items()}

In [ ]:
### Test different tau

#tau_rej = 0.9
# tau_div_dict = {'A': 0.98, 'C': 0.98, 'K': 1}
# tau_cls_dict = {'1': 0.98,
#  '3': 0.98,
#  '21': 0.98,
#  '26': 0.98,
#  '64': 0.98,
#  '66': 0.98}

In [141]:
K_FREE = 1
LAMBDA = 0.05

def renorm(v):
    s = float(np.sum(v))
    return v/s if s > 0 else np.ones_like(v)/len(v)

def raps_score_1d(p, j, k_free=K_FREE, lam=LAMBDA):
    order = np.argsort(-p)
    r = int(np.where(order == j)[0][0]) + 1
    return float(np.sum(p[order[:r]]) + lam * max(0, r - k_free))

def raps_set_1d(p, labels, tau):
    print("RAPS scores:")
    # for j in range(len(labels)): 
    #     print(p[j], str(labels[j]), raps_score_1d(p, j), tau, raps_score_1d(p, j) <= tau)
    return [str(labels[j]) for j in range(len(labels)) if raps_score_1d(p, j) <= tau]

def reject_score_1d(pS):
    return float(1.0 - np.max(pS))

def predict_full_one(desc, max_leaf_size=3, temperature=1):
    
    # get 1 level predictio

    pS = BERT_classification_chunk([desc], sec_clf, temperature=temperature)[0]
    rs = reject_score_1d(pS)

    sec_set = raps_set_1d(pS, sec_labels, tau_sec)
    sec_probs = {sec_labels[i]: pS[i] for i in range(len(pS))}

    # if empty return nothing
    if rs > tau_rej:
        return {
            "section_set": [],
            "section_probs": sec_probs,
            "division_sets": {},
            "division_probs": {}, 
            "class_probs": {},
            "class_sets": {},
            "final_output": {"type":"reject", "reason":"low section confidence", "reject_score": rs},
        }

    if len(sec_set) == 0:
        sec_set = [str(sec_labels[int(np.argmax(pS))])]

    # Temp 

    #sec_set_ = [s for s in sec_set if s in list(div_clf_dict.keys())]

    # get 2 level prediction (of the children)

    div_sets = {}
    div_probs = {}
    #for s in list(set(sec_labels) & set(sec_set)):
    for s in sec_set: 
        pD = BERT_classification_chunk([desc], div_clf_dict[s], temperature=temperature)[0]
        
        child = list(div_labels[s].values())
        print(child)
        print(idx_div_dict)
        print(idx_div_dict[s])
        p_child = renorm(np.array([pD[idx_div_dict[s][str(d)]] for d in child]))

        dset = raps_set_1d(p_child, child, tau_div_dict[s])
        if len(dset) == 0:
            dset = [child[int(np.argmax(p_child))]]

        div_probs[s] = {div_labels[s][i]: pD[i] for i in range(len(pD))}
        div_sets[s] = dset

    # get 3 level prediction (of the children)

    cls_sets = {}
    cls_probs = {}
    leaf = []
    for ds in div_sets.values():
        for d in ds:
            if d in cls_clf_dict.keys():
                pC = BERT_classification_chunk([desc], cls_clf_dict[d], temperature=2)[0]
                child = list(cls_labels[d].values())
                p_child = renorm(np.array([pC[idx_cls_dict[d][str(c)]] for c in child]))
                cset = raps_set_1d(p_child, child, tau_cls_dict[d])
                if len(cset) == 0:
                    cset = [child[int(np.argmax(p_child))]]
                cls_sets[d] = cset
                cls_probs[d] = {cls_labels[d][i]: pC[i] for i in range(len(pC))}
                leaf.extend(cset)

    leaf = sorted(set(leaf))
    if len(leaf) <= max_leaf_size:
        final = {"type":"class_level", "codes": leaf}
    else:
        div_out = sorted({d for ds in div_sets.values() for d in ds})
        final = {"type":"division_level", "codes": div_out}

    return {
        "section_set": sec_set,        
        "section_probs": sec_probs,
        "division_sets": div_sets,
        "division_probs": div_probs,
        "class_sets": cls_sets,
        "class_probs": cls_probs,
        "final_output": final,
    }

predict_full_one("manufacture metal tanks containers reservoirs pressure vessels")

RAPS scores:

{'section_set': [],
 'section_probs': {'C': 0.9995804469166741,
  'A': 2.2647916410674862e-05,
  'F': 3.519895319301642e-05,
  'B': 0.00019237450527419256,
  'J': 0.00016933170844789128},
 'division_sets': {},
 'division_probs': {},
 'class_probs': {},
 'class_sets': {},
 'final_output': {'type': 'reject',
  'reason': 'low section confidence',
  'reject_score': 0.00041955308332586316}}

### Test on Paragraphs

In [147]:
false_positives_lvl_1 = []
false_positives_lvl_2 = []
false_positives_lvl_3 = []

true_lvl_1 = []
true_lvl_2 = []
true_lvl_3 = []

for i in tqdm(range(len(X_lvl_3_test))):
    desc = X_lvl_3_test[i]
    # ts, td, tc = y_sec_cal[i], y_div_cal[i], y_cls_cal[i]

    tc = y_lvl_3_test[i]
    td = [div for div, cls_ in classes.items() if tc in cls_][0]
    ts = [sec for sec, divs in divisions.items() if td in divs][0]
    
    pred = predict_full_one(desc, max_leaf_size=3)


    print("\n==================================================")
    print(f"Description {i}:\n ", desc)
    print(f"True: section={ts}, division={td}, class={tc}")
    print("Section set:", pred["section_set"])
    print("Section probs:", pred["section_probs"])
    print("Division sets:", pred["division_sets"])
    print("Division probs:", pred["division_probs"])
    print("Class sets:", pred["class_sets"])
    print("Class probs:", pred["class_probs"])
    print("Final output:", pred["final_output"])   

    # How good is the prediction
    print("Evaluation:")     
    true = (ts in pred["section_set"])
    true_lvl_1.append(true)
    print("Right class in Level 1?", true)
    print("Level 1 Empty?", (len(pred["section_set"])==0))
    fp = not(ts in pred["section_set"]) and not(len(pred["section_set"])==0)
    false_positives_lvl_1.append(fp)
    print("False Positive: ", fp)
    print()

    divisions_list = [x for k, v in pred["division_sets"].items() for x in v]
    true = (td in divisions_list)
    true_lvl_2.append(true)
    #print("Right class in Level 2 or Level 2 empty? ", (td in divisions_list) or (len(pred["division_sets"])==0))
    print("Right class in Level 2?", true)
    print("Level 2 Empty?", (len(pred["division_sets"])==0))
    fp = not(td in divisions_list) and not(len(pred["division_sets"])==0)
    false_positives_lvl_2.append(fp)
    print("False Positive: ", fp)
    print()

    class_list = [x for k, v in pred["class_sets"].items() for x in v]
    true = (tc in class_list)
    true_lvl_3.append(true)
    #print("Right class in Level 3 or Level 3 empty? ", (tc in class_list) or (len(pred["class_sets"])==0))
    print("Right class in Level 3?", true)
    print("Level 3 Empty?", (len(pred["class_sets"])==0))
    fp = not(tc in class_list) and not(len(pred["class_sets"])==0)
    false_positives_lvl_3.append(fp)
    print("False Positive: ", fp)
    print()

  0%|▏                                                                                                                                                                                | 1/788 [00:00<02:20,  5.61it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 0:
  We are engaged in the comprehensive management of lignite resources, from extraction to processing and transportation. Our mining operations focus on the efficient recovery of lignite, employing innovative techniques that enhance yield while reducing environmental footprint. We also operate processing facilities where lignite is washed and dehydrated to improve its quality for end-use applications. Our logistics team ensures that the processed lignite is delivered promptly to clients, utilizing a network of transportation partners to optimize routes and reduce costs. This integrated approach allows us to create value throughout the lignite supply chain.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques, employing advanced technologies to enhance operational efficiency. We utilize state-of-the-art machinery to ensure minimal environmental impact while maximizing yield. Our team is dedicated to maintaining high safety standards and implementing sustainable practices throughout the mining process. Additionally, we invest in research and development to explore innovative methods for lignite liquefaction, which allows us to diversify our product offerings and improve the quality of our output for various industrial applications.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.503148537350321e-05, 'A': 3.448051237374261e-05, 'F': 1.2412447065314206e-05, 'B': 0.9998908824174186, 'J': 7.193137768603304e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957333425246, 6: 1.3467271961789663e-06, 7: 2.9199302792357865e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023580672422552286, 5.2: 0.9976419327577448}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  1%|█                                                                                                                                                                                | 5/788 [00:00<00:52, 14.93it/s]

RAPS scores:

==================================================
Description 1:
  We specialize in the mining and beneficiation of iron ores, providing high-quality raw materials for the steel industry. Our operations are characterized by a commitment to safety and efficiency, utilizing modern equipment and methodologies to extract ore from diverse geological formations. The beneficiation process involves advanced techniques such as hydrocycloning and magnetic separation, which enhance the iron content of the ore. Our products are tailored to meet the specific needs of our clients, ensuring they receive optimal materials for their steel production processes.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5837129810885735e-05, 'A': 3.3918756635380384e-05, 'F': 1.2290818690856052e-05, 'B': 0.9998908175931484, 'J': 7.135701714439715e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4721765557174767e-06, 6: 1.583336314793463e-06, 7: 0.9999959444871296}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677929595706356, 7.2: 0.03220704042936439}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 2:
  Our business is dedicated to the collection of molluscs along the intertidal zones of coastal regions. We employ a team of trained divers and gatherers who hand-harvest species such as clams, oysters, and mussels, ensuring that our practices are sustainable and compliant with local regulations. The harvested shellfish are then transported to our processing facility, where they undergo rigorous quality checks before being shipped to seafood markets and restaurants. We also engage in educational initiatives to raise awareness about the importance of preserving marine habitats while promoting the benefits of consuming locally sourced seafood.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.07465282748552494, 'A': 0.13404786816033284, 'F': 0.6683756219112149, 'B': 0.10948733530626822, 'J': 0.013436347136659131}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3316243780887851}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 3:
  Specializing in the gathering of lac and resins, we have established a supply chain that connects traditional gatherers with modern manufacturing processes. Our team works closely with local artisans who harvest these natural products from trees, ensuring that the collection methods are sustainable and do not deplete resources. The resins are then processed and used in a range of applications, from cosmetics to varnishes. Our commitment to quality and sustainability has allowed us to build a loyal customer base that values natural ingredients in their products.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9996857631002033, 'A': 1.7929748377312788e-05, 'F': 2.1416298337789778e-05, 'B': 0.00013197172132521027, 'J': 0.00014291913175660045}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003142368997967049}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 4:
  We are dedicated to the extraction of crude petroleum, employing a diverse array of methods including traditional drilling and enhanced oil recovery techniques. Our operations are supported by a fleet of specialized vessels and rigs equipped with cutting-edge technology to ensure efficient extraction. We prioritize safety and environmental stewardship, implementing rigorous protocols to minimize the impact of our activities. Our research and development team continuously explores innovative solutions, such as carbon capture and storage, to align our extraction processes with global sustainability goals. By doing so, we aim to provide reliable energy while safeguarding natural resources.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.507831954989567e-05, 'A': 3.4687824579361275e-05, 'F': 1.2478748937751693e-05, 'B': 0.9998905286964539, 'J': 7.226410478954426e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010947130354610479}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  1%|█▌                                                                                                                                                                               | 7/788 [00:00<01:08, 11.45it/s]

RAPS scores:

==================================================
Description 5:
  In the crude petroleum extraction landscape, our firm stands out for its commitment to innovation and sustainability. We utilize a range of extraction techniques, including directional drilling and hydraulic fracturing, to maximize oil recovery while minimizing environmental impact. Our research and development team is constantly exploring new technologies, such as artificial intelligence for predictive maintenance, to enhance operational efficiency. Furthermore, we actively engage in community development projects, ensuring that our extraction activities contribute positively to the local economy and environment.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.462134281700643e-05, 'A': 3.492604223531527e-05, 'F': 1.249310882299145e-05, 'B': 0.9998907214535158, 'J': 7.238052608941933e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7675239039729478e-06, 6: 0.9999964187424647, 7: 1.8137336312806623e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.002059167840486812, 6.1: 0.9979408321595132}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 6:
  Our company is at the forefront of mining zinc and copper ores, leveraging innovative extraction methods to enhance productivity and reduce costs. We utilize a combination of traditional mining techniques and modern technologies, such as automated drilling and real-time data analytics, to optimize our operations. The ores extracted are processed in our advanced smelting facilities, where we produce high-grade zinc and copper products. These metals are essential for a wide range of applications, including electrical wiring and construction materials. Our commitment to sustainability drives us to implement eco-friendly practices throughout our supply chain, ensuring minimal environmental impact.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5088683136532374e-05, 'A': 3.4442895199956034e-05, 'F': 1.2383261163562013e-05, 'B': 0.9998909172312519, 'J': 7.1679292480237565e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4672992629491544e-06, 6: 1.5897690549204673e-06, 7: 0.9999959429316821}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0351465482696776, 7.2: 0.9648534517303223}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 7:
  Our focus on crude petroleum extraction is driven by a commitment to operational excellence and environmental responsibility. We utilize advanced reservoir simulation software to optimize extraction strategies, ensuring maximum yield from each site. Our drilling operations are supported by a fleet of modern rigs equipped with the latest safety features, reducing the risk of accidents. By investing in renewable energy projects alongside our petroleum activities, we aim to diversify our energy portfolio and contribute to a sustainable energy future while meeting current market demands.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4854328217610703e-05, 'A': 3.49847604319954e-05, 'F': 1.252252900107996e-05, 'B': 0.9998903894054918, 'J': 7.248976857592125e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010961059450820265}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 8:
  Specializing in the capture of freshwater species, our business utilizes both traditional and innovative fishing methods to ensure a sustainable yield. We focus on species like perch and bass, employing catch-and-release practices to support conservation efforts. Our operations include partnerships with local fishing clubs to promote awareness of sustainable practices among recreational anglers. The fish we do harvest are processed and sold directly to consumers through farmers' markets, emphasizing our commitment to freshness and community engagement.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 5.9568615995570744e-05, 'A': 0.9993690390802876, 'F': 0.00018878796887279362, 'B': 0.00032556725218904663, 'J': 5.7037082654954044e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0006309609197123756}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  2%|██▋                                                                                                                                                                             | 12/788 [00:00<00:51, 14.97it/s]

RAPS scores:

==================================================
Description 9:
  Our company is at the forefront of sustainable fishing practices, specializing in the collection of mollusks along intertidal shorelines. We employ hand-harvesting techniques that allow us to gather species such as clams and oysters without damaging their habitats. Our commitment to environmental stewardship is evident in our partnerships with local conservation groups to monitor and protect marine ecosystems. The mollusks we collect are processed and packaged for sale in premium seafood markets, where they are valued for their quality and sustainability.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0014965033743006772, 'A': 0.9461068734603599, 'F': 0.0031301671212172677, 'B': 0.048435712221813386, 'J': 0.0008307438223086054}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05389312653964007}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 10:
  Our company is dedicated to the collection of mosses and lichens from pristine natural areas, which are used in various applications, including horticulture and crafts. We prioritize sustainable harvesting methods that protect the delicate ecosystems from which we gather. By educating our customers about the ecological importance of these materials, we foster a greater appreciation for their natural origins. Our unique product offerings cater to niche markets, allowing us to create a strong brand identity centered around sustainability and environmental stewardship.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0026835088896248016, 'A': 0.8366421249081645, 'F': 0.15265302769426656, 'B': 0.006041626235172167, 'J': 0.001979712272771999}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.16335787509183552}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 11:
  Our company is at the forefront of hard coal mining, employing a range of extraction methods tailored to the geological conditions of our mining sites. We focus on maximizing resource recovery while minimizing environmental impact through responsible mining practices. Our processing facilities are designed to clean and size coal efficiently, ensuring that we deliver high-quality products that meet market demands. By investing in technology and workforce training, we enhance our operational efficiency and safety, creating a sustainable business model that supports both our growth and the communities we serve.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.511898629381631e-05, 'A': 3.4523634469065036e-05, 'F': 1.2393142552809932e-05, 'B': 0.9998908138787164, 'J': 7.150357967765462e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995728071861, 6: 1.341229269449874e-06, 7: 2.9306988695320982e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975271463124828, 5.2: 0.0024728536875171605}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

  2%|███▏                                                                                                                                                                            | 14/788 [00:01<00:54, 14.30it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 12:
  Focused on the mining of molybdenum ores, our company employs advanced extraction techniques that maximize yield while minimizing environmental impact. We have implemented a comprehensive sustainability strategy that includes habitat restoration and water conservation practices. Our processing facilities utilize cutting-edge technology to produce high-purity molybdenum products for the steel and chemical industries. Additionally, we invest in research to explore new applications for molybdenum, which could lead to innovative solutions in energy efficiency and material science, further enhancing our value proposition in the market.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.521615177056135e-05, 'A': 3.4183324448843146e-05, 'F': 1.2331292868072102e-05, 'B': 0.9998911336000976, 'J': 7.135630814763006e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4867607995650047e-06, 6: 1.57289384958527e-06, 7: 0.9999959403453509}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03515540654637552, 7.2: 0.9648445934536244}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 13:
  We are involved in the manufacture of beverages derived from non-perennial crops, such as fruit juices and herbal teas. Our sourcing practices emphasize local and organic ingredients, ensuring that our products are both flavorful and environmentally friendly. We invest in cutting-edge processing technologies that preserve the natural qualities of our ingredients, resulting in high-quality beverages that resonate with health-conscious consumers. Our marketing strategies highlight the benefits of our products, fostering a strong connection with our customer base.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9997758039548529, 'A': 1.1961723019490815e-05, 'F': 1.444663612749241e-05, 'B': 6.777853758878198e-05, 'J': 0.0001300091484113441}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002241960451471181}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 14:
  We specialize in the collection of balata and other rubber-like gums from tropical trees, which are harvested using traditional methods that respect the trees' health and longevity. Our products are processed into high-quality rubber compounds that are used in various industries, including footwear, adhesives, and coatings. By maintaining close relationships with local communities, we ensure fair trade practices and provide training on sustainable harvesting techniques. Our commitment to ethical sourcing and environmental stewardship sets us apart in the marketplace, appealing to eco-conscious brands seeking natural rubber alternatives.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.999674253264088, 'A': 1.8755186372038796e-05, 'F': 2.5761607949419664e-05, 'B': 0.00011602381719955298, 'J': 0.00016520612439111207}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00032574673591201364}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 15:
  Our business is dedicated to the collection of shellfish along the intertidal zones of coastal areas, where we harvest mussels and oysters using environmentally friendly methods. We employ divers and hand-harvesting techniques to ensure minimal disruption to the marine environment. Our operations are supported by rigorous sustainability practices, including monitoring shellfish populations and adhering to seasonal harvesting guidelines. The shellfish are then transported to our processing facility, where they are cleaned, sorted, and packaged for distribution to local seafood markets and restaurants. This direct-to-consumer approach not only supports local economies but also promotes the consumption of fresh, sustainably sourced seafood.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.01445229813708489, 'A': 0.012408904936500894, 'F': 0.0060766554392138366, 'B': 0.9659816822748657, 'J': 0.0010804592123345184}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.034018317725134306}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

  2%|████▏                                                                                                                                                                           | 19/788 [00:01<00:53, 14.47it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 16:
  We are dedicated to the mining and processing of iron ores, focusing on sustainable practices that reduce our carbon footprint. Our team employs cutting-edge technologies for ore extraction, including automated drilling systems and remote monitoring tools that enhance operational efficiency. The iron ore we produce undergoes rigorous beneficiation processes, such as flotation and agglomeration, to improve its purity and market value. Our commitment to environmental stewardship is reflected in our reclamation efforts, which restore mined areas to their natural state post-extraction.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5071317007328165e-05, 'A': 3.43574839860907e-05, 'F': 1.2351998117587518e-05, 'B': 0.9998910557928581, 'J': 7.163408030835549e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4651107719153425e-06, 6: 1.5902391249290493e-06, 7: 0.9999959446501032}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677664968318724, 7.2: 0.032233503168127633}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 17:
  Our operations in the mining of aluminum ores are characterized by a commitment to sustainable practices and technological innovation. We utilize advanced bauxite refining processes that minimize waste and energy consumption while maximizing yield. Our dedicated research team is focused on developing new methods for ore processing that further enhance efficiency and reduce our carbon footprint. Additionally, we engage with local communities to foster economic growth and provide educational opportunities, ensuring that our mining activities contribute positively to the regions in which we operate.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.538489844419519e-05, 'A': 3.406327288294858e-05, 'F': 1.2274324623072658e-05, 'B': 0.9998911837216381, 'J': 7.09378241156199e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.459014762956082e-06, 6: 1.5969146307881877e-06, 7: 0.9999959440706063}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03511948947560122, 7.2: 0.9648805105243987}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 18:
  Our company is dedicated to the production of high-quality beverages derived from non-perennial crops, particularly fruit juices and herbal teas. We source our ingredients from local farmers, ensuring freshness and supporting the agricultural community. Our processing facilities utilize cold-press technology to preserve the nutritional integrity of the fruits, resulting in premium beverages that appeal to health-conscious consumers. We prioritize sustainable practices in our production processes, including eco-friendly packaging and waste reduction initiatives, reinforcing our commitment to environmental responsibility while delivering exceptional products to the market.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.99965391412655, 'A': 2.0587214105802404e-05, 'F': 2.7547475575864536e-05, 'B': 0.00013586495459068978, 'J': 0.00016208622917752373}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.000346085873449975}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  3%|████▉                                                                                                                                                                           | 22/788 [00:01<00:51, 14.91it/s]

RAPS scores:

==================================================
Description 19:
  We specialize in the farming of alligators, focusing on both meat production and leather harvesting. Our facilities are designed to mimic natural habitats, promoting healthy growth and welfare of the animals. We implement strict biosecurity measures to prevent disease and ensure the highest standards of animal care. Our alligator products are marketed to high-end restaurants and fashion brands, emphasizing quality and sustainability. We also engage in educational outreach, informing the public about the importance of alligator farming in conservation efforts and local economies.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.017278777449649993, 'A': 0.46060611230507925, 'F': 0.026937448664863434, 'B': 0.49124499598791743, 'J': 0.0039326655924899695}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5087550040120825}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 20:
  Our operations in crude petroleum extraction are characterized by a commitment to technological advancement and environmental responsibility. We utilize advanced drilling techniques, including directional drilling, to access hard-to-reach reserves while minimizing surface disruption. Our team is dedicated to continuous improvement, regularly assessing our extraction methods to enhance efficiency and safety. By integrating sustainable practices into our operations, we aim to provide a reliable energy supply while safeguarding the environment for future generations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4729367083098175e-05, 'A': 3.486845311155193e-05, 'F': 1.2495363387672446e-05, 'B': 0.9998906869747111, 'J': 7.219841706537253e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010931302528893738}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 21:
  As a leader in hard coal mining, our company focuses on the extraction and processing of coal using both underground and surface methods. We employ advanced technologies for cleaning, sizing, and grading coal, ensuring that we produce high-quality products tailored to our customers' needs. Our innovative pulverizing and compressing processes enhance the coal's properties, making it more suitable for transport and storage. By prioritizing sustainability and efficiency, we aim to meet the growing demand for energy while minimizing our environmental impact, solidifying our position in the competitive coal industry.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.538298602177808e-05, 'A': 3.421528616558834e-05, 'F': 1.2352322673099558e-05, 'B': 0.9998908665534197, 'J': 7.182851719851773e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957234204427, 6: 1.3280804400206202e-06, 7: 2.948499117142243e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975268687060319, 5.2: 0.0024731312939681605}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 22:
  We specialize in the production of turfgrass for sports fields and recreational areas, focusing on varieties that can withstand heavy foot traffic and varying weather conditions. Our advanced growing techniques ensure that our turf is not only durable but also visually appealing. We work closely with sports organizations and landscape architects to provide tailored solutions that meet the specific needs of each project. Our commitment to quality and performance positions us as a trusted partner in the development of high-quality athletic surfaces.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.993671191233844, 'A': 0.0004064467561037338, 'F': 0.0011877606635996392, 'B': 0.003393081525386165, 'J': 0.0013415198210665756}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006328808766156047}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  3%|█████▌                                                                                                                                                                          | 25/788 [00:01<00:51, 14.93it/s]

RAPS scores:

==================================================
Description 23:
  In the realm of coastal fishing, we operate a fleet of small boats that utilize gillnets and traps to catch crabs and lobsters. Our operations are designed to minimize environmental impact, with a focus on sustainable practices that protect juvenile populations and breeding grounds. We collaborate with marine biologists to monitor the health of local crab and lobster stocks, ensuring that our fishing activities do not disrupt the ecosystem. Our products are sold directly to seafood distributors and local markets, where freshness and quality are paramount, allowing us to maintain strong relationships with our customers.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0052508460905797165, 'A': 0.743377094153097, 'F': 0.01835421071004386, 'B': 0.23086390547678767, 'J': 0.0021539435694916164}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.25662290584690295}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 24:
  Focused on the mining of rare non-ferrous metal ores, our company leverages cutting-edge exploration technologies to identify and extract valuable minerals such as lithium and cobalt. We operate multiple mining sites equipped with automated systems that enhance operational efficiency and reduce labor costs. Our processing facilities utilize advanced separation techniques to produce high-purity metal concentrates, which are essential for the production of batteries and electronic components. By investing in research and development, we aim to innovate sustainable mining practices that minimize environmental impact while meeting the growing demand for non-ferrous metals in the technology sector.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5462271400937604e-05, 'A': 3.415664041922487e-05, 'F': 1.2322864047645937e-05, 'B': 0.9998909150185205, 'J': 7.143205611766792e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4583664339116774e-06, 6: 1.5953635158413046e-06, 7: 0.9999959462700502}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03510218415989396, 7.2: 0.9648978158401061}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 25:
  We engage in the traditional methods of charcoal production, sourcing wood from sustainably managed forests to create a high-quality product. Our processes are designed to minimize waste and maximize efficiency, ensuring that our charcoal meets the demands of both local and international markets. By focusing on sustainable practices, we contribute to the preservation of forest resources while providing a valuable energy source for cooking and heating. Our commitment to quality and environmental responsibility sets us apart in the charcoal industry.1. Our company specializes in sustainable logging practices, focusing on the selective harvesting of roundwood to supply both local and international markets. We utilize advanced timber management techniques to ensure that our operations promote forest health and biodiversity. The harvested logs are processed into high-quality lumber and wood products, which are then sold to manufacturers in the construction and furniture industries. Additionally, we have established partnerships with energy companies to provide wood residues for biomass energy production, contributing to renewable energy initiatives while minimizing waste.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9982869170083262, 'A': 7.159828764975673e-05, 'F': 8.987102768031788e-05, 'B': 0.001298742084305025, 'J': 0.00025287159203892044}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001713082991673831}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  4%|██████▎                                                                                                                                                                         | 28/788 [00:01<00:51, 14.77it/s]

RAPS scores:

==================================================
Description 26:
  Our operations in the raising of other animals focus on the breeding and care of alpacas, known for their luxurious fiber. We implement specialized husbandry practices that optimize the health and well-being of our herd, ensuring high-quality fleece production. Our facility includes a fiber processing workshop where we transform raw fleece into finished products, such as yarn and textiles. We also engage in educational programs that promote awareness of sustainable farming practices and the benefits of alpaca fiber. Through these initiatives, we create value for our customers while fostering a deeper appreciation for these unique animals.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0013425890089266658, 'A': 0.9755444057565229, 'F': 0.010758873755357194, 'B': 0.011527071574757707, 'J': 0.0008270599044356878}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.024455594243477097}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 27:
  Our operations focus on the mining of tin ores, where we utilize modern techniques to ensure efficient extraction and processing. We are committed to sustainability, implementing practices that reduce our environmental footprint while maximizing ore recovery. Our tin products are essential for various applications, including electronics and packaging. We invest in research to enhance our processing methods and improve the quality of our output. By collaborating with industry partners, we aim to address the challenges of supply chain sustainability and ensure a reliable supply of tin to meet global demand.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.53661047144863e-05, 'A': 3.406124267430957e-05, 'F': 1.228212897928255e-05, 'B': 0.9998911854869057, 'J': 7.105036726201176e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4576127852821874e-06, 6: 1.601631258326541e-06, 7: 0.9999959407559564}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03515966057736449, 7.2: 0.9648403394226355}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 28:
  In the realm of freshwater aquaculture, our firm focuses on the cultivation of tilapia and catfish in controlled environments. We leverage state-of-the-art pond management techniques and biosecurity measures to maximize yield while minimizing disease risks. Our approach includes the use of organic feed and natural supplements to enhance fish growth and improve the nutritional profile of our products. By employing advanced breeding programs, we ensure a consistent supply of high-quality fingerlings. Our commitment to sustainability is reflected in our efforts to reduce water usage and implement eco-friendly practices, positioning us as a leader in responsible freshwater fish farming.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0005022241209793298, 'A': 0.9929109119082193, 'F': 0.0026190207338130343, 'B': 0.003622424984128853, 'J': 0.00034541825285955725}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00708908809178066}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 29:
  Our business is centered on the raising of camels, focusing on both milk production and tourism. We have developed a unique breeding program that emphasizes the health and productivity of our herd, enabling us to produce high-quality camel milk, which is known for its nutritional benefits. Additionally, we offer camel rides and educational experiences for visitors, showcasing the cultural significance of these animals. Our commitment to sustainable practices includes using renewable resources for our operations and promoting awareness about the importance of camel husbandry in arid regions. Through these initiatives, we contribute to local economies while preserving traditional practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00030277937960651434, 'A': 0.9954022324903051, 'F': 0.0015931647205518688, 'B': 0.0024646536766901404, 'J': 0.00023716973284634867}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.004597767509694872}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  4%|███████▌                                                                                                                                                                        | 34/788 [00:02<00:39, 19.22it/s]

RAPS scores:

==================================================
Description 30:
  Our business is dedicated to the cultivation of root and tuber crops, including potatoes and sweet potatoes, which are staples in many diets worldwide. We implement advanced irrigation techniques and soil management practices to enhance crop quality and yield. Our products are harvested and processed in facilities that adhere to stringent food safety standards, ensuring that they reach consumers in peak condition. We also engage in community initiatives to promote healthy eating and educate consumers about the nutritional value of root vegetables.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.17345889360161484, 'A': 0.011670471890948355, 'F': 0.021382794439307674, 'B': 0.7901875267620093, 'J': 0.0033003133061197502}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.20981247323799068}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 31:
  We specialize in the production of firewood, catering to both residential and commercial markets. Our firewood is sourced from a mix of hardwood and softwood species, ensuring a high heat output and longer burn times. We utilize a combination of traditional and modern processing techniques to cut, season, and package our firewood, making it convenient for consumers. Our commitment to sustainability is reflected in our practices, as we ensure that our firewood is sourced from managed forests, promoting reforestation and biodiversity.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9996597699133558, 'A': 2.0406123526368127e-05, 'F': 2.5779697907317463e-05, 'B': 0.0001333839234332663, 'J': 0.00016066034177749926}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00034023008664418875}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 32:
  Engaging in freshwater fishing, our company utilizes innovative techniques to capture a diverse range of species from lakes and rivers. We employ eco-friendly fishing gear designed to minimize bycatch and habitat disruption. Our operations include seasonal fishing expeditions, where we gather species such as trout and catfish, which are then processed and packaged for distribution. We also offer guided fishing tours, educating participants on sustainable practices while providing an enjoyable outdoor experience. This dual approach not only generates revenue but also fosters a deeper appreciation for freshwater ecosystems among our customers.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0003115559595567368, 'A': 0.9930750063256952, 'F': 0.0007678735352491849, 'B': 0.005610909661241773, 'J': 0.00023465451825705188}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006924993674304769}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 33:
  We focus on the collection of lac and resins, which are harvested from specific tree species in a manner that ensures the health of the trees and surrounding ecosystems. Our products are used in various industries, including cosmetics, pharmaceuticals, and food. We emphasize the importance of ethical sourcing and work closely with local harvesters to provide fair compensation and training in sustainable practices. By promoting the unique properties of our lac and resin products, we aim to expand our market reach while supporting traditional harvesting methods.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9989635129703175, 'A': 5.6151394670433635e-05, 'F': 0.00010142207129651777, 'B': 0.0005803455674741722, 'J': 0.0002985679962411623}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001036487029682509}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 34:
  Our company focuses on the sustainable management of forest resources, emphasizing the importance of thinning and conservation practices. By selectively removing trees, we enhance the growth potential of remaining trees, leading to healthier forests and increased timber yields. Our team employs advanced monitoring technologies to assess forest health and growth patterns, allowing us to make informed decisions that benefit both our business and the environment. This proactive approach not only maximizes profitability but also ensures that we are stewards of the land for future generations.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.403024490526634e-05, 'A': 0.9995802969878659, 'F': 0.0002528139090528841, 'B': 9.41255645891983e-05, 'J': 3.873329358689456e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00041970301213412053}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 35:
  Our company is dedicated to the cultivation of high-quality tobacco, utilizing traditional growing methods combined with innovative agricultural technologies. We focus on producing a variety of tobacco types, catering to both the domestic and international markets. Our commitment to quality control is evident in our rigorous testing protocols, which ensure that our products meet the highest standards. Additionally, we engage in sustainable farming practices, including soil conservation and responsible water usage, to minimize our environmental impact while supporting the livelihoods of our farmers.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9941596123967579, 'A': 0.00026504466587213264, 'F': 0.0005066359131053233, 'B': 0.004387266383432296, 'J': 0.0006814406408326571}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005840387603242125}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  5%|████████▉                                                                                                                                                                       | 40/788 [00:02<00:37, 19.84it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 36:
  Our business model revolves around the mining and processing of hard coal, where we utilize both underground and surface methods to optimize resource extraction. We focus on enhancing the quality of our coal through rigorous cleaning, sizing, and grading processes, supported by advanced pulverizing technologies. Our commitment to innovation includes the implementation of liquefaction techniques that improve coal transport and storage efficiency. By prioritizing sustainability and operational excellence, we aim to provide our clients with a reliable source of high-quality coal for their energy and industrial needs.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.510619393092741e-05, 'A': 3.422957079451679e-05, 'F': 1.233531282541972e-05, 'B': 0.9998911586959587, 'J': 7.1702264904172295e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957188949168, 6: 1.3240115352295849e-06, 7: 2.9570935480970563e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975297679241271, 5.2: 0.002470232075872909}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 37:
  In our commitment to sustainable forestry, we implement comprehensive forest management plans that include regular monitoring and conservation efforts. Our team conducts assessments to determine the optimal timing for thinning and harvesting, ensuring that we maintain a balance between economic viability and ecological integrity. We also engage in community outreach programs to educate local populations about the importance of forest conservation and responsible timber harvesting. By fostering a culture of sustainability, we not only enhance our operational efficiency but also contribute positively to the communities we serve.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 1.9580157420806566e-05, 'A': 0.9997911673424006, 'F': 0.00010397446052363259, 'B': 6.249956140937618e-05, 'J': 2.2778478245512058e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002088326575994115}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 38:
  Our business is centered on the cultivation of beverage crops, particularly coffee and tea. We source our beans and leaves from carefully selected farms that prioritize sustainable practices and fair trade principles. Our commitment to quality is evident in our rigorous selection process, where only the finest crops are chosen for roasting and blending. We also invest in research to explore innovative brewing technologies that enhance flavor extraction, ensuring that our customers enjoy a premium beverage experience with every cup.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.1405531567975957, 'A': 0.015601720247451125, 'F': 0.025173940830225408, 'B': 0.8150716861963084, 'J': 0.003599495928419326}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18492831380369157}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 39:
  Engaged in the mining of nickel ores, our company focuses on producing high-grade nickel products that are vital for stainless steel and battery manufacturing. We utilize advanced mining techniques to extract nickel from both sulfide and laterite ores, ensuring optimal recovery rates. Our processing facilities are equipped with modern hydrometallurgical methods that allow us to produce nickel sulfate, a key ingredient for electric vehicle batteries. By investing in research and development, we continuously seek ways to improve our extraction processes and reduce our environmental footprint, reinforcing our position as a responsible supplier in the non-ferrous metals market.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.649854087662186e-05, 'A': 3.401180287019529e-05, 'F': 1.2329764962804228e-05, 'B': 0.999890006904728, 'J': 7.152986562318574e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010999309527204293}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 40:
  As a prominent player in the hard coal mining sector, we focus on both underground and surface mining techniques to extract valuable resources efficiently. Our operations incorporate liquefaction methods to improve recovery rates while minimizing environmental impact. We have established advanced processing facilities that specialize in cleaning, sizing, and grading coal to ensure optimal quality. Our commitment to innovation extends to our pulverizing processes, enabling us to provide finely processed coal that meets the diverse needs of our clients in energy production and other industries.1. Our company specializes in the extraction of hard coal through both surface and underground mining operations. Utilizing advanced drilling technologies and automated machinery, we ensure efficient and safe mining practices. Once extracted, the coal undergoes rigorous cleaning and sizing processes at our state-of-the-art facilities, where we employ cutting-edge pulverizing and compressing techniques. This not only enhances the quality of the coal but also prepares it for optimal transport and storage solutions. Our commitment to sustainability is reflected in our efforts to minimize environmental impact while maximizing resource recovery, positioning us as a leader in the coal mining sector.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.529884458723026e-05, 'A': 3.431109514240979e-05, 'F': 1.2362799307040894e-05, 'B': 0.9998908415403707, 'J': 7.185720592816029e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957283357475, 6: 1.3412797950437756e-06, 7: 2.930384457295008e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975260298163362, 5.2: 0.0024739701836637004}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  5%|█████████▌                                                                                                                                                                      | 43/788 [00:02<00:57, 13.04it/s]

RAPS scores:

==================================================
Description 41:
  Specializing in the extraction of nickel ores, our company employs innovative mining techniques that prioritize efficiency and environmental responsibility. We utilize advanced geological modeling to identify optimal extraction sites, reducing the environmental footprint of our operations. Our processing facilities are equipped with cutting-edge technology that enables us to produce high-purity nickel products for the battery and aerospace industries. We are committed to sustainability, implementing initiatives such as reforestation and water conservation programs to support local ecosystems. Our focus on research and development drives continuous improvement in our processes, ensuring we meet the evolving demands of the market.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.50288298909254e-05, 'A': 3.433605669650191e-05, 'F': 1.2344062202550601e-05, 'B': 0.9998911455273963, 'J': 7.145523813790836e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.455927589900514e-06, 6: 1.612455929679164e-06, 7: 0.9999959316164803}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0350983607333619, 7.2: 0.9649016392666381}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 42:
  We are engaged in the extraction of natural gas, focusing on maximizing recovery rates through the use of innovative technologies such as 3D seismic imaging and precision drilling. Our operations extend to the separation of liquid hydrocarbon fractions, where we employ advanced processing techniques to enhance product purity. Additionally, our commitment to sustainability is reflected in our gas desulphurization initiatives, which reduce harmful emissions and improve the environmental footprint of our operations, thereby creating value for both our stakeholders and the communities we serve.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.493844924914027e-05, 'A': 3.4605502221548736e-05, 'F': 1.2452040048344956e-05, 'B': 0.9998907911048688, 'J': 7.2129036122615265e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7781855747219469e-06, 6: 0.9999964100144604, 7: 1.811799964992365e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979784027899303, 6.1: 0.002021597210069592}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  6%|██████████▋                                                                                                                                                                     | 48/788 [00:03<00:48, 15.19it/s]

RAPS scores:

==================================================
Description 43:
  We specialize in the extraction and processing of natural gas, utilizing advanced drilling technologies that minimize environmental disruption. Our facilities are equipped with sophisticated gas desulphurization systems that ensure the delivery of high-purity natural gas to our customers. We have also implemented real-time monitoring systems that allow us to optimize production processes and quickly address any operational challenges. Our commitment to innovation and sustainability drives us to continuously improve our methods, ensuring that we remain at the forefront of the natural gas industry.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.521757807818563e-05, 'A': 3.442252563812005e-05, 'F': 1.2420621717609455e-05, 'B': 0.9998907386137237, 'J': 7.200660842574994e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.775627563528437e-06, 6: 0.9999963943736602, 7: 1.8299987762296004e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979649898138476, 6.1: 0.0020350101861524488}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 44:
  Engaged in the hard coal mining sector, our company utilizes a blend of traditional and modern extraction methods to optimize resource recovery. We have implemented advanced technologies for coal cleaning and grading, which not only enhance product quality but also streamline transport and storage processes. Our commitment to sustainability is reflected in our operational practices, as we strive to minimize environmental impact while maximizing economic benefits for our stakeholders. By focusing on innovation and efficiency, we aim to remain a key player in the global coal market.1. Our company specializes in the extraction and processing of hard coal, utilizing advanced underground mining techniques to ensure minimal environmental impact while maximizing yield. We employ state-of-the-art equipment for drilling and blasting, followed by efficient coal transportation systems that facilitate quick delivery to processing facilities. Once extracted, the coal undergoes rigorous cleaning and sizing processes to enhance quality and meet stringent industry standards. Our commitment to innovation is reflected in our investment in liquefaction methods, which allow us to produce cleaner, more efficient coal products for both domestic and international markets.
True: section=B, division=5, class=5.1
Section set: []
Section probs: {'C': 5.540095264030415e-05, 'A': 3.445483913458739e-05, 'F': 1.2417601483211394e-05, 'B': 0.9998904947035063, 'J': 7.231903235553167e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010950529649367269}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 45:
  Our company is dedicated to the cultivation of spices, aromatic, drug, and pharmaceutical crops, including turmeric, ginger, and basil. We employ organic farming methods to produce high-quality herbs and spices that meet the growing demand for natural ingredients in food and wellness products. Our crops are harvested and processed on-site to preserve their freshness and potency. We partner with manufacturers to supply raw materials for dietary supplements and herbal remedies, contributing to the health and wellness industry. Our focus on sustainability and quality has positioned us as a trusted supplier in this niche market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.36268550473832795, 'A': 0.008883815621594253, 'F': 0.013605585643462611, 'B': 0.6110804348038084, 'J': 0.0037446591928067445}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.38891956519619164}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 46:
  Engaging in freshwater fishing, our business focuses on the collection of high-quality fish species from lakes and rivers. We utilize a mix of traditional and modern fishing gear, such as nets and rods, to ensure minimal impact on local ecosystems. Our team is dedicated to maintaining biodiversity by adhering to seasonal catch limits and participating in restocking initiatives. We also offer guided fishing tours, providing enthusiasts with the opportunity to experience the thrill of fishing while educating them on sustainable practices. Our products are sold directly to consumers and local fish markets, emphasizing freshness and quality.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00012147701359228541, 'A': 0.9984481008992477, 'F': 0.00040120389422955714, 'B': 0.0009234659069482415, 'J': 0.00010575228598219757}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0015518991007522631}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 47:
  Engaging in the farming of alligators, our company operates a unique aquaculture venture that combines traditional farming practices with modern techniques. We focus on breeding and raising alligators in controlled environments that mimic their natural habitats, ensuring their health and well-being. Our operations include hatcheries, grow-out facilities, and processing plants, where we produce high-quality leather and meat products. By adhering to strict ethical standards and sustainability practices, we not only provide valuable products but also contribute to the conservation of alligator populations and their ecosystems.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00014274789338771917, 'A': 0.9980682637292945, 'F': 0.0006481016545674657, 'B': 0.0010175083717232053, 'J': 0.00012337835102728956}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0019317362707055308}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  6%|███████████▍                                                                                                                                                                    | 51/788 [00:03<00:42, 17.53it/s]

RAPS scores:

==================================================
Description 48:
  We specialize in the production of ornamental grasses and perennials, providing a diverse selection for landscape designers and garden enthusiasts. Our nursery employs environmentally friendly practices, utilizing organic fertilizers and responsible water management techniques to promote plant health. We offer a wide range of products, including drought-tolerant and low-maintenance varieties, ideal for sustainable landscaping solutions. Our knowledgeable staff provides personalized service and expert advice, helping clients select the right plants for their specific projects. Through our commitment to quality and sustainability, we aim to enhance outdoor spaces while supporting biodiversity.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9995058488070095, 'A': 3.022274726899328e-05, 'F': 4.7717116972215596e-05, 'B': 0.0001823446210864336, 'J': 0.00023386670766287518}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0004941511929904552}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 49:
  ForestCare Inc. is at the forefront of reforestation efforts, focusing on the cultivation of diverse tree species to enhance forest resilience. Our team is involved in the complete lifecycle of forest management, from planting and transplanting to thinning operations that encourage healthy growth. We also run a state-of-the-art tree nursery, where we produce seedlings tailored for various environmental conditions. This not only supports our timber operations but also aids in restoring degraded landscapes, showcasing our commitment to environmental stewardship.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 1.9489860215694113e-05, 'A': 0.9997877156442715, 'F': 0.00011376324227988332, 'B': 5.616244203487936e-05, 'J': 2.2868811198061318e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00021228435572850923}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 50:
  We engage in the comprehensive management of lignite resources, from extraction to final delivery. Our operations include the meticulous planning of mining schedules to maximize output while adhering to safety and environmental standards. After extraction, our lignite undergoes processing to improve its calorific value, making it more attractive to energy producers. By controlling the entire supply chain, we ensure that our clients receive a consistent and high-quality product that meets their energy demands.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.51458787056362e-05, 'A': 3.469629090699621e-05, 'F': 1.2509268517240833e-05, 'B': 0.9998904303278522, 'J': 7.218234018082329e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010956967214781344}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 51:
  We are engaged in the mining of zinc ores, utilizing a combination of underground and open-pit mining methods to maximize ore recovery. Our processing facilities are equipped with advanced flotation technology, which allows us to produce high-quality zinc concentrates. We prioritize safety and environmental stewardship in our operations, implementing rigorous monitoring systems to manage waste and emissions. By collaborating with industries that rely on zinc for galvanization and alloy production, we create value through the reliable supply of essential materials that support infrastructure development and manufacturing.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5560214285761854e-05, 'A': 3.41202486203634e-05, 'F': 1.2308235167223253e-05, 'B': 0.9998908780322022, 'J': 7.133269724366491e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.466986922448471e-06, 6: 1.5898911077222722e-06, 7: 0.9999959431219697}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0351420896225564, 7.2: 0.9648579103774436}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

  7%|████████████                                                                                                                                                                    | 54/788 [00:03<00:49, 14.77it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 52:
  Specializing in natural gas extraction, our company utilizes a range of advanced technologies to optimize our production processes. We conduct comprehensive geological surveys to identify viable drilling locations and employ hydraulic fracturing techniques to enhance gas recovery. Our processing facilities are equipped with the latest technology for the separation and purification of natural gas, ensuring compliance with regulatory standards. We are committed to minimizing our environmental impact, implementing best practices in waste management and emissions control. Our focus on innovation drives us to continuously improve our operations, positioning us as a leader in the sustainable energy landscape.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.484331843090231e-05, 'A': 3.4632284882713126e-05, 'F': 1.243841002562181e-05, 'B': 0.9998908849522153, 'J': 7.201034445493569e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7637260356755383e-06, 6: 0.9999964252435729, 7: 1.8110303912815958e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979597911552106, 6.1: 0.002040208844789434}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 53:
  We specialize in the raising of other cattle and buffaloes, focusing on both meat and dairy production. Our approach combines traditional farming methods with modern technology, ensuring the health and productivity of our livestock. We prioritize animal welfare and environmental sustainability, employing rotational grazing practices that enhance soil health and reduce carbon footprints. Our products are marketed directly to consumers through local farmers' markets, allowing us to build strong relationships with our community while promoting the benefits of locally sourced meat and dairy.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.013871655734658329, 'A': 0.6764645147699256, 'F': 0.02594410116368889, 'B': 0.2799445467196622, 'J': 0.003775181612065013}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.32353548523007436}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 54:
  Our aquaculture business is dedicated to the ethical farming of diverse aquatic species, including fish, molluscs, and crustaceans. We implement comprehensive management practices that encompass breeding, feeding, and harvesting, all while adhering to strict environmental regulations. Our facilities are designed for optimal biosecurity and sustainability, with a focus on minimizing waste and energy consumption. We actively participate in community initiatives aimed at promoting sustainable seafood consumption and educating consumers about the benefits of aquaculture. Our commitment to quality and environmental stewardship has established us as a trusted provider in the seafood market.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of various fish species, including salmon and tilapia. We utilize advanced recirculating aquaculture systems (RAS) that enable us to maintain optimal water quality and reduce environmental impact. Our operations include not only the breeding and rearing of fish but also the implementation of innovative feeding techniques that promote faster growth rates. By employing biosecurity measures, we ensure the health of our stock while maximizing yield. Our commitment to sustainability is reflected in our partnerships with environmental organizations, ensuring that our practices align with responsible aquaculture standards.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0015028089194213184, 'A': 0.9761991452207899, 'F': 0.005104461421552506, 'B': 0.016404356766429005, 'J': 0.0007892276718073572}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.023800854779210123}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  7%|████████████▌                                                                                                                                                                   | 56/788 [00:03<00:46, 15.69it/s]

RAPS scores:

==================================================
Description 55:
  In the realm of plant propagation, our company excels in producing high-quality mushroom spawn for both commercial and home cultivation. Utilizing sterile techniques and a controlled environment, we cultivate a range of mushroom species, ensuring consistent quality and high germination rates. Our spawn is distributed to farmers and hobbyists alike, providing them with the tools needed to grow gourmet mushrooms. We also offer workshops and resources to educate our customers on best practices for mushroom cultivation, fostering a community of mushroom enthusiasts.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.27163392398565733, 'A': 0.10224350978012442, 'F': 0.22374368255216254, 'B': 0.38683600310688876, 'J': 0.015542880575166966}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.6131639968931113}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 56:
  Our company is at the forefront of crude oil extraction, utilizing innovative technologies such as horizontal drilling and multi-well pads to optimize production. By reducing the environmental footprint of our operations, we strive to balance energy needs with ecological responsibility. Our team of experts continuously monitors extraction sites using drone technology, allowing for real-time assessments of operational efficiency and safety compliance. We also engage in comprehensive training programs for our workforce, ensuring they are equipped with the skills necessary to operate advanced extraction equipment safely.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4889757618015154e-05, 'A': 3.5097580290814674e-05, 'F': 1.2555991938059116e-05, 'B': 0.9998901865893278, 'J': 7.270080825305039e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010981341067217709}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 57:
  We are dedicated to the raising of swine, employing modern farming technologies to enhance productivity and animal health. Our facilities are designed with biosecurity measures that minimize disease risks while maximizing the comfort of our pigs. We implement a comprehensive nutrition program tailored to different growth stages, ensuring optimal weight gain and feed efficiency. Our commitment to sustainability is reflected in our waste management practices, which convert by-products into renewable energy. Through partnerships with local processors, we ensure that our pork products meet the highest quality standards, providing consumers with safe and nutritious options.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.012957992401897286, 'A': 0.7011092430059876, 'F': 0.044712719362313115, 'B': 0.23739287272911153, 'J': 0.003827172500690281}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.29889075699401235}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  8%|█████████████▌                                                                                                                                                                  | 61/788 [00:04<00:53, 13.64it/s]

RAPS scores:

==================================================
Description 58:
  We are a leading player in the iron ore mining sector, dedicated to the sustainable extraction and processing of high-quality ores. Our operations involve detailed exploration and assessment of mineral deposits, followed by the implementation of advanced mining techniques that enhance efficiency. Our beneficiation processes include comprehensive crushing and magnetic separation, resulting in premium iron ore concentrates. By fostering strong relationships with our customers and continuously improving our operations, we aim to deliver exceptional value and support the growth of the steel industry.1. Our company specializes in the extraction and processing of high-grade iron ores, focusing on sustainable mining practices that minimize environmental impact. We employ state-of-the-art drilling and blasting techniques to efficiently access ore deposits, ensuring optimal recovery rates. Our beneficiation process involves advanced crushing and screening technologies that enhance the quality of the iron concentrate, making it suitable for various industrial applications. We also invest in research and development to innovate our mining methods, aiming to increase efficiency and reduce costs while adhering to strict safety regulations.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.493969877124257e-05, 'A': 3.4318672526759284e-05, 'F': 1.234088531294528e-05, 'B': 0.9998912426964932, 'J': 7.158046895880354e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4532005167276333e-06, 6: 1.6061113684074643e-06, 7: 0.9999959406881148}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677848397256893, 7.2: 0.03221516027431072}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 59:
  Our iron ore mining operations are characterized by a strong emphasis on technological advancement and sustainability. We have implemented a state-of-the-art beneficiation process that allows us to efficiently separate iron from impurities, resulting in high-purity ore suitable for steel production. Our engineering team collaborates with external consultants to continually refine our processes and ensure compliance with environmental regulations. Additionally, we conduct regular technical testing and analysis to maintain the quality of our products, reinforcing our position as a trusted supplier in the industry.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.561905164168411e-05, 'A': 3.392326618951659e-05, 'F': 1.2262637846208999e-05, 'B': 0.9998910804224674, 'J': 7.114621855248743e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.5461021953508073e-06, 6: 1.551449160144151e-06, 7: 0.9999959024486446}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677607918968846, 7.2: 0.032239208103115403}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 60:
  We specialize in the production of roundwood for energy applications, focusing on the collection of wood residues and the harvesting of logs. Our state-of-the-art facilities enable us to efficiently process these materials into biomass fuel and charcoal, catering to both local and international markets. By prioritizing sustainable practices, we ensure that our operations contribute positively to the environment while providing essential energy solutions.1. Our company specializes in the sustainable harvesting of roundwood, focusing on high-quality logs for various forest-based manufacturing industries. We employ advanced logging techniques that minimize environmental impact while maximizing yield. Our operations include selective logging, which ensures that we maintain the ecological balance of the forest. Additionally, we process harvested wood into firewood and utility poles, catering to both residential and commercial markets. By investing in modern machinery and training for our workforce, we enhance efficiency and safety in our operations, while also supporting local economies through job creation.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9996719725257429, 'A': 1.9985806090966447e-05, 'F': 2.4481342375861665e-05, 'B': 0.0001279960077092984, 'J': 0.00015556431808091056}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00032802747425708656}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  8%|██████████████                                                                                                                                                                  | 63/788 [00:04<00:53, 13.57it/s]

RAPS scores:

==================================================
Description 61:
  Our operations in the capture fishery sector are centered around the collection of wild aquatic plants, particularly kelp and other seaweeds. We utilize sustainable harvesting methods that allow us to gather these resources without damaging marine ecosystems. Our products are processed into various forms, including dried seaweed for culinary use and extracts for nutritional supplements. We are committed to educating consumers about the health benefits of seaweeds and their role in sustainable diets. Our partnerships with local chefs and restaurants help promote the versatility of our products in modern cuisine.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.000588371126936835, 'A': 0.0024677838801125803, 'F': 0.0002639041681619325, 'B': 0.9965618782896988, 'J': 0.00011806253508995734}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003438121710301223}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 62:
  Our iron ore mining operations are characterized by a strong focus on efficiency and quality. We implement rigorous quality control measures throughout our beneficiation processes, ensuring that our iron ore products consistently meet industry standards. Our agglomeration facilities are equipped with the latest technology, allowing us to produce iron pellets that offer superior performance in steel production. By fostering strong relationships with our customers and continuously improving our processes, we aim to be the preferred supplier of iron ore for steel manufacturers worldwide.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5988947279145316e-05, 'A': 3.382994238423814e-05, 'F': 1.2244918655965106e-05, 'B': 0.9998908319451201, 'J': 7.1042465606074785e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.489208254667789e-06, 6: 1.5754872765393575e-06, 7: 0.9999959353044688}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.967799888674092, 7.2: 0.03220011132590807}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 63:
  We are engaged in the raising of other animals, including alpacas and llamas, with a focus on fiber production and eco-tourism. Our breeding program aims to enhance fiber quality, which is highly sought after in the textile industry. We offer farm tours and educational experiences that highlight the benefits of sustainable farming practices and the unique characteristics of these animals. Our products, including yarn and handmade garments, are marketed to niche markets that value artisanal craftsmanship. By combining agriculture with tourism, we create a unique value proposition that supports both our business and the local community.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0008009224683456253, 'A': 0.9880089966552706, 'F': 0.005160298010381738, 'B': 0.005507702696479411, 'J': 0.0005220801695224504}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.011991003344729356}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

  8%|██████████████▌                                                                                                                                                                 | 65/788 [00:04<00:54, 13.25it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 64:
  As a leader in the hard coal mining sector, our company employs cutting-edge technologies to optimize both underground and surface mining operations. We prioritize the quality of our coal by implementing thorough cleaning and sizing processes that prepare our product for transport and storage. Our facilities are designed to handle the pulverizing and compressing of coal, allowing us to meet the diverse needs of our clientele, including power generation and industrial manufacturing. By focusing on innovation and sustainability, we aim to enhance our production capabilities while maintaining a commitment to environmental stewardship.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.543753718251887e-05, 'A': 3.414634092496045e-05, 'F': 1.2330840568048003e-05, 'B': 0.9998909319487607, 'J': 7.153332563812601e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957191737274, 6: 1.3313343973994612e-06, 7: 2.9494918751954242e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975282640695602, 5.2: 0.0024717359304397327}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

  9%|███████████████▍                                                                                                                                                                | 69/788 [00:04<01:00, 11.95it/s]

RAPS scores:

==================================================
Description 65:
  Our company specializes in the mining of lithium, a key component for battery production in electric vehicles and renewable energy storage systems. We utilize modern extraction techniques that prioritize sustainability and efficiency, ensuring minimal disruption to the surrounding ecosystem. Our lithium products are essential for the growing demand in the clean energy sector, and we work closely with battery manufacturers to provide high-quality materials that meet their specifications. By investing in research and development, we aim to enhance our extraction processes and expand our market presence, positioning ourselves as a leader in the lithium mining industry.1. Our company specializes in the extraction and processing of uranium ores, utilizing state-of-the-art technologies to ensure efficient and sustainable operations. We employ advanced drilling techniques and in-situ recovery methods to minimize environmental impact while maximizing yield. Our commitment to safety and regulatory compliance is paramount, as we navigate the complexities of mining in this highly regulated sector. By investing in research and development, we continuously enhance our extraction processes, aiming to improve recovery rates and reduce costs. Additionally, we collaborate with local communities to promote responsible mining practices and support regional economic development.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5447947059893215e-05, 'A': 3.423971284696063e-05, 'F': 1.2349442166429788e-05, 'B': 0.9998908171856508, 'J': 7.145712275917634e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.473375081875592e-06, 6: 1.5985365942821717e-06, 7: 0.9999959280883237}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03514281719774502, 7.2: 0.964857182802255}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 66:
  Engaging in artisanal fishing, we focus on the collection of molluscs along the intertidal shoreline. Our team employs traditional hand-harvesting techniques, ensuring minimal impact on the marine ecosystem. We specialize in premium products such as hand-picked mussels and clams, which are marketed to high-end restaurants and gourmet retailers. Our commitment to quality is reflected in our rigorous harvesting standards and traceability practices. Furthermore, we actively participate in local conservation efforts, educating the community about the importance of maintaining healthy coastal environments for future generations.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0018593527171649191, 'A': 0.8938673584929905, 'F': 0.0032429600487527523, 'B': 0.10003194925315903, 'J': 0.0009983794879327278}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10613264150700952}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 67:
  In our pursuit of excellence in hard coal mining, we have adopted a multifaceted approach that includes both surface and underground extraction methods. Our operations are supported by a robust infrastructure that facilitates the cleaning, sizing, and grading of coal, ensuring that we deliver products of the highest quality. We utilize modern pulverizing techniques to enhance the coal's properties for various applications, from energy generation to steel production. Our commitment to innovation and sustainability drives us to continuously improve our processes, enabling us to meet the demands of a dynamic market while protecting the environment.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.484857891809073e-05, 'A': 3.4573823601904994e-05, 'F': 1.2422196953801264e-05, 'B': 0.9998909545458474, 'J': 7.2008546785962156e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957162534677, 6: 1.3166699305527203e-06, 7: 2.967076601821301e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975301380179286, 5.2: 0.0024698619820714128}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 68:
  Our company specializes in the cultivation of premium grapes, focusing on sustainable farming practices that enhance both quality and yield. We employ advanced irrigation techniques and soil management strategies to ensure our vineyards thrive year-round. By integrating precision agriculture technology, we monitor plant health and optimize nutrient delivery, resulting in grapes that are ideal for high-end wine production. Our commitment to organic practices not only meets consumer demand for healthier options but also supports biodiversity in our local ecosystems. We also offer tours and tastings at our vineyard, creating a unique experience that connects consumers with the origins of their favorite wines.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.06797097304042427, 'A': 0.02944220044175954, 'F': 0.020098310241762774, 'B': 0.8792241933697775, 'J': 0.0032643229062759085}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.12077580663022247}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

  9%|███████████████▊                                                                                                                                                                | 71/788 [00:04<00:59, 12.14it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 69:
  Our operations are centered around the mining of titanium ores, where we employ environmentally friendly extraction methods to minimize our impact on surrounding ecosystems. We utilize advanced processing technologies to produce high-purity titanium dioxide, which is essential for various applications, including pigments and aerospace components. Our research initiatives focus on improving the efficiency of our operations and exploring recycling options to recover titanium from end-of-life products. By prioritizing sustainability and innovation, we aim to provide our customers with reliable, high-quality materials while supporting the transition to a more sustainable future.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.552086274978934e-05, 'A': 3.401406463351052e-05, 'F': 1.2292281052554536e-05, 'B': 0.9998910580443441, 'J': 7.114747220218497e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4838863504190423e-06, 6: 1.5767498900722913e-06, 7: 0.9999959393637594}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03513749410801522, 7.2: 0.9648625058919849}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 70:
  We specialize in the mining and processing of lignite, utilizing both surface and underground methods to extract this essential resource. Our operations include comprehensive washing and pulverizing processes that improve the lignite's quality, making it suitable for various industrial applications. Our state-of-the-art warehousing facilities ensure that our processed lignite is stored securely until it is ready for transport. We pride ourselves on our logistical capabilities, which allow us to efficiently deliver our products to clients, supporting their energy generation needs and contributing to their operational success.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.55962157896593e-05, 'A': 3.4212080089901884e-05, 'F': 1.2388679263697365e-05, 'B': 0.9998906192518031, 'J': 7.18377305354804e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938074819688559}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 71:
  Our company specializes in the cultivation of spices and aromatic crops, including basil, oregano, and saffron, which are grown in ideal climates that enhance their flavors. We implement organic farming techniques to ensure that our products are free from harmful chemicals, appealing to health-conscious consumers. Our spices are harvested at peak potency and are sold both fresh and dried, catering to a diverse range of culinary applications. We also engage in educational initiatives that promote the use of spices in cooking, enhancing consumer knowledge and appreciation. Our dedication to quality and sustainability positions us as a preferred supplier in the spice market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.12522001237736521, 'A': 0.007383144517513205, 'F': 0.008786458233719922, 'B': 0.8565042160999388, 'J': 0.002106168771462708}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.14349578390006124}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 10%|████████████████▉                                                                                                                                                               | 76/788 [00:05<00:45, 15.51it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 72:
  Engaging in freshwater fishing, the company operates a network of fishing camps along pristine lakes and rivers, offering guided fishing tours and equipment rentals. They focus on species such as trout, bass, and catfish, promoting catch-and-release practices to conserve local ecosystems. Additionally, the company sells fishing gear and accessories through its retail outlets, providing customers with everything they need for a successful fishing trip. Their eco-friendly approach not only attracts fishing enthusiasts but also educates the public on the importance of preserving freshwater habitats.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1003557662677471e-05, 'A': 0.9999050799882755, 'F': 4.111981664610688e-05, 'B': 2.931534959739399e-05, 'J': 1.3481287818154042e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007477776178091985, 2: 0.0009108530951724702, 3: 0.9983413692870182}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9588924138586349, 3.2: 0.04110758614136503}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 73:
  Our company is committed to marine fishing, focusing on the sustainable capture of diverse fish species from offshore waters. We utilize advanced fishing technology, including sonar and automated net systems, to enhance our efficiency while adhering to environmental regulations. Our operations are designed to minimize bycatch and support the recovery of overfished species. We work closely with marine biologists to monitor fish populations and adjust our practices accordingly. Our seafood is processed on-site and distributed to retailers and restaurants, ensuring that our customers receive the freshest products while supporting responsible fishing initiatives.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0006431715052718271, 'A': 0.9802578355992255, 'F': 0.0011380845717335972, 'B': 0.01753429278400184, 'J': 0.00042661553976714627}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.019742164400774476}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 74:
  The firm is dedicated to the extraction of crude petroleum from both traditional and unconventional sources. By employing enhanced oil recovery techniques, the company is able to increase the amount of oil extracted from existing fields, thereby extending their productive life. The crude oil produced is then refined into high-demand products such as kerosene and heating oil, which are distributed through a well-established supply chain. The company also engages in research and development to explore alternative extraction methods, aiming to reduce the environmental footprint of its operations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.597249327333505e-05, 'A': 3.733434994348958e-05, 'F': 1.3090590483951836e-05, 'B': 0.9998859922860012, 'J': 7.6102802981217535e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011400771399883158}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 75:
  Our company focuses on the raising of exotic animals, specifically for educational and conservation purposes. We maintain a sanctuary that provides a safe haven for species that are endangered or threatened. Our operations include breeding programs aimed at increasing population numbers and educating the public about wildlife conservation. We offer guided tours and interactive experiences that engage visitors and raise awareness about the importance of protecting these species. By partnering with conservation organizations, we contribute to global efforts to preserve biodiversity and promote responsible animal husbandry practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 4.03447911972385e-05, 'A': 0.9992232246594085, 'F': 0.0005818420646089065, 'B': 0.0001028902283948304, 'J': 5.1698256390498505e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007767753405915068}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 10%|█████████████████▍                                                                                                                                                              | 78/788 [00:05<00:47, 14.97it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 76:
  We are at the forefront of hard coal mining, employing a mix of surface and underground techniques to extract coal efficiently. Our commitment to quality is reflected in our rigorous cleaning and grading processes, which enhance the coal's marketability for various industrial uses. We also invest in advanced pulverizing technology to produce fine coal products that cater to specific client needs. Our strategic focus on sustainability ensures that we minimize our environmental footprint while delivering high-quality coal to power plants and manufacturing facilities across the region.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.490783208409426e-05, 'A': 3.449894406401394e-05, 'F': 1.2392438660723443e-05, 'B': 0.9998909973854307, 'J': 7.203399760369879e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957238067486, 6: 1.328848195426292e-06, 7: 2.9473450560088956e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975282534882169, 5.2: 0.0024717465117831206}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 77:
  We focus on the cultivation of unique and rare plants for the specialty market, catering to collectors and enthusiasts who seek distinctive additions to their gardens. Our propagation methods prioritize plant health and genetic diversity, ensuring that our offerings are both beautiful and resilient. We participate in botanical shows and events to showcase our products and connect with fellow plant lovers. By fostering a community of passionate gardeners, we contribute to the appreciation and preservation of rare plant species.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.005894417154051005, 'A': 0.36943543396700784, 'F': 0.6131052085926807, 'B': 0.008034474149572928, 'J': 0.0035304661366875804}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3868947914073193}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 78:
  Our firm is engaged in the mining and processing of iron ores, focusing on the production of high-grade iron pellets for the steel industry. We employ advanced beneficiation techniques, including magnetic separation and flotation, to refine the ore and enhance its iron content. Our facilities are equipped with modern technologies that facilitate real-time monitoring of ore quality, ensuring that our products meet stringent industry specifications. By prioritizing sustainability, we actively seek to minimize waste and optimize resource use, thereby reinforcing our commitment to responsible mining practices.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.6666267951477523e-05, 'A': 3.3846454556577174e-05, 'F': 1.229121363037541e-05, 'B': 0.9998900482868227, 'J': 7.147777038975841e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010995171317729202}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 10%|██████████████████▎                                                                                                                                                             | 82/788 [00:05<00:49, 14.12it/s]

RAPS scores:

==================================================
Description 79:
  Our business model revolves around the efficient mining and processing of hard coal, utilizing both underground and surface methods to maximize output. We invest in advanced technologies for cleaning, sizing, and grading coal, ensuring that our products meet the highest quality standards. Our commitment to sustainability is evident in our operations, as we strive to minimize environmental impacts while providing reliable coal supplies to our clients. By focusing on innovation and operational excellence, we position ourselves as a leader in the coal mining industry.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.483352236212145e-05, 'A': 3.436573405189366e-05, 'F': 1.23391325622441e-05, 'B': 0.9998913021214703, 'J': 7.159489553260614e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957220923733, 6: 1.3402019015466546e-06, 7: 2.9377057251760674e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975285256495164, 5.2: 0.002471474350483617}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 80:
  Our company is at the forefront of natural gas extraction, employing advanced techniques to maximize production from our extensive reserves. We utilize cutting-edge drilling technologies and efficient processing methods to separate liquid hydrocarbons from gas, ensuring high-quality products for market distribution. Our commitment to sustainability drives our implementation of gas desulphurization processes, which help us meet stringent environmental regulations. With a focus on innovation and efficiency, we continuously seek to improve our operations, thereby enhancing value for our stakeholders and contributing to a cleaner energy future.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.491815454985907e-05, 'A': 3.4703474585184786e-05, 'F': 1.2437370380211752e-05, 'B': 0.9998907445118616, 'J': 7.196488623159396e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7649997900074303e-06, 6: 0.9999964282463193, 7: 1.8067538907385427e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.997967669050331, 6.1: 0.0020323309496690202}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 81:
  Specializing in artisanal fishing, we emphasize traditional methods passed down through generations. Our fishermen utilize small boats and handlines to catch a variety of fish species in both freshwater and marine environments. This approach not only supports local livelihoods but also fosters a deep connection to the aquatic ecosystems we rely on. We actively participate in community initiatives aimed at promoting sustainable fishing practices, ensuring that our methods do not compromise the health of fish populations or their habitats.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00032306924489783676, 'A': 0.993547162104476, 'F': 0.0007697167861571189, 'B': 0.0051222875427129385, 'J': 0.00023776432175633575}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006452837895523977}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 11%|██████████████████▊                                                                                                                                                             | 84/788 [00:05<00:52, 13.40it/s]

RAPS scores:

==================================================
Description 82:
  We focus on the extraction and processing of natural gas, employing innovative techniques to maximize recovery from both conventional and unconventional sources. Our operations include the draining and separation of liquid hydrocarbon fractions, which are essential for producing high-value products. We utilize advanced technologies for gas desulphurization, ensuring that our output meets stringent quality standards. Our commitment to environmental stewardship drives us to implement best practices in safety and sustainability, making us a responsible player in the energy sector while delivering value to our stakeholders.1. Our company specializes in the extraction and production of natural gas, utilizing advanced drilling techniques and state-of-the-art technology to maximize yield from our wells. We focus on both conventional and unconventional sources, ensuring a steady supply of natural gas to meet growing energy demands. Our operations include extensive geological surveys and the implementation of hydraulic fracturing methods to enhance gas flow. Additionally, we invest in research and development to improve extraction efficiency and reduce environmental impact, positioning ourselves as a leader in sustainable energy solutions.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.511940009561053e-05, 'A': 3.461393604863064e-05, 'F': 1.2452423278066333e-05, 'B': 0.9998905727005939, 'J': 7.241539983848678e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010942729940610629}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 83:
  Our company is at the forefront of hard coal mining, utilizing a combination of traditional and innovative extraction methods to meet the growing energy demands. We operate several mines equipped with advanced technologies that enhance both safety and efficiency. Once extracted, our coal undergoes comprehensive processing, including cleaning, sizing, and pulverizing, to ensure optimal quality. Our commitment to sustainability is reflected in our operational practices, where we strive to minimize waste and reduce our carbon footprint while providing reliable coal supplies to our customers.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.499394852456968e-05, 'A': 3.435614365560708e-05, 'F': 1.2349775977466744e-05, 'B': 0.9998911443584957, 'J': 7.1557733466913015e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957170126071, 6: 1.3299308915174955e-06, 7: 2.9530565015241273e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975275820683818, 5.2: 0.002472417931618295}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 84:
  Dedicated to the raising of other livestock, our farm focuses on the sustainable production of alpacas for both fiber and companionship. We prioritize ethical breeding practices to enhance the quality of our herd, producing soft, luxurious fleece that is sought after in the textile industry. Our facilities are designed to provide a comfortable environment for our animals, with ample space for social interaction and exercise. Additionally, we host workshops and farm tours to educate the public about alpaca care and fiber production, creating awareness and appreciation for these unique animals.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0009449856061542001, 'A': 0.9839248816687852, 'F': 0.005322326825224162, 'B': 0.00923029127663541, 'J': 0.000577514623200956}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.016075118331214777}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 11%|███████████████████▋                                                                                                                                                            | 88/788 [00:06<00:47, 14.78it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 85:
  In addition to mining operations, we have established a robust warehousing and storage infrastructure for lignite products. Our facilities are designed to accommodate large volumes of lignite while ensuring optimal conditions for quality preservation. We utilize advanced monitoring systems to track inventory levels and manage stock effectively, allowing us to respond swiftly to market demands. This capability not only supports our mining and processing activities but also provides our customers with reliable access to high-quality lignite, enhancing their operational efficiency.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.502049258010843e-05, 'A': 3.453260233896559e-05, 'F': 1.2448071302667572e-05, 'B': 0.999890783415596, 'J': 7.215418182124497e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957346350961, 6: 1.3514238486380811e-06, 7: 2.913941055439035e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023553787855570114, 5.2: 0.997644621214443}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 86:
  Our business is dedicated to the gathering of eelgrass, a vital marine plant known for its ecological benefits. We work in collaboration with marine biologists to ensure that our harvesting practices support the health of coastal ecosystems. The harvested eelgrass is processed into products for use in landscaping and erosion control, as well as for its potential applications in sustainable agriculture. By raising awareness about the importance of eelgrass in marine environments, we aim to foster a greater appreciation for this valuable resource.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 2.318028092204717e-05, 'A': 0.9997965962639085, 'F': 7.652649800669985e-05, 'B': 7.900471580200841e-05, 'J': 2.4692241360737992e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00020340373609151197}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 87:
  We focus on the extraction and processing of natural gas, leveraging advanced technologies to improve efficiency and reduce our ecological footprint. Our operations include the use of precision drilling and real-time monitoring systems to enhance production capabilities. We specialize in the separation of liquid hydrocarbons from natural gas, providing high-quality products to various markets. Furthermore, our investment in gas desulphurization technologies ensures that our natural gas meets stringent quality standards, making it suitable for both domestic and international markets. By prioritizing innovation and sustainability, we aim to lead the way in the energy sector while supporting a cleaner energy future.1. Our company specializes in the extraction and processing of natural gas, employing advanced drilling techniques to maximize yield while minimizing environmental impact. We utilize state-of-the-art hydraulic fracturing methods to access deep reserves, ensuring efficient recovery of crude gaseous hydrocarbons. Once extracted, our team implements sophisticated separation technologies to refine the gas, removing impurities and enhancing quality. We also engage in gas desulphurization processes to meet stringent regulatory standards, providing clean energy solutions to our clients. Our commitment to innovation and sustainability drives our operations, positioning us as a leader in the natural gas sector.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.4917883826839395e-05, 'A': 3.475680245425761e-05, 'F': 1.2490816772187101e-05, 'B': 0.999890583316506, 'J': 7.251180440694422e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010941668349395695}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 88:
  We specialize in the cultivation of aquatic plants, such as seaweed and watercress, which are increasingly in demand for their nutritional and health benefits. Our innovative farming techniques include vertical farming systems that maximize space and yield while minimizing resource consumption. We partner with research institutions to explore new applications for our products in food, cosmetics, and pharmaceuticals. Through these collaborations, we aim to expand our market reach and contribute to the growing trend of plant-based diets, positioning ourselves as leaders in sustainable aquatic farming.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.05127880332823522, 'A': 0.2268222609634628, 'F': 0.053682049335702794, 'B': 0.6618042157933737, 'J': 0.00641267057922561}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3381957842066263}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 12%|████████████████████▊                                                                                                                                                           | 93/788 [00:06<00:40, 17.24it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 89:
  Our company is at the forefront of natural gas extraction, utilizing cutting-edge technologies to enhance production efficiency. We engage in the separation of liquid hydrocarbon fractions, ensuring that we capture valuable resources during the extraction process. Our commitment to sustainability is evident in our use of advanced gas desulfurization methods, which improve the quality of the gas produced while minimizing environmental impact. By leveraging our expertise and innovative approaches, we aim to meet the growing demand for cleaner energy solutions in a responsible manner.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.4865689369482984e-05, 'A': 3.471807806953072e-05, 'F': 1.243731737131548e-05, 'B': 0.9998907739677559, 'J': 7.2049474338155935e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7706797236526248e-06, 6: 0.9999964255947029, 7: 1.8037255733220327e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979599799792609, 6.1: 0.002040020020739065}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 90:
  Our nursery operations are dedicated to growing a diverse selection of live plants, including bulbs, tubers, and roots, which are essential for both commercial agriculture and home gardening. We prioritize sustainable practices, such as organic growing methods and water conservation techniques, to minimize our environmental impact. Our expert team conducts rigorous quality control measures to ensure that all products meet the highest standards before reaching our customers. Additionally, we provide educational resources and workshops to empower our clients with knowledge about plant care and propagation techniques.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.002383928464892775, 'A': 0.9283648485364985, 'F': 0.058176123269294236, 'B': 0.009678873368445128, 'J': 0.0013962263608694946}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07163515146350152}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 91:
  We are dedicated to the growth and production of high-quality rice, utilizing innovative farming methods that prioritize sustainability. Our operations encompass land preparation, planting, and harvesting, all of which are optimized through the use of modern machinery and irrigation systems. We also focus on seed selection, ensuring that our rice varieties are resilient to climate conditions and pests. Our commitment to quality extends to our processing facilities, where we package and distribute our rice to meet the demands of consumers and food service industries, both locally and abroad.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.06544741724613908, 'A': 0.04678066961614648, 'F': 0.0351393196842446, 'B': 0.848653754120197, 'J': 0.003978839333272954}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15134624587980305}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 92:
  Our firm is dedicated to the extraction of natural gas, leveraging cutting-edge technologies such as horizontal drilling and multi-stage fracturing to unlock reserves previously deemed inaccessible. We focus on maximizing recovery rates while minimizing environmental footprints. Our facilities are equipped with advanced gas processing units that efficiently separate condensates from natural gas, ensuring high-quality output. Additionally, we engage in gas desulphurization processes to meet stringent market specifications, thus enhancing the marketability of our products. Our strategic partnerships with local stakeholders ensure a collaborative approach to resource management and community engagement.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.479704566961203e-05, 'A': 3.487842625279906e-05, 'F': 1.2512485696939437e-05, 'B': 0.999890565697682, 'J': 7.246344698542597e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010943430231802331}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 12%|█████████████████████▍                                                                                                                                                          | 96/788 [00:06<00:42, 16.37it/s]

RAPS scores:

==================================================
Description 93:
  Our business is dedicated to the cultivation of various non-perennial crops, including legumes and oilseeds. We employ crop rotation strategies to maintain soil fertility and reduce pest pressures, ensuring sustainable production practices. Our facilities are equipped with modern processing technology that allows us to extract oils and produce high-protein animal feed from our crops. We focus on meeting the growing demand for plant-based products, supplying both local and international markets with high-quality ingredients. Our research and development team continuously explores innovative ways to enhance crop resilience and yield, ensuring we remain competitive in a rapidly evolving agricultural landscape.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.20915017911918252, 'A': 0.030847598338190466, 'F': 0.046970987265156694, 'B': 0.7066082079355105, 'J': 0.0064230273419597535}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2933917920644895}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 94:
  Our company specializes in the cultivation of diverse plant species for ornamental and agricultural purposes, focusing on sustainability and quality. We utilize advanced growing techniques and eco-friendly practices to produce healthy plants that thrive in various environments. Our product range includes a wide selection of seedlings, cuttings, and grafting stock, all designed to meet the needs of our customers. We pride ourselves on our commitment to exceptional customer service, offering expert advice and support to help clients achieve their gardening goals. Our dedication to sustainability and quality has established us as a trusted partner in the plant propagation sector.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.8120117421921669, 'A': 0.012520231185248126, 'F': 0.07107786732224863, 'B': 0.09419425466388272, 'J': 0.010195904636453434}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18798825780783313}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 95:
  As a prominent player in the hard coal mining industry, we leverage cutting-edge technology to enhance our extraction and processing capabilities. Our operations include both underground and surface mining, with a strong emphasis on safety and sustainability. After extraction, our coal undergoes extensive cleaning and sizing processes to ensure it meets stringent quality standards. We also focus on innovative methods for pulverizing and compressing coal, which not only improves transport efficiency but also reduces our overall environmental impact. Our dedication to quality and sustainability positions us as a trusted partner for our clients.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.48426149271179e-05, 'A': 3.435332281540198e-05, 'F': 1.2351255956103976e-05, 'B': 0.9998912895366415, 'J': 7.163269659812049e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957181233033, 6: 1.329075051858293e-06, 7: 2.9528016448024273e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975272845159682, 5.2: 0.002472715484031777}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 96:
  Our company is at the forefront of crude petroleum extraction, employing cutting-edge technologies to ensure efficient and responsible resource management. We utilize advanced drilling rigs equipped with real-time monitoring systems that provide critical data on well performance and environmental impact. Our commitment to sustainability drives us to implement best practices in waste management and emissions reduction. By collaborating with local communities and stakeholders, we strive to create a positive impact while meeting the growing energy demands of the market. Our focus on innovation and safety sets us apart in the competitive landscape of crude oil extraction.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4966438397944176e-05, 'A': 3.4829512478620265e-05, 'F': 1.2477023170916814e-05, 'B': 0.9998905054485118, 'J': 7.221577440916036e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010949455148823173}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 13%|██████████████████████                                                                                                                                                          | 99/788 [00:06<00:42, 16.13it/s]

RAPS scores:

==================================================
Description 97:
  Our operations in the mining of rare earth elements are pivotal in supporting the technological advancements of the modern world. We employ advanced extraction techniques to separate these critical materials from other non-ferrous ores, ensuring minimal environmental disruption. Our commitment to research and development drives innovation in refining processes, allowing us to produce high-purity rare earth oxides that are essential for manufacturing magnets, batteries, and electronic devices. By collaborating with leading technology firms, we enhance the value of our products and contribute to the global transition towards sustainable energy solutions.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.5966593905627246e-05, 'A': 3.397866978053505e-05, 'F': 1.2313394863459813e-05, 'B': 0.9998906187663804, 'J': 7.122575070058933e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938123361958763}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 98:
  Our business model revolves around the extraction and processing of natural gas, where we leverage cutting-edge technology to streamline operations. We employ advanced drilling methods to tap into both traditional and unconventional gas reserves, maximizing recovery while minimizing costs. Our separation facilities are designed to efficiently isolate liquid hydrocarbons from natural gas, ensuring high-quality outputs. Moreover, our gas desulphurization practices are integral to our operations, allowing us to produce cleaner energy solutions that align with global sustainability goals.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.471255585949088e-05, 'A': 3.469316839256783e-05, 'F': 1.2459572682999693e-05, 'B': 0.9998909104500345, 'J': 7.224253030291769e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.771375569286585e-06, 6: 0.9999964167907597, 7: 1.8118336709915456e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979844290652291, 6.1: 0.0020155709347707946}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 99:
  We specialize in the collection of mosses and lichens, which are increasingly sought after for their applications in decorative arts, horticulture, and natural dyes. Our harvesting techniques prioritize sustainability, allowing these delicate organisms to thrive in their natural habitats. We work closely with artisans and manufacturers to develop innovative products that showcase the unique properties of mosses and lichens. By educating consumers about the ecological significance of these materials, we aim to foster a greater appreciation for their role in biodiversity and promote responsible harvesting practices within the industry.1. Our company specializes in the sustainable harvesting of wild mushrooms and truffles, focusing on premium quality and environmental stewardship. We employ local foragers who are trained in sustainable practices to ensure that our gathering techniques do not disrupt the natural ecosystem. By maintaining strong relationships with gourmet restaurants and specialty food retailers, we provide fresh, organic products that cater to the growing demand for unique culinary experiences. Our commitment to quality is reflected in our rigorous quality control processes, ensuring that only the finest products reach our customers.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9988300378090451, 'A': 6.928486252722753e-05, 'F': 0.00012314702475455747, 'B': 0.0005951416259291988, 'J': 0.00038238867774385046}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0011699621909548874}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 13%|███████████████████████▎                                                                                                                                                       | 105/788 [00:07<00:34, 19.58it/s]

RAPS scores:

==================================================
Description 100:
  We are committed to the production of high-quality planting materials, including seedlings, cuttings, and grafting stocks for both agricultural and ornamental applications. Our nursery employs innovative techniques to ensure that our plants are healthy and resilient, ready to thrive in various environments. Our team of experts continuously researches new propagation methods to improve plant quality and yield. We also offer a selection of educational workshops, empowering our customers with the knowledge they need to succeed in their gardening endeavors.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.999688555007234, 'A': 1.831336873261476e-05, 'F': 2.4865584325932855e-05, 'B': 9.881712748125712e-05, 'J': 0.0001694489122260874}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003114449927660301}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 101:
  Our business is dedicated to the growing of a wide array of vegetables and melons, focusing on organic and sustainable farming methods. We cultivate crops such as tomatoes, cucumbers, and cantaloupes in controlled environments that maximize growth potential while minimizing environmental impact. Our commitment to sustainability extends to our supply chain, where we prioritize local sourcing and eco-friendly packaging solutions. By leveraging technology, such as hydroponics and vertical farming, we are able to produce high-quality vegetables year-round, meeting the increasing consumer demand for fresh and healthy produce.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.13100668150039388, 'A': 0.11684617138275222, 'F': 0.1356397915964121, 'B': 0.6072474111900372, 'J': 0.009259944330404665}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3927525888099628}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 102:
  Our company is dedicated to the raising of poultry, specifically broilers and layers, to meet the growing demand for chicken and eggs. We utilize innovative farming methods, including free-range systems that allow our birds to roam and forage, promoting natural behaviors and improving meat quality. Our facilities are equipped with advanced climate control and ventilation systems to ensure optimal living conditions. We also prioritize animal welfare by adhering to strict ethical standards and providing comprehensive training for our staff on humane handling practices, resulting in healthier flocks and superior products.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.017406078596866003, 'A': 0.62159054783448, 'F': 0.04643579798329143, 'B': 0.31024694063856345, 'J': 0.0043206349467990865}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.37840945216552}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 103:
  We are engaged in the cultivation of sugar cane, utilizing sustainable farming practices to produce high yields while preserving soil health. Our operations include the processing of sugar cane into various products, such as raw sugar and molasses, which are sold to both domestic and international markets. We prioritize efficiency in our production processes, implementing renewable energy sources to power our facilities. Our focus on quality control ensures that our sugar products meet the highest standards, catering to a diverse range of customers, from food manufacturers to consumers.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.13783037775544896, 'A': 0.002035648936884832, 'F': 0.0020457507186474578, 'B': 0.8570728610114567, 'J': 0.001015361577561872}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.14292713898854326}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 104:
  Our company is engaged in the extraction of crude petroleum, focusing on both onshore and offshore operations. We utilize advanced geological mapping technologies to identify potential drilling sites, ensuring that our investments are strategically sound. Our fleet of drilling rigs is equipped with the latest safety features, and we conduct regular training sessions for our crew to uphold the highest safety standards. We are also committed to minimizing our environmental impact through initiatives such as waste reduction and habitat preservation. By balancing production goals with ecological responsibility, we aim to lead the industry in sustainable extraction practices.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.501427359076494e-05, 'A': 3.48934750518755e-05, 'F': 1.2554472466384035e-05, 'B': 0.9998902802323545, 'J': 7.257546536642148e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010971976764551084}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 14%|███████████████████████▉                                                                                                                                                       | 108/788 [00:07<00:38, 17.51it/s]

RAPS scores:

==================================================
Description 105:
  We focus on the collection of acorns and horse chestnuts, which are harvested from local forests using sustainable practices. Our products are marketed for both culinary uses and as natural ingredients in health supplements. We educate our customers on the nutritional benefits of these wild nuts and their potential uses in various recipes. By fostering relationships with local foragers and promoting responsible harvesting, we aim to create a brand that emphasizes the connection between food, health, and the environment, while supporting local economies.1. Our company specializes in the sustainable gathering of wild mushrooms and truffles, sourcing these gourmet ingredients from pristine forests. We employ skilled foragers who are trained in sustainable harvesting practices to ensure the preservation of these delicate ecosystems. Our products are sold to high-end restaurants and gourmet food retailers, where they are celebrated for their unique flavors and quality. By establishing direct relationships with chefs and culinary experts, we not only enhance the dining experience but also promote awareness of the importance of biodiversity and sustainable sourcing in the culinary world.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9013091586106831, 'A': 0.001841101914872272, 'F': 0.005301235792725907, 'B': 0.08919861650609665, 'J': 0.0023498871756222283}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09869084138931694}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:

==================================================
Description 106:
  Our company is involved in the distribution of fresh seafood, sourcing directly from local fishermen engaged in sustainable fishing practices. We prioritize building relationships with our suppliers, ensuring that our products are not only fresh but also ethically harvested. Our distribution network spans local markets, restaurants, and grocery stores, where we emphasize the importance of supporting local economies and sustainable seafood consumption. By providing traceable and high-quality seafood, we aim to educate consumers about the benefits of choosing sustainably sourced products.1. The company specializes in sustainable marine fishing, utilizing advanced trawling techniques to capture a variety of fish species in offshore waters. By employing eco-friendly nets designed to minimize bycatch, the business ensures that its operations have a minimal impact on marine ecosystems. The caught fish are processed on-site, where they are filleted and packaged for distribution to local markets and restaurants. Additionally, the company engages in community outreach programs, educating local fishermen on sustainable practices and contributing to the preservation of marine habitats.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1677775055630236e-05, 'A': 0.9999042032660866, 'F': 3.968605415985287e-05, 'B': 3.0530430610529704e-05, 'J': 1.3902474087391191e-05}
Division sets: {'A': [3]}
Division probs: {'A': {1: 0.0007329338496532905, 2: 0.0009141642204550417, 3: 0.9983529019298916}}
Class sets: {}
Class probs: {}
Final output: {'type': 'class_level', 'codes': []}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 107:
  Our company is dedicated to the sustainable farming of fish species through innovative aquaculture practices. We utilize integrated multi-trophic aquaculture (IMTA) systems that promote biodiversity and enhance resource efficiency. By cultivating fish alongside shellfish and seaweed, we create a balanced ecosystem that maximizes productivity while minimizing waste. Our operations are supported by cutting-edge technology, including automated feeding systems and real-time water quality monitoring, ensuring the health and growth of our stock. We are committed to transparency and traceability, providing our customers with detailed information about the origin and farming practices of our seafood products.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00014420378635786178, 'A': 0.9983950914454582, 'F': 0.0004523270985839324, 'B': 0.0008880148151277242, 'J': 0.00012036285447231292}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0016049085545417618}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 14%|████████████████████████▊                                                                                                                                                      | 112/788 [00:07<00:39, 17.17it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 108:
  Our company is dedicated to the extraction of natural gas, utilizing innovative drilling and processing methods to enhance production efficiency. We focus on the separation of valuable liquid hydrocarbons from raw gas, providing a range of products that meet market demands. Our gas desulphurization processes are designed to ensure compliance with environmental regulations, contributing to cleaner energy solutions. Through strategic investments in technology and infrastructure, we aim to optimize our operations and deliver high-quality natural gas to our customers while supporting a sustainable energy future.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.503785220889494e-05, 'A': 3.446166502031535e-05, 'F': 1.238051598265728e-05, 'B': 0.9998909371214113, 'J': 7.182845376688095e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.759430380742536e-06, 6: 0.9999964428811353, 7: 1.7976884839839438e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979602872057961, 6.1: 0.002039712794203814}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 109:
  Our company is dedicated to the collection of eelgrass, which we harvest from coastal environments. This versatile marine plant is processed into products for use in landscaping, erosion control, and as a natural mulch. We work closely with environmental organizations to ensure that our harvesting practices support the health of marine ecosystems. By raising awareness about the benefits of eelgrass, we aim to create a market that values sustainable coastal resource management.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.001270145573432177, 'A': 0.9708544098895069, 'F': 0.022935686819851215, 'B': 0.0040784665687433825, 'J': 0.0008612911484662965}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.029145590110493114}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 110:
  Our organization is dedicated to the extraction of crude petroleum, focusing on innovative techniques that enhance recovery rates. We employ advanced horizontal drilling methods that allow us to tap into extensive reserves with minimal surface footprint. Our commitment to technological advancement is reflected in our investment in automation and remote monitoring systems, which streamline operations and improve safety. Furthermore, we actively engage in research and development to explore alternative energy sources, ensuring that our extraction practices evolve in line with global energy trends and environmental standards.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.484470905185347e-05, 'A': 3.492622573257555e-05, 'F': 1.2504879900620062e-05, 'B': 0.9998904917182592, 'J': 7.232467055909798e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010950828174083327}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 111:
  We specialize in the raising of various livestock, including exotic breeds that appeal to niche markets. Our farm is dedicated to implementing humane and sustainable practices that ensure the health and well-being of our animals. We focus on breeding programs that enhance desirable traits, such as hardiness and productivity, while also preserving genetic diversity. Our commitment to quality extends to the products we offer, including specialty meats and organic by-products. By collaborating with local artisans and chefs, we create unique culinary experiences that highlight the flavors of our farm, building a loyal customer base that values quality and sustainability.1. Our company specializes in the raising of dairy cattle, focusing on sustainable farming practices that enhance milk production while ensuring animal welfare. We utilize advanced breeding techniques to improve herd genetics, leading to higher milk yields and better quality dairy products. Our facilities are equipped with state-of-the-art milking technology, which allows for efficient collection and processing of milk. We also prioritize environmental stewardship by implementing waste management systems that reduce our carbon footprint and promote soil health. Through these efforts, we provide high-quality dairy products to local markets, contributing to the community's nutritional needs.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.015993694790505334, 'A': 0.6562514070990089, 'F': 0.03719727364375684, 'B': 0.28633190475720305, 'J': 0.004225719709525898}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.34374859290099113}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 15%|██████████████████████████▏                                                                                                                                                    | 118/788 [00:07<00:30, 21.66it/s]

RAPS scores:

==================================================
Description 112:
  Our company excels in the extraction of natural gas, employing innovative technologies such as 3D seismic surveys and automated drilling rigs to enhance operational efficiency. We specialize in the draining and separation of liquid hydrocarbons, ensuring that we capture valuable by-products that contribute to our revenue stream. In addition, our gas desulphurization facilities are designed to remove impurities, allowing us to produce cleaner natural gas that meets the highest industry standards. Through continuous investment in research and development, we aim to improve our extraction techniques and reduce our environmental footprint.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.504506501430073e-05, 'A': 3.488666965381008e-05, 'F': 1.254898975730979e-05, 'B': 0.9998902540684601, 'J': 7.265207114541873e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001097459315398952}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 113:
  Our company is at the forefront of producing roundwood for the manufacturing of high-quality wooden products. We focus on sourcing logs from certified forests, ensuring that our supply chain is both ethical and sustainable. Our products range from beams and planks to specialty items used in construction and furniture making. We leverage advanced milling technologies to enhance precision and reduce waste, allowing us to offer competitive pricing without compromising on quality. Our commitment to sustainability not only meets regulatory requirements but also resonates with consumers increasingly seeking responsibly sourced materials.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997714337123257, 'A': 1.2483532120489823e-05, 'F': 1.5142665380482642e-05, 'B': 6.507385024818465e-05, 'J': 0.00013586623992526534}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00022856628767431442}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 114:
  We are engaged in the traditional production of charcoal from sustainably harvested wood. Our methods prioritize low-impact techniques that preserve forest ecosystems while producing high-quality charcoal for both domestic and export markets. We focus on educating local communities about sustainable harvesting practices, ensuring that our operations contribute to economic development without compromising environmental integrity. Our charcoal is sought after for its superior burning properties, making it a preferred choice for both grilling and industrial applications.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.6760521994102802, 'A': 0.0014632963412473468, 'F': 0.0018141385900825497, 'B': 0.31923947034806516, 'J': 0.0014308953103247368}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.32394780058971984}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 115:
  Our company is at the forefront of implementing environmentally responsible practices in lignite mining. We have established protocols for minimizing the impact of surface mining operations, including reforestation initiatives and habitat restoration projects. By engaging with local communities and stakeholders, we ensure that our mining activities align with regional conservation efforts. Our focus on sustainability not only enhances our corporate reputation but also fosters goodwill among the communities we serve, reinforcing our commitment to responsible resource management.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.520221886249311e-05, 'A': 3.48294430258349e-05, 'F': 1.2492632943237396e-05, 'B': 0.9998902995298407, 'J': 7.176175327682175e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010970047015934625}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 116:
  Our company operates multiple timber tracts where we focus on the sustainable growth of standing timber. We utilize advanced technologies such as drone mapping and remote sensing to monitor forest health and optimize our thinning operations. Our commitment to sustainability extends to our partnerships with environmental organizations, where we collaborate on reforestation projects that restore degraded lands. By integrating technology with traditional forestry practices, we enhance our operational efficiency while ensuring that our activities contribute positively to the environment.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00013646078199634713, 'A': 0.9974330423066519, 'F': 0.0006306037821941861, 'B': 0.0016738886168209902, 'J': 0.00012600451233642533}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0025669576933481375}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 117:
  We are committed to the sustainable harvesting of firewood, providing eco-friendly energy solutions for residential and commercial use. Our firewood is sourced from responsibly managed forests, where we employ practices that ensure continuous growth and regeneration. We offer a range of products, from seasoned firewood to specialty hardwoods, catering to diverse customer needs. Our focus on sustainability not only supports local economies but also promotes the use of renewable energy sources in heating and cooking.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.007851787606607447, 'A': 0.49564222059651114, 'F': 0.013753450124485185, 'B': 0.48030026305936446, 'J': 0.0024522786130316025}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5043577794034888}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 118:
  As a leader in lignite mining, our operations focus on both surface and underground extraction methods tailored to the geological characteristics of our reserves. We utilize cutting-edge technology to optimize the mining process, ensuring safety and efficiency. Our facilities are equipped with advanced washing and dehydrating systems that enhance lignite quality, making it more suitable for transport and storage. We also provide comprehensive logistics solutions, including warehousing and transportation support, to streamline the supply chain for our customers. By prioritizing innovation and sustainability, we deliver high-quality lignite products while minimizing our ecological footprint.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.493457071367471e-05, 'A': 3.43992429643463e-05, 'F': 1.2381949929766784e-05, 'B': 0.9998911202711059, 'J': 7.16396528644168e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957354076623, 6: 1.3483271508336074e-06, 7: 2.9162651868722504e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023551502173298823, 5.2: 0.9976448497826702}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 119:
  Our company is actively involved in the mining and beneficiation of iron ores, focusing on delivering high-quality products to meet the needs of the steel manufacturing industry. We employ advanced extraction techniques that ensure maximum ore recovery while adhering to environmental best practices. The beneficiation process is optimized through the use of cutting-edge technology, resulting in iron concentrates that exceed industry standards. We also prioritize safety and community engagement, ensuring our operations benefit both our stakeholders and the environment.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5522188200847086e-05, 'A': 3.4072703868675735e-05, 'F': 1.2297949262921816e-05, 'B': 0.9998909697288552, 'J': 7.137429812493246e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.47502978179587e-06, 6: 1.5798324981939204e-06, 7: 0.99999594513772}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677864118226709, 7.2: 0.032213588177329146}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 16%|███████████████████████████▌                                                                                                                                                   | 124/788 [00:08<00:41, 15.98it/s]

RAPS scores:

==================================================
Description 120:
  Our operations include the thinning and management of timber tracts, aimed at optimizing growth and yield. By strategically removing select trees, we create space for remaining trees to flourish, thus improving the overall health of the forest. This practice not only increases the quality of timber produced but also enhances the habitat for wildlife. We utilize advanced data analytics to monitor growth patterns and make informed decisions about when and how to thin our forests. This data-driven approach allows us to maximize our resource efficiency while ensuring that our forestry practices align with sustainability goals.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00011409816686655732, 'A': 0.9983372500054845, 'F': 0.0008019713052663397, 'B': 0.0006376261394858047, 'J': 0.00010905438289683219}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0016627499945155444}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 121:
  At GreenSprout Nurseries, we pride ourselves on our extensive selection of live plants, including a variety of bulbs, tubers, and roots. Our dedicated team of horticulturists employs sustainable farming practices to cultivate planting materials that meet the highest industry standards. We focus on producing high-quality cuttings and slips, ensuring that our customers receive robust and healthy plants ready for transplanting. Our commitment to innovation includes the development of eco-friendly packaging solutions that minimize environmental impact while maintaining the integrity of our products during transportation.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0010473913961351838, 'A': 0.9853357982868687, 'F': 0.0066399235188903515, 'B': 0.006348825009052808, 'J': 0.0006280617890530622}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01466420171313132}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 122:
  We operate a commercial nursery that specializes in the production of high-quality seedlings for vegetable crops. Our facilities are equipped with advanced irrigation and climate control systems that optimize growth conditions for a variety of crops, including tomatoes, peppers, and cucumbers. We prioritize sustainable practices, using organic fertilizers and pest management techniques to ensure the health of our plants. Our seedlings are sold to local farmers and home gardeners, who rely on our expertise and quality assurance for their planting needs.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.09002089982678428, 'A': 0.12691393260578263, 'F': 0.13422251633415183, 'B': 0.6406921355882239, 'J': 0.008150515645057215}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3593078644117761}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 123:
  We specialize in the comprehensive mining of iron ores, focusing on both extraction and value-added processing. Our operations include the use of advanced drilling techniques and heavy machinery to efficiently extract ore from our sites. Once mined, the ore is processed in our state-of-the-art beneficiation plants, where we employ technologies such as magnetic separation and pelletizing to produce high-quality iron ore pellets. Our commitment to innovation and efficiency allows us to serve our clients in the steel industry with reliable and high-purity products that meet their specifications.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.55882259573828e-05, 'A': 3.406228467825378e-05, 'F': 1.2311889470942807e-05, 'B': 0.9998909019145901, 'J': 7.135685303378283e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.489853449267578e-06, 6: 1.5727093523310444e-06, 7: 0.9999959374371984}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678034102610651, 7.2: 0.03219658973893492}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 16%|████████████████████████████▏                                                                                                                                                  | 127/788 [00:08<00:37, 17.76it/s]

RAPS scores:

==================================================
Description 124:
  We are dedicated to continuous improvement in our lignite mining operations, employing data analytics and monitoring technologies to optimize our processes. By analyzing geological data and production metrics, we can identify opportunities for increased efficiency and reduced costs. This data-driven approach enables us to make informed decisions that enhance our operational performance while maintaining our commitment to safety and sustainability in all aspects of our business.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.547174769698836e-05, 'A': 3.4447375610908706e-05, 'F': 1.2433316863930332e-05, 'B': 0.9998904569474091, 'J': 7.190612419028679e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010954305259092134}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 125:
  Our company has established a comprehensive logistics framework that supports the transportation and storage of lignite. We operate a fleet of specialized vehicles designed for the safe and efficient movement of lignite from mining sites to processing plants. Our warehousing facilities are equipped with advanced inventory management systems that track stock levels in real-time, ensuring that we can respond quickly to customer demands. By maintaining close relationships with our transportation partners, we guarantee that our clients receive their orders promptly, contributing to their operational efficiency and success.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.613301947859318e-05, 'A': 3.4847731225472595e-05, 'F': 1.2649405882628318e-05, 'B': 0.9998890507858545, 'J': 7.319057558915175e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011094921414545045}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 126:
  We specialize in the extraction of crude petroleum, utilizing advanced drilling techniques and comprehensive geological assessments to maximize our resource potential. Our operations are supported by a skilled workforce trained in the latest safety protocols, ensuring that we meet industry standards while minimizing environmental impact. We transport the crude oil through an extensive pipeline network to refineries, where it is processed into essential fuels and chemicals that drive the global economy. Our commitment to innovation and sustainability positions us as a leader in the energy sector.1. Our company specializes in the extraction of crude petroleum, utilizing advanced drilling techniques and state-of-the-art technology to maximize yield from our oil fields. We employ both onshore and offshore drilling rigs, ensuring efficient access to reserves while adhering to stringent environmental regulations. Our operations are supported by a robust logistics network that transports crude oil to refineries, where it is processed into various petroleum products. Additionally, we invest in research and development to enhance extraction methods, aiming to reduce costs and improve sustainability in our operations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.494470329840669e-05, 'A': 3.4691559134180115e-05, 'F': 1.2467087403622798e-05, 'B': 0.9998906579422242, 'J': 7.238707939621546e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010934205777579642}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 127:
  In the realm of freshwater fishing, our operations are centered around the harvesting of trout and catfish from carefully managed ponds. We utilize eco-friendly feeding techniques and maintain optimal water quality to promote healthy fish growth. Our team conducts regular assessments to monitor fish health and the overall ecosystem, ensuring a balanced environment. Additionally, we offer guided fishing tours that educate participants about sustainable practices while providing an enjoyable outdoor experience. The fish harvested are sold directly to local markets and restaurants, emphasizing freshness and quality in our supply chain.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 7.896386594215556e-05, 'A': 0.9990742977981321, 'F': 0.00024366782191543825, 'B': 0.0005306128426267125, 'J': 7.245767138362118e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009257022018679395}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 128:
  As a leader in natural gas extraction, we pride ourselves on our commitment to technological advancement and operational excellence. Our exploration teams utilize sophisticated seismic imaging techniques to identify optimal drilling sites, significantly reducing the time and resources required for exploration. Once extracted, our natural gas undergoes rigorous processing, including the separation of liquid hydrocarbon fractions, ensuring that we deliver high-quality products to our customers. Additionally, we prioritize safety and environmental stewardship, implementing robust protocols to minimize risks associated with gas extraction and processing.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.5180624483955416e-05, 'A': 3.528486594883208e-05, 'F': 1.2677406337003352e-05, 'B': 0.9998895659243634, 'J': 7.291178866761016e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011043407563660068}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 16%|████████████████████████████▊                                                                                                                                                  | 130/788 [00:08<00:37, 17.38it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 129:
  Our focus on crude petroleum extraction is driven by a commitment to innovation and sustainability. We employ enhanced oil recovery techniques that not only increase our production rates but also reduce the environmental impact of our operations. Our research initiatives explore alternative methods of extraction that minimize water usage and chemical input, aligning with global sustainability goals. By integrating cutting-edge technology with responsible practices, we strive to provide a reliable supply of crude oil while contributing to a more sustainable energy future.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.512335567924337e-05, 'A': 3.42701632556103e-05, 'F': 1.2304022539701569e-05, 'B': 0.9998911660244362, 'J': 7.1364340893712065e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.775404928739581e-06, 6: 0.999996410965234, 7: 1.813629837473926e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.00205902919412445, 6.1: 0.9979409708058756}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 130:
  Engaging in the farming of alligators, our company has carved a niche in the exotic aquaculture market. We provide a controlled environment that mimics their natural habitat, ensuring optimal growth and health. Our operations include breeding programs aimed at producing high-quality skins for the fashion industry, as well as meat products for gourmet markets. By adhering to ethical farming practices and promoting conservation efforts, we strive to educate consumers about the importance of sustainable sourcing in the exotic animal trade.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0007014906910147684, 'A': 0.9863973552186772, 'F': 0.002781573847777177, 'B': 0.009675451434326167, 'J': 0.0004441288082047413}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.013602644781322781}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 17%|█████████████████████████████▎                                                                                                                                                 | 132/788 [00:08<00:41, 15.86it/s]

RAPS scores:

==================================================
Description 131:
  Our company is dedicated to the mining of hard coal, utilizing both surface and underground methods to maximize resource extraction. We focus on employing innovative technologies that facilitate the liquefaction of coal, enhancing its marketability and usability. Our processing plants are equipped to clean, size, and grade coal, ensuring that we deliver products that meet the highest quality standards. By optimizing our operations, we not only improve efficiency but also reduce waste, contributing to a more sustainable mining practice. Our commitment to excellence in coal production enables us to serve a diverse clientele across various sectors, from energy generation to industrial manufacturing.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5168179335545286e-05, 'A': 3.424863808437514e-05, 'F': 1.2331116045336529e-05, 'B': 0.9998910992648662, 'J': 7.152801668448036e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957270094233, 6: 1.3353716857102833e-06, 7: 2.9376188908548716e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975283763465871, 5.2: 0.002471623653412892}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 132:
  Specializing in the mining of hard coal, our operations encompass both underground and surface extraction methods tailored to the unique characteristics of each site. We utilize cutting-edge technologies for the cleaning and grading of coal, ensuring that our products meet high-quality standards. Our facilities are designed to optimize the classification and storage of coal, facilitating efficient transport to our customers. We are dedicated to sustainable mining practices, implementing measures to minimize environmental impact while maximizing resource recovery. Through continuous improvement and innovation, we aim to strengthen our position in the hard coal market.1. Our company specializes in the extraction and processing of hard coal through both underground and surface mining techniques. Utilizing advanced liquefaction methods, we ensure efficient recovery of coal deposits while minimizing environmental impact. Our operations include the cleaning and sizing of coal, where we employ state-of-the-art technologies to enhance the quality of our product. This not only improves the calorific value but also facilitates easier transport and storage. By continuously investing in innovative processing equipment, we aim to meet the growing demand for high-quality coal in both domestic and international markets.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5423792134449154e-05, 'A': 3.4204798944519375e-05, 'F': 1.236711766292081e-05, 'B': 0.9998907997679208, 'J': 7.204523337254346e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957286945028, 6: 1.3487509008647032e-06, 7: 2.9225545963608333e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997525371330364, 5.2: 0.0024746286696360454}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 17%|█████████████████████████████▊                                                                                                                                                 | 134/788 [00:08<00:55, 11.73it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 133:
  As a leader in the iron ore mining sector, our company is committed to sustainable practices that enhance both productivity and environmental stewardship. We employ cutting-edge technologies for ore extraction and processing, including automated drilling and sorting systems that maximize yield while reducing waste. Our beneficiation facilities are equipped with advanced separation techniques, allowing us to produce high-purity iron concentrates. Additionally, we focus on the agglomeration of iron ores, producing high-quality pellets that are essential for efficient steelmaking. Our dedication to innovation and sustainability positions us as a trusted partner in the global steel supply chain.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5269287481690867e-05, 'A': 3.409292143451155e-05, 'F': 1.2291951781964396e-05, 'B': 0.999891212191328, 'J': 7.13364797389268e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4664188147787863e-06, 6: 1.5886528263568066e-06, 7: 0.9999959449283587}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677802345041888, 7.2: 0.032219765495811306}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 134:
  We engage in the production of roundwood used in the manufacturing of engineered wood products, which have become increasingly popular in the construction industry. Our sourcing strategy emphasizes the use of fast-growing tree species that can be harvested responsibly, ensuring a steady supply of raw materials. We utilize innovative processes to transform roundwood into high-quality plywood and laminated beams, which are valued for their strength and versatility. By collaborating with architects and builders, we promote the benefits of using engineered wood, contributing to sustainable building practices.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997724471026833, 'A': 1.2488144018518446e-05, 'F': 1.5220726376827412e-05, 'B': 6.582607580061271e-05, 'J': 0.0001340179511208881}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00022755289731668515}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 135:
  We focus on the sustainable gathering of mosses and lichens, which are collected from pristine natural environments. Our team is trained in ethical harvesting techniques that ensure the continued growth and health of these organisms. The collected mosses and lichens are used in a variety of applications, including decorative arts, horticulture, and traditional medicine. By promoting sustainable practices and educating consumers about the ecological significance of these materials, we aim to foster a greater appreciation for the natural world and its resources.1. Our company specializes in the sustainable gathering of wild mushrooms and truffles, focusing on premium quality products sourced from diverse forest ecosystems. We employ expert foragers who meticulously harvest these delicacies, ensuring that our practices promote ecological balance and preserve local biodiversity. Our products are then processed and packaged for gourmet markets and restaurants, where they are celebrated for their unique flavors and culinary applications. By fostering relationships with local chefs and food artisans, we enhance the value of our offerings and contribute to the growing trend of foraged ingredients in high-end cuisine.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.017684469642443804, 'A': 0.6401165201304749, 'F': 0.03645559360225382, 'B': 0.30119691034831436, 'J': 0.004546506276512995}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.35988347986952507}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 17%|██████████████████████████████▍                                                                                                                                                | 137/788 [00:09<00:46, 13.92it/s]

RAPS scores:

==================================================
Description 136:
  As a premier tree nursery, we focus on the cultivation and sale of a wide variety of ornamental and shade trees. Our nursery employs sustainable practices, ensuring that our trees are grown in an environmentally friendly manner. We provide a selection of native and exotic species, catering to both landscapers and individual customers. Our knowledgeable staff offers expert advice on tree selection and care, helping clients choose the right trees for their specific needs. Additionally, we host workshops on tree planting and maintenance, fostering community engagement and promoting the importance of green spaces.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0011321428018699748, 'A': 0.8936379493548207, 'F': 0.10167031037706607, 'B': 0.0025460451103595646, 'J': 0.001013552355883791}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10636205064517934}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 137:
  We focus on the extraction of natural gas, utilizing advanced technologies to improve our operational efficiency and reduce environmental impact. Our drilling operations are complemented by sophisticated gas processing facilities that include desulphurization units to ensure product quality. We are committed to sustainability and actively seek to implement innovative practices that enhance our extraction methods while minimizing emissions. Our goal is to provide reliable and clean natural gas to meet the growing energy demands of our customers while contributing positively to the communities we operate in.1. Our company specializes in the extraction and production of natural gas, utilizing advanced drilling techniques and state-of-the-art technology to maximize recovery rates. We operate several offshore and onshore facilities, where we implement rigorous safety and environmental protocols. Our operations include the processing of extracted gas to remove impurities, ensuring that the final product meets the highest quality standards for distribution. Additionally, we invest in research and development to enhance extraction efficiency and reduce the carbon footprint of our operations, positioning ourselves as a leader in sustainable energy production.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.513523820428903e-05, 'A': 3.4700966055585364e-05, 'F': 1.2471541332265944e-05, 'B': 0.9998904596599805, 'J': 7.232594427379914e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010954034001953161}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 138:
  Our business focuses on the production of firewood, catering to both residential and commercial markets. We source timber from sustainably managed forests, ensuring that our firewood is not only high-quality but also environmentally responsible. Our operations include efficient processing and packaging, allowing us to deliver a reliable product to our customers. By promoting the use of renewable energy sources, we contribute to reducing carbon footprints and supporting sustainable heating solutions. Our dedication to quality and sustainability has established us as a preferred supplier in the firewood market.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.9748273835157761, 'A': 0.0005497461252007416, 'F': 0.0008099579866654031, 'B': 0.02286660399003367, 'J': 0.000946308382323977}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.025172616484223864}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 18%|███████████████████████████████                                                                                                                                                | 140/788 [00:09<00:45, 14.12it/s]

RAPS scores:

==================================================
Description 139:
  Our company specializes in the mining of lead and zinc ores, focusing on sustainable practices that minimize environmental impact. We employ advanced technologies to enhance ore processing efficiency, ensuring that we produce high-quality concentrates for the metallurgical industry. Our operations include comprehensive environmental management systems to monitor and mitigate any potential impacts from mining activities. By investing in research and development, we aim to improve our extraction methods and contribute to the circular economy through recycling initiatives in the non-ferrous metals sector.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5620614804016276e-05, 'A': 3.4124672075734834e-05, 'F': 1.2304587309603124e-05, 'B': 0.9998908130459556, 'J': 7.1370798549834965e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4519696436646817e-06, 6: 1.6038743432965124e-06, 7: 0.9999959441560131}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03515461806850219, 7.2: 0.9648453819314977}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 140:
  Engaged in the mining of rare earth elements, our company plays a crucial role in the supply chain for high-tech industries. We utilize advanced separation and refining processes to extract valuable materials from complex ore bodies. Our research initiatives focus on developing innovative techniques to enhance recovery rates and reduce the environmental footprint of our operations. By partnering with technology firms, we aim to create value-added products that meet the specific needs of the electronics and renewable energy sectors. Our dedication to sustainable practices and continuous improvement positions us as a key player in the non-ferrous metal mining landscape.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.565643247780225e-05, 'A': 3.408255068117753e-05, 'F': 1.2298123587573655e-05, 'B': 0.9998908396271261, 'J': 7.1232661274667995e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4562344570743448e-06, 6: 1.6016885402640193e-06, 7: 0.9999959420770026}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03510577781994068, 7.2: 0.9648942221800593}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 18%|███████████████████████████████▉                                                                                                                                               | 144/788 [00:09<00:52, 12.16it/s]

RAPS scores:

==================================================
Description 141:
  Our organization is dedicated to the mining of titanium and zirconium ores, focusing on high-quality extraction and processing methods. We employ advanced separation technologies that allow us to efficiently isolate valuable minerals while minimizing waste. Our commitment to research and development enables us to explore new applications for titanium and zirconium in various industries, including aerospace, medical devices, and consumer goods. By fostering partnerships with research institutions, we aim to innovate our product offerings and enhance the performance characteristics of our materials, driving value for our customers and stakeholders.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.558584345174225e-05, 'A': 3.4174464631113974e-05, 'F': 1.2356326718874357e-05, 'B': 0.9998907180447878, 'J': 7.165320410569672e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4558339297525384e-06, 6: 1.602667959260421e-06, 7: 0.999995941498111}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035141988571594826, 7.2: 0.9648580114284051}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 142:
  In the realm of freshwater aquaculture, our business is dedicated to the cultivation of tilapia and catfish in controlled environments. Our facilities employ innovative water filtration and aeration systems to maintain ideal conditions for fish growth. We prioritize eco-friendly practices, such as using plant-based feeds and implementing biosecurity measures to protect our stock from diseases. Our commitment to sustainability extends to our packaging, which is designed to minimize environmental impact. By partnering with local distributors, we ensure that our fresh fish reach consumers quickly, promoting healthy eating habits while supporting local economies.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0006146240198796834, 'A': 0.9913848283170784, 'F': 0.003175624264062334, 'B': 0.0044173217354136025, 'J': 0.0004076016635658042}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.008615171682921585}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 143:
  Our core business revolves around the mining and beneficiation of iron ores, where we utilize cutting-edge technologies to extract and process high-quality materials. We employ a variety of methods to ensure efficient ore extraction, including both surface and underground mining techniques. Following extraction, our beneficiation processes enhance the iron content of the ore through advanced techniques such as magnetic separation and flotation. Additionally, we produce iron ore pellets through agglomeration, which are tailored for optimal performance in the steel industry, providing our clients with reliable and high-value products.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.520080107595493e-05, 'A': 3.422134691811599e-05, 'F': 1.2328187949028629e-05, 'B': 0.9998910800706229, 'J': 7.169593433913854e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4963109655760997e-06, 6: 1.5704095053341546e-06, 7: 0.9999959332795292}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678033991173897, 7.2: 0.032196600882610206}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 19%|████████████████████████████████▋                                                                                                                                              | 147/788 [00:09<00:44, 14.33it/s]

RAPS scores:

==================================================
Description 144:
  We are dedicated to the extraction of natural gas, with a focus on innovative methods that enhance recovery rates while minimizing environmental impact. Our operations include the drilling of new wells and the re-evaluation of existing sites to identify opportunities for increased production. We utilize cutting-edge technologies such as 3D seismic imaging and automated drilling systems to optimize our extraction processes. Additionally, our investment in gas desulphurization facilities ensures that the natural gas we supply is not only efficient but also environmentally friendly, contributing to cleaner energy solutions for our clients.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.502319123217423e-05, 'A': 3.4924589014688044e-05, 'F': 1.2560462813753365e-05, 'B': 0.9998902393341391, 'J': 7.252422800177653e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010976066586088074}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 145:
  Our company is at the forefront of aquaponics, a revolutionary approach that combines aquaculture with hydroponics. By cultivating fish alongside plants in a symbiotic environment, we create a sustainable food production system that maximizes resource efficiency. The waste produced by the fish serves as a nutrient source for the plants, while the plants help filter and purify the water for the fish. This innovative method not only reduces water usage but also allows us to produce fresh vegetables and fish for local markets. Our commitment to sustainability drives our operations, making us a model for future food production.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 3.18900778358487e-05, 'A': 0.9997142352047863, 'F': 0.00011091291523635382, 'B': 0.00010997824343761289, 'J': 3.298355870369532e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00028576479521369436}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 146:
  We are committed to the growth of other perennial crops, focusing on a diverse range of plants that contribute to ecological balance and sustainability. Our operations include the cultivation of various nuts, such as almonds and walnuts, which are known for their health benefits. We implement agroforestry practices that integrate tree crops with other agricultural systems, promoting biodiversity and soil health. Our products are marketed through both traditional retail channels and online platforms, ensuring that we reach a wide audience while supporting sustainable agricultural practices.1. Our company specializes in the cultivation of premium grapes, focusing on both table and wine varieties. We employ sustainable farming practices that enhance soil health and biodiversity, ensuring high-quality yields year after year. Our vineyards are strategically located in regions with optimal climate conditions, allowing us to produce grapes with exceptional flavor profiles. We also invest in advanced irrigation technologies to conserve water while maximizing crop output. The grapes are harvested at peak ripeness and processed in our state-of-the-art winery, where we produce a range of award-winning wines that cater to both local and international markets.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.1562749393539438, 'A': 0.028925663349871674, 'F': 0.03703441846806897, 'B': 0.7725006972658417, 'J': 0.005264281562273816}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2274993027341583}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:

 19%|█████████████████████████████████▊                                                                                                                                             | 152/788 [00:10<00:39, 16.02it/s]

RAPS scores:

==================================================
Description 147:
  The business is dedicated to the collection of mollusks and crustaceans along the intertidal zones, employing skilled divers and hand-harvesting techniques. This artisanal approach not only preserves the delicate marine environment but also yields premium-quality shellfish, including clams and crabs, which are highly sought after in gourmet markets. The company emphasizes traceability and sustainability, providing detailed sourcing information to consumers. Additionally, it collaborates with local chefs to promote seasonal dishes that highlight the freshness of its catch, enhancing the culinary experience while supporting local gastronomy.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.2302304726973039e-05, 'A': 0.9998984074475745, 'F': 4.053643272409873e-05, 'B': 3.4032797488794005e-05, 'J': 1.4721017485699392e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007448812758235134, 2: 0.0009268883393399009, 3: 0.9983282303848366}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9574412303760927, 3.2: 0.042558769623907346}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 148:
  Focusing on the production of molluscs, our aquaculture business is dedicated to the sustainable farming of mussels and scallops. We utilize longline systems that allow for efficient growth while minimizing habitat disruption. Our commitment to environmental stewardship is reflected in our rigorous monitoring of water quality and adherence to best practices in aquaculture. By partnering with local chefs and seafood markets, we promote the culinary versatility of our products, fostering a deeper appreciation for sustainably farmed shellfish within the community.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of various fish species, including salmon and sea bass. Utilizing advanced recirculating aquaculture systems (RAS), we optimize water quality and minimize environmental impact while maximizing yield. Our operations include hatchery management, where we carefully monitor breeding conditions to ensure high survival rates of juvenile fish. We also implement rigorous feeding protocols to promote healthy growth and enhance the nutritional value of our products. By maintaining stringent biosecurity measures, we protect our stock from diseases, ensuring a consistent supply of high-quality seafood to our customers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.23808344497920253, 'A': 0.01645022445262788, 'F': 0.026320424373462794, 'B': 0.7144475727892619, 'J': 0.004698333405444987}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.28555242721073815}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 149:
  We specialize in the raising of goats, offering a range of products including dairy, meat, and fiber. Our operations emphasize humane treatment and sustainable practices, ensuring that our goats thrive in a healthy environment. We have developed a niche market for goat cheese, which is produced on-site and sold at local farmers' markets. Our goats are also raised for their unique fibers, which are processed into high-quality textiles. We engage with local communities through educational programs that promote the benefits of goat farming and sustainable agriculture.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.01302806204196006, 'A': 0.6317332633148424, 'F': 0.047922065596674765, 'B': 0.3035778002037036, 'J': 0.00373880884281923}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.36826673668515764}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 150:
  Our company is engaged in the cultivation of stone fruits, including cherries, peaches, and plums, known for their rich flavors and nutritional benefits. We employ innovative farming techniques, such as drip irrigation and soil moisture sensors, to enhance fruit quality and reduce water consumption. Our commitment to sustainable agriculture is evident in our use of organic pest control methods and cover cropping strategies that improve soil health. We also focus on value-added products, such as jams and preserves, to diversify our revenue streams. By collaborating with local retailers and participating in community events, we promote our stone fruits and strengthen our brand presence in the market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.04616089228034804, 'A': 0.02192883868730189, 'F': 0.012366313600181889, 'B': 0.9172303203695615, 'J': 0.002313635062606726}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08276967963043846}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 151:
  We are engaged in the large-scale cultivation of sugar cane, focusing on sustainable farming practices that enhance both yield and environmental stewardship. Our operations involve state-of-the-art harvesting techniques and efficient processing methods that maximize sugar extraction. We collaborate with local communities to promote fair labor practices and provide economic opportunities. Additionally, we invest in renewable energy initiatives by converting waste from sugar processing into biofuel, contributing to a circular economy and reducing our carbon footprint.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.005571646152179912, 'A': 0.19107302919517533, 'F': 0.004164409258377678, 'B': 0.7976214806734947, 'J': 0.0015694347207723155}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2023785193265053}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 20%|███████████████████████████████████                                                                                                                                            | 158/788 [00:10<00:31, 20.07it/s]

RAPS scores:

==================================================
Description 152:
  We are at the forefront of integrating sustainability into our lignite mining operations. Our commitment to environmentally responsible practices includes the rehabilitation of mined land and the implementation of water conservation measures during the washing and processing stages. We actively seek to minimize waste and promote the use of lignite as a cleaner energy source. By aligning our business activities with sustainable development goals, we not only meet regulatory requirements but also contribute positively to the communities we serve.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.498585827233331e-05, 'A': 3.5194601557175053e-05, 'F': 1.2602805633067823e-05, 'B': 0.9998899341579669, 'J': 7.282576570540807e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011006584203310243}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 153:
  Our aquaculture business is dedicated to the farming of crustaceans, particularly shrimp and prawns, in biosecure environments. We implement advanced breeding techniques to enhance growth rates and disease resistance, ensuring a steady supply of high-quality seafood. Our facilities are equipped with modern water filtration systems and automated feeding technologies, which help optimize production efficiency. We also prioritize traceability in our supply chain, allowing consumers to know the origin of their seafood. By adhering to strict sustainability standards, we aim to meet the increasing consumer demand for responsibly sourced seafood products.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0017568883354905764, 'A': 0.962537796474282, 'F': 0.004517962646533291, 'B': 0.03029570500778373, 'J': 0.0008916475359104861}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03746220352571805}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 154:
  We specialize in the conservation and management of forest resources, employing a range of silvicultural practices to enhance forest health and productivity. Our team conducts regular assessments of timber tracts, identifying opportunities for thinning and selective harvesting that promote the growth of high-value species. We also invest in advanced technologies for monitoring forest conditions, allowing us to respond proactively to threats such as pests and diseases. By implementing sustainable forestry practices, we ensure that our operations not only yield economic benefits but also preserve the ecological integrity of the forests we manage.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.20634783171075e-05, 'A': 0.9996654958538137, 'F': 0.00014296072464995018, 'B': 0.0001252276382900504, 'J': 3.4252304929137885e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00033450414618629853}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 155:
  As a leader in aquaculture, we have expanded our operations to include the farming of alligators and crocodiles, catering to niche markets for both meat and leather. Our facilities are designed to mimic natural habitats, promoting the well-being of these reptiles while optimizing growth conditions. We adhere to strict animal welfare standards and engage in conservation efforts to protect wild populations. By offering high-quality alligator and crocodile products, we not only meet consumer demand but also contribute to sustainable wildlife management practices, ensuring that our operations are both profitable and environmentally responsible.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00014988979429741148, 'A': 0.9979057228204872, 'F': 0.0009002752654429925, 'B': 0.0009103497022136703, 'J': 0.00013376241755847873}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0020942771795128268}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 156:
  Engaged in the raising of horses, our establishment focuses on breeding and training high-performance equines for various disciplines. We emphasize the importance of proper nutrition and care, providing our horses with a balanced diet and access to veterinary services. Our training programs are tailored to individual horse needs, promoting skill development and well-being. We also offer riding lessons and equestrian events, fostering a community of horse enthusiasts. Our commitment to excellence in breeding and training has positioned us as a leader in the equine industry, attracting clients from across the region.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0015748739777960979, 'A': 0.8502605107823716, 'F': 0.14193233361007596, 'B': 0.004749422335439203, 'J': 0.0014828592943171774}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.14973948921762836}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 157:
  Our firm specializes in amphibian aquaculture, particularly in the cultivation of frogs for culinary markets. We utilize innovative breeding techniques to ensure a steady supply of high-quality frogs, while maintaining strict biosecurity measures to prevent disease. Our farms are designed to replicate natural habitats, promoting healthy growth and reproduction. We also focus on sustainability by implementing water recycling systems and organic feeding practices. By collaborating with chefs and food distributors, we are able to showcase the culinary potential of our products, increasing their visibility and demand in gourmet markets.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00623901927647905, 'A': 0.8986495410351127, 'F': 0.028055274420851126, 'B': 0.06458023657776496, 'J': 0.002475928689792135}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10135045896488726}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 20%|███████████████████████████████████▊                                                                                                                                           | 161/788 [00:10<00:28, 21.85it/s]

RAPS scores:

==================================================
Description 158:
  Our operations include the growing of various perennial crops, focusing on unique varieties that are often overlooked in mainstream agriculture. By cultivating these crops, we aim to diversify the agricultural landscape and promote biodiversity. We work closely with research institutions to develop resilient crop varieties that can thrive in changing climates. Additionally, we offer consulting services to other farmers interested in transitioning to perennial systems, sharing our expertise and promoting sustainable agricultural practices.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.0012756370878271052, 'A': 0.9811549353689231, 'F': 0.006924499550605915, 'B': 0.009941402115150136, 'J': 0.0007035258774938435}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.018845064631076935}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 159:
  Specializing in the raising of horses, our facility offers comprehensive breeding, training, and boarding services. We prioritize the health and well-being of our equines, providing them with spacious pastures and high-quality nutrition. Our training programs are tailored to develop both performance and companionship qualities in horses, catering to various disciplines such as dressage and show jumping. We also host equestrian events, fostering a vibrant community of horse enthusiasts and promoting awareness about responsible horse ownership.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0025911803656421674, 'A': 0.5443903399808868, 'F': 0.4414784723447601, 'B': 0.009154138772254024, 'J': 0.002385868536456837}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4556096600191132}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 160:
  Our business is dedicated to the cultivation of spices and aromatic crops, including basil, mint, and saffron. We prioritize organic farming practices, utilizing crop rotation and natural pest deterrents to maintain soil health and product quality. After harvesting, our spices are carefully dried and packaged to preserve their flavor and aroma, ensuring they meet the highest standards for culinary use. We also engage in partnerships with local chefs and restaurants to promote the use of fresh, locally sourced spices, enhancing the culinary experience while supporting sustainable agriculture.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.032680563711419454, 'A': 0.13508539301242237, 'F': 0.02802126622374373, 'B': 0.8003381292049342, 'J': 0.003874647847480231}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1996618707950658}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 161:
  We engage in the sustainable gathering of balata and other rubber-like gums, which are harvested from specific tree species in tropical regions. Our team is trained in ethical tapping methods that minimize harm to the trees and promote regrowth. The collected gum is processed and sold to manufacturers of natural rubber products, including footwear and adhesives. By focusing on eco-friendly practices and maintaining strong relationships with local communities, we ensure that our operations support both environmental sustainability and economic development in the regions where we work.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0033698661707189416, 'A': 0.9267821385238003, 'F': 0.0046502904626680745, 'B': 0.06368904163822872, 'J': 0.0015086632045837821}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07321786147619969}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 162:
  Our company is a pioneer in sustainable forestry, engaging in a range of activities that support the growth of timber resources. We focus on planting and replanting initiatives that enhance forest ecosystems and improve timber quality. Our tree nurseries are equipped with advanced technologies that ensure optimal growth conditions for seedlings. Additionally, we cultivate coppice and pulpwood, providing essential materials for various industries. By integrating conservation efforts into our business model, we not only meet market demands but also contribute to the preservation of biodiversity and the health of our planet.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.543571176826395e-05, 'A': 0.9995915696979846, 'F': 0.00019625700071325132, 'B': 0.00013863798521886487, 'J': 3.809960431512275e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00040843030201542785}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 21%|█████████████████████████████████████                                                                                                                                          | 167/788 [00:10<00:29, 20.77it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 163:
  Our lignite mining operations are characterized by a strong emphasis on quality and efficiency. We utilize both traditional and innovative mining methods to extract lignite, followed by advanced processing techniques that include washing, dehydrating, and pulverizing. This ensures that our product is not only of high quality but also easy to transport and store. Our strategic partnerships with transportation providers enable us to deliver lignite to various markets swiftly, reinforcing our position as a reliable supplier in the energy landscape.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.503124360831364e-05, 'A': 3.424641031010867e-05, 'F': 1.2325245340578336e-05, 'B': 0.9998912575227125, 'J': 7.1395780285419644e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957319509727, 6: 1.3460518013329232e-06, 7: 2.92199722598248e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023545352097951856, 5.2: 0.9976454647902048}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 164:
  As a prominent natural gas producer, we engage in the extraction and processing of crude gaseous hydrocarbons from diverse geological formations. Our approach includes the use of advanced drilling rigs and completion techniques that optimize gas recovery rates. We specialize in the separation of liquid hydrocarbon fractions, utilizing proprietary technologies that enhance efficiency and reduce waste. Our gas desulphurization processes are designed to meet both regulatory requirements and customer specifications, ensuring the delivery of high-quality gas products. By focusing on innovation and operational excellence, we are positioned to lead in the energy sector while promoting sustainable practices.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.50735325394136e-05, 'A': 3.460717997732101e-05, 'F': 1.2446953591736186e-05, 'B': 0.9998906348979528, 'J': 7.237435938670861e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010936510204717642}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 165:
  We are dedicated to the mining and beneficiation of iron ores, focusing on the production of high-grade iron pellets for the steel manufacturing sector. Our operations include extensive geological exploration to identify rich ore bodies, followed by the use of advanced extraction techniques that ensure minimal waste. The beneficiation process involves crushing, grinding, and magnetic separation to enhance the iron content of the ore. Our facilities are equipped with cutting-edge technology that allows for real-time monitoring of production metrics, ensuring quality and efficiency. We are committed to sustainable practices, investing in renewable energy solutions to power our operations and reduce our carbon footprint.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.676578635945027e-05, 'A': 3.373656896435436e-05, 'F': 1.2278174634632627e-05, 'B': 0.9998900859559603, 'J': 7.133514081332115e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010991404403970506}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 166:
  We specialize in the raising of camels, capitalizing on their adaptability and resilience in arid environments. Our operations focus on breeding high-quality camels for both milk production and tourism. We have developed a niche market for camel milk, which is rich in nutrients and gaining popularity among health enthusiasts. Additionally, our farm offers camel rides and educational tours, providing visitors with an immersive experience while promoting awareness about camel husbandry. Our commitment to sustainable practices ensures that our operations have a minimal environmental impact.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00451412394009339, 'A': 0.9109635458980602, 'F': 0.02416824768810767, 'B': 0.05838547089270249, 'J': 0.0019686115810363045}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08903645410193983}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 167:
  We specialize in the production of turfgrass for landscaping and sports fields, focusing on high-performance varieties that thrive in various climates. Our extensive research into soil health and grass genetics allows us to develop turf that is drought-resistant and disease-tolerant. We provide customized solutions for clients, including installation services and ongoing maintenance plans to ensure the longevity and health of the turf. Our commitment to sustainability includes water-efficient growing practices and eco-friendly pest management, making us a preferred partner for environmentally conscious projects.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9967060231639185, 'A': 0.00021384835572088828, 'F': 0.0005341780245805623, 'B': 0.0016777554425717346, 'J': 0.0008681950132082908}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003293976836081458}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 22%|██████████████████████████████████████▍                                                                                                                                        | 173/788 [00:11<00:26, 22.98it/s]

RAPS scores:

==================================================
Description 168:
  We specialize in the traditional production of charcoal within forested areas, utilizing age-old methods that preserve the integrity of the ecosystem. Our charcoal is crafted from sustainably sourced wood, ensuring that the harvesting process does not compromise forest health. This product is highly sought after for both culinary and industrial uses, and we take pride in offering a natural alternative to chemical-laden fuels. Our commitment to quality and sustainability has positioned us as a trusted supplier in the market, catering to both local and international customers.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9526564626581959, 'A': 0.0005254380521444182, 'F': 0.0006851213617177165, 'B': 0.04531766262132131, 'J': 0.0008153153066206545}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.047343537341804076}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 169:
  Our company operates in the natural gas sector, focusing on the extraction and processing of crude gaseous hydrocarbons. We utilize innovative drilling technologies to access previously unreachable reserves, ensuring a reliable supply of natural gas. Our facilities are equipped with advanced separation systems that efficiently isolate liquid hydrocarbon fractions, which are essential for various industrial applications. Additionally, we implement rigorous gas desulphurization processes to enhance product quality and reduce environmental impact. Through strategic partnerships and investments in technology, we strive to remain at the forefront of the energy industry.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.483267126341788e-05, 'A': 3.4763779805960384e-05, 'F': 1.2478304580656601e-05, 'B': 0.9998906817264436, 'J': 7.2435179062575375e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010931827355642465}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 170:
  Engaged in the extraction of crude petroleum, we operate several key drilling sites across diverse geographical locations. Our operations are supported by a robust supply chain that ensures timely delivery of essential equipment and materials. We employ advanced reservoir management techniques to maximize oil recovery while minimizing environmental impact. Our commitment to technological innovation includes the use of artificial intelligence for predictive maintenance of drilling rigs, reducing downtime and enhancing productivity. Furthermore, we actively participate in industry forums to share best practices and collaborate on initiatives aimed at improving safety and sustainability in oil extraction.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5041065107665824e-05, 'A': 3.460614125863623e-05, 'F': 1.2463226906671797e-05, 'B': 0.9998906606428539, 'J': 7.228923873079787e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010933935714607657}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 171:
  Our company is dedicated to the gathering of mosses and lichens, focusing on sustainable practices that protect these delicate ecosystems. We work with local foragers to collect these materials, which are then used in various applications, including decorative arts and natural gardening products. By emphasizing the ecological benefits of mosses and lichens, we educate consumers about their role in the environment while providing high-quality, sustainably sourced products. Our commitment to sustainability and community engagement sets us apart in the market, appealing to consumers who value ethical sourcing.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.012846702669905818, 'A': 0.6532303611269389, 'F': 0.05572442435141783, 'B': 0.27410137892972664, 'J': 0.00409713292201074}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3467696388730611}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 172:
  Our operations include the traditional production of charcoal in forested areas, where we employ age-old methods that respect the environment. By carefully selecting the right types of wood and controlling the carbonization process, we produce high-quality charcoal that is sought after for both grilling and industrial applications. We focus on sustainable harvesting techniques, ensuring that our charcoal production does not deplete forest resources. Our products are marketed to local businesses and consumers who appreciate the craftsmanship and authenticity of traditionally made charcoal, allowing us to carve out a niche in the market.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9992535159026212, 'A': 3.5542647713683584e-05, 'F': 4.1651284952346615e-05, 'B': 0.0004936497506874797, 'J': 0.0001756404140253347}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007464840973787634}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 173:
  Our company is committed to the capture fishery sector, focusing on the collection of shellfish from intertidal zones. We employ skilled divers and hand-harvesting techniques to gather premium mollusks such as clams and oysters. By utilizing environmentally friendly practices, we ensure minimal disruption to the habitat while maintaining high standards of quality. Our shellfish are sold directly to seafood markets and high-end restaurants, where they are celebrated for their freshness and flavor. Additionally, we engage in community outreach programs to educate the public on sustainable harvesting methods.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.003644437559099248, 'A': 0.5886155718035815, 'F': 0.004259605524505871, 'B': 0.4018637368529923, 'J': 0.0016166482598208884}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4113844281964185}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 22%|███████████████████████████████████████                                                                                                                                        | 176/788 [00:11<00:27, 22.66it/s]

RAPS scores:

==================================================
Description 174:
  We engage in the production of charcoal using traditional methods that emphasize sustainability and quality. Our sourcing practices involve selecting wood from responsibly managed forests, ensuring that our production does not harm the environment. The charcoal we produce is favored by both local consumers and international markets, known for its superior burning qualities. We also focus on educating our customers about the benefits of using sustainable charcoal, promoting a shift towards eco-friendly fuel options. Our dedication to traditional craftsmanship and environmental stewardship sets us apart in the charcoal industry.1. Our company specializes in the sustainable harvesting of roundwood, ensuring a steady supply of high-quality logs for the construction and manufacturing sectors. We employ advanced logging techniques that minimize environmental impact while maximizing yield. Our operations include selective logging practices that promote forest regeneration, allowing us to maintain a balance between resource extraction and ecological preservation. Additionally, we process some of our harvested wood into utility poles and fence posts, catering to both local and regional markets. This dual approach not only supports our business growth but also contributes to the sustainability of forest resources.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.03056191540594414, 'A': 0.0007339307643351528, 'F': 0.0005376589569334802, 'B': 0.9678517564767286, 'J': 0.00031473839605864634}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03214824352327139}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 175:
  Our company is at the forefront of aquaculture technology, developing innovative solutions for the farming of molluscs, particularly oysters and clams. We have implemented cutting-edge hatchery techniques that increase larval survival and growth rates. By utilizing environmentally friendly materials for our farming structures, we minimize our ecological footprint while maximizing production efficiency. Our commitment to research and development enables us to continuously improve our farming practices, ensuring that we provide high-quality shellfish to the market while promoting sustainability in marine environments.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0027864885231017864, 'A': 0.9395687421976969, 'F': 0.010187788423181557, 'B': 0.046187313859566405, 'J': 0.0012696669964534942}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.06043125780230307}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 176:
  Our business is dedicated to the mining and processing of hard coal, employing a combination of surface and underground techniques to extract high-quality resources. We utilize state-of-the-art cleaning and sizing technologies to ensure that our coal meets industry standards for purity and performance. Additionally, our pulverizing capabilities allow us to create tailored coal products that serve a wide range of industrial applications, from energy generation to manufacturing. We are committed to sustainable practices that minimize our environmental impact while maximizing the value we deliver to our customers.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.524954204643029e-05, 'A': 3.418890851195052e-05, 'F': 1.2344057965149476e-05, 'B': 0.9998910406828891, 'J': 7.176808587450905e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957142249503, 6: 1.3160246694570926e-06, 7: 2.9697503803922253e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975308040473938, 5.2: 0.002469195952606232}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 23%|███████████████████████████████████████▊                                                                                                                                       | 179/788 [00:11<00:37, 16.30it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 177:
  We specialize in the extraction and production of natural gas, leveraging advanced drilling technologies to optimize resource recovery. Our operations include the draining and separation of liquid hydrocarbon fractions, which enhances our product offerings and meets the diverse needs of our clients. Our commitment to sustainability is evident in our investment in gas desulphurization systems that reduce harmful emissions and improve the overall quality of our products. By employing data-driven strategies and real-time monitoring, we ensure operational excellence and drive profitability. Our focus on innovation positions us as a leader in the natural gas industry, dedicated to delivering value to our customers and stakeholders.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.532872414495717e-05, 'A': 3.432728545115934e-05, 'F': 1.2386111660276084e-05, 'B': 0.9998907679120933, 'J': 7.189966650323675e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7770251669294064e-06, 6: 0.9999964073704404, 7: 1.8156043925694815e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979664723696974, 6.1: 0.0020335276303025365}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 178:
  This aquaculture operation specializes in the production of ornamental fish for the global aquarium trade. With a focus on breeding rare and exotic species, they maintain high standards of care and environmental enrichment to promote healthy growth. The company utilizes innovative breeding techniques to enhance coloration and size, catering to the demands of hobbyists and retailers. They also prioritize education and outreach, providing resources for responsible fishkeeping practices to their customers. By fostering a strong community around ornamental aquaculture, they contribute to the growth and sustainability of the industry.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of various fish species, including salmon and tilapia. Utilizing advanced recirculating aquaculture systems, we ensure optimal water quality and environmental conditions to maximize growth rates. Our operations include regular feeding schedules, health monitoring, and protection against predators, which collectively enhance yield and quality. We also engage in research and development to improve breeding techniques and feed formulations, aiming to produce healthier fish while minimizing our ecological footprint. Our commitment to sustainability is reflected in our certifications and partnerships with environmental organizations.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 1.4503816273715558e-05, 'A': 0.9998764926445926, 'F': 5.326243626849657e-05, 'B': 3.9199538142888665e-05, 'J': 1.654156472239326e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001235073554074484}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 179:
  In the realm of freshwater aquaculture, we operate extensive facilities dedicated to the cultivation of tilapia and catfish. Our approach integrates innovative farming techniques, such as aquaponics, where fish waste provides nutrients for hydroponically grown plants. This symbiotic relationship not only maximizes resource efficiency but also diversifies our product offerings. We prioritize eco-friendly practices, including water recycling and organic feed, to enhance sustainability. Our products are marketed directly to local restaurants and grocery chains, ensuring a fresh supply while promoting the benefits of locally sourced seafood.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00014322353946476395, 'A': 0.9983994337043165, 'F': 0.0005221352822573657, 'B': 0.0008136055233496002, 'J': 0.00012160195061165621}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0016005662956835032}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 180:
  Our extraction activities are centered around maximizing crude petroleum recovery through innovative techniques such as micro-seismic monitoring and reservoir simulation modeling. By employing these technologies, we can accurately assess reservoir conditions and optimize our extraction strategies. Our commitment to sustainability is reflected in our efforts to reduce greenhouse gas emissions during production, utilizing carbon capture and storage solutions where feasible. We believe that responsible extraction practices not only benefit our bottom line but also contribute to the global transition towards cleaner energy sources.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4823626961703196e-05, 'A': 3.4875146756848435e-05, 'F': 1.246717573976736e-05, 'B': 0.9998905909149478, 'J': 7.243135593856895e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010940908505219227}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 23%|████████████████████████████████████████▍                                                                                                                                      | 182/788 [00:11<00:37, 16.01it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 181:
  We are dedicated to the responsible mining of hard coal, employing both traditional and innovative extraction methods to optimize resource recovery. Our surface mining operations are complemented by advanced technologies for cleaning and grading coal, ensuring that our products are of the highest quality. Additionally, we have implemented state-of-the-art pulverizing techniques that enhance the coal's usability in various applications, from power generation to steel production. Our commitment to sustainability drives us to continuously seek ways to reduce our environmental footprint while delivering value to our customers.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.503972115321552e-05, 'A': 3.4310492467419615e-05, 'F': 1.2343597359422204e-05, 'B': 0.9998911577274648, 'J': 7.1484615553021305e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957191351053, 6: 1.3222720805917986e-06, 7: 2.958592814113112e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997529121595978, 5.2: 0.002470878404021991}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 182:
  Our company is dedicated to the efficient mining of hard coal, utilizing both surface and underground methods tailored to the geological conditions of our sites. We invest in cutting-edge technology for extraction and processing, which includes advanced cleaning and grading systems that enhance coal quality. Our operations are designed to be environmentally responsible, with a focus on reducing emissions and managing waste effectively. We also maintain strong relationships with transport partners, ensuring that our coal reaches customers in a timely manner while preserving its integrity throughout the supply chain.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4868674820942e-05, 'A': 3.448705483114781e-05, 'F': 1.2392820649548599e-05, 'B': 0.999891065252923, 'J': 7.186196775278659e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957270011862, 6: 1.341311772237214e-06, 7: 2.9316870414997415e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997526912231132, 5.2: 0.0024730877688681}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 24%|█████████████████████████████████████████▌                                                                                                                                     | 187/788 [00:12<00:37, 15.95it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 183:
  Our operations encompass the full spectrum of iron ore mining, from initial exploration to the final delivery of processed ores. We leverage innovative technologies such as remote sensing and automated drilling to enhance our mining efficiency. The beneficiation process is critical to our business model; we employ advanced techniques like hydrocycloning and gravity separation to produce high-quality iron concentrates. Our products are tailored to meet the specific needs of our clients in the steel industry, and we maintain rigorous quality control measures to ensure compliance with international standards.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.4806096510902436e-05, 'A': 3.445181638884128e-05, 'F': 1.2368617785181045e-05, 'B': 0.9998912134102513, 'J': 7.160059063793519e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.489256341243336e-06, 6: 1.5695104309308794e-06, 7: 0.9999959412332279}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677882031051881, 7.2: 0.032211796894811885}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 184:
  Our business is dedicated to the growth of fiber crops, specifically cotton and flax, which are essential for the textile industry. We focus on sustainable agricultural practices that promote soil health and biodiversity, utilizing cover crops and reduced tillage methods. Our state-of-the-art ginning facilities process the harvested fibers, ensuring high-quality output for textile manufacturers. By collaborating with fashion brands committed to sustainability, we help create eco-friendly fabrics that appeal to environmentally conscious consumers while supporting local farming communities.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.20408494852759926, 'A': 0.01472074760091683, 'F': 0.021811679905907495, 'B': 0.7554270779323985, 'J': 0.003955546033177925}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2445729220676015}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 185:
  Our business focuses on the cultivation of mollusks, particularly oysters and clams, through environmentally friendly aquaculture practices. We utilize bottom culture and suspended culture techniques to enhance growth and ensure a sustainable harvest. By carefully selecting locations with optimal water quality and nutrient availability, we maximize production while preserving the natural habitat. Our operations include seed collection, grow-out management, and post-harvest processing, allowing us to deliver high-quality shellfish to markets. We also engage in community outreach to educate consumers about the benefits of aquaculture and the importance of sustainable seafood choices.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.06273838268434813, 'A': 0.19031506371205786, 'F': 0.09326846323714827, 'B': 0.6466673092244085, 'J': 0.007010781142037191}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3533326907755915}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 186:
  Our agricultural business is dedicated to the raising of other animals, including alpacas and llamas, for their fiber and companionship. We implement sustainable farming practices that ensure the health of our animals and the land they inhabit. Our fiber is processed on-site, allowing us to create high-quality products such as yarn and textiles that appeal to artisans and crafters. We also offer farm tours and educational workshops to engage the community and promote awareness of these unique animals. By combining agriculture with tourism, we create additional revenue streams while fostering a connection between people and animals.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00022288521366836399, 'A': 0.9966492828301479, 'F': 0.0011088206277981697, 'B': 0.0018404863894244707, 'J': 0.00017852493896100506}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0033507171698521354}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 24%|██████████████████████████████████████████▏                                                                                                                                    | 190/788 [00:12<00:37, 16.16it/s]

RAPS scores:

==================================================
Description 187:
  Our company operates a network of fishing charters that provide recreational fishing experiences for enthusiasts. We offer guided trips in both coastal and freshwater environments, catering to various skill levels and preferences. Our experienced captains share their knowledge of local fishing hotspots and techniques, ensuring a memorable and successful outing. We also emphasize conservation by educating our clients on sustainable fishing practices and encouraging catch-and-release methods for certain species.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 3.157868396304855e-05, 'A': 0.9996477441648364, 'F': 0.00014696799129870617, 'B': 0.00013840906820084795, 'J': 3.5300091700974916e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00035225583516362846}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 188:
  Our company focuses on the sustainable gathering of mosses and lichens from pristine environments, which are increasingly sought after for decorative and functional uses. We employ skilled gatherers who are trained to identify and collect these natural materials without damaging their habitats. The collected mosses and lichens are then processed for use in floral arrangements, crafts, and even as natural insulation materials. By promoting the use of these unique products, we aim to educate consumers about the ecological benefits of mosses and lichens, encouraging a greater appreciation for these often-overlooked resources.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0018039076936993302, 'A': 0.0022625927156879415, 'F': 0.0009512333653313145, 'B': 0.9947711509270478, 'J': 0.0002111152982334351}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00522884907295218}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 189:
  As a prominent player in the hard coal mining industry, we leverage cutting-edge technologies to enhance our extraction and processing capabilities. Our operations include both surface and underground mining, allowing us to access a wide range of coal deposits. We employ advanced cleaning and grading techniques to ensure that our coal products are of superior quality, catering to the needs of various industrial clients. Our focus on innovation and efficiency drives our commitment to delivering value while adhering to strict environmental and safety standards.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.491069034985264e-05, 'A': 3.4368376972568016e-05, 'F': 1.2357033784174535e-05, 'B': 0.9998911956702827, 'J': 7.168228610669746e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957157434723, 6: 1.3287220954995867e-06, 7: 2.9555344323362868e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997527063974829, 5.2: 0.002472936025170941}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 190:
  Our business focuses on the sustainable gathering of balsams, particularly from species known for their aromatic properties. We work with local harvesters to collect these natural resins, which are then processed for use in perfumes, incense, and therapeutic products. Our commitment to sustainability ensures that we only harvest what is necessary, allowing the trees to thrive and continue producing. We also engage in community outreach to educate consumers about the benefits of using natural balsams over synthetic fragrances, promoting a healthier lifestyle and environmental responsibility.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.033527625971428936, 'A': 0.0491873680989604, 'F': 0.015855742892544163, 'B': 0.8985910151494019, 'J': 0.0028382478876645663}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10140898485059813}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 24%|██████████████████████████████████████████▊                                                                                                                                    | 193/788 [00:12<00:33, 17.64it/s]

RAPS scores:

==================================================
Description 191:
  Our company is dedicated to the efficient mining and processing of hard coal, employing both underground and surface techniques to access valuable deposits. We utilize advanced technologies for cleaning and grading coal, ensuring that our products meet the highest quality standards. Our logistics team is focused on optimizing transport solutions, enhancing the overall efficiency of our operations. By prioritizing sustainability and innovation, we aim to create significant value for our customers while contributing positively to the energy landscape.1. Our company specializes in the extraction and processing of hard coal, utilizing both underground and surface mining techniques. We employ advanced technologies to enhance the efficiency of our operations, ensuring minimal environmental impact while maximizing yield. Our facilities are equipped with state-of-the-art machinery for cleaning, sizing, and pulverizing coal, which allows us to produce high-quality products tailored to meet the specific needs of our customers. By investing in innovative methods and sustainable practices, we aim to streamline transportation and storage processes, ultimately delivering superior value to our clients in the energy sector.
True: section=B, division=5, class=5.1
Section set: []
Section probs: {'C': 5.565273370393317e-05, 'A': 3.4211853113285576e-05, 'F': 1.23798410545371e-05, 'B': 0.9998905413494749, 'J': 7.214222653293335e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010945865052514048}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 192:
  Our company is engaged in the cultivation of fiber crops, including cotton and flax, which are essential for the textile and manufacturing industries. We implement sustainable farming practices that prioritize soil health and biodiversity, employing crop rotation and organic pest control methods. Our fiber is processed into high-quality textiles and materials, which are then supplied to clothing manufacturers and home goods producers. By investing in research and development, we are exploring new fiber technologies that enhance durability and reduce environmental impact. Our partnerships with local farmers support fair trade practices and ensure a stable supply chain.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.08413542302127036, 'A': 0.010281425627132388, 'F': 0.009117653723926707, 'B': 0.8943518095200413, 'J': 0.0021136881076291142}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10564819047995866}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 193:
  Our company is dedicated to the production of roundwood for various manufacturing applications, including furniture and construction materials. We utilize advanced logging technology to ensure precision in harvesting while maintaining the ecological balance of our forests. Our commitment to sustainability extends to our supply chain, where we prioritize partnerships with suppliers who share our values. By focusing on quality and responsible sourcing, we aim to deliver exceptional products that meet the evolving needs of our customers while preserving forest ecosystems.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997634068380205, 'A': 1.371624305265623e-05, 'F': 1.624734436216724e-05, 'B': 7.618600173781556e-05, 'J': 0.00013044357282691258}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00023659316197954805}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 194:
  Our company specializes in the collection and processing of cork, focusing on sustainable practices that support both the environment and local economies. We work directly with cork oak farmers to ensure that our sourcing methods do not harm the trees, allowing them to continue producing cork for generations. Our products range from traditional cork stoppers to innovative cork-based materials for construction and design. By highlighting the ecological benefits of cork, we appeal to environmentally conscious consumers and businesses looking for sustainable alternatives to plastic.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9985874903356015, 'A': 6.874341125541289e-05, 'F': 0.00013146547209111876, 'B': 0.000875257479470563, 'J': 0.00033704330158157675}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0014125096643985424}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 25%|████████████████████████████████████████████▏                                                                                                                                  | 199/788 [00:12<00:30, 19.18it/s]

RAPS scores:

==================================================
Description 195:
  Engaged in the mining of titanium ores, our company harnesses advanced extraction methods to produce high-quality titanium dioxide for various applications, including pigments and aerospace components. We prioritize sustainable practices, employing technologies that reduce waste and energy consumption during the mining and processing phases. Our commitment to innovation drives us to continually explore new methods for enhancing ore recovery and refining processes. Additionally, we collaborate with industry partners to promote the responsible sourcing of titanium and support initiatives that benefit the communities surrounding our operations.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.550588798049311e-05, 'A': 3.411121469784335e-05, 'F': 1.2302867175659532e-05, 'B': 0.9998909588127459, 'J': 7.121217400205397e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4510887970145267e-06, 6: 1.6129373267447282e-06, 7: 0.9999959359738761}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03512821996533609, 7.2: 0.9648717800346639}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 196:
  At our state-of-the-art facility, we focus on the pulverization and compressing of lignite to optimize its use in various applications. Our proprietary technology allows us to produce high-quality lignite pellets that are easier to handle and transport. We have established partnerships with local power plants, providing them with a reliable supply of processed lignite that meets stringent quality standards. Our commitment to sustainable practices is evident in our efforts to reduce waste and improve the efficiency of our production processes, thereby contributing to a greener energy landscape.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9997524971374034, 'A': 1.2521646889652331e-05, 'F': 1.525595039869767e-05, 'B': 7.21322517347063e-05, 'J': 0.00014759301357333796}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002475028625965603}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 197:
  Our business model revolves around the extraction of crude petroleum, with a focus on maximizing yield while maintaining environmental responsibility. We employ advanced drilling technologies, including horizontal drilling and multi-stage fracturing, to enhance our extraction capabilities. Our commitment to sustainability is reflected in our investment in renewable energy projects that complement our core operations. By fostering strong relationships with local stakeholders, we ensure that our extraction activities contribute positively to the communities in which we operate, creating jobs and supporting local economies.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.474929563840508e-05, 'A': 3.509285348307707e-05, 'F': 1.2558319930556267e-05, 'B': 0.9998903270393837, 'J': 7.272491564162273e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010967296061625831}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 198:
  We specialize in the growing of fiber crops, particularly cotton, which is essential for the textile industry. Our farms implement sustainable practices that focus on soil conservation and water management, ensuring the long-term viability of our operations. We actively engage in research to develop pest-resistant cotton varieties, reducing the need for chemical interventions. Through partnerships with textile manufacturers, we promote the use of eco-friendly fibers, positioning our products as a responsible choice for environmentally conscious consumers.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9921718634088591, 'A': 0.0003346756026748527, 'F': 0.000843531971649301, 'B': 0.005800576433407721, 'J': 0.000849352583408886}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0078281365911409}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 26%|████████████████████████████████████████████▊                                                                                                                                  | 202/788 [00:12<00:32, 18.17it/s]

RAPS scores:

==================================================
Description 199:
  Specializing in hard coal mining, we utilize a blend of underground and surface techniques to maximize resource extraction while minimizing environmental impact. Our operations include comprehensive cleaning, sizing, and grading processes to ensure the highest quality of coal products. We employ advanced pulverizing and compressing technologies, which enhance the efficiency of transport and storage. By focusing on innovation and sustainability, we aim to provide our customers with reliable energy solutions that not only meet their needs but also contribute positively to the environment.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4722011128256935e-05, 'A': 3.45659697005223e-05, 'F': 1.2405730852375285e-05, 'B': 0.9998910976116945, 'J': 7.208676624397858e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957242706489, 6: 1.338723939641719e-06, 7: 2.9370054114368706e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975277120158377, 5.2: 0.0024722879841622618}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 200:
  Our company specializes in the propagation of native plants, promoting biodiversity and ecological restoration. We cultivate a wide range of species that are well-suited to local environments, providing essential habitats for wildlife. Our plants are grown using sustainable practices, ensuring minimal impact on the ecosystem. We collaborate with conservation organizations and landowners to support rewilding efforts, helping to restore natural landscapes and promote ecological health in our communities.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0011371225230963247, 'A': 0.7329328113949475, 'F': 0.26292477728430025, 'B': 0.0016361194415757468, 'J': 0.001369169356080401}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2670671886050525}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 201:
  Our operations focus on the growing of oleaginous fruits, particularly olives, which are harvested for both oil production and table consumption. We utilize traditional cultivation methods alongside modern agricultural practices to ensure the highest quality olives. Our cold-pressed olive oil is marketed as a premium product, highlighting its health benefits and culinary versatility. We also engage in educational initiatives to promote the nutritional advantages of olive oil, enhancing consumer awareness and driving demand. By maintaining strict quality standards, we position ourselves as a leading supplier in both local and international markets.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.5823228335147931, 'A': 0.004227761495610397, 'F': 0.008718305676926224, 'B': 0.40173023196132807, 'J': 0.003000867351342225}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4176771664852069}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 202:
  In the realm of freshwater aquaculture, we operate extensive facilities dedicated to the cultivation of tilapia and catfish. Our approach combines traditional farming techniques with modern technology, including automated feeding systems and water quality management tools. By implementing integrated pest management practices, we minimize the use of chemicals while maximizing fish health and yield. Our products are marketed directly to local restaurants and grocery chains, emphasizing freshness and sustainability to appeal to health-conscious consumers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0001468799415785066, 'A': 0.9983810614212698, 'F': 0.0005652185511238286, 'B': 0.0007826215014757499, 'J': 0.00012421858455234522}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001618938578730189}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 26%|█████████████████████████████████████████████▋                                                                                                                                 | 206/788 [00:13<00:36, 15.77it/s]

RAPS scores:

==================================================
Description 203:
  Our company is engaged in the extraction of crude petroleum, leveraging innovative hydraulic fracturing techniques to enhance production rates from shale formations. By employing multi-stage fracturing processes, we can unlock significant volumes of oil that were previously deemed unextractable. We also focus on reducing the carbon footprint of our operations by investing in renewable energy sources to power our extraction sites. Our commitment to technological advancement and sustainability positions us as a leader in the crude oil sector, allowing us to meet the growing global demand for energy while maintaining responsible environmental stewardship.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.5104397423560755e-05, 'A': 3.455054168871419e-05, 'F': 1.2390967176318355e-05, 'B': 0.9998907438932861, 'J': 7.210200425314094e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7620238304318283e-06, 6: 0.9999964356115765, 7: 1.80236459311903e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.002054142359011951, 6.1: 0.997945857640988}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 204:
  Engaged in the raising of other livestock, our farm focuses on niche markets that include exotic and rare animal breeds. We prioritize ethical breeding practices that enhance genetic diversity and promote animal welfare. Our facilities are designed to accommodate the specific needs of each breed, ensuring their health and well-being. We also participate in educational programs that raise awareness about the importance of biodiversity in agriculture. By offering unique animals to enthusiasts and breeders, we contribute to preserving rare breeds while fostering a community of responsible animal husbandry.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 7.621502965983329e-05, 'A': 0.9989844529232881, 'F': 0.00048447041124756565, 'B': 0.0003807047634284143, 'J': 7.415687237596349e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0010155470767119201}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 205:
  In the realm of mining non-ferrous metal ores, our focus is on the extraction and processing of tin and tungsten. We leverage advanced mining technologies to ensure efficient operations while maintaining high safety standards. Our processing plants utilize innovative techniques to produce high-grade concentrates that meet the demands of the electronics and aerospace industries. We also invest in ongoing research to develop more sustainable mining practices, aiming to reduce our environmental impact and enhance the value we deliver to our stakeholders.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5349863928294526e-05, 'A': 3.42172874651327e-05, 'F': 1.2343580002187317e-05, 'B': 0.9998909436695695, 'J': 7.145599034803237e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.471307911358217e-06, 6: 1.5852173637124778e-06, 7: 0.999995943474725}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03509165556585607, 7.2: 0.9649083444341439}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 26%|██████████████████████████████████████████████▏                                                                                                                                | 208/788 [00:13<00:39, 14.86it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 206:
  Our business is centered on the extraction of natural gas, where we utilize advanced drilling techniques to optimize resource recovery. We focus on the draining and separation of liquid hydrocarbon fractions, which not only boosts our production efficiency but also enhances our product offerings. Our commitment to environmental responsibility is reflected in our gas desulphurization processes, which help us meet regulatory requirements while providing cleaner energy alternatives. Through strategic investments in technology and infrastructure, we aim to strengthen our position in the market and contribute to a sustainable energy future.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.483875687462041e-05, 'A': 3.460523012404709e-05, 'F': 1.2437440705999544e-05, 'B': 0.9998909152435406, 'J': 7.203328754556685e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7736677591324987e-06, 6: 0.9999964147560122, 7: 1.8115762286101533e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979684807869258, 6.1: 0.0020315192130742643}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 207:
  Our enterprise is engaged in the cultivation of tobacco, focusing on high-quality leaf production for the premium market. We implement rigorous quality control measures throughout the growing and harvesting processes to ensure that our products meet the highest standards. By utilizing traditional curing methods combined with modern agricultural practices, we create a unique flavor profile that appeals to discerning consumers. Additionally, we are committed to responsible tobacco farming, investing in community health initiatives and sustainable practices that promote the well-being of our workers and the surrounding environment.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9930488980563789, 'A': 0.0002600111675952384, 'F': 0.00046486657142275355, 'B': 0.0056056674537297195, 'J': 0.0006205567508736713}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006951101943621141}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 208:
  Our enterprise is involved in the raising of horses, catering to both recreational and competitive markets. We provide comprehensive training programs and care services for horses, ensuring they are well-prepared for various disciplines such as dressage, show jumping, and endurance riding. Our facility includes an equestrian center with riding arenas and stables equipped with modern amenities. By offering boarding services and hosting events, we create a vibrant community for horse enthusiasts while generating additional revenue streams.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0009693414044888451, 'A': 0.8683411369381481, 'F': 0.12621168023837367, 'B': 0.003348462738654536, 'J': 0.001129378680334845}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.13165886306185193}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 209:
  We are involved in the manufacture of tobacco products, sourcing high-quality tobacco leaves from our own farms and trusted growers. Our cultivation practices emphasize sustainability and quality, ensuring that our products meet the highest standards. We utilize advanced processing techniques to create a range of tobacco products, including cigars and loose-leaf tobacco, catering to various consumer preferences. Our commitment to responsible marketing and compliance with regulations underscores our dedication to ethical practices in the industry. By engaging with our customers and understanding their needs, we strive to innovate and enhance our product offerings continuously.1. Our company specializes in the cultivation of premium grapes, focusing on both table and wine varieties. We employ sustainable farming practices that enhance soil health and promote biodiversity. Our vineyards are meticulously managed to ensure optimal grape quality, which is crucial for our partnerships with local wineries. We also invest in innovative irrigation technologies that conserve water while maximizing yield. By offering a range of organic and conventionally grown grapes, we cater to diverse market demands, ensuring our products meet the highest standards of quality and taste.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9997741084691135, 'A': 1.231569446429043e-05, 'F': 1.4946533019016161e-05, 'B': 6.682538495965177e-05, 'J': 0.00013180391844367783}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002258915308864795}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 27%|███████████████████████████████████████████████▎                                                                                                                               | 213/788 [00:13<00:37, 15.16it/s]

RAPS scores:

==================================================
Description 210:
  We are engaged in the cultivation of a diverse range of other perennial crops, focusing on innovative agricultural practices to optimize growth and sustainability. Our operations include the production of various nuts and specialty fruits, which are marketed to both local and international markets. We emphasize quality control throughout our supply chain, ensuring that our products meet the highest standards. Additionally, we invest in research and development to explore new crop varieties and farming techniques that enhance resilience to climate change. Our commitment to sustainability and quality positions us as a forward-thinking leader in the agricultural sector.1. Our company specializes in the cultivation of premium grapes, focusing on both table and wine varieties. We employ sustainable farming practices to enhance soil health and biodiversity, ensuring the production of high-quality fruit. Our vineyards are meticulously managed to optimize yield and flavor profiles, which are critical for our winemaking partners. In addition to grape growing, we invest in advanced irrigation systems and climate monitoring technologies to adapt to changing weather patterns. By prioritizing quality and sustainability, we create value not only for our consumers but also for the local ecosystem and economy.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9212331415765106, 'A': 0.001963570969092844, 'F': 0.00472049527115985, 'B': 0.06974602270064792, 'J': 0.002336769482588706}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0787668584234894}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 211:
  Our company is dedicated to the mining of iron ores, focusing on both open-pit and underground operations. We utilize innovative exploration techniques to identify new ore bodies, ensuring a sustainable supply chain for our production facilities. Our beneficiation processes are designed to improve the iron content of the ore while reducing impurities, which is vital for our customers in the steel industry. We also provide extensive technical consultancy services to help our clients optimize their production processes and improve their overall efficiency, thereby enhancing their competitiveness in the market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.540924331899074e-05, 'A': 3.414285500034811e-05, 'F': 1.2306907422274672e-05, 'B': 0.9998910012972017, 'J': 7.139697056764413e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4803132008879017e-06, 6: 1.5764341495880443e-06, 7: 0.9999959432526495}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677983766548881, 7.2: 0.0322016233451119}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 212:
  Our aquaculture operations focus on the farming of amphibians, specifically frogs, which are increasingly sought after for culinary uses in various cuisines. We maintain controlled environments that simulate natural habitats, allowing for optimal growth and reproduction. Our farming practices include regular health checks and a balanced diet to ensure high-quality yields. Additionally, we are committed to ethical farming standards, ensuring humane treatment of our stock throughout their lifecycle. By establishing partnerships with local chefs and restaurants, we promote the culinary potential of our products while supporting sustainable food practices.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00037073318181375767, 'A': 0.9939940358660699, 'F': 0.001127173062294578, 'B': 0.004244644755941489, 'J': 0.0002634131338802089}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006005964133930064}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 213:
  We focus on the collection of natural resins and balsams, which are essential ingredients in the production of perfumes, cosmetics, and incense. Our harvesting techniques prioritize sustainability, ensuring that we do not deplete natural resources. After collection, we refine these materials in our facility to produce high-quality extracts that meet the stringent standards of our clients in the fragrance and beauty industries. Our dedication to quality and sustainability has positioned us as a trusted supplier in a competitive market.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9997369805201426, 'A': 1.5178646566359994e-05, 'F': 1.8718984413321356e-05, 'B': 9.296571992240495e-05, 'J': 0.0001361561289552898}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00026301947985740703}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 27%|███████████████████████████████████████████████▉                                                                                                                               | 216/788 [00:13<00:39, 14.44it/s]

RAPS scores:

==================================================
Description 214:
  Engaged in the extraction of crude petroleum, our company employs a strategic approach that combines advanced drilling technologies with a focus on sustainability. We utilize data-driven insights to optimize drilling operations and enhance recovery from existing wells. Our commitment to reducing environmental impact is evident in our initiatives to minimize water usage and emissions. We collaborate with industry partners to develop innovative solutions that address the challenges of extraction while ensuring compliance with regulatory standards. By prioritizing safety and efficiency, we are positioned to meet the energy needs of the future while maintaining a responsible operational footprint.1. Our company specializes in the extraction of crude petroleum, utilizing advanced drilling techniques and state-of-the-art technology to maximize efficiency and minimize environmental impact. We operate multiple offshore and onshore drilling sites, employing a skilled workforce trained in the latest safety protocols. Our commitment to sustainability drives us to invest in innovative methods such as enhanced oil recovery, which allows us to extract more resources from existing wells while reducing our carbon footprint. By leveraging data analytics and real-time monitoring systems, we ensure optimal production rates and operational reliability, ultimately delivering high-quality crude oil to meet global energy demands.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.50684549711506e-05, 'A': 3.471941241834689e-05, 'F': 1.2497368694525472e-05, 'B': 0.9998904640770359, 'J': 7.250686880171824e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001095359229641435}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 215:
  In the realm of iron ore mining, our company stands out for its commitment to technological innovation and sustainability. We operate several mining sites where we extract high-quality iron ores using environmentally friendly methods. Our beneficiation processes are designed to maximize ore recovery and purity, employing advanced techniques such as gravity separation and hydrocycloning. Furthermore, we specialize in the agglomeration of iron ores into pellets, which are produced in our state-of-the-art facilities. These pellets are tailored to meet the specific requirements of our steel manufacturing partners, ensuring a reliable supply of high-performance raw materials.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.537640031180161e-05, 'A': 3.4052285588982454e-05, 'F': 1.229280394121619e-05, 'B': 0.9998911565901106, 'J': 7.121920047447675e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4910065358504436e-06, 6: 1.573403184219086e-06, 7: 0.9999959355902799}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677913134645076, 7.2: 0.03220868653549231}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 216:
  Our company specializes in the aquaculture of amphibians, particularly frogs, which are raised for culinary markets. We implement biosecure farming practices to ensure the health of our stock while maintaining high standards of animal welfare. Our operations include controlled breeding programs that enhance growth rates and disease resistance. We focus on sustainable practices, such as water conservation and waste recycling, to minimize our environmental impact. By collaborating with chefs and food distributors, we promote the culinary versatility of frog legs, positioning our products as a delicacy in gourmet cuisine while supporting sustainable farming initiatives.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0013934205250723227, 'A': 0.9770287271932906, 'F': 0.005055654975145411, 'B': 0.015756504812135117, 'J': 0.0007656924943565396}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.02297127280670941}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 28%|████████████████████████████████████████████████▋                                                                                                                              | 219/788 [00:14<00:39, 14.45it/s]

RAPS scores:

==================================================
Description 217:
  Specializing in the farming of crocodiles, our business emphasizes ethical practices and habitat conservation. We operate licensed farms that adhere to strict regulations regarding animal welfare and environmental impact. Our operations include breeding, rearing, and harvesting, with a focus on producing high-quality leather and meat products. We engage in conservation efforts to protect wild populations and educate the public about the importance of sustainable practices. Our products are marketed to luxury brands and gourmet food markets, showcasing the unique qualities of crocodile products while promoting responsible aquaculture.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of various fish species, including salmon and sea bass. Utilizing advanced recirculating aquaculture systems, we ensure optimal growth conditions while minimizing environmental impact. Our operations include hatchery management, where we carefully monitor water quality and nutrition to produce healthy juvenile fish. Once harvested, our products are processed and packaged for distribution to both local and international markets, emphasizing freshness and quality. We also engage in research and development to enhance breeding techniques, aiming to improve yield and resilience against diseases.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.01464311513167067, 'A': 0.5906326727565158, 'F': 0.03249302119279734, 'B': 0.3583800863907394, 'J': 0.0038511045282767957}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.40936732724348424}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 218:
  Our organization is at the forefront of mining rare earth elements, crucial for modern technologies. We utilize cutting-edge extraction methods that maximize yield while minimizing environmental disruption. Our research and experimental development team works tirelessly to innovate new techniques for separating these valuable ores from surrounding materials. By partnering with academic institutions, we aim to advance our understanding of these minerals and their applications, ultimately driving growth in sectors such as electronics, renewable energy, and defense.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.490242019366094e-05, 'A': 3.450499484384175e-05, 'F': 1.2405602649865365e-05, 'B': 0.9998910154301434, 'J': 7.171552169396311e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.449858943644485e-06, 6: 1.6269634114375728e-06, 7: 0.9999959231776451}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03520548753228323, 7.2: 0.9647945124677166}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 219:
  We are committed to the cultivation of specialty crops, focusing on unique non-perennial varieties that cater to niche markets. Our operations include the growing of herbs and exotic vegetables, which are increasingly popular among chefs and health-conscious consumers. We utilize hydroponic and aquaponic systems to maximize yield while minimizing resource usage. Our products are marketed directly to restaurants and specialty grocery stores, ensuring that our customers receive the freshest produce available. We also engage in educational initiatives, teaching local communities about the benefits of diverse diets and sustainable agricultural practices, thereby fostering a culture of health and sustainability.1. Our company specializes in the cultivation of a diverse range of non-perennial crops, focusing primarily on cereals and oil seeds. By employing advanced agricultural techniques and precision farming technologies, we maximize yield while ensuring sustainable practices. Our state-of-the-art irrigation systems and soil management strategies enhance crop quality and reduce environmental impact. We also invest in research and development to improve seed varieties, which leads to higher resistance against pests and diseases. Our products are distributed to local markets and international buyers, contributing to food security and economic growth in the regions we operate.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.10219012814819928, 'A': 0.05833450008875296, 'F': 0.04260687486709369, 'B': 0.7913013091206623, 'J': 0.0055671877752915926}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.20869869087933768}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 28%|█████████████████████████████████████████████████▌                                                                                                                             | 223/788 [00:14<00:37, 14.88it/s]

RAPS scores:

==================================================
Description 220:
  Our company is dedicated to the collection of molluscs along the intertidal shoreline, where we employ traditional hand-gathering methods alongside modern tools. We focus on species such as clams and oysters, which are harvested at optimal times to ensure peak flavor and quality. Our operations include rigorous monitoring of tidal patterns and environmental conditions to maximize our yield while adhering to sustainable quotas. The harvested shellfish are then processed in our facility, where they are packaged and distributed to gourmet restaurants and seafood markets, emphasizing freshness and local sourcing.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.13769664128623688, 'A': 0.0502389288270624, 'F': 0.23222923177614183, 'B': 0.5681995548147789, 'J': 0.011635643295780065}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4318004451852211}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 221:
  Our business is dedicated to the mining of non-ferrous metal ores, particularly focusing on the extraction of nickel and its alloys. We utilize both surface and underground mining methods tailored to the geological characteristics of our sites. Our processing plants employ hydrometallurgical techniques to produce high-purity nickel products that are essential for stainless steel and battery manufacturing. We are committed to continuous improvement through research and development, aiming to enhance our operational efficiency and reduce environmental impacts associated with nickel mining.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.55555110695408e-05, 'A': 3.420412829620377e-05, 'F': 1.2343645213401338e-05, 'B': 0.9998907430567473, 'J': 7.153658673468947e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.476076819351105e-06, 6: 1.5824147312139936e-06, 7: 0.9999959415084495}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03507607415093786, 7.2: 0.9649239258490621}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 222:
  Our business is dedicated to the propagation of a wide range of ornamental plants, including flowering annuals and perennials. We utilize state-of-the-art greenhouse technology to create optimal growing conditions, allowing us to produce vibrant and healthy plants. We supply garden centers and landscapers with our products, helping to beautify homes and public spaces. Our commitment to sustainability is reflected in our use of eco-friendly practices and materials, ensuring that our plants contribute positively to the environment.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0014222426520647358, 'A': 0.07712342092159048, 'F': 0.9186510771016188, 'B': 0.0014413383526777198, 'J': 0.001361920972048212}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08134892289838125}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 223:
  Our business is centered on the raising of other animals, including alpacas and llamas, primarily for fiber production. We prioritize humane treatment and environmental sustainability in our farming practices. Our animals are raised in spacious pastures, allowing them to thrive while producing high-quality fleece. We process the fiber into yarn and textiles, collaborating with local artisans to create unique, handcrafted products. By participating in craft fairs and online marketplaces, we connect with consumers who appreciate the artistry and sustainability of our offerings, fostering a community that values ethical fashion and home goods.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0006479582852191695, 'A': 0.9888272728690995, 'F': 0.00435993616441034, 'B': 0.005725682418185125, 'J': 0.000439150263085821}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01117272713090045}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 29%|██████████████████████████████████████████████████▏                                                                                                                            | 226/788 [00:14<00:37, 14.92it/s]

RAPS scores:

==================================================
Description 224:
  Engaged in the growing of other non-perennial crops, our company focuses on niche markets that require specialized agricultural practices. We cultivate a range of unique crops, such as medicinal herbs and specialty vegetables, catering to the growing demand for organic and health-focused products. Our operations are guided by sustainable farming principles, ensuring minimal environmental impact while maximizing crop diversity. We actively participate in farmer cooperatives to share knowledge and resources, enhancing the overall productivity and sustainability of our agricultural community.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.012133702228888312, 'A': 0.7780733841289147, 'F': 0.03815595804362795, 'B': 0.16811953166439722, 'J': 0.0035174239341718705}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2219266158710853}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 225:
  Our company is committed to the responsible mining of hard coal, utilizing advanced technologies to improve extraction and processing efficiency. We specialize in the liquefaction of coal, which allows us to access previously unreachable reserves while reducing environmental impact. Our processing plants are equipped with high-capacity machinery for cleaning, sizing, and pulverizing coal, ensuring that we deliver a consistent product that meets the diverse needs of our clients. We also engage in continuous improvement initiatives, focusing on innovation in our mining techniques and processing methods to enhance the overall quality and value of our coal offerings.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5204330089117344e-05, 'A': 3.421005374317798e-05, 'F': 1.2316912591318686e-05, 'B': 0.9998911123145415, 'J': 7.1563890348749245e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957295981089, 6: 1.3321021416816023e-06, 7: 2.9382997495494666e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975269445803735, 5.2: 0.0024730554196265783}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 226:
  Our company operates a comprehensive warehousing and storage system designed specifically for lignite products. With strategically located facilities, we ensure that our clients have easy access to quality lignite whenever needed. Our storage solutions are equipped with advanced monitoring systems to maintain optimal conditions, preventing degradation and ensuring product integrity. This capability allows us to provide just-in-time delivery services, enhancing our customers' operational efficiency and reducing their inventory costs. We pride ourselves on our ability to adapt to fluctuating market demands while maintaining high standards of service.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9995781147068248, 'A': 1.9636777100800107e-05, 'F': 2.3631747797803946e-05, 'B': 0.0001923889403746283, 'J': 0.00018622782790189316}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00042188529317521706}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 227:
  Our company is at the forefront of iron ore mining, utilizing innovative technologies to streamline our extraction processes. We focus on the production of high-grade iron ore that meets the rigorous specifications of the global steel market. Our operations include not only mining but also the agglomeration of iron ores, where we produce pellets that enhance the efficiency of steel production. By continuously investing in research and development, we aim to improve our processes and reduce waste, contributing to a more sustainable mining industry.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.601073326364138e-05, 'A': 3.395904339090276e-05, 'F': 1.2270701544586205e-05, 'B': 0.9998906501865819, 'J': 7.109335219050714e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010934981341814698}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 29%|███████████████████████████████████████████████████▌                                                                                                                           | 232/788 [00:14<00:29, 18.54it/s]

RAPS scores:

==================================================
Description 228:
  Our operations focus on the cultivation of legumes, including lentils and chickpeas, which are gaining popularity as a protein source in plant-based diets. We employ sustainable farming practices that enhance soil fertility and promote biodiversity, ensuring the long-term viability of our crops. Our products are processed and packaged for both retail and bulk distribution, meeting the needs of health-conscious consumers and food manufacturers alike. By investing in research and development, we aim to improve crop resilience and expand our offerings in the growing market for plant-based foods.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.07650248753959366, 'A': 0.01698913190406779, 'F': 0.01721207690409224, 'B': 0.8865426241136004, 'J': 0.0027536795386458985}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11345737588639959}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 229:
  We engage in extensive research and development to explore new methods of lignite extraction and processing, focusing on sustainability and efficiency. Our team of engineers and scientists work collaboratively to identify innovative solutions that reduce the environmental impact of mining activities. By experimenting with alternative extraction techniques and refining our processing methods, we aim to enhance the quality of our lignite while minimizing resource consumption. This proactive approach positions us as a leader in the industry, committed to responsible resource management.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.5104050048459856e-05, 'A': 3.4748406860374926e-05, 'F': 1.2510577503734735e-05, 'B': 0.9998904004302955, 'J': 7.236535291665119e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010959956970446605}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 230:
  Engaged in the mining of iron and other non-ferrous metal ores, our company focuses on producing high-quality raw materials for the steel and construction industries. We utilize innovative extraction and processing techniques that enhance ore recovery and reduce waste. Our commitment to sustainability is reflected in our investments in renewable energy and efforts to minimize our environmental impact. By developing strong partnerships with our customers, we tailor our products to meet their specific needs, ensuring that we remain a reliable supplier in the competitive non-ferrous metals market.1. Our company specializes in the extraction and processing of uranium and thorium ores, utilizing advanced mining techniques to ensure efficiency and safety. We employ state-of-the-art technologies, including automated drilling systems and real-time monitoring tools, to optimize ore recovery while minimizing environmental impact. Our commitment to sustainability is reflected in our reclamation practices, which restore mined lands to their natural state. Additionally, we collaborate with research institutions to develop innovative methods for ore processing, enhancing yield and reducing waste. This focus on innovation not only drives our operational success but also positions us as a leader in the responsible mining of critical resources.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.565440591633156e-05, 'A': 3.424781488939924e-05, 'F': 1.236477361475135e-05, 'B': 0.9998905474207294, 'J': 7.185584850080678e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010945257927064134}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 231:
  We are committed to the cultivation of fibre crops, including cotton and flax, which are essential for the textile industry. Our farming practices prioritize sustainability, utilizing organic methods and crop rotation to maintain soil health. We invest in research to develop pest-resistant varieties that require fewer chemical inputs, thereby reducing our environmental footprint. Our processing facilities are equipped with advanced technology to ensure that the fibre is of the highest quality, suitable for various applications. By collaborating with fashion brands focused on sustainability, we aim to promote eco-friendly textiles and contribute to a more responsible industry.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9304232400110677, 'A': 0.0013483683384229077, 'F': 0.0028001819797110823, 'B': 0.06373433250849597, 'J': 0.0016938771623022288}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.06957675998893231}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 232:
  Engaging in the cultivation of diverse non-perennial crops, our company focuses on innovative agricultural practices that enhance productivity and sustainability. We grow a variety of crops, including root vegetables and tubers, utilizing crop rotation and cover cropping to maintain soil health. Our state-of-the-art facilities allow us to process and package our products for both local and export markets. We also invest in community outreach programs to educate local farmers on best practices, fostering a collaborative approach to agriculture that benefits the entire region.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.016005239795015485, 'A': 0.7443468944287462, 'F': 0.05013857641566526, 'B': 0.18524623936228068, 'J': 0.004263049998292302}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.25565310557125376}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 30%|████████████████████████████████████████████████████▊                                                                                                                          | 238/788 [00:15<00:27, 20.16it/s]

RAPS scores:

==================================================
Description 233:
  Our organization is a leading grower of citrus fruits, including oranges, lemons, and limes. We implement innovative agricultural techniques, such as integrated pest management and soil conservation practices, to maximize yield and fruit quality. Our citrus orchards are equipped with advanced monitoring systems that track growth conditions and fruit development, enabling us to make data-driven decisions. We are committed to sustainability and have adopted practices that reduce water usage and chemical inputs. The citrus fruits we produce are sold fresh and also processed into juices and concentrates, catering to both local and global markets.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.20713736627667922, 'A': 0.020304962611669572, 'F': 0.028501639945170472, 'B': 0.7393278261426199, 'J': 0.004728205023860761}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.26067217385738006}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 234:
  Our business is centered around the harvesting of wild nuts, particularly acorns and horse chestnuts, which are gaining popularity for their nutritional benefits and culinary versatility. We collaborate with local communities to educate them on sustainable harvesting methods, ensuring that our practices do not deplete natural resources. The nuts are processed into flour and oils, which we supply to health-conscious consumers and food manufacturers looking for natural ingredients. By promoting the use of wild nuts, we aim to create a niche market that values traditional food sources.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0003840066122337742, 'A': 0.993527916497578, 'F': 0.0011319196012972582, 'B': 0.004689815417876071, 'J': 0.0002663418710148084}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00647208350242201}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 235:
  Our warehousing and storage solutions are designed to accommodate the unique challenges of lignite handling. We operate large-scale storage facilities that maintain optimal conditions for lignite preservation, preventing moisture absorption and degradation. Our logistics team ensures that the lignite is stored safely and efficiently, utilizing automated systems for inventory management. This allows us to respond quickly to market demands and ensures a consistent supply for our clients in the energy sector.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9873873537262358, 'A': 0.00016068577041153048, 'F': 0.00015437945513486768, 'B': 0.011804587037170142, 'J': 0.0004929940110479695}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012612646273764239}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 236:
  We are engaged in the comprehensive management of forest resources, with a strong emphasis on sustainable practices that benefit both the environment and local economies. Our activities include the operation of forest tree nurseries, where we produce a variety of seedlings for reforestation and timber production. We also conduct thinning operations that enhance forest health and productivity. By collaborating with landowners and conservation groups, we promote best practices in forestry that support biodiversity, carbon sequestration, and long-term forest resilience.1. Our company specializes in the sustainable management of forest resources, focusing on the cultivation and maintenance of timber stands. We engage in activities such as planting, thinning, and replanting to ensure healthy growth and optimal yield of timber. Our team employs advanced silvicultural techniques to enhance forest productivity while maintaining ecological balance. Additionally, we operate tree nurseries that supply high-quality seedlings for both commercial forestry and conservation projects. By integrating modern technology with traditional forestry practices, we aim to create a sustainable supply chain that supports both the environment and local economies.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.392153078137398e-05, 'A': 0.999455781230462, 'F': 0.00028988479670654353, 'B': 0.00016354913734013794, 'J': 4.686330471009659e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0005442187695380296}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 237:
  We are dedicated to the restoration and management of restocked water bodies, where we engage in the fishing of species that have been reintroduced to local ecosystems. Our team works closely with environmental agencies to monitor fish populations and ensure that restocking efforts are successful. By providing recreational fishing opportunities in these areas, we not only enhance biodiversity but also promote eco-tourism. Our activities support local economies while fostering a greater appreciation for aquatic conservation among the public.1. Our company specializes in marine fishing, utilizing advanced trawling techniques to sustainably harvest a variety of fish species from the open ocean. We operate a fleet of state-of-the-art fishing vessels equipped with sonar technology to locate schools of fish efficiently. Our commitment to sustainable practices ensures that we adhere to strict quotas and utilize selective gear to minimize bycatch. In addition to fresh fish, we also process and package our catch for distribution to local markets and restaurants, emphasizing quality and freshness. Our operations not only contribute to the local economy but also support responsible fishing practices to preserve marine ecosystems.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 4.158048479975012e-05, 'A': 0.9995771764443919, 'F': 0.00017505699907688818, 'B': 0.00016291699306046135, 'J': 4.32690786708663e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00042282355560807616}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 31%|█████████████████████████████████████████████████████▌                                                                                                                         | 241/788 [00:15<00:29, 18.37it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 238:
  Our company operates in the natural gas extraction sector, focusing on the production of crude gaseous hydrocarbons. We utilize advanced techniques for hydraulic fracturing and horizontal drilling, which enable us to access previously untapped reserves. Our facilities are designed for the efficient draining and separation of liquid hydrocarbon fractions, ensuring that we maximize output while adhering to environmental standards. Our gas desulphurization efforts are integral to our operations, allowing us to produce cleaner energy and support global sustainability goals.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.4653598640613995e-05, 'A': 3.469874267179128e-05, 'F': 1.2427479275386093e-05, 'B': 0.9998909963064011, 'J': 7.223873011055501e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7623801195713098e-06, 6: 0.9999964407112873, 7: 1.7969085930542318e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979745293502041, 6.1: 0.0020254706497959524}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 239:
  With a focus on natural gas extraction, our company utilizes innovative drilling and processing technologies to maximize efficiency and yield. We specialize in the draining and separation of liquid hydrocarbon fractions, ensuring that our products meet the highest industry standards. Our commitment to sustainability is reflected in our gas desulphurization efforts, which aim to minimize emissions and promote cleaner energy alternatives. By continuously improving our operational practices and investing in research, we are well-positioned to meet the increasing demand for natural gas in a responsible manner.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.481543889762838e-05, 'A': 3.493012249936432e-05, 'F': 1.2517198944400849e-05, 'B': 0.9998904769693677, 'J': 7.2602702908874536e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010952303063227475}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 240:
  In our crude petroleum extraction operations, we prioritize safety and efficiency through the use of advanced monitoring systems that track drilling performance in real-time. Our teams are trained to respond swiftly to any anomalies, ensuring that our operations remain safe and compliant with industry standards. We also engage in regular assessments of our environmental impact, implementing measures to mitigate any potential risks associated with our extraction activities. By fostering a culture of safety and sustainability, we aim to set a benchmark for responsible oil extraction practices.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.497090302287267e-05, 'A': 3.4843994901819266e-05, 'F': 1.2509924617372728e-05, 'B': 0.999890425986024, 'J': 7.249191434022916e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010957401397604372}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 31%|█████████████████████████████████████████████████████▉                                                                                                                         | 243/788 [00:15<00:37, 14.70it/s]

RAPS scores:

==================================================
Description 241:
  We are engaged in the mining of non-ferrous metal ores, focusing on the extraction of magnesium and titanium. Our operations utilize advanced mining techniques to ensure high recovery rates and minimize environmental impact. We process the extracted ores in our state-of-the-art facilities, producing high-quality magnesium and titanium products for various industries, including aerospace and automotive. Our commitment to innovation drives us to continuously improve our processes, ensuring that we meet the evolving needs of our customers while maintaining sustainable practices throughout our operations.1. Our company specializes in the extraction and processing of uranium ores, utilizing state-of-the-art mining techniques to ensure efficiency and safety. We operate several mines equipped with advanced technologies that minimize environmental impact while maximizing yield. Our commitment to sustainable practices is evident in our reclamation efforts, which restore mined areas to their natural state. Additionally, we invest in research to improve ore recovery processes and reduce waste, ensuring that we remain at the forefront of the uranium mining sector. Our products are critical for nuclear energy production, contributing to a cleaner energy future.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.5807115731865615e-05, 'A': 3.407933086853445e-05, 'F': 1.2319373977754094e-05, 'B': 0.999890658732328, 'J': 7.135447093979602e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010934126767203622}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 242:
  ForestFutures is committed to advancing sustainable forestry through innovative practices in timber cultivation. We specialize in the growth of standing timber, coppice, and firewood, utilizing modern silvicultural techniques to maximize yield and ecological benefits. Our tree nurseries play a vital role in our operations, supplying diverse seedlings that support both commercial forestry and habitat restoration efforts. By focusing on responsible management and conservation, we create value for our stakeholders while promoting the health of our forests and surrounding ecosystems.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.2442133706047888e-05, 'A': 0.9997743780168329, 'F': 0.00010246777650026923, 'B': 7.578583783667639e-05, 'J': 2.492623512403762e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00022562198316711246}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 243:
  We focus on the collection of mosses and lichens from pristine environments, which are used in various decorative and functional applications. Our team of foragers is trained to identify sustainable harvesting practices that protect these delicate organisms. After gathering, the mosses and lichens are processed and packaged for use in floral arrangements, crafts, and landscaping projects. Our dedication to sustainability not only preserves these natural resources but also educates our customers about the importance of biodiversity and responsible sourcing.1. Our company specializes in the sustainable gathering of wild berries, focusing on organic and non-GMO varieties. We partner with local foragers to ensure that our harvesting practices are environmentally friendly and support biodiversity. The berries are then processed into a range of products, including jams, jellies, and natural flavorings for the food industry. By emphasizing traceability and quality, we cater to health-conscious consumers and premium food brands, creating a strong market presence while promoting the conservation of wild habitats.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0002420899609650059, 'A': 0.99722417665262, 'F': 0.0006462952618203824, 'B': 0.001701594104112559, 'J': 0.00018584402048202046}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0027758233473800242}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 31%|██████████████████████████████████████████████████████▊                                                                                                                        | 247/788 [00:15<00:42, 12.63it/s]

RAPS scores:

==================================================
Description 244:
  Focusing on offshore fishing, our enterprise utilizes large commercial vessels equipped with advanced navigation and fishing technology to target pelagic species such as tuna and swordfish. We implement sustainable fishing practices, including selective gear and bycatch reduction techniques, to minimize our environmental footprint. Our products are processed on board and flash-frozen to maintain quality, allowing us to supply global markets with premium seafood. We also engage in collaborative research with marine biologists to study fish migration patterns, ensuring our practices align with conservation efforts and contribute to the long-term health of ocean ecosystems.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0008230049268648599, 'A': 0.9710642067328004, 'F': 0.001589426970090716, 'B': 0.02600190135286395, 'J': 0.0005214600173803058}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.02893579326719964}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 245:
  Focusing on the growing of vegetables and melons, this company employs hydroponic farming techniques to produce fresh, nutritious crops year-round. By utilizing controlled environment agriculture, they can optimize growth conditions and reduce water usage significantly. Their product line includes a variety of leafy greens, cucumbers, and melons, which are marketed directly to consumers through local farmers' markets and grocery store partnerships. The company also emphasizes community engagement by offering educational workshops on sustainable gardening practices, fostering a connection between consumers and their food sources.
True: section=A, division=1, class=1.1
Section set: ['A']
Section probs: {'C': 1.0462273438637305e-05, 'A': 0.999909203340137, 'F': 3.975793469455254e-05, 'B': 2.7818949167923665e-05, 'J': 1.2757502562080113e-05}
Division sets: {'A': ['1']}
Division probs: {'A': {1: 0.9981843067777052, 2: 0.0010637577195040885, 3: 0.0007519355027907943}}
Class sets: {'1': ['1.1']}
Class probs: {'1': {1.2: 0.006265871322875706, 1.4: 0.005766769868962241, 1.3: 0.00307692515096894, 1.1: 0.9848904336571931}}
Final output: {'type': 'class_level', 'codes': ['1.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 246:
  We are committed to the raising of horses, offering a range of services that include breeding, training, and boarding. Our facility features spacious stables and expansive paddocks, providing a safe and enriching environment for our horses. We focus on breeding high-performance equines, utilizing advanced genetic selection techniques to enhance desirable traits. Our training programs are tailored to each horse's individual needs, and we host regular events to showcase our horses and connect with the equestrian community. Our emphasis on quality care and training positions us as a leader in the equine industry.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0024305229887940615, 'A': 0.2537267380962228, 'F': 0.7348756314208175, 'B': 0.006816515037527772, 'J': 0.0021505924566377244}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.26512436857918253}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 32%|███████████████████████████████████████████████████████▎                                                                                                                       | 249/788 [00:16<00:47, 11.34it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 247:
  Our operations are centered around the sustainable mining of iron ores, where we prioritize both productivity and environmental stewardship. We utilize automated drilling and blasting techniques to extract ore efficiently while minimizing waste. Our beneficiation facilities are equipped with advanced technologies, including high-intensity magnetic separators and advanced screening systems, which allow us to produce iron concentrates with exceptional purity levels. By collaborating with industry partners, we are also exploring innovative recycling methods to reclaim iron from waste materials, further enhancing our contribution to a circular economy.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.487995129176704e-05, 'A': 3.4247889082246545e-05, 'F': 1.2324920949399595e-05, 'B': 0.999891402375707, 'J': 7.144862969494796e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4691641421514907e-06, 6: 1.5836149362680615e-06, 7: 0.9999959472209217}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677649237953656, 7.2: 0.032235076204634436}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 248:
  Engaged in the hard coal mining sector, we employ a variety of extraction methods, including both surface and underground techniques. Our commitment to quality is evident in our advanced processing capabilities, which include cleaning, grading, and pulverizing coal to meet diverse customer requirements. We have implemented sustainable practices to minimize our environmental footprint, such as utilizing waste materials in our operations and optimizing energy use. Our robust logistics network ensures that our coal products are efficiently transported and stored, providing our clients with reliable access to high-quality resources.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4913569792368704e-05, 'A': 3.4361854611055926e-05, 'F': 1.235830050903835e-05, 'B': 0.9998911808604273, 'J': 7.185414660180816e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957259736123, 6: 1.3287493534871721e-06, 7: 2.9452770340956287e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997529362519824, 5.2: 0.0024706374801759627}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 32%|███████████████████████████████████████████████████████▋                                                                                                                       | 251/788 [00:16<00:45, 11.80it/s]

RAPS scores:

==================================================
Description 249:
  Our company engages in the production of wood-based energy solutions, focusing on the collection and processing of forest residues. We convert these materials into high-efficiency biomass fuels that are used in various applications, from heating residential homes to powering industrial facilities. By prioritizing sustainability, we not only reduce waste but also contribute to a circular economy that values renewable resources and minimizes environmental impact.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.999749074548993, 'A': 1.483032062673032e-05, 'F': 1.7122407153483047e-05, 'B': 8.841462442378117e-05, 'J': 0.00013055809880284234}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00025092545100702246}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 250:
  As a prominent lignite mining company, we focus on the extraction and processing of lignite to meet the growing energy demands. Our operations include both surface and underground mining, employing state-of-the-art technology to maximize efficiency. We prioritize the washing and dehydrating of lignite to improve its quality, making it suitable for various industrial applications. Our dedicated logistics team manages the warehousing and transportation of our products, ensuring timely delivery to power generation facilities. By combining innovative mining practices with robust logistics, we are positioned to be a key player in the energy sector.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.489209298067943e-05, 'A': 3.458888054880452e-05, 'F': 1.2433061384662565e-05, 'B': 0.9998908895663543, 'J': 7.196398731558434e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957385574454, 6: 1.3462520815489829e-06, 7: 2.9151904730094077e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002355270100846372, 5.2: 0.9976447298991536}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 32%|████████████████████████████████████████████████████████▊                                                                                                                      | 256/788 [00:16<00:36, 14.70it/s]

RAPS scores:

==================================================
Description 251:
  Our company specializes in the mining and processing of rare earth elements, which are critical for a variety of high-tech applications. We utilize innovative separation techniques to extract these valuable minerals from complex ores, ensuring high purity levels for our customers. Our commitment to research and development drives us to explore new methods for improving extraction efficiency and reducing environmental impact. By partnering with technology firms, we support advancements in electronics, renewable energy, and defense sectors, positioning ourselves as a key player in the global supply chain for rare earth materials.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5526017684829976e-05, 'A': 3.4172381587583475e-05, 'F': 1.2340482622423974e-05, 'B': 0.9998907981183865, 'J': 7.162999718727807e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4494886412194944e-06, 6: 1.6339286295681166e-06, 7: 0.9999959165827291}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035135234960081585, 7.2: 0.9648647650399185}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 252:
  We engage in the mining of non-ferrous metal ores, with a particular emphasis on rare earth elements that are critical for modern technologies. Our operations are characterized by a commitment to sustainable practices, utilizing water-efficient extraction methods and recycling waste materials. The rare earth metals we extract are essential for the production of high-performance magnets, batteries, and electronic components. By investing in research and development, we continuously seek to improve our extraction processes and reduce environmental impact, ensuring a steady supply of these vital materials for future generations.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.638415536803586e-05, 'A': 3.380105335659799e-05, 'F': 1.2285323475176766e-05, 'B': 0.9998904148371107, 'J': 7.114630689412963e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010958516288928077}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 253:
  Our company specializes in the aquaculture of freshwater species, with a focus on the sustainable farming of trout. We operate in pristine environments, utilizing natural water sources and advanced filtration systems to maintain water quality. Our practices include selective breeding programs to enhance growth rates and disease resistance, ensuring a high-quality product. We are dedicated to minimizing our environmental footprint through responsible feed sourcing and waste management. The trout harvested from our farms are processed and distributed to various markets, where they are celebrated for their freshness and flavor, appealing to health-conscious consumers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0006364203239993577, 'A': 0.9906443871631501, 'F': 0.002630376808250205, 'B': 0.005678359228239421, 'J': 0.0004104564763609925}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.009355612836849936}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 254:
  We are engaged in the comprehensive management of aquaculture operations, providing consulting services to new and existing farms. Our expertise encompasses site selection, system design, and operational optimization, ensuring that our clients can maximize their yield while adhering to sustainable practices. We offer training programs that educate farmers on the latest technologies and methodologies in aquaculture, empowering them to improve their production efficiency. By fostering a collaborative approach, we aim to enhance the overall sustainability and profitability of the aquaculture industry, supporting the growing demand for responsibly sourced aquatic products.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of high-value species such as salmon and shrimp. We utilize advanced recirculating aquaculture systems (RAS) that optimize water quality and minimize environmental impact. Our operations include hatchery management, where we carefully monitor breeding and early life stages, and grow-out facilities that ensure optimal feeding and health management. By implementing innovative feeding techniques and biosecurity measures, we enhance growth rates and reduce disease outbreaks, resulting in a consistent supply of premium seafood products for both domestic and international markets.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00012978942462632138, 'A': 0.9984106628928943, 'F': 0.0007285338642311368, 'B': 0.0006165924179854586, 'J': 0.00011442140026299508}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0015893371071057372}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 255:
  TimberTech Innovations is revolutionizing the forestry sector with our focus on advanced silvicultural practices. We specialize in the cultivation of timber and pulpwood, utilizing precision forestry techniques to enhance growth rates and yield. Our operations include the establishment of state-of-the-art tree nurseries that produce genetically superior seedlings, ensuring robust forest regeneration. We also implement sustainable thinning practices to maximize forest health and productivity. By integrating technology into our forestry operations, we are able to create value while promoting environmental sustainability and conservation.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00011707942116635081, 'A': 0.9986276924469143, 'F': 0.0003122539940515267, 'B': 0.0008430642996376746, 'J': 9.990983823014126e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0013723075530857054}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 33%|█████████████████████████████████████████████████████████▎                                                                                                                     | 258/788 [00:16<00:36, 14.44it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 256:
  Engaged in the mining of various non-ferrous metal ores, our organization focuses on extracting valuable minerals such as copper, zinc, and lead. We operate multiple mines equipped with cutting-edge technology that enables us to optimize ore extraction and processing. Our commitment to sustainability is reflected in our use of environmentally friendly methods, including water recycling and emissions reduction systems. Additionally, we provide technical support and consulting services to other mining operations, sharing best practices in resource management and operational efficiency.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.49915667735123e-05, 'A': 3.445875421356778e-05, 'F': 1.2375428848031154e-05, 'B': 0.9998909878706179, 'J': 7.186379547000026e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.455714491328568e-06, 6: 1.6011486655281287e-06, 7: 0.999995943136843}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035194831934014535, 7.2: 0.9648051680659854}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 257:
  We are dedicated to the cultivation of high-quality vegetables and melons, employing state-of-the-art greenhouse technology to optimize growing conditions. Our operations focus on hydroponic and vertical farming methods, allowing us to maximize space and resource efficiency. By closely monitoring environmental factors such as temperature and humidity, we ensure consistent product quality throughout the year. Our fresh produce is delivered directly to local markets and grocery chains, emphasizing freshness and sustainability. Furthermore, we engage in community-supported agriculture initiatives, which foster direct relationships with consumers and promote awareness of healthy eating practices.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.0287816590718248, 'A': 0.41064032744536566, 'F': 0.05102635467847463, 'B': 0.5041484777002698, 'J': 0.005403181104065186}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4958515222997302}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 258:
  Our company is at the forefront of aquaculture, focusing on the cultivation of shellfish such as oysters and clams. We operate several coastal farms where we utilize innovative techniques to enhance growth rates and improve water quality. By employing floating cages and bottom planting methods, we ensure that our shellfish thrive in their natural habitat. Our products are harvested and processed on-site, allowing us to maintain strict quality control and deliver fresh seafood directly to consumers and restaurants. Additionally, we conduct research on environmental impacts, striving to balance production with ecological sustainability.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00034789310060296915, 'A': 0.9949923103996576, 'F': 0.002247423851120176, 'B': 0.0021484460904639983, 'J': 0.0002639265581550151}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005007689600342369}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 259:
  We offer comprehensive support activities for transportation, ensuring that our lignite products reach their destinations safely and efficiently. Our fleet of specialized vehicles is equipped to handle the unique challenges of transporting lignite, including bulk transport and adherence to safety regulations. We also collaborate with local transportation providers to optimize routes and reduce delivery times. By investing in logistics technology, we can track shipments in real-time, providing our clients with transparency and peace of mind. Our commitment to reliable transportation services enhances our overall value proposition in the lignite market.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9987461238314633, 'A': 3.8751345180950855e-05, 'F': 9.355316967584921e-05, 'B': 0.00014106500859170854, 'J': 0.0009805066450880731}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0012538761685366717}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 34%|██████████████████████████████████████████████████████████▋                                                                                                                    | 264/788 [00:16<00:27, 18.85it/s]

RAPS scores:

==================================================
Description 260:
  Our company is involved in the breeding and raising of goats, with a focus on dairy production. We utilize selective breeding techniques to enhance milk yield and quality, producing a range of artisanal goat cheeses that have gained recognition in gourmet markets. Our farms are designed to promote animal welfare, offering spacious living conditions and a balanced diet rich in nutrients. We also engage in educational outreach, sharing best practices in goat husbandry with aspiring farmers, thereby fostering a community of sustainable agriculture.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.016300000912306604, 'A': 0.452649006100146, 'F': 0.026105881912346755, 'B': 0.5011322311181307, 'J': 0.0038128799570700065}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.49886776888186934}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 261:
  We are engaged in the mining of magnesium ores, focusing on the extraction and processing of this lightweight metal crucial for the automotive and aerospace industries. Our operations employ advanced techniques such as thermal reduction and electrolysis to produce high-purity magnesium products. We prioritize sustainability, implementing measures to reduce waste and energy consumption throughout our processes. Our research and development team is dedicated to exploring new applications for magnesium, enhancing its use in lightweight structures and energy-efficient technologies. By fostering partnerships with manufacturers and investing in community initiatives, we aim to create a positive impact while driving growth in the non-ferrous metals market.1. Our company specializes in the extraction and processing of uranium ores, utilizing advanced techniques to ensure minimal environmental impact. We operate several mines equipped with state-of-the-art technology that enhances ore recovery rates while adhering to stringent safety protocols. Our commitment to sustainability is reflected in our reclamation projects, which restore mined land for future use. Additionally, we invest in research to develop innovative extraction methods that increase efficiency and reduce waste, positioning us as a leader in the uranium mining sector.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.617512001329099e-05, 'A': 3.390106877308442e-05, 'F': 1.2293452472752051e-05, 'B': 0.999890506514138, 'J': 7.123844602936539e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010949348586197782}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 262:
  At Green Pastures Farms, we are dedicated to the raising of sheep and goats, producing premium wool and organic meat. Our farm employs rotational grazing techniques to maintain soil health and promote biodiversity. We have established partnerships with local artisans who use our wool to create sustainable clothing and home goods. Additionally, we offer farm tours and workshops to educate the community about sustainable farming practices and the benefits of consuming locally sourced products. By prioritizing animal welfare and environmental sustainability, we create value for our customers while supporting the local economy.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0001725023059054966, 'A': 0.9976147539662481, 'F': 0.000802755051604456, 'B': 0.0012653201907368065, 'J': 0.00014466848550521308}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0023852460337518977}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 263:
  Engaging in the capture fishery sector, our business focuses on the use of stationary traps for collecting various aquatic organisms. We strategically place these traps in both coastal and inland waters, targeting species such as lobsters and freshwater shrimp. Our operations are designed to minimize environmental impact, with regular assessments of trap placement and catch rates. We distribute our catch to local seafood markets, emphasizing traceability and quality. Additionally, we collaborate with marine biologists to study the ecosystems we operate in, contributing to ongoing research and conservation efforts.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0007214774336556085, 'A': 0.003125329396011618, 'F': 0.00039459549371367256, 'B': 0.9956093748780981, 'J': 0.00014922279852077879}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.004390625121901914}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 264:
  In the realm of freshwater aquaculture, our business is dedicated to the cultivation of tilapia and catfish in controlled environments. We employ innovative farming techniques that enhance growth rates and feed conversion efficiency, allowing us to produce fish year-round. Our facilities are equipped with state-of-the-art filtration systems that maintain optimal water quality, reducing the risk of disease. We also engage in community outreach programs to educate local farmers about sustainable practices, fostering a network of responsible aquaculture. Our commitment to quality and sustainability positions us as a leader in the freshwater fish market.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00026335845650957466, 'A': 0.9969249645456607, 'F': 0.0008327862684331365, 'B': 0.0017806310568808026, 'J': 0.00019825967251564742}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003075035454339292}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 34%|███████████████████████████████████████████████████████████▉                                                                                                                   | 270/788 [00:17<00:23, 22.50it/s]

RAPS scores:

==================================================
Description 265:
  Our company dedicates itself to the cultivation of other perennial crops, including various medicinal herbs and plants used in traditional remedies. We prioritize organic farming practices, ensuring that our products are free from synthetic chemicals. Our herbs are harvested at peak potency and processed into teas, tinctures, and capsules, catering to the growing demand for natural health products. We engage in community outreach programs to educate consumers about the benefits of herbal medicine, further establishing our brand as a trusted source in the wellness industry.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.030773782935335076, 'A': 0.14852183261614707, 'F': 0.025168140468500123, 'B': 0.7915999857710235, 'J': 0.003936258208994198}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.20840001422897647}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 266:
  Our operations focus on the cultivation of beverage crops, including coffee and tea plants. We implement sustainable farming practices, such as shade-grown cultivation, which preserves local ecosystems while enhancing the flavor profiles of our products. Our coffee beans are sourced from smallholder farmers who adhere to fair trade principles, ensuring ethical sourcing and supporting local communities. We also offer a range of specialty teas, emphasizing unique blends and organic ingredients. Our commitment to quality and sustainability has garnered a loyal customer base, and we actively participate in trade shows to promote our products to a broader audience.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.04024259932425349, 'A': 0.016800822246594672, 'F': 0.009310889859251258, 'B': 0.9317372566808234, 'J': 0.0019084318890771066}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.06826274331917659}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 267:
  Our company is engaged in the production of roundwood specifically for utility applications, including poles and posts. We operate in compliance with stringent environmental regulations, ensuring that our logging practices are sustainable and responsible. The roundwood we harvest is processed to meet the specific requirements of utility companies, providing them with durable and reliable materials for infrastructure development. By focusing on quality and sustainability, we help our clients maintain their operations while contributing to the overall health of the forest ecosystems from which we source our materials.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.004283822003008435, 'A': 0.0016639104325845964, 'F': 0.0005360467068806307, 'B': 0.9932779114749664, 'J': 0.0002383093825599725}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006722088525033643}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 268:
  At GreenCanopy Forestry, we prioritize the health of our forests through meticulous silviculture practices. Our team is dedicated to planting and nurturing a diverse range of tree species, ensuring that our timber stands are resilient and productive. We also focus on thinning operations that optimize growth conditions for remaining trees, enhancing both timber quality and forest ecosystem health. By maintaining a robust forest nursery, we supply local communities with seedlings that promote reforestation efforts, aligning our business model with sustainable development goals and environmental stewardship.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.41073211012879e-05, 'A': 0.9994831135063519, 'F': 0.0002541702646899706, 'B': 0.00017189988686931452, 'J': 4.670902098776828e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0005168864936481166}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 269:
  Specializing in the raising of sheep, our farm is committed to producing high-quality wool and meat. We practice rotational grazing to maintain soil health and promote biodiversity on our pastures. Our sheep are bred for their hardiness and adaptability to local climates, ensuring a sustainable yield year-round. We also offer wool processing services, transforming raw fleece into premium yarns that are sold to artisans and textile manufacturers, thus adding value to our agricultural output and supporting local craft industries.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.010263739366296279, 'A': 0.08525328382107335, 'F': 0.013832434297973158, 'B': 0.8888667085970627, 'J': 0.0017838339175945037}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11113329140293726}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 270:
  We focus on the harvesting of natural resins and balsams from specific tree species, which are used in the production of perfumes, cosmetics, and traditional medicines. Our team of skilled gatherers employs sustainable practices to ensure that the trees remain healthy and productive. We maintain strong relationships with artisans and manufacturers who rely on our high-quality resins, and we actively participate in trade shows to showcase our products. By emphasizing the unique properties of our natural resins, we create value for both our suppliers and customers.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9732124360113257, 'A': 0.0006951450186731972, 'F': 0.0014217495764674436, 'B': 0.023521668473784976, 'J': 0.0011490009197488485}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.026787563988674323}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 35%|████████████████████████████████████████████████████████████▋                                                                                                                  | 273/788 [00:17<00:25, 19.87it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 271:
  Our firm is dedicated to the production of natural gas, employing innovative extraction techniques that leverage the latest advancements in technology. We operate multiple drilling rigs across various locations, focusing on both conventional and unconventional gas sources. Our processing facilities are equipped with sophisticated systems for the separation of liquid hydrocarbons, allowing us to maximize the output from each well. Additionally, we prioritize environmental stewardship by implementing gas desulphurization processes that ensure compliance with regulatory standards. This approach not only enhances the quality of our product but also contributes to cleaner energy solutions for our customers.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.5650952957010426e-05, 'A': 3.412877814111926e-05, 'F': 1.2333516616328842e-05, 'B': 0.9998907298506922, 'J': 7.156901593134475e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7668245136184044e-06, 6: 0.9999964259451123, 7: 1.8072303740468018e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979818635973118, 6.1: 0.0020181364026881695}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 272:
  As a prominent player in the natural gas sector, we focus on the extraction and processing of crude gaseous hydrocarbons. Our operations are characterized by the use of advanced drilling technologies and efficient gas processing techniques, including the separation of liquid hydrocarbon fractions. We are dedicated to reducing our environmental impact through effective gas desulphurization methods, which enhance the quality of our products. Our strategic partnerships with key stakeholders in the energy market enable us to deliver reliable and sustainable natural gas solutions to a diverse range of clients.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.497899610710018e-05, 'A': 3.474357365428202e-05, 'F': 1.249988761026033e-05, 'B': 0.999890535747383, 'J': 7.241795245335734e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010946425261704196}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 273:
  Our company is dedicated to the storage and warehousing of lignite, offering strategically located facilities that ensure optimal conditions for preserving the quality of the coal. We utilize advanced monitoring systems to maintain appropriate humidity and temperature levels, safeguarding the lignite from deterioration. Additionally, our logistics team is skilled in managing inventory efficiently, enabling us to respond swiftly to market demands. By providing reliable storage solutions, we help our clients streamline their supply chains and reduce operational risks associated with lignite handling.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 7.440018050132669e-05, 'A': 3.651614426418667e-05, 'F': 1.4014203976138385e-05, 'B': 0.9998666792884116, 'J': 8.390182846791105e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00013332071158844716}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 274:
  Our business model centers on the extraction of crude petroleum, where we leverage cutting-edge drilling technologies and extensive geological research to maximize resource recovery. We operate in diverse environments, from deepwater offshore fields to complex shale formations, adapting our techniques to suit each unique setting. Our commitment to safety and environmental protection is reflected in our proactive measures to mitigate risks and reduce emissions. By collaborating with industry partners, we continuously seek to improve our operational practices and contribute to a more sustainable energy landscape.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.47757656300549e-05, 'A': 3.4920690058841046e-05, 'F': 1.2519438074587505e-05, 'B': 0.9998905313164667, 'J': 7.25278976997658e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010946868353334249}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 35%|█████████████████████████████████████████████████████████████▉                                                                                                                 | 279/788 [00:17<00:21, 23.71it/s]

RAPS scores:

==================================================
Description 275:
  We are at the forefront of innovative forestry practices, focusing on the growth of firewood and biomass resources. Our operations include the cultivation of fast-growing tree species specifically for energy production, catering to the rising demand for renewable energy sources. Through sustainable harvesting methods, we ensure that our firewood operations do not deplete forest resources. Additionally, we provide educational resources to local communities on the benefits of using sustainably sourced firewood, promoting energy efficiency and environmental responsibility.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 9.025008209297293e-05, 'A': 0.9988179075180654, 'F': 0.0005193491229847049, 'B': 0.0004879757174764176, 'J': 8.451755938055124e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0011820924819345713}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 276:
  Our firm focuses on the extraction of crude petroleum, employing a diverse range of extraction methods tailored to specific geological formations. We prioritize safety and environmental responsibility, implementing rigorous protocols to protect local ecosystems during our operations. Our commitment to innovation drives us to adopt new technologies, such as artificial intelligence for predictive maintenance and drone surveillance for site monitoring. This holistic approach not only enhances our operational efficiency but also strengthens our reputation as a responsible industry player.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.485569797530675e-05, 'A': 3.527930726298571e-05, 'F': 1.2602412449256266e-05, 'B': 0.9998899683838443, 'J': 7.294198468188468e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011003161615574797}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 277:
  Our operations in the charcoal production sector emphasize the use of traditional methods that not only yield high-quality charcoal but also promote sustainable forest management. We source our wood from local forests, ensuring that our production process supports the local economy and minimizes environmental impact. Our charcoal is marketed to both retail and industrial clients, who appreciate the quality and sustainability of our products. By maintaining a strong focus on traditional techniques, we preserve cultural heritage while meeting modern energy needs.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9942332486579444, 'A': 0.00011933315027644902, 'F': 0.00012351988060455452, 'B': 0.005200512809957444, 'J': 0.0003233855012172093}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0057667513420556205}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 278:
  We focus on the sustainable production of vegetative planting materials, including a diverse range of seedlings and cuttings. Our nursery utilizes innovative growing techniques to ensure that our plants are healthy and vigorous, ready for use in various landscaping projects. We offer a wide selection of ornamental plants, as well as turf grasses suitable for different climates and applications. Our commitment to quality and customer satisfaction drives us to provide exceptional products and services, fostering strong relationships with our clients and contributing to the growth of the horticultural industry.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9985978760615365, 'A': 8.591491879196476e-05, 'F': 0.00017087317672874643, 'B': 0.0007356864897490781, 'J': 0.00040964935319384976}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0014021239384635065}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 279:
  We specialize in the growth and processing of diverse non-perennial crops, including specialty grains and pulses. Our innovative farming techniques, such as no-till agriculture, help to preserve soil structure and enhance biodiversity on our farms. We work closely with food manufacturers to develop custom blends and formulations that cater to specific dietary needs, such as gluten-free or high-protein products. Our commitment to sustainability is evident in our efforts to reduce waste throughout the supply chain, from seed production to final product delivery, ensuring that we contribute positively to the environment and society.1. Our company specializes in the cultivation of a diverse range of cereals, including barley and oats, which are essential for both human consumption and animal feed. We employ advanced agricultural techniques such as precision farming and crop rotation to enhance yield and sustainability. Our commitment to quality is reflected in our rigorous testing processes, ensuring that our grains meet the highest standards. Additionally, we engage in seed production, developing high-yield varieties that are resistant to pests and diseases, thereby contributing to food security and agricultural innovation.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9052748569159356, 'A': 0.0020149450069074587, 'F': 0.004810748179299673, 'B': 0.08560852388437473, 'J': 0.00229092601348242}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09472514308406443}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 36%|██████████████████████████████████████████████████████████████▋                                                                                                                | 282/788 [00:17<00:24, 20.41it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 280:
  In the tobacco growing segment, the company employs sustainable farming techniques to cultivate high-quality tobacco leaves. By focusing on soil health and crop rotation, the business minimizes environmental impact while ensuring robust yields. The harvested tobacco is processed into various products, including cigarettes and cigars, catering to both domestic and international markets. The company also invests in community development initiatives to support local farmers and promote responsible tobacco use.
True: section=A, division=1, class=1.1
Section set: ['A']
Section probs: {'C': 1.0492373152497167e-05, 'A': 0.9999095820969297, 'F': 3.8370974503662194e-05, 'B': 2.8815227024930923e-05, 'J': 1.2739328389246568e-05}
Division sets: {'A': ['1']}
Division probs: {'A': {1: 0.997731941515617, 2: 0.0015305146833641376, 3: 0.0007375438010189427}}
Class sets: {'1': ['1.1']}
Class probs: {'1': {1.2: 0.005967476482755419, 1.4: 0.0060550507908332715, 1.3: 0.0030561247109342393, 1.1: 0.984921348015477}}
Final output: {'type': 'class_level', 'codes': ['1.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 281:
  We are dedicated to the raising of swine, utilizing innovative farming methods that prioritize animal health and environmental sustainability. Our facilities are equipped with climate-controlled environments to optimize growth conditions for our pigs. We implement a comprehensive nutrition program that includes locally sourced feed, ensuring that our livestock receive the best possible diet. Our commitment to biosecurity measures protects our herd from diseases, allowing us to supply high-quality pork products to local markets while adhering to strict food safety regulations.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.011229630167562392, 'A': 0.6896146143481353, 'F': 0.03348607920080506, 'B': 0.26225509586023704, 'J': 0.0034145804232601825}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3103853856518647}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 282:
  As a prominent player in the iron ore sector, we focus on the entire value chain from mining to beneficiation. Our operations utilize advanced technology for ore extraction, including remote sensing and automated drilling systems, which enhance operational efficiency and safety. The beneficiation process is designed to produce high-purity iron ore concentrates, which are essential for steel production. We are also committed to reducing our environmental impact through initiatives such as waste recycling and energy-efficient practices, ensuring that our mining activities support sustainable development goals.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.480154059087123e-05, 'A': 3.439982701028253e-05, 'F': 1.2350649354972164e-05, 'B': 0.9998912900518575, 'J': 7.157931186251202e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4565559752067213e-06, 6: 1.6029377470831206e-06, 7: 0.9999959405062778}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677902581302108, 7.2: 0.03220974186978909}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 37%|███████████████████████████████████████████████████████████████▉                                                                                                               | 288/788 [00:17<00:24, 20.73it/s]

RAPS scores:

==================================================
Description 283:
  Our company, Plant Pro, specializes in the production of high-quality vegetative planting materials for both commercial and residential markets. We focus on the cultivation of a wide array of seedlings, cuttings, and grafting stock, ensuring that our plants are healthy and robust. Our nursery employs advanced propagation techniques, including tissue culture and hydroponics, to maximize growth potential and minimize resource use. We also offer a selection of ornamental plants that are perfect for landscaping projects, enhancing the aesthetic appeal of outdoor spaces. By providing expert advice and support to our clients, we foster lasting relationships and promote successful gardening practices.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9957467701069491, 'A': 0.00024649402738388866, 'F': 0.0007630496459917078, 'B': 0.0023170465918823063, 'J': 0.0009266396277929953}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0042532298930508805}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 284:
  Our company is dedicated to the growth of beverage crops, primarily focusing on coffee and tea. We cultivate our crops in ideal climates, ensuring rich flavors and high-quality yields. Our farms are certified organic, and we prioritize sustainable practices that protect the environment and support local communities. We work directly with farmers to improve their cultivation techniques and ensure fair pricing. The harvested beans and leaves are processed and packaged for distribution to specialty retailers and cafes, allowing consumers to enjoy premium beverages that reflect our commitment to quality and sustainability.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.06032335838697707, 'A': 0.09482121343051034, 'F': 0.05370688382863505, 'B': 0.786103741199835, 'J': 0.005044803154042586}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.21389625880016505}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 285:
  Our company focuses on the conservation and management of timber tracts, employing a holistic approach that integrates ecological health with economic viability. We engage in activities such as selective logging, which allows us to harvest timber without compromising the integrity of the forest ecosystem. Our team of experts conducts regular biodiversity assessments to ensure that our practices support wildlife habitats and promote forest regeneration. By balancing timber production with conservation efforts, we create a sustainable model that benefits both the environment and local communities.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.5704161823484534e-05, 'A': 0.9997289841205609, 'F': 0.00011810562385166573, 'B': 9.87521383452386e-05, 'J': 2.8453955418616316e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002710158794391182}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 286:
  Engaged in the raising of other livestock, our operations focus on the breeding of specialty animals such as alpacas and llamas. We prioritize genetic diversity and health, employing advanced breeding techniques to enhance desirable traits. Our animals are raised in a stress-free environment that promotes natural behaviors and well-being. We also produce high-quality fiber products, which are processed on-site to create sustainable textiles. By educating consumers about the benefits of these unique animals, we aim to foster a greater appreciation for their contributions to agriculture and the economy.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00011989323069390381, 'A': 0.9980625949890204, 'F': 0.0011167003398141369, 'B': 0.0005848958481170318, 'J': 0.00011591559235451848}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0019374050109796093}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 287:
  Our operations involve the cultivation of spices and aromatic crops, such as saffron and basil, which are harvested for culinary and medicinal purposes. We utilize organic farming methods to ensure the purity and potency of our products, focusing on small-scale, artisanal production that enhances flavor and aroma. Our spices are packaged in eco-friendly materials and marketed through specialty food stores and online platforms, appealing to consumers seeking high-quality, natural ingredients. We also engage in educational initiatives to raise awareness about the health benefits of our products, fostering a connection with our customers.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.17049621693077657, 'A': 0.005182547236082228, 'F': 0.0064281644502536045, 'B': 0.8159272414517639, 'J': 0.001965829931123718}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18407275854823613}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 288:
  Our nursery is dedicated to producing high-quality seedlings for commercial agriculture, focusing on crops that are in high demand. We employ advanced propagation techniques and rigorous quality control measures to ensure that our seedlings are robust and ready for planting. Our team works closely with farmers to understand their specific needs, offering tailored solutions that enhance crop yield and resilience. We also provide educational resources on best practices for planting and care, empowering our clients to achieve successful harvests. Our commitment to innovation and sustainability positions us as a leader in the agricultural propagation sector.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.007767997383610102, 'A': 0.884498864625797, 'F': 0.05680928481082357, 'B': 0.04790345387407359, 'J': 0.0030203993056956376}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11550113537420303}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 37%|████████████████████████████████████████████████████████████████▋                                                                                                              | 291/788 [00:18<00:25, 19.58it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 289:
  We operate several iron ore mines across diverse geographical regions, each equipped with modern extraction and processing facilities. Our team of engineers and geologists work collaboratively to optimize mining operations, ensuring that we meet production targets while adhering to safety and environmental regulations. Through continuous investment in research and development, we are exploring new methods of ore processing that increase yield and reduce costs. Our commitment to innovation positions us as a competitive player in the iron ore market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.533530362348182e-05, 'A': 3.40893603889876e-05, 'F': 1.2288572870441234e-05, 'B': 0.9998911829070101, 'J': 7.1038561069552665e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.488835579673695e-06, 6: 1.5764784871470344e-06, 7: 0.9999959346859332}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677245424033101, 7.2: 0.03227545759669002}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 290:
  We are dedicated to the cultivation of spices, aromatic plants, and pharmaceutical crops, focusing on high-demand products such as turmeric, ginger, and lavender. Our farming practices emphasize organic methods, which enhance the potency and flavor of our crops. We collaborate with local herbalists and pharmaceutical companies to supply raw materials that meet their quality standards. Our commitment to sustainable agriculture not only supports our business growth but also contributes to the health and wellness of our consumers.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.3862519220281241, 'A': 0.010453336486308347, 'F': 0.020354275828437463, 'B': 0.5785925792267236, 'J': 0.004347886430406505}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4214074207732764}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 291:
  Our company is at the forefront of research and development in sustainable fishing technologies. We collaborate with marine biologists and engineers to create innovative fishing gear that reduces bycatch and minimizes habitat disruption. Our latest product, a biodegradable fishing net, is designed to break down naturally in marine environments, reducing pollution. By providing these solutions to commercial fishers, we aim to enhance the sustainability of fishing practices while promoting environmental stewardship across the industry.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 6.950886900556736e-05, 'A': 0.9992351540083425, 'F': 0.00020891675395458314, 'B': 0.0004206700393509297, 'J': 6.575032934643986e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007648459916574923}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 37%|█████████████████████████████████████████████████████████████████▎                                                                                                             | 294/788 [00:18<00:30, 16.08it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 292:
  Our lignite mining company is dedicated to sustainable practices that prioritize both resource extraction and environmental stewardship. We utilize advanced mining techniques, including liquefaction, to efficiently extract lignite while minimizing our ecological footprint. Our processing facilities are equipped with state-of-the-art washing and dehydrating equipment, which enhances the quality of the lignite for our clients. Furthermore, we have established a comprehensive logistics network that facilitates the smooth transportation of our product to storage facilities, ensuring that we can meet the demands of the energy market effectively.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.494328266099951e-05, 'A': 3.447765667039014e-05, 'F': 1.2384558704839062e-05, 'B': 0.9998910278449907, 'J': 7.16665697311426e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957389448494, 6: 1.3386301246359483e-06, 7: 2.9224250260060268e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023549082280317655, 5.2: 0.9976450917719683}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 293:
  As a leader in iron ore mining, we focus on the full lifecycle of ore extraction, from exploration to delivery. Our geological teams employ cutting-edge surveying technologies to identify high-potential mining sites. Once identified, we utilize automated drilling and blasting techniques to extract ore efficiently. Our beneficiation facilities are equipped with advanced flotation and gravity separation systems, enabling us to produce high-purity iron concentrates. We pride ourselves on our commitment to safety and sustainability, ensuring that our operations adhere to the highest environmental standards while maximizing yield.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.480313940223203e-05, 'A': 3.4501856668018126e-05, 'F': 1.2389347344878808e-05, 'B': 0.9998911387271342, 'J': 7.166929450638215e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4787182433478865e-06, 6: 1.57837548725771e-06, 7: 0.9999959429062694}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677853117342288, 7.2: 0.03221468826577112}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 294:
  Our aquaculture business is at the forefront of innovation, specializing in the farming of molluscs such as oysters and clams. We utilize floating cages and bottom culture techniques to optimize growth conditions and enhance product quality. Our commitment to sustainability is reflected in our use of biodegradable materials for farming gear and our adherence to local environmental regulations. We also invest in research and development to explore new breeding techniques that enhance resilience against climate change. By collaborating with marine scientists, we aim to improve our farming practices and contribute to the restoration of natural habitats while providing high-quality seafood to our customers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.023297783985969205, 'A': 0.1181470249265679, 'F': 0.02154721170149347, 'B': 0.8339148365722034, 'J': 0.0030931428137658972}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.16608516342779656}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 38%|█████████████████████████████████████████████████████████████████▋                                                                                                             | 296/788 [00:18<00:31, 15.42it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 295:
  With a focus on crude petroleum extraction, our operations leverage cutting-edge hydraulic fracturing techniques to access hard-to-reach reserves. We have established a network of strategically located refineries that process the extracted crude into various petroleum products, including gasoline, diesel, and jet fuel. Our integrated supply chain allows us to efficiently transport these products to market, ensuring timely delivery to our customers. Furthermore, we prioritize safety and environmental stewardship, employing rigorous monitoring systems to minimize the ecological footprint of our extraction activities.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.497013415700267e-05, 'A': 3.447084541815996e-05, 'F': 1.2368508769622759e-05, 'B': 0.9998909825817296, 'J': 7.207929925591038e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7853452393054369e-06, 6: 0.9999964068081616, 7: 1.8078465990333488e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020606312989541594, 6.1: 0.9979393687010458}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 38%|██████████████████████████████████████████████████████████████████▊                                                                                                            | 301/788 [00:18<00:30, 15.81it/s]

RAPS scores:

==================================================
Description 296:
  Our focus on the mining and beneficiation of iron ores drives our commitment to operational excellence and sustainability. We employ advanced exploration techniques to identify high-potential ore deposits, followed by efficient extraction methods that prioritize safety and environmental responsibility. Our state-of-the-art beneficiation plants utilize innovative technologies to produce high-quality iron ore products, including pellets and concentrates, which are critical for steel production. We also provide engineering and consultancy services to support other mining operations, sharing our expertise in optimizing processes and enhancing overall efficiency.1. Our company specializes in the extraction and processing of iron ores, focusing primarily on high-grade deposits that yield significant iron content. We utilize advanced mining techniques to ensure efficient ore recovery while minimizing environmental impact. Our operations include open-pit mining and underground methods, complemented by state-of-the-art beneficiation processes that enhance ore quality. We also invest in innovative technologies for ore agglomeration, allowing us to produce pellets that meet the stringent requirements of steel manufacturers. By maintaining strong relationships with our clients, we ensure a steady supply of premium iron products that drive value in the steel production industry.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.520709242435739e-05, 'A': 3.4298156241144896e-05, 'F': 1.2354185251602147e-05, 'B': 0.9998909623479856, 'J': 7.1782180972221e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4574399414458048e-06, 6: 1.6007677285952207e-06, 7: 0.99999594179233}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677823309066846, 7.2: 0.03221766909331539}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 297:
  Our business is rooted in the artisanal fishing tradition, specializing in the collection of crustaceans such as lobsters and crabs. We operate in coastal waters, using traps designed to minimize environmental impact while maximizing catch efficiency. Our commitment to sustainable fishing practices is reflected in our adherence to seasonal regulations and size limits, ensuring the longevity of crustacean populations. The seafood we harvest is delivered fresh to local markets and restaurants, where our reputation for quality and sustainability has garnered a loyal customer base.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0015276837587821638, 'A': 0.9450455849661588, 'F': 0.003271317287017909, 'B': 0.049330230083939525, 'J': 0.0008251839041017228}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05495441503384124}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 298:
  Our company is a leading producer of high-quality tobacco, focusing on sustainable cultivation methods that respect both the environment and the communities we operate in. We implement rigorous quality control measures throughout the growing and curing processes to ensure our products meet the highest standards. By investing in research and development, we are exploring alternative uses for tobacco plants, including biofuel production and natural pest control solutions. Our tobacco is primarily sold to major manufacturers for use in premium products, emphasizing quality and craftsmanship.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9984511814392604, 'A': 9.079623904033711e-05, 'F': 0.0001338410528947063, 'B': 0.0009814192180076255, 'J': 0.0003427620507968146}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0015488185607396288}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 299:
  We are engaged in the operation of forest tree nurseries, where we cultivate a variety of native and non-native species for restoration and commercial purposes. Our state-of-the-art facilities utilize environmentally friendly practices, including organic fertilizers and integrated pest management, to produce healthy, resilient seedlings. We work closely with local communities and conservation organizations to restore degraded lands, enhancing biodiversity and supporting local ecosystems. Our nursery operations not only provide essential resources for reforestation but also foster community engagement in sustainable forestry initiatives.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00010768593876065969, 'A': 0.9975127784705715, 'F': 0.0019193554864217074, 'B': 0.00034487900972268194, 'J': 0.00011530109452341236}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.002487221529428485}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 300:
  We focus on the cultivation of sugar cane, leveraging advanced agronomic practices to enhance yield and sugar content. Our operations are strategically located in regions with optimal climatic conditions, allowing us to produce high-quality cane that meets the demands of the beverage and food industries. We employ sustainable farming techniques, including water conservation methods and soil health initiatives, to ensure the long-term viability of our crops. Additionally, we invest in processing facilities that convert raw cane into sugar and molasses, which are then distributed to various markets. Our commitment to sustainability is further demonstrated through our efforts to reduce carbon emissions in our production processes.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.2358981925674943, 'A': 0.003704760272461361, 'F': 0.004039742963975403, 'B': 0.7545094759843464, 'J': 0.001847828211722522}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.24549052401565363}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 301:
  We are dedicated to the raising of other cattle and buffaloes, focusing on both meat and dairy production. Our farms utilize rotational grazing techniques to enhance pasture quality and animal health. We implement advanced breeding programs that emphasize disease resistance and productivity, ensuring a robust herd. Our facilities are equipped with modern milking technology and processing units that allow us to produce high-quality dairy products, including specialty cheeses. We also engage in community outreach, promoting sustainable farming practices and providing educational resources to local farmers to improve livestock management.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.003165370933245862, 'A': 0.9245209000324397, 'F': 0.00953152803825712, 'B': 0.061386821511509274, 'J': 0.0013953794845482635}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0754790999675603}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 39%|████████████████████████████████████████████████████████████████████▏                                                                                                          | 307/788 [00:19<00:25, 19.11it/s]

RAPS scores:

==================================================
Description 302:
  Our company is dedicated to the raising of exotic animals, including llamas and emus, for both fiber and meat production. We prioritize ethical breeding practices, ensuring the health and well-being of our animals. Our llamas produce high-quality fleece that is sought after by artisans and crafters, while our emus are raised for their lean meat, which is gaining popularity for its nutritional benefits. We also engage in educational outreach, offering farm tours and workshops to teach the community about these unique animals and their contributions to sustainable agriculture.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00042328186470623637, 'A': 0.9926384131617506, 'F': 0.004783656409114289, 'B': 0.0018189746370367386, 'J': 0.00033567392739205414}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00736158683824939}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 303:
  Our company provides specialized support activities for lignite transportation, focusing on optimizing logistics and supply chain management. We have developed a robust network of transportation solutions that include rail and truck services, ensuring timely delivery of lignite to power plants and industrial clients. Our operations are supported by a sophisticated tracking system that monitors shipments in real-time, allowing us to respond swiftly to any logistical challenges. By streamlining our transportation processes, we enhance the overall efficiency of lignite distribution while minimizing costs for our customers.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 4.4200315773503e-05, 'A': 0.00011657575814994635, 'F': 0.9996260644390136, 'B': 1.53956310685187e-05, 'J': 0.00019776385599438843}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003739355609864159}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 304:
  Specializing in the cultivation of aquatic plants, our business engages in the farming of seaweeds and other edible flora. We utilize integrated multi-trophic aquaculture systems that allow for the synergistic growth of various species, enhancing overall productivity. Our seaweed is harvested and processed for use in food products, cosmetics, and biofuels, demonstrating our commitment to diversifying the applications of aquaculture. By employing sustainable farming practices, we contribute to ocean health while providing high-value products that meet the growing demand for natural ingredients in various industries.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.04232876139408558, 'A': 0.4099746404805636, 'F': 0.09038564101131522, 'B': 0.45011202621101304, 'J': 0.007198930903022742}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.549887973788987}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 305:
  We are a leader in the natural gas sector, specializing in the extraction and processing of crude gaseous hydrocarbons. Our operations are characterized by the use of advanced drilling technologies that maximize resource recovery while minimizing environmental impact. We focus on the separation of liquid hydrocarbon fractions, enhancing our product offerings and meeting diverse customer needs. Our commitment to quality is reflected in our state-of-the-art gas desulphurization processes, ensuring that our natural gas is both clean and efficient. We continuously strive to innovate and improve our practices, aligning our business model with sustainable energy solutions.1. Our company specializes in the extraction and processing of natural gas, focusing on maximizing efficiency and sustainability. We employ advanced drilling techniques and state-of-the-art technology to locate and extract crude gaseous hydrocarbons from deep underground reserves. Our operations include the separation of natural gas from condensates and other liquid hydrocarbons, ensuring that we deliver high-purity products to our clients. Additionally, we invest in research and development to enhance our gas desulphurization processes, reducing environmental impact while meeting stringent regulatory standards. Through these efforts, we aim to provide reliable energy solutions that contribute to a cleaner future.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.5243958510327756e-05, 'A': 3.464068121920849e-05, 'F': 1.2506082664437907e-05, 'B': 0.999890349558672, 'J': 7.259718933988643e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010965044132804636}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 306:
  Our operations center around the extraction and processing of natural gas, where we leverage innovative technologies to enhance efficiency and reduce costs. We utilize horizontal drilling and hydraulic fracturing techniques to access previously untapped reserves, ensuring a steady supply of natural gas to meet growing market demands. Our facilities are equipped with advanced separation units that effectively isolate liquid hydrocarbons, allowing us to market high-value condensates alongside our primary gas products. We also prioritize sustainability by implementing gas desulphurization processes that meet stringent environmental regulations, reinforcing our commitment to cleaner energy solutions.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.4818979347769584e-05, 'A': 3.484124199584096e-05, 'F': 1.2512372404430916e-05, 'B': 0.9998905712054087, 'J': 7.2562008432647925e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010942879459130417}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 39%|████████████████████████████████████████████████████████████████████▊                                                                                                          | 310/788 [00:19<00:26, 18.26it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 307:
  Engaged in the extraction of crude petroleum, our operations span multiple regions, leveraging both conventional and unconventional resources. We have invested heavily in research to develop more efficient extraction techniques, such as steam-assisted gravity drainage, which allows us to tap into heavy oil reserves. Our skilled workforce is trained in the latest safety protocols, ensuring that our drilling activities are conducted with minimal risk. Furthermore, we actively participate in community engagement initiatives, providing local employment opportunities and supporting regional development projects that align with our corporate social responsibility goals.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.47220245514663e-05, 'A': 3.473584504949329e-05, 'F': 1.2446834799368196e-05, 'B': 0.9998908660979214, 'J': 7.229197678188127e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7759044642431532e-06, 6: 0.9999964017318311, 7: 1.8223637046601414e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020560840595824238, 6.1: 0.9979439159404175}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 308:
  Our crude oil extraction business is driven by a commitment to technological innovation and operational excellence. We utilize enhanced oil recovery techniques, such as steam injection and gas injection, to maximize output from mature fields. Our focus on continuous improvement leads us to adopt the latest advancements in drilling and production technologies, ensuring that we remain competitive in a dynamic market. We also prioritize workforce safety through rigorous training programs and adherence to industry best practices, creating a culture of safety and accountability across our operations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.497491257727792e-05, 'A': 3.473009451334611e-05, 'F': 1.2427842321799414e-05, 'B': 0.9998906452122808, 'J': 7.221938306827958e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010935478771922913}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 309:
  The organization specializes in the extraction of crude petroleum, employing a multi-faceted approach that includes geological surveys, exploratory drilling, and production optimization. Their operations are characterized by a commitment to safety and efficiency, utilizing automated systems to monitor drilling processes and ensure compliance with industry regulations. Additionally, the company collaborates with technology partners to develop new extraction methods that reduce environmental impact. By focusing on innovation and sustainability, they aim to enhance their operational performance while contributing to global energy security.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.525450360239082e-05, 'A': 3.589068913863477e-05, 'F': 1.2780804283691685e-05, 'B': 0.9998886907910705, 'J': 7.383211904717247e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011130920892954421}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 40%|█████████████████████████████████████████████████████████████████████▉                                                                                                         | 315/788 [00:19<00:24, 19.54it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 310:
  We focus on the mining and processing of aluminum ores, leveraging advanced technologies to produce high-quality bauxite for various industrial applications. Our operations are designed with sustainability in mind, employing energy-efficient methods and reducing greenhouse gas emissions. We also invest in research initiatives aimed at developing new extraction techniques that minimize environmental impact. Our aluminum products are supplied to the automotive, aerospace, and packaging industries, where they are valued for their lightweight and durable properties. Through strategic partnerships, we aim to enhance our supply chain and ensure a steady flow of aluminum to meet market demands.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.588811756742515e-05, 'A': 3.392719864839407e-05, 'F': 1.2296472030512946e-05, 'B': 0.999890766858195, 'J': 7.121353558681029e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.484151671248451e-06, 6: 1.5768972594836296e-06, 7: 0.9999959389510693}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03513895717293921, 7.2: 0.9648610428270609}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 311:
  We are dedicated to the sustainable growth of pulpwood, focusing on fast-growing tree species that can be harvested efficiently. Our operations include planting, maintaining, and harvesting these trees in a manner that minimizes environmental impact. We collaborate with local industries to supply high-quality pulp for paper production, ensuring that our practices align with sustainability goals. Our commitment to responsible forestry not only supports our business growth but also contributes to the health of the ecosystems in which we operate.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.30296969335869456, 'A': 0.016399122315470208, 'F': 0.023334573363874265, 'B': 0.6517632152649735, 'J': 0.005533395696987593}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3482367847350265}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 312:
  We engage in the farming of crustaceans, specifically shrimp, utilizing advanced pond management techniques that promote high-density production. Our facilities are equipped with automated feeding systems and water quality monitoring tools that allow us to maintain optimal growing conditions. Through our commitment to biosecurity and disease management, we ensure a healthy stock that meets the increasing demand for sustainable seafood. Our shrimp products are distributed both domestically and internationally, catering to a diverse range of culinary applications.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.01232774910284494, 'A': 0.02362665794787444, 'F': 0.006255102572250609, 'B': 0.9565895308041608, 'J': 0.0012009595728691132}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.04341046919583924}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 313:
  We specialize in the cultivation of pome fruits, particularly apples and pears, employing innovative techniques to enhance fruit quality and shelf life. Our orchards are designed for optimal sunlight exposure and air circulation, which helps reduce disease and improve fruit development. We focus on sustainable practices, including the use of cover crops and natural pest control methods. Our products are marketed directly to consumers through farmers' markets and local grocery stores, and we are also expanding our reach into the export market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9661918056735459, 'A': 0.0010883276371421128, 'F': 0.0032538098338417516, 'B': 0.027695503107760294, 'J': 0.0017705537477098812}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0338081943264541}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 314:
  We focus on the production of pulpwood through the careful management of fast-growing tree species. Our operations include planting and thinning practices that optimize growth rates and wood quality. By employing precision forestry techniques and leveraging data analytics, we maximize yield while ensuring that our practices align with sustainability goals. Our pulpwood is supplied to various industries, including paper and packaging, where it plays a vital role in reducing reliance on non-renewable resources.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.9992012735098085, 'A': 4.58117913177909e-05, 'F': 5.9548790616357545e-05, 'B': 0.00046950475633729996, 'J': 0.0002238611519199174}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007987264901915259}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 315:
  We engage in the production of roundwood and firewood, catering to both domestic and commercial markets. Our logging practices are designed to be environmentally responsible, utilizing selective harvesting methods that promote forest regeneration. The firewood we supply is sourced from sustainably managed forests, ensuring that our customers receive a product that aligns with their values of sustainability. Additionally, we are exploring innovative ways to convert forest residues into energy, further enhancing our contribution to renewable energy solutions.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.007477155536880843, 'A': 0.01020295782769254, 'F': 0.0018828327473518474, 'B': 0.9797459561102785, 'J': 0.0006910977777962523}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.020254043889721518}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 316:
  Engaging in freshwater fishing, our business operates on several lakes and rivers, employing both traditional and modern fishing techniques. We utilize eco-friendly nets and traps to minimize bycatch and protect local ecosystems. Our team is dedicated to promoting responsible fishing practices, and we conduct educational workshops for local communities on sustainable harvesting methods. The fish caught are processed in our facility, where we focus on quality and freshness, supplying local markets and restaurants with a range of freshwater species. Moreover, we offer guided fishing tours, providing enthusiasts with an immersive experience while fostering appreciation for aquatic environments.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 3.342086696533203e-05, 'A': 0.9996751986246136, 'F': 0.00010267570261820132, 'B': 0.0001541854640025328, 'J': 3.4519341800161815e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003248013753863743}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 40%|██████████████████████████████████████████████████████████████████████▌                                                                                                        | 318/788 [00:19<00:28, 16.41it/s]

RAPS scores:

==================================================
Description 317:
  Dedicated to the mining of tin ores, our company plays a vital role in supplying this essential metal for electronics and soldering applications. We employ advanced mining techniques that optimize ore recovery and reduce environmental impact. Our operations are supported by a robust quality assurance program to ensure that our products meet the highest industry standards. Committed to sustainability, we implement responsible mining practices, including waste reduction and habitat restoration. Through ongoing research and development, we strive to innovate our processes and expand our market reach, ensuring a steady supply of tin for various industries.1. Our company specializes in the extraction and processing of uranium and thorium ores, providing essential materials for the nuclear energy sector. We operate several mining sites equipped with advanced technologies that ensure efficient ore recovery while minimizing environmental impact. Through rigorous safety protocols and sustainable practices, we aim to deliver high-quality uranium and thorium products to our clients. Additionally, we invest in research and development initiatives to innovate extraction methods and enhance ore processing techniques, ensuring our operations remain at the forefront of the industry.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.563970893474667e-05, 'A': 3.414260538455129e-05, 'F': 1.233859589811073e-05, 'B': 0.9998907237254789, 'J': 7.155364303603236e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4479754088719085e-06, 6: 1.6201831662768793e-06, 7: 0.9999959318414248}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03521770156842583, 7.2: 0.9647822984315741}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 318:
  We engage in the sustainable collection of mosses and lichens, sourcing these unique materials from pristine environments. Our team is trained to identify and harvest only the species that can be sustainably managed, ensuring that our practices do not disrupt local ecosystems. The collected mosses and lichens are processed for use in decorative crafts, horticulture, and natural dyes. By promoting the aesthetic and ecological benefits of these materials, we cater to a growing market of consumers interested in sustainable and natural home decor solutions.1. Our company specializes in the sustainable gathering of wild-growing mushrooms and truffles, sourcing these gourmet ingredients from pristine forests. We have established partnerships with local foragers who are trained in sustainable harvesting practices, ensuring that our collection methods do not harm the ecosystem. Our products are then carefully processed and packaged for both retail and wholesale markets, catering to high-end restaurants and specialty food stores. By prioritizing quality and sustainability, we aim to provide our customers with unique flavors while supporting local communities and preserving biodiversity.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.06763087540994543, 'A': 0.08001827353944584, 'F': 0.042652044411800295, 'B': 0.8041344340989678, 'J': 0.005564372539840649}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1958655659010322}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 319:
  We focus on the production of roundwood for energy applications, sourcing timber from sustainably managed forests. Our operations include the gathering of forest residues and the processing of these materials into biomass fuel. We provide a reliable supply of wood chips and pellets that serve as renewable energy sources for heating and power generation. By investing in modern processing technologies, we ensure that our products meet stringent quality standards, helping customers transition to greener energy solutions while reducing their carbon footprint.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.999575015863347, 'A': 2.5419015790553715e-05, 'F': 3.0439737426940266e-05, 'B': 0.00020855780233556474, 'J': 0.00016056758109982892}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00042498413665303936}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 320:
  Our company is dedicated to the mining and processing of hard coal, utilizing a blend of traditional and modern techniques. We focus on both underground and surface mining operations, ensuring that we can access coal deposits efficiently. Our state-of-the-art facilities are equipped for cleaning, sizing, and grading coal, allowing us to produce high-quality products that meet the diverse needs of our customers. By investing in technology and sustainable practices, we aim to enhance our operational efficiency and reduce our environmental impact while delivering reliable coal supplies.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5195533795577655e-05, 'A': 3.4193917216337566e-05, 'F': 1.2327953570713337e-05, 'B': 0.9998911417908178, 'J': 7.140804599528105e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957218906779, 6: 1.3320710071841396e-06, 7: 2.9460383147411167e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975282193924697, 5.2: 0.002471780607530301}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 41%|███████████████████████████████████████████████████████████████████████▋                                                                                                       | 323/788 [00:20<00:31, 14.61it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 321:
  Our company is at the forefront of natural gas extraction, employing innovative techniques such as advanced drilling and real-time monitoring systems. We specialize in the separation of liquid hydrocarbon fractions, which not only enhances the efficiency of our operations but also adds significant value to our product offerings. Our gas desulphurization capabilities are designed to reduce sulfur content, ensuring compliance with environmental regulations while delivering cleaner energy solutions. By leveraging technology and expertise, we aim to optimize our production processes and contribute to a sustainable energy future.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.495516724092802e-05, 'A': 3.46643430349003e-05, 'F': 1.2455085366462192e-05, 'B': 0.9998907075417774, 'J': 7.217862580295096e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7690045391635108e-06, 6: 0.9999964309472807, 7: 1.8000481799196517e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979589215628835, 6.1: 0.0020410784371166133}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 322:
  We focus on the cultivation and processing of various non-perennial crops, including sunflowers and canola, which are essential for the production of cooking oils. Our farms employ innovative agronomic practices that enhance crop resilience and yield, while our processing facilities are equipped with the latest technology to ensure high-quality oil extraction. We prioritize sustainability by utilizing waste products as animal feed and engaging in practices that improve soil health. Our commitment to transparency and quality allows us to build strong relationships with consumers who value responsibly sourced products.1. Our company specializes in the cultivation of a diverse range of cereals, including barley, oats, and corn, aimed at both local and international markets. We employ advanced agricultural techniques, such as precision farming and crop rotation, to enhance yield and sustainability. Our state-of-the-art irrigation systems ensure optimal water usage, while our commitment to organic farming practices allows us to meet the growing demand for healthy food options. Additionally, we engage in seed production, providing high-quality seeds that are resilient to climate change, thus supporting farmers in maximizing their productivity.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.4432582369717492, 'A': 0.0065237018693174425, 'F': 0.012170368707228249, 'B': 0.5346085244934257, 'J': 0.0034391679582794253}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.46539147550657434}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 323:
  Our firm is dedicated to the mining of rare earth elements, which are critical for the production of high-tech devices and renewable energy solutions. We utilize advanced geological surveying techniques to identify and extract these valuable ores with precision. Our facilities are equipped with sophisticated separation technologies that enable us to refine rare earth metals to the highest standards. We prioritize sustainability by implementing eco-friendly practices throughout our operations, including land reclamation and energy-efficient processing methods. Through strategic partnerships with technology companies, we strive to create value by supplying essential materials that drive innovation in electronics and green technologies.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.637844655762021e-05, 'A': 3.391769826041202e-05, 'F': 1.2320890496915762e-05, 'B': 0.9998902507197848, 'J': 7.132244900293213e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010974928021523223}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 42%|████████████████████████████████████████████████████████████████████████▊                                                                                                      | 328/788 [00:20<00:24, 18.53it/s]

RAPS scores:

==================================================
Description 324:
  We focus on the sustainable cultivation of timber through comprehensive forest management practices. Our activities include the careful planning of planting cycles, as well as the implementation of thinning strategies to enhance the growth of remaining trees. We are committed to maintaining the ecological balance of our forested areas, ensuring that our operations do not compromise the health of the ecosystem. Our dedication to sustainability is reflected in our partnerships with environmental organizations, where we collaborate on initiatives aimed at preserving biodiversity and promoting responsible forestry practices. Through these efforts, we aim to create a lasting positive impact on both the environment and the communities we serve.1. Our company specializes in the sustainable management of forest resources, focusing on the planting and replanting of timber species to ensure a continuous supply of high-quality wood. We operate extensive tree nurseries that cultivate a variety of seedlings, including hardwood and softwood species, tailored to meet the specific needs of our clients. By implementing advanced silvicultural practices, we enhance forest health and productivity, fostering biodiversity while also contributing to carbon sequestration efforts. Our commitment to responsible forestry ensures that we not only meet market demands but also preserve the ecological integrity of the forests we manage.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 6.958135185366984e-05, 'A': 0.9991873842548924, 'F': 0.0003703522456274329, 'B': 0.00030508213739998313, 'J': 6.760001022653101e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008126157451076033}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 325:
  We have developed a comprehensive aquaculture operation that focuses on the rearing of juvenile fish species for restocking purposes. Our hatcheries utilize cutting-edge technology to ensure high survival rates and rapid growth, producing healthy fingerlings for both recreational and commercial fisheries. We collaborate with local governments and environmental organizations to support conservation efforts, helping to restore fish populations in natural habitats. Our commitment to sustainability is reflected in our practices, which prioritize ecological balance and the health of aquatic ecosystems.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 8.007695766156067e-05, 'A': 0.99904832972658, 'F': 0.00035124302980072254, 'B': 0.0004448621329586987, 'J': 7.548815299892097e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009516702734200244}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 326:
  We engage in the sustainable gathering of mosses and lichens, which are increasingly sought after for their decorative and ecological applications. Our harvesting practices are designed to minimize environmental impact, and we work closely with ecologists to ensure that our activities do not disrupt local ecosystems. Our products are supplied to craft stores and landscape designers, who appreciate the natural beauty and unique characteristics of mosses and lichens. Through our commitment to sustainability, we aim to raise awareness about the importance of preserving these unique natural resources.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.00963393406002365, 'A': 0.07425163105295943, 'F': 0.010883455370065215, 'B': 0.9035028590965749, 'J': 0.0017281204203766266}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0964971409034251}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 327:
  Our business model centers around the efficient extraction of crude petroleum, leveraging innovative drilling technologies and data analytics to optimize production. We operate in diverse geographical regions, allowing us to tap into various oil reserves while mitigating risks associated with market fluctuations. Our commitment to reducing our carbon footprint is evident in our adoption of renewable energy sources to power our operations, demonstrating our dedication to a sustainable future while meeting the energy demands of today.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4701803751999185e-05, 'A': 3.495242342036145e-05, 'F': 1.2498088370601856e-05, 'B': 0.9998905897359558, 'J': 7.2579485013947555e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001094102640442074}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 328:
  We specialize in the cultivation of live plants for both ornamental and agricultural purposes, focusing on high-quality seedlings and cuttings. Our nursery employs advanced propagation techniques, including hydroponics and aeroponics, to optimize growth and yield. We are committed to sustainable practices, using organic fertilizers and pest management strategies to ensure the health of our plants and the environment. Our extensive product range includes flowering plants, shrubs, and turf grasses, which are supplied to landscapers, garden centers, and individual customers. We also provide expert advice and support to help our clients achieve their gardening goals.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.5883107241967414, 'A': 0.022787582167859203, 'F': 0.28871695327792835, 'B': 0.08371925551758523, 'J': 0.016465484839885802}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.41168927580325865}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 329:
  We are dedicated to the growth of tropical and subtropical fruits, including mangoes, papayas, and avocados, which thrive in our warm climate. Our innovative farming methods incorporate precision agriculture technology, enabling us to monitor crop health and optimize yields. We focus on organic cultivation, minimizing chemical inputs to deliver fresh, nutritious fruits to local and international markets. Our commitment to sustainability also extends to packaging, where we use biodegradable materials to reduce our environmental footprint while enhancing the consumer experience.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.06493763772830459, 'A': 0.055719597880188924, 'F': 0.03234732163560759, 'B': 0.8427725607717357, 'J': 0.004222881984163157}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15722743922826432}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 42%|█████████████████████████████████████████████████████████████████████████▌                                                                                                     | 331/788 [00:20<00:29, 15.75it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 330:
  Our operations are centered on the mining of silver ores, where we employ innovative extraction and processing techniques to produce high-purity silver for various applications. We utilize advanced technologies such as flotation and leaching to maximize recovery rates while minimizing environmental impact. Our commitment to sustainability includes implementing water conservation practices and reducing emissions in our processing facilities. Furthermore, we actively engage in research to explore new uses for silver, particularly in the fields of electronics and renewable energy, enhancing its value in a rapidly evolving market.1. Our company specializes in the extraction and processing of uranium ores, leveraging advanced technologies to ensure efficient and sustainable mining practices. We focus on implementing innovative methods to minimize environmental impact while maximizing yield. Our operations include extensive geological surveys and the use of state-of-the-art equipment for ore extraction. Additionally, we invest in research to enhance ore processing techniques, allowing us to produce high-purity uranium products for the nuclear energy sector. Our commitment to safety and regulatory compliance ensures that we meet industry standards while contributing to the global energy supply.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.547061020760197e-05, 'A': 3.4115833488699494e-05, 'F': 1.2322182657087548e-05, 'B': 0.9998909317774993, 'J': 7.159596147432485e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.454825294478894e-06, 6: 1.6027153426228173e-06, 7: 0.999995942459363}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03515412881644036, 7.2: 0.9648458711835596}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 331:
  We engage in the farming of alligators and crocodiles, focusing on both meat production and leather goods. Our facilities are designed to replicate natural habitats, providing optimal conditions for growth and breeding. We adhere to strict welfare standards and environmental regulations, ensuring our practices are humane and sustainable. The harvested products are processed into high-quality leather and gourmet meat, which are marketed to luxury brands and high-end restaurants. Our commitment to conservation also includes educational outreach programs to raise awareness about the importance of these species and their ecosystems.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.006459392795960281, 'A': 0.8843837449162945, 'F': 0.015069673297664612, 'B': 0.09170116445079644, 'J': 0.0023860245392842544}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11561625508370554}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 332:
  We specialize in the growing of fiber crops, such as cotton and flax, which are essential raw materials for the textile industry. Our operations emphasize sustainable farming techniques, including reduced water usage and organic pest control methods, to ensure minimal environmental impact. Through partnerships with textile manufacturers, we provide high-quality fibers that meet stringent industry standards. Our commitment to ethical sourcing includes supporting fair labor practices and promoting economic development in farming communities, ensuring that our fiber production contributes positively to both the environment and society.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9815278656057931, 'A': 0.0005368024810600505, 'F': 0.001135572606808732, 'B': 0.01578981574602328, 'J': 0.0010099435603149784}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01847213439420692}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 43%|██████████████████████████████████████████████████████████████████████████▊                                                                                                    | 337/788 [00:20<00:24, 18.08it/s]

RAPS scores:

==================================================
Description 333:
  We are involved in the production of utility poles from sustainably sourced roundwood. Our operations ensure that each pole meets industry standards for strength and durability, making them suitable for a variety of applications, including electrical and telecommunications infrastructure. By focusing on sustainable harvesting practices, we minimize our environmental footprint while providing essential materials that support modern connectivity. Our commitment to quality and sustainability has made us a trusted supplier in the industry.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997366830304956, 'A': 1.5153356374651291e-05, 'F': 1.848202686545994e-05, 'B': 8.567500060681383e-05, 'J': 0.00014400658565762647}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002633169695044346}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 334:
  Our core business activities involve the extraction and production of natural gas, supported by advanced technologies that enhance our operational efficiency. We focus on the draining and separation of liquid hydrocarbon fractions, which are critical for maximizing the value of our natural gas output. Our commitment to gas desulphurization ensures that our products are environmentally compliant and meet the needs of our clients. By prioritizing innovation and sustainability, we aim to provide reliable energy solutions while minimizing our ecological impact.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.5297364319419206e-05, 'A': 3.4354853189587214e-05, 'F': 1.2380818015618694e-05, 'B': 0.9998907755576798, 'J': 7.191406795683344e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7829512290542858e-06, 6: 0.999996403865996, 7: 1.8131827749558143e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979690307853442, 6.1: 0.0020309692146557577}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 335:
  Our business is dedicated to the sustainable harvesting of wild nuts, particularly focusing on indigenous species that are often overlooked in commercial markets. We work closely with local farmers and indigenous communities to gather these nuts, ensuring that our practices support local economies and ecosystems. Our products are sold in bulk to health food stores and snack manufacturers, where they are valued for their unique flavors and nutritional benefits. We also engage in educational outreach to promote the importance of preserving these native species.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.00025651956879069296, 'A': 0.9961426290781542, 'F': 0.0008137303327721754, 'B': 0.002595301520613133, 'J': 0.00019181949966971313}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003857370921845793}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 336:
  Our company specializes in the collection of eelgrass from coastal ecosystems, focusing on sustainable harvesting methods that protect marine habitats. The harvested eelgrass is processed into various products, including biodegradable packaging and eco-friendly textiles. By highlighting the environmental benefits of eelgrass, such as its role in carbon sequestration and habitat restoration, we position ourselves as leaders in the sustainable materials industry, appealing to brands looking to reduce their environmental impact.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 1.5253787485839798e-05, 'A': 0.9998688973362327, 'F': 5.2806376732524214e-05, 'B': 4.597883095299477e-05, 'J': 1.706366859600255e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00013110266376725743}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 43%|███████████████████████████████████████████████████████████████████████████▎                                                                                                   | 339/788 [00:21<00:26, 16.92it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 337:
  Engaged in the mining of zinc ores, our company employs a combination of underground and surface mining techniques to optimize resource extraction. We focus on implementing best practices in ore processing, utilizing flotation and hydrometallurgical methods to produce high-quality zinc concentrates. Our commitment to sustainability is reflected in our initiatives to reduce emissions and manage waste effectively. We also invest in research to develop new technologies that enhance the efficiency of our operations, ensuring that we remain competitive while contributing positively to the environment and local communities.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.504066668590346e-05, 'A': 3.4489525257357575e-05, 'F': 1.237557273523792e-05, 'B': 0.9998909321448382, 'J': 7.162090483325191e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4672939774018398e-06, 6: 1.5862494948935646e-06, 7: 0.9999959464565278}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03513200611685403, 7.2: 0.964867993883146}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 338:
  We are committed to the sustainable gathering of cork from Mediterranean cork oak forests. Our harvesting process is designed to protect the trees and promote their longevity, allowing us to collect cork every nine years without harming the ecosystem. The cork we produce is utilized in a variety of applications, from wine stoppers to flooring materials. We emphasize the environmental benefits of cork, such as carbon sequestration and habitat preservation, and work to educate consumers about the importance of choosing sustainable materials in their purchases.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.6020751759318445, 'A': 0.006525266478898351, 'F': 0.013379862115548438, 'B': 0.37378715774908133, 'J': 0.004232537724627424}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.39792482406815555}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 339:
  Engaged in the cultivation of melons and other fruits, our company emphasizes organic farming practices that promote biodiversity and soil health. We utilize integrated pest management techniques to minimize chemical use while ensuring high-quality yields. Our products are sold through various channels, including grocery stores and online platforms, catering to health-conscious consumers. We also invest in local community initiatives, supporting farmers in adopting sustainable practices that enhance their livelihoods and contribute to the local economy.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.017840000943831303, 'A': 0.5631800412875, 'F': 0.033515195365764916, 'B': 0.3812223864810338, 'J': 0.004242375921870066}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4368199587125}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 43%|███████████████████████████████████████████████████████████████████████████▋                                                                                                   | 341/788 [00:21<00:27, 16.07it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 340:
  This firm specializes in the cultivation and harvesting of aquatic plants, such as seaweed and kelp, from both coastal and offshore waters. Utilizing sustainable farming techniques, they have developed a unique system that promotes biodiversity while maximizing yield. The harvested plants are processed into a variety of products, including food additives, cosmetics, and nutritional supplements. By collaborating with research institutions, the company is at the forefront of developing innovative applications for seaweed, contributing to both environmental sustainability and the growing demand for plant-based products in various industries.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.0605519536733971e-05, 'A': 0.9999074112967482, 'F': 4.07620585369911e-05, 'B': 2.83718154956016e-05, 'J': 1.2849309682509225e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.000729838935322711, 2: 0.000937140456838319, 3: 0.998333020607839}}
Class sets: {'3': ['3.2']}
Class probs: {'3': {3.1: 0.4626863274755597, 3.2: 0.5373136725244403}}
Final output: {'type': 'class_level', 'codes': ['3.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True

RAPS scores:

==================================================
Description 341:
  Engaged in the cultivation of sugar cane, our company employs innovative agricultural techniques to enhance productivity and sustainability. We focus on optimizing growth cycles through efficient water management and soil health practices, which not only increase yields but also reduce our carbon footprint. Our processing facilities are equipped with cutting-edge technology that allows us to extract sugar and produce bioenergy from by-products, contributing to a circular economy. By collaborating with local communities, we aim to create economic opportunities while promoting responsible farming practices that benefit both farmers and the environment.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.005886639865785065, 'A': 0.002608131320259417, 'F': 0.0010188790779452545, 'B': 0.9901533088282876, 'J': 0.00033304090772256757}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00984669117171244}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 342:
  We focus on the collection of vegetable hair, which is utilized in the production of brushes and other cleaning tools. Our harvesting practices are designed to be sustainable, ensuring that we do not deplete natural resources while meeting the growing demand for eco-friendly products. The vegetable hair is processed and transformed into high-quality brushes that appeal to both consumers and professionals. We emphasize the importance of using natural materials in our products, aligning with the increasing consumer preference for sustainable and biodegradable options.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9997168469832356, 'A': 1.6484463424722564e-05, 'F': 2.097117947525416e-05, 'B': 9.934349536880296e-05, 'J': 0.00014635387849542574}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00028315301676440363}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 44%|████████████████████████████████████████████████████████████████████████████▊                                                                                                  | 346/788 [00:21<00:28, 15.29it/s]

RAPS scores:

==================================================
Description 343:
  Our company is involved in the mining of tungsten ores, supplying this critical metal for various applications, including electronics and defense. We utilize advanced mining and processing technologies to ensure the efficient extraction of tungsten while adhering to strict environmental standards. Our commitment to sustainability is reflected in our efforts to minimize waste and rehabilitate mining sites. We collaborate with industry partners to develop innovative solutions that enhance the performance of tungsten in high-tech applications. By providing high-quality tungsten, we support advancements in technology and contribute to the growth of key industries.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5620418947096395e-05, 'A': 3.4168860437172476e-05, 'F': 1.2329318474492634e-05, 'B': 0.9998907488152884, 'J': 7.132586852897794e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.49673057380972e-06, 6: 1.5778825651968237e-06, 7: 0.9999959253868609}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0352460006751572, 7.2: 0.9647539993248427}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 344:
  We have established a robust warehousing and storage system for lignite, designed to maintain product integrity and optimize logistics. Our facilities are equipped with advanced monitoring systems that ensure optimal conditions for lignite storage, preventing degradation and ensuring quality. By strategically locating our warehouses near transportation hubs, we streamline the distribution process, reducing lead times for our customers. This logistical efficiency not only enhances our service offerings but also positions us as a reliable partner in the energy supply chain.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9970358086375021, 'A': 7.358487528204638e-05, 'F': 7.860206769491644e-05, 'B': 0.002481401667645867, 'J': 0.00033060275187519534}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0029641913624979255}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 345:
  Our organization is dedicated to the mining and processing of iron ore, providing essential raw materials for the steel industry. We employ a combination of open-pit and underground mining methods to access rich ore deposits. Our beneficiation plants utilize innovative technologies, such as hydrocyclones and spiral separators, to enhance ore quality. Additionally, we focus on reducing waste and improving energy efficiency throughout our operations. By offering a reliable supply of high-quality iron ore, we support our clients in their production processes while fostering sustainable mining practices.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.508033364676737e-05, 'A': 3.433127445115634e-05, 'F': 1.2335567901909324e-05, 'B': 0.999891094631394, 'J': 7.158192605968924e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4493362344345257e-06, 6: 1.6286050471098593e-06, 7: 0.9999959220587186}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677957834007335, 7.2: 0.03220421659926646}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 346:
  Our business model revolves around the extraction of crude petroleum, where we utilize a fleet of advanced drilling rigs equipped with the latest technology. We focus on both offshore and onshore fields, employing geologists and engineers to assess potential sites for oil deposits. Our commitment to safety is paramount, with comprehensive training programs in place for all employees. We also engage in community outreach initiatives, ensuring that local stakeholders are informed and involved in our operations. By optimizing our supply chain logistics, we enhance the efficiency of transporting crude oil to refineries.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.498552852467181e-05, 'A': 3.500603179493006e-05, 'F': 1.2588201575795532e-05, 'B': 0.9998901360468607, 'J': 7.284191244095463e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010986395313927755}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 44%|█████████████████████████████████████████████████████████████████████████████▌                                                                                                 | 349/788 [00:21<00:28, 15.62it/s]

RAPS scores:

==================================================
Description 347:
  Our business is centered around the collection of balsams, which are highly sought after for their aromatic properties and therapeutic benefits. We work with skilled gatherers who understand the delicate balance of harvesting these resins without harming the trees. Our balsams are used in a variety of products, including essential oils, perfumes, and natural remedies. By emphasizing the sustainable aspects of our sourcing practices, we attract a customer base that values natural and holistic products, enhancing our brand's reputation in the wellness industry.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9499467326992767, 'A': 0.0010503267344561982, 'F': 0.0026422208198776088, 'B': 0.0446380354025922, 'J': 0.0017226843437973896}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05005326730072335}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 348:
  Our company is at the forefront of lignite mining, utilizing both traditional and innovative extraction techniques to maximize resource recovery. We conduct extensive geological assessments to identify optimal mining locations, followed by the implementation of liquefaction methods that enhance extraction efficiency. Once mined, our lignite undergoes thorough washing and dehydration to improve its quality, followed by pulverization for easier transport and storage. This integrated approach ensures that we provide high-quality lignite to meet the demands of our industrial customers.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4950007318471046e-05, 'A': 3.4514587384215765e-05, 'F': 1.2396345089284322e-05, 'B': 0.9998909851337294, 'J': 7.153926478567993e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957333345535, 6: 1.3422567839094693e-06, 7: 2.9244086626779823e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023549054273749206, 5.2: 0.9976450945726251}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 349:
  Our enterprise is committed to the raising of poultry, particularly broilers and layers, using cutting-edge technology to enhance production efficiency. We implement climate-controlled housing systems that ensure optimal living conditions for our birds, significantly improving their growth rates and egg-laying capabilities. Our operations also include a comprehensive feed management program that utilizes locally sourced grains and supplements to promote healthy development. By integrating data analytics into our farming practices, we can monitor flock health in real-time, allowing for proactive management and reduced mortality rates. Our poultry products are distributed to major grocery chains, ensuring freshness and quality for consumers.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.03603479974754064, 'A': 0.213669172382972, 'F': 0.058614562593803356, 'B': 0.6865540076067231, 'J': 0.005127457668960887}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.31344599239327686}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 350:
  We are committed to producing a diverse array of live plants for ornamental purposes, specializing in unique and hard-to-find varieties. Our propagation techniques include both traditional methods and innovative tissue culture practices, allowing us to maintain genetic diversity and produce disease-resistant plants. Our knowledgeable staff is always available to assist customers in selecting the right plants for their specific needs, whether for home gardens or large-scale landscaping projects. We pride ourselves on our exceptional customer service and our ability to provide tailored solutions for every client.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9456113286818633, 'A': 0.0033013039661761857, 'F': 0.029930202749939103, 'B': 0.011953163425074692, 'J': 0.009204001176946836}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05438867131813674}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 45%|██████████████████████████████████████████████████████████████████████████████▏                                                                                                | 352/788 [00:21<00:24, 17.95it/s]

RAPS scores:

==================================================
Description 351:
  Our operations focus on the raising of poultry, specifically broilers, where we utilize cutting-edge breeding techniques to enhance growth efficiency and disease resistance. We maintain a biosecure environment that minimizes the risk of infection, ensuring the health of our flocks. Our farms are equipped with automated feeding and watering systems that optimize resource use and reduce waste. We also prioritize the use of non-GMO feed to align with consumer preferences for natural products. By partnering with local processors, we ensure that our poultry reaches the market quickly, providing fresh, high-quality meat to consumers while supporting regional economies.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.03323782680035029, 'A': 0.4207746196376585, 'F': 0.1275814884068092, 'B': 0.4117981157915092, 'J': 0.006607949363672737}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5792253803623415}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 352:
  Our business model revolves around the efficient extraction and processing of hard coal, employing both underground and surface mining methods. We have invested heavily in liquefaction technologies that enhance our mining capabilities while minimizing environmental impact. Our facilities are equipped with advanced cleaning and grading systems that ensure the coal we produce meets the highest quality standards. By focusing on pulverizing and compressing coal, we facilitate better transport and storage solutions for our clients, thereby enhancing the overall value proposition of our offerings.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.490714018846982e-05, 'A': 3.440177837553209e-05, 'F': 1.2366635513661837e-05, 'B': 0.9998911516462005, 'J': 7.172799721883674e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995722542969, 6: 1.323637209611019e-06, 7: 2.953819821363959e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975288718331077, 5.2: 0.002471128166892327}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 45%|██████████████████████████████████████████████████████████████████████████████▌                                                                                                | 354/788 [00:22<00:33, 13.03it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 353:
  In the lignite mining sector, our company is dedicated to maximizing efficiency and sustainability. We utilize advanced extraction techniques, including liquefaction methods, to enhance the quality of our lignite. Our processing facilities are equipped with state-of-the-art washing and dehydrating technologies, which improve the product's calorific value. We also prioritize effective logistics solutions, including warehousing and transportation, to ensure timely delivery to our clients. Our holistic approach to lignite mining positions us as a reliable partner in the energy supply chain.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques. Utilizing advanced machinery and environmentally responsible practices, we ensure efficient extraction while minimizing ecological impact. Our operations are complemented by state-of-the-art washing and dehydrating facilities that enhance the quality of the lignite, making it suitable for various industrial applications. We focus on maintaining high safety standards and implementing innovative technologies to optimize our mining processes, ultimately delivering high-quality lignite to our customers.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.5136343279355044e-05, 'A': 3.435408522903923e-05, 'F': 1.23780280967261e-05, 'B': 0.9998909520725022, 'J': 7.1794708926145575e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995735835058, 6: 1.344713578304412e-06, 7: 2.9194513638408018e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023575069882259127, 5.2: 0.997642493011774}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 354:
  We are engaged in the mining and beneficiation of iron ores, with a strong emphasis on technological advancement and sustainability. Our extraction methods are complemented by a robust research and development program aimed at improving ore recovery rates and reducing waste. We employ a variety of beneficiation techniques, including magnetic separation and pelletizing, to convert raw ore into high-quality iron pellets suitable for steel production. Our focus on continuous improvement ensures that we remain competitive in a rapidly evolving market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.558085883815397e-05, 'A': 3.3975111772611903e-05, 'F': 1.2280557765439888e-05, 'B': 0.9998910428461434, 'J': 7.120625480436069e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.468437204256546e-06, 6: 1.5872111453466045e-06, 7: 0.9999959443516504}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677805987821735, 7.2: 0.03221940121782658}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 45%|███████████████████████████████████████████████████████████████████████████████▌                                                                                               | 358/788 [00:22<00:32, 13.29it/s]

RAPS scores:

==================================================
Description 355:
  Dedicated to the raising of camels, our farm focuses on the unique benefits these animals provide in arid environments. We utilize sustainable grazing practices to ensure the health of our camels while promoting biodiversity in our pastures. Our breeding program emphasizes traits such as endurance and adaptability, making our camels suitable for both transportation and dairy production. We also engage in research to explore the nutritional properties of camel milk, which is gaining popularity for its health benefits. By promoting the use of camels in sustainable agriculture, we aim to enhance the livelihoods of communities in desert regions.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00047263868109763207, 'A': 0.9904474313630058, 'F': 0.0025911492387419035, 'B': 0.0061476209058416555, 'J': 0.00034115981131293833}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.009552568636994163}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 356:
  Engaged in the extraction of crude petroleum, we utilize a combination of advanced geological surveying and drilling technologies to uncover and tap into oil reserves. Our operations are supported by a robust supply chain that ensures the timely delivery of equipment and materials necessary for drilling activities. We focus on optimizing production through the implementation of real-time monitoring systems that track extraction processes and enhance decision-making. Our commitment to innovation drives us to explore alternative energy sources, positioning us as a leader in the transition towards more sustainable energy solutions while maintaining our core crude oil extraction business.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4692965051906224e-05, 'A': 3.4652966472491114e-05, 'F': 1.2434251517763444e-05, 'B': 0.9998910023772924, 'J': 7.217439665482475e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7677514704758497e-06, 6: 0.9999964131778313, 7: 1.8190706983553368e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020546526665001616, 6.1: 0.9979453473334998}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 357:
  Our company is at the forefront of reforestation efforts, specializing in the planting of diverse tree species to restore degraded landscapes. We collaborate with local communities and environmental organizations to identify areas in need of restoration and develop tailored planting strategies. Our focus on biodiversity ensures that the new forests are resilient and capable of withstanding environmental stresses. Through these initiatives, we not only contribute to the restoration of ecosystems but also create job opportunities and foster community engagement in sustainable forestry practices.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.615483363843386e-05, 'A': 0.9986628500797442, 'F': 0.0011165645729153486, 'B': 0.00011361426535388302, 'J': 6.0816248348049965e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001337149920255798}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 46%|████████████████████████████████████████████████████████████████████████████████▏                                                                                              | 361/788 [00:22<00:31, 13.72it/s]

RAPS scores:

==================================================
Description 358:
  We are committed to advancing aquaculture practices through research and innovation, particularly in the area of biosecurity. Our team conducts extensive studies on disease management and prevention strategies for farmed aquatic organisms. By developing and implementing best practices for biosecurity, we help farmers mitigate risks associated with disease outbreaks, ensuring the health of their stock and the sustainability of their operations. Our focus on education and training empowers aquaculture producers to adopt these practices, ultimately contributing to a more resilient industry.1. Our company specializes in the cultivation of premium salmon in state-of-the-art marine farms located along the coastlines. Utilizing advanced aquaculture techniques, we implement sustainable feeding practices and environmental monitoring to ensure optimal growth conditions for our fish. Our facilities are equipped with cutting-edge technology that allows for real-time tracking of water quality and fish health, enabling us to respond swiftly to any changes. We pride ourselves on our commitment to sustainability, employing practices that minimize ecological impact while maximizing yield. Our products are distributed to top-tier retailers and restaurants, ensuring that consumers enjoy the freshest seafood available.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00014306996709294642, 'A': 0.9983606861694402, 'F': 0.00055112067081705, 'B': 0.0008237984033998127, 'J': 0.00012132478925002049}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0016393138305598187}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 359:
  In the realm of crustacean harvesting, our company focuses on the sustainable collection of species such as lobsters and shrimp. We utilize traps that are designed to minimize bycatch and ensure the safety of juvenile specimens, allowing them to grow to maturity. Our operations are complemented by a robust supply chain that emphasizes freshness and quality, with direct distribution to seafood markets and restaurants. We also engage in community education initiatives, teaching local fishermen about sustainable practices and the importance of protecting marine habitats. Our commitment to ethical harvesting practices sets a standard in the industry.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00965354013816847, 'A': 0.6241655070235139, 'F': 0.012529042701958903, 'B': 0.3506286744756893, 'J': 0.003023235660669451}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3758344929764861}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 360:
  Our company is at the forefront of hard coal mining, employing both traditional and modern extraction methods to deliver high-quality products. We focus on the entire process, from mining to processing, ensuring our coal is cleaned, sized, and graded to meet specific customer requirements. Our advanced facilities utilize cutting-edge pulverizing technology to produce finely graded coal, which is essential for various industrial applications. By optimizing our transport and storage solutions, we ensure timely delivery and reliability for our clients in the energy sector.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.506765686694416e-05, 'A': 3.4307517452904515e-05, 'F': 1.2353403612947426e-05, 'B': 0.9998911105340458, 'J': 7.160888021374932e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957174658618, 6: 1.3304364140656554e-06, 7: 2.952097724006066e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975281899992078, 5.2: 0.0024718100007923554}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 361:
  We are committed to the responsible production of roundwood, focusing on both quality and sustainability. Our logging operations employ state-of-the-art equipment that enhances efficiency while reducing waste. We provide a range of products, from untreated logs for construction to firewood for residential heating. Our team works closely with forestry experts to implement best practices in forest management, ensuring that our harvesting methods support long-term forest health. Furthermore, we engage in community outreach to educate stakeholders about the importance of sustainable forestry and energy production from wood residues.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0037430838201167717, 'A': 0.0006502989023303698, 'F': 0.0002920017206861141, 'B': 0.9951755215017157, 'J': 0.00013909405515112724}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.004824478498284268}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 46%|████████████████████████████████████████████████████████████████████████████████▌                                                                                              | 363/788 [00:22<00:30, 13.74it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 362:
  We specialize in the extraction and processing of natural gas, employing innovative techniques to enhance recovery and minimize environmental impact. Our operations include the draining and separation of liquid hydrocarbon fractions, ensuring that we deliver high-quality products to our clients. We are committed to sustainability, utilizing advanced gas desulphurization processes that reduce emissions and improve the overall quality of our natural gas. Our focus on technological advancement allows us to maintain a competitive edge while contributing positively to the energy landscape.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.526716429636971e-05, 'A': 3.4421461687217734e-05, 'F': 1.2410663454805264e-05, 'B': 0.9998907047798302, 'J': 7.195930731430391e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7779193519528307e-06, 6: 0.9999964097086692, 7: 1.8123719787240025e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.99796416845056, 6.1: 0.00203583154943992}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 363:
  Engaging in coastal fishing activities, our business focuses on the sustainable harvest of finfish species such as snapper and grouper. We utilize a combination of artisanal fishing techniques and modern equipment to ensure that our catch is both plentiful and environmentally responsible. Our fishermen are trained in best practices for reducing bycatch and protecting juvenile fish populations. We also invest in community initiatives that support local fishermen and promote the importance of preserving marine habitats. Our commitment to sustainability is reflected in our certification by various environmental organizations, enhancing our reputation in the seafood market.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0003493086530846129, 'A': 0.9925953664443646, 'F': 0.0007536170387198965, 'B': 0.0060488582756115065, 'J': 0.0002528495882192008}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.007404633555635365}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 364:
  EcoForest Services is dedicated to the comprehensive management of timber tracts, emphasizing both economic viability and ecological integrity. We engage in extensive forest management practices, including planting, thinning, and conservation strategies that enhance forest resilience. Our team conducts regular assessments to monitor growth and health, allowing us to implement adaptive management techniques. By fostering partnerships with local communities, we ensure that our forestry practices provide social and economic benefits, such as job creation and sustainable resource use. Our holistic approach to forestry management not only meets market demands but also supports long-term environmental sustainability.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.064391280731609e-05, 'A': 0.999783468672394, 'F': 0.00010665559164009014, 'B': 6.530231799214183e-05, 'J': 2.3929505166425083e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00021653132760601768}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 47%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                             | 369/788 [00:23<00:26, 16.09it/s]

RAPS scores:

==================================================
Description 365:
  We engage in the growing of various perennial crops, including medicinal herbs and plants used in natural remedies. Our cultivation techniques prioritize organic practices to ensure the sustainability and efficacy of our products. We collaborate with research institutions to explore the therapeutic benefits of our crops, which allows us to develop innovative health products. Our herbs are sold to manufacturers of dietary supplements and natural cosmetics, tapping into the growing market for holistic health solutions. By focusing on quality and research-backed benefits, we position ourselves as a trusted supplier in the health and wellness industry.1. Our company specializes in the cultivation of premium grapes, focusing on both table varieties and those used for wine production. With vineyards strategically located in regions known for their ideal climate and soil conditions, we employ sustainable farming practices to enhance grape quality while minimizing environmental impact. Our state-of-the-art irrigation systems and precision agriculture techniques allow us to monitor crop health and optimize yields. Additionally, we collaborate with local wineries to provide them with high-quality grapes, ensuring a seamless supply chain from vineyard to bottle. This commitment to excellence not only enhances our brand reputation but also contributes to the local economy.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.19387141039902395, 'A': 0.05011085488499773, 'F': 0.056695263440698515, 'B': 0.6917716927588495, 'J': 0.007550778516430262}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.30822830724115047}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 366:
  Our company is engaged in the growing of stone fruits, including cherries, peaches, and plums. We utilize state-of-the-art irrigation systems and soil management practices to ensure high-quality yields. Our commitment to sustainability includes minimizing water usage and promoting biodiversity within our orchards. We have established partnerships with local distributors to deliver fresh stone fruits to consumers, and we are exploring opportunities for processing our fruits into jams and preserves to enhance our product offerings.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.40037634782112896, 'A': 0.009942388919035183, 'F': 0.03382289364473182, 'B': 0.5510975625190273, 'J': 0.004760807096076732}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4489024374809727}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 367:
  In the field of aquaculture, we specialize in the farming of crocodiles, focusing on sustainable practices that ensure the welfare of the animals and the surrounding environment. Our facilities are designed to mimic natural habitats, providing optimal conditions for growth and breeding. We implement strict health monitoring protocols and engage in research to enhance breeding techniques. The harvested crocodiles are utilized for their meat and hides, which are processed and marketed to luxury goods manufacturers. Our commitment to sustainability includes habitat preservation initiatives that support local wildlife and ecosystems.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00011402307054047791, 'A': 0.9986449443081424, 'F': 0.0006262702466428787, 'B': 0.0005114807502320938, 'J': 0.00010328162444214916}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0013550556918575651}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 368:
  We are engaged in the mining and processing of iron ore, utilizing state-of-the-art technology to ensure high efficiency and quality. Our beneficiation processes are designed to maximize the extraction of valuable minerals while minimizing waste. We also focus on the agglomeration of iron ores, producing pellets that are crucial for modern steelmaking. Our approach combines rigorous testing and analysis to maintain high standards of quality control, ensuring that our products meet the demands of our global clientele.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.561298803576482e-05, 'A': 3.3951717004396666e-05, 'F': 1.2287020984597965e-05, 'B': 0.9998910114734644, 'J': 7.136800510745603e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.493951653032801e-06, 6: 1.571240179384167e-06, 7: 0.9999959348081677}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678061032065969, 7.2: 0.03219389679340323}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 48%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                           | 375/788 [00:23<00:20, 20.43it/s]

RAPS scores:

==================================================
Description 369:
  As a prominent grower of bush fruits and nuts, we specialize in blueberries, raspberries, and hazelnuts. Our farms are designed with biodiversity in mind, promoting pollinator health and soil vitality. We implement advanced irrigation techniques and organic pest control measures to enhance crop resilience. Our products are marketed both fresh and processed, with a focus on health-conscious consumers seeking nutritious snacks. By partnering with local food producers, we create value-added products that showcase the versatility of our bush fruits and nuts.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9281312542858031, 'A': 0.002029529210635164, 'F': 0.006323024008535572, 'B': 0.06081033261961528, 'J': 0.0027058598754110463}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07186874571419688}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 370:
  Our operations focus on the cultivation of beverage crops, with a particular emphasis on coffee and tea. We source high-quality seeds and employ sustainable farming methods to produce beans and leaves that are rich in flavor and aroma. Our products undergo rigorous quality control processes before being packaged and distributed to specialty retailers and cafes worldwide. We also prioritize fair trade practices, ensuring that our farmers receive equitable compensation while promoting sustainable agricultural practices in coffee and tea production.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.31343427427240705, 'A': 0.01031085614202815, 'F': 0.014519122538749618, 'B': 0.6577729111710774, 'J': 0.003962835875737756}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3422270888289226}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 371:
  We are dedicated to the propagation of diverse plant species, supplying nurseries and agricultural businesses with premium grafting stock and seedlings. Our innovative approach combines traditional horticultural practices with modern biotechnology, allowing us to produce disease-resistant and high-yield varieties. We operate a fully equipped laboratory for tissue culture propagation, which ensures the genetic integrity of our plants. By focusing on sustainability, we also implement eco-friendly practices in our growing processes, minimizing our environmental footprint while delivering exceptional products to our customers.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.011949501826547332, 'A': 0.12517103757170497, 'F': 0.8463218679282419, 'B': 0.01174000673234743, 'J': 0.004817585941158516}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15367813207175807}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 372:
  Our business is centered on the cultivation of beverage crops, including coffee and tea, which are grown in ideal climates that enhance their unique flavors. We employ sustainable farming practices, such as shade-grown techniques, to preserve the ecosystem while producing high-quality beans and leaves. Our processing facilities are equipped with modern technology to ensure that our products maintain their freshness and flavor during production. We also focus on direct trade relationships with our buyers, ensuring fair compensation for farmers and transparency in the supply chain. Our commitment to quality and ethical sourcing resonates with consumers who value sustainability in their beverage choices.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.04905367202709306, 'A': 0.02123390609814671, 'F': 0.012633287256380023, 'B': 0.9147427338801835, 'J': 0.0023364007381969326}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08525726611981654}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 373:
  Our business is dedicated to the raising of other animals, including rabbits and guinea pigs, primarily for the pet market. We focus on breeding healthy, well-socialized animals that meet the needs of families and pet owners. Our facilities are designed to provide a safe and comfortable environment for the animals, with ample space for exercise and social interaction. We also offer educational resources for new pet owners, emphasizing responsible care and husbandry practices. By participating in local pet expos and community events, we connect with potential customers and promote the benefits of adopting small animals as pets.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 4.4399841996471745e-05, 'A': 0.9992383898128424, 'F': 0.0005501758677745424, 'B': 0.00011340863958230373, 'J': 5.362583780425474e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007616101871575909}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 374:
  Our operations focus on the production of high-quality turf grasses designed for residential and commercial landscaping. We employ precision farming techniques to grow our turf, ensuring that it is robust and resilient. Our research and development team continuously works on improving grass varieties to enhance drought resistance and pest tolerance. Additionally, we provide expert consultation services to landscape architects and contractors, helping them select the best turf solutions for their projects. Our commitment to quality and innovation has positioned us as a leader in the turf production market.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.8779677704438461, 'A': 0.003189593037514613, 'F': 0.006722111008926439, 'B': 0.10904660742190572, 'J': 0.003073918087806955}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.12203222955615389}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 375:
  Our firm is dedicated to the mining and processing of hard coal, focusing on both surface and underground operations. We leverage modern technology to optimize our mining processes, enhancing safety and efficiency. Our coal cleaning facilities employ sophisticated methods to remove contaminants, while our sizing and grading systems ensure that the coal meets stringent quality standards for various applications. By investing in advanced pulverizing equipment, we are able to produce finely milled coal, which is ideal for energy generation and industrial use, thereby adding significant value to our product offerings.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.563834692564079e-05, 'A': 3.4081553969956e-05, 'F': 1.2316791299338903e-05, 'B': 0.9998908014470693, 'J': 7.161860735730329e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957224589321, 6: 1.3189849235254531e-06, 7: 2.958556144232522e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975283516578343, 5.2: 0.002471648342165676}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 376:
  Our business is dedicated to the cultivation of oleaginous fruits, particularly avocados and olives, which are highly sought after for their health benefits and culinary versatility. We employ sustainable farming practices, including water conservation techniques and organic pest management, to maintain the quality of our crops. Our avocados are harvested at peak ripeness and sold fresh to grocery stores and restaurants, while our olives are processed into high-quality oils and tapenades. We also engage in educational initiatives to promote the nutritional benefits of our products, helping consumers make informed choices. This focus on quality and sustainability has established us as a trusted brand in the market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.07126811430474125, 'A': 0.02238938350553391, 'F': 0.01933326192229182, 'B': 0.8840450633391409, 'J': 0.002964176928292007}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1159549366608591}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 48%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                           | 378/788 [00:23<00:25, 16.16it/s]

RAPS scores:

==================================================
Description 377:
  Our organization is dedicated to the mining of hard coal, utilizing innovative extraction techniques that combine the best of both underground and surface methods. We have invested significantly in technology that allows us to liquefy coal for easier handling and transport, thereby improving efficiency. In addition to extraction, we focus on the cleaning and sizing of coal, employing advanced pulverizing and compressing technologies to enhance product quality. By optimizing our processes, we aim to provide our clients with high-grade coal that meets their specific requirements, all while minimizing our ecological footprint.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.530804946198921e-05, 'A': 3.42842217015315e-05, 'F': 1.2362351624367596e-05, 'B': 0.9998908684261286, 'J': 7.176951083575397e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957227236329, 6: 1.3271979427553962e-06, 7: 2.9500784241740865e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975284498235624, 5.2: 0.002471550176437544}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 378:
  We specialize in the support activities for transportation of lignite, ensuring that our mining operations are seamlessly integrated with logistics solutions. Our team works closely with transportation providers to optimize routes and schedules for the delivery of both raw and processed lignite. By leveraging technology and data analytics, we enhance our operational efficiency and reduce costs, which ultimately benefits our customers. Our dedication to reliable transportation solutions reinforces our position as a trusted partner in the lignite supply chain.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques. We utilize advanced drilling and blasting methods to ensure efficient recovery of this vital resource. Our operations are complemented by state-of-the-art equipment that minimizes environmental impact while maximizing yield. We also invest in innovative liquefaction methods to enhance the quality of lignite, making it more suitable for various industrial applications. By adhering to strict safety and environmental regulations, we ensure that our mining practices contribute positively to the communities in which we operate.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.5038960670365574e-05, 'A': 3.4585748387725064e-05, 'F': 1.245610079313759e-05, 'B': 0.9998906921409836, 'J': 7.227049165315313e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957361954608, 6: 1.3486293640285568e-06, 7: 2.915175175381332e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023571498185064868, 5.2: 0.9976428501814936}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 48%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                          | 382/788 [00:23<00:29, 14.00it/s]

RAPS scores:

==================================================
Description 379:
  We specialize in the cultivation of oleaginous fruits, focusing on varieties such as olives and avocados. Our orchards are designed to promote biodiversity and resilience, utilizing organic farming methods that enhance soil health and reduce reliance on synthetic inputs. We produce high-quality olive oil and avocado products that are marketed both locally and internationally. Our commitment to sustainability extends to our packaging solutions, which are designed to minimize environmental impact while ensuring product freshness and quality.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9872607617565412, 'A': 0.0004601782421317777, 'F': 0.0009942758267709876, 'B': 0.010340772557229897, 'J': 0.0009440116173264491}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012739238243458795}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 380:
  Our company is a key player in the iron ore mining sector, focusing on both the extraction of raw materials and their subsequent processing. We operate a series of mines that are equipped with modern extraction technologies, allowing us to efficiently access and recover high-quality iron ore. Our beneficiation plants utilize a combination of mechanical and chemical processes to enhance the purity and grade of our products. We are dedicated to maintaining the highest safety standards and minimizing our environmental impact, ensuring that our operations are sustainable and responsible.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.4864526021732664e-05, 'A': 3.437110812798864e-05, 'F': 1.2341494673706127e-05, 'B': 0.9998912662233969, 'J': 7.156647779735763e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.5076124881024723e-06, 6: 1.565315251194971e-06, 7: 0.9999959270722608}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677819740815297, 7.2: 0.032218025918470346}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 381:
  We specialize in the integrated aquaculture of fish and plants, employing a method known as aquaponics. This innovative system allows us to cultivate tilapia alongside various vegetables, creating a symbiotic environment where fish waste provides nutrients for the plants, and the plants help filter the water for the fish. Our operations emphasize sustainability, resource efficiency, and local food production, catering to the growing demand for fresh, organic produce while minimizing environmental impact and promoting community health.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0010074123366167187, 'A': 0.9874880103658618, 'F': 0.005794506472851114, 'B': 0.005093369199498451, 'J': 0.0006167016251719163}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012511989634138243}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 49%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                         | 384/788 [00:24<00:28, 14.16it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 382:
  We are dedicated to the mining and processing of rare earth elements, crucial for modern technologies such as smartphones and electric vehicles. Our operations utilize innovative separation techniques that allow us to efficiently extract these valuable minerals from complex ores. By investing in research and development, we aim to improve our extraction methods and reduce the environmental impact of our mining activities. Our commitment to sustainability is further demonstrated through partnerships with local communities to ensure responsible mining practices and support regional economic development.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.4957319737985e-05, 'A': 3.43899893099857e-05, 'F': 1.2361287964243155e-05, 'B': 0.999891131947085, 'J': 7.159455902694209e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.449561095197683e-06, 6: 1.6189714668095176e-06, 7: 0.999995931467438}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03511399207738403, 7.2: 0.9648860079226159}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 383:
  Timber Innovations focuses on the sustainable production of roundwood, catering to both the construction industry and the energy sector. Our logging practices are designed to yield high-quality logs while also gathering forest residues for biomass energy. We produce firewood and utility poles, ensuring that our products are sourced responsibly. By leveraging advanced technologies in our operations, we strive to enhance efficiency and reduce waste, aligning our business model with the principles of sustainability and environmental responsibility.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0027193792690483752, 'A': 0.003596868054123212, 'F': 0.0005638018245090298, 'B': 0.9928431728470256, 'J': 0.000276778005293806}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.007156827152974388}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 384:
  We focus on the mining and processing of cobalt ores, essential for the production of batteries used in electric vehicles and portable electronics. Our operations are characterized by advanced extraction techniques that ensure high recovery rates while maintaining environmental stewardship. We have implemented rigorous safety protocols to protect our workforce and surrounding communities. By collaborating with technology partners, we aim to innovate in our processing methods, enhancing the quality of our cobalt products and supporting the growing demand for sustainable energy solutions.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.551842866516793e-05, 'A': 3.401160033267508e-05, 'F': 1.2286813901061175e-05, 'B': 0.9998910851983657, 'J': 7.0979587352971734e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.472651659761597e-06, 6: 1.5862336024630027e-06, 7: 0.9999959411147377}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035190055737045395, 7.2: 0.9648099442629545}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 49%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                        | 388/788 [00:24<00:28, 13.95it/s]

RAPS scores:

==================================================
Description 385:
  We are engaged in the raising of other animals, including llamas and alpacas, focusing on the production of high-quality fiber. Our breeding program emphasizes the development of animals with superior fleece characteristics, which are highly sought after in the textile industry. We provide our animals with a nurturing environment that promotes their health and well-being. Our shearing processes are conducted with care to ensure the comfort of the animals while producing premium fibers for spinning and weaving. We also offer farm tours and educational workshops to raise awareness about the benefits of sustainable animal husbandry and fiber production.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0074512455173008346, 'A': 0.8808066068385125, 'F': 0.0598731982309648, 'B': 0.0488210927585237, 'J': 0.003047856654698131}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11919339316148747}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 386:
  Our hard coal mining operations are characterized by a commitment to innovation and sustainability. We leverage both underground and surface mining techniques to extract coal efficiently, while our processing facilities utilize cutting-edge technology for cleaning and grading. This ensures that our coal not only meets but exceeds industry standards for quality. We also prioritize environmentally responsible practices throughout our operations, from extraction to transport, ensuring that we minimize our ecological footprint. Our focus on quality and sustainability makes us a leader in the coal mining sector, catering to a diverse range of clients.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.484506048123627e-05, 'A': 3.437064207306046e-05, 'F': 1.2335476279652422e-05, 'B': 0.9998912964904562, 'J': 7.1523307098778264e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957295048321, 6: 1.3440680269282194e-06, 7: 2.926427141090836e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975274156551297, 5.2: 0.00247258434487035}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 387:
  We specialize in the extraction and beneficiation of iron ores, focusing on delivering high-quality products to the steel manufacturing sector. Our mining operations utilize advanced drilling and blasting techniques, followed by a series of beneficiation processes that include washing and magnetic separation. This ensures that we produce iron ore concentrates with optimal purity. Our agglomeration facilities create iron ore pellets that are designed to meet the specific needs of our clients, providing them with a reliable input for their steel production processes. We are committed to maintaining high safety standards and minimizing our environmental impact throughout our operations.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.621116111300715e-05, 'A': 3.398823183662575e-05, 'F': 1.2330180148497012e-05, 'B': 0.9998903011518598, 'J': 7.169275042179271e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010969884814016062}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 50%|███████████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 393/788 [00:24<00:22, 17.36it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 388:
  We are dedicated to the extraction of crude petroleum, utilizing a combination of conventional and unconventional methods to maximize output. Our research initiatives focus on developing more efficient extraction techniques, including the use of nanotechnology to enhance oil recovery rates. We also prioritize the reduction of greenhouse gas emissions during our operations, implementing carbon capture technologies where feasible. Our strategic approach not only meets the energy demands of today but also aligns with our long-term sustainability goals.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4817584478244544e-05, 'A': 3.461277879074971e-05, 'F': 1.2401027628412318e-05, 'B': 0.9998909942404401, 'J': 7.174368662449584e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7790362108665224e-06, 6: 0.9999964010602179, 7: 1.8199035714046648e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020551694572787877, 6.1: 0.9979448305427212}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 389:
  We are committed to the cultivation of oleaginous fruits, such as avocados and olives, which are known for their health benefits and culinary versatility. Our orchards are managed with an emphasis on sustainable practices, including minimal pesticide use and organic fertilization. We have invested in cold-pressed extraction technology to produce high-quality oils that retain the natural flavors and nutrients of the fruits. Our products are marketed to both retail and food service sectors, appealing to consumers looking for premium, healthy cooking oils.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9502059744786574, 'A': 0.0010091920702313608, 'F': 0.0025198506482298705, 'B': 0.04474900955777883, 'J': 0.0015159732451025924}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0497940255213426}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 390:
  As a producer of beverage crops, we specialize in the cultivation of coffee and tea, focusing on premium varieties that are ethically sourced and sustainably grown. Our farms are located in high-altitude regions that provide the ideal climate for developing rich flavors and aromas. We employ shade-grown techniques that preserve local ecosystems while improving crop resilience. Our commitment to fair trade practices ensures that our farmers receive equitable compensation, fostering community development and supporting sustainable livelihoods.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9871106629520892, 'A': 0.0005543498487040343, 'F': 0.0013391095939994106, 'B': 0.009808753631919962, 'J': 0.0011871239732875172}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012889337047910843}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 391:
  Our nursery specializes in the cultivation of a wide variety of flowering plants, shrubs, and trees for both ornamental and agricultural use. We utilize innovative propagation techniques to ensure the health and vitality of our plants, providing customers with vibrant options for their gardens and landscapes. Our commitment to sustainability is evident in our growing practices, which prioritize organic methods and environmental stewardship. We also offer landscaping services, helping clients design and implement beautiful outdoor spaces that incorporate our high-quality plants.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.012506991959866588, 'A': 0.06551873958146245, 'F': 0.9066532068107349, 'B': 0.011193287274671672, 'J': 0.0041277743732643386}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09334679318926509}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 392:
  We focus on the cultivation of beverage crops, particularly coffee and tea, which are essential for the global beverage industry. Our farms are located in regions known for their ideal growing conditions, and we implement sustainable farming practices to enhance the quality of our crops. We work closely with local farmers to promote fair trade practices and ensure that they receive fair compensation for their harvests. Our products are processed and packaged with care, maintaining their unique flavor profiles. We also engage in educational initiatives to raise awareness about the importance of sustainable agriculture in the beverage sector.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.1318224959956596, 'A': 0.02114965928835186, 'F': 0.025268536176363463, 'B': 0.8178526939258737, 'J': 0.003906614613751415}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18214730607412633}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 50%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 396/788 [00:24<00:23, 16.82it/s]

RAPS scores:

==================================================
Description 393:
  As a prominent grower of tobacco, we are committed to producing high-quality leaf that meets the stringent requirements of the global market. Our cultivation practices focus on soil health and crop management, ensuring that our tobacco plants thrive. We employ skilled agronomists who oversee the growth process, from planting to harvesting, ensuring optimal conditions for flavor and quality. Our tobacco is processed using traditional methods, enhancing its appeal to manufacturers of premium products. We also engage in community development initiatives, supporting local farmers and fostering sustainable practices within the industry.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9943093113045182, 'A': 0.0002505422701353527, 'F': 0.0004755131365412341, 'B': 0.004298734702347725, 'J': 0.0006658985864575511}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005690688695481838}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 394:
  As a leader in the natural gas sector, our company is dedicated to the extraction and processing of crude gaseous hydrocarbons. We utilize innovative hydraulic fracturing techniques to access previously unreachable reserves, ensuring a steady supply of natural gas. Our facilities are equipped with cutting-edge technology for the separation of liquid hydrocarbon fractions, allowing us to efficiently convert raw materials into market-ready products. Furthermore, we prioritize environmental stewardship by implementing advanced gas desulphurization methods, which significantly reduce emissions and enhance the quality of our output. Our commitment to operational excellence positions us as a trusted partner in the energy landscape.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.506488982603157e-05, 'A': 3.472764935347778e-05, 'F': 1.2492313181710147e-05, 'B': 0.9998904523844826, 'J': 7.26276315623893e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010954761551740244}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 395:
  Our company focuses on the extraction of crude petroleum from both conventional and unconventional sources, employing a diverse array of techniques tailored to each reservoir's unique characteristics. We utilize hydraulic fracturing and horizontal drilling to unlock oil trapped in shale formations, significantly increasing our production capabilities. Our team of geologists and engineers work collaboratively to develop comprehensive extraction plans that prioritize safety and environmental stewardship. By investing in renewable energy initiatives alongside our petroleum operations, we aim to create a balanced energy portfolio that meets current and future demands.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.481819739101822e-05, 'A': 3.4750593144266475e-05, 'F': 1.2459998220463573e-05, 'B': 0.9998907310667319, 'J': 7.240144512464498e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7618877213644116e-06, 6: 0.9999964343755084, 7: 1.8037367702789014e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020575208536743614, 6.1: 0.9979424791463256}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 396:
  As a prominent player in the mining of lead and silver ores, our company provides critical materials for various industrial applications, including construction and electronics. We utilize advanced mining technologies to ensure high recovery rates while maintaining a focus on safety and environmental stewardship. Our processing plants are equipped with cutting-edge equipment that enables us to produce refined metals that meet the highest quality standards. Additionally, we are dedicated to research and development efforts aimed at discovering new applications for lead and silver, enhancing our value proposition in the marketplace.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.58757264243569e-05, 'A': 3.4104612834203635e-05, 'F': 1.2352088679702156e-05, 'B': 0.9998905197899479, 'J': 7.147782113709505e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010948021005208197}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 51%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 399/788 [00:24<00:21, 17.71it/s]

RAPS scores:

==================================================
Description 397:
  We specialize in the extraction and processing of natural gas, utilizing advanced drilling and separation technologies to maximize efficiency. Our operations include the removal of impurities through gas desulphurization, ensuring that we deliver high-quality natural gas to our clients. We also focus on the extraction of condensates, which adds value to our product offerings. By investing in innovative solutions and adhering to environmental standards, we are committed to providing sustainable energy solutions while meeting the growing demands of the market.1. Our company specializes in the extraction and processing of natural gas, utilizing advanced drilling technologies to maximize yield while minimizing environmental impact. We employ state-of-the-art hydraulic fracturing techniques to access deep reserves, ensuring efficient extraction of crude gaseous hydrocarbons. Additionally, our facilities are equipped with cutting-edge separation technologies that allow us to effectively drain and separate liquid hydrocarbon fractions, enhancing the quality of our natural gas output. By investing in sustainable practices and innovative technologies, we aim to meet the growing global demand for cleaner energy solutions.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.520946858298855e-05, 'A': 3.450881879205406e-05, 'F': 1.2434255533235434e-05, 'B': 0.9998906101007069, 'J': 7.237356384817111e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938989929309972}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 398:
  In our commitment to advancing aquaculture technology, we focus on developing and implementing smart farming solutions that enhance productivity and sustainability. Our research and development team is dedicated to creating automated systems for monitoring water quality, feeding schedules, and growth rates of aquatic organisms. By leveraging data analytics and IoT technology, we provide aquaculture operators with tools to optimize their operations, reduce costs, and improve yield. Our innovative solutions are designed to support the industry's transition towards more sustainable and efficient practices, ultimately benefiting both producers and consumers.1. Our company specializes in marine aquaculture, focusing on the sustainable cultivation of high-value fish species such as salmon and sea bass. Utilizing advanced recirculating aquaculture systems (RAS), we ensure optimal growth conditions while minimizing environmental impact. Our operations include regular monitoring of water quality and temperature, as well as a meticulously designed feeding regimen that promotes healthy development. By employing innovative breeding techniques, we are able to enhance disease resistance and growth rates, ultimately delivering premium seafood products to both local and international markets.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 6.995315913450267e-05, 'A': 0.9992966295546731, 'F': 0.0002400330327314787, 'B': 0.00032879012696583956, 'J': 6.459412649496144e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007033704453268674}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 399:
  We focus on the extraction of crude petroleum through a combination of traditional drilling methods and cutting-edge hydraulic fracturing techniques. Our operations are strategically located in regions rich in untapped resources, allowing us to supply high-quality crude oil to both domestic and international markets. We prioritize safety and environmental stewardship, employing rigorous monitoring systems to mitigate risks associated with extraction activities. Our skilled workforce is dedicated to maintaining operational excellence, ensuring that we meet the growing demand for energy while adhering to strict regulatory standards.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4858844963956214e-05, 'A': 3.4646318557399263e-05, 'F': 1.2443698037092562e-05, 'B': 0.999890829932269, 'J': 7.221206172464393e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7704779173615688e-06, 6: 0.999996412094368, 7: 1.8174277148503333e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020553352293799345, 6.1: 0.99794466477062}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 51%|█████████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 404/788 [00:25<00:20, 19.15it/s]

RAPS scores:

==================================================
Description 400:
  Our business thrives on the cultivation of citrus fruits, particularly oranges and lemons, which are grown in our expansive orchards. We leverage modern agricultural technologies, such as drone monitoring and soil sensors, to optimize growth conditions and ensure consistent fruit quality. Our processing facilities are equipped to produce a range of citrus-based products, including juices, concentrates, and essential oils, catering to both the beverage and food industries. We are committed to reducing our carbon footprint by implementing energy-efficient practices and promoting sustainable farming initiatives that benefit both our community and the environment.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.4544304374565205, 'A': 0.0065674558418065436, 'F': 0.012896248453565925, 'B': 0.5226752400744564, 'J': 0.0034306181736505703}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4773247599255436}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 401:
  Our focus on artisanal fishing practices allows us to capture a variety of fish species in small-scale operations that prioritize quality over quantity. We use traditional fishing methods that have been passed down through generations, ensuring minimal disruption to marine ecosystems. Our products are marketed as premium offerings, highlighting their freshness and the sustainable methods employed in their capture. We collaborate with local chefs and restaurants to promote our catch, creating a direct link between fishermen and consumers. This model not only supports local economies but also fosters a deeper appreciation for the origins of seafood.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0034137058376410225, 'A': 0.687594275315333, 'F': 0.004177429387384974, 'B': 0.3033255560465327, 'J': 0.0014890334131083404}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.312405724684667}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 402:
  Our business is centered around the growing of citrus fruits, with a focus on oranges, lemons, and limes. We utilize advanced cultivation methods, including soil moisture sensors and climate control systems, to enhance fruit quality and yield. Our citrus products are marketed fresh to grocery chains and food service providers, while our juice production facility processes surplus fruit into high-quality juice products. We prioritize sustainability by employing organic farming practices and minimizing waste through recycling initiatives. Our commitment to quality and sustainability has positioned us as a trusted supplier in the citrus market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.8488412237550382, 'A': 0.0028179885939901544, 'F': 0.006826910297641395, 'B': 0.13879377900698234, 'J': 0.002720098346347847}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15115877624496177}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 403:
  We operate a comprehensive forestry consultancy that assists landowners in managing their timber resources effectively. Our services include forest inventory assessments, growth modeling, and conservation planning. By leveraging our expertise in silviculture, we help clients optimize their timber production while adhering to sustainable management practices. Our goal is to empower landowners to make informed decisions that enhance both ecological health and economic viability.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.0338581797829985e-05, 'A': 0.9996580760172983, 'F': 0.0001642850236306032, 'B': 0.000113986294637082, 'J': 3.331408263618054e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00034192398270171953}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 52%|██████████████████████████████████████████████████████████████████████████████████████████▍                                                                                    | 407/788 [00:25<00:21, 18.03it/s]

RAPS scores:

==================================================
Description 404:
  Our company is at the forefront of iron ore mining, employing a range of advanced technologies to enhance our extraction and processing capabilities. We focus on the beneficiation of iron ores through methods such as gravity separation and magnetic separation, which allow us to produce high-quality iron concentrates with minimal environmental impact. Our operations are supported by a robust logistics network that ensures efficient transportation of our products to steel mills and other end-users. We also prioritize research and development, continuously seeking innovative solutions to improve our mining processes and reduce our ecological footprint.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.535309330284812e-05, 'A': 3.419160507157543e-05, 'F': 1.2319219494770768e-05, 'B': 0.9998909933800509, 'J': 7.142702079740518e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.491866063186379e-06, 6: 1.5715241644165398e-06, 7: 0.9999959366097724}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677886564850771, 7.2: 0.03221134351492289}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 405:
  Our business focuses on the gathering and production of wood for energy, utilizing both roundwood and forest residues to create renewable energy sources. We operate several biomass facilities that convert wood into clean energy, catering to the increasing demand for sustainable power solutions. Our team employs innovative technologies to optimize the conversion process, ensuring high efficiency and low emissions. We also collaborate with local communities to source wood sustainably, promoting responsible forest management practices. By turning waste materials into valuable energy products, we contribute to a circular economy while supporting energy independence.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.005885278540767428, 'A': 0.004464384534856783, 'F': 0.001276380530439135, 'B': 0.9879577447427917, 'J': 0.0004162116511449972}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012042255257208256}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 406:
  Our company is dedicated to the extraction of high-quality crude petroleum, employing advanced seismic imaging technology to identify optimal drilling locations. This precision approach not only boosts our extraction efficiency but also reduces the environmental footprint of our operations. We have established a comprehensive training program for our personnel, ensuring they are equipped with the latest skills in safe drilling practices and environmental stewardship. By focusing on innovation and sustainability, we aim to create long-term value for our shareholders and contribute positively to the communities in which we operate.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5300802872170455e-05, 'A': 3.4794752165986016e-05, 'F': 1.2526198624108284e-05, 'B': 0.9998901333403178, 'J': 7.244906019899237e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010986665968215625}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 407:
  Engaged in the mining of iron ores, our company employs a comprehensive approach that encompasses exploration, extraction, and beneficiation. We utilize advanced technologies to conduct geological surveys and assess ore quality, followed by efficient mining operations that prioritize worker safety and environmental protection. Our beneficiation facilities are equipped with cutting-edge technologies that maximize ore recovery and produce high-grade iron concentrates. With a commitment to quality and innovation, we strive to meet the evolving needs of our clients in the steel industry, ensuring a competitive edge in the market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5110300512431995e-05, 'A': 3.432564202757926e-05, 'F': 1.2356083387875249e-05, 'B': 0.999891052148497, 'J': 7.155825575124911e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4684842913056443e-06, 6: 1.5851803300432494e-06, 7: 0.9999959463353786}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677902618462353, 7.2: 0.03220973815376461}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 52%|███████████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 412/788 [00:25<00:19, 19.02it/s]

RAPS scores:

==================================================
Description 408:
  We focus on the production of roundwood for various forest-based manufacturing industries, ensuring that our operations align with sustainable forestry practices. Our logging activities are complemented by a commitment to reforestation and biodiversity conservation. The logs we produce are processed into timber products that serve a wide range of applications, from furniture making to construction. By leveraging advanced technology in our harvesting processes, we enhance productivity while minimizing waste. Our dedication to quality and sustainability positions us as a trusted partner in the supply chain for manufacturers seeking responsibly sourced materials.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9995981063316591, 'A': 2.4847891306554693e-05, 'F': 3.135180296479661e-05, 'B': 0.0001855133661402736, 'J': 0.00016018060792917483}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00040189366834086915}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 409:
  Our lignite processing facilities are equipped with the latest technologies for washing, dehydrating, and pulverizing lignite to meet the diverse needs of our clients. By utilizing high-efficiency machinery, we enhance the quality of our lignite, making it suitable for power generation and industrial applications. Our commitment to continuous improvement drives us to adopt new techniques that increase yield and reduce waste, ensuring that we remain competitive in the market while adhering to strict environmental standards.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.977239946396284, 'A': 0.00022208592665994988, 'F': 0.00020287281752292118, 'B': 0.021769504407071597, 'J': 0.0005655904524616517}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.022760053603716024}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 410:
  Specializing in the raising of other cattle and buffaloes, our farm emphasizes organic practices to produce high-quality beef. We prioritize pasture-based systems that allow animals to graze naturally, enhancing the flavor and nutritional profile of our meat. Our breeding strategy focuses on genetic diversity and disease resistance, ensuring a healthy herd. We also engage in direct sales to consumers, providing transparency about our farming methods and the quality of our products. Our commitment to sustainable agriculture helps us contribute positively to the environment while meeting the growing demand for ethically produced beef.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.006196818013989148, 'A': 0.7721460153307942, 'F': 0.01653196171422471, 'B': 0.20293107390123954, 'J': 0.002194131039752326}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2278539846692058}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 411:
  In the realm of freshwater aquaculture, our business is dedicated to the cultivation of high-quality catfish and trout. We operate several farms equipped with biosecure systems that minimize disease risk and enhance fish welfare. Our team of aquaculture specialists implements precise feeding regimens and water quality monitoring to maximize production efficiency. We take pride in our traceability systems, allowing consumers to know the origin of their seafood. Additionally, our partnerships with local restaurants and grocery chains ensure that our fresh fish reaches consumers promptly, supporting a farm-to-table approach.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0002548066991059155, 'A': 0.9968903806028503, 'F': 0.0012564115775842474, 'B': 0.0014002865811442455, 'J': 0.00019811453931531525}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00310961939714971}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 412:
  Our company is engaged in the collection of aquatic plants, particularly seaweed, from coastal waters. We employ sustainable harvesting techniques that allow us to gather these resources without damaging their natural habitats. The seaweed is processed into various products, including snacks and health supplements, catering to the growing demand for plant-based nutrition. We also focus on educating consumers about the nutritional benefits of seaweed, positioning our brand as a leader in the sustainable food movement and expanding our reach into health-conscious markets.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 6.337023851744038e-05, 'A': 0.999282928979815, 'F': 0.0003888642737621521, 'B': 0.00020010792681269057, 'J': 6.472858109256719e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0007170710201850339}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 53%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                  | 418/788 [00:25<00:17, 21.75it/s]

RAPS scores:

==================================================
Description 413:
  We focus on the production of charcoal using traditional methods that honor age-old practices while ensuring sustainability. Our operations are rooted in local communities, where we source wood from managed forests, ensuring that our production does not deplete resources. The charcoal is crafted in small batches to maintain quality and flavor, appealing to both culinary enthusiasts and industrial users. Our commitment to traditional craftsmanship combined with sustainable sourcing has allowed us to carve out a niche market, where customers appreciate the authenticity and environmental responsibility of our products.1. Our company specializes in the sustainable management and harvesting of roundwood, focusing on high-quality logs intended for various manufacturing applications. We employ advanced logging techniques that minimize environmental impact while maximizing yield. Our operations include selective cutting practices that ensure the health of the forest ecosystem. Additionally, we process timber into firewood, catering to the growing demand for renewable energy sources. By investing in efficient transportation and storage solutions, we ensure that our products reach customers promptly, whether they are local businesses or energy producers.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.028543974746741457, 'A': 0.0008134847549065099, 'F': 0.0006086030036250258, 'B': 0.9697051583291819, 'J': 0.00032877916554516174}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.030294841670818085}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 414:
  Our operations are centered around the raising of other animals, specifically rabbits and guinea pigs, for both pets and meat production. We prioritize humane breeding practices and provide enriched environments for our animals to thrive. Our focus on high-quality genetics ensures that our rabbits produce tender meat and that our guinea pigs are healthy companions for families. We also engage in community education, offering workshops on responsible pet ownership and the benefits of raising rabbits as a sustainable protein source. Our products are marketed through local pet stores and farmers' markets, emphasizing our commitment to animal welfare and sustainable practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.000786171676382338, 'A': 0.9862502828246499, 'F': 0.00637430056639848, 'B': 0.00606303400201177, 'J': 0.000526210930557476}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.013749717175350118}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 415:
  Our company is engaged in the raising of horses, providing a range of services that include breeding, training, and boarding. We focus on developing high-performance equines for various disciplines, from dressage to show jumping. Our training programs are tailored to each horse's unique needs, emphasizing positive reinforcement techniques. We also offer educational workshops for horse owners, promoting best practices in care and management. Our facilities are equipped with top-notch amenities, ensuring a safe and enriching environment for both horses and riders, and contributing to the local equestrian community.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0027886712588437532, 'A': 0.3913964262099782, 'F': 0.5959827155340669, 'B': 0.007201471987467123, 'J': 0.00263071500964405}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4040172844659331}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 416:
  Our business is dedicated to the capture fishery sector, focusing on the sustainable harvesting of freshwater fish from lakes and rivers. We utilize a fleet of small boats equipped with modern fishing gear to target species such as perch and bass. Our commitment to environmental stewardship is reflected in our practices, which include monitoring fish populations and participating in local conservation initiatives. In addition to selling our catch to restaurants and grocery stores, we also offer fishing licenses and equipment rentals to promote recreational fishing in the area. By engaging the community, we strive to foster a love for freshwater fishing while ensuring the health of our aquatic resources.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00026061217842982524, 'A': 0.9956697148050246, 'F': 0.0006916547204461795, 'B': 0.003175255644518861, 'J': 0.00020276265158068307}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0043302851949753585}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 417:
  Our company operates in the offshore fishing segment, utilizing large-scale purse seine nets to capture schooling fish like sardines and mackerel. We invest in cutting-edge navigation and communication technologies to optimize our fishing routes and ensure efficient operations. Our commitment to sustainability is evident in our practices, which include bycatch reduction devices and regular assessments of fish stocks. We supply our catch to both domestic and international markets, focusing on delivering high-quality products while supporting initiatives aimed at ocean conservation.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.003349647434691931, 'A': 0.29360978874921717, 'F': 0.0036287466978019165, 'B': 0.698033648970668, 'J': 0.0013781681476208994}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.301966351029332}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 418:
  Our business focuses on the sustainable gathering of nuts, particularly in regions known for their rich biodiversity. We employ local harvesters who are trained in environmentally friendly practices to ensure that our collection methods do not disrupt local ecosystems. The nuts are processed in our facility, where they are roasted and packaged for both retail and wholesale markets. We also prioritize direct-to-consumer sales through our online platform, where we educate customers about the nutritional benefits of our products and the importance of sustainable harvesting.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.00044601001630807646, 'A': 0.9914423571910669, 'F': 0.0011797856170635774, 'B': 0.006624156984662941, 'J': 0.0003076901908985345}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.008557642808933119}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 53%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                 | 421/788 [00:26<00:16, 22.11it/s]

RAPS scores:

==================================================
Description 419:
  Our company specializes in the sustainable harvesting of roundwood for various applications, including the production of utility poles and construction materials. We utilize advanced logging techniques to ensure that our operations are efficient and environmentally responsible. Our roundwood is processed into high-quality products that meet the needs of our clients in the construction and energy sectors. We also invest in reforestation initiatives, ensuring that our logging practices contribute to the long-term health of the forests we rely on. By prioritizing sustainability, we aim to support economic growth while preserving natural resources for future generations.1. Our company specializes in sustainable logging practices that prioritize environmental stewardship while meeting the growing demand for roundwood. We engage in selective logging, which allows us to harvest timber without compromising the health of the forest ecosystem. Our operations focus on producing high-quality logs that are supplied to local manufacturers for construction and furniture production. Additionally, we are committed to reforestation efforts, ensuring that for every tree harvested, several are planted in its place, thus maintaining the balance of our natural resources.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.009581493454192487, 'A': 0.006948972401202855, 'F': 0.0023171234763105166, 'B': 0.9804847448561615, 'J': 0.0006676658121327198}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01951525514383845}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 420:
  In the realm of recreational fishing, our business offers guided fishing experiences on both freshwater lakes and coastal waters. We provide clients with access to well-maintained boats and top-of-the-line fishing gear, ensuring a successful outing. Our knowledgeable guides share insights on local fishing techniques and sustainable practices, fostering a deeper appreciation for the environment. We also organize community events to promote fishing as a family-friendly activity, emphasizing the importance of conservation and responsible fishing. By creating memorable experiences, we aim to cultivate a new generation of environmentally conscious anglers.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 2.6771424008202425e-05, 'A': 0.999735475125928, 'F': 0.00010566356097819878, 'B': 0.00010274057969164666, 'J': 2.934930939401153e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002645248740720252}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 421:
  Specializing in the extraction of crude petroleum, our company employs a range of innovative technologies to improve operational efficiency. We utilize advanced drilling techniques, including directional drilling, to access hard-to-reach reserves while minimizing surface disruption. Our commitment to sustainability is reflected in our investments in carbon capture and storage projects, which aim to reduce greenhouse gas emissions associated with oil extraction. By fostering partnerships with local communities, we ensure that our operations contribute positively to the regions in which we operate.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4830652716315515e-05, 'A': 3.4762732117521043e-05, 'F': 1.2479456258143527e-05, 'B': 0.9998907038632369, 'J': 7.223295671274652e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7586779839680977e-06, 6: 0.9999964377787492, 7: 1.8035432668366344e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.002056631547927848, 6.1: 0.9979433684520721}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 422:
  Engaged in the growing of tobacco, our company emphasizes quality and sustainability in every aspect of our operations. We cultivate several premium tobacco varieties, carefully managing the growing conditions to enhance flavor and aroma. Our commitment to responsible farming practices includes soil conservation and the reduction of chemical inputs, which not only benefits the environment but also meets the expectations of health-conscious consumers. We collaborate closely with local farmers, providing them with training and resources to ensure that our tobacco meets the highest standards for both domestic and international markets.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9836897920012144, 'A': 0.0005601631288368594, 'F': 0.001053410347555026, 'B': 0.013628821962287423, 'J': 0.001067812560106336}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.016310207998785575}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 54%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                | 427/788 [00:26<00:18, 20.02it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 423:
  Our operations in the hard coal mining sector are driven by a commitment to quality and sustainability. We utilize both underground and surface mining methods to extract coal, which is then subjected to rigorous cleaning and sizing processes. Our advanced facilities are equipped for efficient pulverization and compression, enhancing the transportability of our coal products. By continuously investing in technology and best practices, we aim to meet the evolving demands of our clients while minimizing our environmental impact.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.516930323202609e-05, 'A': 3.418120799336231e-05, 'F': 1.2311435299553028e-05, 'B': 0.9998912056538216, 'J': 7.132399653533268e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957239920764, 6: 1.3373368782221304e-06, 7: 2.9386710455176483e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975296410220895, 5.2: 0.002470358977910514}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 424:
  Our company specializes in artisanal fishing, focusing on small-scale, sustainable methods to catch a variety of fish and shellfish. We utilize handlines and traps, ensuring that our impact on the environment is minimal while maintaining high-quality standards. Our catch is sold directly to consumers at local farmers' markets, where we emphasize the freshness and traceability of our products. By fostering direct relationships with our customers, we create a community of seafood lovers who value sustainable practices and the flavors of locally sourced seafood.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00655367368493427, 'A': 0.3923340889058143, 'F': 0.008382893838642288, 'B': 0.5907188363421613, 'J': 0.002010507228447819}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.40928116365783873}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 425:
  At GreenWood Solutions, we are dedicated to the sustainable growth of timber and pulpwood. Our operations include the careful selection and planting of tree species that thrive in local conditions, as well as ongoing maintenance to ensure optimal growth. We also operate specialized nurseries that provide high-quality seedlings to support reforestation projects. By utilizing innovative techniques such as selective thinning, we enhance forest productivity and biodiversity. Our focus on sustainable practices not only meets market demands for timber but also supports ecological balance and conservation efforts.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00023726659187282484, 'A': 0.9932853365291886, 'F': 0.005487497899332722, 'B': 0.0007592407676832404, 'J': 0.00023065821192235424}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0067146634708113995}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 426:
  We are dedicated to the cultivation of premium rice varieties, leveraging traditional farming methods complemented by modern technology. Our operations span from seed selection to harvesting, ensuring that each grain meets our stringent quality standards. We implement water-efficient irrigation techniques to minimize environmental impact while maximizing yield. Our rice is marketed both domestically and internationally, catering to diverse culinary preferences. Additionally, we engage in community outreach programs to educate local farmers on sustainable practices, fostering a cooperative approach to rice production.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.05069656059357928, 'A': 0.02947736236036927, 'F': 0.01770648805555948, 'B': 0.8993040783832925, 'J': 0.0028155106071995695}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10069592161670748}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 427:
  Our company is at the forefront of hard coal mining, employing innovative techniques to extract and process coal efficiently. We utilize both underground and surface mining methods, ensuring that we can access a variety of coal deposits. Our processing facilities are equipped with advanced technology for cleaning and sizing coal, which enhances its quality and marketability. By focusing on operational efficiency and environmental stewardship, we are able to provide our clients with a reliable source of high-quality coal while minimizing our impact on the environment.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4991204150385096e-05, 'A': 3.44820191497138e-05, 'F': 1.238636197960084e-05, 'B': 0.9998909502050499, 'J': 7.1902096705041455e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957196693217, 6: 1.3373419739861674e-06, 7: 2.9429887043703797e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975266863628477, 5.2: 0.002473313637152363}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 428:
  We are engaged in the extraction of crude petroleum, focusing on maximizing output while minimizing environmental impact. Our operations leverage advanced technologies such as 3D seismic imaging and automated drilling systems, which allow us to accurately locate and efficiently extract oil reserves. We prioritize safety and environmental responsibility, implementing comprehensive risk management strategies and engaging with local communities to address concerns related to our operations. Our goal is to be a leader in sustainable oil extraction practices.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.490966877254941e-05, 'A': 3.453450176332742e-05, 'F': 1.2415431288505515e-05, 'B': 0.9998909494119003, 'J': 7.190986275384223e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7781168656358344e-06, 6: 0.9999963930803196, 7: 1.8288028145810727e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.002055309311327787, 6.1: 0.9979446906886723}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 55%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                              | 433/788 [00:26<00:20, 17.59it/s]

RAPS scores:

==================================================
Description 429:
  Specializing in the gathering of lac and resins, our company sources these natural materials from the forests of Southeast Asia. We work with local harvesters to ensure that our collection methods are sustainable and do not harm the environment. The lac we collect is processed into high-quality shellac, which is used in various applications, including woodworking and cosmetics. Our commitment to ethical sourcing and fair trade practices has helped us build strong relationships with our suppliers, ensuring a reliable and sustainable supply chain for our customers.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.006781108549619454, 'A': 0.0005922235397783426, 'F': 0.000344100297291633, 'B': 0.9921141378114109, 'J': 0.00016842980189965908}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00788586218858911}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 430:
  We are at the forefront of aquafarming, specializing in the cultivation of aquatic plants such as seaweed and algae. Our operations leverage cutting-edge cultivation methods, including vertical farming and integrated multi-trophic aquaculture, to maximize production efficiency. The harvested seaweed is processed into various products, from food additives to biofuels, showcasing our commitment to innovation and sustainability. By promoting the use of aquatic plants, we contribute to carbon sequestration and provide eco-friendly alternatives in various industries, including food and cosmetics.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0002879655635813126, 'A': 0.9962001820991743, 'F': 0.0008411518016326808, 'B': 0.002454057626192095, 'J': 0.00021664290941953045}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0037998179008257305}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 431:
  We recognize the importance of innovation in the lignite sector and continuously invest in new technologies to enhance our operations. Our research team is focused on developing advanced extraction and processing methods that improve efficiency and reduce environmental impact. We also explore opportunities for integrating digital technologies, such as IoT and data analytics, to optimize our mining and processing operations. By fostering a culture of innovation, we aim to position ourselves as a leader in the lignite industry, driving growth and creating value for our stakeholders.1. Our company specializes in the extraction and processing of lignite, employing both surface and underground mining techniques to ensure efficient resource recovery. We utilize advanced liquefaction methods to enhance the quality of our lignite, making it suitable for various industrial applications. Our state-of-the-art washing and dehydrating facilities further refine the coal, removing impurities and optimizing its energy content. By investing in innovative technologies, we not only improve the quality of our products but also minimize environmental impact, positioning ourselves as a leader in sustainable lignite mining.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.557419969599012e-05, 'A': 3.4502922332683965e-05, 'F': 1.247419957012554e-05, 'B': 0.9998901966414925, 'J': 7.252036908733665e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010980335850752088}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 432:
  We are involved in the growing of various perennial crops, including medicinal herbs and plants used in pharmaceuticals. Our cultivation practices emphasize organic methods and biodiversity, ensuring that our products are of the highest quality. We work closely with researchers and health professionals to develop new herbal formulations and supplements. Our commitment to sustainability and ethical sourcing has positioned us as a leader in the herbal market, providing consumers with natural alternatives for health and wellness.1. Our company specializes in the cultivation and harvesting of premium grapes, focusing on both table and wine varieties. We employ sustainable agricultural practices to enhance soil health and yield quality. Our vineyards are strategically located in regions known for their unique terroirs, allowing us to produce grapes with distinctive flavors. Additionally, we invest in advanced irrigation systems and precision farming technologies to optimize water usage and crop management. By partnering with local wineries, we ensure our grapes contribute to high-quality wine production, thus creating value for both our growers and consumers.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9091423062971935, 'A': 0.0027998241107491197, 'F': 0.0070970542782687555, 'B': 0.07796297536712729, 'J': 0.0029978399466613053}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0908576937028065}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 55%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                              | 435/788 [00:26<00:21, 16.22it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 433:
  Engaged in the extraction of crude petroleum, our company operates in some of the most prolific oil fields globally. We utilize advanced geological modeling and reservoir simulation tools to identify optimal drilling locations, significantly improving our extraction efficiency. Our operations are complemented by a strong emphasis on safety and environmental stewardship, with rigorous protocols in place to mitigate risks associated with oil spills and emissions. By investing in renewable energy projects alongside our petroleum activities, we aim to diversify our energy portfolio and contribute to a more sustainable future while meeting the world's growing energy demands.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.488640502851477e-05, 'A': 3.4696570406757324e-05, 'F': 1.2453927676277424e-05, 'B': 0.9998907372672227, 'J': 7.225829665924338e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7571624481410621e-06, 6: 0.9999964406439691, 7: 1.8021935828548842e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.002056186305071881, 6.1: 0.997943813694928}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 434:
  Our company focuses on the integrated aquaculture of fish and plants, creating a symbiotic environment that maximizes resource efficiency. By combining aquaponics systems, we cultivate fish alongside vegetables, utilizing nutrient-rich water from fish tanks to nourish plant growth. This innovative approach not only reduces water usage but also minimizes waste, creating a sustainable food production model. Our products include fresh fish and organic vegetables, which we market to local grocery stores and restaurants. Through community workshops, we educate consumers about the benefits of aquaponics and sustainable farming, fostering a greater appreciation for locally sourced food.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00011276445120456142, 'A': 0.9988386893236668, 'F': 0.0003944244899579855, 'B': 0.0005555373217192962, 'J': 9.858441345150132e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0011613106763331826}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 435:
  As a manufacturer of beverages, our company is dedicated to producing a wide range of drinks, including juices, teas, and flavored waters derived from locally grown fruits and herbs. We prioritize sourcing ingredients from local farmers, ensuring freshness and supporting regional agriculture. Our production process emphasizes sustainability, utilizing eco-friendly packaging and minimizing waste. By focusing on health-conscious consumers, we create beverages that are not only delicious but also rich in nutrients, catering to the growing demand for functional drinks that promote wellness.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9997725172015812, 'A': 1.240671450533018e-05, 'F': 1.5391727700031898e-05, 'B': 6.626141794614368e-05, 'J': 0.00013342293826728658}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002274827984187766}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 436:
  We focus on the gathering of balata and other rubber-like gums from tropical trees, ensuring that our practices are environmentally sustainable and socially responsible. Our team works directly with local communities to harvest these materials, which are then processed into natural rubber products. This not only provides a source of income for the communities but also supports the conservation of forest ecosystems. Our commitment to ethical sourcing and quality has positioned us as a leading supplier in the natural rubber market, catering to industries that prioritize eco-friendly materials.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.01659604185437283, 'A': 0.4533276326580792, 'F': 0.02703718163609868, 'B': 0.4988836178655258, 'J': 0.004155525985923366}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5011163821344742}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 56%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 438/788 [00:27<00:24, 14.53it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 437:
  In the iron ore mining sector, our company is committed to excellence in both extraction and beneficiation. We harness cutting-edge technology to explore and develop iron ore deposits, ensuring that our mining practices are both efficient and environmentally responsible. Our beneficiation processes are designed to produce high-grade iron ore concentrates that cater to the specific needs of our customers in the steel industry. By focusing on innovation and sustainability, we strive to enhance our operational performance while contributing to the overall growth of the iron ore market.1. Our company specializes in the extraction and processing of high-grade iron ores, focusing on sustainable mining practices that minimize environmental impact. We utilize advanced drilling and blasting techniques to efficiently access ore deposits, followed by state-of-the-art beneficiation processes that enhance the iron content of our raw materials. Our commitment to innovation includes the implementation of automated systems for ore sorting and processing, which not only increases yield but also reduces operational costs. By partnering with local communities and adhering to strict safety protocols, we ensure that our mining activities contribute positively to the regions in which we operate.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.538726831005889e-05, 'A': 3.419672701557469e-05, 'F': 1.2320881332018291e-05, 'B': 0.9998909373056085, 'J': 7.157817733996098e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4557613255225203e-06, 6: 1.6032557449424243e-06, 7: 0.9999959409829295}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677807288804889, 7.2: 0.032219271119511214}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 56%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                             | 440/788 [00:27<00:24, 14.06it/s]

RAPS scores:

==================================================
Description 438:
  Our operations in hard coal mining involve a comprehensive approach that includes both extraction and processing. We utilize a combination of underground and surface mining techniques to access coal deposits, ensuring we maximize recovery rates. Our state-of-the-art processing facilities are equipped with advanced machinery for cleaning, sizing, and grading coal, which enhances its market value. Furthermore, we employ innovative pulverizing and compressing technologies to facilitate the efficient transport and storage of our products. With a strong focus on sustainability, we strive to minimize our environmental impact while providing high-quality coal to meet the energy needs of our customers.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.48247886346744e-05, 'A': 3.4380263171384586e-05, 'F': 1.2352374850440147e-05, 'B': 0.9998912758940885, 'J': 7.166679254995282e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957271944151, 6: 1.334987777984585e-06, 7: 2.9378178068824606e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975284069132736, 5.2: 0.0024715930867264643}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 439:
  Engaging in the cultivation of tobacco, we prioritize quality and sustainability in our farming practices. Our farms utilize integrated pest management techniques to reduce chemical usage while maintaining crop health. We work closely with local farmers, providing training and resources to improve their yield and quality of tobacco leaves. Our processing facilities are designed to ensure that every step, from curing to packaging, meets the highest standards of quality. By focusing on responsible sourcing and environmental stewardship, we aim to create a positive impact on the communities we serve.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.10047876380182018, 'A': 0.02114937302809479, 'F': 0.017292449190774616, 'B': 0.857721252570884, 'J': 0.003358161408426189}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.14227874742911595}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 440:
  We are engaged in the mining of iron ores, focusing on the extraction of high-quality ores that are essential for steel production. Our operations are characterized by the use of modern mining techniques, including automated drilling and real-time monitoring systems, which enhance safety and efficiency. Following extraction, our beneficiation processes involve crushing, grinding, and advanced separation methods to produce iron concentrates. We also implement agglomeration techniques, such as pelletizing, to create products that improve the efficiency of steelmaking. Our dedication to sustainable practices ensures that we minimize our ecological footprint while delivering top-tier iron ore to our clients.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5477064832773594e-05, 'A': 3.404208258642054e-05, 'F': 1.2297317029007715e-05, 'B': 0.9998910571083005, 'J': 7.126427251336613e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4532338584326147e-06, 6: 1.604924735781742e-06, 7: 0.9999959418414058}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678017349533587, 7.2: 0.032198265046641264}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 56%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                            | 442/788 [00:27<00:31, 11.02it/s]

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 441:
  The company focuses on developing and implementing sustainable fishing practices in collaboration with local communities. By providing training and resources for responsible fishing techniques, the organization aims to enhance the livelihoods of local fishers while ensuring the health of aquatic ecosystems. The company also engages in research initiatives to monitor fish populations and assess the impact of fishing activities. This commitment to community involvement and environmental stewardship not only strengthens relationships with local stakeholders but also promotes a sustainable future for the fishing industry.1. Our company operates a diverse marine fishing business that focuses on sustainable practices to harvest a variety of fish species from the Atlantic Ocean. Utilizing advanced sonar technology, we locate schools of fish efficiently, minimizing bycatch and ensuring compliance with environmental regulations. Our fleet of modern fishing vessels is equipped with eco-friendly gear, such as biodegradable nets, to reduce our ecological footprint. We supply fresh catches to local markets and restaurants, emphasizing quality and freshness. Additionally, we engage in community outreach programs to educate aspiring fishers about sustainable fishing practices, fostering a responsible approach to marine resource management.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.2339358060745257e-05, 'A': 0.999897417030076, 'F': 4.2425679898699875e-05, 'B': 3.335083859994086e-05, 'J': 1.4467093364614297e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007399961961730416, 2: 0.0009167007199384294, 3: 0.9983433030838886}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9582934880709154, 3.2: 0.041706511929084505}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 56%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                            | 444/788 [00:27<00:29, 11.53it/s]

RAPS scores:

==================================================
Description 442:
  We specialize in the extraction and beneficiation of iron ores, leveraging cutting-edge technologies to enhance operational efficiency and product quality. Our mining operations are supported by comprehensive geological studies that guide our exploration efforts, ensuring that we target the most promising deposits. Once extracted, our ores undergo rigorous beneficiation processes, including crushing, grinding, and magnetic separation, to produce high-purity iron concentrates. Our commitment to innovation extends to our logistics operations, where we utilize advanced tracking systems to optimize the transportation of our products to customers around the globe.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5201283548371505e-05, 'A': 3.419555916614244e-05, 'F': 1.2333577275306455e-05, 'B': 0.9998911180656389, 'J': 7.151514371381026e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4687326620857433e-06, 6: 1.5859189883317229e-06, 7: 0.9999959453483497}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677845535440277, 7.2: 0.03221544645597217}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 443:
  Our business model revolves around the comprehensive extraction of natural gas, where we leverage innovative technologies to enhance recovery rates. We utilize advanced seismic imaging and reservoir modeling to identify optimal drilling locations, ensuring that we maximize our resource extraction. Our team of geologists and engineers work collaboratively to monitor production and implement strategies that improve efficiency. Furthermore, we have established partnerships with local communities to promote responsible extraction practices, fostering goodwill and supporting economic development in the regions where we operate.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.497094564201263e-05, 'A': 3.511495015445088e-05, 'F': 1.2609412735886984e-05, 'B': 0.9998900092422012, 'J': 7.295449266560876e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010999075779882794}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 444:
  We specialize in the collection and processing of cork, sourced from sustainably managed cork oak forests. Our operations include the careful stripping of bark, which regenerates over time, ensuring the longevity of the trees. The harvested cork is then processed into a variety of products, including wine stoppers, flooring, and insulation materials. By promoting the environmental benefits of cork, such as its role in carbon sequestration, we aim to position our products as a sustainable alternative to synthetic materials in various industries.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9993219914063433, 'A': 3.613583927952966e-05, 'F': 5.093988897299484e-05, 'B': 0.00038060311231233616, 'J': 0.0002103297530918783}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0006780085936567426}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 445:
  Our company leverages cutting-edge technology to improve the efficiency of lignite pulverization processes. By adopting advanced machinery and automation, we can produce finely ground lignite that meets the specific requirements of our industrial clients. This precision in processing enhances the combustion efficiency of lignite in power generation, leading to reduced emissions and a more sustainable energy output. Our continuous investment in technology ensures that we remain a leader in providing high-quality lignite products tailored to the evolving needs of the energy sector.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9997625444807344, 'A': 1.2219868952387654e-05, 'F': 1.4616776465286207e-05, 'B': 7.617398495433695e-05, 'J': 0.00013444488889342404}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002374555192655725}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 57%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                           | 450/788 [00:28<00:21, 15.86it/s]

RAPS scores:

==================================================
Description 446:
  Our operations encompass both underground and surface mining of hard coal, where we leverage innovative liquefaction methods to enhance extraction efficiency. The coal mined is subjected to rigorous quality control measures, including sizing and grading, to ensure it meets the stringent standards required by our customers. We also provide comprehensive logistics solutions that facilitate the seamless transport of coal to power plants and industrial users. By integrating advanced technologies, we are able to streamline our processes, reduce waste, and improve the overall quality of our coal products.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5139141981356565e-05, 'A': 3.4380333153949326e-05, 'F': 1.237687984510571e-05, 'B': 0.9998909272889582, 'J': 7.176356061513449e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957303544532, 6: 1.3220980865402766e-06, 7: 2.947547460381177e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975256026147906, 5.2: 0.0024743973852094305}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 447:
  In the raising of sheep, our farm focuses on both meat and wool production, employing rotational grazing techniques to enhance pasture health and animal welfare. We utilize advanced breeding practices to produce high-quality lambs with desirable traits for meat production while also prioritizing the quality of our wool. Our shearing process is conducted with care to minimize stress on the animals, and we ensure that our wool is processed sustainably. Our products are marketed to both local butchers and textile manufacturers, highlighting our commitment to quality and ethical farming practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.018361215055790907, 'A': 0.06774242452988986, 'F': 0.014450053801418741, 'B': 0.8972139797675075, 'J': 0.002232326845392947}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1027860202324925}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 448:
  We engage in the production of firewood and wood chips for residential and commercial heating solutions. Our operations involve sourcing timber from responsibly managed forests, and we process the wood into various sizes to meet customer preferences. We also offer a delivery service, ensuring that our clients receive their orders promptly. By focusing on renewable energy sources, we contribute to reducing carbon footprints and promoting sustainable energy practices within our communities.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9996290867267575, 'A': 2.252508977999624e-05, 'F': 3.0162439334678904e-05, 'B': 0.0001366730715338032, 'J': 0.0001815526725941259}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00037091327324245693}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 449:
  We are dedicated to the growth and management of coppice and pulpwood, providing essential raw materials for various industries. Our operations involve careful monitoring and selective harvesting to ensure that the forest remains healthy and productive. Through innovative techniques, we optimize the growth cycles of our coppice, allowing for rapid regeneration and sustainable yields. Additionally, we offer consulting services for landowners looking to enhance their forest management practices, helping them to achieve both economic and environmental goals. Our commitment to responsible forestry practices ensures a steady supply of wood products while preserving the integrity of our natural resources.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0032119650886796537, 'A': 0.8198564538896375, 'F': 0.005846613697587933, 'B': 0.16959107928568895, 'J': 0.0014938880384059363}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18014354611036254}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 450:
  Our company is a leader in the production of mushroom spawn, providing high-quality mycelium to commercial growers and home cultivators. We employ sterile techniques in our propagation process to ensure that our spawn is free from contaminants and ready for successful cultivation. Our product range includes various mushroom species, catering to the growing demand for gourmet and medicinal mushrooms. We also offer workshops and resources to educate our customers on mushroom cultivation techniques, fostering a community of passionate growers. By focusing on quality and education, we aim to support the burgeoning interest in sustainable food production.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9986753276468165, 'A': 7.646492583412931e-05, 'F': 0.00013021336123713174, 'B': 0.0007391661569684164, 'J': 0.00037882790914391953}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0013246723531834537}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 455/788 [00:28<00:18, 18.15it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 451:
  This fishing operation is dedicated to the collection of aquatic plants, such as seaweed and kelp, from coastal waters. Using sustainable harvesting techniques, the company ensures that the collection process does not harm marine ecosystems. The harvested plants are processed into various products, including health supplements, culinary ingredients, and natural fertilizers. By capitalizing on the growing demand for plant-based products, the company has established a strong market presence, emphasizing the nutritional benefits and environmental sustainability of its offerings.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1006001327899981e-05, 'A': 0.9999068359580529, 'F': 3.888678230033802e-05, 'B': 2.9942767227882976e-05, 'J': 1.3328491091280438e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007290853609990607, 2: 0.0009404994019597387, 3: 0.9983304152370411}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9584147173324447, 3.2: 0.04158528266755543}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 452:
  We specialize in the raising of camels, focusing on both milk production and tourism. Our camels are raised in a natural habitat that mimics their native environment, ensuring their health and well-being. We produce high-quality camel milk, which is rich in nutrients and gaining popularity in health-conscious markets. Additionally, we offer camel rides and educational tours that highlight the importance of these animals in desert ecosystems. By promoting camel milk products and sustainable tourism, we create value for our community while educating consumers about the benefits of camel farming.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0263087804582671, 'A': 0.17788336097840535, 'F': 0.04128521715544959, 'B': 0.7504695543462889, 'J': 0.004053087061588931}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.24953044565371107}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 453:
  We specialize in the sustainable gathering of vegetable hair, sourcing this unique material from specific plant species known for their fibrous properties. Our products are utilized in the production of brushes, brooms, and other cleaning tools, catering to both commercial and residential markets. By focusing on eco-friendly harvesting techniques, we ensure that our supply chain supports sustainable practices and minimizes environmental impact. Our commitment to quality and sustainability has made us a preferred supplier for businesses looking to offer green alternatives to traditional cleaning products.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9997037091526697, 'A': 1.706179729259285e-05, 'F': 2.2230077579877437e-05, 'B': 9.59646763097245e-05, 'J': 0.0001610342961479785}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00029629084733029387}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 454:
  Our company is at the forefront of forest restoration initiatives, specializing in the replanting of native species in deforested areas. We collaborate with environmental organizations to develop comprehensive reforestation plans that not only restore ecosystems but also enhance carbon sequestration. Through our efforts, we aim to create resilient forests that provide habitat for wildlife and contribute to climate change mitigation.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.9334068403739114e-05, 'A': 0.999195631028799, 'F': 0.0005952440484525886, 'B': 0.00011994364544834843, 'J': 4.984720889625744e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008043689712009527}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 455:
  Our business focuses on the sustainable harvesting of firewood, providing a renewable energy source for residential and commercial use. We manage dedicated woodlots where we practice selective cutting and regeneration techniques to ensure a steady supply of firewood while maintaining forest health. Our operations include processing and packaging firewood for distribution, meeting the growing demand for eco-friendly heating solutions. By promoting the use of locally sourced firewood, we support community resilience and reduce reliance on fossil fuels.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0014555252932314095, 'A': 0.9513517478900239, 'F': 0.0029847914404370645, 'B': 0.04342223819180341, 'J': 0.0007856971845042313}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.04864825210997614}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 58%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                         | 458/788 [00:28<00:16, 20.57it/s]

RAPS scores:

==================================================
Description 456:
  As a leader in the production of utility poles and fence posts, our business is dedicated to sourcing high-quality roundwood from sustainably managed forests. We utilize state-of-the-art treatment processes to enhance the durability and longevity of our products, ensuring they withstand harsh environmental conditions. Our utility poles serve essential functions in power distribution, while our fence posts are favored for agricultural and residential applications. By prioritizing sustainable practices, we not only meet market demands but also contribute positively to the ecosystem.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9996323970434348, 'A': 2.1621187627713708e-05, 'F': 2.8472928008013765e-05, 'B': 0.00014352658327114736, 'J': 0.00017398225765839114}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00036760295656523834}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 457:
  Focused on the cultivation of other non-perennial crops, our business explores a variety of specialty crops, including herbs and spices. We employ organic farming methods to enhance flavor and quality while meeting the increasing consumer demand for natural ingredients. Our products are marketed to gourmet food producers and health-conscious consumers through both retail and online channels. We also engage in educational initiatives to promote the benefits of using fresh herbs and spices in everyday cooking, fostering a deeper appreciation for these crops.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.0009966540938601072, 'A': 0.9839512401242052, 'F': 0.002885983910455385, 'B': 0.011602508679739318, 'J': 0.0005636131917399545}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.016048759875794794}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 458:
  We are dedicated to the capture fishery sector, focusing on the collection of crustaceans such as lobsters and crabs. Our business employs a network of traps strategically placed in prime fishing locations, allowing for efficient harvesting while adhering to seasonal regulations. We prioritize sustainability by participating in local conservation efforts and ensuring our practices do not disrupt marine habitats. The freshly caught crustaceans are processed and packaged for distribution to high-end seafood retailers, where they are celebrated for their quality and taste.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.002319245495691626, 'A': 0.845060291633164, 'F': 0.0031361764820592598, 'B': 0.14830021354995623, 'J': 0.001184072839128823}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15493970836683602}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 459:
  Our company is a key player in the iron ore mining sector, with a focus on both extraction and beneficiation processes. We utilize advanced mining techniques to ensure maximum efficiency and minimal environmental impact. Our beneficiation operations include state-of-the-art facilities that employ gravity separation and flotation methods to enhance the quality of the iron ore we produce. Additionally, we invest in research and development to explore new agglomeration techniques, such as sintering and pelletizing, that improve the usability of our products in steel production. Our commitment to innovation drives our success in a competitive market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.516028168119376e-05, 'A': 3.425666994839145e-05, 'F': 1.2338985958766971e-05, 'B': 0.9998911034010949, 'J': 7.140661316761428e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.503729405284166e-06, 6: 1.5665248913015642e-06, 7: 0.9999959297457034}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677821785130754, 7.2: 0.032217821486924585}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 59%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                        | 461/788 [00:28<00:20, 16.12it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 460:
  We are committed to the sustainable mining of hard coal, employing both underground and surface techniques to extract valuable resources. Our operations include the use of liquefaction methods to enhance coal recovery while minimizing environmental impact. Once extracted, the coal undergoes rigorous cleaning and grading processes at our state-of-the-art facilities, ensuring that we deliver high-quality products to our customers. Our focus on innovation and sustainability drives our business model, allowing us to meet the growing demand for clean energy solutions while adhering to environmental regulations.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.492986886097763e-05, 'A': 3.440714178754992e-05, 'F': 1.2368100567059779e-05, 'B': 0.9998911188273412, 'J': 7.1760614433042405e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957201971438, 6: 1.3204354265826677e-06, 7: 2.9593674297194625e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975288630174873, 5.2: 0.002471136982512553}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 461:
  As a prominent player in crude petroleum extraction, we focus on maximizing the efficiency of our operations through the use of advanced technologies. Our exploration efforts are supported by sophisticated geological modeling and data analytics, allowing us to identify and develop new oil fields effectively. We prioritize environmental stewardship by implementing comprehensive risk management strategies and investing in renewable energy initiatives that complement our core business. Our dedication to innovation ensures that we remain competitive in a rapidly evolving energy landscape.1. Our company specializes in the extraction of crude petroleum, utilizing advanced drilling techniques and cutting-edge technology to maximize efficiency and minimize environmental impact. We operate several offshore and onshore drilling rigs, employing a skilled workforce trained in the latest safety and operational protocols. Our commitment to sustainability drives us to implement innovative extraction methods that reduce waste and enhance recovery rates. By leveraging data analytics and real-time monitoring systems, we optimize production processes, ensuring that we meet both market demand and regulatory standards while contributing to energy security.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5236167087009855e-05, 'A': 3.505127847630877e-05, 'F': 1.2573308540785521e-05, 'B': 0.9998898507606394, 'J': 7.288485256724736e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011014923936059073}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 462:
  Our business is dedicated to the sustainable harvesting of nuts, specifically walnuts and hazelnuts, from wild and cultivated sources. We prioritize organic farming practices, ensuring that our nuts are free from pesticides and chemicals. Our processing facilities are equipped with state-of-the-art technology that preserves the nutritional value and flavor of the nuts. We distribute our products through health food stores and online platforms, emphasizing the health benefits of our nuts. Additionally, we engage in community outreach programs to educate consumers about the importance of sustainable nut harvesting and its impact on the environment.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.01042875492362293, 'A': 0.017835264066720417, 'F': 0.004221190075224195, 'B': 0.9665353565095814, 'J': 0.000979434424851066}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.033464643490418555}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                                                        | 464/788 [00:28<00:18, 17.79it/s]

RAPS scores:

==================================================
Description 463:
  Our company specializes in the production of vegetative planting materials, focusing on the cultivation of high-quality seedlings and cuttings for both ornamental and agricultural use. We utilize advanced propagation techniques, such as tissue culture, to ensure the health and vigor of our plants. Our extensive product range includes a variety of flowering plants, shrubs, and turf grasses, all grown in environmentally controlled conditions. We also provide educational resources and workshops to help our customers understand best practices for plant care and maintenance, fostering a deeper appreciation for horticulture and sustainability.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.999588306959111, 'A': 2.5112435927755796e-05, 'F': 3.6711439024956486e-05, 'B': 0.0001417888001873321, 'J': 0.0002080803657489626}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00041169304088894965}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 464:
  Focused on the mining of nickel and cobalt ores, our operations are designed to support the growing demand for these metals in the battery and aerospace industries. We utilize sustainable mining practices that prioritize environmental protection and community engagement. Our processing techniques are optimized for high recovery rates, ensuring that we deliver high-quality nickel and cobalt products to our clients. Additionally, we invest in research and development to innovate our extraction processes, aiming to reduce costs and improve efficiency while maintaining our commitment to sustainability.1. Our company specializes in the extraction and processing of uranium ore, leveraging advanced mining techniques to ensure minimal environmental impact. We operate several mines across North America, utilizing state-of-the-art technology to enhance ore recovery rates. In addition to mining, we invest in research and development to innovate more efficient extraction methods and improve safety protocols for our workforce. Our commitment to sustainability drives us to implement rigorous monitoring systems to mitigate the ecological footprint of our operations, while our high-quality uranium products supply the growing demand for clean energy solutions.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5177570811370126e-05, 'A': 3.42419956811307e-05, 'F': 1.2337103126089025e-05, 'B': 0.9998910874772559, 'J': 7.155853125320177e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4507002135970353e-06, 6: 1.6125612777892397e-06, 7: 0.9999959367385085}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03519049690193999, 7.2: 0.96480950309806}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                      | 469/788 [00:29<00:21, 15.05it/s]

RAPS scores:

==================================================
Description 465:
  Our company specializes in the production of live plants for the horticultural industry, focusing on both ornamental and edible varieties. We employ advanced propagation techniques to ensure that our plants are healthy and ready for market. Our commitment to sustainability drives us to implement eco-friendly practices throughout our operations, from sourcing materials to growing methods. We also offer educational resources to help our clients succeed in their gardening endeavors, promoting a culture of sustainability and environmental stewardship.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.717136126719078, 'A': 0.017174253261875255, 'F': 0.0894301324792193, 'B': 0.16577008784395006, 'J': 0.010489399695877423}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.282863873280922}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 466:
  We focus on the sustainable gathering of acorns and horse chestnuts, which are processed for use in animal feed and natural remedies. Our operations involve careful collection to ensure the viability of the trees and surrounding ecosystems. We partner with local farmers and herbalists to create products that promote health and wellness, emphasizing the nutritional benefits of these wild nuts. Our commitment to sustainable practices not only supports local agriculture but also educates consumers about the value of wild-harvested ingredients.1. Our company specializes in the sustainable gathering of wild mushrooms and truffles, focusing on premium, high-quality products sourced from diverse forest ecosystems. We employ a network of skilled foragers trained in sustainable harvesting practices to ensure the preservation of natural habitats. Our offerings include a variety of gourmet mushrooms and truffles that are sold directly to high-end restaurants and specialty food retailers. We also provide educational workshops for aspiring foragers, promoting awareness of biodiversity and the importance of responsible sourcing in the culinary world.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0004359721109305638, 'A': 0.993733495480405, 'F': 0.0022554554700862906, 'B': 0.0032615317132448415, 'J': 0.00031354522533321604}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006266504519594984}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 467:
  Our business model revolves around the sustainable cultivation of timber and related products. We focus on the replanting and conservation of forest areas, implementing practices that enhance biodiversity and forest health. Our operations include the management of coppice and the production of firewood, catering to both local markets and larger industrial needs. By fostering partnerships with environmental organizations, we promote sustainable forestry initiatives that benefit both the economy and the environment.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00015852630930444692, 'A': 0.9977456056276623, 'F': 0.0008147910333994988, 'B': 0.001145174889551814, 'J': 0.00013590214008203438}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0022543943723376536}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 468:
  Our company is engaged in the extraction of natural gas, utilizing cutting-edge technologies that enhance the efficiency and safety of our drilling operations. We are committed to sustainable practices, employing gas desulphurization techniques that not only improve product quality but also align with environmental regulations. Our processing facilities are equipped with advanced separation technologies that allow us to maximize the recovery of liquid hydrocarbon fractions. By integrating these processes, we create value for our stakeholders while ensuring a reliable supply of energy to meet growing demand.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.504963749547285e-05, 'A': 3.459952225398213e-05, 'F': 1.2448008020264086e-05, 'B': 0.9998907064897202, 'J': 7.196342509976577e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7625145658628874e-06, 6: 0.9999964306290143, 7: 1.806856419712038e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979704442467712, 6.1: 0.0020295557532287243}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 60%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                     | 475/788 [00:29<00:15, 19.72it/s]

RAPS scores:

==================================================
Description 469:
  We are committed to the cultivation of spices and aromatic crops, including basil, oregano, and saffron. Our farms utilize organic farming methods to ensure the purity and quality of our spices, which are harvested at their peak flavor. We focus on value-added processing, offering dried, ground, and blended spice products that cater to both retail and foodservice markets. Our innovative packaging solutions preserve freshness and extend shelf life, making our products appealing to consumers. Additionally, we engage in research to develop new spice varieties that meet evolving culinary trends, positioning us as a leader in the specialty spice market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.5515763825945919, 'A': 0.005495910968717105, 'F': 0.010800849540240767, 'B': 0.42875682122139525, 'J': 0.0033700356750549667}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.44842361740540815}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 470:
  Our company focuses on the production of firewood, catering to both residential and commercial markets. We source our wood from local forests, ensuring that our operations support the local economy while promoting sustainable forestry practices. Our firewood is seasoned and packaged to meet the needs of our customers, who value convenience and quality. We also offer delivery services, making it easier for clients to access our products. By prioritizing customer satisfaction and sustainability, we have established a strong reputation in the community as a reliable supplier of eco-friendly firewood.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.10132780551934616, 'A': 0.008781966772474599, 'F': 0.008116601337048715, 'B': 0.8795614743655521, 'J': 0.0022121520055784134}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1204385256344479}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 471:
  We provide comprehensive logistical solutions for the transportation of lignite, ensuring that our clients receive their shipments on time and in optimal condition. Our fleet of specialized vehicles is designed to handle the unique challenges associated with lignite transport, including bulk handling and weight restrictions. We also offer customized solutions that cater to the specific needs of our customers, including just-in-time delivery and inventory management services. Our expertise in logistics not only enhances the efficiency of lignite distribution but also strengthens our relationships with clients across various sectors.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9179059019572823, 'A': 0.0006066736726812066, 'F': 0.013186989282189423, 'B': 0.0010719004312466083, 'J': 0.06722853465660056}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08209409804271772}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 472:
  Our business focuses on the gathering of vegetable hair, such as coir and sisal, which are sourced from wild-growing plants. These natural fibers are processed into a range of eco-friendly products, including ropes, mats, and brushes, appealing to consumers seeking sustainable alternatives to synthetic materials. We emphasize fair trade practices, ensuring that local communities benefit from the harvesting and processing of these fibers. By promoting the use of vegetable hair in various applications, we contribute to reducing plastic waste and encouraging environmentally responsible choices.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.4323207081705391, 'A': 0.02698253211471405, 'F': 0.06287387120500988, 'B': 0.46809375472389214, 'J': 0.009729133785844769}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5319062452761079}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 473:
  Our company operates in the niche market of restocked water bodies, focusing on the sustainable fishing of species that have been reintroduced to local lakes and rivers. By collaborating with environmental agencies, we help monitor the health of these ecosystems while providing a source of fresh fish for local communities. Our fishing practices include catch-and-release techniques and selective harvesting to ensure that populations remain stable. We also offer guided fishing tours, educating participants about the importance of conservation and responsible fishing practices, thereby fostering a deeper appreciation for aquatic ecosystems.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 2.1321576011859556e-05, 'A': 0.9998087158228162, 'F': 7.746994608284664e-05, 'B': 6.906816441430147e-05, 'J': 2.3424490674714982e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00019128417718383695}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 474:
  Our business is centered around the sustainable harvesting of nuts, particularly walnuts and hazelnuts, from local orchards and wild groves. We prioritize organic farming practices to ensure that our nuts are free from pesticides and chemicals. After harvesting, we employ advanced drying and packaging techniques to maintain freshness and flavor. Our products are sold directly to consumers through online platforms and specialty stores, as well as to food manufacturers looking for high-quality nut ingredients. By promoting sustainable agriculture and supporting local farmers, we contribute to the health of both our customers and the environment.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.014344187726210773, 'A': 0.044817264486950475, 'F': 0.008545802138370176, 'B': 0.9306536207136761, 'J': 0.0016391249347925288}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.06934637928632392}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                    | 478/788 [00:29<00:15, 20.62it/s]

RAPS scores:

==================================================
Description 475:
  This organization operates a network of commercial fishing boats that focus on harvesting a diverse range of species from both coastal and offshore waters. They utilize a combination of traditional fishing techniques and modern technology, such as GPS and fish finders, to optimize their catch while adhering to sustainable practices. The company is dedicated to transparency in their operations, providing customers with information about the origins of their seafood and the methods used in harvesting. Their commitment to sustainability is reinforced through partnerships with environmental groups, ensuring that their fishing practices contribute positively to marine conservation efforts.1. Our company specializes in marine fishing, focusing on sustainable practices to harvest a diverse range of fish species from both coastal and offshore waters. Utilizing advanced trawling techniques and eco-friendly nets, we aim to minimize bycatch while maximizing our yield. Our fleet is equipped with state-of-the-art sonar technology to locate schools of fish efficiently, ensuring that we operate within sustainable quotas. We also engage in partnerships with local fisheries to promote responsible fishing practices and contribute to the restoration of marine ecosystems. The fish we catch are processed on-site and distributed to local markets, emphasizing freshness and quality for our consumers.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 2.6282007535107968e-05, 'A': 0.9997629155855241, 'F': 8.030636805701526e-05, 'B': 0.0001026568675106318, 'J': 2.7839171373141646e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00023708441447589657}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 476:
  Our company is a leader in the gathering and production of wood for energy, focusing on sustainable practices that minimize waste. We collect biomass from forest residues and other wood waste, converting it into renewable energy sources such as wood pellets and chips. Our state-of-the-art processing facilities ensure that the wood is transformed efficiently while adhering to stringent environmental standards. By providing an alternative to fossil fuels, we contribute to a greener energy landscape and help our clients reduce their carbon footprint.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.09136533242892907, 'A': 0.0037381635203086764, 'F': 0.003261530278020307, 'B': 0.9003933890312976, 'J': 0.0012415847414443226}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09960661096870238}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 477:
  Specializing in the cultivation of various non-perennial crops, our operations encompass a wide range of fruits and vegetables. We utilize hydroponic systems to maximize space and yield, allowing us to produce high-quality products year-round. Our commitment to sustainability is reflected in our use of renewable energy sources and water conservation techniques. We actively participate in community-supported agriculture (CSA) programs, connecting consumers directly with our farm and promoting local food systems.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.2261898445491334, 'A': 0.03427965691928274, 'F': 0.07349202800724446, 'B': 0.6586866663227088, 'J': 0.007351804201630593}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3413133336772912}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 478:
  Our company is at the forefront of lignite mining, utilizing innovative techniques to extract and process this vital resource. We operate extensive surface and underground mining sites, where we implement advanced liquefaction methods to maximize output. Post-extraction, our facilities are equipped for washing and dehydrating lignite, ensuring that it meets stringent quality standards for various applications. We also prioritize efficient storage solutions, utilizing modern warehousing technologies to facilitate the safe and effective transport of our products. Our commitment to operational excellence and environmental stewardship drives our continuous improvement initiatives in all aspects of our business.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.469814746095412e-05, 'A': 3.458894556456649e-05, 'F': 1.242295401650327e-05, 'B': 0.9998911002839002, 'J': 7.189669057699699e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957403301241, 6: 1.351418701071454e-06, 7: 2.9082511748729736e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002355280745004237, 5.2: 0.9976447192549956}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                    | 481/788 [00:29<00:21, 14.43it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 479:
  Our organization is dedicated to the mining of aluminum ores, utilizing advanced bauxite extraction techniques that prioritize efficiency and sustainability. We have implemented a closed-loop water system in our operations to reduce water consumption and protect local ecosystems. Our processing plants are equipped with cutting-edge technology that allows for the production of high-quality aluminum products used in various industries, from aerospace to packaging. Through ongoing research and development, we strive to improve our extraction methods and reduce energy consumption, reinforcing our commitment to environmental stewardship.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.552580183876551e-05, 'A': 3.410157892744506e-05, 'F': 1.2300450492538705e-05, 'B': 0.9998909639126181, 'J': 7.108256123112217e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4656820982192664e-06, 6: 1.5944182002010194e-06, 7: 0.9999959398997015}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03510487735273399, 7.2: 0.964895122647266}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 480:
  Our company is dedicated to the mining of hard coal, where we leverage both traditional and innovative extraction methods to ensure a steady supply of high-grade coal. We operate several mines across diverse geographical regions, each equipped with the latest technology for efficient coal recovery. Our processing plants utilize advanced cleaning and sizing techniques that enhance the coal's marketability by improving its calorific value. Additionally, our commitment to safety and environmental stewardship is evident in our operations, as we implement best practices to minimize our ecological footprint while delivering quality products to our clients.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.514102421124571e-05, 'A': 3.426208485398131e-05, 'F': 1.2340550929230139e-05, 'B': 0.9998910880438046, 'J': 7.168296200968411e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957267442982, 6: 1.3280994429140234e-06, 7: 2.9451562589341945e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975284480601405, 5.2: 0.0024715519398594323}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                   | 484/788 [00:30<00:18, 16.34it/s]

RAPS scores:

==================================================
Description 481:
  We specialize in the collection of balata and other rubber-like gums, tapping into the rich biodiversity of our tropical forests. Our team of skilled gatherers is trained in traditional harvesting methods that respect the trees and promote regeneration. The gums we collect are processed for various applications, including adhesives and specialty coatings. By focusing on sustainable practices, we not only provide high-quality raw materials but also contribute to the preservation of forest ecosystems and the livelihoods of local communities.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.14875468069321499, 'A': 0.0070858215695132456, 'F': 0.008142557724708628, 'B': 0.833492610223032, 'J': 0.0025243297895312213}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.166507389776968}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 482:
  Engaging in the gathering of forest harvesting residues, our business transforms what would otherwise be waste into valuable energy resources. We collect branches, leaves, and other by-products from logging operations, processing them into wood chips and pellets for biomass energy production. This not only reduces waste but also provides a renewable energy source for heating and electricity generation. Our partnerships with energy companies highlight our commitment to supporting the transition to sustainable energy solutions while promoting responsible forest management practices.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.000490555664686041, 'A': 0.002385205720528324, 'F': 0.00022995814716001973, 'B': 0.9967880207480632, 'J': 0.00010625971956230824}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003211979251936836}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 483:
  We are dedicated to the extraction and processing of iron ore, focusing on maximizing ore recovery through innovative mining techniques. Our operations include extensive beneficiation processes such as washing, grinding, and magnetic separation to produce high-quality iron concentrates. We also invest in research to develop new technologies that can enhance our operational efficiency and reduce environmental impact. In addition to our mining activities, we provide technical consultancy services to assist other companies in improving their extraction and processing methods, contributing to the overall advancement of the industry.1. Our company specializes in the extraction and processing of high-grade iron ores, utilizing advanced mining techniques to ensure efficiency and sustainability. We operate several mines equipped with state-of-the-art machinery that enhances ore recovery rates while minimizing environmental impact. Our beneficiation processes include crushing, grinding, and magnetic separation, allowing us to produce iron concentrates that meet the stringent quality requirements of steel manufacturers. By investing in innovative technologies and adhering to best practices in resource management, we are committed to delivering premium iron products that contribute to the global steel supply chain.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.638481177274946e-05, 'A': 3.3999443196761453e-05, 'F': 1.2317076754888734e-05, 'B': 0.9998901355230163, 'J': 7.163145259230912e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010986447698368984}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 484:
  Our business model revolves around the sustainable harvesting of roundwood for various industrial applications. We employ advanced technology in our logging operations to ensure that we maximize yield while minimizing environmental impact. Our focus on quality control allows us to produce logs that meet the specific needs of our clients, whether for construction, paper manufacturing, or other uses. Additionally, we are committed to continuous improvement, investing in training and equipment to enhance our operational efficiency.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.00019453629685765915, 'A': 0.00017503425337922474, 'F': 4.980725479460108e-05, 'B': 0.9995567970729747, 'J': 2.3825121993709053e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00044320292702526576}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 485:
  Our lignite supply chain is supported by a robust network of partnerships with transportation and logistics providers. This collaboration allows us to streamline the movement of lignite from extraction sites to processing facilities and ultimately to our customers. By leveraging technology for real-time tracking and efficient route planning, we ensure that our clients receive their orders promptly and reliably. Our focus on logistics excellence is a key differentiator in the competitive lignite market, reinforcing our commitment to customer satisfaction.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 8.353422413721624e-05, 'A': 4.954756746406715e-05, 'F': 1.9036680443600786e-05, 'B': 0.9998368155244391, 'J': 1.1066003516161079e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00016318447556085136}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                  | 489/788 [00:30<00:19, 15.72it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 486:
  The company specializes in the cultivation of various vegetables, focusing on both traditional and exotic varieties to meet diverse consumer preferences. By employing hydroponic systems and vertical farming techniques, the firm maximizes space and resource efficiency, producing high-quality vegetables year-round. The harvested crops are sold directly to consumers through local farmers' markets and online platforms, promoting farm-to-table initiatives. Additionally, the company engages in community outreach programs to educate consumers on the benefits of fresh, locally sourced produce.
True: section=A, division=1, class=1.1
Section set: ['A']
Section probs: {'C': 1.0417568558513917e-05, 'A': 0.9999100390326497, 'F': 3.8863828031310555e-05, 'B': 2.798450092471543e-05, 'J': 1.2695069835879534e-05}
Division sets: {'A': ['1']}
Division probs: {'A': {1: 0.9982054677656161, 2: 0.0010570791359912869, 3: 0.0007374530983924854}}
Class sets: {'1': ['1.1']}
Class probs: {'1': {1.2: 0.006058879975976457, 1.4: 0.005926456142617025, 1.3: 0.0030469090769042763, 1.1: 0.9849677548045022}}
Final output: {'type': 'class_level', 'codes': ['1.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 487:
  Our company focuses on the sustainable production of roundwood for both industrial and energy applications. We harvest timber from certified forests, ensuring that our practices support biodiversity and ecosystem health. The logs we produce are primarily directed towards the manufacturing of utility poles and other structural components. Additionally, we process wood residues into biomass fuel, providing a renewable energy source for local communities. Our commitment to sustainability and quality has established us as a leader in the market, meeting the needs of diverse customers while promoting responsible forest management.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9838935773487179, 'A': 0.0004773351449374975, 'F': 0.0007738395620355175, 'B': 0.013994075554711877, 'J': 0.0008611723895972064}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01610642265128215}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 488:
  Our company specializes in the mining of cobalt and lithium ores, essential components for the battery industry. Utilizing innovative extraction methods, we ensure high recovery rates while minimizing environmental impact. Our operations are supported by a strong commitment to research and development, where we explore new technologies for ore processing and recycling. We collaborate with leading technology firms to enhance the efficiency of battery materials, contributing to the advancement of electric vehicles and renewable energy solutions. By prioritizing sustainability and responsible sourcing, we aim to lead the way in the transition to a greener economy.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5294264961251124e-05, 'A': 3.4249087592867764e-05, 'F': 1.2332481880605929e-05, 'B': 0.9998909918167513, 'J': 7.132348813975765e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.451805956622853e-06, 6: 1.6064330608465256e-06, 7: 0.9999959417609826}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035165888855645464, 7.2: 0.9648341111443547}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                | 496/788 [00:30<00:13, 21.66it/s]

RAPS scores:

==================================================
Description 489:
  Our company is dedicated to the extraction of crude petroleum, focusing on maximizing recovery from existing fields through the use of enhanced oil recovery techniques. We employ a multidisciplinary team of geologists, engineers, and environmental specialists to ensure that our extraction processes are efficient and sustainable. By investing in research and development, we continuously seek to improve our methodologies, integrating new technologies that reduce our environmental impact. Our commitment to corporate social responsibility drives us to engage with local communities, ensuring that our operations contribute positively to their economic development.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.503077314475995e-05, 'A': 3.472493801761632e-05, 'F': 1.2460777609626381e-05, 'B': 0.999890576347206, 'J': 7.207164021897441e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010942365279398292}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 490:
  Our company focuses on the capture of freshwater fish, particularly in stocked ponds and lakes, where we employ a mix of netting and angling techniques to ensure a steady supply of fish for recreational fishing. We work closely with local communities to manage these water bodies sustainably, providing educational resources on fish conservation and best practices for anglers. Our commitment to quality is evident in our processing methods, which prioritize freshness and flavor. We also organize fishing tournaments that promote community engagement and awareness of the importance of maintaining healthy aquatic ecosystems.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 3.220986909837735e-05, 'A': 0.9996934205507774, 'F': 0.00010295994964771325, 'B': 0.00013799622523483156, 'J': 3.341340524167525e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003065794492226326}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 491:
  We focus on the cultivation of fiber crops, particularly cotton, where we employ innovative agronomic practices to enhance yield and fiber quality. Our operations include a comprehensive seed development program aimed at producing drought-resistant varieties that thrive in varying climatic conditions. We maintain strong relationships with textile manufacturers, ensuring a steady supply of high-quality cotton for fabric production. Additionally, we are committed to sustainable practices, implementing water conservation techniques and promoting fair labor practices throughout our supply chain.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.22931416782719005, 'A': 0.017933344787117132, 'F': 0.026856716774911676, 'B': 0.7211061817955396, 'J': 0.004789588815241431}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.27889381820446035}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 492:
  We operate a comprehensive logging business that sources roundwood from managed forests. Our operations include selective logging practices that prioritize the health of the forest and the regeneration of tree populations. We supply premium logs for the production of furniture and building materials, while also collecting wood residues that are converted into eco-friendly charcoal. This dual approach not only supports local economies but also promotes sustainable forestry practices.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.00035144582282833003, 'A': 0.9910535298294865, 'F': 0.0007179283624693839, 'B': 0.0076190958918238095, 'J': 0.0002580000933920264}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.008946470170513532}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 493:
  We operate a tree nursery focused on producing high-quality saplings for reforestation and landscape enhancement projects. Our commitment to sustainable forestry practices ensures that our trees are grown in a manner that supports local ecosystems. We offer a wide selection of native and non-native species, catering to the diverse needs of our clients. Our knowledgeable staff provides expert advice on tree selection and care, helping customers make informed choices that contribute to healthier environments.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0001100362260521102, 'A': 0.9983956532088828, 'F': 0.0009436896202712506, 'B': 0.00044460139665211847, 'J': 0.00010601954814163035}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001604346791117206}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 494:
  We recognize the importance of community engagement in our lignite mining operations. Our company actively collaborates with local stakeholders to address concerns related to mining activities and to promote economic development in the regions where we operate. By fostering partnerships and investing in community projects, we aim to create a positive impact while ensuring that our operations are conducted responsibly and ethically.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.51874710104659e-05, 'A': 3.490999583058986e-05, 'F': 1.2545210011534228e-05, 'B': 0.9998901321697036, 'J': 7.225153443661108e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010986783029642844}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 495:
  Our company is committed to the extraction of crude petroleum through the application of cutting-edge technologies that enhance recovery rates and reduce operational costs. We conduct extensive geological research to identify promising drilling sites, employing both land and offshore rigs. Our focus on safety and environmental responsibility drives us to adopt practices that minimize our carbon footprint. The crude oil extracted is vital for the production of energy and petrochemical products, supporting both local economies and global markets.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5061382219436345e-05, 'A': 3.465936599012851e-05, 'F': 1.2441212789751151e-05, 'B': 0.9998906470017516, 'J': 7.191037249106792e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010935299824843536}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 63%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                | 499/788 [00:30<00:14, 20.08it/s]

RAPS scores:

==================================================
Description 496:
  Our company specializes in the aquaculture of aquatic plants, particularly seaweed, which is cultivated in both open water and land-based systems. We employ innovative cultivation techniques that maximize growth and minimize environmental impact, such as using nutrient-rich water from fish farming operations. Our seaweed products are harvested and processed for various applications, including food, cosmetics, and biofuels. We prioritize sustainable practices, ensuring that our farming methods contribute positively to marine ecosystems while providing valuable resources for diverse industries.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.010886554665073699, 'A': 0.8437066489429061, 'F': 0.03663176478507206, 'B': 0.10532647660269193, 'J': 0.0034485550042563182}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.15629335105709385}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 497:
  GreenRoots Forestry is focused on the sustainable growth of timber resources through innovative silvicultural practices. We engage in comprehensive forest management, including planting, thinning, and the operation of specialized tree nurseries. Our team employs cutting-edge techniques to monitor forest health and optimize growth conditions, ensuring that our timber stands are productive and resilient. By fostering partnerships with local communities, we not only supply high-quality timber and pulpwood but also contribute to regional reforestation initiatives that enhance ecological integrity and promote sustainable land use.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 1.672739813210296e-05, 'A': 0.999839419620181, 'F': 7.091124186521747e-05, 'B': 5.383334972626319e-05, 'J': 1.910839009554618e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00016058037981903084}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 498:
  We are engaged in the extraction of iron ore, focusing on both the mining and beneficiation processes. Our operations are characterized by the use of advanced machinery and techniques that enhance ore recovery and quality. We conduct thorough testing and analysis of our products to ensure they meet the specifications required by our customers in the steel industry. Our commitment to innovation extends to our consulting services, where we provide expertise in optimizing mining operations and implementing best practices for ore processing.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.528677143973252e-05, 'A': 3.4066511340339505e-05, 'F': 1.2285336557646854e-05, 'B': 0.9998912412138282, 'J': 7.120166834033468e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4765396966661778e-06, 6: 1.5797850372575486e-06, 7: 0.999995943675266}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677216008245255, 7.2: 0.032278399175474565}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 499:
  Our organization is dedicated to the cultivation of coppice and pulpwood, providing essential raw materials for the paper and bioenergy industries. We manage extensive tracts of land where we practice sustainable harvesting techniques, ensuring that our operations do not compromise the ecological balance of the forests. By investing in research and development, we continuously improve our methods of wood production, enhancing yield while minimizing environmental impact. Our commitment to sustainability is further demonstrated through partnerships with local communities, fostering economic growth while protecting forest ecosystems.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.007955968569766428, 'A': 0.7921511742541715, 'F': 0.012744919369920664, 'B': 0.1843423057041449, 'J': 0.002805632101996672}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.20784882574582852}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                              | 505/788 [00:31<00:13, 20.78it/s]

RAPS scores:

==================================================
Description 500:
  We engage in the production of roundwood for various manufacturing applications, emphasizing quality and sustainability in our operations. Our team utilizes advanced logging equipment to ensure efficient and responsible harvesting practices. The roundwood we produce is primarily used in the construction and furniture industries, where it is valued for its strength and durability. We collaborate with manufacturers to understand their needs and provide tailored solutions that enhance their production processes while promoting sustainable sourcing.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997694518533918, 'A': 1.3019943901515334e-05, 'F': 1.5540677112699034e-05, 'B': 7.108302540586721e-05, 'J': 0.0001309045001882574}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00023054814660816714}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 501:
  Our farm is dedicated to the raising of other livestock, including alpacas and llamas, focusing on fiber production and sustainable farming practices. We employ eco-friendly methods to manage our pastures, ensuring the health of our animals and the land. The fiber harvested from our animals is processed into high-quality textiles, which we sell at craft fairs and online. We also offer farm tours and workshops, educating visitors about the benefits of sustainable animal husbandry and the unique qualities of alpaca and llama fiber. This engagement helps us build a community around our farm and promotes awareness of sustainable practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.000888613242874771, 'A': 0.9839456233999995, 'F': 0.004521966754452722, 'B': 0.010102984471712591, 'J': 0.0005408121309603454}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01605437660000053}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 502:
  We are dedicated to the breeding and raising of exotic animals, focusing on conservation and educational outreach. Our facilities provide a safe haven for species that are often overlooked, and we collaborate with wildlife organizations to promote awareness of their habitats and challenges. Our breeding programs aim to maintain genetic diversity while providing educational programs for schools and community groups. By offering guided tours and interactive experiences, we engage the public in conversations about biodiversity and the importance of preserving these unique species for future generations.1. Our company specializes in the raising of dairy cattle, focusing on sustainable farming practices that enhance milk production while prioritizing animal welfare. We have implemented advanced breeding techniques to improve the genetic quality of our herd, ensuring high milk yields and superior nutritional content. Our state-of-the-art facilities include automated milking systems that streamline operations and maintain hygiene standards. Additionally, we invest in renewable energy sources, such as solar panels, to power our farms, reducing our carbon footprint. The milk produced is processed on-site and distributed to local dairies, ensuring freshness and supporting the regional economy.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00018644618888587103, 'A': 0.9976033131703789, 'F': 0.0010305118965432455, 'B': 0.0010195380154189772, 'J': 0.00016019072877318158}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0023966868296211308}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 503:
  Our business is dedicated to the raising of poultry, specializing in organic and free-range practices that cater to the increasing consumer demand for ethically sourced products. We implement rigorous health monitoring protocols to ensure the well-being of our flocks, while our feed is sourced from non-GMO grains to enhance the quality of our eggs and meat. Our processing facilities adhere to strict hygiene standards, allowing us to deliver fresh, high-quality poultry products to retailers and restaurants. By emphasizing transparency in our operations, we build trust with consumers who value sustainable and humane farming practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.02600599202694816, 'A': 0.4401538454005401, 'F': 0.06468301458597155, 'B': 0.46393092167848154, 'J': 0.005226226308058636}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5360690783215185}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 504:
  We operate in the natural gas sector, specializing in the extraction and processing of crude gaseous hydrocarbons. Our facilities are equipped with state-of-the-art technology for gas desulphurization, ensuring that our products meet the highest quality and environmental standards. We are committed to sustainable practices, focusing on reducing emissions and optimizing resource use throughout our operations. By fostering innovation and collaboration within the industry, we aim to enhance our extraction processes and contribute to the global shift towards cleaner energy solutions, ultimately delivering value to our customers and stakeholders.1. Our company specializes in the extraction of natural gas from both conventional and unconventional reservoirs. Utilizing advanced drilling techniques, including horizontal drilling and hydraulic fracturing, we optimize production rates while ensuring environmental sustainability. Our state-of-the-art processing facilities are designed to separate natural gas from condensates and other hydrocarbons efficiently. We also invest in innovative technologies for gas desulphurization, which allows us to meet stringent regulatory standards and deliver cleaner energy solutions to our customers. By leveraging data analytics and real-time monitoring, we enhance operational efficiency and reduce downtime, ultimately maximizing value for our stakeholders.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.584637338618528e-05, 'A': 3.4244107410011135e-05, 'F': 1.2408741076033188e-05, 'B': 0.9998902907253687, 'J': 7.210052759194753e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010970927463127556}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 505:
  With a strong emphasis on sustainability, our iron ore mining operations are designed to minimize environmental impact while maximizing efficiency. We utilize eco-friendly technologies in our beneficiation processes, ensuring that we produce high-quality iron ore with minimal waste. Our team of geologists and engineers work collaboratively to implement best practices in resource extraction and site rehabilitation. Additionally, we offer technical consultancy services to help other mining firms adopt sustainable practices, thereby promoting environmental responsibility across the industry.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5010678427335676e-05, 'A': 3.4393165192055145e-05, 'F': 1.2355041037983981e-05, 'B': 0.9998910895159222, 'J': 7.151599420385539e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4901763992859553e-06, 6: 1.5740680527086693e-06, 7: 0.9999959357555479}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677610522476348, 7.2: 0.032238947752365354}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 506:
  Our lignite mining operations are characterized by a commitment to quality and sustainability. We employ advanced mining techniques to extract lignite while minimizing environmental disruption. The extracted lignite is subjected to rigorous washing and dehydrating processes, improving its calorific value for energy production. Our logistics infrastructure is designed to facilitate efficient transportation, and we maintain secure storage facilities to ensure the integrity of our processed lignite. By prioritizing innovation, we continually enhance our operational efficiency and reduce our carbon footprint.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4877406494221126e-05, 'A': 3.44319098539487e-05, 'F': 1.2368366532470749e-05, 'B': 0.9998911650626031, 'J': 7.157254516297705e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957390372614, 6: 1.3436989311195102e-06, 7: 2.9172638074254957e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023562490038353877, 5.2: 0.9976437509961646}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 511/788 [00:31<00:15, 17.75it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 507:
  In the crude petroleum extraction sector, we focus on maximizing efficiency and minimizing environmental impact. Our operations utilize advanced drilling technologies, such as horizontal drilling, which allows us to access multiple reservoirs from a single location. By employing real-time monitoring systems, we can optimize drilling parameters and reduce resource waste. Our commitment to safety and environmental stewardship is reflected in our comprehensive risk management strategies and our proactive engagement with regulatory bodies.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4883261986895295e-05, 'A': 3.464016449834448e-05, 'F': 1.2453215993083991e-05, 'B': 0.9998908108045756, 'J': 7.2125529460864825e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7799254374457921e-06, 6: 0.9999963869745319, 7: 1.833100030672445e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020602763664430866, 6.1: 0.9979397236335569}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 508:
  Engaged in the raising of swine, our operation employs innovative genetics and nutrition strategies to produce premium pork products. We maintain a rigorous health management program to ensure the well-being of our animals, which contributes to the quality of our meat. Our facility is equipped with modern housing systems that provide optimal living conditions for the pigs, enhancing their growth and productivity. We also focus on traceability, allowing consumers to know the source of their meat, which strengthens our brand reputation and consumer trust.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.03455259939716659, 'A': 0.021559213366781804, 'F': 0.015936113174679634, 'B': 0.925785766278245, 'J': 0.0021663077831268833}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07421423372175495}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 509:
  Specializing in the mining of lignite, our company employs a variety of extraction techniques to ensure optimal resource recovery. We focus on enhancing the quality of our lignite through advanced washing and dehydrating processes. Our commitment to innovation extends to our transportation support activities, where we implement efficient logistics solutions that minimize costs and delivery times. By prioritizing quality and efficiency, we not only meet but exceed the expectations of our clients in the energy sector.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.476670488642765e-05, 'A': 3.490282044005279e-05, 'F': 1.2514293642690266e-05, 'B': 0.9998905649350283, 'J': 7.251246002702036e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010943506497174127}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 510:
  We specialize in the capture of crustaceans, particularly shrimp and crabs, through both trap and net fishing methods. Our operations are conducted in coastal waters, where we employ innovative baiting techniques to attract target species while minimizing impact on non-target organisms. Our commitment to sustainability is evident in our use of biodegradable materials for traps, which reduce environmental harm. We also engage in community outreach programs to educate local fishers on best practices for sustainable crustacean harvesting, ensuring the longevity of this vital resource for future generations.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00922284802659198, 'A': 0.5293970275648506, 'F': 0.015764722297110123, 'B': 0.442539480147776, 'J': 0.003075921963671302}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.47060297243514937}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                            | 514/788 [00:31<00:15, 17.24it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 511:
  Our operations in the hard coal mining sector are characterized by a blend of traditional and modern techniques aimed at maximizing output while minimizing environmental impact. We engage in both surface and underground mining, utilizing advanced machinery for efficient extraction. Our processing capabilities include thorough cleaning, sizing, and pulverizing of coal, which not only enhances its quality but also prepares it for various industrial applications. With a robust logistics network, we ensure that our coal is delivered promptly to clients, supporting their energy needs and contributing to their operational success.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.504869501266171e-05, 'A': 3.4157367775955474e-05, 'F': 1.2312388116416223e-05, 'B': 0.9998913478576332, 'J': 7.13369146178147e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957087096283, 6: 1.3266816130647616e-06, 7: 2.964608758717889e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975294324421136, 5.2: 0.0024705675578864947}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 512:
  Our company is at the forefront of developing advanced forestry technologies that enhance the efficiency of timber production. We utilize drone technology for aerial surveys of forested areas, enabling precise mapping of tree growth and health. This data-driven approach allows us to optimize planting schedules and improve resource allocation. Additionally, we have integrated remote sensing tools to monitor environmental conditions and assess the impact of climate change on our forests. By leveraging these technologies, we aim to streamline our operations while ensuring sustainable forest management practices.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0002011476259211082, 'A': 0.9971687894801214, 'F': 0.0005632535925246347, 'B': 0.0019044349626776947, 'J': 0.00016237433875509333}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0028312105198785575}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 513:
  Our firm is engaged in the extraction of crude petroleum, focusing on maximizing resource recovery through innovative extraction techniques. We utilize advanced seismic imaging and reservoir engineering to identify optimal drilling locations, ensuring efficient resource utilization. Our operations are supported by a dedicated team of geoscientists and engineers who continuously analyze production data to drive improvements. We also prioritize safety and environmental stewardship, implementing comprehensive training programs for our workforce and adhering to strict regulatory standards, thereby reinforcing our commitment to responsible energy production.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.494276914884484e-05, 'A': 3.4758419747809984e-05, 'F': 1.2469060779442907e-05, 'B': 0.999890622319626, 'J': 7.2074306980779025e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010937768037400097}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 514:
  Our business model centers around the extraction of crude petroleum, where we employ a combination of onshore and offshore drilling strategies. By integrating advanced geological survey technologies, we accurately pinpoint drilling sites, reducing the time and resources spent on exploration. Our operations are supported by a robust logistics network that facilitates the transportation of crude oil to refineries, where it is processed into various petroleum products. We also actively engage in community relations, ensuring that our operations benefit local economies and adhere to environmental regulations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.480698443370362e-05, 'A': 3.500454181082618e-05, 'F': 1.2557595879898172e-05, 'B': 0.9998903676114287, 'J': 7.263266447024979e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010963238857131241}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 517/788 [00:31<00:15, 17.02it/s]

RAPS scores:

==================================================
Description 515:
  We focus on the collection and distribution of wild berries, including blueberries, raspberries, and cranberries, which are harvested from organic farms and wild areas. Our operations involve meticulous quality control, from the picking process to packaging. We employ advanced freezing techniques to maintain freshness and nutritional value, allowing us to supply year-round to grocery chains and juice manufacturers. Additionally, we engage in community initiatives that promote berry-picking events, fostering a connection between consumers and the natural environment while enhancing our brand's visibility.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.07067432411784419, 'A': 0.01077790129986, 'F': 0.012164413725488415, 'B': 0.904239093315743, 'J': 0.0021442675410642577}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09576090668425696}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 516:
  Our operations focus on the extraction and processing of lignite, where we utilize both traditional and innovative mining techniques to ensure sustainable resource management. We employ advanced washing and dehydrating processes to improve the quality of our lignite, which is then stored in our state-of-the-art facilities designed to optimize product integrity. Our commitment to efficient logistics allows us to provide reliable transportation solutions, ensuring that our customers receive high-quality lignite in a timely manner, thus supporting their energy production needs.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.489011312891025e-05, 'A': 3.4392336005441466e-05, 'F': 1.2364265544846517e-05, 'B': 0.9998911796490964, 'J': 7.173636224481038e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957348976041, 6: 1.3417435737409808e-06, 7: 2.923358822299201e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002354795644244749, 5.2: 0.9976452043557553}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                           | 521/788 [00:32<00:17, 15.26it/s]

RAPS scores:

==================================================
Description 517:
  We are committed to the extraction of natural gas, focusing on both exploration and production. Our team employs advanced geological modeling techniques to identify potential drilling sites, ensuring that we target the most promising reserves. We utilize high-efficiency drilling rigs and automated systems to streamline our operations, reducing costs and enhancing safety. Additionally, our gas processing facilities are equipped with cutting-edge desulphurization technology, allowing us to produce cleaner natural gas that meets stringent environmental standards. Our dedication to innovation and sustainability positions us as a leader in the energy sector.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.496358297570437e-05, 'A': 3.461120722233451e-05, 'F': 1.2458673836936146e-05, 'B': 0.9998907692715909, 'J': 7.197264374189918e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.779305122271546e-06, 6: 0.9999963879252216, 7: 1.8327696560908639e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979789501075796, 6.1: 0.002021049892420449}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 518:
  Our business is centered around the cultivation of beverage crops, particularly coffee and tea. We source our beans and leaves from carefully selected farms that adhere to ethical farming practices, ensuring fair trade and organic certification. Our roasting and blending techniques are tailored to enhance the unique flavors of each batch, resulting in a diverse product line that appeals to discerning consumers. We also engage in community initiatives that support local farmers, fostering relationships that strengthen our supply chain.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.04877309309706299, 'A': 0.014654182250935982, 'F': 0.011740579931594263, 'B': 0.9228364410250016, 'J': 0.0019957036954051507}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07716355897499838}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 519:
  Our logging operations are designed to balance economic viability with environmental stewardship. We focus on selective logging, which allows us to extract valuable timber while preserving the overall health of the forest. Our team employs state-of-the-art equipment to ensure precision and efficiency in our harvesting processes. We also engage in reforestation efforts, planting new trees to replace those harvested, thus ensuring the sustainability of our operations. By maintaining transparency in our supply chain, we build trust with our customers, who value responsibly sourced wood products.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0022423733244059715, 'A': 0.7453396308664042, 'F': 0.003254749626549919, 'B': 0.24796862297741176, 'J': 0.0011946232052280291}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2546603691335958}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 520:
  Focused on the extraction of bauxite, our company plays a crucial role in the aluminum supply chain. We utilize advanced mining techniques to ensure efficient ore recovery while adhering to environmental regulations. Our processing plants convert bauxite into alumina, which is then supplied to aluminum smelters globally. We are committed to sustainability, implementing measures to rehabilitate mining sites and reduce water usage. Additionally, our research initiatives explore alternative uses for bauxite residue, contributing to a circular economy and enhancing our value proposition in the non-ferrous metals market.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.488338818735896e-05, 'A': 3.430878438400969e-05, 'F': 1.2333847384699214e-05, 'B': 0.9998913220413478, 'J': 7.151938696228716e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4879551746421026e-06, 6: 1.5685101414388854e-06, 7: 0.9999959435346838}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0351004964733625, 7.2: 0.9648995035266374}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 66%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                          | 523/788 [00:32<00:20, 12.90it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 521:
  As a leader in the hard coal mining sector, our operations focus on both surface and underground extraction methods. We leverage cutting-edge technology to ensure safe and efficient mining processes, while our dedicated teams work tirelessly to maintain compliance with environmental regulations. After extraction, our coal is meticulously cleaned and graded to enhance its quality. We also invest in advanced pulverizing techniques that allow us to produce a range of coal sizes tailored to our clients' needs. By prioritizing quality and reliability, we position ourselves as a trusted supplier for energy companies and industrial clients alike.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.487013736310912e-05, 'A': 3.436017366563563e-05, 'F': 1.235271034003582e-05, 'B': 0.9998912557361523, 'J': 7.161242478807148e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957226608219, 6: 1.3358334069666038e-06, 7: 2.941505770941751e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975261869091435, 5.2: 0.002473813090856505}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 522:
  We specialize in the mining of iron ores, employing innovative techniques to extract and process high-quality materials for the global market. Our operations include extensive geological exploration to identify rich ore deposits, followed by efficient extraction methods that prioritize safety and environmental stewardship. Our beneficiation processes utilize cutting-edge technology to enhance ore quality, ensuring that we deliver products that meet the highest industry standards. Our commitment to sustainability drives us to implement practices that reduce waste and promote the responsible use of natural resources.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.538124547674833e-05, 'A': 3.42283014309089e-05, 'F': 1.2341410829719103e-05, 'B': 0.9998909098752348, 'J': 7.139167028113936e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.448175574039179e-06, 6: 1.6332602863878124e-06, 7: 0.9999959185641396}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677046873050499, 7.2: 0.03229531269495006}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 525/788 [00:32<00:20, 12.95it/s]

RAPS scores:

==================================================
Description 523:
  Our business is dedicated to the sustainable gathering of vegetable hair, which is collected from wild plants known for their fibrous properties. We focus on sourcing materials that can be used in various applications, including brushes, brooms, and natural fiber products. By employing eco-friendly harvesting techniques, we ensure that our collection does not harm the environment, and we work closely with local artisans to create unique, handcrafted items. Our emphasis on sustainability and craftsmanship has allowed us to carve out a niche in the growing market for natural and biodegradable products.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9952795037481222, 'A': 0.00022627655937272807, 'F': 0.0005793812236076745, 'B': 0.003118623695525746, 'J': 0.0007962147733716545}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.004720496251877759}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 524:
  Our hard coal mining enterprise is dedicated to delivering high-quality coal through efficient extraction and processing methods. We employ a combination of underground and surface mining strategies to access coal reserves, ensuring safety and sustainability in our operations. After extraction, the coal undergoes rigorous cleaning and sizing processes to enhance its quality. Our advanced pulverizing techniques further improve the coal's performance in combustion applications, making it a preferred choice for energy companies. We are committed to continuous improvement and innovation, striving to meet the evolving demands of the energy market.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.483374145464808e-05, 'A': 3.457055305525189e-05, 'F': 1.2389413641589181e-05, 'B': 0.9998910062058911, 'J': 7.200085957409981e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957216004084, 6: 1.3317979069866601e-06, 7: 2.946601684741359e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975255696595484, 5.2: 0.0024744303404515334}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                          | 527/788 [00:32<00:22, 11.50it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 525:
  Our company leverages advanced data analytics to optimize our lignite mining and processing operations. By analyzing geological data, we can identify the most productive mining sites and tailor our extraction methods accordingly. Furthermore, we utilize predictive maintenance technologies to ensure our equipment operates at peak efficiency, reducing downtime and operational costs. This data-driven approach enhances our ability to deliver high-quality lignite products while maximizing profitability and sustainability.1. Our company specializes in the extraction and processing of lignite, utilizing both surface and underground mining techniques to ensure efficient resource recovery. We employ advanced liquefaction methods to enhance the quality of lignite, making it suitable for various industrial applications. Our state-of-the-art washing and dehydrating facilities further improve the coal's characteristics, enabling us to deliver a superior product to our clients. By investing in innovative technologies, we not only maximize yield but also minimize environmental impact, ensuring that our operations align with sustainable practices while meeting the growing demand for energy resources.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.5086996384769885e-05, 'A': 3.4470860204597515e-05, 'F': 1.2416714362305572e-05, 'B': 0.9998908155083055, 'J': 7.209920742698013e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957396552377, 6: 1.3374765609931895e-06, 7: 2.9228682013102095e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023566178086358897, 5.2: 0.9976433821913642}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 526:
  We are engaged in the production of high-quality roundwood for various applications, including pit-props and fencing materials. Our logging practices are rooted in sustainability, as we carefully select trees that allow for the regeneration of the forest ecosystem. The products we offer are tailored to meet the specific needs of our customers, with a focus on durability and performance. By maintaining strong relationships with local suppliers and customers, we ensure that our operations contribute positively to the community while providing essential materials for construction and agriculture.1. Our company specializes in sustainable logging practices, focusing on the selective harvesting of roundwood to supply the forest-based manufacturing industries. By employing advanced techniques and equipment, we ensure minimal impact on the ecosystem while maximizing yield. Our logs are processed into high-quality timber, which is then sold to manufacturers for furniture and construction purposes. Additionally, we engage in reforestation efforts, planting new trees to replace those harvested, thereby contributing to the long-term health of the forest and securing a renewable source of raw materials for future generations.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9995791396308018, 'A': 2.4887671024990775e-05, 'F': 3.119144842938677e-05, 'B': 0.00020793263101635373, 'J': 0.0001568486187272948}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0004208603691981949}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 527:
  Our company is committed to the sustainable management of forest resources, focusing on the conservation of existing timberlands while promoting responsible harvesting practices. We conduct regular assessments of forest health and implement management plans that prioritize ecological balance. By integrating modern technologies such as GIS mapping and remote sensing, we enhance our ability to monitor forest conditions and adapt our strategies to changing environmental factors.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.042739891033727e-05, 'A': 0.99979412857717, 'F': 9.598312699149235e-05, 'B': 6.598585481013142e-05, 'J': 2.3475042118133754e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00020587142283001736}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 528:
  Our organization is dedicated to the cultivation of firewood and biomass resources, responding to the increasing demand for renewable energy sources. We manage extensive tracts of land where we grow fast-growing tree species specifically for firewood production. Through careful management and sustainable harvesting practices, we ensure a continuous supply of high-quality firewood for residential and commercial use. Our commitment to replanting and maintaining healthy forest ecosystems allows us to contribute positively to the environment while meeting energy needs.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0004256874719732187, 'A': 0.9941254657497711, 'F': 0.002725463281467637, 'B': 0.00240919621074929, 'J': 0.00031418728603874256}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00587453425022888}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 68%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                        | 533/788 [00:33<00:16, 15.18it/s]

RAPS scores:

==================================================
Description 529:
  Our business is dedicated to the extraction of crude petroleum, leveraging both land and offshore drilling operations to tap into diverse oil fields. We utilize enhanced oil recovery techniques that allow us to maximize output from existing wells while minimizing waste. Our investment in digital technologies, such as IoT sensors and data analytics, enables real-time monitoring of production and predictive maintenance of equipment. This approach not only boosts our operational efficiency but also supports our goal of reducing the carbon footprint associated with oil extraction, aligning with global sustainability initiatives.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.470099029000897e-05, 'A': 3.492840364219371e-05, 'F': 1.249111205941157e-05, 'B': 0.9998906199392713, 'J': 7.259554737167881e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938006072869211}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 530:
  Our company is engaged in the mining of rare earth elements, which are critical for the production of high-tech devices and renewable energy technologies. We employ innovative extraction methods that reduce waste and enhance recovery rates, ensuring that we meet the growing demand for these essential materials. Our commitment to sustainability is reflected in our investments in research and development aimed at improving the efficiency of our mining processes. By collaborating with technology partners, we are also exploring new applications for rare earth materials, thereby creating value for both our stakeholders and the broader economy.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.592656602625457e-05, 'A': 3.400548800448608e-05, 'F': 1.2303273996111883e-05, 'B': 0.999890646824493, 'J': 7.117847480059695e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010935317550697654}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 531:
  Specializing in the gathering of lac and resins, we focus on sustainable practices that protect the ecosystems from which these materials are sourced. Our team collaborates with local harvesters to collect these natural products, which are then processed into high-quality lac for use in varnishes and dyes. We are committed to transparency in our supply chain, ensuring that our customers understand the origins of our products. By fostering relationships with artisans and manufacturers, we promote the use of traditional techniques that enhance the value of lac and resin in modern applications.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.07112892245614622, 'A': 0.003005836070585987, 'F': 0.0024149991720075104, 'B': 0.9223735468052114, 'J': 0.001076695496048679}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07762645319478856}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 532:
  As a prominent player in the natural gas extraction sector, our company focuses on leveraging technology to enhance production capabilities. We utilize advanced drilling techniques to access and extract crude gaseous hydrocarbons efficiently. Our operations include sophisticated facilities for draining and separating liquid hydrocarbon fractions, which are crucial for maximizing yield. Additionally, we prioritize gas desulphurization to ensure that our natural gas meets the stringent quality standards required by our customers. Our commitment to sustainability and technological advancement positions us as a leader in providing cleaner energy solutions.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.471592832928072e-05, 'A': 3.479239035469413e-05, 'F': 1.2469366204387998e-05, 'B': 0.9998907979285461, 'J': 7.2243865654525884e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7653962550262696e-06, 6: 0.9999964388198248, 7: 1.7957839203154193e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979702167873373, 6.1: 0.0020297832126626512}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 68%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                       | 538/788 [00:33<00:14, 17.75it/s]

RAPS scores:

==================================================
Description 533:
  We are dedicated to the collection and distribution of wild berries, focusing on organic and sustainably sourced varieties. Our operations involve a network of local pickers who gather seasonal berries, which are then processed and packaged for both retail and wholesale markets. We emphasize traceability and transparency in our supply chain, allowing consumers to know the origin of their products. In addition to fresh berries, we also produce value-added products such as jams and preserves, enhancing our product line while supporting local economies and promoting biodiversity in berry cultivation.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.025302976067112477, 'A': 0.5717478406679994, 'F': 0.07020693605288089, 'B': 0.32695233285858943, 'J': 0.005789914353417625}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.42825215933200056}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 534:
  Our operations revolve around the breeding and raising of sheep, with a strong emphasis on producing high-quality wool and meat. We practice rotational grazing to maintain pasture health and enhance the nutritional value of the feed for our flock. Our breeding program focuses on selecting for traits that improve wool quality and meat yield, ensuring that our products meet the demands of the textile and culinary markets. We also invest in modern shearing techniques that minimize stress on the animals while maximizing wool recovery. The wool is processed locally, allowing us to offer a range of sustainable textile products to eco-conscious consumers.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.012779536181812781, 'A': 0.3847400708311858, 'F': 0.03351757644220796, 'B': 0.5656572265785504, 'J': 0.00330558996624304}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.43434277342144956}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 535:
  Our business is focused on the cultivation of beverage crops, including coffee and tea, which are integral to many cultures worldwide. We source our coffee beans from sustainable farms that practice shade-grown agriculture, ensuring biodiversity and high-quality yields. Our tea plantations are managed with a commitment to organic farming, producing a range of herbal and traditional teas. We emphasize fair trade practices, ensuring that our farmers receive fair compensation for their products. By developing unique blends and flavors, we cater to discerning consumers looking for premium beverage options, enhancing our brand's reputation in the market.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.03663941544433025, 'A': 0.014086973011327894, 'F': 0.007603121910692395, 'B': 0.9399895865681455, 'J': 0.001680903065504063}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.06001041343185454}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 536:
  Our business is focused on the raising of poultry, specifically broilers and layers, to meet the growing demand for high-quality chicken and eggs. We utilize innovative housing systems that provide optimal living conditions for our birds, enhancing their health and productivity. Our feed formulation is tailored to ensure that the nutritional needs of our poultry are met, resulting in superior growth rates and egg production. We also invest in biosecurity measures to prevent disease, ensuring a safe and reliable supply chain. Our products are distributed to local grocery stores and restaurants, emphasizing freshness and quality.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0890116454788911, 'A': 0.10424934411164706, 'F': 0.1521563233294202, 'B': 0.6471941378016384, 'J': 0.007388549278403368}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.35280586219836163}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:

==================================================
Description 537:
  The organization is involved in the restocking of water bodies, collaborating with environmental agencies to replenish fish populations in local lakes and rivers. By breeding and releasing species such as salmon and catfish, the company plays a crucial role in restoring aquatic ecosystems. This initiative not only supports biodiversity but also enhances recreational fishing opportunities for the community. In addition, the company offers educational workshops on sustainable fishing practices, fostering awareness and responsibility among local anglers and promoting a culture of conservation.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.174504589806499e-05, 'A': 0.999899751884481, 'F': 4.42126071097515e-05, 'B': 3.0047247051796323e-05, 'J': 1.4243215459375275e-05}
Division sets: {'A': [3]}
Division probs: {'A': {1: 0.0007308674723015017, 2: 0.0009130884242589948, 3: 0.9983560441034396}}
Class sets: {}
Class probs: {}
Final output: {'type': 'class_level', 'codes': []}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 540/788 [00:33<00:14, 17.65it/s]

RAPS scores:

==================================================
Description 538:
  We are engaged in the operation of forest tree nurseries, focusing on the cultivation of diverse tree species to support both commercial forestry and ecological restoration initiatives. Our nurseries are equipped with advanced irrigation and nurturing systems that promote healthy seedling growth. We prioritize the use of native species to enhance local biodiversity and resilience against climate change. By supplying high-quality seedlings to various stakeholders, we play a crucial role in reforestation efforts and the sustainable management of forest resources.1. Our company specializes in sustainable forestry management, focusing on the cultivation and maintenance of timber resources. We engage in activities such as planting and replanting various tree species to ensure a healthy and diverse forest ecosystem. Through our advanced silviculture techniques, we optimize growth conditions and enhance timber quality. Our commitment to environmental stewardship includes implementing conservation practices that protect biodiversity while meeting the growing demand for timber products. Additionally, we operate tree nurseries that supply high-quality seedlings to both commercial and private landowners, contributing to reforestation efforts and promoting responsible forest management.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.787225105125653e-05, 'A': 0.9994725033677412, 'F': 0.0002415048827784126, 'B': 0.00018950622446954214, 'J': 4.8613273959515504e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.000527496632258817}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 539:
  We operate a seafood processing facility that focuses on the preparation and packaging of freshly caught fish and shellfish. Our state-of-the-art equipment ensures that our products meet the highest quality standards while maintaining their freshness. We prioritize traceability by sourcing our seafood from local fishermen who adhere to sustainable practices. Our commitment to quality extends to our distribution channels, where we supply restaurants and retailers with premium seafood, helping to elevate culinary experiences while supporting local economies.1. Our company specializes in marine fishing, focusing on sustainable practices that ensure the health of aquatic ecosystems. We operate a fleet of modern fishing vessels equipped with advanced sonar technology to locate schools of fish efficiently. Our primary catch includes various species of finfish and shellfish, which are processed on-site to maintain freshness. We also engage in partnerships with local communities to promote responsible fishing methods, ensuring that our operations support both the economy and the environment. By implementing traceability systems, we provide consumers with transparency about the origin of their seafood, enhancing their trust in our brand.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.02049751592152459, 'A': 0.006117130777703331, 'F': 0.003315875379892285, 'B': 0.9691687494461287, 'J': 0.0009007284747510884}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03083125055387126}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 540:
  We operate in the hard coal mining sector, where our focus is on maximizing extraction efficiency through innovative mining techniques. Our operations include both surface and underground mining, supported by a robust infrastructure for cleaning and sizing coal. We have implemented advanced pulverizing methods that allow us to produce a range of coal grades tailored for different industrial applications. Our commitment to quality control ensures that our products are not only competitive but also environmentally responsible, as we strive to minimize the impact of our operations on local ecosystems.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4902497106893224e-05, 'A': 3.4289383906741314e-05, 'F': 1.2327103714105311e-05, 'B': 0.9998913434177259, 'J': 7.137597546432373e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957296111386, 6: 1.3380908500416598e-06, 7: 2.932298011414015e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975279060423436, 5.2: 0.0024720939576563915}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                      | 545/788 [00:33<00:13, 18.68it/s]

RAPS scores:

==================================================
Description 541:
  GreenCanopy Forestry is a leader in sustainable timber cultivation, engaging in practices that promote the health and productivity of our forests. Our operations include the careful management of coppice and pulpwood, providing essential resources for various industries. We also focus on the establishment and maintenance of tree nurseries, where we cultivate seedlings for reforestation and commercial purposes. By implementing advanced silvicultural techniques, we enhance the quality of our timber while ensuring the ecological integrity of our forest tracts. Our holistic approach to forestry not only meets market needs but also supports environmental conservation efforts.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.5800050929492313e-05, 'A': 0.9997539387389994, 'F': 8.909298956471466e-05, 'B': 0.00010397255959717692, 'J': 2.7195660909087718e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00024606126100057413}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 542:
  We are committed to responsible logging practices that focus on the production of roundwood for various uses. Our operations include the harvesting of timber for construction, as well as the production of firewood for residential heating. We utilize modern technology to ensure that our processes are efficient and environmentally friendly. By prioritizing sustainability, we aim to provide high-quality wood products while maintaining the health of the forests we depend on for future generations.1. Our company specializes in sustainable logging practices, focusing on the careful harvesting of roundwood to supply local manufacturing industries. By employing advanced techniques and equipment, we ensure minimal environmental impact while maximizing yield. Our logs are processed into high-quality timber for construction and furniture production, meeting the growing demand for eco-friendly materials. Additionally, we collaborate with local communities to promote responsible forestry, enhancing both economic opportunities and forest conservation efforts.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.014226548935490173, 'A': 0.003883120785881605, 'F': 0.0016771996987904195, 'B': 0.9796188713699954, 'J': 0.0005942592098424359}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.02038112863000463}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 543:
  We operate a network of forest tree nurseries that specialize in the propagation of diverse tree species for various applications, including reforestation and landscaping. Our team employs cutting-edge horticultural practices to ensure the health and vitality of our seedlings. We also provide educational resources and workshops for local communities, emphasizing the importance of forestry in combating climate change and promoting biodiversity. By fostering a culture of sustainability, we empower individuals and organizations to participate in forest conservation efforts.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 5.0317398178454265e-05, 'A': 0.99919201160694, 'F': 0.0005375020735628553, 'B': 0.00016493267908665907, 'J': 5.523624223176218e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008079883930599552}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 544:
  We focus on the collection and distribution of wild berries, including blueberries, raspberries, and cranberries, which are sourced from organic farms and wild areas. Our operations include harvesting, sorting, and freezing the berries to maintain their freshness and nutritional value. We partner with local farmers and community groups to ensure fair practices and support local economies. Our products are sold directly to consumers through our online platform and at farmers' markets, where we emphasize the health benefits and culinary versatility of our wild berries.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.017001678912791408, 'A': 0.4539278861086745, 'F': 0.04185574870334501, 'B': 0.4831657034409241, 'J': 0.004048982834265061}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.516834296559076}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                     | 547/788 [00:33<00:16, 14.44it/s]

RAPS scores:

==================================================
Description 545:
  As a leader in the hard coal mining sector, our company focuses on employing innovative extraction techniques that reduce operational costs and enhance safety. We utilize both surface and underground mining methods, adapting our approach based on geological assessments to ensure optimal resource recovery. Our processing facilities are equipped with cutting-edge technology for cleaning, grading, and pulverizing coal, allowing us to produce a range of products tailored to meet the specific needs of our clients. By investing in research and development, we continually improve our processes, ensuring that we remain competitive while adhering to environmental regulations and contributing to sustainable mining practices.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5182719080044154e-05, 'A': 3.429264394951106e-05, 'F': 1.2341962753876712e-05, 'B': 0.9998910459040878, 'J': 7.136770128736475e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957232259566, 6: 1.338388844696362e-06, 7: 2.9383851985891995e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975284122036232, 5.2: 0.002471587796376709}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 546:
  In the hard coal mining sector, our company stands out for its comprehensive approach to resource extraction and processing. We employ a combination of underground and surface mining methods, utilizing state-of-the-art technologies to maximize coal recovery. Our processing operations focus on cleaning and sizing coal to meet the specific requirements of our customers, which include power plants and manufacturing facilities. By prioritizing safety and environmental sustainability, we ensure that our mining practices not only yield high-quality products but also contribute positively to the communities in which we operate.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.493128657362427e-05, 'A': 3.429555519962938e-05, 'F': 1.2323262465761126e-05, 'B': 0.999891297981109, 'J': 7.15191465200221e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957238279417, 6: 1.337384705751583e-06, 7: 2.9387873525435237e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997526648716133, 5.2: 0.0024733512838669472}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 547:
  We are involved in the cultivation of a diverse range of other perennial crops, including various medicinal herbs and ornamental plants. Our approach emphasizes biodiversity and sustainable practices, allowing us to produce crops that are both ecologically friendly and commercially viable. We utilize advanced propagation techniques to ensure the health and vigor of our plants, and our research team continuously explores new varieties to meet market demands. Our products are marketed through nurseries and specialty retailers, where consumers appreciate the quality and uniqueness of our offerings in the horticultural market.1. Our company specializes in the cultivation of premium grape varieties, focusing on both table grapes and those intended for wine production. We employ sustainable farming practices that enhance soil health and biodiversity while maximizing yield and quality. Our vineyards are strategically located in regions with optimal climates, allowing us to produce grapes with exceptional flavor profiles. We also invest in advanced irrigation systems and precision agriculture technologies to monitor crop health and optimize resource use. Additionally, we offer a range of value-added products, including dried grapes and grape juice, catering to diverse consumer preferences and expanding our market reach.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9539981049673533, 'A': 0.0018289487483944872, 'F': 0.005444856447886977, 'B': 0.03608238369794277, 'J': 0.0026457061384224365}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.046001895032646734}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 70%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 549/788 [00:34<00:17, 13.70it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 548:
  Specializing in the mining of hard coal, our business employs a comprehensive approach that includes both surface and underground extraction methods. We are committed to producing high-quality coal through rigorous cleaning, sizing, and grading processes that meet industry standards. Our advanced pulverizing technologies allow us to create a product that is not only efficient for transport but also suitable for a wide range of applications in the energy sector. By focusing on innovation and sustainability, we strive to enhance our production capabilities while minimizing our ecological footprint.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5605127736194926e-05, 'A': 3.410425263080712e-05, 'F': 1.232109709326829e-05, 'B': 0.9998908060274874, 'J': 7.1634950522550284e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995724674716, 6: 1.321112461132798e-06, 7: 2.9542128228053997e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975295716932296, 5.2: 0.002470428306770343}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 549:
  Our business is centered around the cultivation of oleaginous fruits, particularly olives and avocados, which are prized for their healthy fats and culinary versatility. We utilize organic farming methods to enhance the quality of our fruits while promoting biodiversity in our orchards. Our cold-pressed olive oil and guacamole products are crafted in small batches to ensure freshness and flavor integrity. By establishing partnerships with gourmet food retailers and restaurants, we aim to elevate the culinary experience while educating consumers about the health benefits of our offerings.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.24589127129102745, 'A': 0.005495775432924794, 'F': 0.008608250725223771, 'B': 0.7375895891194857, 'J': 0.0024151134313381167}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2624104108805143}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 550:
  We are a leading provider of vegetative planting materials, specializing in the production of grafting stock for fruit trees. Our expert team carefully selects rootstock varieties that enhance disease resistance and improve fruit quality. Through meticulous cultivation practices, we ensure that our grafting stock is robust and ready for successful grafting. We also offer workshops for growers, teaching them the art of grafting and the benefits of using our high-quality rootstock in their orchards.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.9932387327523579, 'A': 0.0004206765193649979, 'F': 0.0011260757108989123, 'B': 0.004029492928191386, 'J': 0.0011850220891868788}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.006761267247642144}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 70%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 552/788 [00:34<00:16, 14.61it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 551:
  As a prominent player in the mining of silver ores, we specialize in extracting high-purity silver through environmentally responsible methods. Our operations are characterized by advanced processing techniques that maximize recovery rates and minimize waste. We supply silver to various industries, including jewelry, electronics, and renewable energy. Our commitment to sustainability is reflected in our efforts to reduce water usage and implement recycling programs. By investing in research and development, we continuously seek innovative ways to enhance our mining practices and meet the growing demand for silver in a changing market.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.582944192246812e-05, 'A': 3.397769607755585e-05, 'F': 1.2278988580761646e-05, 'B': 0.999890810682159, 'J': 7.103191260258364e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4669110349607925e-06, 6: 1.5956472787596081e-06, 7: 0.9999959374416864}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03524033829106213, 7.2: 0.9647596617089379}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 552:
  Timber Harvesting Co. is dedicated to the responsible management of timberlands, specializing in the growth and maintenance of standing timber. Our operations encompass a range of activities, including the thinning of overgrown areas to promote healthier tree growth and the conservation of forest ecosystems. We employ cutting-edge technology to monitor forest health and optimize our harvesting practices, ensuring minimal environmental impact. Our forest tree nurseries supply a variety of native species, supporting both our operations and community reforestation projects. By integrating sustainable practices into our business model, we contribute to the long-term viability of forest resources.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 1.914348974988111e-05, 'A': 0.9998156604232946, 'F': 7.69217784690053e-05, 'B': 6.684715723736816e-05, 'J': 2.1427151248872456e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00018433957670538348}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 553:
  We have established partnerships with local communities to promote sustainable lignite mining practices. Through community engagement initiatives, we educate stakeholders about the benefits of lignite as an energy source and involve them in decision-making processes. Our community development programs focus on creating job opportunities and supporting local economies, ensuring that the benefits of lignite mining extend beyond our operations. By fostering positive relationships with local residents, we enhance our social license to operate and contribute to regional development.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.5178451151530806e-05, 'A': 3.5334794502789036e-05, 'F': 1.2652476278322384e-05, 'B': 0.99988951843067, 'J': 7.315847397495641e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011048156933002318}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                   | 557/788 [00:34<00:15, 14.56it/s]

RAPS scores:

==================================================
Description 554:
  Focused on the extraction and processing of crude gaseous hydrocarbons, our company utilizes advanced drilling techniques to tap into natural gas reserves. We excel in the draining and separation of liquid hydrocarbon fractions, which maximizes our yield and enhances product quality. Our state-of-the-art gas desulphurization systems play a crucial role in minimizing environmental impact, ensuring that our operations comply with stringent regulations. By prioritizing innovation and sustainability, we aim to provide our clients with reliable and eco-friendly energy solutions that contribute to a sustainable future.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.491754669430939e-05, 'A': 3.463655389255455e-05, 'F': 1.245046632907393e-05, 'B': 0.999890762522621, 'J': 7.232910463056113e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7659788789192136e-06, 6: 0.9999964374903573, 7: 1.7965307637353548e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979785004330033, 6.1: 0.0020214995669966913}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 555:
  We are dedicated to the cultivation of sugar cane, employing state-of-the-art harvesting techniques that minimize waste and maximize efficiency. Our processing facilities utilize advanced technology to convert raw cane into refined sugar and bioenergy, contributing to a circular economy. By investing in renewable energy sources, we power our operations sustainably while reducing our carbon footprint. Our sugar products are marketed under various brands, catering to both industrial clients and retail consumers, with an emphasis on quality and traceability.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.27528541646163057, 'A': 0.001776903268510497, 'F': 0.001855689244782217, 'B': 0.7199130973884563, 'J': 0.0011688936366203086}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2800869026115437}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 556:
  We operate a network of iron ore mines that leverage innovative technologies for efficient extraction and processing. Our facilities are equipped with automated sorting systems that enhance the quality of the ore before it enters the beneficiation phase. By employing advanced analytics, we track ore quality and processing efficiency in real-time, allowing us to make data-driven decisions that optimize production. Our iron ore products are tailored to meet the specific requirements of our customers in the steel industry, ensuring a reliable supply of high-quality materials that drive their manufacturing processes.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.573619843511662e-05, 'A': 3.4093253454391745e-05, 'F': 1.2310478067853422e-05, 'B': 0.9998906988759437, 'J': 7.1611940990201145e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.504845320178523e-06, 6: 1.5679507685002377e-06, 7: 0.9999959272039113}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678054383478756, 7.2: 0.032194561652124476}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 557:
  Specializing in the extraction of crude petroleum, our company focuses on leveraging advanced drilling technologies and sustainable practices. We have implemented a comprehensive environmental management system that minimizes the impact of our operations on local ecosystems. Our extraction processes are designed to maximize yield while adhering to the highest safety standards. By fostering strong relationships with local stakeholders, we aim to create shared value and contribute to the economic development of the regions where we operate.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4848048625786897e-05, 'A': 3.485296532731142e-05, 'F': 1.2482391769327042e-05, 'B': 0.9998905845679713, 'J': 7.232026306189254e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001094154320286922}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 71%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 560/788 [00:34<00:12, 17.57it/s]

RAPS scores:

==================================================
Description 558:
  Our company is involved in the sustainable gathering of eelgrass, which is harvested from coastal ecosystems. This valuable marine plant is processed for use in a variety of applications, including biodegradable packaging and as a natural fertilizer. We work closely with marine biologists to ensure that our harvesting practices do not disrupt local habitats, promoting the health of coastal environments. Additionally, we engage in community outreach programs to raise awareness about the importance of eelgrass in marine ecosystems, reinforcing our commitment to sustainability and environmental education.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 3.3040952530136766e-05, 'A': 0.9997178238141843, 'F': 9.261742603622261e-05, 'B': 0.00012324265538306663, 'J': 3.327515186633332e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.000282176185815719}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 559:
  Our business model revolves around the sustainable harvesting of roundwood, with a strong emphasis on quality and environmental responsibility. We produce logs that serve a variety of industries, including construction and furniture manufacturing. In addition, we are actively involved in gathering forest residues, which we convert into biomass energy, providing a renewable fuel source for heating and power generation. By prioritizing sustainable practices, we ensure that our operations benefit both the economy and the ecosystems we rely on.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.8149000268568579, 'A': 0.002869316176335015, 'F': 0.00516883122894282, 'B': 0.17433156802327557, 'J': 0.0027302577145888263}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18509997314314208}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 560:
  Our organization is at the forefront of research in lignite processing technologies, focusing on improving the overall efficiency of lignite as a fuel source. We are actively developing methods to enhance the combustion properties of lignite through innovative treatment processes. By collaborating with academic institutions and industry leaders, we aim to bring cutting-edge solutions to market that will not only improve the performance of lignite in power generation but also reduce emissions associated with its use. This commitment to innovation positions us as a leader in the lignite sector, ready to meet the challenges of a changing energy landscape.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques. We employ advanced liquefaction methods to enhance the efficiency of our operations, ensuring minimal environmental impact while maximizing yield. Our state-of-the-art facilities are equipped with the latest technology for washing and dehydrating lignite, which improves its quality and prepares it for transport. By implementing rigorous quality control measures, we guarantee that our product meets the highest industry standards, providing reliable energy sources for our clients.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.657376305142511e-05, 'A': 3.425630228491248e-05, 'F': 1.2486193220714186e-05, 'B': 0.9998894308230477, 'J': 7.252918395378175e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011056917695229096}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                 | 565/788 [00:34<00:12, 18.41it/s]

RAPS scores:

==================================================
Description 561:
  As a prominent player in the hard coal mining industry, we focus on innovative extraction methods that prioritize safety and efficiency. Our underground mining operations leverage advanced geological mapping technologies to identify high-yield deposits, while our surface mining techniques utilize eco-friendly practices to reduce land disturbance. Post-extraction, our coal is subjected to a comprehensive cleaning process that includes grading and pulverizing, ensuring that we deliver high-quality products to our customers. We also invest in research and development to improve our mining technologies, aiming to enhance productivity and reduce operational costs.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.4862415567986826e-05, 'A': 3.444617696683107e-05, 'F': 1.2358592252744915e-05, 'B': 0.9998911842477987, 'J': 7.148567413901051e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957288179143, 6: 1.3251212738661011e-06, 7: 2.946060811723612e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975277902162266, 5.2: 0.002472209783773448}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 562:
  Our business is focused on the cultivation of various perennial crops, including medicinal herbs and plants used in pharmaceutical applications. We prioritize organic farming practices to ensure the purity and efficacy of our products. Our research and development team works closely with healthcare professionals to explore new applications for our crops in wellness and alternative medicine. We also engage in educational initiatives to raise awareness about the benefits of herbal remedies, positioning our brand as a leader in the natural health sector.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.04279238041510388, 'A': 0.31508127758380666, 'F': 0.05229514267538973, 'B': 0.5834445506524989, 'J': 0.006386648673200712}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4165554493475011}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 563:
  Our business is dedicated to the sustainable harvesting of vegetable hair, primarily from palm fibers and other plant sources. We focus on eco-friendly practices that minimize waste and promote the use of renewable resources. Our products are utilized in a variety of applications, including brushes, brooms, and other cleaning tools. By sourcing materials directly from local producers, we support community livelihoods and ensure that our supply chain remains transparent and sustainable.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.6442335146417306, 'A': 0.007336211609695946, 'F': 0.01848097088683354, 'B': 0.3250095402743526, 'J': 0.004939762587387378}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3557664853582694}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 564:
  Our company is engaged in the growing of stone fruits, including cherries, peaches, and plums. We implement cutting-edge agronomic practices to ensure optimal fruit size and flavor, such as targeted pruning and nutrient management. Our commitment to sustainability is reflected in our water conservation efforts and the use of renewable energy sources on our farms. We collaborate with local distributors to bring our fresh stone fruits to market, and we also explore value-added products like dried fruits and jams, enhancing our product range while supporting local economies.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.8334400797665537, 'A': 0.00357286428858961, 'F': 0.010632119632988945, 'B': 0.14898036675780424, 'J': 0.0033745695540637003}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.16655992023344635}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 565:
  As a leader in the natural gas sector, we engage in the extraction of both conventional and unconventional gas resources. Our team utilizes state-of-the-art seismic imaging and reservoir modeling to optimize drilling locations, resulting in enhanced recovery rates. We also invest in research and development to improve our extraction processes, including the implementation of carbon capture technologies that reduce greenhouse gas emissions. Our commitment to sustainability is reflected in our partnerships with local communities and regulatory bodies to ensure responsible resource management.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.513046330404704e-05, 'A': 3.488375532452462e-05, 'F': 1.2555806004068361e-05, 'B': 0.9998901600472658, 'J': 7.269928101559128e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001098399527341698}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 568/788 [00:35<00:12, 17.06it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 566:
  Our organization is dedicated to the extraction and production of natural gas, utilizing innovative techniques to optimize resource recovery. We focus on the efficient separation of liquid hydrocarbons during extraction, ensuring that we capture valuable condensates for further processing. Our commitment to sustainability drives us to implement advanced gas desulphurization technologies, reducing the environmental impact of our operations. By continuously improving our extraction methods and investing in research, we aim to meet the increasing global demand for cleaner energy solutions while maintaining operational efficiency.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.505750670743398e-05, 'A': 3.4521544433739746e-05, 'F': 1.239598556706393e-05, 'B': 0.9998908311021353, 'J': 7.193861156400439e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7812975506856827e-06, 6: 0.9999964035758935, 7: 1.815126555873693e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979647723978577, 6.1: 0.0020352276021421583}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 567:
  We focus on the sustainable gathering of acorns and horse chestnuts, which are processed for use in natural health products and animal feed. Our harvesting practices prioritize ecological balance and support local wildlife. We collaborate with nutritionists to develop products that highlight the health benefits of these nuts, promoting their use in various diets. Additionally, we conduct research on innovative uses for acorns in food products, aiming to expand their market potential while supporting sustainable agriculture.1. Our company specializes in the sustainable gathering of wild mushrooms and truffles, leveraging a network of foragers who are trained in identifying premium varieties. We focus on regions known for their rich biodiversity, ensuring that our harvesting practices do not deplete natural resources. By employing eco-friendly methods, we maintain the integrity of the environment while providing gourmet products to high-end restaurants and specialty food retailers. Our commitment to quality and sustainability has positioned us as a leader in the gourmet food sector, where we also offer educational workshops on foraging and the culinary uses of our products.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.018091057678442452, 'A': 0.3813677625237447, 'F': 0.02081483853609766, 'B': 0.575822602088923, 'J': 0.0039037391727922595}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.424177397911077}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 568:
  The core of our business revolves around the production of coppice and pulpwood, which are essential for the paper and bioenergy sectors. We strategically manage our forests to promote rapid regrowth, allowing us to harvest materials sustainably while minimizing ecological impact. Our operations include thinning practices that improve the health of the forest ecosystem and enhance the quality of the wood produced. By integrating innovative harvesting technologies, we efficiently process timber, ensuring a steady supply of raw materials for our partners in manufacturing and energy production.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.9995628409021244, 'A': 2.540549818004012e-05, 'F': 3.316766718856923e-05, 'B': 0.0002054863486940858, 'J': 0.00017309958381270414}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0004371590978755613}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 569:
  Our company engages in the mining and beneficiation of iron ore, with a strong emphasis on technological advancement. We utilize advanced separation techniques to enhance ore quality, producing high-grade iron concentrates that cater to the needs of the steel industry. Our facilities are equipped with modern crushing and screening equipment, enabling us to efficiently process large volumes of ore. Additionally, we invest in continuous improvement initiatives to streamline operations and reduce waste, thereby maximizing the value of our iron ore resources.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.6738483445187865e-05, 'A': 3.4002871861474195e-05, 'F': 1.2325729466183128e-05, 'B': 0.9998897665235892, 'J': 7.166391637951666e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011023347641081482}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 73%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                               | 574/788 [00:35<00:10, 21.19it/s]

RAPS scores:

==================================================
Description 570:
  Our tobacco farming operations focus on producing high-quality leaf tobacco for the global market. We implement rigorous quality control measures throughout the cultivation process, from seed selection to harvesting, ensuring that our products meet the stringent requirements of manufacturers. We also prioritize sustainable farming practices, including soil conservation and crop diversification, to enhance the resilience of our farming systems. Our partnerships with local farmers provide them with training and resources to improve their agricultural practices, fostering economic growth in the communities where we operate.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.8806958772339206, 'A': 0.001638511163504514, 'F': 0.0024616942136750355, 'B': 0.11348464223647747, 'J': 0.0017192751524222783}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11930412276607938}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 571:
  We are engaged in the sustainable gathering of balata and other rubber-like gums from tropical trees, which are harvested without harming the trees themselves. Our operations emphasize environmental stewardship and fair trade practices, ensuring that local communities benefit from our activities. The extracted gums are processed into natural rubber products used in various applications, including adhesives and sealants. By focusing on ethical sourcing and innovative processing techniques, we provide high-quality materials that meet the needs of eco-conscious manufacturers and consumers alike.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.06514179552441507, 'A': 0.0023827385808654795, 'F': 0.00246098005006959, 'B': 0.9291402996411708, 'J': 0.0008741862034789312}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07085970035882916}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 572:
  Our company is dedicated to the comprehensive aquaculture of amphibians, particularly frogs, for both culinary and ecological purposes. We utilize controlled breeding and rearing techniques to ensure a steady supply of high-quality frog legs while maintaining genetic diversity within our stock. Our operations include habitat enhancement measures that support local biodiversity and promote ecosystem health. We actively participate in conservation programs aimed at protecting amphibian populations in the wild, reinforcing our commitment to sustainability. Through partnerships with chefs and culinary schools, we aim to educate consumers about the culinary potential of amphibians, creating new market opportunities.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00013396221627118456, 'A': 0.997438865135568, 'F': 0.001863196493824132, 'B': 0.00042550018797915556, 'J': 0.0001384759663578049}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.002561134864431991}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 573:
  At Green Forest Solutions, we are dedicated to the sustainable management of forest resources. Our operations include the planting and nurturing of timber species, as well as the careful thinning of mature forests to promote biodiversity and growth. We also focus on the cultivation of coppice and firewood, providing renewable energy sources to local communities. Our forest tree nurseries play a crucial role in supplying quality saplings, which are essential for reforestation projects and timber production. By implementing innovative forestry practices, we aim to balance economic viability with environmental stewardship.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.180939771839876e-05, 'A': 0.9995105832622948, 'F': 0.00024026268092754136, 'B': 0.00016268769522205675, 'J': 4.4656963837289664e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.000489416737705195}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                              | 577/788 [00:35<00:12, 17.40it/s]

RAPS scores:

==================================================
Description 574:
  Our business is dedicated to the sustainable mining of hard coal, employing innovative techniques that minimize environmental impact. We utilize advanced equipment for the extraction process, ensuring that our operations are efficient and safe for workers. Our facilities are designed to clean and grade coal, enhancing its quality for end-users. By implementing rigorous quality control measures, we guarantee that our products not only meet but exceed industry specifications, thereby creating significant value for our customers.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.483565009302372e-05, 'A': 3.448592217103157e-05, 'F': 1.2377820687852622e-05, 'B': 0.9998911234197071, 'J': 7.177187340971635e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957224806607, 6: 1.3296626759621525e-06, 7: 2.9478566634235734e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975243064376687, 5.2: 0.0024756935623314}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 575:
  Our business focuses on the sustainable gathering of vegetable hair, specifically from the agave plant, which is used in the production of high-quality brushes and brooms. We collaborate with local artisans who have honed their skills over generations, ensuring that our products are crafted with care and precision. By promoting the use of natural materials, we cater to eco-conscious consumers looking for sustainable alternatives to synthetic products. Our commitment to quality craftsmanship and sustainability has positioned us as a leader in the natural brush market.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9986205588689793, 'A': 7.492957576392494e-05, 'F': 0.00015116497618784325, 'B': 0.0007713474019167634, 'J': 0.0003819991771521431}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.001379441131020731}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 576:
  We focus on the extraction of precious metals such as gold and silver from non-ferrous metal ores. Our mining operations employ innovative techniques that enhance ore recovery while adhering to strict environmental standards. We utilize advanced processing methods, including cyanidation and gravity separation, to ensure high purity levels in our final products. Our commitment to sustainability drives us to implement responsible mining practices and engage with local stakeholders, ensuring that our operations contribute positively to the communities in which we operate.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.525356741419063e-05, 'A': 3.4231301633628236e-05, 'F': 1.2326870968159377e-05, 'B': 0.9998910590898875, 'J': 7.1291700964346255e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.45808275495176e-06, 6: 1.6009906279429268e-06, 7: 0.999995940926617}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03513059586078489, 7.2: 0.9648694041392152}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 577:
  We grow a diverse range of pome and stone fruits, including apples, pears, peaches, and cherries, with an emphasis on organic farming practices. Our orchards are carefully designed to enhance pollination and fruit development, resulting in high yields of flavorful produce. We utilize innovative storage techniques to extend the freshness of our fruits, allowing us to supply year-round to grocery chains and local markets. Additionally, we engage in community outreach programs to educate consumers about the health benefits of our fruits, fostering a strong connection between our brand and the community.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.731493119234656, 'A': 0.005930511149916986, 'F': 0.017086715475156226, 'B': 0.24120052760789912, 'J': 0.0042891265323716475}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.268506880765344}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                              | 580/788 [00:35<00:11, 18.63it/s]

RAPS scores:

==================================================
Description 578:
  Our business model revolves around the collection of aquatic plants, such as seaweed and watercress, from both marine and freshwater environments. We employ sustainable harvesting techniques that ensure the regeneration of these vital resources, which are increasingly sought after for their nutritional and culinary value. Our products are processed and packaged for distribution to health food stores and restaurants, where they are featured in a variety of dishes. We also engage in educational outreach, teaching consumers about the benefits of incorporating aquatic plants into their diets and the importance of sustainable harvesting practices. This dual focus on product quality and environmental responsibility sets us apart in the market.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.006740516620387831, 'A': 0.8964333729309206, 'F': 0.03303410972543538, 'B': 0.06116453673156863, 'J': 0.0026274639916874557}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10356662706907938}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 579:
  Engaged in the farming of various aquatic organisms, our business employs sustainable practices that align with environmental conservation efforts. We cultivate a diverse range of species, including fish, molluscs, and aquatic plants, utilizing methods that enhance biodiversity and ecosystem health. Our operations focus on minimizing waste through efficient resource management and recycling initiatives. We actively participate in community education programs, promoting awareness of sustainable aquaculture practices. By fostering partnerships with local stakeholders, we aim to create a resilient aquaculture sector that supports both economic growth and environmental sustainability.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of high-value species such as salmon and sea bass. We utilize advanced recirculating aquaculture systems (RAS) to maintain optimal water quality and reduce environmental impact. By implementing precision feeding techniques and monitoring health parameters, we ensure the growth of our fish exceeds natural rates. Our operations are complemented by a robust logistics network that guarantees fresh delivery to markets, enhancing our customers’ access to premium seafood products while supporting local economies.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.002031618268090213, 'A': 0.9685906964037269, 'F': 0.006493143035412725, 'B': 0.0218807305709978, 'J': 0.0010038117217723943}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03140930359627314}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 580:
  Our operations in the capture fishery sector extend to restocked water bodies, where we engage in the sustainable harvesting of fish species that have been reintroduced to local ecosystems. By collaborating with environmental organizations, we ensure that our fishing practices support the health of these water bodies. Our team employs a combination of traditional fishing techniques and modern equipment to efficiently gather fish while maintaining ecological balance. The harvested fish are processed and sold to local markets, promoting awareness of the importance of sustainable fishing practices and the benefits of consuming locally sourced products.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 4.355355296433653e-05, 'A': 0.9995696377095471, 'F': 0.00010476779747202632, 'B': 0.0002395538797180691, 'J': 4.24870602985462e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0004303622904529014}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 581:
  Our lignite mining operations are designed to maximize efficiency and sustainability. We utilize advanced surface mining techniques alongside innovative washing and pulverizing methods to produce high-quality lignite. Our dedicated warehousing facilities ensure that the lignite is stored safely and securely, ready for transport to our customers. By continuously improving our processes and investing in technology, we create significant value for our clients while adhering to stringent environmental standards.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.5101825150466075e-05, 'A': 3.426457445671605e-05, 'F': 1.233687447619288e-05, 'B': 0.9998911504319876, 'J': 7.1462939291243326e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957376887573, 6: 1.3441013652235502e-06, 7: 2.918209877516767e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023547782810540573, 5.2: 0.997645221718946}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                             | 583/788 [00:36<00:12, 16.20it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 582:
  As a leader in the hard coal mining sector, we operate multiple mines where we implement innovative extraction techniques to maximize yield. Our team is dedicated to the continuous improvement of our processes, employing advanced technologies for pulverizing and compressing coal. This not only enhances the quality of our products but also reduces waste and environmental impact. We pride ourselves on our robust supply chain management, ensuring that our coal is efficiently transported and stored, meeting the needs of our diverse customer base across various industries.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.486429068909547e-05, 'A': 3.435412476493845e-05, 'F': 1.2346627385888136e-05, 'B': 0.9998912684078163, 'J': 7.166549343634362e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957260861146, 6: 1.332329556509311e-06, 7: 2.9415843287444507e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975255943760212, 5.2: 0.0024744056239789105}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 583:
  We specialize in the management of forest resources through a combination of traditional and modern silvicultural practices. Our operations include the careful selection of tree species for planting, as well as ongoing maintenance activities such as thinning and pest management. By operating our own nurseries, we produce high-quality seedlings that are tailored to thrive in local environments. Our approach not only enhances the productivity of our forests but also supports local economies through job creation and sustainable resource management, reflecting our commitment to both profitability and environmental stewardship.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00015012418066247368, 'A': 0.9960539601131082, 'F': 0.0031121491496775527, 'B': 0.0005270720925868838, 'J': 0.00015669446396487886}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0039460398868917945}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                            | 588/788 [00:36<00:11, 17.92it/s]

RAPS scores:

==================================================
Description 584:
  Our operations in hard coal mining encompass a comprehensive approach that includes extraction, processing, and distribution. We employ both underground and surface mining techniques, supplemented by innovative liquefaction methods to enhance coal recovery. Our processing plants are designed to clean, size, and grade the coal, ensuring that it meets the diverse needs of our customers. By implementing efficient transport solutions, we facilitate the timely delivery of our products to various markets, thereby enhancing our competitive edge in the energy sector.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.503901136504718e-05, 'A': 3.423234895018217e-05, 'F': 1.2328184233702876e-05, 'B': 0.9998912555202816, 'J': 7.144935169610976e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995723410472, 6: 1.3347821760826916e-06, 7: 2.941807351745061e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975272392331218, 5.2: 0.002472760766878287}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 585:
  Our company specializes in the propagation of high-quality vegetative planting materials, focusing on producing a diverse range of seedlings and cuttings for both commercial growers and home gardeners. We utilize advanced propagation techniques, including tissue culture and hydroponic systems, to ensure healthy and vigorous plants. Our state-of-the-art facilities allow us to maintain optimal growing conditions, resulting in a robust inventory of ornamental plants and vegetables. Additionally, we provide expert guidance and resources to our clients, helping them select the right varieties for their specific needs, thereby enhancing their planting success and sustainability.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.0646518899316288, 'A': 0.06922946332176506, 'F': 0.8169995313433907, 'B': 0.03880972292952867, 'J': 0.010309392473686674}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.18300046865660935}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 586:
  We focus on the sustainable collection of wild berries, offering a diverse range of products from fresh, organic blueberries to processed jams and jellies. Our team of skilled harvesters is trained to identify and gather only the ripest berries, ensuring the highest quality for our customers. We collaborate with local farmers' markets and health food stores to distribute our products, emphasizing our commitment to eco-friendly practices. Additionally, we invest in community outreach programs to educate the public about the nutritional benefits of wild berries and the importance of preserving their natural habitats.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.005372710725247543, 'A': 0.8632728849377069, 'F': 0.011309329335078434, 'B': 0.11802575408339501, 'J': 0.0020193209185719913}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.13672711506229307}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 587:
  We are dedicated to the sustainable gathering of lac and resins from specific tree species, utilizing traditional harvesting methods that have been passed down through generations. Our products serve multiple industries, including cosmetics, pharmaceuticals, and food processing. By ensuring that our harvesting practices do not deplete natural resources, we contribute to the preservation of biodiversity. We also invest in local communities by providing fair compensation and training for harvesters, fostering a sense of stewardship towards the forests. Our focus on quality and sustainability has established us as a trusted supplier in the market.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.016775180357656495, 'A': 0.004018119900630918, 'F': 0.0021767097096808373, 'B': 0.9763739012476232, 'J': 0.0006560887844084142}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.023626098752376756}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                           | 593/788 [00:36<00:10, 18.28it/s]

RAPS scores:

==================================================
Description 588:
  Our iron ore mining operations are characterized by a commitment to efficiency and sustainability. We employ advanced extraction techniques that reduce waste and enhance ore recovery rates. Our beneficiation processes utilize modern technologies, such as flotation and magnetic separation, to produce high-grade iron concentrates. Additionally, we provide technical consultancy services that help other mining companies improve their operational efficiencies and environmental compliance. By focusing on innovation and collaboration, we strive to lead the industry in producing quality iron ore while minimizing our ecological footprint.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.515738310533197e-05, 'A': 3.4176144814558016e-05, 'F': 1.2294458120160276e-05, 'B': 0.9998912442684714, 'J': 7.127745488483992e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4616626234174e-06, 6: 1.5977616024129409e-06, 7: 0.9999959405757741}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677793795504238, 7.2: 0.03222062044957612}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 589:
  Our company excels in the manufacture of utility poles, providing essential infrastructure for power and telecommunications. We source high-quality roundwood from sustainably managed forests, ensuring that our products are durable and reliable. Our manufacturing process includes treating the wood to enhance its lifespan and resistance to environmental factors. By collaborating with utility companies, we ensure that our poles meet stringent safety and performance standards, contributing to the development of resilient energy and communication networks.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997747756383374, 'A': 1.2104096701725852e-05, 'F': 1.4556126883325723e-05, 'B': 7.141641389326601e-05, 'J': 0.0001271477241840248}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00022522436166261262}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 590:
  We focus on the mining and processing of iron ores, providing high-quality products that serve the steel industry. Our operations encompass the entire value chain, from exploration and extraction to beneficiation and agglomeration. By employing innovative technologies and best practices in our processing plants, we enhance the iron content of our ores, producing pellets that are in high demand globally. Our commitment to sustainable mining practices drives us to continuously improve our operational efficiency while minimizing environmental impact, ensuring that we meet the needs of our customers responsibly.1. Our company specializes in the extraction and processing of high-grade iron ore from our strategically located mines. Utilizing advanced drilling and blasting techniques, we ensure efficient ore recovery while minimizing environmental impact. Our beneficiation process employs state-of-the-art technologies, including magnetic separation and flotation, to enhance the iron content of the ore. This not only maximizes the value of our raw materials but also supports our commitment to sustainable mining practices. We supply premium iron ore to steel manufacturers, contributing to the production of high-quality steel used in construction and infrastructure projects worldwide.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.581923575064692e-05, 'A': 3.4061105413102114e-05, 'F': 1.2326759664014215e-05, 'B': 0.9998906127750978, 'J': 7.1801240745561305e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938722490216879}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 591:
  Our operations in the growing of melons and tubers leverage advanced irrigation technologies to optimize water usage and enhance crop resilience. We prioritize soil health through organic amendments and crop rotation, which contribute to higher yields and better quality produce. Our marketing strategy includes direct-to-consumer sales, allowing us to build relationships with our customers and educate them on the benefits of locally sourced food. We also engage in community initiatives that promote healthy eating habits, further solidifying our position as a leader in the local agricultural landscape.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.06475960569830846, 'A': 0.17514988270915552, 'F': 0.13420903707023407, 'B': 0.6184805232086884, 'J': 0.007400951313613423}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3815194767913116}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 592:
  As a leader in the forestry sector, we operate extensive tree nurseries dedicated to the propagation of native and commercially valuable tree species. Our nurseries utilize state-of-the-art propagation techniques, including tissue culture and seedling acclimatization, to produce robust saplings ready for reforestation projects. We collaborate with environmental organizations to supply seedlings for restoration efforts in degraded areas, promoting biodiversity and ecological resilience. Additionally, our expertise in soil management and pest control ensures that our nursery operations yield healthy plants that thrive in various environmental conditions.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0002630648463051302, 'A': 0.9958854647046904, 'F': 0.0022236302571309167, 'B': 0.0014141675854902598, 'J': 0.00021367260638341962}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.004114535295309585}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                          | 596/788 [00:36<00:11, 16.50it/s]

RAPS scores:

==================================================
Description 593:
  We are dedicated to providing tailored solutions for our clients in the lignite sector, from mining to delivery. Our team of experts works closely with customers to understand their specific needs and develop customized logistics plans that ensure timely and efficient delivery of lignite. By leveraging data analytics and real-time tracking systems, we enhance transparency and reliability in our supply chain, fostering long-term partnerships with our clients.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.6940012134894205e-05, 'A': 3.629107039733317e-05, 'F': 1.3162245625785396e-05, 'B': 0.9998860236423458, 'J': 7.583029496128303e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011397635765419967}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 594:
  We specialize in the mining of iron ores, focusing on the extraction of high-quality deposits that are essential for steel production. Our operations include a comprehensive beneficiation process, utilizing advanced technologies such as magnetic separation and flotation to enhance the iron content of the ore. We also engage in the agglomeration of iron ores, producing pellets that improve the efficiency of steel manufacturing. Our commitment to sustainability drives us to implement environmentally friendly practices throughout our operations, ensuring that we meet the demands of our customers while protecting the planet. Our innovative approach and dedication to quality make us a trusted partner in the iron ore industry.1. Our company specializes in the extraction and processing of high-grade iron ores, which are essential for steel production. We operate multiple mining sites equipped with advanced drilling and blasting technologies to ensure efficient ore recovery. Our beneficiation processes utilize state-of-the-art separation techniques, including magnetic and gravity separation, to enhance the iron content of the extracted ores. This not only maximizes yield but also minimizes environmental impact through responsible waste management practices. We are committed to sustainable mining operations, ensuring that our activities contribute positively to local communities and ecosystems while meeting the growing demand for iron in various industries.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.599970549775131e-05, 'A': 3.3978983685295856e-05, 'F': 1.2309105751654404e-05, 'B': 0.9998905586943879, 'J': 7.153510677388506e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0001094413056120791}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 595:
  Our company is dedicated to the sustainable mining of iron ores, focusing on both the extraction and processing stages. We employ advanced technologies to ensure efficient ore recovery while adhering to strict environmental regulations. Our beneficiation processes are designed to optimize the iron content of the mined ores, producing high-grade concentrates that cater to the steel industry. Additionally, we invest in agglomeration techniques that enhance the usability of iron fines, creating pellets that improve the efficiency of steel production. Through innovation and responsible practices, we strive to deliver value to our stakeholders while preserving natural resources.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5770639440401314e-05, 'A': 3.401706104955543e-05, 'F': 1.228322549574046e-05, 'B': 0.9998908135498951, 'J': 7.11552411908304e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4586436801959697e-06, 6: 1.596801938238525e-06, 7: 0.9999959445543817}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678057206358814, 7.2: 0.03219427936411859}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 598/788 [00:36<00:12, 15.70it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 596:
  Our company is engaged in the mining of bauxite, the primary ore for aluminum production. We employ a rigorous approach to resource extraction, utilizing advanced geological mapping and drilling techniques to identify optimal mining sites. Our processing plants are designed to efficiently convert bauxite into alumina, which is then further refined into aluminum. We prioritize environmental responsibility by implementing measures to reduce emissions and manage waste effectively. By supplying high-quality aluminum to the construction and transportation sectors, we contribute to the development of lightweight, durable materials that enhance energy efficiency and sustainability.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.534206857551817e-05, 'A': 3.428297974673432e-05, 'F': 1.2351568962627074e-05, 'B': 0.9998908821339011, 'J': 7.141248814110357e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4705438359824487e-06, 6: 1.5834314492781343e-06, 7: 0.9999959460247146}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03512059632615174, 7.2: 0.9648794036738483}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 597:
  Our company specializes in the production of cuttings for a variety of flowering plants, catering to both amateur gardeners and professional landscapers. We employ advanced propagation techniques to ensure that our cuttings are healthy and ready for planting. Our extensive selection includes popular varieties as well as rare species, providing customers with a wide range of options for their gardens. We also offer educational resources and workshops, helping our clients develop their gardening skills and knowledge.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.988818257885478, 'A': 0.000655073538919141, 'F': 0.002913218260808867, 'B': 0.00552644585766697, 'J': 0.002087004457127058}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.011181742114522053}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 598:
  As a leader in rice cultivation, we focus on producing high-quality varieties that cater to both local and international markets. Our operations are centered around innovative irrigation techniques, which maximize water efficiency and ensure consistent crop yields even in varying climate conditions. We also invest in research and development to enhance the nutritional profile of our rice, aiming to provide healthier options for consumers. By collaborating with agricultural cooperatives, we support local farmers through training programs, helping them adopt best practices that improve productivity and sustainability.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.013075427156265316, 'A': 0.701028280363908, 'F': 0.031321606444829314, 'B': 0.2509653163473813, 'J': 0.003609369687616216}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.29897171963609204}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                         | 600/788 [00:37<00:12, 15.18it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 599:
  The company is engaged in the collection of aquatic plants, such as seaweed and kelp, from coastal waters. These plants are harvested sustainably and processed into various products, including food ingredients, supplements, and biofuels. By leveraging innovative extraction techniques, the company maximizes the nutritional benefits of the harvested plants while minimizing waste. This diversification not only enhances the product line but also positions the company as a leader in the burgeoning market for plant-based food and sustainable energy solutions.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1396236996154742e-05, 'A': 0.9999054279917158, 'F': 3.906056276064975e-05, 'B': 3.0433469196746375e-05, 'J': 1.3681739330428057e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007278997180837565, 2: 0.0009455776113548016, 3: 0.9983265226705613}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.955284123820108, 3.2: 0.044715876179892027}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 600:
  Our aquaculture operations extend to the farming of aquatic plants, particularly seaweed, which has gained popularity for its nutritional and ecological benefits. We utilize innovative cultivation techniques that promote rapid growth while ensuring minimal environmental disruption. Our farms are strategically located in coastal areas with ideal conditions for seaweed growth, allowing us to harvest sustainably year-round. We focus on processing and packaging our seaweed products for various applications, including food, cosmetics, and biofuels. By promoting the use of seaweed, we contribute to environmental sustainability and offer consumers a versatile and healthy product.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.013855130752505709, 'A': 0.5665478398562169, 'F': 0.024988326265104197, 'B': 0.3910485965782463, 'J': 0.0035601065479268917}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.43345216014378307}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 601:
  We specialize in the cultivation of beverage crops, particularly coffee and tea, sourcing high-quality beans and leaves from sustainable farms. Our operations emphasize fair trade practices, ensuring that farmers receive equitable compensation for their products. We utilize innovative processing techniques to enhance flavor profiles and maintain freshness, which are crucial for our premium product lines. Our brand is built around the story of our growers, creating a strong emotional connection with consumers. We also offer subscription services that deliver fresh coffee and tea directly to customers, enhancing convenience and fostering brand loyalty.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.3207768927421021, 'A': 0.024455746780308478, 'F': 0.034193322397014524, 'B': 0.6138260363945223, 'J': 0.0067480016860527485}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.38617396360547773}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 606/788 [00:37<00:10, 17.09it/s]

RAPS scores:

==================================================
Description 602:
  Our business model revolves around the efficient mining and processing of iron ores, where we focus on maximizing the value of our mineral resources. We employ a range of techniques, from traditional open-pit mining to advanced beneficiation processes that enhance ore quality. Our state-of-the-art processing facilities utilize high-efficiency separators and classifiers, ensuring that we deliver premium iron concentrate to our clients. We are dedicated to sustainable practices, continuously seeking ways to reduce waste and energy consumption in our operations, thereby contributing to a more sustainable future.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.47397892177138e-05, 'A': 3.4414786763641784e-05, 'F': 1.2358820789610492e-05, 'B': 0.9998913179755242, 'J': 7.168627704645516e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4627128352137897e-06, 6: 1.5915059671918969e-06, 7: 0.9999959457811977}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677822082484686, 7.2: 0.032217791751531485}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 603:
  We are committed to enhancing the aquaculture sector through research and development of new farming techniques and species diversification. Our team collaborates with academic institutions to explore innovative practices that improve yield and reduce environmental impact. By investing in genetic research, we aim to develop strains of fish and shellfish that are better suited for aquaculture, improving growth rates and disease resistance. Our focus on sustainability and innovation positions us as a leader in the industry, enabling us to meet the growing global demand for seafood while protecting marine ecosystems.1. Our company specializes in marine aquaculture, focusing on the sustainable farming of various fish species, including salmon and tilapia. Utilizing advanced recirculating aquaculture systems, we ensure optimal water quality and nutrient levels, which promote rapid growth and health of the fish. Our operations include regular monitoring and feeding protocols, designed to maximize yield while minimizing environmental impact. We also engage in research and development to improve breeding techniques, enhancing disease resistance and growth rates. Through strategic partnerships with local fisheries, we aim to provide fresh, high-quality seafood to both local and international markets.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 6.536675635532411e-05, 'A': 0.999370648094244, 'F': 0.00021846572678378332, 'B': 0.0002844149254917234, 'J': 6.11044971250413e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0006293519057559704}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 604:
  Engaged in the aquaculture of amphibians, our company focuses on the sustainable farming of frogs for culinary markets. We maintain specialized facilities that mimic natural habitats, ensuring optimal growth conditions through controlled temperature and humidity. Our operations include breeding, rearing, and harvesting, with a strong emphasis on biosecurity to prevent disease. We utilize environmentally friendly practices, such as organic feed and efficient waste management systems, to minimize our ecological footprint. Our commitment to quality and sustainability has positioned us as a trusted supplier in the gourmet food industry, catering to chefs and restaurants seeking high-quality frog legs.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0004095674446710717, 'A': 0.9931131333931583, 'F': 0.00401887760965748, 'B': 0.0021405376455641695, 'J': 0.0003178839069489413}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0068868666068416795}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 605:
  Our company is a leader in the harvesting of cork, focusing on sustainable practices that support both the environment and local economies. We collaborate with cork oak farmers to ensure that the extraction process is done without harming the trees, allowing them to continue producing cork for decades. Our cork products are used in a variety of applications, from flooring to wine stoppers, and are marketed as environmentally friendly alternatives. By investing in community education and sustainable practices, we create a positive impact while delivering high-quality products to our customers.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0002974883866858945, 'A': 0.0004388500349592458, 'F': 7.888027767785889e-05, 'B': 0.9991437852373528, 'J': 4.0996063324076545e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008562147626471894}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                        | 608/788 [00:37<00:11, 16.22it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 606:
  Our organization is dedicated to the extraction of crude petroleum, employing a combination of traditional drilling and enhanced oil recovery techniques. We utilize advanced reservoir modeling software to optimize extraction processes and predict production rates accurately. Our team of geologists and engineers work collaboratively to assess new drilling sites, ensuring that we tap into the most productive reservoirs. Additionally, we are committed to reducing our carbon footprint by implementing carbon capture technologies at our extraction sites, allowing us to contribute to a more sustainable energy future while meeting the demands of our customers.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.509421201208637e-05, 'A': 3.43702105618619e-05, 'F': 1.2356268589313298e-05, 'B': 0.999891020353851, 'J': 7.158954985624772e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7710461715604569e-06, 6: 0.9999964100973711, 7: 1.8188564574447492e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020540900645288733, 6.1: 0.997945909935471}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 607:
  Our commitment to sustainable forestry is reflected in our comprehensive approach to managing forest resources. We engage in activities such as thinning and conservation to promote healthy growth and biodiversity within our managed forests. Our operations are designed to minimize environmental impact while maximizing timber production, allowing us to meet the growing demand for sustainable wood products. Additionally, we partner with local communities to promote awareness of sustainable practices, ensuring that our forestry activities benefit both the economy and the environment.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.318460197464686e-05, 'A': 0.999485479871164, 'F': 0.00022830438466118772, 'B': 0.00019736627387893424, 'J': 4.5664868321333234e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0005145201288360157}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 608:
  Our firm specializes in the mining of tin ores, employing innovative techniques that enhance ore recovery and processing efficiency. We are committed to sustainable mining practices, focusing on minimizing our environmental footprint through responsible waste management and land rehabilitation efforts. Our research initiatives aim to develop new technologies that improve the quality of our tin products, which are essential for electronics and packaging industries. By fostering strong relationships with our customers, we ensure that our materials meet their specific needs, thereby driving mutual growth and sustainability in the supply chain.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.560252198392758e-05, 'A': 3.42671274482771e-05, 'F': 1.2338418771602437e-05, 'B': 0.999890673259325, 'J': 7.118672471207881e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010932674067498649}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 613/788 [00:37<00:11, 15.72it/s]

RAPS scores:

==================================================
Description 609:
  As a prominent player in the iron ore mining industry, we prioritize the development of sustainable mining practices. Our operations are supported by cutting-edge technology that allows for real-time monitoring of ore quality and processing efficiency. We utilize advanced beneficiation techniques to produce iron ore pellets that are highly sought after in the steel manufacturing sector. Our engineering and technical consultancy teams work diligently to provide tailored solutions that enhance productivity and reduce environmental impact. Through our commitment to excellence, we aim to set new standards in the iron ore mining sector.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.514215169605263e-05, 'A': 3.427213189952189e-05, 'F': 1.23147842224954e-05, 'B': 0.9998911503347966, 'J': 7.120597385241342e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4697575986721306e-06, 6: 1.5906956699694516e-06, 7: 0.9999959395467314}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677795022190507, 7.2: 0.032220497780949264}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 610:
  Our company is a leader in the production of citrus fruits, particularly oranges and lemons, known for their vibrant flavors and nutritional value. We employ innovative farming techniques, including organic practices and soil health management, to cultivate our orchards sustainably. Our citrus products are processed into juices, essential oils, and flavoring agents for the food and beverage industry. We prioritize quality control at every stage, from harvest to packaging, ensuring that our products meet the highest standards. Our commitment to sustainability is reflected in our efforts to reduce water usage and promote biodiversity within our orchards.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.8880622258066811, 'A': 0.0016629159129957184, 'F': 0.003370319680756714, 'B': 0.10506963565929085, 'J': 0.001834902940275566}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11193777419331885}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 611:
  We are dedicated to the growth of beverage crops, particularly coffee and tea, sourcing our plants from sustainable farms that prioritize ethical practices. Our coffee beans are carefully selected and roasted to perfection, creating unique blends that cater to diverse palates. We also focus on the cultivation of specialty teas, promoting health benefits and flavor diversity. Our brand emphasizes transparency in sourcing, allowing consumers to trace their beverages back to the farms, enhancing their appreciation for the products.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.47858118795023485, 'A': 0.008353025683030764, 'F': 0.021556714015096207, 'B': 0.4872530293781049, 'J': 0.004256042973533453}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5127469706218951}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 612:
  Our lignite mining operations are driven by a commitment to sustainability and efficiency. We utilize both traditional and modern mining techniques, ensuring that we extract lignite in a manner that minimizes environmental disruption. Our facilities are equipped with advanced washing and dehydrating systems that improve the quality of our lignite, making it more suitable for energy production. Furthermore, we have established robust support activities for transportation, including partnerships with logistics providers, to ensure that our product reaches customers promptly and in optimal condition.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.502752151311193e-05, 'A': 3.435840677096034e-05, 'F': 1.236708294225097e-05, 'B': 0.999891091674722, 'J': 7.155314051752329e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957339679119, 6: 1.3434746890681772e-06, 7: 2.9225573989393257e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002354667383687953, 5.2: 0.9976453326163119}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                      | 615/788 [00:38<00:11, 15.12it/s]

RAPS scores:

==================================================
Description 613:
  Engaged in the raising of camels, our operation focuses on both milk production and tourism. We have developed a unique breeding program that emphasizes the health and productivity of our herd, which is known for its high-quality milk rich in nutrients. Our camel milk is marketed as a health product, appealing to consumers seeking alternatives to traditional dairy. Additionally, we offer camel rides and educational tours, providing visitors with an immersive experience in camel husbandry. Our commitment to animal welfare and sustainable practices ensures that our business not only thrives but also contributes positively to the community and environment.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0003207770023069827, 'A': 0.9949472742577825, 'F': 0.0015060155411616364, 'B': 0.0029784668103396087, 'J': 0.00024746638840938506}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00505272574221749}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 614:
  In our lignite mining operations, we focus on optimizing the extraction process through innovative liquefaction methods. This technology enables us to convert lignite into a more transportable form, enhancing its marketability. Our facilities are equipped with advanced pulverizing and compressing machinery that prepares the lignite for both immediate use and long-term storage solutions. By ensuring high-quality output, we cater to the increasing demand for reliable energy sources while adhering to stringent environmental regulations.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.528622384363763e-05, 'A': 3.422399977974394e-05, 'F': 1.2346182437135836e-05, 'B': 0.9998909924947823, 'J': 7.151099157219e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957345314108, 6: 1.3438322025942403e-06, 7: 2.9216363867394494e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002354156650965195, 5.2: 0.9976458433490348}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 615:
  We are involved in the growing of various tree and bush fruits, including blueberries, raspberries, and blackberries, which are cultivated using sustainable agricultural practices. Our farms are equipped with drip irrigation systems that conserve water while ensuring optimal growth conditions. We focus on organic certification to meet the increasing demand for chemical-free produce. Our berries are sold fresh, frozen, and processed into jams and sauces, catering to diverse consumer preferences. We also engage in community-supported agriculture (CSA) programs, allowing local consumers to receive fresh produce directly from our farms, fostering a strong connection with our community.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.2723755512488417, 'A': 0.014043181297214841, 'F': 0.030667012138767626, 'B': 0.6783030891104793, 'J': 0.004611166204696527}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3216969108895207}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 616:
  Our organization is dedicated to the extraction of crude petroleum, employing innovative techniques such as hydraulic fracturing and horizontal drilling to unlock new reserves. We invest heavily in research to improve these methods, focusing on reducing water usage and minimizing the environmental impact of our operations. Our skilled workforce is trained in the latest technologies, ensuring that we can adapt to changing market conditions and regulatory requirements. By prioritizing safety and efficiency, we strive to deliver reliable energy solutions to our customers while supporting the transition to a more sustainable energy landscape.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.495547745635282e-05, 'A': 3.5063722153247486e-05, 'F': 1.2559635241090244e-05, 'B': 0.9998901535853179, 'J': 7.267579831484194e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010984641468214651}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                     | 621/788 [00:38<00:08, 20.07it/s]

RAPS scores:

==================================================
Description 617:
  We recognize the importance of efficient transportation in the lignite supply chain and have invested in a fleet of specialized vehicles designed for the safe and effective transport of lignite products. Our logistics team works diligently to optimize routes and schedules, ensuring timely deliveries to our customers. Additionally, we collaborate with local authorities to ensure compliance with transportation regulations, further enhancing our reputation as a reliable partner in the lignite industry. Our focus on safety and efficiency underscores our commitment to delivering value to our clients.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.999397795035293, 'A': 2.0528903134805433e-05, 'F': 3.5803008360344016e-05, 'B': 8.495742595707027e-05, 'J': 0.000460915627254793}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.000602204964706976}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 618:
  At Timber Harvesters Inc., we focus on the sustainable growing of coppice and pulpwood to meet the needs of the paper and packaging industries. Our operations include the careful selection of species and management of growth cycles to ensure optimal yield. We employ environmentally friendly harvesting techniques that minimize disruption to surrounding ecosystems. Our commitment to sustainability extends to our partnerships with local communities, where we provide training and resources to promote responsible forestry practices. By prioritizing both economic and environmental considerations, we contribute to a sustainable future for the forestry sector.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0067086439083718944, 'A': 0.4758542674610168, 'F': 0.007527059688878634, 'B': 0.5077875068103049, 'J': 0.0021225221314277714}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.49221249318969507}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 619:
  In the crude petroleum extraction sector, our company has established a reputation for operational excellence and innovation. We utilize a combination of traditional drilling methods and cutting-edge technologies, such as automated drilling systems and real-time monitoring tools, to enhance our extraction capabilities. Our commitment to safety is paramount, and we continuously train our personnel to adhere to best practices in the field. Furthermore, we engage in extensive environmental assessments before commencing any extraction activities, ensuring that we mitigate potential impacts on local ecosystems. This proactive approach not only protects the environment but also builds trust with the communities in which we operate.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.513201919012531e-05, 'A': 3.4674919836496136e-05, 'F': 1.2486971501915476e-05, 'B': 0.9998904865332283, 'J': 7.219556243040537e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010951346677168239}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 620:
  We specialize in the collection of eelgrass, a vital marine plant known for its ecological benefits. Our operations involve careful harvesting techniques that protect the underwater ecosystem while allowing us to supply eelgrass for use in landscaping, erosion control, and as a natural habitat for marine life. Our commitment to sustainable practices ensures that we contribute positively to coastal environments while providing high-quality products that meet the needs of our clients.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.05003671043713446, 'A': 0.4159587467062665, 'F': 0.20226736759664576, 'B': 0.3216868668204862, 'J': 0.010050308439467094}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5840412532937336}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 621:
  Flora Fusion is a leader in the propagation of high-quality vegetative planting materials, focusing on both ornamental and agricultural markets. Our nursery operations include the cultivation of a wide variety of seedlings, cuttings, and grafting stock, ensuring that our plants are robust and ready for successful transplantation. We utilize cutting-edge propagation techniques to ensure the highest quality seedlings and cuttings, which are tailored to meet the needs of our clients. Our commitment to sustainability is reflected in our eco-friendly practices, from organic growing methods to responsible water usage. By partnering with local farmers and landscapers, we contribute to the growth of sustainable agriculture and enhance the beauty of our communities through vibrant green spaces.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.001357360718884929, 'A': 0.9483077149664368, 'F': 0.04603598454303882, 'B': 0.0032967977382428026, 'J': 0.0010021420333963971}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05169228503356316}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 79%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 624/788 [00:38<00:10, 16.39it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 622:
  Our lignite mining operations are designed to maximize efficiency and minimize environmental impact. We utilize innovative extraction techniques that allow us to access lignite reserves while preserving the surrounding ecosystem. Our processing capabilities include washing, dehydrating, and pulverizing lignite, which improve its quality and make it more suitable for various applications. Additionally, we focus on optimizing our warehousing and transportation strategies, ensuring that our customers receive high-quality lignite promptly and efficiently.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques. We utilize advanced drilling and blasting methods to access rich deposits, ensuring minimal environmental impact while maximizing output. Our operations are complemented by state-of-the-art washing and dehydrating processes, which enhance the quality of the lignite before it is transported to our customers. By investing in innovative technologies and sustainable practices, we aim to provide high-grade lignite that meets the energy needs of various industries while adhering to strict environmental regulations.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.503474212718858e-05, 'A': 3.434361850399032e-05, 'F': 1.2374709731242969e-05, 'B': 0.9998910518747643, 'J': 7.195054873168168e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957325110621, 6: 1.3400638860745528e-06, 7: 2.9274250518725338e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.00235754063336788, 5.2: 0.9976424593666321}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 623:
  Our aquaculture business is dedicated to the farming of aquatic plants, particularly seaweed, which has gained popularity for its nutritional benefits and versatility in food products. We utilize innovative cultivation methods that enhance growth rates while minimizing environmental impact. Our seaweed is harvested sustainably and processed into various products, including snacks, supplements, and ingredients for cosmetics. By collaborating with research institutions, we continuously explore new applications for our seaweed, contributing to a circular economy. Our focus on sustainability and innovation positions us as a leader in the burgeoning market for aquatic plants.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.014462025794363417, 'A': 0.5540171508241232, 'F': 0.02377742278445176, 'B': 0.4041159421613612, 'J': 0.0036274584357004922}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4459828491758768}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 624:
  Our logging operations are designed to maximize efficiency while minimizing environmental impact. We utilize selective logging techniques that allow us to harvest roundwood without compromising the health of the forest ecosystem. This approach not only provides high-quality timber for construction and manufacturing but also ensures that we maintain biodiversity and protect wildlife habitats. Our commitment to sustainable forestry practices is reflected in our certification from recognized environmental organizations, assuring our clients of our dedication to responsible sourcing.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0006273288421601411, 'A': 0.9779274150908621, 'F': 0.0011140983759715564, 'B': 0.019901099405504327, 'J': 0.0004300582855015618}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.022072584909137882}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                    | 626/788 [00:38<00:10, 15.80it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 625:
  We specialize in the mining and processing of hard coal, employing a range of extraction methods to optimize resource recovery. Our operations include both underground and surface mining, complemented by advanced facilities for cleaning and grading coal. By utilizing cutting-edge technology, we ensure that our products not only meet but exceed industry quality standards. Our commitment to sustainability drives us to implement practices that reduce waste and emissions, making us a responsible player in the energy market while delivering value to our customers and stakeholders.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.497639548220637e-05, 'A': 3.4356492130864226e-05, 'F': 1.2359169416592478e-05, 'B': 0.9998911545422998, 'J': 7.153400670603985e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957244501728, 6: 1.3274232613680517e-06, 7: 2.9481265659227534e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975290593045368, 5.2: 0.002470940695463072}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 626:
  Our lignite mining operations are characterized by a commitment to innovation and sustainability. We utilize advanced mining techniques that allow us to extract lignite efficiently while minimizing the ecological footprint. The extracted lignite undergoes thorough processing, including washing, dehydrating, and pulverizing, to enhance its marketability. We also offer warehousing solutions that ensure the safe storage of lignite before it is transported to customers. Our integrated approach to mining and logistics enables us to deliver high-quality products that meet the energy needs of our clients while adhering to strict environmental standards.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4922288167663065e-05, 'A': 3.441553985760494e-05, 'F': 1.236316268541313e-05, 'B': 0.999891146896213, 'J': 7.152113076562411e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995735739659, 6: 1.335173681294443e-06, 7: 2.9290866597110605e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002355475149381885, 5.2: 0.9976445248506182}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 630/788 [00:38<00:10, 14.63it/s]

RAPS scores:

==================================================
Description 627:
  Our operations are centered around the growing of vegetables and melons, where we utilize hydroponic systems to enhance growth rates and reduce land use. This method allows us to produce fresh, pesticide-free produce year-round, catering to health-conscious consumers. Our distribution network ensures that these vegetables reach local markets swiftly, maintaining peak freshness. Additionally, we engage in community-supported agriculture, allowing customers to subscribe to weekly deliveries of seasonal produce, thereby fostering a direct relationship between growers and consumers.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.19898731943980028, 'A': 0.028597627942497213, 'F': 0.05790567451308277, 'B': 0.7081442228779189, 'J': 0.006365155226700909}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2918557771220811}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 628:
  Our business is dedicated to the extraction of natural gas, where we utilize advanced drilling technologies to optimize resource recovery. We implement rigorous safety and environmental protocols to minimize our impact on surrounding ecosystems. Our processing operations include sophisticated gas desulphurization methods, ensuring that the natural gas we deliver meets high-quality standards for our customers. By fostering a culture of innovation and sustainability, we strive to lead the industry in responsible energy production and contribute to the transition towards cleaner energy sources.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.48316273711654e-05, 'A': 3.484555442709726e-05, 'F': 1.2499065879465969e-05, 'B': 0.9998905980528692, 'J': 7.2256994531452676e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010940194713082718}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 629:
  Focused on the extraction and production of natural gas, our operations are characterized by a commitment to technological innovation and environmental stewardship. We utilize advanced drilling methods and gas desulphurization processes to ensure that our products are not only efficient but also environmentally friendly. Our facilities are designed for the effective separation of liquid hydrocarbon fractions, allowing us to deliver high-quality products to our customers. By prioritizing safety and sustainability, we aim to set industry standards while meeting the growing energy demands of the market.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.5642720508240195e-05, 'A': 3.4130885594697056e-05, 'F': 1.2355024783054414e-05, 'B': 0.9998907275772572, 'J': 7.14379185690606e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7731730606518115e-06, 6: 0.9999964128805516, 7: 1.8139463876014297e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979630816701174, 6.1: 0.0020369183298826195}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 630:
  In our lignite processing facilities, we focus on washing and dehydrating the raw material to improve its quality for end-users. Utilizing cutting-edge technology, we remove impurities and enhance the calorific value of lignite, making it suitable for various applications, including electricity generation and industrial heating. Our commitment to innovation ensures that we remain competitive in the market while adhering to stringent environmental regulations, thereby providing our clients with high-quality products that meet their specific energy needs.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9990421558054964, 'A': 3.545585047362632e-05, 'F': 3.7823891575597097e-05, 'B': 0.0006918675082975317, 'J': 0.0001926969441568643}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009578441945036209}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 632/788 [00:39<00:12, 12.53it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 631:
  We are dedicated to the responsible mining of lignite, employing both traditional and innovative extraction methods to maximize efficiency. Our operations include advanced washing techniques that enhance the quality of the lignite, making it more suitable for various applications. We also focus on the logistics of warehousing and transportation, ensuring that our products are stored under optimal conditions and delivered promptly to clients. By integrating these processes, we create a seamless supply chain that not only meets customer expectations but also supports sustainable practices within the industry, reinforcing our commitment to environmental responsibility.1. Our company specializes in the extraction of lignite through both surface and underground mining techniques. By employing advanced drilling and blasting methods, we ensure efficient access to high-quality lignite deposits. Our operations are complemented by state-of-the-art machinery that minimizes environmental impact while maximizing yield. Additionally, we invest in innovative liquefaction technologies that enhance the quality of lignite, making it more suitable for various energy applications. This commitment to sustainable practices not only boosts our production efficiency but also aligns with our goal of reducing carbon emissions in the energy sector.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.5083410135887804e-05, 'A': 3.447565960811706e-05, 'F': 1.2430472731698912e-05, 'B': 0.9998908001122921, 'J': 7.210345232004972e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957317582652, 6: 1.3552926043972515e-06, 7: 2.9129491305076906e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023573651231457455, 5.2: 0.9976426348768543}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 632:
  We focus on the breeding and raising of various livestock, including rare and heritage breeds, to promote biodiversity in agriculture. Our farms are committed to sustainable practices that enhance the health of our animals and the land. We prioritize ethical breeding methods that preserve genetic diversity while ensuring the viability of our stock. Our products, including meat and dairy, are marketed as premium offerings that appeal to consumers seeking quality and sustainability. By collaborating with conservation organizations, we actively contribute to efforts aimed at protecting endangered breeds and educating the public about the importance of preserving agricultural diversity.1. Our company specializes in the raising of dairy cattle, focusing on sustainable farming practices that enhance milk production while prioritizing animal welfare. We employ advanced breeding techniques to improve herd genetics, resulting in higher yields and better quality milk. Our state-of-the-art milking facilities utilize automated systems that ensure efficiency and hygiene. Additionally, we invest in renewable energy solutions, such as solar panels, to power our operations, further reducing our carbon footprint. Our commitment to sustainability not only benefits our business but also supports local communities through job creation and partnerships with local suppliers.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.011038090222929068, 'A': 0.781814879250384, 'F': 0.031579127194471375, 'B': 0.17212874305085477, 'J': 0.0034391602813610245}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.21818512074961605}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 635/788 [00:39<00:10, 14.95it/s]

RAPS scores:

==================================================
Description 633:
  Our enterprise is dedicated to the raising of horses, focusing on breeding and training for both recreational and competitive purposes. We maintain a state-of-the-art facility that includes spacious stables, riding arenas, and training tracks. Our breeding program emphasizes conformation and temperament, producing horses that excel in various disciplines, from dressage to show jumping. We also offer training services and riding lessons, catering to enthusiasts of all skill levels. Our commitment to the equine community extends to organizing local events and competitions, promoting a culture of excellence and sportsmanship among riders and trainers alike.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0016212439740056742, 'A': 0.5160913957930577, 'F': 0.47599701163786196, 'B': 0.004518292832079094, 'J': 0.0017720557629954867}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.48390860420694226}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 634:
  We are dedicated to the cultivation of high-quality timber through innovative silvicultural techniques. Our operations include the careful management of tree growth cycles, from planting to thinning, ensuring that each tree reaches its full potential. We also focus on the establishment of forest tree nurseries, where we grow a diverse selection of seedlings for both commercial and conservation purposes. Our commitment to research and development allows us to stay at the forefront of forestry practices, ensuring that we provide sustainable solutions to meet the growing demand for timber products.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.0001850741279080386, 'A': 0.9974544098032396, 'F': 0.0012007203272466158, 'B': 0.0010025886977561378, 'J': 0.0001572070438495246}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0025455901967603722}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 635:
  We specialize in the production of oleaginous fruits, particularly olives, which are harvested for both oil and table consumption. Our groves are cultivated using traditional methods combined with modern agricultural practices to ensure high-quality yields. We produce a range of olive oils, from extra virgin to flavored varieties, catering to diverse culinary preferences. Our commitment to quality is reflected in our careful processing techniques, and we actively participate in food fairs and exhibitions to promote our products and educate consumers about the health benefits of olive oil.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9994573860187549, 'A': 3.1749124945657536e-05, 'F': 4.725401287816195e-05, 'B': 0.00026148685199801577, 'J': 0.0002021239914232077}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0005426139812451103}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 636:
  Our company is dedicated to supporting the transportation of lignite through a network of logistics services that streamline the delivery process. We operate a fleet of specialized vehicles designed for the safe and efficient transport of lignite to various industrial clients. Additionally, we collaborate with rail and barge operators to expand our reach, ensuring that our products can be delivered to both domestic and international markets. This integrated approach to transportation enhances our service offerings and strengthens our position in the lignite supply chain.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.00024469897384890013, 'A': 0.0001722782600815822, 'F': 0.998207033571647, 'B': 4.295960057811028e-05, 'J': 0.001333029593844413}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0017929664283530267}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 641/788 [00:39<00:09, 16.23it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 637:
  Our company is actively engaged in the capture fishery sector, concentrating on the collection of aquatic organisms for both consumption and ecological restoration. We employ a range of fishing techniques, including hand-collecting and netting, to gather species such as fish and crustaceans from various water bodies. Our commitment to sustainability is evident in our partnerships with environmental organizations, which help us implement best practices in fishing and habitat preservation. Additionally, we offer educational programs that inform the public about the importance of sustainable fisheries, fostering a culture of conservation within the community.1. The company specializes in marine fishing, utilizing a fleet of modern trawlers equipped with advanced sonar technology to locate schools of fish efficiently. By employing sustainable fishing practices, they ensure that their catch includes a variety of species, such as cod and haddock, while minimizing bycatch. The fish are processed on board and immediately frozen to preserve freshness, allowing for high-quality products that are distributed to markets and restaurants worldwide. Additionally, the company engages in community outreach programs to educate local fishermen on sustainable practices, reinforcing their commitment to responsible fishing and environmental stewardship.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.2397211037649002e-05, 'A': 0.99989789459505, 'F': 4.103076652977904e-05, 'B': 3.4154708634466236e-05, 'J': 1.4522718748175707e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007503263594025419, 2: 0.0009164805541768319, 3: 0.9983331930864205}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9585360406157032, 3.2: 0.04146395938429669}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 638:
  Our aquaculture business is dedicated to the sustainable farming of aquatic plants, particularly seaweed, which is increasingly recognized for its nutritional and environmental benefits. We cultivate various species of seaweed in controlled environments, employing techniques that promote rapid growth and high yields. Our operations prioritize minimal environmental impact, utilizing renewable energy sources and reducing water usage through efficient farming practices. The harvested seaweed is processed into a range of products, including food ingredients, dietary supplements, and biofuels, contributing to a circular economy and supporting sustainable practices in the food industry.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.001143225673957832, 'A': 0.9813035244034496, 'F': 0.0034578313190180153, 'B': 0.013465948790559842, 'J': 0.0006294698130146173}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.01869647559655041}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 639:
  As a prominent grower of tobacco, we focus on cultivating high-quality leaf varieties that meet the stringent demands of the tobacco industry. Our farms employ integrated pest management strategies to minimize chemical usage while ensuring robust plant health. We also invest in research to develop new strains that offer unique flavor profiles and improved resilience. Our processing facilities are equipped to handle the curing and fermentation processes, essential for producing premium tobacco products. Through responsible sourcing and community engagement, we strive to create a positive impact on the regions where we operate while adhering to regulatory standards.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.994826247211178, 'A': 0.0002226447735799796, 'F': 0.0004176542426118463, 'B': 0.003912094051941793, 'J': 0.0006213597206885679}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005173752788822039}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 640:
  Our business focuses on the collection of wild nuts, particularly chestnuts and acorns, which are harvested from sustainably managed forests. We process these nuts into a variety of products, including flours and oils, that appeal to health-conscious consumers and gourmet chefs alike. By promoting the nutritional benefits of these wild ingredients, we aim to create a niche market that values natural, unprocessed foods. Our partnerships with local farmers and foragers allow us to maintain a steady supply while ensuring that our practices contribute positively to the environment.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.2453949977480121, 'A': 0.0102188826213878, 'F': 0.019722425692910273, 'B': 0.7208300150691913, 'J': 0.0038336788684984377}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2791699849308087}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 643/788 [00:39<00:09, 15.41it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 641:
  Our company is dedicated to the extraction of crude petroleum, employing a combination of conventional and unconventional methods to optimize resource recovery. We utilize advanced reservoir modeling techniques to enhance our understanding of oil fields, allowing for more strategic drilling decisions. Our commitment to technological advancement is reflected in our use of automated drilling systems, which increase safety and efficiency. Furthermore, we prioritize sustainability by implementing measures to reduce emissions and conserve water during extraction processes. By balancing operational excellence with environmental responsibility, we strive to meet the growing global demand for crude oil while minimizing our ecological footprint.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.4968006741277776e-05, 'A': 3.462495825978553e-05, 'F': 1.2420942121013034e-05, 'B': 0.9998907851535778, 'J': 7.200939300068223e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7663224441613852e-06, 6: 0.9999964156396339, 7: 1.8180379221252568e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020556751283597177, 6.1: 0.9979443248716402}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 642:
  We are engaged in the production of roundwood, specifically targeting the construction sector with high-quality logs. Our logging operations are designed to be environmentally responsible, utilizing selective cutting methods that preserve the surrounding ecosystem. The timber we harvest is processed into various forms, including beams and planks, which are essential for building and infrastructure projects. Additionally, we offer firewood as a byproduct of our operations, catering to local markets and promoting the use of renewable energy sources for heating.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9988394858658499, 'A': 5.023453329012051e-05, 'F': 5.732649992698642e-05, 'B': 0.0008497797960004889, 'J': 0.00020317330493255386}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0011605141341500813}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 643:
  Our business focuses on the collection of aquatic plants, particularly seaweed, which has gained popularity in health food markets. We operate in coastal waters, employing sustainable harvesting methods that promote regrowth and ecological balance. Our seaweed is processed into various products, including snacks, supplements, and culinary ingredients, catering to the growing demand for plant-based foods. We collaborate with researchers to study the nutritional benefits of seaweed, enhancing our product offerings while educating consumers about its environmental advantages, such as carbon sequestration and habitat support for marine life.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.0175267784736574, 'A': 0.7203198144098863, 'F': 0.0547448698359108, 'B': 0.20256797805175925, 'J': 0.00484055922878625}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.27968018559011365}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 645/788 [00:39<00:09, 14.96it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 644:
  Our operations in hard coal mining are characterized by a blend of traditional expertise and modern technology. We employ both surface and underground mining techniques, allowing us to adapt to different geological conditions while maximizing resource extraction. The coal extracted is subjected to rigorous cleaning and sizing processes, ensuring that it meets the quality standards required by our clients. By focusing on efficiency and sustainability, we aim to provide a reliable supply of high-quality coal that supports energy production and contributes to the sustainable management of natural resources.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.494463631634845e-05, 'A': 3.433217937931833e-05, 'F': 1.234819889111892e-05, 'B': 0.9998912269375024, 'J': 7.148047910840088e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957169386924, 6: 1.3376831803295993e-06, 7: 2.945378127282322e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975282587788942, 5.2: 0.0024717412211057786}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 645:
  At Heritage Farms, we specialize in the raising of other cattle and buffaloes, focusing on organic beef production. Our cattle are raised on lush pastures, ensuring they are grass-fed and free from synthetic additives. We operate a farm-to-consumer model, allowing customers to purchase beef directly from us through subscription boxes. Our commitment to transparency is reflected in our practices, where we provide detailed information about the animal's diet and living conditions. By connecting with our customers through social media and farm events, we build a community that values ethical and sustainable meat production.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00038336093565835636, 'A': 0.9940382005487411, 'F': 0.0015182050174084277, 'B': 0.003787909722421878, 'J': 0.0002723237757701128}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0059617994512588535}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 646:
  We are engaged in the raising of other livestock, including alpacas and llamas, focusing on sustainable practices that enhance both animal welfare and product quality. Our operations include breeding programs aimed at producing high-quality fiber, which is harvested and processed into textiles. We also offer farm tours and educational experiences for visitors, highlighting the benefits of alternative livestock farming. Our commitment to sustainability is reflected in our land management practices, which promote ecological balance and biodiversity. We actively participate in local markets to promote our unique products.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00019435419650133058, 'A': 0.9971633076998334, 'F': 0.0012863709442664452, 'B': 0.0011905959397567692, 'J': 0.00016537121964186772}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.002836692300166588}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 651/788 [00:40<00:07, 18.15it/s]

RAPS scores:

==================================================
Description 647:
  Our focus is on the mining of cobalt ores, a vital component for lithium-ion batteries used in electric vehicles and renewable energy storage systems. We employ sustainable mining practices and advanced processing technologies to ensure the efficient extraction of cobalt while minimizing environmental impact. Our research team is dedicated to exploring new methods of refining cobalt to enhance its purity and performance in battery applications. By collaborating with industry partners and stakeholders, we aim to support the growing demand for clean energy solutions and contribute to the global transition towards sustainable transportation.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.508278735494548e-05, 'A': 3.437134678423155e-05, 'F': 1.2343619661707021e-05, 'B': 0.9998910571778702, 'J': 7.145068328891845e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4726687357785883e-06, 6: 1.5944257918457569e-06, 7: 0.9999959329054723}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.035314963940918744, 7.2: 0.9646850360590814}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 648:
  We are dedicated to advancing forest conservation through innovative thinning practices that enhance forest health and productivity. By selectively removing certain trees, we improve light penetration and nutrient availability for remaining trees, leading to stronger growth and increased biodiversity. Our team employs state-of-the-art technology to monitor forest conditions and assess the impact of our interventions, ensuring that our practices are both effective and environmentally responsible.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 6.335988325290432e-05, 'A': 0.9990627069458305, 'F': 0.0005885058784011756, 'B': 0.00021620855761264588, 'J': 6.921873490253306e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009372930541694524}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 649:
  Our company excels in crude petroleum extraction by employing a multi-faceted approach that includes geological research, advanced drilling techniques, and environmental stewardship. We utilize 3D seismic imaging to accurately locate oil reserves, which allows us to minimize drilling risks and costs. Our extraction processes are designed to be as efficient as possible, reducing the time from exploration to production. Furthermore, we actively engage with stakeholders to ensure transparency and foster trust, reinforcing our commitment to responsible resource management.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.479793140538446e-05, 'A': 3.484482883047368e-05, 'F': 1.2490650664003004e-05, 'B': 0.9998906362381964, 'J': 7.230350903554327e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010936376180359364}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 650:
  Our organization focuses on the operation of forest tree nurseries, where we propagate a diverse range of native and commercially valuable tree species. We employ state-of-the-art propagation techniques, including tissue culture and seedling production, to ensure high germination rates and robust plant health. In addition to supplying seedlings for reforestation projects, we provide technical support and guidance to customers on best practices for planting and maintaining young trees. Our commitment to quality and sustainability has positioned us as a trusted partner for both governmental and non-governmental organizations involved in forest restoration initiatives.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00015420285773390767, 'A': 0.9961753732519132, 'F': 0.0030721513997424613, 'B': 0.00043637434302525637, 'J': 0.00016189814758515216}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0038246267480868124}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 651:
  Our firm is dedicated to the extraction of crude petroleum, focusing on both traditional and unconventional resources. We utilize advanced seismic imaging technologies to identify potential drilling sites with high yield potential. Our operations are supported by a robust supply chain that ensures timely delivery of materials and equipment. We also engage in community partnerships to promote local development and environmental stewardship. By integrating sustainable practices into our extraction processes, we aim to balance the demand for energy with the need for ecological preservation, ultimately contributing to a more sustainable future.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5054399802647137e-05, 'A': 3.4774120494491544e-05, 'F': 1.2508994103261599e-05, 'B': 0.9998904277442254, 'J': 7.234741374295035e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010957225577457042}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 655/788 [00:40<00:08, 16.10it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 652:
  We are dedicated to the sustainable mining of lignite, employing innovative extraction techniques that minimize environmental impact. Our operations include both surface and underground mining, with a strong emphasis on safety and efficiency. After extraction, the lignite undergoes a comprehensive washing and dehydrating process to enhance its quality for energy production. We also engage in the pulverizing of lignite to meet specific customer specifications, ensuring our products are tailored to the diverse needs of the energy sector.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4797214778196697e-05, 'A': 3.467446742864033e-05, 'F': 1.2440658424959853e-05, 'B': 0.999890909931097, 'J': 7.177728271354345e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957274676038, 6: 1.3456391506102405e-06, 7: 2.926893245597644e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023556152200939103, 5.2: 0.997644384779906}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 653:
  Our business is dedicated to the production of roundwood for various applications, including construction and utility needs. We operate several logging sites equipped with modern machinery that allows us to efficiently harvest timber while minimizing environmental impact. The logs are sorted and transported to our processing facilities, where they are cut to specification for clients requiring pit-props, fence posts, and utility poles. This commitment to quality and sustainability ensures that our products meet the rigorous standards of our customers in the forestry and construction sectors.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9993088911608721, 'A': 3.269109188022734e-05, 'F': 3.683880450538623e-05, 'B': 0.0004565862813739968, 'J': 0.00016499266136818988}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0006911088391279296}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 654:
  Operating in coastal waters, the company utilizes stationary traps and nets to capture crustaceans, particularly shrimp and crabs. Their fishing operations are designed to minimize environmental impact, employing selective gear that reduces bycatch. The harvested seafood is processed on-site, ensuring optimal freshness before distribution to wholesalers and retailers. The company also invests in research to improve trap designs and fishing techniques, thereby enhancing efficiency and sustainability. Their commitment to quality is reflected in their certifications from recognized seafood sustainability programs.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1196178252186565e-05, 'A': 0.9999049166665979, 'F': 3.8999731291775064e-05, 'B': 3.1274031623621025e-05, 'J': 1.3613392234686516e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007403797433604118, 2: 0.0009121790894629748, 3: 0.9983474411671767}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9587832312060637, 3.2: 0.041216768793936195}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 658/788 [00:40<00:08, 16.04it/s]

RAPS scores:

==================================================
Description 655:
  We specialize in the cultivation of pome fruits, such as apples and pears, utilizing modern horticultural techniques to maximize yield and fruit quality. Our orchards are designed for efficiency, with precise spacing and pruning methods that promote optimal sunlight exposure and air circulation. We are committed to sustainable practices, including organic pest control and soil enrichment strategies, which enhance the health of our trees and the surrounding ecosystem. Our fruits are marketed through various channels, including farmer’s markets and grocery chains, where consumers appreciate our focus on freshness and sustainability.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.9855494705392117, 'A': 0.0005725706099987647, 'F': 0.0016729303542147112, 'B': 0.010995408154557958, 'J': 0.0012096203420167097}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.014450529460788286}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 656:
  Our company is dedicated to the mining of iron ores, utilizing advanced methodologies to ensure high efficiency and minimal environmental impact. We implement cutting-edge beneficiation techniques, including dense medium separation and sintering, to produce high-quality iron products tailored to the needs of our customers. Additionally, we engage in rigorous technical testing and analysis to maintain product integrity and compliance with industry standards. Our focus on continuous improvement and innovation positions us as a reliable partner in the global iron and steel supply chain.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.580562288592949e-05, 'A': 3.410144494023785e-05, 'F': 1.2336885470586702e-05, 'B': 0.9998906111604285, 'J': 7.1448862747491515e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938883957145595}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 657:
  As a leader in the mining sector, our company is dedicated to the sustainable extraction of iron ores. We operate multiple mines that are equipped with advanced technologies for ore detection and extraction. Our beneficiation processes include crushing, screening, and magnetic separation, which maximize the recovery of iron content while minimizing environmental impact. We also engage in comprehensive geological assessments to ensure the longevity of our mining operations. By focusing on quality and sustainability, we provide our clients with superior iron ore products that support their production needs and contribute to responsible resource management.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.519097018928732e-05, 'A': 3.4083980588374936e-05, 'F': 1.2291525096397316e-05, 'B': 0.9998913080940708, 'J': 7.12543005521441e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.483894644049737e-06, 6: 1.575633785412569e-06, 7: 0.9999959404715705}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677780376005071, 7.2: 0.0322219623994929}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 662/788 [00:40<00:07, 15.87it/s]

[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:

==================================================
Description 658:
  The organization focuses on artisanal fishing practices, promoting traditional methods that have been passed down through generations. They work closely with local fishermen to preserve cultural heritage while ensuring sustainable fish stocks. The company markets their catch as premium, locally sourced seafood, appealing to consumers who value quality and sustainability. They also host community events, including fish festivals and cooking classes, to educate the public about the importance of supporting local fisheries and the benefits of consuming sustainably sourced seafood.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.1053617150954895e-05, 'A': 0.9999051410618619, 'F': 4.054220529801248e-05, 'B': 2.9832281956407002e-05, 'J': 1.343083373265259e-05}
Division sets: {'A': [3]}
Division probs: {'A': {1: 0.0007094479026263471, 2: 0.000923300045687371, 3: 0.9983672520516863}}
Class sets: {}
Class probs: {}
Final output: {'type': 'class_level', 'codes': []}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 659:
  We specialize in the production of alligator and crocodile farming, catering to both the culinary and leather industries. Our farms are designed to ensure the well-being of these reptiles while maximizing growth rates through controlled breeding and feeding practices. We adhere to strict regulations to maintain animal welfare and environmental standards. Our products include high-quality meat and sustainable leather goods, which are marketed to niche markets and luxury brands. By promoting the sustainable use of these species, we contribute to conservation efforts while providing unique products that appeal to discerning consumers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.9126430712955065, 'A': 0.0024746609060683758, 'F': 0.005599003663859831, 'B': 0.07643906260624408, 'J': 0.002844201528321034}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.08735692870449352}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 660:
  As a leader in the production of charcoal using traditional methods, our company operates within forested areas where we gather suitable wood materials. We prioritize eco-friendly practices, ensuring that our charcoal is produced with minimal waste and environmental disruption. Our products are marketed to both local and international markets, appealing to consumers who value natural and sustainable fuel sources. We also engage in community education programs to promote the benefits of using charcoal as a clean energy alternative, further enhancing our brand reputation and commitment to environmental stewardship.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9984790655847691, 'A': 6.11071545662167e-05, 'F': 7.522147294255254e-05, 'B': 0.0011481638781468244, 'J': 0.00023644190957532228}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0015209344152309345}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 661:
  Our company is at the forefront of hard coal mining, employing innovative techniques to maximize extraction while minimizing environmental impact. We utilize a combination of underground and surface mining methods, tailored to the specific geological conditions of our sites. The coal is then processed through advanced cleaning and sizing operations, ensuring that it meets rigorous quality standards. Our investment in liquefaction technologies allows us to produce cleaner coal, facilitating its transport and storage, and making it a preferred choice for energy producers seeking sustainable solutions.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.50667649092995e-05, 'A': 3.439518777756425e-05, 'F': 1.2371231179467737e-05, 'B': 0.9998910061815339, 'J': 7.160634599786645e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957131922942, 6: 1.3211074063287397e-06, 7: 2.96570029960081e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975291415759199, 5.2: 0.0024708584240802434}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 665/788 [00:41<00:06, 18.77it/s]

RAPS scores:

==================================================
Description 662:
  Our company specializes in sustainable logging practices that prioritize environmental stewardship while meeting the demand for high-quality roundwood. We operate in diverse forest ecosystems, utilizing advanced techniques to ensure minimal impact on the surrounding environment. Our logs are harvested for various applications, including construction and manufacturing. Additionally, we engage in the production of firewood, catering to both residential and commercial markets. By employing skilled labor and modern machinery, we ensure that our operations are efficient and responsible, contributing to the local economy while promoting forest regeneration.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0037885851519355723, 'A': 0.4724480922002774, 'F': 0.00476452292996586, 'B': 0.5174605076145563, 'J': 0.0015382921032648085}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4825394923854437}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 663:
  This company is at the forefront of natural gas extraction, utilizing innovative techniques to access and produce gaseous hydrocarbons efficiently. Their operations include the separation of valuable liquid hydrocarbon fractions from raw natural gas, ensuring high-quality products for various markets. The firm has made significant investments in gas desulfurization technologies, which not only enhance product quality but also minimize environmental impact. By prioritizing safety and sustainability, the company positions itself as a responsible energy provider while meeting the growing demand for cleaner energy solutions.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.6258318499870184e-05, 'A': 3.759426965103826e-05, 'F': 1.3235951446376254e-05, 'B': 0.9998852386719146, 'J': 7.672788488012674e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011476132808541095}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 664:
  Our business focuses on the sustainable gathering of vegetable hair, specifically from plants like agave and coconut husks. We process these fibers into a variety of eco-friendly products, including brushes and brooms, catering to the growing demand for sustainable household items. By working directly with farmers, we ensure that our sourcing practices support local economies and promote environmental sustainability. Our commitment to quality and ethical production resonates with consumers who are increasingly seeking alternatives to synthetic materials in their everyday lives.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9871550496476065, 'A': 0.0005014527590622819, 'F': 0.0018916408118184998, 'B': 0.00905480413730165, 'J': 0.0013970526442111534}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012844950352393525}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 665:
  Our business revolves around the sustainable collection of vegetable hair, which is harvested from specific plants known for their fibrous properties. We process these fibers into brushes, brooms, and other cleaning tools, emphasizing their biodegradable nature and eco-friendliness. Our products are marketed to environmentally conscious consumers and businesses looking to reduce their plastic footprint. We also engage in educational initiatives to raise awareness about the benefits of using natural materials in everyday products, fostering a shift towards more sustainable consumption patterns.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9995740435893382, 'A': 2.3934967558851336e-05, 'F': 3.9200193184585046e-05, 'B': 0.00013463639995815063, 'J': 0.00022818484996054797}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00042595641066178747}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 670/788 [00:41<00:05, 19.85it/s]

RAPS scores:

==================================================
Description 666:
  Our business model revolves around the extraction of natural gas and the efficient separation of hydrocarbon fractions. We employ cutting-edge technologies to maximize yield while maintaining a strong focus on safety and environmental responsibility. Our facilities are designed to process raw gas into market-ready products, utilizing advanced desulphurisation techniques that ensure compliance with stringent quality standards. By fostering a culture of innovation, we continuously seek to improve our operational efficiency and reduce costs, ultimately delivering greater value to our customers and shareholders alike.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.506722103697686e-05, 'A': 3.441581598153695e-05, 'F': 1.2390520628575888e-05, 'B': 0.9998909446791553, 'J': 7.18176319747535e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7846728228208951e-06, 6: 0.9999964061516745, 7: 1.8091755026674588e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979691008535547, 6.1: 0.0020308991464452575}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 667:
  In the realm of freshwater aquaculture, we operate a state-of-the-art facility dedicated to the cultivation of tilapia and catfish. Our approach integrates modern technology, such as automated feeding systems and water quality sensors, to maximize efficiency and productivity. We focus on biosecure practices to prevent disease and ensure the health of our fish stocks. Our products are marketed directly to local grocery chains and restaurants, emphasizing freshness and quality. Additionally, we engage in community outreach programs to educate consumers about the benefits of farm-raised fish, promoting sustainable eating habits and supporting local economies.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 7.289850877620451e-05, 'A': 0.9991276831389851, 'F': 0.00044164326416350696, 'B': 0.0002862051658584881, 'J': 7.156992221691762e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008723168610148546}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 668:
  Our company is dedicated to the sustainable gathering of forest harvesting residues, which we transform into energy products. By focusing on the collection of leftover materials such as branches, leaves, and sawdust, we minimize waste and contribute to a circular economy. These residues are processed into high-quality wood chips and pellets, which are then supplied to biomass power plants and heating systems. Our operations are designed to be environmentally friendly, promoting the use of renewable energy sources while supporting local economies through job creation and resource management.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.006588280981230114, 'A': 0.15061600791120153, 'F': 0.006746702408944278, 'B': 0.8343772967228097, 'J': 0.0016717119758143408}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.1656227032771903}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 669:
  We engage in the cultivation of specialty wood products, focusing on high-value species that are in demand for luxury furniture and flooring. Our operations include the careful management of growth cycles and the implementation of sustainable harvesting practices. By partnering with local artisans and manufacturers, we ensure that our timber is transformed into exquisite products that highlight the beauty and durability of responsibly sourced materials.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.9944748137584816, 'A': 0.0002121757353938486, 'F': 0.000374967643953654, 'B': 0.004398061720786975, 'J': 0.0005399811413838288}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005525186241518432}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 670:
  In the realm of freshwater aquaculture, our operations are centered on the cultivation of tilapia and catfish in carefully monitored environments. We implement integrated pest management strategies to protect our stocks from diseases while ensuring optimal growth conditions. Our facilities are equipped with state-of-the-art aeration systems that enhance oxygen levels in the water, promoting healthier fish. We also engage in research and development to improve breeding techniques, which allows us to produce faster-growing and disease-resistant strains. Our products are distributed to both local and international markets, contributing to food security and economic growth.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.002216862765310359, 'A': 0.9607774663189622, 'F': 0.008745075556982444, 'B': 0.027167290003108625, 'J': 0.0010933053556363692}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.039222533681037786}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 671:
  We operate a family-owned orchard dedicated to the growing of pome fruits, particularly apples and pears. Our focus on heirloom varieties allows us to offer unique flavors and textures that appeal to discerning consumers. We practice sustainable farming techniques, including cover cropping and organic pest control, to maintain soil health and biodiversity. Our fruits are sold directly to consumers through farmers' markets and online platforms, where we emphasize the importance of local agriculture. Additionally, we produce homemade preserves and cider from our surplus fruit, creating additional value and reducing waste.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.0692819960859846, 'A': 0.21824302536923235, 'F': 0.1295147457966586, 'B': 0.5747735277797281, 'J': 0.008186704968396397}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4252264722202719}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 676/788 [00:41<00:05, 22.34it/s]

RAPS scores:

==================================================
Description 672:
  As a leader in the forestry sector, we are committed to the sustainable growth of firewood and biomass resources. Our operations include the careful management of forested areas to produce high-quality firewood while maintaining the ecological balance of the environment. We employ efficient harvesting methods that minimize waste and promote regeneration. By offering firewood products that meet stringent quality standards, we cater to both residential and commercial markets, contributing to the local economy while promoting renewable energy sources.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00016554261319431628, 'A': 0.997548951953646, 'F': 0.0005793248692027952, 'B': 0.0015692635214305617, 'J': 0.0001369170425263676}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0024510480463539874}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 673:
  Our company focuses on the sustainable gathering of wood for energy, utilizing both roundwood and forest residues to produce biomass fuel. Our operations are designed to minimize waste and maximize efficiency, allowing us to provide a reliable energy source for both residential and commercial applications. We work closely with local forestry partners to ensure that our practices support long-term forest health and sustainability. By promoting the use of renewable energy, we contribute to a cleaner environment and a more sustainable future for our communities.1. Our company specializes in sustainable logging practices, focusing on the selective harvesting of roundwood for various forest-based manufacturing industries. By employing advanced techniques and maintaining strict environmental standards, we ensure that our operations minimize ecological impact while maximizing yield. Our logs are processed into high-quality timber, which is then supplied to manufacturers for furniture, construction, and other applications. Additionally, we offer consulting services to help other businesses implement sustainable forestry practices, promoting responsible resource management across the sector.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.010658255261279824, 'A': 0.04446641465722996, 'F': 0.005498674101596956, 'B': 0.9379465978019833, 'J': 0.0014300581779100182}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.062053402198016694}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 674:
  Engaging in the production of roundwood for the manufacturing sector, we provide high-quality timber that serves as the backbone for various industrial applications. Our logging operations are designed to be efficient and environmentally responsible, utilizing advanced technology to minimize waste and maximize yield. The roundwood we supply is processed into plywood, particleboard, and other engineered wood products, catering to the construction and furniture industries. By maintaining strong relationships with manufacturers, we ensure a steady supply of raw materials that meet their specific needs, driving innovation and sustainability in wood product development.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997613330548082, 'A': 1.3627640671082541e-05, 'F': 1.5996582648273853e-05, 'B': 8.328640962580913e-05, 'J': 0.00012575631224669213}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002386669451918122}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 675:
  Our company is at the forefront of forest harvesting residue collection, transforming what was once considered waste into valuable energy resources. By gathering branches, leaves, and other by-products from logging activities, we produce biomass fuel that can be used in power generation. Our innovative processing techniques ensure that these residues are converted efficiently, providing a sustainable alternative to fossil fuels. We work closely with local forestry operations to streamline collection and processing, creating a circular economy that benefits both the environment and the community.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.002805284679300878, 'A': 0.731942157603203, 'F': 0.0037146156221924773, 'B': 0.2601849747012905, 'J': 0.0013529673940131984}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.268057842396797}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 676:
  Our company specializes in the extraction of crude petroleum, utilizing advanced exploration techniques such as 3D seismic imaging to identify potential drilling sites. We operate a fleet of modern drilling rigs designed for both onshore and offshore environments, ensuring that we can access a diverse range of oil reserves. Our commitment to innovation drives us to implement enhanced oil recovery techniques that improve extraction efficiency while minimizing environmental impact. In addition, we engage in comprehensive stakeholder engagement to ensure that our operations align with community interests and contribute positively to local economies.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.4999464493473144e-05, 'A': 3.5102289157211945e-05, 'F': 1.2610052902290234e-05, 'B': 0.9998899937287109, 'J': 7.29446473602158e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011000627128909812}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 679/788 [00:41<00:04, 23.57it/s]

RAPS scores:

==================================================
Description 677:
  We are dedicated to the growth and distribution of tropical and subtropical fruits, including mangoes, papayas, and avocados. Our operations span multiple regions, allowing us to provide a year-round supply of these sought-after products. By implementing integrated pest management and organic farming practices, we ensure that our fruits are not only delicious but also environmentally friendly. Our commitment to quality is reflected in our rigorous testing and certification processes, which guarantee that our fruits meet the highest standards. We collaborate closely with retailers to develop marketing strategies that highlight the unique flavors and health benefits of our offerings.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.33939409043057334, 'A': 0.04320839026153826, 'F': 0.20826881178216924, 'B': 0.3962644075876603, 'J': 0.01286429993805876}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.6037355924123398}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 678:
  Our company excels in the cultivation of bulbs, tubers, and roots, providing a diverse range of planting materials for both commercial and home gardeners. We focus on high-yield varieties that are well-suited to various climates and soil types, ensuring successful growth and vibrant blooms. Our commitment to quality control includes rigorous testing and monitoring throughout the growing process, allowing us to deliver exceptional products that meet the needs of our customers. We also offer planting guides and support to help gardeners achieve the best results with our products.
True: section=A, division=1, class=1.3
Section set: []
Section probs: {'C': 0.6579707373231296, 'A': 0.020760640728562145, 'F': 0.18488218677321672, 'B': 0.1233094962333782, 'J': 0.0130769389417133}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3420292626768704}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 679:
  Engaging in freshwater fishing, our company operates in various lakes and rivers, using both traditional and innovative fishing techniques. We utilize a combination of nets and lines, tailored to target specific species such as trout and bass. Our commitment to sustainability is reflected in our catch-and-release programs and efforts to restock fish populations in collaboration with local conservation groups. We also offer guided fishing tours, providing customers with an immersive experience while educating them about the importance of preserving aquatic ecosystems. Our products are marketed directly to consumers, ensuring they receive the freshest catch possible.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 4.974252493533537e-05, 'A': 0.999451827619079, 'F': 0.00016207825930438804, 'B': 0.00028716786195690544, 'J': 4.91837347244087e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0005481723809209749}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 680:
  Engaging in freshwater fishing, the company operates in lakes and rivers, employing both traditional and modern fishing techniques. They utilize specialized gear, such as gill nets and traps, to target species like trout and catfish. The company also emphasizes the importance of catch-and-release practices to maintain fish populations and promote biodiversity. Additionally, they run educational programs for local communities, teaching sustainable fishing methods and the significance of preserving aquatic ecosystems. This commitment not only enhances their brand reputation but also fosters a sense of stewardship among consumers who value responsible fishing practices.
True: section=A, division=3, class=3.1
Section set: ['A']
Section probs: {'C': 1.103518643367097e-05, 'A': 0.999905763843088, 'F': 4.012229571599321e-05, 'B': 2.9635931361669286e-05, 'J': 1.3442743400684069e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007563209375493381, 2: 0.00091991651336845, 3: 0.9983237625490821}}
Class sets: {'3': ['3.1']}
Class probs: {'3': {3.1: 0.9589163718813944, 3.2: 0.04108362811860549}}
Final output: {'type': 'class_level', 'codes': ['3.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 682/788 [00:41<00:05, 17.82it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 681:
  Our core business is the extraction of crude petroleum, where we employ a range of advanced technologies to enhance production efficiency. Our exploration teams utilize geophysical surveys and data analytics to identify promising drilling sites, while our production facilities are equipped with the latest in separation and refining technology. We are committed to reducing our environmental footprint through initiatives such as water recycling and emissions reduction programs. By fostering a culture of safety and innovation, we strive to maintain our position as a leader in the crude oil extraction sector while delivering sustainable growth.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.513003839372992e-05, 'A': 3.4335046016026665e-05, 'F': 1.23496156371325e-05, 'B': 0.9998910356308016, 'J': 7.149669151559624e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7772276740507827e-06, 6: 0.9999963952962726, 7: 1.8274760535257173e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020540353278015113, 6.1: 0.9979459646721984}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 682:
  Our operations in amphibian aquaculture specialize in the breeding and farming of frogs, particularly for culinary markets. We implement biosecure farming practices that ensure the health and growth of our stock while minimizing ecological disruption. Our facilities are equipped with climate-controlled environments that optimize breeding cycles, resulting in high-quality products. By focusing on sustainable harvesting and responsible sourcing, we cater to gourmet restaurants and specialty markets, promoting the culinary versatility of amphibians while supporting biodiversity.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0014744168096695266, 'A': 0.9709440600390731, 'F': 0.0036602205214426365, 'B': 0.02313113578962609, 'J': 0.0007901668401888598}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.029055939960926924}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 688/788 [00:42<00:05, 18.57it/s]

RAPS scores:

==================================================
Description 683:
  Our operations center around the mining of high-quality iron ores, with a strong emphasis on sustainable practices. We employ advanced beneficiation techniques to process the ore, which includes crushing, grinding, and magnetic separation to improve its iron content. The agglomeration of the processed ore into pellets is a key aspect of our business, as it enhances the efficiency of transportation and downstream processing. By continuously investing in technology and adhering to environmental standards, we ensure that our operations contribute positively to the mining industry and the communities we serve.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5747676810422316e-05, 'A': 3.398076420836017e-05, 'F': 1.2283542397299196e-05, 'B': 0.9998908635443775, 'J': 7.124472206428675e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.486729376139479e-06, 6: 1.573108367995197e-06, 7: 0.9999959401622558}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677741712931631, 7.2: 0.03222582870683677}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 684:
  Our company focuses on the mining of cobalt and lithium ores, essential components in the production of batteries for electric vehicles and renewable energy storage systems. We utilize innovative mining techniques that prioritize safety and environmental responsibility, ensuring minimal disruption to local ecosystems. Our research and development team is actively exploring new methods to enhance ore recovery and reduce processing costs. By establishing strategic partnerships with battery manufacturers, we aim to secure a stable supply chain for these critical materials, contributing to the transition towards a more sustainable energy future.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.5722398046799195e-05, 'A': 3.415936412396984e-05, 'F': 1.2329076389139326e-05, 'B': 0.999890664021373, 'J': 7.125140067055423e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010933597862694544}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 685:
  Our business is dedicated to the breeding and raising of sheep, with a strong emphasis on producing high-quality wool and meat. We implement rotational grazing techniques that promote soil health and enhance pasture quality, which in turn improves the well-being of our flock. Our shearing process is conducted with care to ensure minimal stress on the animals, and we maintain strict quality control standards for our wool products. We also engage in educational outreach to promote sustainable sheep farming practices within our community, fostering a culture of responsible agriculture.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0016671629695868297, 'A': 0.9628114625388757, 'F': 0.007043411980927298, 'B': 0.027587574429853393, 'J': 0.000890388080756655}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03718853746112427}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 686:
  In the crude petroleum extraction sector, our company stands out for its commitment to technological innovation and environmental responsibility. We utilize advanced drilling technologies, including rotary steerable systems and real-time data analytics, to enhance our extraction processes. Our operations are designed to minimize ecological disruption, employing best practices in waste management and emissions control. By fostering a culture of safety and continuous improvement, we ensure that our extraction activities not only contribute to energy production but also uphold our commitment to sustainability and community engagement.1. Our company specializes in the exploration and extraction of crude petroleum, utilizing advanced seismic imaging and drilling technologies to locate and recover oil reserves efficiently. We deploy state-of-the-art drilling rigs and employ enhanced oil recovery techniques to maximize yield from existing fields. Our commitment to sustainability drives us to implement environmentally responsible practices, including minimizing flaring and utilizing water recycling systems. By investing in research and development, we aim to innovate in extraction methods, reduce operational costs, and improve safety measures for our workforce.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.5013331742730485e-05, 'A': 3.478260362598796e-05, 'F': 1.2499478198713227e-05, 'B': 0.999890445347964, 'J': 7.2592384685474095e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010955465203599246}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 687:
  As a leading producer of vegetables and melons, our company operates extensive farms that grow a variety of crops, including tomatoes, cucumbers, and watermelons. We prioritize organic farming practices, employing natural pest control methods and composting to enrich soil health. Our state-of-the-art packing facilities ensure that our produce reaches consumers in peak freshness, while our logistics network allows for efficient distribution to grocery stores and farmers' markets. We also engage in community-supported agriculture (CSA) programs, fostering direct relationships with consumers and promoting local food systems.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.04474827981425557, 'A': 0.18207291370848352, 'F': 0.040442214361758794, 'B': 0.7273337181352219, 'J': 0.005402873980280241}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.27266628186477815}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 688:
  We operate a state-of-the-art hard coal mining facility that employs both surface and underground methods to extract coal efficiently. Our operations include advanced cleaning and sizing processes that ensure the coal produced meets stringent quality standards. By utilizing sophisticated technology for grading and pulverizing, we enhance the usability of our coal for various applications, including power generation and industrial use. Our focus on operational excellence and safety allows us to deliver a reliable supply of high-quality coal while minimizing our environmental footprint and supporting local communities.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.521691038532459e-05, 'A': 3.430172045718607e-05, 'F': 1.2362346429528542e-05, 'B': 0.9998909250425493, 'J': 7.1939801786137905e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957175785806, 6: 1.3345956945204553e-06, 7: 2.947825724888166e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997528272887312, 5.2: 0.0024717271126880936}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 689:
  As a prominent player in the hard coal mining sector, we focus on maximizing efficiency through a combination of surface and underground extraction methods. Our operations are designed to ensure the highest quality of coal, utilizing advanced cleaning and sizing technologies that prepare our products for various applications. We also employ innovative pulverizing techniques to enhance the coal's properties, making it easier to transport and store. Our commitment to sustainability drives us to continuously improve our processes, ensuring that we meet the energy demands of our clients while protecting the environment.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.488301546980248e-05, 'A': 3.445199686403131e-05, 'F': 1.2386977948231577e-05, 'B': 0.9998910874733399, 'J': 7.190536378140613e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957160047213, 6: 1.3253234697716313e-06, 7: 2.9586718088575327e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.997528996423852, 5.2: 0.0024710035761479877}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 691/788 [00:42<00:06, 13.96it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 690:
  As a prominent player in the iron ore mining sector, we focus on delivering high-quality iron ore through efficient extraction and processing methods. Our operations include extensive geological exploration to identify rich ore deposits, followed by the use of modern mining techniques to ensure optimal recovery rates. We also operate advanced beneficiation facilities that utilize technologies such as flotation and magnetic separation to produce iron concentrates tailored to the specifications of our steel industry clients. Our dedication to sustainable practices ensures that we minimize our environmental impact while maximizing value for our stakeholders.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.489505221078775e-05, 'A': 3.4353305868124754e-05, 'F': 1.233794374189889e-05, 'B': 0.9998912730526754, 'J': 7.140645503671998e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4672751473321706e-06, 6: 1.5887740340192704e-06, 7: 0.9999959439508187}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678021175698611, 7.2: 0.032197882430139}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 691:
  Our company is focused on the mining of rare earth elements, which are essential for high-tech applications in electronics, renewable energy, and defense industries. We utilize specialized extraction techniques to separate these valuable minerals from ore, ensuring high purity levels for our clients. Our processing facilities are designed to handle complex ores, employing advanced separation technologies to maximize yield. We also engage in extensive research and development to improve the efficiency of our extraction processes and reduce environmental impacts, positioning ourselves as a key player in the sustainable sourcing of critical materials.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5561065980232256e-05, 'A': 3.4123403439359196e-05, 'F': 1.2340736037077228e-05, 'B': 0.9998908291366992, 'J': 7.145657844074868e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4614619200098794e-06, 6: 1.5937789424671784e-06, 7: 0.9999959447591376}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03507656235617862, 7.2: 0.9649234376438214}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 695/788 [00:42<00:06, 13.69it/s]

RAPS scores:

==================================================
Description 692:
  Our company is involved in the growing of various root and tuber crops, including potatoes and sweet potatoes, which are staples in many diets. We implement advanced soil management techniques and crop rotation to enhance soil fertility and crop resilience. Our focus on sustainable practices not only improves yield but also supports biodiversity in our farming ecosystems. We partner with local food banks to donate surplus produce, reinforcing our commitment to community support and food security. By prioritizing quality and sustainability, we aim to become a trusted source for nutritious root vegetables.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.061062633625614565, 'A': 0.06034668366551147, 'F': 0.0490534395209728, 'B': 0.8253171083321467, 'J': 0.004220134855754506}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.17468289166785333}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 693:
  We focus on the conservation and restoration of forest ecosystems through targeted silvicultural practices. Our team conducts comprehensive assessments of forest health, identifying areas in need of intervention. By implementing tree thinning and selective logging, we enhance the growth potential of remaining trees and promote biodiversity. Our services extend to replanting initiatives aimed at restoring degraded areas, ensuring that future generations can benefit from robust and thriving forests.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 4.947160717725632e-05, 'A': 0.999028408645794, 'F': 0.000726759366916187, 'B': 0.00013507849160229079, 'J': 6.028188851050493e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009715913542059917}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 694:
  Specializing in the mining of bauxite, our company plays a crucial role in the aluminum supply chain. We employ environmentally responsible mining practices, including land reclamation and habitat restoration, to mitigate the impact of our operations. Our processing plants utilize cutting-edge technology to refine bauxite into alumina, which is then supplied to aluminum producers worldwide. We are committed to transparency and ethical sourcing, ensuring that our operations align with global sustainability standards. By investing in community development and education programs, we aim to create lasting positive impacts in the regions where we operate, fostering a collaborative approach to resource management.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.4879518363146245e-05, 'A': 3.443358792204128e-05, 'F': 1.2371693009252737e-05, 'B': 0.999891143119263, 'J': 7.172081442619893e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 3.6827127692142222e-06, 6: 1.6268178899924427e-06, 7: 0.9999946904693409}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03514052134318024, 7.2: 0.9648594786568196}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 697/788 [00:43<00:06, 13.65it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 695:
  We specialize in the extraction and beneficiation of iron ores, focusing on delivering high-quality products to the steel industry. Our mining operations are characterized by the use of advanced equipment and methodologies that ensure efficient ore recovery. The beneficiation process involves a series of steps, including crushing, milling, and magnetic separation, which enhance the iron content of the ore. By maintaining strong relationships with our customers, we are able to tailor our products to meet their specific requirements, thereby creating value and fostering long-term partnerships.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5628682051201125e-05, 'A': 3.395098822746643e-05, 'F': 1.2287340205168129e-05, 'B': 0.9998910038181139, 'J': 7.129171402076532e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4796882163143667e-06, 6: 1.5784590295227916e-06, 7: 0.9999959418527542}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677992348363725, 7.2: 0.03220076516362746}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 696:
  Our organization is committed to the cultivation of non-perennial crops, particularly focusing on seed production for various vegetables and grains. We utilize cutting-edge biotechnology to develop hybrid seeds that offer improved yield and pest resistance. Our facilities are designed for efficient seed processing and packaging, ensuring that we meet the demands of farmers and agricultural businesses. By fostering partnerships with agricultural research institutions, we stay at the forefront of innovation, contributing to the advancement of sustainable farming practices and food production.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.13689763806208421, 'A': 0.14600097363461045, 'F': 0.11480180957260175, 'B': 0.5921472306840315, 'J': 0.010152348046671991}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4078527693159685}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 697:
  Engaged in the production of charcoal using traditional methods, we focus on small-scale operations that promote local craftsmanship and environmental stewardship. Our charcoal is made from sustainably harvested wood, ensuring that our practices support forest conservation. We emphasize the importance of traditional techniques that enhance the flavor and quality of the charcoal, appealing to both local consumers and gourmet markets. Through community engagement and education, we strive to raise awareness about the benefits of sustainable charcoal production.1. Our company specializes in the sustainable harvesting of roundwood, focusing on high-quality logs for the construction and manufacturing sectors. We employ advanced logging techniques that minimize environmental impact while maximizing yield. Our operations include selective logging practices that ensure the health of forest ecosystems. Additionally, we process some of our harvested timber into firewood, catering to both residential and commercial markets. Our commitment to sustainability extends to our reforestation initiatives, where we plant multiple trees for every one harvested, ensuring a balanced approach to resource management.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.002150600949737108, 'A': 0.0007818269552801211, 'F': 0.0002612206916321193, 'B': 0.9966853010295137, 'J': 0.00012105037383712222}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0033146989704863072}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 702/788 [00:43<00:05, 15.79it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 698:
  In the realm of lignite mining, our company is at the forefront of employing sustainable practices to extract and process brown coal. We utilize both surface and underground mining techniques, ensuring that our operations are adaptable to various geological conditions. Our post-extraction processes include washing and compressing the lignite to improve its quality, making it suitable for energy generation. Additionally, we have established efficient warehousing facilities that allow for the safe storage of our product, ensuring a steady supply for our customers. Our focus on innovation and sustainability positions us as a leader in the industry, dedicated to meeting the needs of our clients while protecting the environment.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4818859186453594e-05, 'A': 3.44899470325152e-05, 'F': 1.2392298373254028e-05, 'B': 0.999891120991066, 'J': 7.177904341595162e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957423831004, 6: 1.3412209745468659e-06, 7: 2.916395925003818e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002356390801906687, 5.2: 0.9976436091980933}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 699:
  Engaged in the cultivation of legumes, our company is committed to producing high-nutrient crops such as lentils and chickpeas. We prioritize sustainable agricultural methods, including nitrogen-fixing crop rotations that enhance soil fertility and reduce the need for chemical fertilizers. Our research team works on developing improved seed varieties that are resilient to climate fluctuations, ensuring consistent yields. By partnering with local farmers, we provide education and resources to help them adopt these sustainable practices, ultimately contributing to food security and economic stability in the regions we operate.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.05572952736638727, 'A': 0.09438757077219448, 'F': 0.043485051309833954, 'B': 0.8014964920041309, 'J': 0.004901358547453399}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.19850350799586913}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 700:
  Our company focuses on the cultivation of melons and root vegetables, employing regenerative farming techniques that enhance soil health and biodiversity. We prioritize organic practices, avoiding synthetic fertilizers and pesticides, which allows us to produce clean, nutritious food for our customers. Our melons are sold fresh to local grocery stores and through community-supported agriculture (CSA) programs, while our root vegetables are processed for both fresh and frozen markets. We also engage in educational outreach, teaching consumers about the benefits of local and seasonal eating, further connecting them to our farming practices.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.07293738883320143, 'A': 0.017578143851518083, 'F': 0.015000724073129343, 'B': 0.8918594531160536, 'J': 0.0026242901260975864}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10814054688394636}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 701:
  Our company is engaged in the mining of iron ores, utilizing advanced technologies to extract and process these valuable resources. We focus on the beneficiation of iron ores, employing techniques such as crushing, grinding, and magnetic separation to enhance the quality of our products. Our agglomeration processes convert fine iron ore into pellets, making them more efficient for transportation and use in steel production. By prioritizing sustainability and innovation, we strive to deliver high-quality iron ore while minimizing our environmental impact.
True: section=B, division=7, class=7.1
Section set: []
Section probs: {'C': 5.579945993610554e-05, 'A': 3.4060445730229984e-05, 'F': 1.2314217604355888e-05, 'B': 0.9998906760652553, 'J': 7.149811474107457e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010932393474472057}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 704/788 [00:43<00:05, 14.59it/s]

RAPS scores:

==================================================
Description 702:
  Our business is centered on the operation of forest tree nurseries, where we cultivate a diverse range of native and commercially valuable tree species. We prioritize sustainable growing practices, ensuring that our seedlings are robust and well-suited for reforestation and timber production. By collaborating with environmental organizations, we contribute to habitat restoration projects that enhance local ecosystems. Our commitment to quality and sustainability not only supports the timber industry but also fosters a healthier environment for wildlife and future generations.1. Our company specializes in sustainable forestry practices, focusing on the growth and management of timber resources. We engage in activities such as planting and replanting native tree species to enhance biodiversity while ensuring the health of our forests. Our operations include thinning mature stands to promote growth and improve timber quality. Additionally, we manage tree nurseries that supply high-quality seedlings for reforestation projects. By implementing innovative silvicultural techniques, we not only contribute to environmental conservation but also provide a steady supply of timber for various industries, ensuring a balance between economic growth and ecological sustainability.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00010604684887758894, 'A': 0.9985370380858335, 'F': 0.0007590207676787221, 'B': 0.0004982570152007834, 'J': 9.96372824093422e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0014629619141665051}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 703:
  Our business model revolves around the mining and processing of hard coal, where we utilize cutting-edge technologies to enhance extraction efficiency. We focus on the cleaning and grading of coal to ensure that our products meet the diverse needs of our clients in energy and manufacturing sectors. Our commitment to innovation extends to our logistics operations, which are designed to streamline the transportation of coal from our mines to end-users. By fostering strong partnerships and maintaining high operational standards, we strive to deliver exceptional value to our customers while promoting sustainable practices.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.5067478345308506e-05, 'A': 3.4300617900291236e-05, 'F': 1.2359616485454907e-05, 'B': 0.9998910873221085, 'J': 7.184965160331731e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957227036591, 6: 1.3229229301707066e-06, 7: 2.9543734106899646e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975297784990034, 5.2: 0.002470221500996642}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 704:
  We specialize in the conservation and management of forest ecosystems, focusing on maintaining biodiversity and enhancing carbon sequestration. Our initiatives include the restoration of degraded forest areas and the establishment of protected zones to safeguard endangered species. By promoting healthy forest dynamics, we contribute to climate change mitigation while providing resources for timber production. Our holistic approach to forestry management balances economic objectives with ecological integrity, ensuring a sustainable future for our forests.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00012806906634225642, 'A': 0.9951130278854007, 'F': 0.004268573414395933, 'B': 0.00033820320157978946, 'J': 0.0001521264322813557}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0048869721145993195}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 705:
  We are dedicated to the cultivation of spices and aromatic crops, such as saffron and basil, which are grown using organic methods to ensure purity and flavor. Our farms utilize innovative drying and packaging techniques that maintain the integrity of the spices from harvest to shelf. We collaborate with chefs and food enthusiasts to develop unique spice blends and cooking classes, creating a community around culinary exploration. Our commitment to quality and sustainability has positioned us as a trusted source for premium spices in both local and international markets.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.13387720535090553, 'A': 0.033236173958394157, 'F': 0.04126958019121652, 'B': 0.7866878026482315, 'J': 0.004929237851252267}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.21331219735176854}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 707/788 [00:43<00:05, 14.99it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 706:
  As a key player in the hard coal mining sector, we focus on both surface and underground operations to optimize resource extraction. Our surface mining operations utilize heavy machinery for efficient overburden removal, allowing us to access high-quality coal seams. Once extracted, the coal undergoes a meticulous grading and pulverizing process in our state-of-the-art facilities, where we ensure that the final product meets diverse customer specifications. We also prioritize safety and environmental stewardship, integrating best practices in waste management and land reclamation into our mining operations to support sustainable development in the regions we operate.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.487246141215293e-05, 'A': 3.4413862770449014e-05, 'F': 1.2363198364500392e-05, 'B': 0.9998911717854846, 'J': 7.178691968488934e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957254330527, 6: 1.3325042757602596e-06, 7: 2.9420626716505945e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975267581253141, 5.2: 0.002473241874686015}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 707:
  Our company is at the forefront of the iron ore mining industry, where we extract and process iron-rich ores through innovative techniques. We utilize advanced beneficiation methods to separate valuable iron from impurities, producing high-grade iron concentrates. Our state-of-the-art facilities are equipped with the latest technology to ensure efficiency and environmental compliance. We are dedicated to maintaining strong relationships with our clients by providing consistent quality and reliable supply of iron ore products.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.533479011038629e-05, 'A': 3.423436307045901e-05, 'F': 1.2317873985177584e-05, 'B': 0.9998909627672299, 'J': 7.150205604074344e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.46029374066871e-06, 6: 1.6038230901255675e-06, 7: 0.9999959358831693}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677606542820957, 7.2: 0.032239345717904364}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 709/788 [00:43<00:05, 14.77it/s]

RAPS scores:

==================================================
Description 708:
  Our business model centers around the extraction and processing of natural gas, where we employ advanced technologies to enhance operational efficiency. We specialize in the draining and separation of liquid hydrocarbon fractions, which allows us to produce a range of high-demand products. Our gas desulphurization processes are designed to meet rigorous environmental standards, ensuring that our natural gas is not only efficient but also clean. Through continuous innovation, we aim to provide reliable energy solutions while supporting a sustainable future.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.586891572483988e-05, 'A': 3.4124082178828894e-05, 'F': 1.2366644577440461e-05, 'B': 0.9998904541325827, 'J': 7.1862249363566845e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010954586741729333}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 709:
  We are involved in the mining and processing of iron ores, utilizing a blend of traditional and innovative techniques to ensure high-quality output. Our operations include comprehensive exploration to identify rich ore deposits, followed by efficient extraction methods that prioritize safety and sustainability. The ore undergoes rigorous beneficiation processes, including crushing, grinding, and magnetic separation, to produce iron concentrates that meet the stringent requirements of our customers. Our commitment to reducing our carbon footprint and engaging with local communities underscores our dedication to responsible mining practices and long-term industry leadership.1. Our company specializes in the extraction and processing of high-grade iron ores from our strategically located mines. We utilize advanced drilling and blasting techniques to ensure efficient ore recovery while minimizing environmental impact. Our beneficiation process employs state-of-the-art technologies, including magnetic separation and flotation, to enhance the iron content of the ore before it is shipped to steel manufacturers. Additionally, we have invested in sustainable practices, such as water recycling and waste management systems, to reduce our carbon footprint and support local ecosystems.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.542138589961662e-05, 'A': 3.417546880303304e-05, 'F': 1.2333718611876197e-05, 'B': 0.9998908950091303, 'J': 7.174417555197228e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4561876069162436e-06, 6: 1.602407384129129e-06, 7: 0.9999959414050089}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677834794117137, 7.2: 0.032216520588286425}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 711/788 [00:44<00:06, 11.30it/s]

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 710:
  The company is involved in the cultivation of various non-perennial crops, including specialty herbs and spices, which are grown using innovative agricultural techniques. By focusing on niche markets, the company has established a strong presence in the gourmet food sector, supplying restaurants and specialty retailers with fresh, high-quality produce. The use of vertical farming technology allows for year-round production, minimizing land use while maximizing output. The company also emphasizes sustainable practices, ensuring that its growing methods align with environmental stewardship and consumer demand for organic products.
True: section=A, division=1, class=1.1
Section set: ['A']
Section probs: {'C': 1.0318045801735243e-05, 'A': 0.999910441107356, 'F': 3.915148676017201e-05, 'B': 2.7399834972326574e-05, 'J': 1.2689525109821396e-05}
Division sets: {'A': ['1']}
Division probs: {'A': {1: 0.9982199869451499, 2: 0.0010370400222636622, 3: 0.0007429730325862715}}
Class sets: {'1': ['1.1']}
Class probs: {'1': {1.2: 0.006194920224864068, 1.4: 0.005830489999007857, 1.3: 0.003034682208066733, 1.1: 0.9849399075680614}}
Final output: {'type': 'class_level', 'codes': ['1.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 711:
  Our aquaculture enterprise is dedicated to the farming of aquatic plants, such as seaweed and watercress, in both coastal and freshwater environments. Utilizing sustainable harvesting methods, we focus on the nutritional and ecological benefits of these plants, promoting their use in health foods and biofuels. Our production facilities are equipped with advanced cultivation systems that optimize growth conditions while minimizing environmental impact. We collaborate with food manufacturers and health product companies to develop innovative products that highlight the benefits of aquatic plants, tapping into the growing market for superfoods.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0005405409477696165, 'A': 0.9919035897756114, 'F': 0.0013018858546348865, 'B': 0.0059037381110536215, 'J': 0.0003502453109304624}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.008096410224388562}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 712:
  We are dedicated to the raising of swine, utilizing state-of-the-art facilities designed for optimal animal health and growth efficiency. Our operations include a comprehensive feed management system that ensures our pigs receive a balanced diet tailored to their growth stages. We focus on producing high-quality pork products, which are processed and packaged in our on-site facility. By establishing direct relationships with local grocery stores and restaurants, we ensure our products reach consumers fresh and with a commitment to ethical farming practices.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.00521331842331244, 'A': 0.8917710184526212, 'F': 0.03210916379765859, 'B': 0.06870387543493374, 'J': 0.0022026238914740434}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.10822898154737881}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 714/788 [00:44<00:05, 12.78it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 713:
  Specializing in the extraction of natural gas, our company is at the forefront of adopting new technologies that improve efficiency and safety. We utilize advanced drilling techniques to access challenging reserves, while our processing facilities are equipped with state-of-the-art systems for liquid hydrocarbon separation. Our focus on gas desulphurization not only enhances product quality but also aligns with our commitment to environmental responsibility. By fostering innovation and sustainability, we aim to meet the evolving energy needs of our customers.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.495148030955847e-05, 'A': 3.457107514636805e-05, 'F': 1.2438243515171459e-05, 'B': 0.9998908495114903, 'J': 7.189689538520497e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7613055998092924e-06, 6: 0.9999964314226516, 7: 1.8072717486402161e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979732204837417, 6.1: 0.0020267795162582903}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 714:
  Our business model revolves around the extraction of natural gas and the production of associated liquid hydrocarbons. We employ advanced geophysical techniques to identify optimal drilling locations, ensuring maximum recovery rates. Our facilities are equipped with sophisticated gas processing units that facilitate the separation of valuable condensates from raw natural gas. Through our commitment to innovation, we have developed proprietary technologies that enhance the efficiency of gas desulphurization, allowing us to produce cleaner energy while adhering to regulatory requirements. This focus on technology and sustainability positions us as a leader in the natural gas sector.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.486639850975054e-05, 'A': 3.447823328470828e-05, 'F': 1.2401498591325221e-05, 'B': 0.9998910626905015, 'J': 7.191179112693225e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7719660848635329e-06, 6: 0.9999964176053436, 7: 1.8104285715554838e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.997970797700119, 6.1: 0.0020292022998810184}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 719/788 [00:44<00:04, 14.45it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 715:
  Our operations focus on the mining and processing of tin and tungsten ores, essential for various industrial applications. We employ state-of-the-art separation technologies that maximize recovery rates while minimizing environmental impact. Our commitment to sustainability includes the implementation of responsible mining practices and community engagement initiatives that foster economic development in local areas. We also invest in research to explore the potential of recycling these metals from electronic waste, contributing to a circular economy and reducing the demand for virgin materials.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.508642817699947e-05, 'A': 3.422030361649804e-05, 'F': 1.2320746869602573e-05, 'B': 0.9998912295110323, 'J': 7.143010304706123e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.482332892149248e-06, 6: 1.577996203176119e-06, 7: 0.9999959396709046}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0351308463893971, 7.2: 0.964869153610603}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 716:
  We are dedicated to the cultivation of tropical and subtropical fruits, including mangoes, pineapples, and avocados, leveraging innovative agricultural techniques to maximize yield and flavor. Our farms utilize integrated pest management systems to minimize chemical usage and enhance sustainability. We focus on exporting our fresh produce to international markets, ensuring that our fruits meet stringent quality standards. Additionally, we invest in research to develop new varieties that are resilient to climate change, allowing us to adapt to shifting agricultural conditions while meeting consumer demand for high-quality tropical fruits.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.5747369026978036, 'A': 0.008022037508192243, 'F': 0.021000166245235565, 'B': 0.3916485302446488, 'J': 0.00459236330411967}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.42526309730219636}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 717:
  Our operations center around the cultivation of root and tuber crops, including potatoes and sweet potatoes, which are staples in many diets worldwide. We utilize precision farming techniques to monitor soil conditions and crop health, allowing us to optimize our yield and minimize waste. Our commitment to sustainability is reflected in our water management practices and the use of organic fertilizers. We also engage in community outreach programs to educate local farmers on best practices, fostering a collaborative approach to agriculture that enhances food security and promotes sustainable farming methods.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.016439714483561258, 'A': 0.017243904278384386, 'F': 0.005980578199477043, 'B': 0.9591300305232648, 'J': 0.001205772515312312}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.04086996947673516}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 718:
  As a producer of charcoal using traditional methods, our company emphasizes artisanal craftsmanship while adhering to sustainable practices. We harvest hardwood from carefully managed forests, ensuring that our charcoal is of the highest quality and free from harmful additives. Our production process involves slow carbonization, which enhances the flavor and aroma of the charcoal, making it ideal for grilling and barbecuing. We engage with local communities to promote our products, educating consumers about the benefits of using sustainably sourced charcoal, and fostering a deeper appreciation for traditional cooking methods.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9991387795797712, 'A': 4.139159636504116e-05, 'F': 4.767247719856089e-05, 'B': 0.0005844803168843759, 'J': 0.0001876760297810268}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008612204202288476}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 719:
  We specialize in the cultivation of melons and root vegetables, employing advanced agronomic techniques to maximize yield and flavor. Our farms utilize integrated pest management and organic fertilizers to ensure the health of our crops while minimizing environmental impact. The produce is marketed directly to consumers through subscription services and local grocery stores, emphasizing freshness and quality. Our commitment to sustainable practices is reflected in our packaging, which is designed to reduce waste and promote recyclability.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9494483967766889, 'A': 0.0012096706290938134, 'F': 0.0029900882626924634, 'B': 0.0446542748004021, 'J': 0.0016975695311227156}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05055160322331109}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 721/788 [00:44<00:04, 14.34it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 720:
  Focused on the mining of thorium ores, our operations leverage innovative extraction methods that enhance ore purity and output. We employ a skilled workforce trained in the latest mining technologies, ensuring that our practices meet the highest safety and environmental standards. Our thorium products are essential for various applications, including potential use in advanced nuclear reactors. We also engage in partnerships with research institutions to explore the benefits of thorium as a sustainable energy source, positioning our company as a leader in the transition to cleaner energy alternatives.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.496585137990222e-05, 'A': 3.4295963071292355e-05, 'F': 1.2331517990881753e-05, 'B': 0.9998912698277691, 'J': 7.136839788885978e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.452802822936549e-06, 6: 1.6072406322195171e-06, 7: 0.9999959399565449}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03521462337617896, 7.2: 0.964785376623821}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 721:
  We are a leader in the mining of non-ferrous metal ores, specializing in the extraction of tin and tungsten. Our operations are centered on utilizing innovative mining techniques that enhance ore recovery and reduce environmental impact. We prioritize safety and sustainability, implementing best practices in waste management and resource conservation. Our refined metals are essential for various applications, including electronics and manufacturing. Through ongoing research and development, we aim to improve our processes and expand our product offerings, ensuring we meet the evolving needs of our customers while contributing to a sustainable future.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.548136572823142e-05, 'A': 3.42020934720196e-05, 'F': 1.2336000229320223e-05, 'B': 0.9998908553175988, 'J': 7.125222971456043e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4662506419102364e-06, 6: 1.5884733027516709e-06, 7: 0.9999959452760554}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03515199801827225, 7.2: 0.9648480019817277}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 726/788 [00:45<00:03, 15.99it/s]

RAPS scores:

==================================================
Description 722:
  We are dedicated to the sustainable production of wood for energy, focusing on the transformation of forest residues into biomass fuel. Our operations involve collecting leftover materials from logging activities and processing them into high-efficiency pellets. These pellets are marketed to both residential and industrial clients seeking renewable energy solutions. By converting waste into valuable energy products, we contribute to a more sustainable energy landscape while promoting responsible forest management practices.1. Our company specializes in the sustainable harvesting of roundwood, focusing on high-quality logs that are supplied to various manufacturing industries. We employ advanced logging techniques that minimize environmental impact while maximizing yield. Additionally, we process forest residues to produce biomass energy, contributing to renewable energy solutions. Our commitment to sustainable practices ensures that we maintain healthy forest ecosystems while providing essential materials for construction and energy production.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9981981525154373, 'A': 7.257941140322145e-05, 'F': 8.68557441426578e-05, 'B': 0.0013936728027684998, 'J': 0.000248739526248265}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0018018474845626908}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 723:
  Our aquaculture business focuses on the production of high-quality fish feed tailored for various species, including both marine and freshwater organisms. We utilize sustainable ingredients, including plant-based proteins and by-products from the food industry, to create nutritionally balanced feed formulations. Our research and development team works closely with aquaculture producers to customize feed solutions that optimize growth and health in their stock. By prioritizing sustainability and innovation, we aim to support the aquaculture industry in meeting global seafood demands while minimizing environmental impact.1. The company specializes in marine aquaculture, focusing on the sustainable farming of various fish species such as salmon and sea bass. Utilizing advanced recirculating aquaculture systems, they ensure optimal growth conditions while minimizing environmental impact. The firm employs a rigorous feeding regimen and health monitoring protocols to enhance yield and quality. Their operations not only include the cultivation of juvenile fish but also extend to processing and packaging, allowing for a seamless supply chain that delivers fresh seafood directly to retail partners. This integrated approach helps meet the growing consumer demand for responsibly sourced seafood.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 3.220233164117057e-05, 'A': 0.9997354590735091, 'F': 8.710686200814323e-05, 'B': 0.00011303169673128097, 'J': 3.220003611038053e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002645409264908638}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 724:
  Our operations encompass the full spectrum of forestry activities, from establishing tree nurseries to managing timber resources. We prioritize the cultivation of high-quality seedlings that are well-suited for local environments, ensuring successful reforestation efforts. Our team works closely with environmental organizations to implement best practices in forest management, focusing on biodiversity and ecosystem health. By fostering a culture of sustainability, we aim to create lasting value for both our stakeholders and the communities we serve, reinforcing our commitment to responsible forestry.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.309130431194536e-05, 'A': 0.9995933931370318, 'F': 0.0002093957334252331, 'B': 0.0001274152184294875, 'J': 3.670460680145187e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00040660686296822846}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 725:
  Our business model revolves around the sustainable extraction and processing of lignite, with a strong emphasis on environmental responsibility. We utilize modern mining techniques that minimize land disruption and promote biodiversity. The lignite we extract undergoes rigorous processing, including washing and pulverizing, to ensure it meets the quality standards required by our customers. We also invest in research and development to explore innovative methods for lignite utilization, aiming to enhance its value in energy production and other applications. Our commitment to sustainability drives our operational decisions and shapes our future growth strategies.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 5.473896340395189e-05, 'A': 3.496043079835591e-05, 'F': 1.2516146269336243e-05, 'B': 0.99989053689175, 'J': 7.2475677785400314e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010946310824999639}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 726:
  We specialize in the farming of alligators, utilizing controlled environments that mimic their natural habitat. Our operations involve breeding alligators for both meat and leather production, ensuring that we adhere to strict animal welfare standards. Our facilities are designed to provide optimal conditions for growth, including temperature regulation and proper nutrition. We also engage in educational programs to raise awareness about alligator conservation and the importance of sustainable farming practices. By offering high-quality alligator products to gourmet restaurants and specialty retailers, we contribute to a niche market that values ethically sourced exotic meats.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.018054699498992563, 'A': 0.45958870526591, 'F': 0.030684370410683535, 'B': 0.4875392734033133, 'J': 0.004132951421100548}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5124607265966867}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 728/788 [00:45<00:03, 15.33it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 727:
  Our company is at the forefront of the hard coal mining industry, utilizing innovative extraction techniques and advanced processing technologies. We focus on cleaning and sizing coal to ensure that our products meet the highest quality standards demanded by our customers. By optimizing our operations and investing in sustainable practices, we are able to deliver reliable coal solutions that support energy generation and industrial processes. Our commitment to safety and environmental responsibility is integral to our business model, ensuring that we operate in harmony with the communities we serve.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.520894514998035e-05, 'A': 3.443764779840133e-05, 'F': 1.2389815588547127e-05, 'B': 0.9998907851333237, 'J': 7.178458139310079e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957268149059, 6: 1.3522953600740786e-06, 7: 2.9208897340095025e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975274538782432, 5.2: 0.0024725461217569235}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 728:
  At the forefront of natural gas production, our company integrates advanced technologies in the extraction and processing of gaseous hydrocarbons. We utilize automated systems for monitoring and controlling drilling operations, which enhances safety and efficiency. Our facilities are equipped with cutting-edge gas desulphurization units that ensure the removal of impurities, resulting in high-quality natural gas products. We also focus on the development of new extraction techniques that not only increase yield but also reduce the environmental footprint of our operations.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.4934636669596614e-05, 'A': 3.455298101624137e-05, 'F': 1.2419456902901197e-05, 'B': 0.9998908904108408, 'J': 7.202514570565013e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.757904140398994e-06, 6: 0.9999964472801344, 7: 1.7948157252599143e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979532404669268, 6.1: 0.002046759533073165}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 730/788 [00:45<00:04, 14.25it/s]

RAPS scores:

==================================================
Description 729:
  In the natural gas industry, our firm is committed to the extraction and processing of crude gaseous hydrocarbons. We employ advanced drilling techniques and innovative technologies to maximize our production capabilities. Our operations include the extraction of condensates, which are processed in our modern facilities to create high-value energy products. Additionally, our gas desulphurisation processes are designed to ensure compliance with environmental regulations, allowing us to deliver cleaner energy solutions to our clients while contributing to a sustainable future.1. Our company specializes in the extraction and production of natural gas, utilizing advanced drilling techniques and state-of-the-art technology to maximize yield while minimizing environmental impact. We operate several offshore and onshore facilities, where we employ innovative methods for gas extraction and processing. Our operations include the separation of liquid hydrocarbon fractions, ensuring that we capture valuable by-products such as condensates. By investing in cutting-edge desulphurization technologies, we enhance the quality of the gas we deliver to our customers, contributing to cleaner energy solutions and supporting the transition to a more sustainable energy future.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.553238568142683e-05, 'A': 3.437089533025401e-05, 'F': 1.24226111213243e-05, 'B': 0.9998904395319954, 'J': 7.234575871390081e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010956046800458807}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 730:
  As a leader in lignite mining, we focus on innovative extraction methods that reduce operational costs and enhance safety. Our surface mining operations are equipped with cutting-edge machinery that allows for the efficient removal of overburden, ensuring minimal disruption to the surrounding environment. We also prioritize the development of our workforce through ongoing training programs, ensuring that our employees are skilled in the latest mining technologies. By investing in research and development, we continually seek ways to improve our lignite quality, enabling us to provide superior products to our customers.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.488668424486601e-05, 'A': 3.442419030972515e-05, 'F': 1.2368505254667542e-05, 'B': 0.9998911752120105, 'J': 7.145408180318526e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957353832283, 6: 1.3556416313366637e-06, 7: 2.908975140463089e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023550365016765705, 5.2: 0.9976449634983235}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 734/788 [00:45<00:04, 12.49it/s]

RAPS scores:

==================================================
Description 731:
  Engaged in the mining of various non-ferrous metal ores, our operations focus on extracting valuable minerals such as copper, nickel, and zinc. We employ innovative methods such as hydrometallurgy to optimize the recovery of these metals from ore, ensuring that we maximize yield while minimizing environmental footprints. Our processing facilities are equipped with cutting-edge technology that allows us to refine these ores into high-purity metals, which are then supplied to industries ranging from electronics to construction. Through strategic partnerships, we also explore new markets to enhance our product offerings and expand our global reach.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5540152357296145e-05, 'A': 3.415254097222728e-05, 'F': 1.2334223395862572e-05, 'B': 0.9998908133377593, 'J': 7.159745515222466e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.45972073447026e-06, 6: 1.5981090564126965e-06, 7: 0.999995942170209}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.0350989865043233, 7.2: 0.9649010134956767}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 732:
  Our company is engaged in the comprehensive mining of hard coal, employing both surface and underground methods to access valuable resources. We have invested heavily in modernizing our processing plants, which feature cutting-edge technology for cleaning, sizing, and pulverizing coal. This allows us to produce a variety of coal grades tailored to meet the demands of different industries. Additionally, we prioritize environmental sustainability, implementing practices that minimize our ecological footprint and promote the responsible use of natural resources.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.527078269118994e-05, 'A': 3.416282369911433e-05, 'F': 1.2322645798089558e-05, 'B': 0.9998910852924442, 'J': 7.158455367435167e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957127041551, 6: 1.325411311231506e-06, 7: 2.9618845335269016e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975280818290009, 5.2: 0.002471918170999167}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 733:
  We focus on the cultivation of oleaginous fruits, particularly avocados and olives, which are prized for their healthy fats and culinary versatility. Our farms utilize drip irrigation and organic farming techniques to ensure sustainable production while enhancing fruit quality. We process our olives into high-quality olive oil, which is marketed under our brand, emphasizing its cold-pressed and organic attributes. Our avocados are sold fresh to both domestic and international markets, catering to the growing trend of healthy eating. This dual product strategy allows us to diversify our revenue streams effectively.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.6726635164576756, 'A': 0.0032793791337207825, 'F': 0.006901865661268815, 'B': 0.31455049697360243, 'J': 0.0026047417737324803}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.32733648354232436}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 734:
  We are engaged in the mining and processing of molybdenum ores, which are vital for steel production and various industrial applications. Our operations employ state-of-the-art extraction techniques that prioritize efficiency and safety, while our processing facilities utilize advanced technologies to produce high-quality molybdenum products. We are committed to sustainability, implementing practices that minimize waste and reduce energy consumption. Additionally, we collaborate with industry partners to research new applications for molybdenum, driving innovation and expanding market opportunities while ensuring that our operations are environmentally responsible.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.623506633907124e-05, 'A': 3.38359811279994e-05, 'F': 1.2292831101043931e-05, 'B': 0.9998905050445381, 'J': 7.13107689377767e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010949495546186405}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 736/788 [00:45<00:04, 12.79it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 735:
  We are engaged in the extraction and processing of natural gas, leveraging cutting-edge technologies to enhance our operational efficiency. Our extraction processes are complemented by sophisticated separation systems that allow us to recover valuable liquid hydrocarbons from raw gas streams. This not only increases our product offerings but also contributes to the overall value chain within the energy sector. Furthermore, we have implemented robust gas desulfurization methods to reduce sulfur content, ensuring that our products are compliant with regulatory standards and appealing to environmentally conscious consumers.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.520966071044678e-05, 'A': 3.418924507835852e-05, 'F': 1.2336509253866e-05, 'B': 0.9998911097808397, 'J': 7.154804117509913e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7825126043228304e-06, 6: 0.9999964110695004, 7: 1.8064178952675262e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979701651104166, 6.1: 0.0020298348895833283}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 736:
  We specialize in the raising of camels and camelids, capitalizing on their unique adaptability to arid environments. Our farm employs traditional and modern breeding techniques to enhance the quality of our herd, focusing on traits such as endurance and temperament. We provide camel milk, which is gaining popularity for its nutritional benefits, and we process it into various products, including cheese and yogurt. Our commitment to sustainable practices includes utilizing renewable resources for water and feed, ensuring minimal environmental impact. We also engage in cultural exchange programs that educate the public about the significance of camels in our heritage.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.004796104051582445, 'A': 0.9087348845744787, 'F': 0.042068648308698525, 'B': 0.042229462891976516, 'J': 0.0021709001732637735}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.09126511542552129}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 737:
  We are dedicated to the collection and distribution of wild berries, focusing on organic and sustainable practices. Our team works closely with local farmers and foragers to ensure that we gather only the ripest, most flavorful berries, including blueberries, blackberries, and raspberries. These berries are then processed into jams, jellies, and frozen products, which are marketed to health-conscious consumers seeking natural and locally sourced ingredients. Our commitment to quality and sustainability not only supports local economies but also promotes biodiversity in berry-growing regions.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.0005326332158658127, 'A': 0.9927030167399629, 'F': 0.002315004531654051, 'B': 0.004082748716832672, 'J': 0.0003665967956846883}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.007296983260037138}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 741/788 [00:46<00:03, 13.73it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 738:
  Our company is dedicated to the sustainable mining of iron ores, utilizing advanced technologies to maximize efficiency and minimize environmental impact. We employ a range of extraction techniques tailored to the geological characteristics of our sites. Our beneficiation process enhances the iron content of the ore through state-of-the-art separation technologies. We also produce iron pellets through agglomeration, which are crucial for optimizing the steel production process. Our commitment to safety, quality, and environmental stewardship drives our operations and underpins our long-term success in the industry.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.5280948281396365e-05, 'A': 3.412104364636967e-05, 'F': 1.2302201028130208e-05, 'B': 0.9998911710455763, 'J': 7.124761467828522e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.491497749397867e-06, 6: 1.5697125083448811e-06, 7: 0.9999959387897421}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9678055423489982, 7.2: 0.03219445765100181}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 739:
  A leader in freshwater aquaculture, this company cultivates tilapia and catfish in controlled environments that mimic natural habitats. By implementing innovative water filtration technologies, they maintain high water quality and reduce disease risks. The firm also focuses on breeding programs to enhance fish growth rates and disease resistance. Their commitment to sustainability is evident in their use of plant-based feeds, which reduce reliance on wild fish stocks. Additionally, they provide educational resources to local farmers, promoting best practices in aquaculture and contributing to community development.
True: section=A, division=3, class=3.2
Section set: ['A']
Section probs: {'C': 1.051021378636718e-05, 'A': 0.9999056960769834, 'F': 4.267261404228985e-05, 'B': 2.8144644194511777e-05, 'J': 1.2976450993250434e-05}
Division sets: {'A': ['3']}
Division probs: {'A': {1: 0.0007151966469118315, 2: 0.0009434951479271117, 3: 0.9983413082051611}}
Class sets: {'3': ['3.2']}
Class probs: {'3': {3.1: 0.16031451304623753, 3.2: 0.8396854869537625}}
Final output: {'type': 'class_level', 'codes': ['3.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 740:
  Our aquaculture business is dedicated to the farming of amphibians, specifically frogs, which are increasingly sought after for their culinary value. We implement controlled breeding programs to ensure a consistent supply of high-quality frogs while adhering to strict animal welfare standards. Our facilities are designed to replicate natural habitats, providing the optimal environment for growth and development. We also engage in educational initiatives to raise awareness about the ecological importance of amphibians and promote responsible consumption practices among our customers.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.00020886999311508763, 'A': 0.9970320201137319, 'F': 0.0008556903912489543, 'B': 0.0017346231243896074, 'J': 0.00016879637751442817}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0029679798862680684}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 743/788 [00:46<00:03, 13.53it/s]

RAPS scores:
[1, 2, 3]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'1': 0, '2': 1, '3': 2}
RAPS scores:
RAPS scores:

==================================================
Description 741:
  Engaged in the cultivation of spices and aromatic crops, the company specializes in growing high-demand products such as saffron, basil, and rosemary. They employ organic farming practices to ensure the purity and flavor of their spices, which are marketed to gourmet food producers and health-conscious consumers. The company has established a robust supply chain that includes direct sales to restaurants and specialty grocery stores, allowing them to maintain freshness and quality. Additionally, they invest in educating consumers about the culinary and health benefits of their products, enhancing brand recognition and loyalty.
True: section=A, division=1, class=1.2
Section set: ['A']
Section probs: {'C': 1.0246849959774961e-05, 'A': 0.9999095954119691, 'F': 3.9893879231683105e-05, 'B': 2.7656510798401163e-05, 'J': 1.260734804104333e-05}
Division sets: {'A': ['1']}
Division probs: {'A': {1: 0.9979838797269268, 2: 0.001276626958278655, 3: 0.0007394933147945763}}
Class sets: {'1': ['1.2']}
Class probs: {'1': {1.2: 0.9830309467787093, 1.4: 0.0030415162913559647, 1.3: 0.006855689243604865, 1.1: 0.007071847686329976}}
Final output: {'type': 'class_level', 'codes': ['1.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 742:
  Our operations focus on the mining of titanium and zirconium ores, essential for the production of high-performance materials used in aerospace and automotive applications. We utilize advanced mineral processing technologies to separate and refine these ores, ensuring high purity and quality. Our commitment to sustainability drives us to implement eco-friendly practices throughout our mining operations, including water recycling and habitat restoration. By investing in cutting-edge research, we continually seek to enhance our extraction processes and reduce our carbon footprint, positioning ourselves as a responsible leader in the non-ferrous metals sector.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.740339745633806e-05, 'A': 3.376203290779199e-05, 'F': 1.2306371282499007e-05, 'B': 0.999889398059292, 'J': 7.1301390614585166e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011060194070799945}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 747/788 [00:46<00:03, 13.32it/s]

RAPS scores:

==================================================
Description 743:
  Focused on the extraction of crude petroleum, our operations span several key regions known for their rich hydrocarbon deposits. We employ cutting-edge hydraulic fracturing methods to unlock shale oil reserves, significantly increasing our output. Our team of geologists and engineers work collaboratively to assess geological formations, enabling us to make informed decisions about drilling locations. We also prioritize sustainability, implementing practices that minimize our carbon footprint and protect local ecosystems. By investing in research and development, we aim to enhance our extraction techniques and ensure a steady supply of crude oil to meet global energy demands.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.471551467279489e-05, 'A': 3.4567144363450837e-05, 'F': 1.2402909572490647e-05, 'B': 0.9998911056051822, 'J': 7.208826208950671e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7646917885795513e-06, 6: 0.9999964303393809, 7: 1.8049688306336546e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0022553125289051556, 6.1: 0.9977446874710948}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 744:
  Our operations revolve around the cultivation of high-quality tobacco plants, which we grow under strict quality control measures to ensure premium leaf production. We focus on sustainable farming practices, including integrated pest management and soil conservation techniques, to enhance the quality of our crops. Our tobacco is processed and sold to major manufacturers for use in premium cigar and cigarette production. We also invest in community development initiatives, supporting local farmers through training programs that promote best practices in tobacco cultivation.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.05925163178688657, 'A': 0.01009283678641146, 'F': 0.008400244923563385, 'B': 0.9204539959664491, 'J': 0.001801290536689613}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.07954600403355094}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 745:
  Focused on the mining of non-ferrous metal ores, we have developed a robust supply chain that integrates exploration, extraction, and processing. Our operations are powered by advanced geological modeling technologies that allow us to identify and evaluate ore deposits with precision. We prioritize safety and environmental stewardship, implementing rigorous protocols to manage the ecological impact of our activities. By producing high-quality metals, we serve a diverse range of sectors, including aerospace, automotive, and construction, ensuring that our products meet the highest industry standards.
True: section=B, division=7, class=7.2
Section set: ['B']
Section probs: {'C': 5.5555503298439315e-05, 'A': 3.403213833502439e-05, 'F': 1.2314564620455409e-05, 'B': 0.9998909607809006, 'J': 7.137012845311715e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4608686818133056e-06, 6: 1.5927479952469177e-06, 7: 0.9999959463833229}}
Class sets: {'7': ['7.2']}
Class probs: {'7': {7.1: 0.03514772870993726, 7.2: 0.9648522712900627}}
Final output: {'type': 'class_level', 'codes': ['7.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 746:
  Specializing in the raising of sheep and goats, our company focuses on producing high-quality wool and meat products. We practice rotational grazing, which not only improves pasture health but also enhances the nutritional quality of our livestock. Our breeding program emphasizes genetic diversity and resilience, ensuring that our flocks are well-adapted to local conditions. We also engage in value-added processing, transforming raw wool into finished textiles that are marketed to eco-conscious consumers. Our commitment to animal welfare and sustainable practices has positioned us as a leader in the local agricultural community, fostering strong relationships with both suppliers and customers.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.006948106193718963, 'A': 0.8311130972381409, 'F': 0.03132640893814956, 'B': 0.12803274623935568, 'J': 0.0025796413906349234}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.16888690276185914}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 750/788 [00:46<00:02, 15.83it/s]

RAPS scores:

==================================================
Description 747:
  Our business is centered on the extraction of natural gas, utilizing innovative techniques that prioritize efficiency and environmental responsibility. We operate multiple extraction sites equipped with advanced technology for the draining and separation of liquid hydrocarbon fractions. This process not only maximizes our output but also allows us to provide high-quality condensates to various sectors. Our gas desulphurization initiatives further enhance our commitment to sustainability, ensuring compliance with environmental regulations while improving product quality. Through strategic investments in technology and infrastructure, we aim to enhance our operational capabilities and deliver exceptional value to our partners.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.500065260105529e-05, 'A': 3.469334424208025e-05, 'F': 1.2472146891272617e-05, 'B': 0.9998906147586629, 'J': 7.219097602658259e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010938524133707883}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 748:
  Our business is centered around the gathering of forest residues, which we convert into energy products. We collect materials such as branches, leaves, and sawdust from logging operations, ensuring that no part of the tree goes to waste. These residues are processed into pellets and briquettes, providing a renewable energy source for heating and power generation. By utilizing what would otherwise be discarded, we contribute to a circular economy while promoting sustainable energy solutions.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.00010449690474786022, 'A': 7.777349569489339e-05, 'F': 2.5334849037229962e-05, 'B': 0.999779248627861, 'J': 1.3146122659010552e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0002207513721389498}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 749:
  We are engaged in the extraction and processing of natural gas, employing innovative methodologies that prioritize both efficiency and environmental sustainability. Our operations feature advanced drilling techniques that enable us to access previously untapped reserves while minimizing ecological disruption. We utilize sophisticated gas desulphurisation technologies to enhance the quality of our output, ensuring compliance with environmental regulations. By fostering strong partnerships with local communities and stakeholders, we aim to create shared value, driving economic growth while maintaining our commitment to responsible resource management.1. Our company specializes in the extraction and processing of natural gas, focusing on maximizing yield while minimizing environmental impact. Utilizing advanced drilling technologies and hydraulic fracturing techniques, we access previously untapped reserves of natural gas. Our operations include the separation of liquid hydrocarbon fractions, where we employ state-of-the-art separation technologies to enhance efficiency and reduce waste. Additionally, we provide gas desulphurization services to ensure compliance with environmental regulations, thereby delivering cleaner energy solutions to our clients. Our commitment to innovation and sustainability drives our growth in this competitive market.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.5339874463219616e-05, 'A': 3.4578752501024234e-05, 'F': 1.2489315813353205e-05, 'B': 0.999890335681625, 'J': 7.256375597509648e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010966431837500235}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 754/788 [00:47<00:02, 14.93it/s]

RAPS scores:

==================================================
Description 750:
  As a leader in lignite mining, we operate multiple surface mines that are strategically located to access rich deposits. Our mining operations are complemented by cutting-edge equipment that allows for the efficient extraction and transportation of lignite. We also provide comprehensive warehousing solutions, ensuring that our processed lignite is stored under optimal conditions to maintain quality before distribution. Our commitment to innovation includes implementing real-time monitoring systems that enhance operational efficiency and reduce downtime, ultimately delivering greater value to our clients.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.456845302271232e-05, 'A': 3.460581491793516e-05, 'F': 1.2401462402123651e-05, 'B': 0.9998912439767081, 'J': 7.180292949140343e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957362896036, 6: 1.3448366967565507e-06, 7: 2.91887369962571e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.0023550594684360365, 5.2: 0.9976449405315639}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 751:
  Our business is centered around the extraction of natural gas from both conventional and unconventional sources. We utilize horizontal drilling and hydraulic fracturing to unlock resources previously deemed inaccessible. Our facilities are equipped with advanced separation technologies that efficiently isolate liquid hydrocarbon fractions, allowing us to maximize output and profitability. Additionally, we have implemented comprehensive gas desulphurization processes to ensure compliance with environmental regulations and enhance the marketability of our products. By fostering strategic partnerships with local communities and stakeholders, we aim to create shared value while advancing our operational goals.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.489674931109676e-05, 'A': 3.4758762801049256e-05, 'F': 1.249961122678124e-05, 'B': 0.9998905975468967, 'J': 7.247329764334762e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010940245310331331}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 752:
  We specialize in the extraction of crude petroleum, employing advanced geological modeling techniques to identify the most promising drilling locations. Our commitment to technology extends to the use of automated drilling systems that enhance precision and reduce operational downtime. Additionally, we are exploring the integration of renewable energy sources into our extraction processes, aiming to create a more sustainable energy future. Our focus on innovation and efficiency not only drives our production but also positions us as a leader in responsible oil extraction practices.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.519129590893798e-05, 'A': 3.444405631391975e-05, 'F': 1.241526924934583e-05, 'B': 0.9998907725171102, 'J': 7.176861417565093e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7801197998561365e-06, 6: 0.9999963822432894, 7: 1.8376369107347888e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020525340565825706, 6.1: 0.9979474659434173}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 753:
  We engage in the production of roundwood specifically for the manufacturing of rubber products, such as rubberwood furniture and flooring. Our logging practices are designed to ensure that we harvest only the best quality timber, which is then processed into high-value products. By focusing on rubberwood, we not only provide a sustainable alternative to traditional hardwoods but also help reduce waste in the rubber industry. Our commitment to sustainability extends to our manufacturing processes, where we prioritize eco-friendly practices and materials.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.9997684066751977, 'A': 1.3104557483140792e-05, 'F': 1.555894186385809e-05, 'B': 7.038104241647727e-05, 'J': 0.00013254878303871782}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00023159332480227057}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 756/788 [00:47<00:02, 14.87it/s]

RAPS scores:

==================================================
Description 754:
  Our company operates a network of forest tree nurseries that specialize in the cultivation of diverse tree species for various applications. We focus on producing seedlings that are not only suitable for timber production but also for ecological restoration projects. By utilizing innovative propagation techniques and sustainable practices, we ensure that our nurseries contribute positively to the environment. Our partnerships with conservation organizations enable us to play a vital role in reforestation efforts, helping to restore habitats and promote biodiversity.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 3.4907353868638314e-05, 'A': 0.9996193708806665, 'F': 0.00018805660598653306, 'B': 0.00012054409890288735, 'J': 3.712106057510434e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0003806291193334532}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 755:
  We are committed to sustainable mining practices, employing innovative methods in the extraction of iron ore. Our operations are equipped with modern machinery that enables us to optimize ore recovery and minimize waste. We also prioritize environmental stewardship by implementing comprehensive land rehabilitation programs post-mining. Our focus on quality assurance ensures that the iron ore we supply is of the highest grade, supporting our clients in the steel industry to meet their production needs while adhering to environmental regulations.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.499964629581847e-05, 'A': 3.4368621340879315e-05, 'F': 1.2338462938199955e-05, 'B': 0.9998911533584999, 'J': 7.139910925310857e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.461589266083838e-06, 6: 1.5958702355975408e-06, 7: 0.9999959425404983}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677951777836514, 7.2: 0.03220482221634844}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 760/788 [00:47<00:02, 13.86it/s]

RAPS scores:

==================================================
Description 756:
  We specialize in the extraction of natural gas, utilizing innovative technologies to enhance our operational efficiency and output quality. Our team employs advanced drilling techniques to access deep reserves, while our processing facilities are designed to effectively separate condensates and liquid hydrocarbon fractions. This allows us to maximize the value of our natural gas production. Furthermore, we are committed to implementing gas desulphurization processes that reduce sulfur content in our products, ensuring compliance with environmental regulations and contributing to the development of cleaner energy solutions for our clients.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.510943872352358e-05, 'A': 3.441060893382992e-05, 'F': 1.23940006742932e-05, 'B': 0.9998909117204369, 'J': 7.174231231449815e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7724105720495864e-06, 6: 0.9999964138748323, 7: 1.8137145957289432e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979752015336105, 6.1: 0.0020247984663894596}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 757:
  Our company is engaged in the cultivation of various other perennial crops, focusing on sustainable practices that enhance biodiversity and soil health. We grow a diverse array of plants, including medicinal herbs and ornamental species, catering to both the agricultural and horticultural markets. Our commitment to organic farming ensures that our products meet the highest standards of quality and safety. We actively participate in community-supported agriculture programs, allowing consumers to access fresh, locally grown products while supporting sustainable farming practices. Our innovative approaches to crop diversity help us adapt to changing market demands.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.06719878377482418, 'A': 0.4117241075753426, 'F': 0.23465491358655516, 'B': 0.27604834439029685, 'J': 0.010373850672981348}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5882758924246574}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 758:
  Our business model is centered around the extraction and processing of iron ores, with a strong emphasis on technological innovation and sustainability. We operate several mines where we utilize advanced extraction techniques to ensure maximum yield while minimizing environmental disruption. Our beneficiation operations are equipped with cutting-edge technology that allows us to produce high-quality iron concentrates. We also focus on agglomeration processes, producing iron pellets that are ideal for the steel manufacturing sector. By continuously investing in research and development, we aim to improve our operational efficiencies and reduce our carbon footprint.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.546720305243527e-05, 'A': 3.406292618346637e-05, 'F': 1.2306843090073195e-05, 'B': 0.999891019165605, 'J': 7.143862069033057e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.4958580901178264e-06, 6: 1.568667948680236e-06, 7: 0.9999959354739613}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677515332469956, 7.2: 0.032248466753004315}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 759:
  Our company specializes in the raising of other equines, particularly donkeys and mules, for both work and companionship. We prioritize humane treatment and proper care, ensuring that our animals are healthy and well-socialized. Our breeding practices focus on enhancing traits that make these animals suitable for various tasks, from farm work to therapy roles. We also offer educational programs for potential owners, promoting responsible ownership and care. By highlighting the versatility and unique qualities of donkeys and mules, we aim to increase awareness and appreciation for these remarkable animals.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0008805503159168314, 'A': 0.9447106975134273, 'F': 0.05098043481420217, 'B': 0.002571919692890098, 'J': 0.0008563976635639156}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.05528930248657271}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 762/788 [00:47<00:01, 13.86it/s]

RAPS scores:

==================================================
Description 760:
  Our operations focus on the cultivation of sugar cane, where we employ cutting-edge agricultural practices to enhance productivity and sustainability. We utilize precision farming techniques to monitor crop health and optimize irrigation, resulting in higher yields and reduced environmental impact. The harvested cane is processed at our nearby facilities, where we produce raw sugar and molasses, supplying both local markets and export opportunities. Our commitment to ethical sourcing and eco-friendly practices positions us as a leader in the sugar industry.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.00703322048262293, 'A': 0.003460445929205806, 'F': 0.0012444798560107462, 'B': 0.9878493297315395, 'J': 0.0004125240006210211}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.012150670268460506}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 761:
  As a leader in lignite mining, our company focuses on maximizing resource recovery while minimizing environmental impact. We employ surface mining techniques that are complemented by advanced washing and dehydration processes to enhance lignite quality. Our state-of-the-art storage facilities are designed to protect the integrity of the lignite before it is transported to clients. By integrating cutting-edge technology and sustainable practices, we create value for our stakeholders and contribute to the energy needs of various sectors.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4784357196684146e-05, 'A': 3.455028988888586e-05, 'F': 1.2406206908269345e-05, 'B': 0.9998910853548166, 'J': 7.173791189510445e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957351312672, 6: 1.3476438864078682e-06, 7: 2.917224846616857e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002354946877435565, 5.2: 0.9976450531225644}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 767/788 [00:48<00:01, 16.08it/s]

RAPS scores:

==================================================
Description 762:
  Our business is centered around the extraction and processing of natural gas, utilizing advanced technologies to optimize our operations. We employ innovative drilling techniques to access crude gaseous hydrocarbons and maximize extraction efficiency. Our facilities are designed for the effective separation of liquid hydrocarbon fractions, ensuring high recovery rates and quality outputs. Furthermore, we prioritize gas desulphurization to produce cleaner natural gas that meets stringent environmental regulations. Through continuous investment in technology and sustainable practices, we strive to be a leader in the energy sector, providing reliable and eco-friendly solutions.
True: section=B, division=6, class=6.2
Section set: ['B']
Section probs: {'C': 5.473925073252311e-05, 'A': 3.478035137041547e-05, 'F': 1.2472963732388198e-05, 'B': 0.999890779129872, 'J': 7.228304292747234e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.7658331984965236e-06, 6: 0.9999964341838478, 7: 1.7999829538581702e-06}}
Class sets: {'6': ['6.2']}
Class probs: {'6': {6.2: 0.9979689278531844, 6.1: 0.002031072146815734}}
Final output: {'type': 'class_level', 'codes': ['6.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 763:
  We are at the forefront of growing fiber crops, particularly cotton and hemp, which are essential for the textile and bioproducts industries. Our cultivation methods emphasize sustainability, with a focus on water conservation and soil health. We collaborate with researchers to develop eco-friendly pest management solutions, reducing the reliance on chemical inputs. Our commitment to quality extends to our supply chain, where we ensure that our fiber products meet the stringent requirements of manufacturers, thus supporting the circular economy in the fashion industry.
True: section=A, division=1, class=1.1
Section set: []
Section probs: {'C': 0.9977376878472063, 'A': 0.00010818129473825739, 'F': 0.0002071184731025924, 'B': 0.0015618679436818254, 'J': 0.00038514444127090775}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0022623121527937107}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 764:
  Our firm specializes in the extraction of nickel and cobalt ores, essential components for battery production in electric vehicles. We utilize advanced hydrometallurgical processes to ensure high recovery rates and minimize waste. Our commitment to sustainability is evident in our efforts to reduce carbon emissions and implement circular economy practices, such as recycling spent batteries for raw materials. We work closely with automotive manufacturers to develop tailored solutions that meet their specific needs, positioning ourselves as a reliable supplier in the rapidly evolving green technology market. Our focus on innovation and collaboration drives our competitive edge in the non-ferrous mining sector.
True: section=B, division=7, class=7.2
Section set: []
Section probs: {'C': 5.7340728878068114e-05, 'A': 3.373736605486183e-05, 'F': 1.2289809306030117e-05, 'B': 0.9998895131531992, 'J': 7.118942561707435e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00011048684680081688}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 765:
  Focused on the raising of rabbits, our farm produces high-quality meat and fur products while emphasizing humane treatment and sustainable practices. We implement a breeding program that prioritizes health and growth rates, ensuring that our rabbits are raised in spacious, clean environments. Our commitment to animal welfare includes providing enrichment activities that promote natural behaviors. We also explore value-added products, such as gourmet rabbit meat and handcrafted fur items, allowing us to tap into niche markets while maintaining our dedication to ethical farming practices.1. Our company specializes in the raising of dairy cattle, focusing on sustainable practices that enhance milk production while prioritizing animal welfare. We employ advanced breeding techniques to improve herd genetics, ensuring high-quality milk with optimal nutritional value. Our state-of-the-art milking facilities utilize automated technology to streamline operations, reduce labor costs, and maintain hygiene standards. Additionally, we invest in renewable energy sources, such as solar panels, to power our operations, further reducing our carbon footprint. Our commitment to sustainability not only benefits the environment but also strengthens our brand reputation among health-conscious consumers.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.018672413966648115, 'A': 0.20657745281417467, 'F': 0.024603038333874075, 'B': 0.7467813358749595, 'J': 0.003365759010343548}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.25321866412504046}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 766:
  Our freshwater aquaculture operations focus on breeding and raising fish species such as tilapia and catfish in controlled environments. By utilizing recirculating aquaculture systems, we reduce water usage and minimize waste, creating a sustainable model for fish production. Our facility is designed to provide optimal growth conditions, ensuring high-quality fish that meet the demands of both local and international markets. We also engage in educational outreach, sharing best practices for sustainable aquaculture with aspiring fish farmers to promote responsible food production in the region.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 7.46767644124034e-05, 'A': 0.9991884568279298, 'F': 0.00026242910467931123, 'B': 0.00040536331488104236, 'J': 6.907398809733096e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0008115431720702171}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 770/788 [00:48<00:00, 18.80it/s]

RAPS scores:

==================================================
Description 767:
  We focus on the comprehensive processing of lignite, utilizing innovative pulverizing technology to create a product that meets diverse customer requirements. Our facilities are designed to optimize the washing and dehydrating processes, ensuring that the lignite we produce is not only of high quality but also ready for efficient transportation. Additionally, we offer storage solutions that maintain the integrity of the lignite, preventing moisture absorption and degradation. This commitment to quality and efficiency allows us to serve a wide range of industries that depend on reliable energy sources.
True: section=B, division=5, class=5.2
Section set: []
Section probs: {'C': 0.9996309737002335, 'A': 1.7959586033072203e-05, 'F': 2.008065346092952e-05, 'B': 0.00018585423908395652, 'J': 0.0001451318211885037}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00036902629976653945}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 768:
  Engaged in freshwater fishing, our operations are centered around the collection of high-quality fish species from lakes and rivers. We employ environmentally friendly fishing techniques, such as catch-and-release practices, to ensure the sustainability of fish populations. Our team utilizes specialized equipment, including gill nets and fishing rods, to target species like trout and bass. Additionally, we offer guided fishing tours, providing enthusiasts with an opportunity to experience the thrill of fishing while educating them on conservation efforts and the importance of maintaining healthy aquatic ecosystems.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.00018197530716467251, 'A': 0.9968950813863178, 'F': 0.0005242252178355358, 'B': 0.002250914693576552, 'J': 0.00014780339510560173}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.003104918613682228}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 769:
  Our aquaculture enterprise is at the forefront of shrimp farming, employing cutting-edge techniques to enhance production efficiency. We utilize biosecurity measures and advanced feeding protocols to promote healthy growth and reduce mortality rates. Our farms are strategically located in coastal areas to leverage natural tidal movements, which aid in water circulation and nutrient distribution. We also invest in research to develop sustainable farming practices that align with environmental regulations. By prioritizing quality and sustainability, we cater to both local markets and international seafood distributors.
True: section=A, division=3, class=3.2
Section set: []
Section probs: {'C': 0.0011062708105784257, 'A': 0.9695286033788216, 'F': 0.0020956220377764292, 'B': 0.02665446033598372, 'J': 0.0006150434368396967}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.03047139662117837}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 770:
  We are dedicated to the collection and processing of wild berries, offering a range of products from fresh, organic berries to value-added items like jams and jellies. Our operations involve a network of local pickers who gather berries during peak seasons, ensuring optimal quality and flavor. We utilize eco-friendly packaging and distribution methods to minimize our environmental footprint. Our commitment to sustainability and quality has earned us partnerships with health food stores and organic markets, where our products are celebrated for their taste and nutritional benefits.
True: section=A, division=2, class=2.3
Section set: []
Section probs: {'C': 0.9539968269163513, 'A': 0.0010769777075618813, 'F': 0.0029237448530628593, 'B': 0.04018723091342816, 'J': 0.0018152196095959248}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.04600317308364865}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 771:
  We focus on the extraction of natural gas, utilizing sophisticated technologies to enhance our production capabilities. Our operations include the draining and separation of liquid hydrocarbon fractions, which are vital for maximizing the value of our resources. We have adopted advanced gas desulphurization processes to improve the quality of our natural gas, ensuring compliance with environmental regulations. Our commitment to research and development drives our continuous improvement efforts, positioning us as a leader in the natural gas industry while contributing to a sustainable energy future.1. Our company specializes in the extraction and processing of natural gas, utilizing advanced drilling techniques to access deep reserves. We employ state-of-the-art technology to ensure efficient extraction while minimizing environmental impact. Our operations include the separation of natural gas from condensates, which allows us to maximize yield and deliver high-quality products to our clients. Additionally, we invest in gas desulphurization processes to enhance the purity of our gas, making it suitable for various industrial applications. By focusing on innovation and sustainability, we aim to meet the growing demand for cleaner energy sources.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.604676999541009e-05, 'A': 3.407176044381126e-05, 'F': 1.2352168934588348e-05, 'B': 0.9998903413406883, 'J': 7.187959937953135e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010965865931167329}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 773/788 [00:48<00:00, 19.98it/s]

RAPS scores:

==================================================
Description 772:
  Our enterprise specializes in the raising of other equines, particularly donkeys and mules, which are valued for their strength and temperament. We provide educational programs on the benefits of using these animals for farm work and companionship. Our breeding program emphasizes the development of gentle and trainable animals, catering to both recreational and agricultural markets. We also engage in community outreach, offering workshops that highlight the importance of equines in sustainable farming practices, thereby fostering a greater appreciation for these hardworking animals.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 5.3481552387063294e-05, 'A': 0.9990801217243968, 'F': 0.0006372484744280833, 'B': 0.00016618442824955628, 'J': 6.296382053850123e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0009198782756032475}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 773:
  Our focus on hard coal mining encompasses a comprehensive approach that includes both extraction and processing. We utilize cutting-edge technologies to optimize our underground and surface mining operations, ensuring we maximize coal recovery while adhering to environmental regulations. After extraction, our coal undergoes thorough cleaning and sizing processes, enhancing its quality for end-users. Our state-of-the-art pulverizing facilities allow us to produce coal in various grades, meeting the specific requirements of our clients in the energy and manufacturing sectors, ultimately driving value creation across the supply chain.1. Our company specializes in the extraction and processing of hard coal through both surface and underground mining techniques. Utilizing advanced liquefaction methods, we enhance the efficiency of our mining operations, ensuring minimal environmental impact. We employ state-of-the-art machinery for the cleaning and sizing of coal, which allows us to produce high-quality products tailored to the needs of our clients. Our commitment to sustainability is evident in our rigorous quality control processes, which not only improve the coal's market value but also facilitate its transport and storage, ensuring that we meet the demands of various industries while adhering to environmental regulations.
True: section=B, division=5, class=5.1
Section set: ['B']
Section probs: {'C': 5.524175982088705e-05, 'A': 3.433419210861751e-05, 'F': 1.2378578609468522e-05, 'B': 0.9998908418166381, 'J': 7.203652822870152e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.999995729774875, 6: 1.336895038462838e-06, 7: 2.933330086224409e-06}}
Class sets: {'5': ['5.1']}
Class probs: {'5': {5.1: 0.9975268122398986, 5.2: 0.0024731877601014813}}
Final output: {'type': 'class_level', 'codes': ['5.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 778/788 [00:48<00:00, 15.61it/s]

RAPS scores:

==================================================
Description 774:
  Our forestry operations encompass the management of coppice woodlands, where we practice selective harvesting to promote regrowth and sustainability. This method allows us to produce high-quality firewood and pulpwood while maintaining the ecological integrity of the forest. Through careful monitoring and planning, we optimize the yield from our coppice systems, providing a renewable source of energy and raw materials for various industries. Our approach not only meets market demands but also fosters a healthy forest ecosystem.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 0.00014446381339421947, 'A': 0.9979953478720412, 'F': 0.0005705463926416192, 'B': 0.0011641676140037723, 'J': 0.000125474307919195}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.0020046521279587504}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 775:
  Our business focuses on the sustainable harvesting of roundwood for various applications, including the production of charcoal and firewood. We implement eco-friendly practices throughout our operations, from logging to processing, ensuring that we maintain the health of the forests we rely on. Our charcoal products are crafted using traditional methods that enhance flavor and quality, appealing to both culinary professionals and home cooks. By diversifying our product offerings, we create value for our customers while supporting sustainable forest management.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.001859438962258684, 'A': 0.002540268108185264, 'F': 0.000586965133239013, 'B': 0.9948174446784931, 'J': 0.00019588311782414036}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00518255532150691}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 776:
  We specialize in the extraction of natural gas, with a focus on maximizing recovery through innovative drilling techniques and advanced geological analysis. Our operations are characterized by a commitment to environmental stewardship, as we implement best practices in resource management and emissions reduction. We also invest in research and development to enhance our extraction methods, ensuring that we remain at the forefront of technological advancements in the industry. By providing reliable and sustainable natural gas solutions, we contribute to meeting the growing energy demands of our customers while supporting a transition to cleaner energy sources.
True: section=B, division=6, class=6.2
Section set: []
Section probs: {'C': 5.5035787082984404e-05, 'A': 3.484476137936202e-05, 'F': 1.252798164991208e-05, 'B': 0.9998903694388708, 'J': 7.222031017021204e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010963056112922587}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 777:
  We are dedicated to the sustainable mining of lignite, employing cutting-edge technologies that minimize our ecological footprint. Our operations include both surface and underground mining, with a strong emphasis on safety and efficiency. Once extracted, the lignite undergoes a thorough washing and pulverizing process, which not only improves its quality but also facilitates easier transport and storage. Our logistics team ensures that the processed lignite reaches our customers promptly, supporting their energy needs while adhering to strict environmental regulations.
True: section=B, division=5, class=5.2
Section set: ['B']
Section probs: {'C': 5.4774820324468694e-05, 'A': 3.458759502522663e-05, 'F': 1.2423077611250339e-05, 'B': 0.9998910355627371, 'J': 7.178944301879748e-06}
Division sets: {'B': ['5']}
Division probs: {'B': {5: 0.9999957264249969, 6: 1.337429350000571e-06, 7: 2.9361456530138207e-06}}
Class sets: {'5': ['5.2']}
Class probs: {'5': {5.1: 0.002355814695129701, 5.2: 0.9976441853048702}}
Final output: {'type': 'class_level', 'codes': ['5.2']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 781/788 [00:48<00:00, 18.28it/s]

RAPS scores:

==================================================
Description 778:
  Our company is a leader in the gathering and production of wood for energy, focusing on renewable resources to meet the increasing demand for sustainable energy solutions. We source wood from responsibly managed forests, transforming it into biomass fuel that powers homes and businesses. Our advanced processing facilities ensure that the wood is converted efficiently, providing a clean alternative to fossil fuels. By promoting the use of biomass, we contribute to reducing carbon emissions and supporting a greener future.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.009670582041850987, 'A': 0.3855399389647386, 'F': 0.008724223558268292, 'B': 0.5934990141603508, 'J': 0.0025662412747913415}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4065009858396492}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 779:
  In the realm of raising other animals, our company specializes in the breeding of alpacas for their luxurious fiber. We have developed a sustainable farming model that emphasizes the health and well-being of our animals while producing high-quality fleece. Our alpacas are raised in a serene environment that encourages natural behaviors, and we utilize responsible breeding practices to enhance fiber quality and genetic diversity. The fleece is processed into a range of products, including yarn and textiles, which are marketed to artisans and craft enthusiasts. Our commitment to ethical farming and quality craftsmanship has established us as a leader in the niche market of alpaca products.
True: section=A, division=1, class=1.4
Section set: []
Section probs: {'C': 0.0005109225544886331, 'A': 0.9927219455851412, 'F': 0.0038167475969847742, 'B': 0.0025801214764686296, 'J': 0.0003702627869167915}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.007278054414858848}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 780:
  Our company specializes in the collection and processing of forest harvesting residues, transforming what would otherwise be waste into valuable energy resources. We gather leftover branches, bark, and other by-products from logging operations and convert them into biomass fuel. This not only reduces waste but also provides a sustainable energy alternative for local communities. By employing innovative processing techniques, we ensure that our biomass products are efficient and cost-effective, contributing to a circular economy within the forestry sector.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0015833575031379042, 'A': 0.00831243211490038, 'F': 0.0008002005262339184, 'B': 0.9890132498151523, 'J': 0.0002907600405756005}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.010986750184847738}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 781:
  Timberland Enterprises is dedicated to the sustainable management of timber resources, specializing in the cultivation of firewood and pulpwood. Our operations involve strategic planting and replanting efforts that prioritize the health of our forests. We utilize innovative silvicultural practices to ensure that our thinning operations are efficient and environmentally friendly. Our tree nursery provides high-quality seedlings that support both commercial forestry and ecological restoration initiatives. By focusing on sustainability and community engagement, we aim to create value while preserving the natural environment for future generations.1. Our company specializes in sustainable forest management, focusing on the growth and conservation of timber resources. We engage in activities such as planting, replanting, and thinning to ensure the health and productivity of our forests. By utilizing advanced silvicultural techniques, we optimize growth rates and enhance biodiversity. Our commitment to responsible forestry practices not only contributes to the local economy but also supports environmental sustainability. We operate tree nurseries that provide high-quality seedlings for reforestation projects, ensuring a continuous supply of timber for future generations while maintaining ecological balance.
True: section=A, division=2, class=2.1
Section set: []
Section probs: {'C': 2.37747479730639e-05, 'A': 0.9997740417713129, 'F': 8.846335290505809e-05, 'B': 8.818514349527236e-05, 'J': 2.5534984313876354e-05}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00022595822868709536}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 782:
  Our company is at the forefront of crude petroleum extraction, utilizing a combination of traditional and innovative practices to enhance production efficiency. We operate several offshore platforms equipped with the latest drilling technology, allowing us to extract oil from deep-water reserves. Our commitment to safety and environmental protection is paramount; we implement rigorous monitoring systems to track emissions and spills, ensuring compliance with industry regulations. Additionally, we invest in community engagement initiatives, fostering relationships with local stakeholders to promote transparency and trust in our operations.
True: section=B, division=6, class=6.1
Section set: []
Section probs: {'C': 5.503034959179836e-05, 'A': 3.476360803667138e-05, 'F': 1.2470486419338816e-05, 'B': 0.999890509062915, 'J': 7.2264930372353526e-06}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.00010949093708501056}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 784/788 [00:48<00:00, 16.80it/s]

RAPS scores:
[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 783:
  Our operations are centered around the mining and beneficiation of iron ores, where we utilize both open-pit and underground mining techniques. We prioritize the use of environmentally friendly practices, including water recycling and land rehabilitation, to minimize our ecological footprint. The iron ores extracted are processed through advanced crushing and grinding systems, followed by magnetic separation to produce high-purity concentrates. Our ongoing investment in research and development enables us to innovate and improve our processes, ensuring we remain competitive in the global iron ore market.
True: section=B, division=7, class=7.1
Section set: ['B']
Section probs: {'C': 5.4799837198477985e-05, 'A': 3.429922749760968e-05, 'F': 1.2320899269765848e-05, 'B': 0.9998914394574403, 'J': 7.140578593849832e-06}
Division sets: {'B': ['7']}
Division probs: {'B': {5: 2.481457134665876e-06, 6: 1.5777704868914417e-06, 7: 0.9999959407723785}}
Class sets: {'7': ['7.1']}
Class probs: {'7': {7.1: 0.9677973066833688, 7.2: 0.03220269331663115}}
Final output: {'type': 'class_level', 'codes': ['7.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 784:
  Our company is dedicated to gathering and producing wood for energy, focusing on renewable resources to meet the growing demand for sustainable energy solutions. We harvest wood from managed forests, ensuring that our practices promote ecological health and regeneration. The wood we collect is processed into biomass fuel, which is then supplied to energy producers looking to reduce their carbon footprint. By converting waste materials and forest residues into energy, we contribute to a circular economy and support local communities through job creation.
True: section=A, division=2, class=2.2
Section set: []
Section probs: {'C': 0.0003607702468539355, 'A': 0.9949938444870196, 'F': 0.0009220011399608911, 'B': 0.0034653460766973262, 'J': 0.0002580380494683695}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.005006155512980448}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

==================================================
Description 785:
  Our company is dedicated to the innovative processing of fish for both fresh and frozen markets. We utilize advanced refrigeration techniques to maintain the highest quality standards from catch to consumer. Our processing facility is equipped with cutting-edge technology that allows for quick turnaround times, ensuring our products reach customers promptly. We also emphasize traceability, providing consumers with information about the origin of their seafood. Our partnerships with local fishermen help us source sustainable fish, reinforcing our commitment to responsible fishing practices.
True: section=A, division=3, class=3.1
Section set: []
Section probs: {'C': 0.9928162542596757, 'A': 0.0001905135096637571, 'F': 0.0003288941568623089, 'B': 0.006145251551837261, 'J': 0.0005190865219610002}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.007183745740324321}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

RAPS scores:

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 788/788 [00:49<00:00, 16.02it/s]

[5, 6, 7]
{'A': {'1': 0, '2': 1, '3': 2}, 'B': {'5': 0, '6': 1, '7': 2}}
{'5': 0, '6': 1, '7': 2}
RAPS scores:
RAPS scores:

==================================================
Description 786:
  As a leader in crude petroleum extraction, we utilize a combination of traditional drilling and advanced technologies such as horizontal drilling to maximize our output. Our operations are designed to be efficient and environmentally responsible, with a strong emphasis on reducing waste and emissions. We have established a comprehensive training program for our workforce, ensuring that they are equipped with the skills needed to operate our advanced machinery safely. Additionally, our commitment to innovation drives us to explore new extraction techniques that could further enhance our productivity while preserving the integrity of the ecosystems in which we operate.
True: section=B, division=6, class=6.1
Section set: ['B']
Section probs: {'C': 5.491615907633453e-05, 'A': 3.466051053235497e-05, 'F': 1.2449077244019456e-05, 'B': 0.999890767275044, 'J': 7.206978103417398e-06}
Division sets: {'B': ['6']}
Division probs: {'B': {5: 1.788943930676562e-06, 6: 0.9999963784655781, 7: 1.8325904913130045e-06}}
Class sets: {'6': ['6.1']}
Class probs: {'6': {6.2: 0.0020571047850644333, 6.1: 0.9979428952149355}}
Final output: {'type': 'class_level', 'codes': ['6.1']}
Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:

==================================================
Description 787:
  Our organization focuses on the cultivation of citrus fruits, including oranges, lemons, and limes, which are harvested at peak ripeness to ensure optimal flavor and nutritional value. We utilize precision agriculture technologies to monitor soil health and crop conditions, allowing for targeted interventions that enhance productivity. Our citrus fruits are processed into juices, essential oils, and flavoring agents, catering to a diverse range of food and beverage industries. We also engage in research and development to breed disease-resistant varieties, ensuring a sustainable supply chain for our customers.
True: section=A, division=1, class=1.2
Section set: []
Section probs: {'C': 0.3776203915561634, 'A': 0.009540233932936721, 'F': 0.01566881690954344, 'B': 0.5931802597398603, 'J': 0.003990297861496124}
Division sets: {}
Division probs: {}
Class sets: {}
Class probs: {}
Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4068197402601397}
Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

In [161]:
rs = reject_score_1d(list({'C': 5.6940012134894205e-05, 'A': 3.629107039733317e-05, 'F': 1.3162245625785396e-05, 'B': 0.9998860236423458, 'J': 7.583029496128303e-06}.values()))
rs

0.00011397635765419967

In [162]:
rs > tau_rej, tau_rej

(True, 0.00010931266827907127)

In [150]:
print("false_positives_lvl_1: ", np.mean(false_positives_lvl_1))
print("false_positives_lvl_2: ", np.mean(false_positives_lvl_2))
print("false_positives_lvl_3: ", np.mean(false_positives_lvl_3))

print("true_lvl_1: ", np.mean(true_lvl_1))
print("true_lvl_2: ", np.mean(true_lvl_2))
print("true_lvl_3: ", np.mean(true_lvl_3)) 

print("Nbr of test datapoints: ", len(true_lvl_2))

false_positives_lvl_1:  0.0
false_positives_lvl_2:  0.0038071065989847717
false_positives_lvl_3:  0.0012690355329949238
true_lvl_1:  0.2868020304568528
true_lvl_2:  0.282994923857868
true_lvl_3:  0.2817258883248731
Nbr of test datapoints:  788

## Test for Desc Pages

In [ ]:
# use description pages

dataset_path = "data/datasets/stoxx_600"

over_view_df_path = os.path.join(dataset_path, os.path.basename(dataset_path) + "_overview.csv")

dataset_path_texts = os.path.join(dataset_path, "TXTs")

dataset_name = os.path.basename(dataset_path)

nace_classes_full = pd.read_csv(over_view_df_path, index_col=0, sep=";")

In [ ]:
nace_classes = nace_classes_full[nace_classes_full["description_page"].notna()]
nace_classes

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page
107,AAK AB,AAK-SE,AAK-SE,4741.086317,4010.433824,3939.34280627966,10.89,C,AAK AB1.pdf,3
94,ABB Ltd.,ABBN-CH,ABBN-CH,28073.948473,29665.651960,30586.3762461154,27.11,C,ABB Ltd.2.pdf,18
135,Accelleron Industries AG,ACLN-CH,ACLN-CH,742.680345,846.217532,NaN,28.11,C,Accelleron Industries AG1.pdf,7
296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7
365,Accor SA,AC-FR,AC-FR,4224.000000,5056.000000,5606,55.10,I,Accor SA1.pdf,5
...,...,...,...,...,...,...,...,...,...,...
69,Orkla ASA,ORK-NO,ORK-NO,5774.960695,5932.590483,6073.67720031738,10.89,C,Orkla ASA1.pdf,11
598,Scout24 SE,G24-DE,G24-DE,447.539000,509.114000,s,96.09,S,Scout24 SE3.pdf,41
286,Severn Trent Plc,SVT-GB,SVT-GB,2505.264229,2709.430915,NaN,36.00,E,Severn Trent Plc1.pdf,8
133,Siemens Energy AG,ENR-DE,ENR-DE,29005.000000,31119.000000,34465,27.33,C,Siemens Energy AG1.pdf,5
30,Signify NV,LIGHT-NL,LIGHT-NL,7514.000000,6704.000000,6143,27.40,C,Signify NV3.pdf,6

In [ ]:
description_page_path = "data/datasets/stoxx_600/company_descriptions_txt/"

In [ ]:
nace_classes["NACE_lvl_3"] = nace_classes["NACE"].apply(lambda x: NACE_helper.get_all_level(x)[3])
nace_classes = nace_classes[nace_classes["NACE_lvl_3"].apply(lambda x: x in all_classes)]

/tmp/ipykernel_848414/4104711228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nace_classes["NACE_lvl_3"] = nace_classes["NACE"].apply(lambda x: NACE_helper.get_all_level(x)[3])

In [ ]:
nace_classes = nace_classes.sort_values(by="NACE_letter")
nace_classes

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page,NACE_lvl_3
1,Bakkafrost P/F,BAKKA-NO,BAKKA-NO,929.503079,937.862170,973.053513491168,3.21,A,Bakkafrost PF2.pdf,4,03.2
132,Alcon AG,ALC-CH,ALC-CH,8294.208061,8745.595513,9162.50793328229,26.60,C,Alcon AG1.pdf,47,26.6
125,argenx SE,ARGX-BE,ARGX-BE,390.824013,1134.306078,2024.8217775747,21.10,C,argenx SE1.pdf,28,21.1
35,AstraZeneca PLC,AZN-GB,AZN-GB,42199.888931,42373.821732,49989.333053702,21.20,C,AstraZeneca PLC1.pdf,5,21.2
76,Bavarian Nordic A/S,BAVA-DK,BAVA-DK,423.526567,947.164439,765.63798368454,21.20,C,Bavarian Nordic AS1.pdf,6,21.2
129,COMET Holding AG,COTN-CH,COTN-CH,584.204846,409.093151,467.557574915886,26.60,C,COMET Holding AG1.pdf,21,26.6
123,DiaSorin S.p.A.,DIA-IT,DIA-IT,1361.138000,1148.210000,NaN,21.20,C,DiaSorin S.p.A.1.pdf,11,21.2
52,Merck KGaA,MRK-DE,MRK-DE,22232.000000,20993.000000,21156,21.20,C,Merck KGaA2.pdf,4,21.2
475,Allfunds Group plc,ALLFG-NL,ALLFG-NL,493.950000,548.153000,632.100000000053,66.11,K,Allfunds Group plc1.pdf,6,66.1
433,Avanza Bank Holding AB,AZA-SE,AZA-SE,324.377745,410.819403,478.646065026522,66.12,K,Avanza Bank Holding AB1.pdf,4,66.1
428,Bank of Ireland Group Plc,BIRG-IE,BIRG-IE,6074.000000,8952.000000,9853,64.19,K,Bank of Ireland Group Plc1.pdf,7,64.1
473,Banque Cantonale Vaudoise,BCVN-CH,BCVN-CH,1179.079691,1643.462332,1745.73023593426,64.19,K,Banque Cantonale Vaudoise1.pdf,12,64.1
469,Bridgepoint Group Plc,BPT-GB,BPT-GB,367.667822,366.781809,NaN,66.30,K,Bridgepoint Group Plc1.pdf,4,66.3
460,Cembra Money Bank AG,CMBN-CH,CMBN-CH,536.239665,607.890645,688.319492304325,64.92,K,Cembra Money Bank AG1.pdf,5,64.9
439,Deutsche Bank Aktiengesellschaft,DBK-DE,DBK-DE,40533.000000,60635.000000,30092,66.12,K,Deutsche Bank Aktiengesellschaft1.pdf,6,66.1

In [ ]:
false_positives_lvl_1 = []
false_positives_lvl_2 = []
false_positives_lvl_3 = []

true_lvl_1 = []
true_lvl_2 = []
true_lvl_3 = []

for i, row in nace_classes.iterrows():
#for i, row in nace_classes.loc[460:460].iterrows():
#for i in range(len(X_lvl_3_test)):
    with open(os.path.join(description_page_path,row["Report"].replace("pdf", "txt")), "r") as f: 
        desc = f.read()

    # ts, td, tc = y_sec_cal[i], y_div_cal[i], y_cls_cal[i]

    tc = row["NACE_lvl_3"]
    td = [div for div, cls_ in classes.items() if tc in cls_][0]
    ts = [sec for sec, divs in divisions.items() if td in divs][0]
    
    pred = predict_full_one(desc, max_leaf_size=3)

    y_lvl_3_test

    print("\n==================================================")
    print(f"Description {i}:\n ", desc.replace("\n", " "))
    print(f"True: section={ts}, division={td}, class={tc}")
    print("Section probs:", pred["section_probs"])
    print("Section set:", pred["section_set"])
    print()

    print("Division probs:", pred["division_probs"])
    print("Division sets:", pred["division_sets"])
    print()

    print("Class probs:", pred["class_probs"])
    print("Class sets:", pred["class_sets"])
    print()
    print("Final output:", pred["final_output"])   
    print()

    # How good is the prediction
    print("Evaluation:")     
    true = (ts in pred["section_set"])
    true_lvl_1.append(true)
    print("Right class in Level 1?", true)
    print("Level 1 Empty?", (len(pred["section_set"])==0))
    fp = not(ts in pred["section_set"]) and not(len(pred["section_set"])==0)
    false_positives_lvl_1.append(fp)
    print("False Positive: ", fp)
    print()

    divisions_list = [x for k, v in pred["division_sets"].items() for x in v]
    true = (td in divisions_list)
    true_lvl_2.append(true)
    #print("Right class in Level 2 or Level 2 empty? ", (td in divisions_list) or (len(pred["division_sets"])==0))
    print("Right class in Level 2?", true)
    print("Level 2 Empty?", (len(pred["division_sets"])==0))
    fp = not(td in divisions_list) and not(len(pred["division_sets"])==0)
    false_positives_lvl_2.append(fp)
    print("False Positive: ", fp)
    print()

    class_list = [x for k, v in pred["class_sets"].items() for x in v]
    true = (tc in class_list)
    true_lvl_3.append(true)
    #print("Right class in Level 3 or Level 3 empty? ", (tc in class_list) or (len(pred["class_sets"])==0))
    print("Right class in Level 3?", true)
    print("Level 3 Empty?", (len(pred["class_sets"])==0))
    fp = not(tc in class_list) and not(len(pred["class_sets"])==0)
    false_positives_lvl_3.append(fp)
    print("False Positive: ", fp)
    print()

RAPS scores:
0.0035687592889069946 K 1.1000000000000003 0.9002629947582977 False
0.9688819216143889 A 0.9688819216143889 0.9002629947582977 False
0.02754931909670421 C 1.0464312407110932 0.9002629947582977 False
RAPS scores:
0.0018423829118975044 2 1.1 0.88983018984842 False
0.9916753971843973 3 0.9916753971843973 0.88983018984842 False
0.006482219903705083 1 1.0481576170881024 0.88983018984842 False
RAPS scores:
0.08304982546389057 03.1 1.05 0.9458850677529222 False
0.9169501745361094 03.2 0.9169501745361094 0.9458850677529222 True

==================================================
Description 1:
  ABOuT BAkkAfrOST  ## About Bakkafrost  <!-- image -->  Key  Resources  ## Our Value Chain  BAKKAFROST: Established in 1968.  Location: Faroe Islands Headquarters, Glyvrar, Eysturoy  Production and business-to-business sale: salmon, packaging, biogas, fish meal, oil and feed.  Longest integrated value chain in the industry: Fully owned subsidiaries: FOF segment Havsbrún, Fuglafjørður (production of fishmeal, -oil and -feed); Bakkafrost Scotland (Scottish Salmon producer, processing, and sales); Bakkafrost UK, Grimsby (salmon import and sales); Bakkafrost USA, New Jersey (seafood import, processing and sales); FÖRKA, Tórshavn (biogas plant) Svínoyar Rognkelsisstøð (cleaner fish farming), FarCargo (airfreight) and subsidiary Munkebo Seafood, Denmark (canned seafood processing and sales).  Listed:  Oslo Børs with the ticker symbol BAKKA  Employees:  1,078 FTEs across the group. 1,180 FTEs in Faroe Islands, USA, UK, DK and FR and 598 FTEs in Scotland  Markets served: Western Europe (67%), North America (18%), Asia (9%), Eastern Europe (5%) and rest of the world (1%)  - We finance our operations through a combination of cash flow, debt and shareholder capital - We rely on the expertise and competency of our workforce, working to our values to develop and grow the business - We depend on natural resources to produce world class quality salmon - We ensure that we have state of the art production facilities and service vessels to optimise efficiency - We have built a strong reputation for high quality salmon and feed to develop our increasing market share - We are committed to building relationships with our stakeholders to ensure transparency and full appreciation of our shared values.  FISHMEAL  <!-- image -->  Fishmeal, oil and feed  FISH OIL  <!-- image -->  FISH FEED  <!-- image -->  Smolt  HATCHERIES  <!-- image -->  Breeding  BROODSTOCK  <!-- image -->  Biogas  BIOGAS  <!-- image -->  Sales/Marketing  SALES &amp; LOGISTICS  <!-- image -->  Sea water  <!-- image -->  FARMING  FSV  <!-- image -->  HARVESTING  <!-- image -->  Processing  <!-- image -->  PROCESSING  <!-- image -->  PACKAGING  | Output                    | 164,000t of fishmeal annual capacity                                | 110,000t of fish oil annual capacity   | 255,000t of fish feed annual capacity   | Increasing part of roe from our own strains   | 20 million 500 g smolts and 11 million 250 g smolts annual capacity in 2023   | 90-100,000t of waste conversion annual capacity   | 57 marine sites in operation across areas in Faroe Islands and Scotland                                                                                                                                | 8 farming service vessels, including 5 live fish carriers                                                                                                                                              | 90,603t of salmon harvested in 2022                   | 140,000t primary and 40,000t secondary annual capacity.   | 80,000t of salmon, annual packaging capacity   | 7,130 DKK billion operating revenues Sales to 30+ countries   | |---------------------------|---------------------------------------------------------------------|----------------------------------------|-----------------------------------------|-----------------------------------------------|-------------------------------------------------------------------------------|---------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------|---------------------------------------------------------------| | The Bakkafrost Difference | High nutritional content using local marine sources, no ethoxyquin, | recepies and sustainable               | non-GMO, ingredients.                   | Increased focus                               | on biosecurity Natural farming efficient circular                             | no use of growth                                  | environment, solutions, hormones Modern fleet of farming service vessels staffed by people with centuries of sea-faring know-how provide fast and gentle transportation from marine site to production | environment, solutions, hormones Modern fleet of farming service vessels staffed by people with centuries of sea-faring know-how provide fast and gentle transportation from marine site to production | Efficient processing capabilities product development | Efficient processing capabilities product development     | and                                            | Extensive market reach                                        |  ## Value Created  - We create value for our shareholders, the Faroe Islands and Scotland through taxes and direct and indirect employment - We meet growing global demand for protein with healthy and efficiently production of salmon - We aim to contribute towards improved infrastructure in our areas of operation - We collaborate with the broader aquaculture industry to promote responsible and sustainable practice (Please see our Annual Report at www.bakkafrost.com for our consolidated financial statements.)
True: section=A, division=3, class=03.2
Section probs: {'K': 0.0035687592889069946, 'A': 0.9688819216143889, 'C': 0.02754931909670421}
Section set: ['A']

Division probs: {'A': {'2': 0.0018423829118975048, '3': 0.9916753971843976, '1': 0.006482219903705085}}
Division sets: {'A': ['3']}

Class probs: {'3': {'03.1': 0.08304982546389057, '03.2': 0.9169501745361094}}
Class sets: {'3': ['03.2']}

Final output: {'type': 'class_level', 'codes': ['03.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
0.006909554483136882 K 1.1 0.9002629947582977 False
0.02640472639291451 A 1.043090445516863 0.9002629947582977 False
0.9666857191239486 C 0.9666857191239486 0.9002629947582977 False
RAPS scores:
0.11637843109986312 26 1.0304226394181728 0.8639848202430107 False
0.0047044448075514445 23 1.2 0.8639848202430107 False
0.8640442083183097 21 0.8640442083183097 0.8639848202430107 False
0.0055746151817799555 27 1.1452955551924484 0.8639848202430107 False
0.009298300592495751 10 1.0897209400106687 0.8639848202430107 False
RAPS scores:
0.02792587566793755 21.1 1.05 0.9724085167367025 False
0.9720741243320625 21.2 0.9720741243320625 0.9724085167367025 True

==================================================
Description 132:
  ## 4.B. BUSINESS OVERVIEW  ## Overview  Alcon is the global leader in eye care with $8.7 billion in net sales during the year ended December 31, 2022. We research, develop, manufacture, distribute and sell a full suite of eye care products within two key businesses: Surgical and Vision Care. Based on sales for the year ended December 31, 2022, we are the number one company by global market share in the ophthalmic surgical market and in the vision care market. We employ over 25,000 associates from more than 100 nationalities, operating in 60 countries and serving consumers and patients in over 140 countries. We believe our market leading  position  and  global  footprint  allow  us  to  benefit  from  economies  of  scale,  maximize  the  potential  of  our commercialized products and pipeline and will permit us to effectively grow the market and expand into new product categories.  Our Surgical business is focused on ophthalmic products for cataract surgery, vitreoretinal surgery, refractive laser surgery and glaucoma surgery. Our broad surgical portfolio includes implantables, consumables and surgical equipment required for these procedures and supports the end-to-end needs of the ophthalmic surgeon. Our Vision Care business comprises daily disposable, reusable and color-enhancing contact lenses and a comprehensive portfolio of ocular health products, including products for dry eye, ocular allergies, glaucoma, and contact lens care, as well as ocular vitamins and redness relievers.  Alongside  our  world-class  products,  Alcon  provides  best-in-class  service,  training,  education  and  technical support for our customers.  Our Surgical and Vision Care businesses are complementary and benefit from synergies in research and development, manufacturing, distribution  and  consumer  awareness  and  education.  This  allows  us  to  position  ourselves  as  a  trusted partner  for  eye  care  products  across  the  continuum  of  care  from  retail  consumer,  to  optometry,  to  surgical ophthalmology. For example, in research and development, we can apply our expertise in material and surface chemistry to  develop  innovative  next-generation  products  for  both  our  IOL  and  contact  lens  product  lines.  Similarly,  our  global commercial  footprint  and  expertise  as  a  global  organization  provide  us  with  product  development,  manufacturing, distribution and commercial promotion and marketing knowledge that can be applied to both of our businesses.  We are dedicated to providing innovative products that enhance quality of life by helping people see brilliantly. Our strong foundation is based on our longstanding success as a trusted brand, our legacy of industry firsts and advancements, our leading  positions  in  the  markets  in  which  we  compete  and  our  continued  commitment  to  substantial  investment  in innovation.  With  more  than  75  years  of  history  in  the  ophthalmic  industry,  we  believe  the  Alcon  brand  name  is synonymous with innovation, quality, service and leadership among eye care professionals worldwide.  ## Our Markets  ## Overview  We currently operate in the global ophthalmic surgical and vision care markets, which are large, dynamic and growing. As the world population grows and ages, the need for quality eye care is expanding and evolving, and we estimate that the size of the eye care market in which we operate is approximately $32 billion and is projected to grow mid-single digits per year from 2022 to 2027.  Although it is estimated that 90% of all visual impairments are currently preventable, treatable or curable, we operate in markets  that  have  substantial  unmet  medical  and  consumer  needs.  For  example,  based  on  market  research,  it  is estimated  that  there  are  currently  65  million  people  with  moderate  to  severe  vision  impairment  due  to  cataracts, 1.8  billion  who  suffer  from  presbyopia,  153  million  with  uncorrected  refractive  errors,  146  million  with  diabetic retinopathy, 103 million living with glaucoma and approximately 1.4 billion who suffer from symptoms of dry eye, among other unaddressed ocular health conditions. In addition, there are 1 billion people living with some form of unaddressed visual impairment. Below is a brief description of these ocular disorders.
True: section=C, division=26, class=26.6
Section probs: {'K': 0.006909554483136882, 'A': 0.02640472639291451, 'C': 0.9666857191239486}
Section set: ['C']

Division probs: {'C': {'26': 0.11637843109986315, '23': 0.004704444807551445, '21': 0.86404420831831, '27': 0.005574615181779956, '10': 0.009298300592495753}}
Division sets: {'C': ['21']}

Class probs: {'21': {'21.1': 0.02792587566793755, '21.2': 0.9720741243320625}}
Class sets: {'21': ['21.2']}

Final output: {'type': 'class_level', 'codes': ['21.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True

RAPS scores:
0.010474396548403259 K 1.0999999999999999 0.9002629947582977 False
0.05026571085661379 A 1.0395256034515967 0.9002629947582977 False
0.9392598925949829 C 0.9392598925949829 0.9002629947582977 False
RAPS scores:
0.004075519559732614 26 1.046438187445088 0.8639848202430107 False
0.0004998548654202535 23 1.2 0.8639848202430107 False
0.9923626678853555 21 0.9923626678853555 0.8639848202430107 False
0.0005082973913376346 27 1.1495001451345797 0.8639848202430107 False
0.0025536602981539045 10 1.098991847743242 0.8639848202430107 False
RAPS scores:
0.027885307969110214 21.1 1.05 0.9724085167367025 False
0.9721146920308897 21.2 0.9721146920308897 0.9724085167367025 True

==================================================
Description 125:
  Risk Factors  Corporate Governance  Share Capital  ## 1 Presentation of the Group  ## 1.1 Company Profile  ## 1.1.1 General  We are a commercial-stage, global, fully-integrated biopharma company developing a deep pipeline of differentiated therapies for the treatment of severe autoimmune diseases. By combining our suite of antibody engineering technologies with the disease biology expertise of our research collaborators, we aim to translate immunology breakthroughs into a pipeline of novel antibody-based medicines through our discovery engine, the IIP . We have a particular focus on rare, autoimmune diseases that fit into our growing commercial franchises focused on neurology, hematology and rheumatology, dermatology and nephrology. Through the building and use of commercial franchises, we plan to leverage capabilities and an organizational footprint for subsequent potential launches across our broad immunology pipeline. On December 17, 2021, the FDA approved efgartigimod in the U.S., which is marketed as VYVGART (efgartigimod alfa-fcab), for the treatment of gMG in adult patients who are AChR-AB+. On January 20, 2022, MHLW approved VYVGART (efgartigimod alfa) for the treatment of adult patients with gMG who do not have sufficient response to steroids or non-steroidal ISTs. On August 11, 2022 the EU Commission granted marketing authorization for VYVGART (efgartigimod alfa-fcab) as an add-on to standard therapy for the treatment of adult patients with gMG who are AChR-AB+ in all 27 EU Member States, Iceland, Norway and Liechtenstein (collectively, with the U.S. and Japan, the VYVGART Approved Countries ). With these regulatory milestones, VYVGART is the first-and-only approved FcRn blocker in the U.S., Europe and Japan.  argenx was founded on April 25, 2008 and is registered with the trade register of the Dutch Chamber of Commerce under number 24435214. Our registered office is at Laarderhoogtweg 25, 1101 EB Amsterdam, the Netherlands. Our commercial name is 'argenx' and, since April 26, 2017, our corporate name is 'argenx SE'.  Our ordinary shares are listed on the regulated market of Euronext Brussels in Belgium under ISIN NL0010832176 under the symbol 'ARGX' since 2014 and our ADSs, each representing one ordinary share in argenx (or a right to receive such share), are listed on the Nasdaq Global Select Market ( Nasdaq ) under the symbol 'ARGX' since 2017.  Financial Statements
True: section=C, division=21, class=21.1
Section probs: {'K': 0.010474396548403259, 'A': 0.05026571085661379, 'C': 0.9392598925949829}
Section set: ['C']

Division probs: {'C': {'26': 0.004075519559732613, '23': 0.0004998548654202534, '21': 0.9923626678853554, '27': 0.0005082973913376345, '10': 0.002553660298153904}}
Division sets: {'C': ['21']}

Class probs: {'21': {'21.1': 0.027885307969110214, '21.2': 0.9721146920308897}}
Class sets: {'21': ['21.2']}

Final output: {'type': 'class_level', 'codes': ['21.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True

RAPS scores:
0.006770641502595055 K 1.1 0.9002629947582977 False
0.08616001468568193 A 1.0432293584974048 0.9002629947582977 False
0.907069343811723 C 0.907069343811723 0.9002629947582977 False
RAPS scores:
0.004175829458014262 26 1.0463760391818555 0.8639848202430107 False
0.0005098282669552569 23 1.2 0.8639848202430107 False
0.9922002097238412 21 0.9922002097238412 0.8639848202430107 False
0.0005200743984719991 27 1.1494901717330448 0.8639848202430107 False
0.0025940581527172817 10 1.0989700973345728 0.8639848202430107 False
RAPS scores:
0.028122514139811573 21.1 1.05 0.9724085167367025 False
0.9718774858601884 21.2 0.9718774858601884 0.9724085167367025 True

==================================================
Description 35:
  ## Create novel therapies and vaccines  Help people with chronic diseases live better, healthier lives. Redefine cancer care. Pioneer treatments for rare diseases.  Make patients partners in their own treatment.  <!-- image -->  See the full story at www.astrazeneca.com/ our-therapy-areas.html.  Transform the lives of  ## billions of people  Give more and more of us access to healthcare. Inspire us to do incredible things.  <!-- image -->  See the full story at www.astrazeneca.com/ sustainability.  Make people, societies and  <!-- image -->  <!-- image -->  ## the planet healthier  Make healthcare systems more sustainable and resilient. Lead the way to a low-carbon world.  <!-- image -->  See the full story at www.astrazeneca.com/ sustainability.  <!-- image -->  <!-- image -->  Science can…  Scan the QR code to see our film, 'Science can…'  <!-- image -->  <!-- image -->
True: section=C, division=21, class=21.2
Section probs: {'K': 0.006770641502595055, 'A': 0.08616001468568193, 'C': 0.907069343811723}
Section set: ['C']

Division probs: {'C': {'26': 0.004175829458014262, '23': 0.0005098282669552569, '21': 0.9922002097238412, '27': 0.0005200743984719991, '10': 0.0025940581527172817}}
Division sets: {'C': ['21']}

Class probs: {'21': {'21.1': 0.028122514139811573, '21.2': 0.9718774858601884}}
Class sets: {'21': ['21.2']}

Final output: {'type': 'class_level', 'codes': ['21.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False

RAPS scores:
0.005160514036038727 K 1.0999999999999999 0.9002629947582977 False
0.029168981436198952 A 1.0448394859639611 0.9002629947582977 False
0.9656705045277623 C 0.9656705045277623 0.9002629947582977 False
RAPS scores:
0.003911245195177564 26 1.0464207756265607 0.8639848202430107 False
0.0004928955414347137 23 1.2 0.8639848202430107 False
0.9925095304313831 21 0.9925095304313831 0.8639848202430107 False
0.0004972432865337249 27 1.1495071044585652 0.8639848202430107 False
0.0025890855454707463 10 1.0990098611720316 0.8639848202430107 False
RAPS scores:
0.027685598509634656 21.1 1.05 0.9724085167367025 False
0.9723144014903654 21.2 0.9723144014903654 0.9724085167367025 True

==================================================
Description 76:

In [ ]:
print("false_positives_lvl_1: ", np.mean(false_positives_lvl_1))
print("false_positives_lvl_2: ", np.mean(false_positives_lvl_2))
print("false_positives_lvl_3: ", np.mean(false_positives_lvl_3))
print("true_lvl_1: ", np.mean(true_lvl_1))
print("true_lvl_2: ", np.mean(true_lvl_2))
print("true_lvl_3: ", np.mean(true_lvl_3))

false_positives_lvl_1:  0.0
false_positives_lvl_2:  0.3333333333333333
false_positives_lvl_3:  0.4
true_lvl_1:  1.0
true_lvl_2:  0.6666666666666666
true_lvl_3:  0.4666666666666667

### With llm summaries

Please summarize the business model in 4 sentences:

In [ ]:
description_page_path_llm_summary = "data/datasets/stoxx_600/company_descriptions_txt_1/"
# from_ = os.path.join(description_page_path,row["Report"].replace("pdf", "txt"))
# to_ = os.path.join(description_page_path_to,row["Report"].replace("pdf", "txt"))

# import shutil

# for i, row in nace_classes.iterrows():
#     from_ = os.path.join(description_page_path,row["Report"].replace("pdf", "txt"))
#     to_ = os.path.join(description_page_path_llm_summary,row["Report"].replace("pdf", "txt"))
#     shutil.copyfile(from_, to_)

In [ ]:
nace_classes

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page,NACE_lvl_3
1,Bakkafrost P/F,BAKKA-NO,BAKKA-NO,929.503079,937.862170,973.053513491168,3.21,A,Bakkafrost PF2.pdf,4,03.2
52,Merck KGaA,MRK-DE,MRK-DE,22232.000000,20993.000000,21156,21.20,C,Merck KGaA2.pdf,4,21.2
129,COMET Holding AG,COTN-CH,COTN-CH,584.204846,409.093151,467.557574915886,26.60,C,COMET Holding AG1.pdf,21,26.6
132,Alcon AG,ALC-CH,ALC-CH,8294.208061,8745.595513,9162.50793328229,26.60,C,Alcon AG1.pdf,47,26.6
125,argenx SE,ARGX-BE,ARGX-BE,390.824013,1134.306078,2024.8217775747,21.10,C,argenx SE1.pdf,28,21.1
76,Bavarian Nordic A/S,BAVA-DK,BAVA-DK,423.526567,947.164439,765.63798368454,21.20,C,Bavarian Nordic AS1.pdf,6,21.2
35,AstraZeneca PLC,AZN-GB,AZN-GB,42199.888931,42373.821732,49989.333053702,21.20,C,AstraZeneca PLC1.pdf,5,21.2
123,DiaSorin S.p.A.,DIA-IT,DIA-IT,1361.138000,1148.210000,NaN,21.20,C,DiaSorin S.p.A.1.pdf,11,21.2
291,Bellway p.l.c.,BWY-GB,BWY-GB,4177.814981,3915.032717,2775.47977695465,41.20,F,Bellway p.l.c.1.pdf,18,41.2
296,Acciona SA,ANA-ES,ANA-ES,11195.000000,17021.000000,19190,41.20,F,Acciona SA2.pdf,7,41.2
297,Ackermans & van Haaren NV,ACKB-BE,ACKB-BE,4401.419000,5221.553000,6043.335,42.99,F,Ackermans & van Haaren NV1.pdf,7,42.9
292,Balfour Beatty plc,BBY-GB,BBY-GB,8941.465767,9190.241368,NaN,42.11,F,Balfour Beatty plc1.pdf,2,42.1
428,Bank of Ireland Group Plc,BIRG-IE,BIRG-IE,6074.000000,8952.000000,9853,64.19,K,Bank of Ireland Group Plc1.pdf,7,64.1
473,Banque Cantonale Vaudoise,BCVN-CH,BCVN-CH,1179.079691,1643.462332,1745.73023593426,64.19,K,Banque Cantonale Vaudoise1.pdf,12,64.1
475,Allfunds Group plc,ALLFG-NL,ALLFG-NL,493.950000,548.153000,632.100000000053,66.11,K,Allfunds Group plc1.pdf,6,66.1
469,Bridgepoint Group Plc,BPT-GB,BPT-GB,367.667822,366.781809,NaN,66.30,K,Bridgepoint Group Plc1.pdf,4,66.3
460,Cembra Money Bank AG,CMBN-CH,CMBN-CH,536.239665,607.890645,688.319492304325,64.92,K,Cembra Money Bank AG1.pdf,5,64.9
439,Deutsche Bank Aktiengesellschaft,DBK-DE,DBK-DE,40533.000000,60635.000000,30092,66.12,K,Deutsche Bank Aktiengesellschaft1.pdf,6,66.1
433,Avanza Bank Holding AB,AZA-SE,AZA-SE,324.377745,410.819403,478.646065026522,66.12,K,Avanza Bank Holding AB1.pdf,4,66.1
583,Ashtead Group plc,AHT-GB,AHT-GB,9287.242816,10033.160119,NaN,77.32,N,Ashtead Group plc1.pdf,2,77.3

In [ ]:
false_positives_lvl_1 = []
false_positives_lvl_2 = []
false_positives_lvl_3 = []
true_lvl_1 = []
true_lvl_2 = []
true_lvl_3 = []

for i, row in nace_classes.iterrows():
#for i, row in nace_classes.loc[460:460].iterrows():
#for i in range(len(X_lvl_3_test)):
    try: 
        with open(os.path.join(description_page_path_llm_summary,row["Report"].replace("pdf", "txt")), "r") as f: 
            desc = f.read()
    except FileNotFoundError:
        print("File not found:", os.path.join(description_page_path_llm_summary,row["Report"].replace("pdf", "txt")))
        continue

    # ts, td, tc = y_sec_cal[i], y_div_cal[i], y_cls_cal[i]

    tc = row["NACE_lvl_3"]
    td = [div for div, cls_ in classes.items() if tc in cls_][0]
    ts = [sec for sec, divs in divisions.items() if td in divs][0]
    
    print("\n==================================================")
    print(f"Description {i}:\n ", desc.replace("\n", " "))
    
    pred = predict_full_one(desc, max_leaf_size=3, temperature=1)


    print(f"True: section={ts}, division={td}, class={tc}")
    print("Section probs:", pred["section_probs"])
    print("Section set:", pred["section_set"])
    print()

    print("Division probs:", pred["division_probs"])
    print("Division sets:", pred["division_sets"])
    print()

    print("Class probs:", pred["class_probs"])
    print("Class sets:", pred["class_sets"])
    print()
    print("Final output:", pred["final_output"])   
    print()

    # How good is the prediction
    print("Evaluation:")     
    true = (ts in pred["section_set"])
    true_lvl_1.append(true)
    print("Right class in Level 1?", true)
    print("Level 1 Empty?", (len(pred["section_set"])==0))
    fp = not(ts in pred["section_set"]) and not(len(pred["section_set"])==0)
    false_positives_lvl_1.append(fp)
    print("False Positive: ", fp)
    print()

    divisions_list = [x for k, v in pred["division_sets"].items() for x in v]
    true = (td in divisions_list)
    true_lvl_2.append(true)
    #print("Right class in Level 2 or Level 2 empty? ", (td in divisions_list) or (len(pred["division_sets"])==0))
    print("Right class in Level 2?", true)
    print("Level 2 Empty?", (len(pred["division_sets"])==0))
    fp = not(td in divisions_list) and not(len(pred["division_sets"])==0)
    false_positives_lvl_2.append(fp)
    print("False Positive: ", fp)
    print()

    class_list = [x for k, v in pred["class_sets"].items() for x in v]
    true = (tc in class_list)
    true_lvl_3.append(true)
    #print("Right class in Level 3 or Level 3 empty? ", (tc in class_list) or (len(pred["class_sets"])==0))
    print("Right class in Level 3?", true)
    print("Level 3 Empty?", (len(pred["class_sets"])==0))
    fp = not(tc in class_list) and not(len(pred["class_sets"])==0)
    false_positives_lvl_3.append(fp)
    print("False Positive: ", fp)
    print()

==================================================
Description 1:
  Bakkafrost is a vertically integrated salmon farming company headquartered in the Faroe Islands, controlling the entire value chain from fishmeal, feed, and smolt production to farming, harvesting, processing, packaging, and global sales. It produces and sells high-quality salmon and related products through fully owned subsidiaries across Europe, North America, and Asia, serving mainly Western Europe and North America. The company leverages state-of-the-art facilities, a specialized fleet, and in-house biogas and by-product processing to maximize efficiency, sustainability, and biosecurity. Value is created through premium salmon production, strong market reach, sustainable use of natural resources, and long-term returns for shareholders and local communities.
True: section=A, division=3, class=03.2
Section probs: {'J': 0.0011982489136096667, 'A': 0.9887178991623901, 'K': 0.006674764116217659, 'C': 0.0011072818459238786, 'F': 0.0008454760111492288, 'N': 0.001456329950709738}
Section set: ['A']

Division probs: {'A': {'2': 0.0018276798035139854, '3': 0.991691272213505, '1': 0.006481047982981265}}
Division sets: {'A': ['3']}

Class probs: {'3': {'03.1': 0.08301209563358729, '03.2': 0.9169879043664126}}
Class sets: {'3': ['03.2']}

Final output: {'type': 'class_level', 'codes': ['03.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False


==================================================
Description 52:
  Merck is a science and technology company that operates three diversified business sectors: Life Science, Healthcare, and Electronics. In Life Science, it supplies tools, chemicals, and consumables to support scientific research and biopharmaceutical manufacturing, supported by a broad product portfolio and a leading e-commerce platform. In Healthcare, Merck develops and commercializes innovative therapies for serious diseases, treating tens of millions of patients worldwide, while in Electronics it provides semiconductor and display materials that underpin digital technologies used in everyday devices. By leveraging synergies across these sectors and a long-term, sustainability-driven approach, Merck aims to enable scientific progress and technological innovation that improve human life.
True: section=C, division=21, class=21.2
Section probs: {'J': 0.009845635852533995, 'A': 0.0019333742900233904, 'K': 0.010009920903063352, 'C': 0.6637440018469862, 'F': 0.00544929851122787, 'N': 0.30901776859616514}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.33625599815301377}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False


==================================================
Description 129:
  The Comet Group’s business model is centered on supplying advanced technologies and system solutions primarily to the semiconductor and electronics markets. It operates three businesses built on two core technologies—radio-frequency (RF) power and X-ray—covering plasma control technologies, X-ray modules, and X-ray systems. Comet generates value by providing high-precision components (e.g., RF generators, vacuum capacitors, X-ray tubes) as well as integrated systems and software for industrial and R&D applications. Its offering is complemented by customized services, including machine-learning-based analytics, enabling customers to optimize production quality, reliability, and efficiency.
True: section=C, division=26, class=26.6
Section probs: {'J': 0.010965441655370181, 'A': 0.00086810939283208, 'K': 0.0012155986478822897, 'C': 0.9607096132146966, 'F': 0.004885442906373717, 'N': 0.02135579418284526}
Section set: ['C']

Division probs: {'C': {'26': 0.9789082422934781, '23': 0.012147903166064112, '21': 0.0038982631623847683, '27': 0.003402661825133159, '10': 0.0016429295529398415}}
Division sets: {'C': ['26']}

Class probs: {'26': {'26.1': 0.9054792917326363, '26.6': 0.0945207082673636}}
Class sets: {'26': ['26.1']}

Final output: {'type': 'class_level', 'codes': ['26.1']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True


==================================================
Description 132:
  Alcon is a global leader in eye care that researches, develops, manufactures, and sells a comprehensive portfolio of products across two complementary businesses: Surgical and Vision Care. Its Surgical segment provides implantables, consumables, and equipment for cataract, vitreoretinal, refractive, and glaucoma surgeries, while Vision Care offers contact lenses and a broad range of ocular health products. The company leverages its global scale, strong brand, and integrated capabilities in R&D, manufacturing, and distribution to serve customers across the full continuum of eye care, from consumers to surgeons. Alcon’s business model is driven by sustained investment in innovation, market leadership, and synergies between its two segments to address growing global demand for eye care solutions.
True: section=C, division=26, class=26.6
Section probs: {'J': 0.000992288150891739, 'A': 0.002646901774874771, 'K': 0.4088057275562921, 'C': 0.0048232611065732725, 'F': 0.0017103178293789816, 'N': 0.5810215035819891}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.4189784964180109}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False


==================================================
Description 125:
  argenx is a global, fully integrated biopharmaceutical company that discovers, develops, and commercializes antibody-based therapies for severe and rare autoimmune diseases. Its business model combines proprietary antibody engineering technologies with deep immunology expertise to build a differentiated pipeline, particularly across neurology, hematology, rheumatology, dermatology, and nephrology. The company generates value by translating research breakthroughs into approved medicines, exemplified by VYVGART, the first approved FcRn blocker in the U.S., Europe, and Japan, which anchors its initial commercial franchise. By establishing strong commercial platforms and global regulatory capabilities, argenx aims to efficiently launch additional products from its broader immunology pipeline and scale long-term growth.
True: section=C, division=21, class=21.1
Section probs: {'J': 0.0014333442895040575, 'A': 0.013622667423878647, 'K': 0.7471742538241033, 'C': 0.004669677464721744, 'F': 0.0021645077044348364, 'N': 0.23093554929335736}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.2528257461758967}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False


==================================================
Description 76:
  Bavarian Nordic is a fully integrated vaccines company that develops, manufactures, and commercializes life-saving vaccines through in-house R&D, end-to-end manufacturing, and global commercial operations. Its business model combines proprietary products with leading market positions (e.g., rabies, TBE, Ebola, smallpox, Mpox) and in-licensed vaccines that expand its portfolio and revenue base. The company distributes vaccines via its own salesforce in strategic markets, ensuring control over commercialization and quality standards. Growth is driven by a late-stage pipeline targeting large unmet medical needs, including RSV and COVID-19.
True: section=C, division=21, class=21.2
Section probs: {'J': 0.020927391652081732, 'A': 0.2297815805121269, 'K': 0.49706986352503085, 'C': 0.05303555473439042, 'F': 0.017775059099903644, 'N': 0.18141055047646654}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.5029301364749692}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False


==================================================
Description 35:
  The company develops innovative therapies and vaccines to improve outcomes for people with chronic, cancer, and rare diseases. It focuses on patient-centric care by empowering patients to actively participate in their own treatment. By expanding access to healthcare globally, it aims to positively impact billions of people. At the same time, it integrates sustainability into its business by strengthening healthcare systems and contributing to a low-carbon, healthier planet.
True: section=C, division=21, class=21.2
Section probs: {'J': 0.0004443492188330985, 'A': 0.007784970042220478, 'K': 0.8897560218990958, 'C': 0.0013644145354721592, 'F': 0.0008990896736598246, 'N': 0.09975115463071872}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.11024397810090425}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False


==================================================
Description 123:
  The company develops and commercializes advanced diagnostic solutions by translating unmet healthcare needs into reliable laboratory, molecular, and point-of-care tests through continuous investment in research and technology. Its business model is built around proprietary automated platforms, a broad specialty test menu, and rapid development capabilities that support laboratories, clinicians, and decentralized care settings. Strategic partnerships and licensed technologies complement internal R&D to accelerate innovation and address emerging medical challenges such as infectious diseases and antimicrobial resistance. Value creation is driven by timely, high-quality diagnostics, a strong installed base, and a sustainability-oriented approach centered on patient health, scientific excellence, and long-term stakeholder impact.
True: section=C, division=21, class=21.2
Section probs: {'J': 0.001424577176201529, 'A': 0.0036129352011415386, 'K': 0.3263831507370233, 'C': 0.00848489424856517, 'F': 0.002350209507440849, 'N': 0.6577442331296275}
Section set: []

Division probs: {}
Division sets: {}

Class probs: {}
Class sets: {}

Final output: {'type': 'reject', 'reason': 'low section confidence', 'reject_score': 0.3422557668703725}

Evaluation:
Right class in Level 1? False
Level 1 Empty? True
False Positive:  False

Right class in Level 2? False
Level 2 Empty? True
False Positive:  False

Right class in Level 3? False
Level 3 Empty? True
False Positive:  False

File not found: data/datasets/stoxx_600/company_descriptions_txt_1/Bellway p.l.c.1.txt
File not found: data/datasets/stoxx_600/company_descriptions_txt_1/Acciona SA2.txt
File not found: data/datasets/stoxx_600/company_descriptions_txt_1/Ackermans & van Haaren NV1.txt
File not found: data/datasets/stoxx_600/company_descriptions_txt_1/Balfour Beatty plc1.txt

==================================================
Description 428:
  The Group’s business model underwent a step change in 2022, driven by prior technology investments and the transformative acquisitions of Davy and KBC portfolios. It capitalized on a structural shift in the Irish market to rapidly acquire customers, significantly increasing current accounts and opening around 450,000 new accounts across products. The acquisition of Davy expanded assets under management to approximately €39 billion, strengthening capabilities across wealth management, investments, and capital markets for mass-market to high-net-worth clients. The KBC mortgage and deposit acquisition materially increased mortgage lending stock, enhancing scale and profitability while remaining financially attractive despite a manageable CET1 impact.
True: section=K, division=64, class=64.1
Section probs: {'J': 0.00019161148713168835, 'A': 0.007204424275600478, 'K': 0.9661308071709506, 'C': 0.0005320673788581649, 'F': 0.0004171641164346532, 'N': 0.025523925571024637}
Section set: ['K']

Division probs: {'K': {'64': 0.05924384058134831, '66': 0.9407561594186518}}
Division sets: {'K': ['66']}

Class probs: {'66': {'66.3': 0.10474967755978429, '66.1': 0.821630644906453, '66.2': 0.07361967753376268}}
Class sets: {'66': ['66.3', '66.1']}

Final output: {'type': 'class_level', 'codes': ['66.1', '66.3']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True


==================================================
Description 473:
  BCV is a publicly owned universal bank majority held by the Canton of Vaud, providing a comprehensive range of banking and financial services to retail, private, corporate, and institutional clients. Its core business is organized around four divisions—Retail Banking, Private Banking, Corporate Banking, and Asset Management & Trading—leveraging a dense local branch network and specialized subsidiaries. The bank’s mandate emphasizes strong regional anchoring, notably through financing households, businesses, and public-sector entities in Vaud, including mortgage lending. BCV aims to generate sustainable value for shareholders and clients while supporting the economic, social, and environmental development of the Canton of Vaud.
True: section=K, division=64, class=64.1
Section probs: {'J': 0.00019931627254062044, 'A': 0.007670465232085744, 'K': 0.9666248537617267, 'C': 0.0005436660391944797, 'F': 0.00042956940605246426, 'N': 0.02453212928839994}
Section set: ['K']

Division probs: {'K': {'64': 0.07177581894407875, '66': 0.9282241810559213}}
Division sets: {'K': ['66']}

Class probs: {'66': {'66.3': 0.07959249060426916, '66.1': 0.8639308510081859, '66.2': 0.05647665838754486}}
Class sets: {'66': ['66.3', '66.1']}

Final output: {'type': 'class_level', 'codes': ['66.1', '66.3']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True


==================================================
Description 475:
  Allfunds is a wealthtech company that operates a digital platform connecting fund houses and distributors across the entire fund distribution value chain. It generates value by providing centralized trading and execution, data and analytics, reporting, portfolio and compliance tools, and technology solutions within a single secure ecosystem. The company also offers investment outsourcing, sub-advisory services, and ESG solutions to banks, wealth managers, and institutional investors to help streamline operations and support sustainable investing. In addition, Allfunds develops advanced technologies, including custom software and blockchain solutions, to increase efficiency, transparency, and scalability in fund distribution.
True: section=K, division=66, class=66.1
Section probs: {'J': 0.00020747153206065064, 'A': 0.00785255020814038, 'K': 0.9656769446497735, 'C': 0.000569466884352986, 'F': 0.0004470871126402034, 'N': 0.025246479613032315}
Section set: ['K']

Division probs: {'K': {'64': 0.06432970396488197, '66': 0.9356702960351181}}
Division sets: {'K': ['66']}

Class probs: {'66': {'66.3': 0.935894700660003, '66.1': 0.025976643403758028, '66.2': 0.03812865593623885}}
Class sets: {'66': ['66.3']}

Final output: {'type': 'class_level', 'codes': ['66.3']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? False
Level 3 Empty? False
False Positive:  True


==================================================
Description 469:
  Bridgepoint is an international alternative asset manager that invests in growth-oriented businesses, primarily with a European focus. Its business model centers on providing capital and strategic support to help portfolio companies scale and enhance their long-term value. The firm operates globally, with offices in Europe, the United States, and China, enabling access to international opportunities and expertise. Value creation is driven through active ownership, operational improvement, and long-term partnership with management teams.
True: section=K, division=66, class=66.3
Section probs: {'J': 0.000186054790124185, 'A': 0.006278041925535278, 'K': 0.9642850873817946, 'C': 0.000538127027505612, 'F': 0.00041147247742824686, 'N': 0.028301216397612062}
Section set: ['K']

Division probs: {'K': {'64': 0.06310293608934528, '66': 0.9368970639106547}}
Division sets: {'K': ['66']}

Class probs: {'66': {'66.3': 0.9367155012283682, '66.1': 0.02524856848405658, '66.2': 0.03803593028757542}}
Class sets: {'66': ['66.3']}

Final output: {'type': 'class_level', 'codes': ['66.3']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? True
Level 2 Empty? False
False Positive:  False

Right class in Level 3? True
Level 3 Empty? False
False Positive:  False


==================================================
Description 460:
  Cembra is a Swiss consumer finance bank that provides personal loans, auto loans and leasing, credit cards, invoice financing (BNPL), insurance intermediation, and deposit products to retail and institutional customers. It generates revenues primarily from interest income, fees, and commissions by distributing its products through branches, online channels, retail partners, car dealers, and independent intermediaries. The bank leverages strong partner ecosystems and subsidiaries to scale credit cards and BNPL solutions while maintaining a broad, brand-independent offering. Operating nationwide with over one million customers, Cembra positions itself as a stable, regulated, and ESG-oriented provider of consumer financing in Switzerland.
True: section=K, division=64, class=64.9
Section probs: {'J': 0.00020144517269992472, 'A': 0.0077980663786241435, 'K': 0.9665888710491891, 'C': 0.0005480174499045281, 'F': 0.00043277548876722005, 'N': 0.024430824460815133}
Section set: ['K']

Division probs: {'K': {'64': 0.06462380086156812, '66': 0.9353761991384318}}
Division sets: {'K': ['66']}

Class probs: {'66': {'66.3': 0.18953099075643073, '66.1': 0.6057105299053458, '66.2': 0.20475847933822344}}
Class sets: {'66': ['66.1', '66.2']}

Final output: {'type': 'class_level', 'codes': ['66.1', '66.2']}

Evaluation:
Right class in Level 1? True
Level 1 Empty? False
False Positive:  False

Right class in Level 2? False
Level 2 Empty? False
False Positive:  True


In [ ]:
len(false_positives_lvl_1)

15

In [ ]:
# Temperatur bei calibrierugn auf 2 angepasst!

print("False Positives in Level 1: ", np.mean(false_positives_lvl_1))
print("False Positives in Level 2: ", np.mean(false_positives_lvl_2))
print("False Positives in Level 3: ", np.mean(false_positives_lvl_3))
print("True Predictions in Level 1: ", np.mean(true_lvl_1))
print("True Predictions in Level 2: ", np.mean(true_lvl_2))
print("True Predictions in Level 3: ", np.mean(true_lvl_3))

False Positives in Level 1:  0.0
False Positives in Level 2:  0.26666666666666666
False Positives in Level 3:  0.4
True Predictions in Level 1:  1.0
True Predictions in Level 2:  0.7333333333333333
True Predictions in Level 3:  0.4666666666666667

In [ ]:
nace_classes_full
nace_classes_full["NACE_lvl_3"] = nace_classes_full["NACE"].apply(lambda x: NACE_helper.get_all_level(x)[3])
nace_classes_full = nace_classes_full[nace_classes_full["NACE_lvl_3"].apply(lambda x: x in all_classes)]
nace_classes_full

,Name,Symbol,FactSet ID,Revenue - 2022 (in EUR),Revenue - 2023 (in EUR),Revenue - 2024 (in EUR),NACE,NACE_letter,Report,description_page,NACE_lvl_3
483,3i Group plc,III-GB,III-GB,701.210162,1276.962137,NaN,66.30,K,NaN,NaN,66.3
484,ABN AMRO Bank N.V. Depositary receipts,ABN-NL,ABN-NL,10716.000000,19055.000000,20045,64.19,K,NaN,NaN,64.1
478,Abrdn plc,ABDN-GB,ABDN-GB,1790.871634,1836.208616,1782.59705686569,66.30,K,NaN,NaN,66.3
533,Adyen NV,ADYEN-NL,ADYEN-NL,8935.611000,1863.406000,2181.177,66.19,K,NaN,NaN,66.1
512,Aegon Ltd.,AGN-NL,AGN-NL,53773.000000,22883.000000,NaN,66.22,K,NaN,NaN,66.2
...,...,...,...,...,...,...,...,...,...,...,...
77,UCB S.A.,UCB-BE,UCB-BE,5517.000000,5252.000000,6152,21.20,C,UCB S.A.1.pdf,NaN,21.2
455,UniCredit S.p.A.,UCG-IT,UCG-IT,27973.000000,46765.000000,49196,64.19,K,UniCredit S.p.A.3.pdf,NaN,64.1
525,VZ Holding AG,VZN-CH,VZN-CH,419.120738,534.742315,623.70437912786,66.30,K,NaN,NaN,66.3
450,Wendel SE,MF-FR,MF-FR,6745.900000,7127.600000,8063.5,64.99,K,Wendel SE2.pdf,NaN,64.9
246,Zealand Pharma A/S,ZEAL-DK,ZEAL-DK,13.977698,46.005625,8.40500161716342,21.20,C,NaN,NaN,21.2

In [ ]:
df_overview = pd.read_csv("data/datasets/reports_subset_from_full_data_3/reports_subset_from_full_data_3_overview.csv", index_col=0)
df_overview["NACE_lvl_3"] = df_overview["NACE"].apply(lambda x: NACE_helper.get_all_level(x)[3])
df_overview.groupby("NACE_lvl_3").count()

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,NACE,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_Letter,Report
NACE_lvl_3,,,,,,,,,,,,,,,,,,,,,
01.1,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
01.2,2,2,2,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
01.3,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
01.4,11,11,11,10,11,11,9,11,11,11,...,11,11,11,11,11,11,11,11,11,11
01.5,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92.0,17,17,17,16,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
93.1,14,14,14,13,14,14,12,14,14,14,...,14,14,14,14,14,14,14,14,14,14
93.2,17,17,17,16,17,17,16,17,17,17,...,17,17,17,17,17,17,17,17,17,17
95.2,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
96.0,40,40,40,40,40,40,35,40,40,40,...,40,40,40,40,40,40,40,40,40,40