In [1]:
import pandas as pd
import os
import math
import numpy as np
import json
import random
import re
import copy
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from tqdm import tqdm
import datetime

In [2]:
os.chdir('/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis')

In [3]:
%pwd

'/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis'

In [5]:
nace_description_path = "data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv"
nace_descriptions = pd.read_csv(nace_description_path, sep="\t")

In [6]:
def get_zero_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_zero_shot"]

def get_few_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_few_shot"]

def get_system_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["system_prompt"]

In [7]:
user_prompt_topic = """
TASK
For the following business sector, create short descriptions of realistic business models for exisiting companies. 

DEFINITION
{includes} {includes_also}

{excludes}

INSTRUCTION
- Create a list of {num_samples} different realistic explanations of a business model 
- The length should be one sentence
- Pick one or multiple subsections for this business model
- Do not explain what you did or what you used
"""

In [8]:
def generate_topic(
        num_samples: int, 
        includes: str,
        includes_also: str, 
        excludes: str,
        prompt_path: str,  
        temperature: float = 0.4, 
        model: str = "gpt-4o-mini"
): 

    # Initialize LLM
    if model == "gpt-4o-mini":
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=temperature
        )
    elif model == "openai/gpt-oss-120b":
        llm = ChatOllama(
            model=model,
            temperature=temperature, 
            base_url="http://10.80.20.127:11434/"
        )


    prompt = ChatPromptTemplate.from_messages([
        ("system", ""),
        ("human", user_prompt_topic)
    ])

    # Adapt excludes
    if excludes != "": 
        excludes = "Excludes: " + excludes

    # Chain
    chain = prompt | llm

    # inputs
    input = {
        "num_samples": num_samples,
        "includes": includes,
        "includes_also": includes_also,
        "excludes": excludes,
        }

    formatted_prompt = prompt.invoke(input)

    # print("Formatted User Prompt:", formatted_prompt.messages[1].content)

    # Run
    response = chain.invoke(input)

    # print(response.content)

    return formatted_prompt, response.content

In [9]:
def generate_synthetic_data(
        num_samples: int, 
        gold_standard: list, 
        includes: str,
        includes_also: str, 
        excludes: str,
        subsections: list,
        prompt_path: str,  
        temperature: float = 0.4, 
        model: str = "gpt-4o-mini", 
        topic: str = None
): 

    # Initialize LLM
    if model == "gpt-4o-mini":
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=temperature
        )
    elif model == "openai/gpt-oss-120b":
        llm = ChatOllama(
            model=model,
            temperature=temperature, 
            base_url="http://10.80.20.127:11434/"
        )

    # Prompt
    if gold_standard == []: 
        #print("Zero Shot!")
        prompt = ChatPromptTemplate.from_messages([
            ("system", get_system_prompt(prompt_path)),
            ("human", get_zero_shot_user_prompt(prompt_path))
        ])
        gold_standard_str = ""
        
    else: 
        prompt = ChatPromptTemplate.from_messages([
            ("system", get_system_prompt(prompt_path)),
            ("human", get_few_shot_user_prompt(prompt_path))
        ])
        gold_standard_str = ""
        for i, text in enumerate(gold_standard): 
            gold_standard_str += f"Example {i+1}:\n{text}\n\n"
        gold_standard_str = gold_standard_str[:-2]

    # Subsections string
    subsections_str = "\n - " + "\n - ".join(subsections)

    # Adapt excludes
    if excludes != "": 
        excludes = "Excludes: " + excludes

    # Chain
    chain = prompt | llm

    # inputs
    input = {
        "num_samples": num_samples,
        "gold_standard": gold_standard_str,
        "includes": includes,
        "includes_also": includes_also,
        "excludes": excludes,
        "subsections": subsections_str,
        }

    # is topic used? topic in params -> business model must be in user prompt
    if topic is not None:
        if "business_model" not in prompt.input_variables: 
            print("If topic is given, prompt must conatin '{business_model}'")
            return False
        else: 
            if isinstance(topic, list): 
                topic_str = "\n".join([f"{i+1}: {text}" for i, text in enumerate(topic)])
                input["business_model"] = topic_str
            else:
                input["business_model"] = topic

    formatted_prompt = prompt.invoke(input)

    #print("Formatted Prompt:", formatted_prompt)

    # Run
    response = chain.invoke(input)

    #print(response.content)

    return formatted_prompt, response.content

In [10]:
def split_synthetic_data(content: str, num_samples: int): 
    content_list = content.split("\n")
    content_list = [c for c in content_list if c != ""]
    # if len(content_list) != num_samples: 
    #     print("Warning: length of creates examples != num_samples!")
    return content_list

In [11]:
def get_sublevels(nace_class, level): 
    nace_class_temp = nace_class
    nace_id = nace_descriptions[nace_descriptions["CODE"] == nace_class_temp]["ID"].iloc[0]
    nace_class_lvl_2 = []
    nace_class_lvl_3 = []
    nace_class_lvl_4 = []

    for _, row in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id].iterrows(): 
        nace_id_temp = row["ID"]
        nace_class_lvl_2.append(f'{row["NAME"]}')
        for _, row_2 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp].iterrows(): 
            nace_id_temp_temp = row_2["ID"]
            nace_class_lvl_3.append(f'{row["NAME"]}: {row_2["NAME"]}')
            for _, row_3 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp_temp].iterrows(): 
                nace_class_lvl_4.append(f'{row["NAME"]}: {row_2["NAME"]}: {row_3["NAME"]}')
        
    if level == 2: 
        return nace_class_lvl_2
    if level == 3: 
        return nace_class_lvl_3
    if level == 4: 
        return nace_class_lvl_4

In [12]:
def get_sublevels_df(nace_class, level) -> pd.DataFrame: 
    nace_class_temp = nace_class
    nace_id = nace_descriptions[nace_descriptions["CODE"] == nace_class_temp]["ID"].iloc[0]
    nace_class_lvl_2 = []
    nace_class_lvl_3 = []
    nace_class_lvl_4 = []

    for _, row in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id].iterrows(): 
        nace_id_temp = row["ID"]
        nace_class_lvl_2.append(row)
        for _, row_2 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp].iterrows(): 
            nace_id_temp_temp = row_2["ID"]
            nace_class_lvl_3.append(row_2)
            for _, row_3 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp_temp].iterrows(): 
                nace_class_lvl_4.append(row_3)
        
    if level == 2: 
        df =  pd.concat(nace_class_lvl_2, axis=1).T
        return df.drop_duplicates()

    if level == 3: 
        df = pd.concat(nace_class_lvl_3, axis=1).T
        return df.drop_duplicates()

    if level == 4: 
        df = pd.concat(nace_class_lvl_4, axis=1).T
        return df.drop_duplicates()

In [13]:
generate_nace_class = "A"

includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
assert includes is not None and includes != ""
includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
includes_also = "" if pd.isna(includes_also) else includes_also
excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
excludes = "" if pd.isna(excludes) else excludes

gold_standard = []

## Generate Few-Shot Data

In [14]:
# select gold standard data

# ds_2_desc  = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")

# ds_2_desc  = ds_2_desc[pd.notna(ds_2_desc["Description"])]

# gold_standard = []
# # 1. take one of each lvl 3 class:
# for lvl_3 in ds_2_desc[pd.notna(ds_2_desc["Description"])].groupby("NACE_lvl_3").size().index: 
#     gold_standard.append(ds_2_desc[ds_2_desc["NACE_lvl_3"] == lvl_3].iloc[0])

# df_gold_standard = pd.concat(gold_standard, axis=1).T

#df_gold_standard.to_csv("/Users/hendrikweichel/Downloads/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv")

In [15]:
#df_gold_standard = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")
df_gold_standard = pd.read_csv("data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")

### Hyperparams

In [16]:
prompt_path = "generate_synthetic_data/prompts/prompts_5_list.json"
print("System Prompt: ", get_system_prompt(prompt_path))
print("User Prompt: ", get_few_shot_user_prompt(prompt_path))

System Prompt:  You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms
User Prompt:  TASK
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
{includes} {includes_also}

{excludes}

Here are some examples of descriptions of these classes:
```
{gold_standard}
```

BUSINESS MODELS
{business_model}

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse

In [17]:
level = 1
head_nace_code = "1" if level > 1 else None
generated_classes = nace_descriptions[nace_descriptions["PARENT_ID"] == head_nace_code]["CODE"]
generated_classes = ["A", "B", "C", "J", "F"]

In [ ]:
few_shot = True

In [18]:
# generate date 

date = datetime.datetime.now().strftime("%Y%m%d")
suffix = "__few_shot" if few_shot else "__zero_shot"
suffix += "__from_lvl_4_topics"
store_path = "data/synthetic_data/two_step/data_" + date + f"__level_{level}__subclasses_{head_nace_code}__{os.path.basename(prompt_path).replace('.json', '')}{suffix}/" 
os.makedirs(store_path, exist_ok=True)

In [19]:
generated_data = {}

In [21]:
# # load previous results
# prev_results = "projects/nace_classification/nace_report_topic_analysis/data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot/class_A.csv"
# prev_results = "data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot"
# for class_name in generated_classes: 
#    file_path = os.path.join(prev_results, f"class_{class_name}.csv")
#    try:
#        df = pd.read_csv(file_path)
#        generated_data[class_name] = {
#            "data": df[class_name].tolist()
#        }
#    except Exception as e:
#        print(f"Could not load previous results for class {class_name}: {e}")

### Generate Topics

Here: 

- for each class get the subclasses on level 4
- for each subclass: 
    - generate k topics such that n_data topics are created

In [22]:
n_data = 1000 # total number of samples to generate per class
num_samples = 20 # number of samples per iteration (generated through one LLM call)
iterations_ = n_data // num_samples

In [25]:
topics = {}

In [26]:
for generate_nace_class in generated_classes:

    df_subsections = get_sublevels_df(generate_nace_class, level=4)

    topics_per_subsec = math.ceil(n_data / len(df_subsections))
    topic_samples = min(topics_per_subsec, 50)
    topic_iterations = math.ceil(topics_per_subsec / topic_samples)

    print("Nbr. of Subsecs. : ", len(df_subsections), ", Topics per Subclass", topics_per_subsec, ", Samples per LLM call: ", topic_samples, ", LLM calls per Subsec.: ", topic_iterations)

    examples = []

    for i, subsection in tqdm(df_subsections.iterrows()): 

        includes = subsection["Includes"]
        if pd.isna(includes):
            includes = subsection["NAME"]

        includes_also = subsection["IncludesAlso"]
        includes_also = "" if pd.isna(includes_also) else includes_also
        excludes = subsection["Excludes"]
        excludes = "" if pd.isna(excludes) else excludes

        topics_subsection = []

        for i in range(topic_iterations):
            res = generate_topic(num_samples=topic_samples, 
                                includes=includes, 
                                includes_also=includes_also, 
                                excludes=excludes,  
                                prompt_path=prompt_path, 
                                model="gpt-4o-mini", 
                                temperature=0.8)

            topics_subsection.append(res[1])
        
        examples.append({"CODE": subsection["CODE"], "NAME": subsection["NAME"], "TOPICS": "\n".join(topics_subsection)})
    
    clean_text = lambda x: re.sub(r'^\d+\.\s*', " ", x).strip()
    
    examples = pd.DataFrame(examples)
    examples["TOPICS"] = examples["TOPICS"].apply(clean_text)

    data = split_synthetic_data("\n\n".join(examples["TOPICS"]), num_samples * iterations_)

    results = {
        "topics": random.sample(data, k=2),
        "topics_df": examples,
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": data,
        "few_shot": few_shot
    }

    topics[generate_nace_class] = results

Nbr. of Subsecs. :  78 , Topics per Subclass 13 , Samples per LLM call:  13 , LLM calls per Subsec.:  1

78it [09:49,  7.56s/it]

Nbr. of Subsecs. :  33 , Topics per Subclass 31 , Samples per LLM call:  31 , LLM calls per Subsec.:  1

33it [07:23, 13.44s/it]

Nbr. of Subsecs. :  230 , Topics per Subclass 5 , Samples per LLM call:  5 , LLM calls per Subsec.:  1

230it [14:33,  3.80s/it]

Nbr. of Subsecs. :  26 , Topics per Subclass 39 , Samples per LLM call:  39 , LLM calls per Subsec.:  1

26it [07:22, 17.03s/it]

Nbr. of Subsecs. :  22 , Topics per Subclass 46 , Samples per LLM call:  46 , LLM calls per Subsec.:  1

22it [06:54, 18.85s/it]

In [37]:
examples

Empty DataFrame
Columns: []
Index: []

In [38]:
data

['A property development firm specializes in acquiring distressed residential properties, renovating them, and selling them at a premium to first-time homebuyers.',
 '2. A mixed-use development company partners with local governments to transform underutilized land into vibrant communities with both residential and commercial spaces.',
 '3. A real estate investment trust (REIT) focuses on developing luxury condominiums in urban areas, targeting affluent buyers and investors.',
 '4. A sustainable building developer creates eco-friendly residential communities that incorporate renewable energy sources and green building materials.',
 '5. A joint venture between a private developer and a municipal government aims to revitalize downtown areas by building affordable housing and community amenities.',
 '6. A modular construction company designs and manufactures pre-fabricated residential units, reducing construction time and costs for homebuilders.',
 '7. A luxury resort developer constructs high-end vacation homes in popular tourist destinations, appealing to affluent travelers looking for second homes.',
 '8. A commercial real estate developer focuses on building office spaces equipped with smart technology to attract tech companies and startups.',
 '9. A company specializes in building affordable housing projects by leveraging government grants and incentives to reduce overall costs.',
 '10. A boutique firm collaborates with architects to create unique, custom-designed homes for clients seeking personalized living spaces.',
 '11. A property syndication business pools investor funds to acquire and develop large residential projects, sharing profits through rental income and sales.',
 '12. A green building developer focuses on retrofitting existing structures with energy-efficient technologies to reduce their carbon footprint and enhance their marketability.',
 '13. A community-focused developer partners with non-profit organizations to create mixed-income housing projects that promote social equity.',
 '14. A land development company buys large parcels of land, zoning them for residential use, and selling off smaller lots to builders and individual buyers.',
 '15. A company specializes in developing multi-family housing units in urban areas, catering to young professionals seeking convenient living options.',
 '16. A real estate crowdfunding platform allows individual investors to fund residential development projects in exchange for a share of the profits.',
 '17. An innovative developer uses augmented reality to showcase building projects to potential buyers before construction begins, enhancing sales prospects.',
 '18. A niche firm focuses on developing retirement communities that offer a range of amenities and services for active seniors.',
 '19. A company develops luxury townhome communities that incorporate smart home technology to appeal to tech-savvy homeowners.',
 '20. A specialized developer creates housing solutions for the homeless by collaborating with local governments and charities to provide affordable living spaces.',
 '21. A social impact developer builds cooperative housing projects that empower residents to have a stake in their living environments.',
 '22. A commercial property developer constructs retail and office spaces with integrated residential units to create live-work-play environments.',
 '23. An investment group develops vacation rental properties in prime tourist locations, generating income through short-term rentals.',
 '24. A developer focuses on transforming historic buildings into modern residential units while preserving their architectural integrity.',
 '25. A company builds energy-efficient homes with off-grid capabilities, targeting environmentally conscious buyers.',
 '26. A real estate development firm partners with lifestyle brands to create themed communities that align with specific lifestyle choices.',
 '27. A neighborhood revitalization organization develops low-income housing by leveraging public-private partnerships to secure funding.',
 '28. A firm specializes in transforming former industrial sites into vibrant residential communities with parks and commercial spaces.',
 '29. A developer constructs high-rise apartments in urban centers, offering a mix of luxury and affordable units to attract diverse tenants.',
 '30. A company develops gated communities for families, incorporating amenities like playgrounds, pools, and community centers.',
 '31. A student housing developer builds affordable apartments near college campuses, addressing the growing demand for student accommodations.',
 '32. A developer implements smart city concepts in residential projects, integrating technology to enhance living experiences and sustainability.',
 '33. A company leverages data analytics to identify promising locations for new residential developments based on demographic trends.',
 '34. A real estate firm partners with healthcare providers to develop senior living facilities that prioritize wellness and accessibility.',
 '35. A company creates boutique housing developments with unique architectural designs, catering to niche markets looking for distinct living spaces.',
 '36. A property development business focuses on building eco-villages that promote sustainable living and communal practices among residents.',
 '37. A firm specializes in developing co-housing communities where residents share resources and common spaces to foster collaboration.',
 '38. A commercial developer targets the growing market for co-working spaces by integrating them into new residential buildings.',
 '39. A company engages in urban infill development, transforming vacant lots within established neighborhoods into new residential units.',
 '40. A developer constructs affordable tiny home communities, appealing to minimalists and those seeking lower-cost housing options.',
 '41. A company focuses on building disaster-resilient housing in areas prone to natural disasters, ensuring safety and sustainability.',
 '42. A real estate firm develops high-density housing projects in proximity to public transit, promoting sustainable urban living.',
 '43. A specialized developer creates transitional housing for individuals exiting homelessness, providing support services and resources.',
 '44. A company partners with artists to create live-work spaces that blend residential living with creative studios and galleries.',
 '45. A mixed-income developer builds housing projects that include market-rate and affordable units to promote diversity in neighborhoods.',
 '46. A firm focuses on creating intergenerational housing communities that foster connections between different age groups and lifestyles.',
 'A construction company specializing in eco-friendly single-family homes using sustainable materials and energy-efficient designs.',
 '2. A firm focused on building high-rise residential complexes that integrate smart home technology for enhanced living experiences.',
 '3. A company that specializes in the construction of multi-family buildings with affordable housing options in urban areas.',
 '4. A construction business that constructs modular industrial buildings for factories, allowing for quick assembly and relocation.',
 '5. A general contractor that renovates and remodels existing residential structures to improve energy efficiency and modernize interiors.',
 '6. A company that builds custom office buildings designed to enhance employee productivity and collaboration through open layouts.',
 '7. A construction firm that develops hotels and resorts with a focus on luxury and sustainability, attracting eco-conscious travelers.',
 '8. A contractor specializing in the construction of indoor sports facilities that cater to community needs, such as gyms and swimming pools.',
 '9. A construction company that focuses on building educational institutions with innovative learning environments to enhance student engagement.',
 '10. A firm that constructs parking garages using advanced technology for automated parking systems to maximize efficiency in urban settings.',
 '11. A builder that specializes in creating state-of-the-art warehouses equipped with logistics technology for efficient inventory management.',
 '12. A company that constructs healthcare facilities, including hospitals and clinics, designed for patient-centered care and improved workflows.',
 '13. A contractor that focuses on building shopping malls that combine retail, dining, and entertainment to create a comprehensive consumer experience.',
 '14. A construction business that specializes in developing religious buildings that serve as community centers and promote social engagement.',
 '15. A firm that builds high-rise residential buildings with rooftop gardens and green spaces for urban dwellers.',
 '16. A construction company that focuses on the assembly and erection of prefabricated homes to reduce construction time and costs.',
 '17. A contractor offering renovation services for historic homes, preserving architectural integrity while updating amenities.',
 '18. A business specializing in constructing energy-efficient schools that utilize renewable energy sources and green building practices.',
 '19. A firm that focuses on building luxury condominiums in high-demand urban areas with exclusive amenities and services.',
 '20. A construction company that specializes in developing mixed-use properties that combine residential, commercial, and recreational spaces.',
 '21. A contractor that constructs flexible office spaces for startups, featuring shared amenities and collaborative work areas.',
 '22. A firm that builds custom private hospitals with advanced medical technology and patient-focused design for specialized care.',
 '23. A company that specializes in constructing environmentally friendly shopping centers with green roofs and solar panels.',
 '24. A contractor that focuses on building high-quality residential properties with integrated smart home automation systems.',
 '25. A construction business that develops innovative parking solutions, such as multi-level parking structures in congested areas.',
 '26. A firm specializing in the construction of state-of-the-art assembly plants tailored for high-tech manufacturing processes.',
 '27. A contractor that renovates older commercial buildings into modern office spaces while preserving their historical charm.',
 '28. A company that constructs budget-friendly residential developments aimed at first-time homebuyers in suburban neighborhoods.',
 '29. A construction firm that builds community centers and recreational facilities designed to promote healthy living and social interaction.',
 '30. A business that specializes in constructing energy-efficient factories with a focus on reducing the carbon footprint of industrial production.',
 '31. A firm that provides renovation services to convert underutilized commercial spaces into vibrant mixed-use developments.',
 '32. A construction company dedicated to building performance-oriented sports complexes that host local and regional events.',
 '33. A contractor focused on renovating and retrofitting existing buildings to meet modern safety and efficiency standards.',
 '34. A specialized construction firm that designs and builds luxury vacation homes in prime tourist destinations.',
 '35. A company that focuses on building eco-friendly warehouses designed for sustainable logistics and distribution.',
 '36. A construction business that creates flexible, multi-purpose spaces for community use, including gyms, theaters, and meeting rooms.',
 '37. A contractor that constructs hospitals with integrated telemedicine capabilities to enhance patient accessibility and care.',
 '38. A firm specializing in the renovation of office buildings to create open-plan layouts that promote collaboration and flexibility.',
 '39. A construction company that builds shopping malls featuring pedestrian-friendly designs and outdoor gathering spaces.',
 '40. A contractor focused on constructing prefabricated educational facilities that can be deployed quickly to underserved areas.',
 '41. A firm that builds custom-designed hotels incorporating local culture and aesthetics to enhance guest experiences.',
 '42. A company that specializes in constructing creative workspaces that cater to freelancers and remote workers.',
 '43. A contractor that renovates existing religious buildings to accommodate modern community needs while respecting original designs.',
 '44. A firm focused on constructing affordable housing developments with a mix of single-family homes and apartment buildings.',
 '45. A construction business that develops state-of-the-art logistics hubs that optimize supply chain operations for various industries.',
 '46. A contractor specializing in the construction of green sports facilities with sustainable design features and practices.',
 'A construction company specializing in highway development partners with local governments to secure contracts for new roadway projects and infrastructure upgrades.',
 '2. A firm focuses on asphalt paving for both commercial and residential sectors, offering eco-friendly materials and technology for sustainable road surfaces.',
 '3. A street marking business provides comprehensive services that include painting road lines and installing traffic signs to ensure compliance with safety regulations.',
 '4. An engineering consultancy works closely with municipalities to design and oversee the construction of pedestrian walkways and bike lanes, promoting urban mobility.',
 '5. A company that specializes in installing crash barriers teams up with state authorities to enhance road safety on high-traffic highways.',
 '6. A construction contractor offers bundled services for both road construction and surface work, allowing for streamlined project management and cost savings.',
 '7. An asphalt recycling company collects old pavement, processes it, and supplies it to construction businesses for eco-friendly road resurfacing projects.',
 '8. A firm that focuses on road construction diversifies by offering maintenance contracts to local governments for ongoing service and repairs.',
 '9. A technology-driven startup uses drone surveys and AI to optimize the planning and execution of road construction projects, increasing efficiency.',
 '10. A niche company specializes in the construction of airfield runways, providing high-precision work to meet aviation standards.',
 '11. A construction firm secures public-private partnerships to develop urban road networks, investing in infrastructure pivotal for economic growth.',
 '12. A dedicated road painting service employs innovative materials that increase visibility and extend the lifespan of road markings.',
 '13. A contractor offers specialized services for the construction of pedestrian bridges, focusing on safety and aesthetic appeal in urban areas.',
 '14. A company that installs traffic signs collaborates with municipalities to develop smart signage systems that provide real-time traffic updates.',
 '15. A construction business invests in advanced technology for asphalt paving, reducing project time while maintaining high-quality standards.',
 '16. A street rehabilitation firm focuses on upgrading existing roads with new surfaces, enhancing safety and durability for heavy traffic.',
 '17. A company offering comprehensive roadway maintenance services provides seasonal evaluations and repairs to keep highways and roads safe year-round.',
 '18. An organization specializes in emergency road repair services, offering rapid response teams to address asphalt damage caused by natural disasters.',
 '19. A road construction company integrates green technology in paving practices, utilizing recycled materials and reducing carbon footprints.',
 '20. A firm focuses on multi-use trail construction, creating pathways that accommodate pedestrians, cyclists, and recreational users in urban settings.',
 '21. An asphalt paving company launches a subscription service for regular maintenance of commercial properties, ensuring their road surfaces are well-kept.',
 '22. A transportation-focused construction business works with state agencies to develop projects that improve traffic flow and reduce congestion.',
 '23. A contractor dedicated to bridge construction leverages innovative materials and techniques to create longer-lasting structures.',
 '24. A road safety consulting firm partners with construction companies to design safer roadways through strategic layout and traffic flow analysis.',
 '25. A company specializing in pedestrian way construction promotes walkability in urban areas by designing safe and attractive footpaths.',
 '26. A municipal contractor offers all-inclusive services for road projects, from initial design to final surface application, ensuring quality control.',
 '27. A construction company develops educational programs for municipalities on best practices for road maintenance and safety standards.',
 '28. A firm focuses on tunnel construction, providing specialized engineering and construction services to meet the challenges of subterranean work.',
 '29. A road construction business leverages big data analytics to predict traffic patterns and tailor projects accordingly for reduced disruption.',
 '30. A company providing pavement management solutions offers software and consulting services to help municipalities manage their road assets efficiently.',
 '31. A contractor focuses on sustainable road construction, utilizing eco-friendly materials and practices to minimize environmental impact.',
 '32. A service dedicated to road construction logistics optimizes supply chain management for timely delivery of materials to job sites.',
 '33. An infrastructure firm partners with universities for research and development in advanced materials for road construction and maintenance.',
 '34. A paving contractor invests in employee training programs to ensure high standards of safety and quality are maintained on every project.',
 '35. A road marking specialization business offers retroreflective painting technologies that enhance nighttime visibility for drivers.',
 '36. A construction firm creates community engagement initiatives that allow residents to participate in the planning of local roadway projects.',
 '37. A government contractor focuses on minimizing disruption during road construction by employing innovative techniques and technologies.',
 '38. An asphalt sealing company offers services to prolong the life of existing pavements while also providing resurfacing options for aging roads.',
 '39. A construction business provides design-build services for roadways, streamlining processes and reducing timelines for completion.',
 '40. A firm specializing in urban street design partners with city planners to create multifunctional public spaces that integrate pedestrian and vehicular traffic.',
 '41. A road infrastructure firm utilizes 3D modeling to visualize projects before construction, improving stakeholder engagement and project accuracy.',
 '42. A contractor dedicated to airfield runway construction offers specialized materials and construction methods tailored for aviation needs.',
 '43. A company focused on crash barrier installation collaborates with road safety organizations to implement best practices for accident prevention.',
 '44. A construction firm branching into road painting diversifies with creative designs for promotional road art that enhances community aesthetics.',
 '45. A specialized agency develops maintenance plans for new roads, ensuring ongoing compliance with safety and quality regulations post-construction.',
 '46. A company that builds multi-modal transport routes integrates bicycle lanes, walkways, and vehicle paths in a single project to enhance mobility.',

#### Store Topics

In [27]:
all_topics = []
for class_ in topics: 
    df_temp = topics[class_]["topics_df"].copy()
    df_temp["LVL_1_CODE"] = class_
    all_topics.append(df_temp)

all_topics = pd.concat(all_topics, axis=0)
all_topics.to_csv(os.path.join(store_path, "all_topics.csv"))

In [ ]:
topics_store = copy.deepcopy(topics)
for class_ in topics_store: 
    topics_store[class_]["topics_df"] = None

with open(os.path.join(store_path, "topics.json"), "w") as f: 
    json.dump(topics_store, f, indent=4)

### Generate Descriptions

In [29]:
generated_data = {}

In [ ]:
for generate_nace_class in generated_classes:

    includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
    if pd.isna(includes):
        print("No description for class:", generate_nace_class)
        continue
    includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
    includes_also = "" if pd.isna(includes_also) else includes_also
    excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
    excludes = "" if pd.isna(excludes) else excludes

    if few_shot: 
        gold_standard = df_gold_standard[df_gold_standard["NACE_letter"] == generate_nace_class]["Description_clean"].to_list()[:3] 
        gold_standard = [text.replace("\n", "") for text in gold_standard]
    else: 
        gold_standard = [] 

    subsections = get_sublevels(generate_nace_class, level=2)

    examples = []

    #if generated_data.get(generate_nace_class) is not None:
    #    if len(generated_data[generate_nace_class].get("data", [])) > 0:
    #        examples = generated_data[generate_nace_class]["data"]

    for i in tqdm(range(iterations_), desc=generate_nace_class):

        iteration_topics = topics[generate_nace_class]["output"][num_samples*i:num_samples*(i+1)]
        res = generate_synthetic_data(num_samples=num_samples, gold_standard=gold_standard, includes=includes, includes_also=includes_also, excludes=excludes, subsections=subsections, prompt_path=prompt_path, model="gpt-4o-mini", topic=iteration_topics)
        examples.append(res[1])
        data = split_synthetic_data("\n\n".join(examples), num_samples * iterations_)
        pd.DataFrame(data, columns=[generate_nace_class]).to_csv(os.path.join(store_path, f"class_{generate_nace_class}.csv"), index=False)

        if i < 2: 
            [print(example) for example in examples]
            print(res[0].messages[1].content)

        if len(data) >= num_samples * iterations_:
            break

    results = {
        "data": data,
        "prompt": res[0],
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": examples, 
        "few_shot": few_shot
    }

    generated_data[generate_nace_class] = results

A:   0%|                                                 | 0/50 [00:00<?, ?it/s]

A:   2%|▊                                        | 1/50 [00:27<22:35, 27.66s/it]

1. Operating as a cooperative, our organization brings together local farmers to harness their collective strengths in cultivating high-quality organic wheat and barley. By pooling resources, we not only enhance our production capabilities but also streamline the marketing process, allowing us to supply specialty bakeries and restaurants with premium grains. This collaborative approach fosters a strong sense of community while ensuring that our products meet the rigorous standards of discerning culinary professionals.

2. Our subscription service revolutionizes the way consumers access fresh, seasonal legumes, including chickpeas and lentils. Through a user-friendly online platform, we connect directly with customers, emphasizing transparency from farm to table. Each delivery showcases the best of what our farms have to offer, allowing families to enjoy nutritious meals while supporting sustainable agricultural practices. This model not only caters to health-conscious consumers but also strengthens the bond between producers and the community.

3. As a vertically integrated agribusiness, we take pride in our comprehensive approach to sunflower cultivation and processing. From planting to bottling, every step is meticulously managed to produce premium cooking oil that meets the highest quality standards. Our distribution channels span both retail and food service sectors, ensuring that our products are available to a wide range of customers. This integration allows us to maintain control over quality and consistency, reinforcing our reputation in the market.

4. Our regenerative agriculture initiative is dedicated to cultivating a diverse array of cereal crops while promoting sustainable farming techniques. We not only focus on crop production but also invest in educational programs designed for aspiring farmers. By sharing knowledge and best practices, we aim to create a new generation of environmentally conscious agriculturalists who can thrive in harmony with nature, ultimately contributing to a more sustainable food system.

5. Specializing in the cultivation and export of rare leguminous crops like lupines and pigeon peas, our niche market business caters to health food stores around the globe. We meticulously select and grow these unique varieties, which are increasingly sought after for their nutritional benefits. Our commitment to quality and sustainability ensures that our products not only meet the expectations of health-conscious consumers but also support the livelihoods of farmers engaged in this specialized agriculture.

6. As an agri-tech startup, we harness the power of data analytics and IoT technology to enhance the growing conditions for oil seeds. By providing commercial farmers with real-time insights and monitoring capabilities, we help optimize yields and minimize waste. Our innovative approach empowers farmers to make informed decisions, ultimately leading to more efficient and sustainable agricultural practices that benefit both their bottom line and the environment.

7. Our specialty grain mill proudly sources local barley and rye from regional farmers, transforming these grains into artisanal flours tailored for craft breweries and local baking enthusiasts. By maintaining close relationships with our suppliers, we ensure that our products reflect the unique characteristics of the region. This dedication to quality not only supports local agriculture but also fosters a vibrant community of makers who share our passion for exceptional food.

8. Through a contract farming model, we partner with smallholder farmers to cultivate high-yield soybeans, ensuring a reliable supply for the growing demand for plant-based protein products. This collaboration not only enhances the farmers' income but also guarantees that our processing facilities have access to the best raw materials. By aligning our interests with those of the farmers, we create a sustainable supply chain that benefits all stakeholders involved.

9. Our farm-to-fork initiative embodies a holistic approach to agriculture, where we grow and distribute organic grains and legumes while also providing cooking classes to educate consumers on nutrition and meal preparation. By bridging the gap between production and consumption, we empower individuals to make healthier choices while fostering a deeper appreciation for the food they eat. This initiative not only promotes well-being but also strengthens community ties.

10. Focused on the export market, our business grows and processes a diverse range of oil seeds, packaging them with a strong emphasis on fair trade and sustainability. By adhering to ethical practices, we ensure that our products resonate with conscious consumers worldwide. Our commitment to quality and responsible sourcing not only enhances our brand reputation but also contributes to the livelihoods of farmers in the regions where we operate.

11. Our community-supported agriculture (CSA) model is specifically designed for cereals and legumes, allowing members to receive a seasonal share of the harvest directly from our farm. This initiative fosters a direct connection between consumers and producers, creating a sense of shared responsibility for the land and its bounty. By participating in our CSA, members enjoy fresh, locally-grown produce while supporting sustainable agricultural practices.

12. As a research-driven agronomy firm, we collaborate with universities to develop and promote hybrid varieties of grain maize that enhance drought resistance and overall productivity. Our innovative research not only benefits farmers by providing them with resilient crop options but also contributes to food security in regions facing climate challenges. By staying at the forefront of agricultural science, we aim to drive positive change in the industry.

13. Our collaborative farming enterprise focuses on sustainable practices like crop rotation and intercropping to produce a diverse mix of cereals and legumes. By reducing reliance on chemical inputs, we prioritize environmental health while maintaining high productivity levels. This approach not only supports the ecosystem but also cultivates a community of farmers who are committed to responsible land stewardship.

14. Dedicated to organic production methods, our sustainable rice farm offers premium-priced, certified organic rice to health-conscious consumers. By participating in local farmers' markets and engaging in online sales, we connect directly with our customers, ensuring they understand the value of our products. This commitment to quality and sustainability resonates with our clientele, fostering a loyal customer base that appreciates our approach.

15. As a pioneer in genetically modified rice, we develop high-yield, drought-resistant varieties and partner with agricultural cooperatives to distribute seeds to smallholder farmers in developing countries. Our innovative solutions aim to empower farmers by providing them with the tools needed to adapt to changing environmental conditions. This collaboration not only enhances agricultural productivity but also contributes to food security in vulnerable regions.

16. Our eco-friendly rice plantation employs permaculture techniques and integrates aquaculture, allowing us to sell both rice and sustainably farmed fish to local restaurants and grocery stores. This holistic approach not only maximizes land use but also promotes biodiversity and soil health. By offering high-quality, sustainably produced products, we cater to a growing market of environmentally conscious consumers.

17. Our subscription service delivers fresh, locally-grown rice directly to consumers' homes, emphasizing organic practices and community-supported agriculture. This model allows us to build strong relationships with our customers while ensuring they receive the freshest produce possible. By prioritizing sustainability and transparency, we create a loyal customer base that values the connection between their food and the farmers who grow it.

18. As an agricultural technology firm, we specialize in precision farming tools designed specifically for rice growers. By offering data analytics and remote monitoring services, we empower farmers to optimize crop yields while reducing water usage. Our innovative solutions not only enhance productivity but also promote sustainable water management practices, ensuring a more resilient agricultural landscape.

19. Our rice processing plant focuses on producing specialty rice products, such as puffed rice snacks and rice flour, catering to the health and wellness trends in urban markets. By diversifying our product offerings, we tap into the growing demand for nutritious, convenient options that align with modern lifestyles. This strategic focus allows us to position our brand as a leader in the specialty food segment.

20. Our rice farm incorporates agro-tourism, inviting visitors to participate in harvest activities and experience farm life firsthand. This initiative generates additional revenue through guided tours and farm-to-table dining experiences, allowing us to share our passion for agriculture with the community. By blending education and entertainment, we foster a deeper appreciation for the agricultural process while supporting our farm's sustainability efforts.
TASK
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats.



Here are some examples of descriptions of these classes:
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODELS
1: A cooperative model where local farmers pool resources to collectively grow and market high-quality organic wheat and barley to specialty bakeries and restaurants.
2: 2. A subscription-based service offering fresh, seasonal legumes such as chickpeas and lentils directly to consumers through an online platform, promoting farm-to-table transparency.
3: 3. A vertically integrated agribusiness that cultivates sunflowers and processes them into premium cooking oil, distributing through both retail and food service channels.
4: 4. A regenerative agriculture initiative focusing on the cultivation of diverse cereal crops, paired with educational programs for sustainable farming practices targeted at new farmers.
5: 5. A niche market business that specializes in the cultivation and export of rare leguminous crops like lupines and pigeon peas, catering to health food stores worldwide.
6: 6. An agri-tech startup that leverages data analytics and IoT devices to optimize the growing conditions for oil seeds, enhancing yield and reducing waste for commercial farmers.
7: 7. A specialty grain mill that sources local barley and rye from regional farmers, producing artisanal flours for craft breweries and local baking communities.
8: 8. A contract farming model where large food processors partner with smallholder farmers to cultivate high-yield soybeans, ensuring a steady supply for plant-based protein products.
9: 9. A farm-to-fork initiative that grows and distributes organic grains and legumes while also providing cooking classes to educate consumers on nutrition and recipes.
10: 10. An export-focused business that grows and processes diverse oil seeds, packaging them for international markets while emphasizing fair trade and sustainability.
11: 11. A community-supported agriculture (CSA) model specifically for cereals and legumes, where members receive a seasonal share of harvest directly from the farm.
12: 12. A research-driven agronomy firm that collaborates with universities to develop and promote hybrid varieties of grain maize, enhancing drought resistance and productivity.
13: 13. A collaborative farming enterprise that focuses on crop rotation and intercropping techniques to produce a sustainable mix of cereals and legumes, reducing dependency on chemical inputs.
14: A sustainable rice farm that focuses on organic production methods, providing premium-priced, certified organic rice to health-conscious consumers through local farmers' markets and online sales.
15: 2. A genetically modified (GM) rice company that develops high-yield, drought-resistant rice varieties, partnering with agricultural cooperatives to distribute seeds to smallholder farmers in developing countries.
16: 3. An eco-friendly rice plantation that utilizes permaculture techniques and integrates aquaculture, selling both rice and sustainably farmed fish to local restaurants and grocery stores.
17: 4. A subscription-based service that delivers fresh, locally-grown rice directly to consumers' homes, emphasizing organic practices and community-supported agriculture.
18: 5. An agricultural technology firm that specializes in precision farming tools for rice growers, offering data analytics and remote monitoring services to optimize crop yields and reduce water usage.
19: 6. A rice processing plant that focuses on producing specialty rice products, such as puffed rice snacks and rice flour, catering to health and wellness trends in urban markets.
20: 7. A rice farm that incorporates agro-tourism, allowing visitors to participate in harvest activities while generating additional revenue through guided tours and farm-to-table dining experiences.

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse

A:   4%|█▋                                       | 2/50 [00:55<22:23, 27.98s/it]

1. Operating as a cooperative, our organization brings together local farmers to harness their collective strengths in cultivating high-quality organic wheat and barley. By pooling resources, we not only enhance our production capabilities but also streamline the marketing process, allowing us to supply specialty bakeries and restaurants with premium grains. This collaborative approach fosters a strong sense of community while ensuring that our products meet the rigorous standards of discerning culinary professionals.

2. Our subscription service revolutionizes the way consumers access fresh, seasonal legumes, including chickpeas and lentils. Through a user-friendly online platform, we connect directly with customers, emphasizing transparency from farm to table. Each delivery showcases the best of what our farms have to offer, allowing families to enjoy nutritious meals while supporting sustainable agricultural practices. This model not only caters to health-conscious consumers but also strengthens the bond between producers and the community.

3. As a vertically integrated agribusiness, we take pride in our comprehensive approach to sunflower cultivation and processing. From planting to bottling, every step is meticulously managed to produce premium cooking oil that meets the highest quality standards. Our distribution channels span both retail and food service sectors, ensuring that our products are available to a wide range of customers. This integration allows us to maintain control over quality and consistency, reinforcing our reputation in the market.

4. Our regenerative agriculture initiative is dedicated to cultivating a diverse array of cereal crops while promoting sustainable farming techniques. We not only focus on crop production but also invest in educational programs designed for aspiring farmers. By sharing knowledge and best practices, we aim to create a new generation of environmentally conscious agriculturalists who can thrive in harmony with nature, ultimately contributing to a more sustainable food system.

5. Specializing in the cultivation and export of rare leguminous crops like lupines and pigeon peas, our niche market business caters to health food stores around the globe. We meticulously select and grow these unique varieties, which are increasingly sought after for their nutritional benefits. Our commitment to quality and sustainability ensures that our products not only meet the expectations of health-conscious consumers but also support the livelihoods of farmers engaged in this specialized agriculture.

6. As an agri-tech startup, we harness the power of data analytics and IoT technology to enhance the growing conditions for oil seeds. By providing commercial farmers with real-time insights and monitoring capabilities, we help optimize yields and minimize waste. Our innovative approach empowers farmers to make informed decisions, ultimately leading to more efficient and sustainable agricultural practices that benefit both their bottom line and the environment.

7. Our specialty grain mill proudly sources local barley and rye from regional farmers, transforming these grains into artisanal flours tailored for craft breweries and local baking enthusiasts. By maintaining close relationships with our suppliers, we ensure that our products reflect the unique characteristics of the region. This dedication to quality not only supports local agriculture but also fosters a vibrant community of makers who share our passion for exceptional food.

8. Through a contract farming model, we partner with smallholder farmers to cultivate high-yield soybeans, ensuring a reliable supply for the growing demand for plant-based protein products. This collaboration not only enhances the farmers' income but also guarantees that our processing facilities have access to the best raw materials. By aligning our interests with those of the farmers, we create a sustainable supply chain that benefits all stakeholders involved.

9. Our farm-to-fork initiative embodies a holistic approach to agriculture, where we grow and distribute organic grains and legumes while also providing cooking classes to educate consumers on nutrition and meal preparation. By bridging the gap between production and consumption, we empower individuals to make healthier choices while fostering a deeper appreciation for the food they eat. This initiative not only promotes well-being but also strengthens community ties.

10. Focused on the export market, our business grows and processes a diverse range of oil seeds, packaging them with a strong emphasis on fair trade and sustainability. By adhering to ethical practices, we ensure that our products resonate with conscious consumers worldwide. Our commitment to quality and responsible sourcing not only enhances our brand reputation but also contributes to the livelihoods of farmers in the regions where we operate.

11. Our community-supported agriculture (CSA) model is specifically designed for cereals and legumes, allowing members to receive a seasonal share of the harvest directly from our farm. This initiative fosters a direct connection between consumers and producers, creating a sense of shared responsibility for the land and its bounty. By participating in our CSA, members enjoy fresh, locally-grown produce while supporting sustainable agricultural practices.

12. As a research-driven agronomy firm, we collaborate with universities to develop and promote hybrid varieties of grain maize that enhance drought resistance and overall productivity. Our innovative research not only benefits farmers by providing them with resilient crop options but also contributes to food security in regions facing climate challenges. By staying at the forefront of agricultural science, we aim to drive positive change in the industry.

13. Our collaborative farming enterprise focuses on sustainable practices like crop rotation and intercropping to produce a diverse mix of cereals and legumes. By reducing reliance on chemical inputs, we prioritize environmental health while maintaining high productivity levels. This approach not only supports the ecosystem but also cultivates a community of farmers who are committed to responsible land stewardship.

14. Dedicated to organic production methods, our sustainable rice farm offers premium-priced, certified organic rice to health-conscious consumers. By participating in local farmers' markets and engaging in online sales, we connect directly with our customers, ensuring they understand the value of our products. This commitment to quality and sustainability resonates with our clientele, fostering a loyal customer base that appreciates our approach.

15. As a pioneer in genetically modified rice, we develop high-yield, drought-resistant varieties and partner with agricultural cooperatives to distribute seeds to smallholder farmers in developing countries. Our innovative solutions aim to empower farmers by providing them with the tools needed to adapt to changing environmental conditions. This collaboration not only enhances agricultural productivity but also contributes to food security in vulnerable regions.

16. Our eco-friendly rice plantation employs permaculture techniques and integrates aquaculture, allowing us to sell both rice and sustainably farmed fish to local restaurants and grocery stores. This holistic approach not only maximizes land use but also promotes biodiversity and soil health. By offering high-quality, sustainably produced products, we cater to a growing market of environmentally conscious consumers.

17. Our subscription service delivers fresh, locally-grown rice directly to consumers' homes, emphasizing organic practices and community-supported agriculture. This model allows us to build strong relationships with our customers while ensuring they receive the freshest produce possible. By prioritizing sustainability and transparency, we create a loyal customer base that values the connection between their food and the farmers who grow it.

18. As an agricultural technology firm, we specialize in precision farming tools designed specifically for rice growers. By offering data analytics and remote monitoring services, we empower farmers to optimize crop yields while reducing water usage. Our innovative solutions not only enhance productivity but also promote sustainable water management practices, ensuring a more resilient agricultural landscape.

19. Our rice processing plant focuses on producing specialty rice products, such as puffed rice snacks and rice flour, catering to the health and wellness trends in urban markets. By diversifying our product offerings, we tap into the growing demand for nutritious, convenient options that align with modern lifestyles. This strategic focus allows us to position our brand as a leader in the specialty food segment.

20. Our rice farm incorporates agro-tourism, inviting visitors to participate in harvest activities and experience farm life firsthand. This initiative generates additional revenue through guided tours and farm-to-table dining experiences, allowing us to share our passion for agriculture with the community. By blending education and entertainment, we foster a deeper appreciation for the agricultural process while supporting our farm's sustainability efforts.
1. Our company stands at the forefront of the global rice export market, specializing in sourcing premium jasmine and basmati rice varieties directly from small-scale farmers. By fostering fair trade practices, we ensure that these farmers receive equitable compensation while gaining direct access to international markets. This commitment not only uplifts local communities but also guarantees that our customers enjoy high-quality, ethically sourced rice. As we expand our network, we continuously seek innovative ways to enhance our supply chain, ensuring that our products meet the growing demand for premium rice globally.

2. Operating as a fully integrated rice farming enterprise, our company manages every aspect of the supply chain—from the cultivation of seeds to the processing and distribution of our products. This vertical integration allows us to maintain stringent quality control and competitive pricing, ensuring that our rice consistently meets the highest standards. By leveraging advanced agricultural techniques and efficient logistics, we are able to respond swiftly to market demands while optimizing our operational efficiencies.

3. Our innovative mobile application bridges the gap between rice farmers and consumers, enabling users to trace the origins of their rice and purchase directly from producers. This platform not only enhances transparency in the food supply chain but also supports local economies by empowering farmers with direct sales opportunities. As we grow our user base, we remain dedicated to fostering connections that benefit both consumers seeking quality products and farmers striving for fair compensation.

4. At the heart of our operations lies a commitment to research and development in rice cultivation techniques. Collaborating with leading universities, we focus on creating environmentally sustainable practices that can be shared with commercial growers through licensing agreements. Our innovative approach not only enhances crop yields but also contributes to the broader goal of sustainable agriculture, ensuring that future generations can continue to enjoy the benefits of rice farming.

5. Our cooperative model unites multiple small rice farmers, allowing them to pool resources and share equipment, significantly reducing operational costs. This collaborative approach not only enhances efficiency but also enables us to present a unified brand identity in the market, effectively promoting our organic rice offerings. By working together, we are able to leverage collective strengths, ensuring that each farmer thrives while delivering high-quality products to consumers.

6. We have established an online educational platform dedicated to empowering aspiring rice farmers with knowledge on organic farming practices, pest management, and sustainable irrigation techniques. Through a series of comprehensive courses, we generate revenue while fostering a new generation of environmentally conscious farmers. Our mission is to equip individuals with the skills needed to thrive in the agricultural sector, contributing to a more sustainable future for all.

7. Specializing in hydroponic farming, our company focuses on cultivating fresh lettuce and herbs, which we supply directly to local restaurants and grocery stores. By utilizing advanced hydroponic systems, we ensure year-round availability of our produce, meeting the demands of a market that increasingly values freshness and quality. Our commitment to local sourcing not only supports regional economies but also reduces the carbon footprint associated with long-distance transportation.

8. Our organic farm is dedicated to growing a diverse range of root vegetables, including carrots and potatoes, while employing sustainable agricultural practices. Through our subscription box service, customers receive a curated selection of seasonal produce delivered right to their doorstep. This model not only promotes healthy eating but also strengthens the connection between consumers and the source of their food, fostering a greater appreciation for local agriculture.

9. As a gourmet mushroom cultivation enterprise, we focus on producing high-quality varieties such as shiitake and oyster mushrooms. Our products are sold to upscale restaurants and featured at local farmers' markets, where we emphasize the unique flavors and culinary applications of our mushrooms. By cultivating relationships with chefs and food enthusiasts, we create a niche market that values quality and sustainability in gourmet dining.

10. Our family-owned farm specializes in the cultivation of asparagus and sweet potatoes, offering unique farm-to-table experiences that include guided tours and u-pick events. By inviting customers to engage directly with the farming process, we create memorable interactions that highlight the importance of fresh, locally grown produce. This hands-on approach not only enhances customer loyalty but also educates visitors about sustainable farming practices.

11. Operating a hydroponic greenhouse, we focus on growing cucumbers and tomatoes, supplying fresh produce to meal kit companies and grocery chains. Our innovative growing methods allow us to deliver high-quality vegetables with minimal environmental impact. By aligning our production with the needs of meal kit providers, we ensure that our products are consistently available, meeting the demands of health-conscious consumers.

12. Our community-supported agriculture (CSA) program cultivates a wide variety of leafy vegetables and fruit-bearing crops, providing members with regular deliveries of fresh produce. This model fosters a direct relationship between consumers and farmers, promoting transparency and trust in the food supply chain. By encouraging community involvement, we strengthen local food systems while ensuring that our members enjoy the freshest seasonal offerings.

13. As an innovative startup, we specialize in developing and selling vegetable seeds, including sustainable options for home gardeners and commercial farmers alike. Our focus on quality and environmental responsibility sets us apart in a competitive market. By providing gardeners with access to high-yield, pest-resistant varieties, we empower them to cultivate their own produce while contributing to a more sustainable agricultural landscape.

14. Our specialty farm is dedicated to the cultivation of truffles and other high-value mushrooms, partnering with renowned chefs to create exclusive dining experiences that feature our unique products. By focusing on quality and rarity, we position ourselves as a premium supplier in the culinary market, attracting food enthusiasts eager to explore the flavors of our carefully cultivated fungi.

15. Committed to regenerative agriculture, our project focuses on growing heirloom varieties of potatoes and yams, promoting biodiversity and sustainable farming practices. By selling our produce through local organic co-ops, we connect with consumers who value quality and environmental stewardship. Our approach not only enhances soil health but also supports local economies, ensuring that our farming practices benefit both the land and the community.

16. Our online marketplace connects small-scale farmers who grow a variety of vegetables, including onions and garlic, directly with consumers. By enhancing farm incomes through direct sales, we create a more equitable food system that benefits both producers and buyers. This platform not only promotes local agriculture but also empowers consumers to make informed choices about the food they purchase.

17. As a research and development firm, we focus on creating pest-resistant and high-yield vegetable varieties, including turnips and leeks. By licensing our findings to commercial growers, we contribute to the advancement of agricultural practices that prioritize sustainability and efficiency. Our commitment to innovation ensures that we remain at the cutting edge of agricultural technology, driving positive change in the industry.

18. Our local cooperative is dedicated to growing and processing a variety of melons and fruit-bearing vegetables, with a focus on producing value-added products like salsas and preserves. By collaborating with local farmers, we enhance product offerings while supporting community agriculture. This approach not only diversifies our revenue streams but also strengthens our ties to the local economy.

19. At our educational farm, we offer workshops focused on growing leafy greens and root vegetables, generating revenue through classes while promoting sustainable agriculture practices. By providing hands-on learning experiences, we inspire individuals to adopt environmentally friendly farming methods. Our mission is to cultivate a community of informed consumers and responsible farmers who prioritize sustainability.

20. Our vertically integrated sugar cane plantation encompasses every aspect of the sugar production process, from cultivation to harvesting and processing into raw sugar. By selling directly to food manufacturers, we ensure a consistent supply of high-quality sugar while optimizing our operations for efficiency. This comprehensive approach allows us to respond effectively to market demands while maintaining our commitment to sustainable farming practices.
TASK
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats.



Here are some examples of descriptions of these classes:
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:

A:  28%|███████████▏                            | 14/50 [06:50<17:59, 30.00s/it]

In [40]:
topics[generate_nace_class]["output"]

['A cooperative model where local farmers pool resources to collectively grow and market high-quality organic wheat and barley to specialty bakeries and restaurants.',
 '2. A subscription-based service offering fresh, seasonal legumes such as chickpeas and lentils directly to consumers through an online platform, promoting farm-to-table transparency.',
 '3. A vertically integrated agribusiness that cultivates sunflowers and processes them into premium cooking oil, distributing through both retail and food service channels.',
 '4. A regenerative agriculture initiative focusing on the cultivation of diverse cereal crops, paired with educational programs for sustainable farming practices targeted at new farmers.',
 '5. A niche market business that specializes in the cultivation and export of rare leguminous crops like lupines and pigeon peas, catering to health food stores worldwide.',
 '6. An agri-tech startup that leverages data analytics and IoT devices to optimize the growing conditions for oil seeds, enhancing yield and reducing waste for commercial farmers.',
 '7. A specialty grain mill that sources local barley and rye from regional farmers, producing artisanal flours for craft breweries and local baking communities.',
 '8. A contract farming model where large food processors partner with smallholder farmers to cultivate high-yield soybeans, ensuring a steady supply for plant-based protein products.',
 '9. A farm-to-fork initiative that grows and distributes organic grains and legumes while also providing cooking classes to educate consumers on nutrition and recipes.',
 '10. An export-focused business that grows and processes diverse oil seeds, packaging them for international markets while emphasizing fair trade and sustainability.',
 '11. A community-supported agriculture (CSA) model specifically for cereals and legumes, where members receive a seasonal share of harvest directly from the farm.',
 '12. A research-driven agronomy firm that collaborates with universities to develop and promote hybrid varieties of grain maize, enhancing drought resistance and productivity.',
 '13. A collaborative farming enterprise that focuses on crop rotation and intercropping techniques to produce a sustainable mix of cereals and legumes, reducing dependency on chemical inputs.',
 "A sustainable rice farm that focuses on organic production methods, providing premium-priced, certified organic rice to health-conscious consumers through local farmers' markets and online sales.",
 '2. A genetically modified (GM) rice company that develops high-yield, drought-resistant rice varieties, partnering with agricultural cooperatives to distribute seeds to smallholder farmers in developing countries.',
 '3. An eco-friendly rice plantation that utilizes permaculture techniques and integrates aquaculture, selling both rice and sustainably farmed fish to local restaurants and grocery stores.',
 "4. A subscription-based service that delivers fresh, locally-grown rice directly to consumers' homes, emphasizing organic practices and community-supported agriculture.",
 '5. An agricultural technology firm that specializes in precision farming tools for rice growers, offering data analytics and remote monitoring services to optimize crop yields and reduce water usage.',
 '6. A rice processing plant that focuses on producing specialty rice products, such as puffed rice snacks and rice flour, catering to health and wellness trends in urban markets.',
 '7. A rice farm that incorporates agro-tourism, allowing visitors to participate in harvest activities while generating additional revenue through guided tours and farm-to-table dining experiences.',
 '8. A global export company that sources premium jasmine and basmati rice varieties from small-scale farmers, ensuring fair trade practices and direct access to international markets.',
 '9. A vertically integrated rice farming operation that controls the entire supply chain, from seed production to processing and distribution, allowing for consistent quality and competitive pricing.',
 '10. A mobile application that connects rice farmers with consumers, allowing users to track the source of their rice and purchase directly from producers, fostering transparency and supporting local economies.',
 '11. A research and development firm specializing in innovative rice cultivation techniques, collaborating with universities to develop environmentally sustainable practices and licensing findings to commercial growers.',
 '12. A co-op model where multiple small rice farmers pool resources and share equipment, cutting costs while offering a collective branding approach to market their organic rice effectively.',
 '13. An online educational platform that provides training for aspiring rice farmers on organic farming practices, pest management, and sustainable irrigation techniques, generating revenue through course fees.',
 'A vertical farming company specializing in hydroponic lettuce and herbs that sells directly to local restaurants and grocery stores, ensuring fresh produce year-round.',
 '2. An organic farm that grows a variety of root vegetables like carrots and potatoes, utilizing sustainable practices, and offers a subscription box service for customers to receive seasonal produce.',
 "3. A mushroom cultivation enterprise that produces gourmet varieties such as shiitake and oyster mushrooms, selling to high-end restaurants and at local farmer's markets.",
 '4. A family-owned farm that focuses on growing asparagus and sweet potatoes, providing farm-to-table experiences through on-site tours and u-pick events.',
 '5. A hydroponic greenhouse business that specializes in growing cucumbers and tomatoes, supplying fresh produce to meal kit companies and grocery chains.',
 '6. A community-supported agriculture (CSA) program that cultivates diverse leafy vegetables and fruit-bearing crops, allowing members to subscribe for regular deliveries of fresh produce.',
 '7. An innovative startup that develops and sells vegetable seeds, such as sugar beet seeds, targeting both home gardeners and commercial farmers with sustainable options.',
 '8. A specialty farm dedicated to cultivating truffles and other high-value mushrooms, which partners with chefs to create exclusive dining experiences featuring their products.',
 '9. A regenerative agriculture project focusing on growing heirloom varieties of potatoes and yams, promoting biodiversity and selling through local organic co-ops.',
 '10. An online marketplace that connects small-scale farmers growing a variety of vegetables, including onions and garlic, directly with consumers, enhancing farm incomes.',
 '11. A research and development company that creates pest-resistant and high-yield vegetable varieties, including turnips and leeks, licensed to commercial growers.',
 '12. A local cooperative that grows and processes various melons and fruit-bearing vegetables, aiming to produce value-added products like salsa and preserves.',
 '13. An educational farm that offers workshops on growing leafy greens and root vegetables, generating revenue through classes while promoting sustainable agriculture practices.',
 'A vertically integrated sugar cane plantation that not only grows and harvests sugar cane but also processes it into raw sugar and sells it directly to food manufacturers.',
 '2. An organic sugar cane farm that specializes in sustainable cultivation practices, producing high-quality organic sugar for health-conscious consumers and specialty food markets.',
 '3. A sugar cane farm that partners with local distilleries to supply fresh cane juice for craft rum production, creating a niche market for artisanal spirits.',
 '4. A sugar cane plantation that utilizes precision agriculture technology to optimize yield and reduce waste, selling data analytics services to other farmers in the region.',
 '5. A cooperative model where multiple small-scale sugar cane farmers band together to pool resources, share equipment, and market their sugar collectively to increase bargaining power.',
 '6. A sugar cane processing facility that generates additional revenue by producing value-added products such as molasses, ethanol, and bioplastics from sugar cane by-products.',
 '7. A regenerative agriculture business that focuses on restoring soil health while cultivating sugar cane, selling carbon credits to companies looking to offset their emissions.',
 '8. A sugar cane farm that starts a subscription service for customers to receive locally sourced sugar and related products like syrups and raw sugar bakes monthly.',
 '9. A technology-driven startup that develops and sells mobile applications for sugar cane farmers to track crop health, market prices, and manage supply chains efficiently.',
 '10. An agro-tourism venture that offers tours and tastings at a sugar cane plantation, educating visitors on the sugar production process while generating additional income.',
 '11. A specialty sugar company that sources premium sugar cane from various regions, creating unique blends and marketing them as gourmet products for chefs and home bakers.',
 '12. A research and development lab that partners with sugar cane growers to develop disease-resistant cane varieties, licensing these innovations to other farms in exchange for royalties.',
 '13. A sugar cane farm that collaborates with local schools and organizations to promote educational programs about sustainable farming practices and the importance of sugar cane in the economy.',
 'A tobacco farm using sustainable agricultural practices to cultivate organic tobacco leaves, targeting niche markets focused on health-conscious consumers.',
 '2. A cooperative model where local farmers pool resources and share knowledge to increase the efficiency of growing high-quality, natural tobacco.',
 '3. A vertically integrated business that grows and processes tobacco on-site, ensuring quality control from seed to leaf for premium specialty tobacco.',
 '4. A subscription-based service delivering fresh, locally sourced tobacco leaves directly to artisanal cigar makers and hobbyists who prioritize quality over quantity.',
 '5. A research-driven enterprise specializing in the development of new tobacco strains with unique flavor profiles, appealing to gourmet tobacco connoisseurs.',
 '6. An export-oriented business focusing on growing rare tobacco varieties for international markets, leveraging trade partnerships to access premium pricing.',
 '7. An agri-tourism venture that offers farm tours and educational workshops on sustainable tobacco farming, attracting eco-conscious visitors.',
 '8. A technology-driven farm utilizing precision agriculture techniques to optimize crop yields and reduce environmental impact while growing unmanufactured tobacco.',
 '9. A hybrid model that combines traditional farming practices with hydroponics to cultivate high-quality tobacco in urban settings, catering to local markets.',
 '10. A regenerative agriculture business that focuses on soil health and biodiversity while producing tobacco, selling leaves to boutique manufacturers.',
 '11. A brand that emphasizes the heritage of tobacco farming by sourcing from small, family-owned farms and promoting their stories to attract ethical consumers.',
 '12. An innovative approach to tobacco farming that incorporates agroforestry, promoting biodiversity while producing unmanufactured tobacco for specialty markets.',
 '13. A diversified farming operation that grows multiple cash crops alongside tobacco, utilizing crop rotation to enhance soil fertility and profitability.',
 'A sustainable cotton farming cooperative that uses organic practices to produce premium, eco-friendly cotton for the fashion industry.',
 '2. A jute processing company that converts raw jute into biodegradable packaging solutions for environmentally-conscious businesses.',
 '3. A flax cultivation enterprise that partners with local artisans to create high-quality linen fabrics while promoting traditional weaving techniques.',
 '4. A kenaf fiber production facility that supplies raw materials to the automotive industry for biocomposite components.',
 '5. An industrial hemp farm that produces hemp-based textiles and bioplastics, catering to the growing demand for sustainable materials.',
 '6. A sisal plantation that focuses on producing high-strength sisal fibers for the rope and twine market, emphasizing eco-friendly farming methods.',
 '7. A boutique abaca farm that crafts artisanal paper products, targeting niche markets for sustainable stationery and crafts.',
 '8. A ramie processing plant that specializes in creating blended textiles, combining ramie with other fibers for enhanced durability and breathability.',
 '9. A vertical farming operation dedicated to cultivating kenaf and jute, utilizing hydroponic techniques to maximize yield in urban environments.',
 '10. An online platform connecting small-scale vegetable fiber farmers with global textile manufacturers looking for sustainable sourcing options.',
 '11. A research and development company focused on innovating sustainable textile fibers from agave plants, aimed at replacing synthetic fibers.',
 '12. A community-driven initiative that promotes the cultivation of traditional fiber crops while providing education and resources for sustainable farming practices.',
 '13. A logistics firm specializing in the export of natural fibers like abaca and jute, facilitating trade connections between local farmers and international buyers.',
 'A local farm specializes in the cultivation and direct-to-consumer sales of a diverse range of non-perennial forage crops, focusing on organic clover and alfalfa for livestock feed.',
 '2. An established flower seed company operates a subscription service that delivers seasonal flower seed packets to customers, promoting home gardening and sustainable practices.',
 '3. A mixed-use agricultural enterprise grows swedes and fodder roots while also offering educational workshops on sustainable farming techniques to local farmers.',
 '4. A boutique farm produces cut flowers and flower buds for upscale events, partnering with wedding planners and event coordinators to create customized floral arrangements.',
 '5. A vertically integrated business grows and processes forage maize, selling both the raw product to livestock farmers and producing value-added products like silage.',
 '6. An online marketplace connects small-scale flower growers with urban consumers, facilitating the sale of locally grown cut flowers and offering delivery services.',
 '7. A seed company focuses on breeding and selling high-yielding forage plant seeds, targeting commercial livestock operations in regions with specific climate challenges.',
 '8. A community-supported agriculture (CSA) model that includes a selection of seasonal forage crops, allowing members to receive fresh produce and support local farmers.',
 "9. A sustainable farm utilizes permaculture principles to grow diverse flower varieties and forage crops, selling directly at local farmers' markets and through an e-commerce platform.",
 '10. A research-driven agricultural firm develops innovative growing techniques for beet seeds and forage plants, collaborating with universities for trials and commercial applications.',
 '11. A wellness brand markets herbal teas made from a blend of forage plants, leveraging partnerships with local farmers to source high-quality, organic ingredients.',
 '12. An agritech startup creates an app that helps farmers optimize their growing conditions for non-perennial crops by providing data analytics and remote monitoring solutions.',
 '13. A floral subscription box service curates seasonal bouquets made from locally sourced flowers, delivering them weekly to customers while supporting sustainable farming practices.',
 'A craft brewery focusing on small-batch, locally sourced ingredients to create unique seasonal beers that cater to the artisanal market.',
 "2. A beverage startup that specializes in organic, cold-pressed juices, leveraging subscription services to deliver fresh products directly to consumers' doors weekly.",
 '3. An established soft drink company that develops health-oriented sparkling water infused with natural flavors and adaptogens, targeting health-conscious millennials.',
 '4. A wine producer that utilizes sustainable farming practices and emphasizes vineyard tours and tastings as part of its direct-to-consumer sales strategy.',
 '5. A multinational beverage corporation that integrates advanced AI analytics to predict consumer trends, optimizing product development and marketing strategies across global markets.',
 '6. A beverage company focused on producing ready-to-drink coffee beverages that partner with local cafes to enhance brand visibility and community engagement.',
 '7. A traditional soda manufacturer that diversifies its offerings by introducing a line of low-sugar, naturally sweetened sodas to appeal to evolving consumer preferences.',
 '8. A bottled water brand that promotes eco-friendly packaging and partners with environmental organizations to enhance brand image and customer loyalty.',
 '9. A tea company that emphasizes unique blends and flavor infusions, marketing its products through e-commerce platforms while hosting online tea tasting events.',
 '10. A beverage conglomerate that creates a portfolio of private label drinks for retail partners, focusing on affordability and convenience for budget-conscious consumers.',
 '11. A dairy beverage producer that innovates with non-dairy alternatives, such as oat and almond-based drinks, to meet the growing demand for plant-based options.',
 '12. An energy drink manufacturer that collaborates with fitness influencers to promote a new line tailored for athletes, combining performance-enhancing ingredients and sustainable packaging.',
 '13. A beverage company that focuses on functional drinks aimed at wellness, incorporating probiotics and vitamins, while leveraging social media campaigns to engage a health-oriented audience.',
 "A vineyard specializing in organic table grapes sells directly to local grocery stores and farmers' markets, capitalizing on the demand for fresh, pesticide-free produce.",
 '2. A boutique winery partners with a sustainable agriculture program to grow unique wine grape varieties, allowing for exclusive wine releases that emphasize terroir.',
 "3. A vineyard operates a membership subscription service that delivers seasonal harvest boxes of both wine and table grapes to customers' homes.",
 '4. A farm-to-table restaurant collaborates with local vineyards to source seasonal table grapes and wine grapes, creating a unique dining experience that highlights regional produce.',
 '5. A vineyard offers agritourism experiences, including grape-picking events and educational tours about sustainable grape farming, enhancing visitor engagement and generating additional revenue.',
 '6. A winery utilizes a sharecropping model, partnering with local farmers to cultivate wine grapes on their land, sharing profits while expanding cultivation area.',
 '7. A vineyard implements a direct-to-consumer e-commerce platform, allowing customers to order fresh table grapes and seasonal wines shipped straight to their doorstep.',
 '8. A cooperative of small grape growers pools resources to market and distribute their products collectively, increasing visibility and market access for all members.',
 '9. A vineyard implements precision agriculture techniques, using data analytics to optimize grape yield and quality, reducing waste and increasing profitability.',
 "10. A vineyard develops partnerships with local chefs to create exclusive recipes featuring their table grapes, promoting both the chefs' restaurants and the vineyard's produce.",
 '11. A vineyard leases land to hobbyist grape growers, providing them with access to expert advice and resources while generating rental income.',

In [33]:
topics[generate_nace_class]["topics_df"]#[num_samples*i:num_samples*(i+1)]

In [ ]:
# print prompts
for k,v in generated_data.items(): 
    print(k,len(v["output"]), "_______"*20)
    for k in v["output"]: 
        print(k)
        print("_")

C 25 ____________________________________________________________________________________________________________________________________________
1. Our company is at the forefront of innovation in the recreational vehicle sector, specializing in the design and production of collapsible trailers that redefine convenience for outdoor enthusiasts. These trailers are engineered for easy storage and transport, allowing users to maximize their adventures without the hassle of cumbersome equipment. By focusing on lightweight materials and smart engineering, we ensure that our products not only meet the demands of the modern adventurer but also enhance the overall experience of outdoor travel. Our commitment to quality and functionality has positioned us as a preferred choice among recreational vehicle users who value both practicality and design.

2. As a dedicated manufacturer of specialized equipment tailored for off-road vehicles, we cater to the growing adventure tourism market. Our products are meticulously crafted to withstand the rigors of challenging terrains while providing unmatched performance and reliability. By collaborating closely with adventure tourism companies, we continuously refine our offerings to meet their specific needs, ensuring that our equipment enhances their operational efficiency and safety. Our focus on innovation and durability has established us as a trusted partner in the adventure tourism industry, where the right equipment can make all the difference.

3. At the heart of our woodworking company is a commitment to sustainability and environmental stewardship. We specialize in producing eco-friendly wood finishes and treatments that appeal to consumers who prioritize responsible sourcing and minimal environmental impact. Our formulations are designed to enhance the natural beauty of wood while providing long-lasting protection, ensuring that our customers can enjoy their spaces with peace of mind. By leveraging sustainable practices and materials, we not only contribute to a healthier planet but also empower our customers to make environmentally conscious choices in their homes and businesses.

4. We are revolutionizing the logistics industry with our line of modular cargo ships, designed for versatility and efficiency. These ships can be easily reconfigured to accommodate varying shipping needs, allowing logistics companies to optimize their operations and reduce costs. Our innovative approach to maritime design enables seamless transitions between different cargo types, enhancing both speed and flexibility in shipping operations. As global trade continues to evolve, our commitment to adaptability and efficiency positions us as a leader in the maritime logistics sector.

5. Our company provides mobile conveyor systems that are transforming material handling for construction firms across various job sites. These rental systems are designed for quick setup and portability, allowing contractors to streamline their operations and improve productivity. By focusing on user-friendly designs and robust performance, we empower our clients to handle materials efficiently, regardless of the project scale. Our dedication to innovation in construction logistics ensures that we remain a valuable partner in the industry, helping businesses achieve their goals with ease.

6. As a manufacturer of ceramic insulators for the electrical industry, we leverage cutting-edge materials science to enhance both performance and safety in electrical applications. Our products are engineered to withstand extreme conditions while providing reliable insulation, making them essential components in various electrical systems. By investing in research and development, we continuously improve our offerings, ensuring that they meet the highest industry standards. Our commitment to quality and innovation has solidified our reputation as a trusted supplier in the electrical sector.

7. We specialize in the development of advanced polymer-based materials tailored for medical applications, prioritizing biocompatibility and compliance with stringent regulatory standards. Our innovative materials are designed to enhance patient safety and comfort, making them ideal for a range of medical devices and applications. By collaborating with healthcare professionals and regulatory bodies, we ensure that our products not only meet but exceed industry expectations. Our focus on quality and innovation positions us as a leader in the medical materials sector, dedicated to improving patient outcomes through superior technology.

8. Our company is dedicated to the extraction and purification of ethane from natural gas liquids, supplying this critical resource to the petrochemical industry for plastic production. By employing state-of-the-art technologies and processes, we ensure the highest purity levels, which are essential for the production of high-quality plastics. Our commitment to operational excellence and sustainability allows us to meet the growing demand for ethane while minimizing environmental impact. As a key player in the petrochemical supply chain, we are positioned to support the industry's evolving needs.

9. At our tobacco-processing plant, we utilize innovative fermentation techniques to enhance the flavor profiles of premium tobacco products. Our focus on quality and craftsmanship ensures that each batch meets the highest standards, appealing to discerning consumers who appreciate rich and complex flavors. By continuously refining our processes and sourcing the finest raw materials, we create products that stand out in a competitive market. Our dedication to innovation in flavor enhancement positions us as a leader in the premium tobacco segment.

10. We provide a cutting-edge digital catalog printing service that enables retailers to produce both online and printed versions of their product catalogs simultaneously. This dual approach not only streamlines the marketing process but also enhances customer engagement by providing a cohesive shopping experience. Our technology allows for real-time updates and customization, ensuring that retailers can showcase their latest offerings effectively. By integrating digital and print solutions, we empower our clients to reach their audiences more efficiently and effectively.

11. Our company specializes in the production of essential oils and natural fragrances derived from organic plant materials, catering to the cosmetics and personal care industries. We are committed to sourcing high-quality botanicals and employing sustainable extraction methods to create products that resonate with consumers seeking authenticity and purity. Our extensive portfolio of fragrances not only enhances product formulations but also aligns with the growing demand for natural and eco-friendly options. By focusing on quality and sustainability, we position ourselves as a trusted partner for brands looking to elevate their offerings.

12. We design and implement automated systems for the textile industry, focusing on reducing labor intensity while significantly increasing production rates. Our innovative solutions streamline manufacturing processes, allowing textile producers to enhance efficiency and reduce operational costs. By integrating advanced technology with industry expertise, we empower our clients to adapt to changing market demands and improve their competitiveness. Our commitment to innovation in textile automation positions us as a key player in the evolution of the industry.

13. As an established electronics firm, we produce smart home devices that seamlessly integrate with existing home networks, enhancing convenience and security for users. Our subscription service provides ongoing software updates and new features, ensuring that our customers always have access to the latest innovations. By focusing on user-friendly designs and robust functionality, we create products that not only simplify daily life but also contribute to a smarter, more connected home environment. Our dedication to quality and customer satisfaction drives our continued success in the smart home market.

14. Our luxury brand is pioneering the integration of biodegradable leather substitutes into our collections, appealing to environmentally conscious consumers who value sustainability without compromising on style. By sourcing innovative materials that mimic the look and feel of traditional leather, we create products that resonate with a modern ethos of responsible consumption. Our commitment to ethical fashion positions us as a leader in the luxury market, where consumers increasingly seek out brands that reflect their values.

15. We are a marine electronics manufacturer focused on designing smart navigation systems that enhance safety for boaters by integrating real-time weather and traffic data. Our cutting-edge technology provides users with critical information at their fingertips, allowing for informed decision-making on the water. By prioritizing user experience and reliability, we empower boaters to navigate with confidence, regardless of conditions. Our dedication to innovation in marine technology positions us as a trusted partner for both recreational and commercial boating communities.

16. As a manufacturer of plastic counter displays, we help brands effectively showcase their products in retail environments. Our designs are tailored to enhance visibility and engagement, ensuring that products stand out to consumers. By focusing on quality materials and innovative designs, we provide our clients with solutions that drive sales and elevate their brand presence. Our commitment to customer satisfaction and creativity positions us as a preferred partner for retailers looking to optimize their merchandising strategies.

17. Our wood products company specializes in offering customizable wooden signage for businesses, merging craftsmanship with branding to create unique visual identities. Each piece is meticulously crafted to reflect the essence of our clients' brands, ensuring that their message resonates with customers. By emphasizing quality and personalization, we empower businesses to make a lasting impression in their markets. Our dedication to artistry and customer collaboration positions us as a leader in the custom signage industry.

18. We are dedicated to creating a range of wooden toys made from natural materials, emphasizing safety and educational value for children. Our products are designed to inspire creativity and learning while adhering to the highest safety standards. By sourcing sustainable wood and employing eco-friendly practices, we ensure that our toys are not only fun but also contribute to a healthier planet. Our commitment to quality and education positions us as a trusted choice for parents seeking enriching play experiences for their children.

19. Our automotive technology firm is at the forefront of developing advanced driver-assistance systems (ADAS) for new vehicle manufacturers. By focusing on innovation and safety, we create solutions that enhance the driving experience while reducing risks on the road. Our systems integrate seamlessly with existing vehicle architectures, providing manufacturers with the tools they need to meet evolving safety standards and consumer expectations. Our commitment to excellence and technological advancement positions us as a leader in automotive safety technology.

20. We specialize in creating innovative chemical formulations for personal protective equipment, enhancing both safety and comfort for users. Our products are designed to meet the rigorous demands of various industries while ensuring that wearers can perform their tasks with confidence. By focusing on research and development, we continuously improve our formulations to address emerging safety challenges. Our dedication to quality and innovation positions us as a trusted partner in the field of personal protective equipment.
_
1. Our company is at the forefront of energy-efficient lighting solutions, specializing in the production of innovative light bulbs designed for the environmentally conscious consumer. By utilizing a direct-to-consumer sales strategy, we eliminate traditional retail overhead, allowing us to offer competitive pricing while maintaining high-quality standards. Our online platform not only streamlines the purchasing process but also fosters a direct relationship with our customers, enabling us to gather valuable feedback and continuously improve our product offerings. As we expand our product line, we remain committed to sustainability, ensuring that our bulbs consume less energy and have a longer lifespan, contributing positively to both consumer savings and environmental impact.

2. As a socially responsible brewery, we blend our passion for craft beer with a commitment to community engagement. A portion of our profits is dedicated to supporting local charities, creating a unique value proposition that resonates with our customers. This cause-driven approach not only enhances our brand loyalty but also encourages patrons to feel a sense of connection with our mission. Through community events and collaborative initiatives, we engage our customers in meaningful ways, fostering a culture of giving back while delivering high-quality brews that reflect our dedication to both craftsmanship and social impact.

3. Our company has revolutionized the construction tool market by designing multifunctional tools that adapt seamlessly to various tasks. This innovative approach reduces the need for extensive toolkits, making it easier for both professionals and DIY enthusiasts to tackle projects efficiently. Each tool is engineered for versatility, allowing users to switch between functions with ease, thus saving time and space. We are dedicated to continuous improvement, incorporating user feedback into our design process to ensure that our products not only meet but exceed the expectations of our diverse customer base.

4. We pride ourselves on being a leader in sustainable lumber production, sourcing our timber exclusively from certified forests that adhere to the highest environmental standards. Our commitment to eco-conscious practices resonates with builders and architects who prioritize sustainability in their projects. By offering a range of high-quality lumber products, we enable our clients to create beautiful, durable structures while minimizing their ecological footprint. Our partnerships with environmental organizations further reinforce our dedication to responsible forestry, ensuring that we contribute positively to the planet's health.

5. As a premier manufacturer of active pharmaceutical ingredients (APIs), we focus on delivering high-quality materials to leading drug companies worldwide. Our rigorous adherence to international quality standards ensures that our products meet the stringent requirements of the pharmaceutical industry. With a state-of-the-art facility and a team of experienced professionals, we are committed to innovation and excellence in every batch we produce. By fostering strong relationships with our clients, we not only provide reliable supply but also collaborate on developing tailored solutions that address their specific needs.

6. In a groundbreaking joint venture, we are collaborating with renewable energy firms to create hybrid systems that integrate solar and wind energy into traditional refining processes. This innovative approach not only enhances energy efficiency but also significantly reduces the carbon footprint associated with refining operations. By leveraging cutting-edge technology and shared expertise, we are paving the way for a more sustainable future in energy production. Our commitment to environmental stewardship drives us to explore new avenues for integrating renewable resources into our operations, ensuring long-term viability and compliance with evolving industry standards.

7. Our variable data printing service specializes in creating personalized marketing materials that resonate with individual customers. By harnessing the power of data analytics, we enable businesses to tailor their messaging, ensuring that each piece of communication is relevant and impactful. This approach not only enhances customer engagement but also drives conversion rates, making marketing efforts more effective. With a focus on innovation and quality, we continuously refine our printing techniques to deliver exceptional results that meet the dynamic needs of our clients.

8. Our subscription service offers urban dwellers the flexibility to swap vehicles on a monthly basis, catering to the evolving needs of city living. By providing access to a range of vehicles, we empower our members to choose the right car for their lifestyle, whether it's a compact for daily commutes or a spacious SUV for weekend getaways. This model not only promotes convenience but also encourages sustainable transportation choices, as members can select electric or hybrid options. Our seamless app experience ensures that vehicle selection and management are hassle-free, enhancing the overall user experience.

9. At our ceramics company, we collaborate closely with chefs to design custom dishware that elevates restaurant branding and presentation. By understanding the unique vision of each culinary artist, we create bespoke pieces that reflect their style and enhance the dining experience. Our commitment to quality craftsmanship ensures that every item not only looks stunning but also withstands the rigors of a busy kitchen. This partnership approach allows us to innovate continuously, pushing the boundaries of traditional ceramics to meet the specific needs of the food service industry.

10. We specialize in producing metal storage solutions that optimize warehouse space and enhance operational efficiency. Our customizable shelving systems are designed to adapt to various storage needs, allowing businesses to maximize their available square footage. By focusing on durability and functionality, we provide products that withstand the demands of a fast-paced environment while maintaining an organized workspace. Our commitment to customer satisfaction drives us to offer tailored solutions that meet the unique challenges faced by our clients in managing their inventory.

11. Our firm is dedicated to producing high-quality metal components specifically designed for renewable energy systems, with a focus on wind and solar power installations. By leveraging advanced manufacturing techniques, we ensure that our products meet the rigorous standards required for sustainable energy solutions. Our commitment to innovation drives us to continuously improve our processes, enhancing efficiency and reducing waste. As the demand for clean energy grows, we are proud to play a vital role in supporting the transition to a greener future.

12. As a leading chemical producer, we develop high-performance coatings tailored for the automotive industry, enhancing the durability and aesthetic appeal of vehicles. Our innovative formulations are designed to withstand harsh environmental conditions while providing a sleek finish that meets the demands of modern consumers. By investing in research and development, we stay ahead of industry trends, ensuring that our products not only meet but exceed the expectations of our clients. Our commitment to quality and performance drives our success in a competitive marketplace.


In [ ]:
# print prompts
for k,v in generated_data.items(): 
    print(k,"_______"*20)
    print(v["user_prompt"])

A ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats.



Here are some examples of descriptions of these classes:
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODEL
20. A firm specializing in the production of biodegradable packaging from agricultural waste, targeting eco-conscious brands and businesses.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse
C ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the physical or chemical transformation of materials, substances, or components into new products, although this cannot be used as the single universal criterion for defining manufacturing (see remark on processing of waste below). The materials, substances, or components transformed are raw materials that are products of agriculture, forestry, fishing, mining or quarrying as well as products of other manufacturing activities. Substantial alteration, renovation or reconstruction of goods is generally considered to be manufacturing.\n\nThe output of a manufacturing process may be finished in the sense that it is ready for utilisation or consumption, or it may be semi-finished in the sense that it is to become an input for further manufacturing. For example, the output of alumina refining is the input used in the primary production of aluminium; primary aluminium is the input to aluminium wire drawing; and aluminium wire is the input for the manufacture of fabricated wire products.\n\nManufacture of specialised components and parts of, and accessories and attachments to, machinery and equipment is, as a general rule, classified in the same class as the manufacture of the machinery and equipment for which the parts and accessories are intended. Manufacture of unspecialised components and parts of machinery and equipment, e.g. engines, pistons, electric motors, electrical assemblies, valves, gears, roller bearings, is classified in the appropriate class of manufacturing, without regard to the machinery and equipment in which these items may be included. However, making specialised components and accessories by moulding or extruding plastics materials is included in group 22.2.\n\nAssembly of the component parts of manufactured products is considered manufacturing. This includes the assembly of manufactured products from either self-produced or purchased components. \n\nThe recovery of waste, i.e. the processing of waste into secondary raw materials is classified in group 38.3 (Materials recovery). While this may involve physical or chemical transformations, this is not considered to be a part of manufacturing. The primary purpose of these activities is considered to be the treatment or processing of waste and they are therefore classified in Section E (Water supply; sewerage, waste management and remediation activities). However, the manufacture of new final products (as opposed to secondary raw materials) is classified in manufacturing, even if these processes use waste as an input. For example, the production of silver from film waste is considered to be a manufacturing process.\n\nSpecialised maintenance and repair of industrial, commercial and similar machinery and equipment is, in general, classified in division 33 (Repair, maintenance and installation of machinery and equipment). However, the repair of computers and personal and household goods is classified in division 95 (Repair of computers and personal and household goods), while the repair of motor vehicles is classified in division 45 (Wholesale and retail trade and repair of motor vehicles and motorcycles). \n\nThe installation of machinery and equipment, when carried out as a specialised activity, is classified in 33.20. \n\nRemark: The boundaries of manufacturing and the other sectors of the classification system can be somewhat blurry. As a general rule, the activities in the manufacturing section involve the transformation of materials into new products. Their output is a new product. However, the definition of what constitutes a new product can be somewhat subjective. As clarification, the following activities are considered manufacturing in NACE:\n- fresh fish processing (oyster shucking, fish filleting), not done on a fishing boat (see 10.20)\n- milk pasteurising and bottling (see 10.51)\n- leather converting (see 15.11)\n- wood preserving (see 16.10)\n- printing and related activities (see 18.1)\n- tyre retreading (see 22.11)\n- ready-mixed concrete production (see 23.63)\n- electroplating, plating, and metal heat treating (see 25.61)\n- rebuilding or remanufacture of machinery (e.g. automobile engines, see 29.10)\n\nConversely, there are activities that, although sometimes involving transformation processes, are classified in other sections of NACE; in other words, they are not classified as manufacturing. They include:\n- logging, classified in section A (Agriculture, forestry and fishing);\n- beneficiating of agricultural products, classified in section A (Agriculture, forestry and fishing); \n- preparation of food for immediate consumption on the premises is classified to division 56 (Food and beverage service activities);\n- beneficiating of ores and other minerals, classified in section B (Mining and quarrying); \n- construction of structures and fabricating operations performed at the site of construction, classified in section F (Construction);\n- activities of breaking bulk and redistribution in smaller lots, including packaging, repackaging, or bottling products, such as liquors or chemicals; sorting of scrap; mixing paints to customer order; and cutting metals to customer order; treatment not resulting into a different good is classified to section G (Wholesale and retail trade; repair of motor vehicles and motorcycles).



Here are some examples of descriptions of these classes:
```
Example 1:
We are a development stage biopharmaceutical company focused on discovering and developing novel and distinctive small molecule therapeutics that modulate G protein-coupled receptors, or GPCR, pathways. We are designing proprietary novel small molecule therapeutic candidates with the intent of developing best/first in class therapeutics for the treatment of metabolic, inflammatory and fibrotic diseases with significant unmet medical needs, using our integrated drug discovery platform, medicinal chemistry expertise and deep understanding of the GPCR biology.Our pipeline is currently made up of three development programs. The candidate we selected for clinical development, LMNL6511, a selective antagonist for the GPR84 receptor, is expected to commence a Phase 1 clinical trial in the second half of 2023. We are also developing potential OXER1 antagonists and GPR40 agonists, both of which are at the preclinical stage. In addition to these priority development programs, we continue to explore other development opportunities to add to our pipeline.We believe that our drug discovery platform and deep understanding of GPCRs allows us to identify small molecule candidates that can accurately target GPCRs where other drug discovery approaches have been unsuccessful. Our drug discovery platform leverages a fully integrated chemistry and biology expertise supported by our broad in vivo capabilities, which allows us to investigate our preclinical drug candidates' efficacy in a wide variety of animal models and enables us to develop small molecule therapeutic candidates for the treatment of various metabolic, inflammatory and fibrotic diseases. We aim to develop best or first-in-class therapies targeting indications with significant unmet needs, where a novel small molecule approach may be better suited using our drug discovery platform, specialized know-how and data-driven development plans.We are led by a strong, experienced team with proven track records in the discovery, development, and approval of biopharmaceuticals. Our team's extensive experience in clinical development, and regulatory success is backed by our data driven philosophy.

Example 2:
The company Biologics is a biopharma company focused on developing and commercializing innovative gene therapies for retinal neurodegenerative diseases and central nervous system disorders. The company is currently concentrating its efforts and resources on securing the upcoming LUMEVOQ validation campaign with its manufacturing partner in the US. Additionally, GenSight is discussing a financing bridge with certain existing shareholders to extend its cash runway beyond the results of the validation campaign expected in Q3 2023.

Example 3:
As a global leader in optical technologies, we harness the full spectrum of light to make life better. From product idea to tangible design through to the manufacturing process, we enable our customers to create high performance optical applications for the automotive, consumer, industrial and healthcare markets. What differentiates us, is our broad technology spectrum covering the emission of light as well as its detection through sensing and intelligent processing. We serve the value chain of optical solutions with our innovative products and solutions, which are designed for best-in class performance, size, cost and energy efficiency.We are experts in the development and integration of a wide range of optical technologies, from single components through to complex systems. This enables us to be a market and innovation leader, serve our customers as trusted partners and differentiate ourselves in the marketplace.
```

BUSINESS MODEL
20. **Manufacture of jewellery and related articles:** An artisan jeweller creating bespoke pieces using ethically sourced gemstones, targeting consumers interested in unique and sustainable jewellery.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse

#### Aggregate data and split

In [ ]:
# config

config = {
    "prompts": {k: v.get("user_prompt") for k, v in generated_data.items()}, 
    #"samples": num_samples * iterations_,
    #"generated_iterations": iterations_,
    "level": level,
    "head_nace_code": head_nace_code,
    "system_prompt": get_system_prompt(prompt_path), 
    "few_shot_prompting": few_shot
}

# store
import json
with open(os.path.join(store_path, "config.json"), "w") as f: 
    json.dump(config, f, indent=4)

In [ ]:
df_full = []
for k, v in generated_data.items(): 
    df_temp = pd.DataFrame(v["data"], columns=["text"])
    df_temp["label"] = k
    df_full.append(df_temp)
df_full = pd.concat(df_full, axis=0)
df_full = df_full.reset_index(drop=True)
df_full

                                                  text label
0    1. Our company is at the forefront of innovati...     C
1    2. As a dedicated manufacturer of specialized ...     C
2    3. At the heart of our woodworking company is ...     C
3    4. We are revolutionizing the logistics indust...     C
4    5. Our company provides mobile conveyor system...     C
..                                                 ...   ...
995  16. We offer a fishing gear rental service tha...     A
996  17. Our woodworking school teaches students th...     A
997  18. Operating as a regenerative agriculture fa...     A
998  19. Our fishing tourism venture offers guided ...     A
999  20. We have developed a subscription model for...     A

[1000 rows x 2 columns]

In [ ]:
import re
clean_text = lambda x: re.sub(r'^\d+\.\s*', " ", x).strip()

In [ ]:
df_full["text"] = df_full["text"].apply(clean_text)

In [ ]:
df_full.to_csv(os.path.join(store_path, "synthetic_data_full.csv"), index=False)

In [ ]:
# make train test split 6:2:2

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(df_full, test_size=0.4, random_state=42, stratify=df_full["label"])
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df["label"])

len(train_df), len(test_df), len(val_df)

(600, 200, 200)

In [ ]:
train_df.to_csv(os.path.join(store_path, "train_data.csv"), index=False)
test_df.to_csv(os.path.join(store_path, "test_data.csv"), index=False)
val_df.to_csv(os.path.join(store_path, "val_data.csv"), index=False)

In [272]:
llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=0.8
        )

In [ ]:
a =llm.invoke("""TASK 
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats. 



Here are some examples of descriptions of these classes: 
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODELS
0: A tech platform connects local wood suppliers with artisans looking for raw materials, streamlining the procurement process.
1: A company that offers consulting services to help landowners manage their forests for both timber and non-timber product extraction.
2: An organic dairy farm producing artisanal cheeses and yogurts, paired with a farm-to-table café on-site.
3: A cooperative that aggregates products from various mixed farms to sell under a single organic brand.
4: A sustainable sea cucumber farm that caters to niche markets in Asian health and culinary sectors.
5: An eco-friendly farm that integrates permaculture principles, offering educational courses and a variety of organic seasonal produce.

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse""")

In [279]:
print(a.content)

### Business Model Descriptions

**Business Model 0:**
The company operates an innovative tech platform that seamlessly connects local wood suppliers with artisans seeking high-quality raw materials for their crafts. By streamlining the procurement process, the platform enhances efficiency and accessibility for both suppliers and buyers. In addition to facilitating transactions, the company emphasizes transparency and sustainability, ensuring that sourced materials are harvested responsibly. This approach not only supports local economies but also fosters a vibrant community of creators dedicated to sustainable practices in their production processes.

**Business Model 1:**
Our company specializes in providing expert consulting services tailored for landowners aiming to optimize the management of their forests. We focus on both timber and non-timber product extraction, guiding clients through sustainable practices that enhance productivity while preserving ecosystem integrity. Our team of specialists collaborates closely with landowners, offering insights on forest health, resource sustainability, and market trends. This holistic approach empowers landowners to maximize their assets while contributing positively to the environment.

**Business Model 2:**
As an organic dairy farm, our company prides itself on producing exceptional artisanal cheeses and yogurts that reflect our commitment to quality and sustainability. We operate a farm-to-table café on-site, providing visitors with an immersive culinary experience that highlights our products. Through careful animal husbandry and organic practices, we ensure the highest standards of animal welfare and environmental stewardship. The café not only serves as a retail outlet but also as a venue for educating consumers about the benefits of organic farming and the importance of supporting local agriculture.

**Business Model 3:**
The company functions as a cooperative that aggregates diverse products from various mixed farms, uniting them under a single, recognized organic brand. By collaborating with local farmers, we ensure a wide range of high-quality produce that meets the growing consumer demand for organic options. Our cooperative model empowers farmers by providing them with greater market access and collective bargaining power, while our commitment to sustainability and ethical sourcing resonates with environmentally conscious consumers. This approach fosters a strong community of producers and fosters healthy, organic eating.

**Business Model 4:**
Specializing in sustainable aquaculture, our company operates a sea cucumber farm that targets niche markets in the Asian health and culinary sectors. By employing eco-friendly farming techniques, we cultivate high-quality sea cucumbers known for their nutritional benefits and culinary versatility. Our commitment to sustainability ensures that we maintain the delicate balance of marine ecosystems while providing premium products to our discerning customers. Through strategic partnerships and a focus on quality, we have established a strong presence in both local and international markets, meeting the needs of health-conscious consumers and gourmet chefs alike.

In [280]:
b = llm.invoke("""TASK 
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats. 



Here are some examples of descriptions of these classes: 
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODELS
0: A tech platform connects local wood suppliers with artisans looking for raw materials, streamlining the procurement process.
1: A company that offers consulting services to help landowners manage their forests for both timber and non-timber product extraction.
2: An organic dairy farm producing artisanal cheeses and yogurts, paired with a farm-to-table café on-site.
3: A cooperative that aggregates products from various mixed farms to sell under a single organic brand.
4: A sustainable sea cucumber farm that caters to niche markets in Asian health and culinary sectors.
5: An eco-friendly farm that integrates permaculture principles, offering educational courses and a variety of organic seasonal produce.
6: A mixed operation that incorporates agro-tourism, allowing visitors to experience crop harvesting while selling farm products on-site.
7: A forestry management consultancy that assists landowners in optimizing timber yield while maintaining ecological health in their forests.
8: A boutique retail shop that curates and sells handcrafted goods made from roundwood and wild forest products.
9: An organic vineyard that not only produces wine but also operates a farm-to-glass restaurant, providing farm tours and tastings.
10: A timber construction company specializing in homes built from locally sourced roundwood, emphasizing energy efficiency.
11: A community-supported fishery (CSF) that offers subscription boxes of seasonal, wild-caught fish directly from local fishermen to households.
12: A multi-generational family business that has been producing firewood and charcoal using traditional methods for decades.
13: A farm specializing in heirloom vegetables, providing seed shares to local gardeners and running seasonal pop-up markets.
14: A mixed farming operation that grows vegetables alongside specialty mushrooms, supplying local chefs with unique ingredients.
15: An online marketplace for niche forest products, connecting small producers of non-timber goods with a broader audience.
16: A permaculture farm that integrates tree crops, vegetables, and livestock to create a self-sustaining ecosystem.
17: An agribusiness that raises goats for milk and cheese production, selling to local markets and hosting farm visits for educational purposes.
18: A specialty farm that produces organic spices and herbs, targeting gourmet chefs and health food stores with unique offerings.
19: A cooperative that brings together mushroom growers and crop farmers to enhance biodiversity and offer unique farm products.

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse""")

In [281]:
print(b.content)

### Business Model Descriptions

**Business Model 0:**
The company operates a cutting-edge digital platform that serves as a bridge between local timber suppliers and artisans in need of raw materials. By streamlining the procurement process, the platform enhances efficiency and fosters direct connections among stakeholders, ensuring that artisans can access quality wood sustainably sourced from nearby regions. This innovative approach not only supports local economies but promotes responsible forestry practices.

**Business Model 1:**
This organization specializes in providing expert consulting services to landowners, focusing on sustainable forest management practices. The firm aids clients in maximizing both timber and non-timber product yields, while prioritizing ecological preservation. Through tailored management plans and ongoing support, the company empowers landowners to achieve economic benefits alongside environmental stewardship.

**Business Model 2:**
Located on a picturesque organic dairy farm, the company is dedicated to crafting artisanal cheeses and yogurts from high-quality milk. Complementing its production facilities is a charming farm-to-table café that highlights the farm's offerings, allowing visitors to savor fresh dairy products. This dual approach not only serves the community with delicious food but also educates consumers about sustainable agricultural practices.

**Business Model 3:**
Operating as a cooperative, this entity aggregates diverse products from a network of small mixed farms to market them under a unified organic brand. By bringing together various producers, the cooperative enhances visibility and accessibility of organic goods, catering to consumers who seek quality and sustainability in their food choices. This collective model fosters collaboration and strengthens the local agricultural community.

**Business Model 4:**
The company runs a sustainable sea cucumber farm, catering to niche markets in the health and culinary sectors across Asia. By adhering to environmentally friendly farming practices, the business not only provides a premium product but also contributes to the preservation of marine ecosystems. This focus on quality and sustainability positions the company as a leader in the specialty seafood market.

**Business Model 5:**
This eco-friendly farm embraces permaculture principles, creating a self-sustaining ecosystem that flourishes with organic seasonal produce. In addition to cultivation, the farm offers hands-on educational courses, empowering individuals to learn sustainable farming techniques. By integrating agriculture with education, the farm promotes a holistic approach to food production and environmental stewardship.

**Business Model 6:**
This innovative mixed farming operation combines traditional agriculture with agro-tourism, inviting visitors to participate in the crop harvesting experience. On-site, the farm sells its fresh produce directly to consumers, fostering a connection between people and the land. The immersive nature of the experience enhances community engagement while generating additional revenue streams for the business.

**Business Model 7:**
The company operates a forestry management consultancy, dedicated to assisting landowners in optimizing timber production while ensuring ecological integrity. With a focus on sustainable practices, the consultancy provides strategic insights and management solutions that enhance forest health and productivity. This balanced approach supports both economic viability and environmental care.

**Business Model 8:**
With a focus on artisan craftsmanship, this boutique retail shop curates a selection of handcrafted goods made from locally sourced roundwood and wild forest products. By showcasing the talents of local artisans, the shop serves as a platform for unique products while promoting the sustainable use of natural resources. This commitment to quality and locality resonates with environmentally conscious consumers.

**Business Model 9:**
This organic vineyard is dedicated to the craft of winemaking, producing a range of exceptional wines that reflect the terroir of its land. Additionally, the vineyard features a farm-to-glass restaurant, where guests can enjoy meals paired with wines from the estate. Offering farm tours and tastings, the business provides an immersive experience that connects visitors to the winemaking process and the natural environment.

**Business Model 10:**
Specializing in timber construction, the company builds energy-efficient homes using locally sourced roundwood. This commitment to sustainable building practices not only enhances the quality and durability of the homes but also supports local forestry initiatives. The company’s focus on environmentally friendly design aligns with the growing consumer demand for sustainable housing solutions.

**Business Model 11:**
Operating a community-supported fishery (CSF), the company provides subscription boxes of seasonal, wild-caught fish directly from local fishermen to households. This model fosters a direct connection between consumers and their food sources, promoting sustainable fishing practices while ensuring fresh, high-quality seafood. The CSF approach builds a community around shared values of sustainability and support for local fishers.

**Business Model 12:**
This multi-generational family business has been producing firewood and charcoal through traditional methods for decades. With a strong commitment to quality and craftsmanship, the company not only meets local demand but also champions sustainable practices in biomass production. The enduring legacy of the family business reinforces its reputation within the community.

**Business Model 13:**
Specializing in heirloom vegetables, this farm offers seed shares to local gardeners and actively participates in seasonal pop-up markets. By promoting biodiversity and encouraging community gardening, the farm not only enriches local food systems but also fosters a connection to heritage crops. This focus on local engagement supports sustainable agriculture and cultivates appreciation for diverse food sources.

**Business Model 14:**
This innovative mixed farming operation grows a variety of vegetables in tandem with specialty mushrooms, supplying local chefs with unique and high-quality ingredients. By enhancing biodiversity on the farm, the operation not only boosts resilience but also meets the increasing demand for unique culinary products. The commitment to local sourcing strengthens ties within the culinary community.

**Business Model 15:**
An online marketplace specializing in niche forest products, this company connects small producers of non-timber goods with a broader audience. By leveraging digital technology, the marketplace enhances visibility for unique offerings while promoting sustainable resource use. This platform empowers local artisans and producers, fostering economic opportunities in the forest products sector.

**Business Model 16:**
This permaculture farm integrates tree crops, vegetables, and livestock to create a self-sustaining ecosystem. Through holistic management practices, the farm promotes biodiversity and resilience while providing a diverse array of products. The emphasis on sustainable practices not only enhances productivity but educates consumers on the benefits of integrated farming systems.

**Business Model 17:**
Focused on raising goats for milk and cheese production, this agribusiness serves local markets while hosting educational farm visits. By engaging the community, the company enhances awareness of sustainable dairy practices and fosters a connection between consumers and their food sources. This dual approach not only drives sales but also promotes a culture of transparency in food production.

**Business Model 18:**
This specialty farm is committed to producing organic spices and herbs, targeting gourmet chefs and health-conscious consumers with unique offerings. By focusing on quality and sustainability, the farm positions itself at the intersection of culinary excellence and health trends. The emphasis on organic practices underscores the company's dedication to both quality and environmental responsibility.

**Business Model 19:**
As a cooperative, this organization unites mushroom growers and crop farmers to enhance biodiversity and create distinctive farm products. By facilitating collaboration among producers, the cooperative not only increases product diversity but also fosters sustainable agricultural practices. This synergistic approach benefits both the environment and the local economy, reinforcing community connections.