In [1]:
import pandas as pd
import os
import json
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from tqdm import tqdm
import datetime

In [41]:
os.chdir('/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis')

In [42]:
%pwd

'/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis'

In [44]:
nace_description_path = "data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv"
nace_descriptions = pd.read_csv(nace_description_path, sep="\t")

In [2]:
def get_zero_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_zero_shot"]

def get_few_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_few_shot"]

def get_system_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["system_prompt"]

In [3]:
user_prompt_topic = """
TASK
For the following business sector, create short descriptions of realistic business models for exisiting companies. 

\nDEFINITION
\n{includes} {includes_also}
\n
\n{excludes}
\n
\nHere are some possible subsections: {subsections}

INSTRUCTION
- Create a list of {num_samples} different realistic explanations of a business model 
- The length should be one sentence
- Pick one or multiple subsections for this business model
- Do not explain what you did or what you used
"""

In [47]:
def generate_topic(
        num_samples: int, 
        includes: str,
        includes_also: str, 
        excludes: str,
        subsections: list,
        prompt_path: str,  
        temperature: float = 0.4, 
        model: str = "gpt-4o-mini"
): 

    # Initialize LLM
    if model == "gpt-4o-mini":
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=temperature
        )
    elif model == "openai/gpt-oss-120b":
        llm = ChatOllama(
            model=model,
            temperature=temperature, 
            base_url="http://10.80.20.127:11434/"
        )


    prompt = ChatPromptTemplate.from_messages([
        ("system", ""),
        ("human", user_prompt_topic)
    ])

    # Subsections string
    subsections_str = "\n - " + "\n - ".join(subsections)

    # Adapt excludes
    if excludes != "": 
        excludes = "Excludes: " + excludes

    # Chain
    chain = prompt | llm

    # inputs
    input = {
        "num_samples": num_samples,
        "includes": includes,
        "includes_also": includes_also,
        "excludes": excludes,
        "subsections": subsections_str,
        }

    formatted_prompt = prompt.invoke(input)

    #print("Formatted Prompt:", formatted_prompt)

    # Run
    response = chain.invoke(input)

    #print(response.content)

    return formatted_prompt, response.content

In [48]:
def generate_synthetic_data(
        num_samples: int, 
        gold_standard: list, 
        includes: str,
        includes_also: str, 
        excludes: str,
        subsections: list,
        prompt_path: str,  
        temperature: float = 0.4, 
        model: str = "gpt-4o-mini", 
        topic: str = None
): 

    # Initialize LLM
    if model == "gpt-4o-mini":
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=temperature
        )
    elif model == "openai/gpt-oss-120b":
        llm = ChatOllama(
            model=model,
            temperature=temperature, 
            base_url="http://10.80.20.127:11434/"
        )

    # Prompt
    if gold_standard == []: 
        #print("Zero Shot!")
        prompt = ChatPromptTemplate.from_messages([
            ("system", get_system_prompt(prompt_path)),
            ("human", get_zero_shot_user_prompt(prompt_path))
        ])
        gold_standard_str = ""
        
    else: 
        prompt = ChatPromptTemplate.from_messages([
            ("system", get_system_prompt(prompt_path)),
            ("human", get_few_shot_user_prompt(prompt_path))
        ])
        gold_standard_str = ""
        for i, text in enumerate(gold_standard): 
            gold_standard_str += f"Example {i+1}:\n{text}\n\n"
        gold_standard_str = gold_standard_str[:-2]

    # Subsections string
    subsections_str = "\n - " + "\n - ".join(subsections)

    # Adapt excludes
    if excludes != "": 
        excludes = "Excludes: " + excludes

    # Chain
    chain = prompt | llm

    # inputs
    input = {
        "num_samples": num_samples,
        "gold_standard": gold_standard_str,
        "includes": includes,
        "includes_also": includes_also,
        "excludes": excludes,
        "subsections": subsections_str,
        }
    print(prompt)
    # is topic used? topic in params -> business model must be in user prompt
    if topic is not None:
        if "business_model" not in prompt.input_variables: 
            print("If topic is given, prompt must conatin '{business_model}'")
            return False
        else: 
            input["business_model"] = topic

    formatted_prompt = prompt.invoke(input)

    #print("Formatted Prompt:", formatted_prompt)

    # Run
    response = chain.invoke(input)

    #print(response.content)

    return formatted_prompt, response.content

In [49]:
def split_synthetic_data(content: str, num_samples: int): 
    content_list = content.split("\n")
    content_list = [c for c in content_list if c != ""]
    # if len(content_list) != num_samples: 
    #     print("Warning: length of creates examples != num_samples!")
    return content_list

In [50]:
def get_sublevels(nace_class, level): 
    nace_class_temp = nace_class
    nace_id = nace_descriptions[nace_descriptions["CODE"] == nace_class_temp]["ID"].iloc[0]
    nace_class_lvl_2 = []
    nace_class_lvl_3 = []
    nace_class_lvl_4 = []

    for _, row in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id].iterrows(): 
        nace_id_temp = row["ID"]
        nace_class_lvl_2.append(f'{row["NAME"]}')
        for _, row_2 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp].iterrows(): 
            nace_id_temp_temp = row_2["ID"]
            nace_class_lvl_3.append(f'{row["NAME"]}: {row_2["NAME"]}')
            for _, row_3 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp_temp].iterrows(): 
                nace_class_lvl_4.append(f'{row["NAME"]}: {row_2["NAME"]}: {row_3["NAME"]}')
        
    if level == 2: 
        return nace_class_lvl_2
    if level == 3: 
        return nace_class_lvl_3
    if level == 4: 
        return nace_class_lvl_4

In [51]:
generate_nace_class = "A"

includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
assert includes is not None and includes != ""
includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
includes_also = "" if pd.isna(includes_also) else includes_also
excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
excludes = "" if pd.isna(excludes) else excludes

num_samples = 2
gold_standard = ["A fischeeeee", "A Weizeeeen"]
gold_standard = []

## Generate Few-Shot Data

In [52]:
# select gold standard data

# ds_2_desc  = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")

# ds_2_desc  = ds_2_desc[pd.notna(ds_2_desc["Description"])]

# gold_standard = []
# # 1. take one of each lvl 3 class:
# for lvl_3 in ds_2_desc[pd.notna(ds_2_desc["Description"])].groupby("NACE_lvl_3").size().index: 
#     gold_standard.append(ds_2_desc[ds_2_desc["NACE_lvl_3"] == lvl_3].iloc[0])

# df_gold_standard = pd.concat(gold_standard, axis=1).T

#df_gold_standard.to_csv("/Users/hendrikweichel/Downloads/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv")

In [53]:
#df_gold_standard = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")
df_gold_standard = pd.read_csv("data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")

### Hyperparams

In [54]:
prompt_path = "generate_synthetic_data/prompts/prompts_5.json"
print(get_system_prompt(prompt_path))
print()
print(get_few_shot_user_prompt(prompt_path))

You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms


TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
{includes} {includes_also}

{excludes}

Here are some examples of descriptions of these classes:
```
{gold_standard}
```

BUSINESS MODEL
{business_model}

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse

In [55]:
level = 1
head_nace_code = "1" if level > 1 else None
generated_classes = nace_descriptions[nace_descriptions["PARENT_ID"] == head_nace_code]["CODE"]
few_shot = True

In [56]:
# generate date 

date = datetime.datetime.now().strftime("%Y%m%d")
date = "20251218"
suffix = "__few_shot" if few_shot else "__zero_shot"
store_path = "data/synthetic_data/data_" + date + f"__level_{level}__subclasses_{head_nace_code}__{os.path.basename(prompt_path).replace('.json', '')}{suffix}/" 
os.makedirs(store_path, exist_ok=True)

In [57]:
generated_data = {}

In [58]:
generated_classes = ["A", "B", "C", "J", "F"]
generated_classes = ["A", "C"]

In [59]:
# load previous results
prev_results = "projects/nace_classification/nace_report_topic_analysis/data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot/class_A.csv"
prev_results = "data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot"
for class_name in generated_classes: 
   file_path = os.path.join(prev_results, f"class_{class_name}.csv")
   try:
       df = pd.read_csv(file_path)
       generated_data[class_name] = {
           "data": df[class_name].tolist()
       }
   except Exception as e:
       print(f"Could not load previous results for class {class_name}: {e}")

### Generate Topics

In [63]:
num_samples = 5
iterations_ = 20

In [64]:
topics = {}

for generate_nace_class in generated_classes[1:]:

    includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
    if pd.isna(includes):
        print("No description for class:", generate_nace_class)
        continue
    includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
    includes_also = "" if pd.isna(includes_also) else includes_also
    excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
    excludes = "" if pd.isna(excludes) else excludes

    subsections = get_sublevels(generate_nace_class, level=4)

    examples = []

    for i in tqdm(range(iterations_), desc=generate_nace_class):
        res = generate_topic(num_samples=num_samples, 
                             includes=includes, 
                             includes_also=includes_also, 
                             excludes=excludes, 
                             subsections=subsections, 
                             prompt_path=prompt_path, 
                             model="gpt-4o-mini", 
                             temperature=0.8)
        examples.append(res[1])
        data = split_synthetic_data("\n\n".join(examples), num_samples * iterations_)
        if len(data) >= num_samples * iterations_:
            break

    results = {
        "topics": data,
        "prompt": res[0],
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": examples,
        "few_shot": few_shot
    }

    topics[generate_nace_class] = results

C:   5%|████████▊                                                                                                                                                                      | 1/20 [00:10<03:24, 10.79s/it]

KeyboardInterrupt:

In [66]:
print(res[0].messages[1].content)

TASK
For the following business sector, create short descriptions of realistic business models for exisiting companies.


DEFINITION

This section includes the physical or chemical transformation of materials, substances, or components into new products, although this cannot be used as the single universal criterion for defining manufacturing (see remark on processing of waste below). The materials, substances, or components transformed are raw materials that are products of agriculture, forestry, fishing, mining or quarrying as well as products of other manufacturing activities. Substantial alteration, renovation or reconstruction of goods is generally considered to be manufacturing.\n\nThe output of a manufacturing process may be finished in the sense that it is ready for utilisation or consumption, or it may be semi-finished in the sense that it is to become an input for further manufacturing. For example, the output of alumina refining is the input used in the primary production of aluminium; primary aluminium is the input to aluminium wire drawing; and aluminium wire is the input for the manufacture of fabricated wire products.\n\nManufacture of specialised components and parts of, and accessories and attachments to, machinery and equipment is, as a general rule, classified in the same class as the manufacture of the machinery and equipment for which the parts and accessories are intended. Manufacture of unspecialised components and parts of machinery and equipment, e.g. engines, pistons, electric motors, electrical assemblies, valves, gears, roller bearings, is classified in the appropriate class of manufacturing, without regard to the machinery and equipment in which these items may be included. However, making specialised components and accessories by moulding or extruding plastics materials is included in group 22.2.\n\nAssembly of the component parts of manufactured products is considered manufacturing. This includes the assembly of manufactured products from either self-produced or purchased components. \n\nThe recovery of waste, i.e. the processing of waste into secondary raw materials is classified in group 38.3 (Materials recovery). While this may involve physical or chemical transformations, this is not considered to be a part of manufacturing. The primary purpose of these activities is considered to be the treatment or processing of waste and they are therefore classified in Section E (Water supply; sewerage, waste management and remediation activities). However, the manufacture of new final products (as opposed to secondary raw materials) is classified in manufacturing, even if these processes use waste as an input. For example, the production of silver from film waste is considered to be a manufacturing process.\n\nSpecialised maintenance and repair of industrial, commercial and similar machinery and equipment is, in general, classified in division 33 (Repair, maintenance and installation of machinery and equipment). However, the repair of computers and personal and household goods is classified in division 95 (Repair of computers and personal and household goods), while the repair of motor vehicles is classified in division 45 (Wholesale and retail trade and repair of motor vehicles and motorcycles). \n\nThe installation of machinery and equipment, when carried out as a specialised activity, is classified in 33.20. \n\nRemark: The boundaries of manufacturing and the other sectors of the classification system can be somewhat blurry. As a general rule, the activities in the manufacturing section involve the transformation of materials into new products. Their output is a new product. However, the definition of what constitutes a new product can be somewhat subjective. As clarification, the following activities are considered manufacturing in NACE:\n- fresh fish processing (oyster shucking, fish filleting), not done on a fishing boat (see 10.20)\n- milk pasteurising and bottling (see 10.51)\n- leather converting (see 15.11)\n- wood preserving (see 16.10)\n- printing and related activities (see 18.1)\n- tyre retreading (see 22.11)\n- ready-mixed concrete production (see 23.63)\n- electroplating, plating, and metal heat treating (see 25.61)\n- rebuilding or remanufacture of machinery (e.g. automobile engines, see 29.10)\n\nConversely, there are activities that, although sometimes involving transformation processes, are classified in other sections of NACE; in other words, they are not classified as manufacturing. They include:\n- logging, classified in section A (Agriculture, forestry and fishing);\n- beneficiating of agricultural products, classified in section A (Agriculture, forestry and fishing); \n- preparation of food for immediate consumption on the premises is classified to division 56 (Food and beverage service activities);\n- beneficiating of ores and other minerals, classified in section B (Mining and quarrying); \n- construction of structures and fabricating operations performed at the site of construction, classified in section F (Construction);\n- activities of breaking bulk and redistribution in smaller lots, including packaging, repackaging, or bottling products, such as liquors or chemicals; sorting of scrap; mixing paints to customer order; and cutting metals to customer order; treatment not resulting into a different good is classified to section G (Wholesale and retail trade; repair of motor vehicles and motorcycles).







Here are some possible subsections:
 - Manufacture of food products: Processing and preserving of meat and production of meat products: Processing and preserving of meat
 - Manufacture of food products: Processing and preserving of meat and production of meat products: Processing and preserving of poultry meat
 - Manufacture of food products: Processing and preserving of meat and production of meat products: Production of meat and poultry meat products
 - Manufacture of food products: Processing and preserving of fish, crustaceans and molluscs: Processing and preserving of fish, crustaceans and molluscs
 - Manufacture of food products: Processing and preserving of fruit and vegetables: Processing and preserving of potatoes
 - Manufacture of food products: Processing and preserving of fruit and vegetables: Manufacture of fruit and vegetable juice
 - Manufacture of food products: Processing and preserving of fruit and vegetables: Other processing and preserving of fruit and vegetables
 - Manufacture of food products: Manufacture of vegetable and animal oils and fats: Manufacture of oils and fats
 - Manufacture of food products: Manufacture of vegetable and animal oils and fats: Manufacture of margarine and similar edible fats
 - Manufacture of food products: Manufacture of dairy products: Operation of dairies and cheese making
 - Manufacture of food products: Manufacture of dairy products: Manufacture of ice cream
 - Manufacture of food products: Manufacture of grain mill products, starches and starch products: Manufacture of grain mill products
 - Manufacture of food products: Manufacture of grain mill products, starches and starch products: Manufacture of starches and starch products
 - Manufacture of food products: Manufacture of bakery and farinaceous products: Manufacture of bread; manufacture of fresh pastry goods and cakes
 - Manufacture of food products: Manufacture of bakery and farinaceous products: Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes
 - Manufacture of food products: Manufacture of bakery and farinaceous products: Manufacture of macaroni, noodles, couscous and similar farinaceous products
 - Manufacture of food products: Manufacture of other food products: Manufacture of sugar
 - Manufacture of food products: Manufacture of other food products: Manufacture of cocoa, chocolate and sugar confectionery
 - Manufacture of food products: Manufacture of other food products: Processing of tea and coffee
 - Manufacture of food products: Manufacture of other food products: Manufacture of condiments and seasonings
 - Manufacture of food products: Manufacture of other food products: Manufacture of prepared meals and dishes
 - Manufacture of food products: Manufacture of other food products: Manufacture of homogenised food preparations and dietetic food
 - Manufacture of food products: Manufacture of other food products: Manufacture of other food products n.e.c.
 - Manufacture of food products: Manufacture of prepared animal feeds: Manufacture of prepared feeds for farm animals
 - Manufacture of food products: Manufacture of prepared animal feeds: Manufacture of prepared pet foods
 - Manufacture of beverages: Manufacture of beverages: Distilling, rectifying and blending of spirits
 - Manufacture of beverages: Manufacture of beverages: Manufacture of wine from grape
 - Manufacture of beverages: Manufacture of beverages: Manufacture of cider and other fruit wines
 - Manufacture of beverages: Manufacture of beverages: Manufacture of other non-distilled fermented beverages
 - Manufacture of beverages: Manufacture of beverages: Manufacture of beer
 - Manufacture of beverages: Manufacture of beverages: Manufacture of malt
 - Manufacture of beverages: Manufacture of beverages: Manufacture of soft drinks; production of mineral waters and other bottled waters
 - Manufacture of tobacco products: Manufacture of tobacco products: Manufacture of tobacco products
 - Manufacture of textiles: Preparation and spinning of textile fibres: Preparation and spinning of textile fibres
 - Manufacture of textiles: Weaving of textiles: Weaving of textiles
 - Manufacture of textiles: Finishing of textiles: Finishing of textiles
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of knitted and crocheted fabrics
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of made-up textile articles, except apparel
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of carpets and rugs
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of cordage, rope, twine and netting
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of non-wovens and articles made from non-wovens, except apparel
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of other technical and industrial textiles
 - Manufacture of textiles: Manufacture of other textiles: Manufacture of other textiles n.e.c.
 - Manufacture of wearing apparel: Raising of dairy cattle: Manufacture of leather clothes
 - Manufacture of wearing apparel: Raising of dairy cattle: Manufacture of workwear
 - Manufacture of wearing apparel: Raising of dairy cattle: Manufacture of other outerwear
 - Manufacture of wearing apparel: Raising of dairy cattle: Manufacture of underwear
 - Manufacture of wearing apparel: Raising of dairy cattle: Manufacture of other wearing apparel and accessories
 - Manufacture of wearing apparel: Raising of other cattle and buffaloes: Manufacture of articles of fur
 - Manufacture of wearing apparel: Raising of horses and other equines: Manufacture of knitted and crocheted hosiery
 - Manufacture of wearing apparel: Raising of horses and other equines: Manufacture of other knitted and crocheted apparel
 - Manufacture of wearing apparel: Manufacture of wearing apparel, except fur apparel: Manufacture of leather clothes
 - Manufacture of wearing apparel: Manufacture of wearing apparel, except fur apparel: Manufacture of workwear
 - Manufacture of wearing apparel: Manufacture of wearing apparel, except fur apparel: Manufacture of other outerwear
 - Manufacture of wearing apparel: Manufacture of wearing apparel, except fur apparel: Manufacture of underwear
 - Manufacture of wearing apparel: Manufacture of wearing apparel, except fur apparel: Manufacture of other wearing apparel and accessories
 - Manufacture of wearing apparel: Manufacture of articles of fur: Manufacture of articles of fur
 - Manufacture of wearing apparel: Manufacture of knitted and crocheted apparel: Manufacture of knitted and crocheted hosiery
 - Manufacture of wearing apparel: Manufacture of knitted and crocheted apparel: Manufacture of other knitted and crocheted apparel
 - Manufacture of leather and related products: Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur: Tanning and dressing of leather; dressing and dyeing of fur
 - Manufacture of leather and related products: Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur: Manufacture of luggage, handbags and the like, saddlery and harness
 - Manufacture of leather and related products: Manufacture of footwear: Manufacture of footwear
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for crop production: Sawmilling and planing of wood
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for animal production: Manufacture of veneer sheets and wood-based panels
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for animal production: Manufacture of assembled parquet floors
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for animal production: Manufacture of other builders' carpentry and joinery
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for animal production: Manufacture of wooden containers
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Support activities for animal production: Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Sawmilling and planing of wood: Sawmilling and planing of wood
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Manufacture of products of wood, cork, straw and plaiting materials: Manufacture of veneer sheets and wood-based panels
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Manufacture of products of wood, cork, straw and plaiting materials: Manufacture of assembled parquet floors
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Manufacture of products of wood, cork, straw and plaiting materials: Manufacture of other builders' carpentry and joinery
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Manufacture of products of wood, cork, straw and plaiting materials: Manufacture of wooden containers
 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials: Manufacture of products of wood, cork, straw and plaiting materials: Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials
 - Manufacture of paper and paper products: Manufacture of pulp, paper and paperboard: Manufacture of pulp
 - Manufacture of paper and paper products: Manufacture of pulp, paper and paperboard: Manufacture of paper and paperboard
 - Manufacture of paper and paper products: Manufacture of articles of paper and paperboard: Manufacture of corrugated paper and paperboard and of containers of paper and paperboard
 - Manufacture of paper and paper products: Manufacture of articles of paper and paperboard: Manufacture of household and sanitary goods and of toilet requisites
 - Manufacture of paper and paper products: Manufacture of articles of paper and paperboard: Manufacture of paper stationery
 - Manufacture of paper and paper products: Manufacture of articles of paper and paperboard: Manufacture of wallpaper
 - Manufacture of paper and paper products: Manufacture of articles of paper and paperboard: Manufacture of other articles of paper and paperboard
 - Printing and reproduction of recorded media: Printing and service activities related to printing: Printing of newspapers
 - Printing and reproduction of recorded media: Printing and service activities related to printing: Other printing
 - Printing and reproduction of recorded media: Printing and service activities related to printing: Pre-press and pre-media services
 - Printing and reproduction of recorded media: Printing and service activities related to printing: Binding and related services
 - Printing and reproduction of recorded media: Reproduction of recorded media: Reproduction of recorded media
 - Manufacture of coke and refined petroleum products: Manufacture of coke oven products: Manufacture of coke oven products
 - Manufacture of coke and refined petroleum products: Manufacture of refined petroleum products: Manufacture of refined petroleum products
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of industrial gases
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of dyes and pigments
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of other inorganic basic chemicals
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of other organic basic chemicals
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of fertilisers and nitrogen compounds
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of plastics in primary forms
 - Manufacture of chemicals and chemical products: Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms: Manufacture of synthetic rubber in primary forms
 - Manufacture of chemicals and chemical products: Manufacture of pesticides and other agrochemical products: Manufacture of pesticides and other agrochemical products
 - Manufacture of chemicals and chemical products: Manufacture of paints, varnishes and similar coatings, printing ink and mastics: Manufacture of paints, varnishes and similar coatings, printing ink and mastics
 - Manufacture of chemicals and chemical products: Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations: Manufacture of soap and detergents, cleaning and polishing preparations
 - Manufacture of chemicals and chemical products: Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations: Manufacture of perfumes and toilet preparations
 - Manufacture of chemicals and chemical products: Manufacture of other chemical products: Manufacture of explosives
 - Manufacture of chemicals and chemical products: Manufacture of other chemical products: Manufacture of glues

In [95]:
for e in examples: 
    print("---")
    print(e)

---
1. **Processing and preserving of meat:** A company specializing in the production of premium, ready-to-eat jerky from locally sourced, grass-fed beef and poultry, targeting health-conscious consumers.

2. **Manufacture of dairy products:** A dairy cooperative that produces organic cheese using traditional recipes and sustainable practices, distributing through local farmer's markets and upscale grocery stores.

3. **Manufacture of beverages:** A craft brewery creating small-batch, artisanal beers with unique flavor profiles, focusing on local ingredients and sustainable brewing methods.

4. **Manufacture of bakery and farinaceous products:** A bakery that offers gluten-free pastries and breads, catering to the growing demand for alternative dietary options in urban areas.

5. **Manufacture of grain mill products:** A company producing whole grain flours from heirloom grains, providing organic options to consumers and local bakeries through direct sales.

6. **Manufacture of prepared animal feeds:** A manufacturer of all-natural, organic pet food, utilizing human-grade ingredients and focusing on transparency in sourcing and production processes.

7. **Manufacture of vegetable and animal oils and fats:** A business specializing in cold-pressed oils from local seeds and nuts, promoting sustainable farming practices and health benefits of natural oils.

8. **Manufacture of textiles:** A company producing sustainable fashion using organic cotton and recycled materials, targeting eco-conscious consumers through direct-to-consumer sales.

9. **Manufacture of footwear:** A shoemaker creating bespoke leather footwear with a focus on sustainability, using ethically sourced materials and local craftsmanship.

10. **Manufacture of paper and paper products:** An eco-friendly paper company that produces recycled paper products, targeting businesses committed to sustainability and reducing waste.

11. **Manufacture of furniture:** A custom furniture maker that specializes in upcycled wood furniture, appealing to consumers interested in sustainable and unique home décor.

12. **Manufacture of glass and glass products:** A business that creates decorative glassware using reclaimed glass, focusing on artistic designs and environmentally friendly production techniques.

13. **Manufacture of chemicals and chemical products:** A company producing biodegradable cleaning products, targeting both residential and commercial clients seeking eco-friendly solutions.

14. **Manufacture of rubber and plastic products:** A manufacturer that uses recycled plastics to produce durable outdoor furniture, appealing to environmentally conscious consumers.

15. **Manufacture of motor vehicles:** An electric vehicle startup focusing on affordable city cars, utilizing innovative battery technology to reduce emissions and promote urban mobility.

16. **Manufacture of basic metals:** A company specializing in the production of high-strength steel for construction, emphasizing quality and safety standards in its manufacturing processes.

17. **Manufacture of medical and dental instruments and supplies:** A manufacturer of 3D-printed surgical tools, offering custom solutions to healthcare providers for improved surgical outcomes.

18. **Manufacture of other non-metallic mineral products:** A company producing ceramic tiles from sustainable materials, targeting eco-friendly building projects and renovations.

19. **Manufacture of sports goods:** A business specializing in custom sports equipment for fitness enthusiasts, utilizing innovative materials and designs to enhance athletic performance.

20. **Manufacture of jewellery and related articles:** An artisan jeweller creating bespoke pieces using ethically sourced gemstones, targeting consumers interested in unique and sustainable jewellery.

21. **Manufacture of soft drinks:** A company producing organic, low-sugar sodas using natural sweeteners and flavors, catering to health-conscious consumers seeking alternatives to traditional soft drinks.

22. **Manufacture of frozen foods:** A brand that specializes in frozen, organic meal kits, appealing to busy consumers looking for healthy and convenient dining options.

23. **Manufacture of cosmetics:** A beauty company focusing on cruelty-free, vegan skincare products made from natural ingredients, targeting conscious consumers in the wellness industry.

24. **Manufacture of farm machinery:** A manufacturer of precision agricultural equipment designed to optimize crop yields while reducing environmental impact, focusing on smart farming technologies.

25. **Manufacture of construction materials:** A company producing eco-friendly insulation materials from recycled paper, catering to the green building sector.

26. **Manufacture of toys:** An educational toy manufacturer focusing on eco-friendly materials that promote STEM learning for children, appealing to parents seeking sustainable options.

27. **Manufacture of musical instruments:** A luthier creating handcrafted guitars using sustainable wood, targeting musicians who value quality craftsmanship and environmental responsibility.

28. **Manufacture of candles:** A candle company producing natural, non-toxic candles with unique scents, focusing on artisanal quality and eco-friendly practices.

29. **Manufacture of home appliances:** A manufacturer of energy-efficient kitchen appliances designed for small spaces, appealing to urban dwellers looking for sustainable home solutions.

30. **Manufacture of packaging products:** A business producing biodegradable packaging solutions for e-commerce brands, targeting companies committed to reducing plastic waste.

31. **Manufacture of leather and related products:** A company that designs and produces sustainable leather goods from vegetable-tanned leather, catering to eco-conscious consumers.

32. **Manufacture of essential oils:** A manufacturer of therapeutic-grade essential oils sourced from organic farms, targeting the wellness and aromatherapy markets.

33. **Manufacture of fragrances:** A niche perfume maker creating custom fragrances using natural ingredients, appealing to clients looking for personalized scent experiences.

34. **Manufacture of renewable energy equipment:** A company producing solar panels tailored for residential use, emphasizing affordability and efficiency in renewable energy solutions.

35. **Manufacture of pharmaceuticals:** A biotech firm specializing in personalized medicine, leveraging genetic data to develop targeted therapies for chronic diseases.

36. **Manufacture of knitwear:** A company producing hand-knit, sustainable wool sweaters, targeting consumers looking for unique and eco-friendly fashion options.

37. **Manufacture of tools:** A business specializing in high-quality, precision hand tools for woodworking, appealing to both hobbyists and professional carpenters.

38. **Manufacture of industrial machinery:** A manufacturer of automated assembly line solutions focusing on efficiency and reliability for the automotive industry.

39. **Manufacture of biofuels:** A company producing biodiesel from waste cooking oil, targeting environmentally conscious consumers and businesses seeking sustainable energy solutions.

40. **Manufacture of home décor:** A business creating artisanal home décor products from reclaimed materials, focusing on sustainability and unique design.

41. **Manufacture of cleaning supplies:** An eco-friendly cleaning supply company producing biodegradable products for both home and commercial use, targeting green businesses.

42. **Manufacture of printed materials:** A printing company specializing in sustainable printing practices, focusing on recycled papers and soy-based inks for marketing materials.

43. **Manufacture of fishing gear:** A company producing sustainable fishing tackle and gear made from recycled materials, appealing to environmentally conscious anglers.

44. **Manufacture of garden supplies:** A manufacturer of organic fertilizers and soil amendments, targeting home gardeners focused on sustainable practices.

45. **Manufacture of pet products:** A business creating eco-friendly pet toys made from recycled materials, appealing to pet owners who prioritize sustainability.

46. **Manufacture of home textiles:** A company specializing in organic cotton bedding and linens, targeting health-conscious consumers seeking toxin-free products.

47. **Manufacture of bicycles:** A manufacturer producing lightweight, electric bicycles designed for urban commuting, appealing to eco-friendly transportation enthusiasts.

48. **Manufacture of knitwear:** A company producing hand-knitted, sustainable fashion accessories, focusing on local craftsmanship and community engagement.

49. **Manufacture of health supplements:** A business producing plant-based dietary supplements targeting fitness enthusiasts and health-conscious consumers.

50. **Manufacture of baby products:** A company specializing in organic, non-toxic baby furniture and accessories, appealing to parents looking for safe and sustainable options.
---
1. A company specializing in the processing and preserving of poultry meat uses advanced chilling technology to extend shelf life while ensuring quality for restaurants and retailers.

2. A juice manufacturer utilizes locally sourced fruits to create organic beverages, focusing on sustainable practices and eco-friendly packaging to attract health-conscious consumers.

3. A bakery produces a range of gluten-free products, catering to the increasing demand for dietary alternatives in the bakery and farinaceous products sector.

4. An ice cream manufacturer combines artisanal techniques with innovative flavors, sourcing natural ingredients to appeal to gourmet ice cream lovers.

5. A meat processing plant specializes in halal-certified meats, targeting both domestic and international markets that prioritize religious dietary laws.

6. A soft drink company utilizes reclaimed water in its production process, promoting sustainability while maintaining high-quality beverage standards.

7. A pet food manufacturer creates premium dog and cat foods using only organic ingredients, tapping into the growing trend of pet humanization.

8. A brewery produces craft beers using traditional methods and unique local ingredients, enhancing regional flavors and supporting local agriculture.

9. A chocolate manufacturer offers vegan and sugar-free options, leveraging health trends while maintaining indulgent flavor profiles for confectionery products.

10. A dairy processor focuses on small-batch cheese production, allowing for artisanal quality and unique flavor variations tailored to local tastes.

11. A textile manufacturer specializes in eco-friendly fabrics dyed with natural pigments, appealing to environmentally conscious fashion brands.

12. A company designs and manufactures ergonomic office furniture, responding to the growing demand for health and wellness products in the workplace.

13. A cosmetics manufacturer leverages waste byproducts from fruit processing to create sustainable beauty products, aligning with ethical sourcing standards.

14. An electronics company produces energy-efficient appliances, capitalizing on the rising consumer interest in reducing energy consumption at home.

15. A furniture manufacturer utilizes reclaimed wood to produce stylish and sustainable home furnishings, targeting environmentally aware consumers.

16. A packaging company specializes in biodegradable materials, catering to businesses looking to minimize their environmental impact.

17. A glass manufacturer focuses on producing decorative glassware using traditional blowing techniques, appealing to both tourists and collectors.

18. A renewable energy equipment manufacturer creates components for solar panels, addressing the growing demand for sustainable energy solutions.

19. A construction materials company produces prefabricated concrete solutions, enabling faster build times and cost savings for commercial projects.

20. A cosmetics company produces high-end skincare using organic ingredients sourced from fair-trade farms, targeting luxury consumers.

21. A manufacturer of precision metal parts uses advanced machining techniques to supply components for the aerospace and automotive industries.

22. A company develops specialized machinery for the textile industry, enhancing efficiency and reducing waste in manufacturing processes.

23. An innovative toy manufacturer designs educational toys that promote STEM learning, capitalizing on parents' desire for engaging learning experiences.

24. A footwear brand focuses on creating high-performance athletic shoes made from recycled plastics, appealing to eco-conscious athletes.

25. A manufacturer of industrial cleaning products creates eco-friendly formulations for commercial use, addressing the demand for safer workplace environments.

26. A company produces custom metal fabrications for architectural projects, offering tailored solutions that meet specific design requirements.

27. A furniture maker focuses on modular designs that allow consumers to customize their living spaces, catering to urban dwellers with limited space.

28. A ceramic manufacturer develops eco-friendly, non-toxic dinnerware, responding to consumer concerns about health and sustainability.

29. A company specializes in the production of vegan leather goods, targeting the market for cruelty-free and sustainable fashion accessories.

30. A manufacturer of biodegradable cleaning supplies uses plant-based ingredients to create effective yet environmentally friendly products for homes and businesses.

31. A pet accessory manufacturer designs durable, stylish products from recycled materials, appealing to eco-conscious pet owners.

32. A manufacturer of high-end bicycles incorporates lightweight materials and advanced engineering, targeting competitive cyclists seeking performance enhancement.

33. A company offers customized packaging solutions for food products, utilizing innovative designs to enhance brand visibility and consumer engagement.

34. A manufacturer of artisanal pasta uses traditional methods and locally sourced ingredients, appealing to foodies and gourmet markets.

35. A company specializes in the production of 3D-printed metal parts for the aerospace sector, providing rapid prototyping and manufacturing solutions.

36. A textile producer develops smart fabrics embedded with sensors, targeting the wearable technology market for health and fitness applications.

37. A manufacturer of natural skincare products uses ethically sourced botanicals, targeting consumers interested in clean beauty and holistic wellness.

38. A company produces high-quality fishing tackle using sustainable materials, catering to the eco-conscious fishing community.

39. A manufacturer of carbonated beverages focuses on unique flavor combinations and natural sweeteners, appealing to adventurous consumers.

40. A company producing modular kitchen systems emphasizes flexibility and design, targeting homeowners looking for innovative cooking solutions.

41. A wood products manufacturer focuses on creating eco-friendly finishes and adhesives, responding to the demand for sustainable construction materials.

42. An electronics manufacturer specializes in refurbished devices, providing affordable options for consumers while reducing electronic waste.

43. A company produces organic baby food sourced from local farms, catering to health-conscious parents looking for nutritious options for their children.

44. A metalworking shop offers customized engraving services for wedding and anniversary gifts, appealing to consumers seeking personalized products.

45. A manufacturer of eco-friendly paints uses non-toxic ingredients, targeting environmentally conscious homeowners and businesses.

46. A company specializes in the production of luxury pet beds made from sustainable materials, appealing to affluent pet owners who prioritize quality.

47. A textile manufacturer focuses on producing breathable fabrics for activewear, addressing consumer demand for comfort and performance in fitness clothing.

48. A company sells premium kitchen gadgets that promote healthy cooking techniques, catering to consumers interested in culinary health.

49. A manufacturer of sustainable surfboards uses recycled materials, attracting environmentally conscious surfers looking for eco-friendly alternatives.

50. A company develops innovative home insulation products made from recycled materials, focusing on energy savings and environmental impact reduction.
---
1. A company specializing in the processing and preserving of meat products uses a farm-to-table model, sourcing livestock directly from local farms to ensure quality and sustainability. (Manufacture of food products: Processing and preserving of meat and production of meat products)

2. An eco-friendly juice manufacturer utilizes surplus fruits from local orchards to create organic fruit juices, reducing food waste while promoting healthy living. (Manufacture of food products: Manufacture of fruit and vegetable juice)

3. A dairy cooperative collects milk from regional farmers, processes it into cheese, and sells directly to consumers through farmers' markets and local grocery stores. (Manufacture of dairy products: Operation of dairies and cheese making)

4. A plant-based protein company manufactures meat alternatives using legumes and grains, targeting health-conscious consumers and promoting vegetarian lifestyles. (Manufacture of other food products: Manufacture of prepared meals and dishes)

5. A craft brewery sources locally grown grains and hops to produce small-batch beers, fostering community engagement and supporting local agriculture. (Manufacture of beverages: Manufacture of beer)

6. A chocolate manufacturer partners with fair-trade cacao farmers to produce high-quality chocolates, ensuring ethical sourcing and sustainability practices. (Manufacture of other food products: Manufacture of cocoa, chocolate and sugar confectionery)

7. A specialty bakery focuses on gluten-free and organic baked goods, catering to the growing demand for health-conscious products in urban areas. (Manufacture of bakery and farinaceous products: Manufacture of bread; manufacture of fresh pastry goods and cakes)

8. A seafood processing company works with local fishermen to deliver fresh, sustainable seafood products directly to restaurants and grocery stores. (Manufacture of food products: Processing and preserving of fish, crustaceans and molluscs)

9. A fruit and vegetable processing plant converts seasonal produce into frozen and canned goods, extending shelf life and minimizing waste. (Manufacture of food products: Other processing and preserving of fruit and vegetables)

10. A vegan condiment manufacturer creates a line of plant-based sauces and dressings, focusing on clean ingredients and environmentally friendly packaging. (Manufacture of other food products: Manufacture of condiments and seasonings)

11. A furniture manufacturer utilizes reclaimed wood to create eco-friendly furniture pieces, appealing to environmentally conscious consumers. (Manufacture of wood and of products of wood and cork, except furniture)

12. A company specializing in custom metal fabrication provides tailored solutions for construction firms, delivering high-quality metal structures on demand. (Manufacture of fabricated metal products, except machinery and equipment: Manufacture of metal structures and parts of structures)

13. A small-scale distillery focuses on producing artisanal spirits using locally sourced grains and fruits, emphasizing craftsmanship and local heritage. (Manufacture of beverages: Distilling, rectifying and blending of spirits)


### Generate Descriptions

In [134]:

#for generate_nace_class in generated_classes:
for generate_nace_class in ["A"]:

    includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
    if pd.isna(includes):
        print("No description for class:", generate_nace_class)
        continue
    includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
    includes_also = "" if pd.isna(includes_also) else includes_also
    excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
    excludes = "" if pd.isna(excludes) else excludes

    if few_shot: 
        gold_standard = df_gold_standard[df_gold_standard["NACE_letter"] == generate_nace_class]["Description_clean"].to_list()[:3] 
        gold_standard = [text.replace("\n", "") for text in gold_standard]
    else: 
        gold_standard = [] 

    subsections = get_sublevels(generate_nace_class, level=2)

    examples = []

    if generated_data.get(generate_nace_class) is not None:
        if len(generated_data[generate_nace_class].get("data", [])) > 0:
            examples = generated_data[generate_nace_class]["data"]

    for i in tqdm(range(iterations_*num_samples), desc=generate_nace_class):
        topic = topics[generate_nace_class]["topics"][i]
        res = generate_synthetic_data(num_samples=10, gold_standard=gold_standard, includes=includes, includes_also=includes_also, excludes=excludes, subsections=subsections, prompt_path=prompt_path, model="gpt-4o-mini", topic=topic)
        examples.append(res[1])
        data = split_synthetic_data("\n\n".join(examples), num_samples * iterations_)
        pd.DataFrame(data, columns=[generate_nace_class]).to_csv(os.path.join(store_path, f"class_{generate_nace_class}.csv"), index=False)
        if len(data) >= num_samples * iterations_:
            break

    results = {
        "data": data,
        "prompt": res[0],
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": examples, 
        "few_shot": few_shot
    }

    generated_data[generate_nace_class] = results

A:   0%|                                                                                                                                                                                     | 0/1000 [00:00<?, ?it/s]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   0%|▏                                                                                                                                                                          | 1/1000 [00:04<1:15:38,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   0%|▎                                                                                                                                                                          | 2/1000 [00:08<1:08:53,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   0%|▌                                                                                                                                                                          | 3/1000 [00:12<1:08:58,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   0%|▋                                                                                                                                                                          | 4/1000 [00:16<1:09:17,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   0%|▊                                                                                                                                                                          | 5/1000 [00:19<1:00:19,  3.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█                                                                                                                                                                            | 6/1000 [00:22<55:36,  3.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█▏                                                                                                                                                                           | 7/1000 [00:25<55:40,  3.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█▎                                                                                                                                                                         | 8/1000 [00:30<1:05:06,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█▌                                                                                                                                                                         | 9/1000 [00:35<1:07:45,  4.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█▋                                                                                                                                                                        | 10/1000 [00:40<1:14:09,  4.49s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|█▊                                                                                                                                                                        | 11/1000 [00:44<1:09:10,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|██                                                                                                                                                                        | 12/1000 [00:47<1:03:58,  3.89s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|██▏                                                                                                                                                                       | 13/1000 [00:51<1:03:20,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   1%|██▍                                                                                                                                                                       | 14/1000 [00:55<1:05:09,  3.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|██▌                                                                                                                                                                       | 15/1000 [00:59<1:05:18,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|██▋                                                                                                                                                                       | 16/1000 [01:03<1:06:29,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|██▉                                                                                                                                                                       | 17/1000 [01:06<1:01:36,  3.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███                                                                                                                                                                         | 18/1000 [01:10<59:29,  3.63s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███▏                                                                                                                                                                      | 19/1000 [01:14<1:04:19,  3.93s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███▍                                                                                                                                                                      | 20/1000 [01:20<1:14:00,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███▌                                                                                                                                                                      | 21/1000 [01:23<1:08:02,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███▋                                                                                                                                                                      | 22/1000 [01:28<1:12:11,  4.43s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|███▉                                                                                                                                                                      | 23/1000 [01:33<1:13:55,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|████                                                                                                                                                                      | 24/1000 [01:38<1:14:20,  4.57s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   2%|████▎                                                                                                                                                                     | 25/1000 [01:42<1:13:58,  4.55s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|████▍                                                                                                                                                                     | 26/1000 [01:46<1:09:59,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|████▌                                                                                                                                                                     | 27/1000 [01:50<1:05:41,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|████▊                                                                                                                                                                     | 28/1000 [01:53<1:04:13,  3.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|████▉                                                                                                                                                                     | 29/1000 [01:57<1:04:57,  4.01s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|█████                                                                                                                                                                     | 30/1000 [02:03<1:11:54,  4.45s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|█████▎                                                                                                                                                                    | 31/1000 [02:06<1:06:34,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|█████▍                                                                                                                                                                    | 32/1000 [02:10<1:04:02,  3.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|█████▌                                                                                                                                                                    | 33/1000 [02:14<1:04:05,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   3%|█████▊                                                                                                                                                                    | 34/1000 [02:19<1:08:07,  4.23s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|█████▉                                                                                                                                                                    | 35/1000 [02:23<1:06:37,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████                                                                                                                                                                    | 36/1000 [02:28<1:11:25,  4.45s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████▎                                                                                                                                                                   | 37/1000 [02:32<1:08:12,  4.25s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████▍                                                                                                                                                                   | 38/1000 [02:38<1:20:29,  5.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████▋                                                                                                                                                                   | 39/1000 [02:42<1:14:34,  4.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████▊                                                                                                                                                                   | 40/1000 [02:46<1:10:50,  4.43s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|██████▉                                                                                                                                                                   | 41/1000 [02:50<1:07:20,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|███████▏                                                                                                                                                                  | 42/1000 [02:53<1:04:12,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|███████▎                                                                                                                                                                  | 43/1000 [02:57<1:01:15,  3.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|███████▍                                                                                                                                                                  | 44/1000 [03:01<1:01:55,  3.89s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   4%|███████▋                                                                                                                                                                  | 45/1000 [03:06<1:09:51,  4.39s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|███████▊                                                                                                                                                                  | 46/1000 [03:10<1:05:17,  4.11s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|███████▉                                                                                                                                                                  | 47/1000 [03:14<1:07:01,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|████████▏                                                                                                                                                                 | 48/1000 [03:21<1:18:50,  4.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|████████▎                                                                                                                                                                 | 49/1000 [03:24<1:10:47,  4.47s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|████████▌                                                                                                                                                                 | 50/1000 [03:33<1:30:44,  5.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|████████▋                                                                                                                                                                 | 51/1000 [03:37<1:20:45,  5.11s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|████████▊                                                                                                                                                                 | 52/1000 [03:42<1:20:18,  5.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|█████████                                                                                                                                                                 | 53/1000 [03:46<1:14:40,  4.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   5%|█████████▏                                                                                                                                                                | 54/1000 [03:50<1:12:46,  4.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|█████████▎                                                                                                                                                                | 55/1000 [03:54<1:10:54,  4.50s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|█████████▌                                                                                                                                                                | 56/1000 [03:57<1:04:25,  4.09s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|█████████▋                                                                                                                                                                | 57/1000 [04:01<1:01:39,  3.92s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|█████████▊                                                                                                                                                                | 58/1000 [04:05<1:04:51,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████                                                                                                                                                                | 59/1000 [04:10<1:08:34,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████▏                                                                                                                                                               | 60/1000 [04:15<1:08:58,  4.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████▎                                                                                                                                                               | 61/1000 [04:20<1:10:54,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████▌                                                                                                                                                               | 62/1000 [04:25<1:13:13,  4.68s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████▋                                                                                                                                                               | 63/1000 [04:29<1:09:14,  4.43s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|██████████▉                                                                                                                                                               | 64/1000 [04:33<1:08:16,  4.38s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   6%|███████████                                                                                                                                                               | 65/1000 [04:36<1:03:09,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|███████████▏                                                                                                                                                              | 66/1000 [04:41<1:04:37,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|███████████▍                                                                                                                                                              | 67/1000 [04:44<1:01:09,  3.93s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|███████████▋                                                                                                                                                                | 68/1000 [04:48<59:54,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|███████████▋                                                                                                                                                              | 69/1000 [04:52<1:01:05,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|███████████▉                                                                                                                                                              | 70/1000 [04:56<1:04:04,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|████████████                                                                                                                                                              | 71/1000 [05:01<1:05:55,  4.26s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|████████████▏                                                                                                                                                             | 72/1000 [05:04<1:01:29,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|████████████▍                                                                                                                                                             | 73/1000 [05:10<1:09:06,  4.47s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   7%|████████████▌                                                                                                                                                             | 74/1000 [05:14<1:09:30,  4.50s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|████████████▊                                                                                                                                                             | 75/1000 [05:18<1:04:47,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|████████████▉                                                                                                                                                             | 76/1000 [05:22<1:05:37,  4.26s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████                                                                                                                                                             | 77/1000 [05:26<1:03:22,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████▎                                                                                                                                                            | 78/1000 [05:30<1:01:48,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████▍                                                                                                                                                            | 79/1000 [05:34<1:04:26,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████▌                                                                                                                                                            | 80/1000 [05:41<1:12:44,  4.74s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████▊                                                                                                                                                            | 81/1000 [05:48<1:23:23,  5.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|█████████████▉                                                                                                                                                            | 82/1000 [05:53<1:21:19,  5.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|██████████████                                                                                                                                                            | 83/1000 [05:58<1:22:20,  5.39s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|██████████████▎                                                                                                                                                           | 84/1000 [06:03<1:17:50,  5.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   8%|██████████████▍                                                                                                                                                           | 85/1000 [06:07<1:14:33,  4.89s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|██████████████▌                                                                                                                                                           | 86/1000 [06:10<1:06:13,  4.35s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|██████████████▊                                                                                                                                                           | 87/1000 [06:16<1:11:24,  4.69s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|██████████████▉                                                                                                                                                           | 88/1000 [06:20<1:11:58,  4.74s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▏                                                                                                                                                          | 89/1000 [06:25<1:12:41,  4.79s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▎                                                                                                                                                          | 90/1000 [06:30<1:14:16,  4.90s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▍                                                                                                                                                          | 91/1000 [06:36<1:17:56,  5.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▋                                                                                                                                                          | 92/1000 [06:40<1:13:05,  4.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▊                                                                                                                                                          | 93/1000 [06:44<1:10:12,  4.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:   9%|███████████████▉                                                                                                                                                          | 94/1000 [06:47<1:02:39,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▏                                                                                                                                                         | 95/1000 [06:52<1:03:53,  4.24s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▎                                                                                                                                                         | 96/1000 [06:56<1:04:56,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▍                                                                                                                                                         | 97/1000 [07:01<1:08:10,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▋                                                                                                                                                         | 98/1000 [07:07<1:11:40,  4.77s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▊                                                                                                                                                         | 99/1000 [07:11<1:08:08,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|████████████████▉                                                                                                                                                        | 100/1000 [07:14<1:01:46,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|█████████████████                                                                                                                                                        | 101/1000 [07:18<1:00:00,  4.00s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|█████████████████▍                                                                                                                                                         | 102/1000 [07:21<56:27,  3.77s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|█████████████████▌                                                                                                                                                         | 103/1000 [07:25<57:20,  3.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|█████████████████▊                                                                                                                                                         | 104/1000 [07:29<57:55,  3.88s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  10%|█████████████████▉                                                                                                                                                         | 105/1000 [07:33<59:34,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|█████████████████▉                                                                                                                                                       | 106/1000 [07:38<1:05:05,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|██████████████████                                                                                                                                                       | 107/1000 [07:44<1:10:30,  4.74s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|██████████████████▎                                                                                                                                                      | 108/1000 [07:47<1:01:32,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|██████████████████▋                                                                                                                                                        | 109/1000 [07:49<54:41,  3.68s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|██████████████████▊                                                                                                                                                        | 110/1000 [07:53<54:20,  3.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|██████████████████▉                                                                                                                                                        | 111/1000 [07:58<58:22,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|███████████████████▏                                                                                                                                                       | 112/1000 [08:00<53:16,  3.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|███████████████████▎                                                                                                                                                       | 113/1000 [08:05<56:57,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  11%|███████████████████▍                                                                                                                                                       | 114/1000 [08:08<54:28,  3.69s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|███████████████████▋                                                                                                                                                       | 115/1000 [08:11<52:08,  3.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|███████████████████▊                                                                                                                                                       | 116/1000 [08:15<52:59,  3.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████                                                                                                                                                       | 117/1000 [08:19<53:02,  3.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▏                                                                                                                                                      | 118/1000 [08:22<51:47,  3.52s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▎                                                                                                                                                      | 119/1000 [08:26<53:50,  3.67s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▌                                                                                                                                                      | 120/1000 [08:31<58:03,  3.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▍                                                                                                                                                    | 121/1000 [08:36<1:03:54,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▌                                                                                                                                                    | 122/1000 [08:42<1:12:34,  4.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|████████████████████▊                                                                                                                                                    | 123/1000 [08:46<1:07:49,  4.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|█████████████████████▏                                                                                                                                                     | 124/1000 [08:49<59:35,  4.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  12%|█████████████████████▍                                                                                                                                                     | 125/1000 [08:53<57:35,  3.95s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|█████████████████████▌                                                                                                                                                     | 126/1000 [08:55<52:58,  3.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|█████████████████████▋                                                                                                                                                     | 127/1000 [09:01<59:59,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|█████████████████████▋                                                                                                                                                   | 128/1000 [09:05<1:00:51,  4.19s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████                                                                                                                                                     | 129/1000 [09:09<59:11,  4.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████▏                                                                                                                                                    | 130/1000 [09:13<57:55,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████▍                                                                                                                                                    | 131/1000 [09:15<52:37,  3.63s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████▌                                                                                                                                                    | 132/1000 [09:18<49:23,  3.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████▍                                                                                                                                                  | 133/1000 [09:24<1:01:01,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  13%|██████████████████████▉                                                                                                                                                    | 134/1000 [09:28<57:31,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|██████████████████████▊                                                                                                                                                  | 135/1000 [09:33<1:03:00,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|███████████████████████▎                                                                                                                                                   | 136/1000 [09:36<56:19,  3.91s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|███████████████████████▍                                                                                                                                                   | 137/1000 [09:40<58:08,  4.04s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|███████████████████████▌                                                                                                                                                   | 138/1000 [09:44<55:17,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|███████████████████████▊                                                                                                                                                   | 139/1000 [09:49<59:35,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|███████████████████████▉                                                                                                                                                   | 140/1000 [09:52<54:55,  3.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|████████████████████████                                                                                                                                                   | 141/1000 [09:54<50:02,  3.49s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|████████████████████████▎                                                                                                                                                  | 142/1000 [09:58<48:49,  3.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|████████████████████████▍                                                                                                                                                  | 143/1000 [10:01<48:47,  3.42s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|████████████████████████▌                                                                                                                                                  | 144/1000 [10:06<56:14,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  14%|████████████████████████▊                                                                                                                                                  | 145/1000 [10:11<58:05,  4.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|████████████████████████▋                                                                                                                                                | 146/1000 [10:16<1:01:41,  4.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|████████████████████████▊                                                                                                                                                | 147/1000 [10:24<1:17:03,  5.42s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████                                                                                                                                                | 148/1000 [10:30<1:19:50,  5.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████▏                                                                                                                                               | 149/1000 [10:34<1:14:28,  5.25s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████▎                                                                                                                                               | 150/1000 [10:39<1:12:33,  5.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████▌                                                                                                                                               | 151/1000 [10:43<1:10:17,  4.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████▋                                                                                                                                               | 152/1000 [10:50<1:15:18,  5.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|█████████████████████████▊                                                                                                                                               | 153/1000 [10:56<1:17:50,  5.51s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  15%|██████████████████████████                                                                                                                                               | 154/1000 [11:04<1:28:09,  6.25s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|██████████████████████████▏                                                                                                                                              | 155/1000 [11:13<1:40:50,  7.16s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|██████████████████████████▎                                                                                                                                              | 156/1000 [11:17<1:29:46,  6.38s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|██████████████████████████▌                                                                                                                                              | 157/1000 [11:20<1:14:20,  5.29s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|██████████████████████████▋                                                                                                                                              | 158/1000 [11:25<1:11:26,  5.09s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|██████████████████████████▊                                                                                                                                              | 159/1000 [11:29<1:09:40,  4.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|███████████████████████████                                                                                                                                              | 160/1000 [11:33<1:05:16,  4.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|███████████████████████████▏                                                                                                                                             | 161/1000 [11:38<1:07:04,  4.80s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|███████████████████████████▍                                                                                                                                             | 162/1000 [11:43<1:04:58,  4.65s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|███████████████████████████▌                                                                                                                                             | 163/1000 [11:48<1:06:17,  4.75s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|███████████████████████████▋                                                                                                                                             | 164/1000 [11:51<1:01:49,  4.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  16%|████████████████████████████▏                                                                                                                                              | 165/1000 [11:55<58:53,  4.23s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|████████████████████████████▍                                                                                                                                              | 166/1000 [12:00<59:35,  4.29s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|████████████████████████████▌                                                                                                                                              | 167/1000 [12:03<56:38,  4.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|████████████████████████████▋                                                                                                                                              | 168/1000 [12:06<52:17,  3.77s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|████████████████████████████▉                                                                                                                                              | 169/1000 [12:11<54:26,  3.93s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|█████████████████████████████                                                                                                                                              | 170/1000 [12:14<53:21,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|█████████████████████████████▏                                                                                                                                             | 171/1000 [12:18<51:44,  3.75s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|█████████████████████████████▍                                                                                                                                             | 172/1000 [12:22<54:24,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|█████████████████████████████▌                                                                                                                                             | 173/1000 [12:27<58:35,  4.25s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  17%|█████████████████████████████▍                                                                                                                                           | 174/1000 [12:32<1:02:01,  4.51s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|█████████████████████████████▌                                                                                                                                           | 175/1000 [12:37<1:03:16,  4.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|█████████████████████████████▋                                                                                                                                           | 176/1000 [12:41<1:00:30,  4.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|█████████████████████████████▉                                                                                                                                           | 177/1000 [12:45<1:00:12,  4.39s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|██████████████████████████████▍                                                                                                                                            | 178/1000 [12:49<56:44,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|██████████████████████████████▌                                                                                                                                            | 179/1000 [12:53<56:42,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|██████████████████████████████▊                                                                                                                                            | 180/1000 [12:58<58:44,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|██████████████████████████████▉                                                                                                                                            | 181/1000 [13:01<54:14,  3.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|███████████████████████████████                                                                                                                                            | 182/1000 [13:06<56:51,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|██████████████████████████████▉                                                                                                                                          | 183/1000 [13:12<1:07:58,  4.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|███████████████████████████████                                                                                                                                          | 184/1000 [13:18<1:10:28,  5.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  18%|███████████████████████████████▎                                                                                                                                         | 185/1000 [13:25<1:18:13,  5.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|███████████████████████████████▍                                                                                                                                         | 186/1000 [13:30<1:13:47,  5.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|███████████████████████████████▌                                                                                                                                         | 187/1000 [13:35<1:11:54,  5.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|███████████████████████████████▊                                                                                                                                         | 188/1000 [13:38<1:04:05,  4.74s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|████████████████████████████████▎                                                                                                                                          | 189/1000 [13:42<59:32,  4.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|████████████████████████████████▍                                                                                                                                          | 190/1000 [13:46<56:56,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|████████████████████████████████▎                                                                                                                                        | 191/1000 [13:51<1:00:17,  4.47s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|████████████████████████████████▊                                                                                                                                          | 192/1000 [13:55<59:51,  4.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|█████████████████████████████████                                                                                                                                          | 193/1000 [13:58<54:41,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  19%|████████████████████████████████▊                                                                                                                                        | 194/1000 [14:04<1:02:20,  4.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|████████████████████████████████▉                                                                                                                                        | 195/1000 [14:10<1:05:50,  4.91s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|█████████████████████████████████▌                                                                                                                                         | 196/1000 [14:13<58:06,  4.34s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|█████████████████████████████████▋                                                                                                                                         | 197/1000 [14:17<56:00,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|█████████████████████████████████▊                                                                                                                                         | 198/1000 [14:21<55:52,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████                                                                                                                                         | 199/1000 [14:25<56:46,  4.25s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████▏                                                                                                                                        | 200/1000 [14:30<58:38,  4.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████▎                                                                                                                                        | 201/1000 [14:34<54:57,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████▌                                                                                                                                        | 202/1000 [14:36<49:19,  3.71s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████▋                                                                                                                                        | 203/1000 [14:40<50:27,  3.80s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|██████████████████████████████████▉                                                                                                                                        | 204/1000 [14:45<52:56,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  20%|███████████████████████████████████                                                                                                                                        | 205/1000 [14:48<51:04,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▏                                                                                                                                       | 206/1000 [14:54<57:39,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▍                                                                                                                                       | 207/1000 [14:58<55:42,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▌                                                                                                                                       | 208/1000 [15:02<56:58,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▋                                                                                                                                       | 209/1000 [15:06<53:11,  4.04s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▉                                                                                                                                       | 210/1000 [15:11<57:23,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|████████████████████████████████████                                                                                                                                       | 211/1000 [15:14<52:28,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▊                                                                                                                                     | 212/1000 [15:25<1:21:39,  6.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|███████████████████████████████████▉                                                                                                                                     | 213/1000 [15:29<1:13:47,  5.63s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  21%|████████████████████████████████████▏                                                                                                                                    | 214/1000 [15:34<1:07:31,  5.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|████████████████████████████████████▎                                                                                                                                    | 215/1000 [15:38<1:03:21,  4.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|████████████████████████████████████▉                                                                                                                                      | 216/1000 [15:41<57:15,  4.38s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████                                                                                                                                      | 217/1000 [15:46<58:15,  4.46s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|████████████████████████████████████▊                                                                                                                                    | 218/1000 [15:51<1:03:20,  4.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████▍                                                                                                                                     | 219/1000 [15:55<56:47,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████▌                                                                                                                                     | 220/1000 [16:00<59:02,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████▊                                                                                                                                     | 221/1000 [16:03<53:12,  4.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████▉                                                                                                                                     | 222/1000 [16:07<54:12,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|██████████████████████████████████████▏                                                                                                                                    | 223/1000 [16:12<59:10,  4.57s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|█████████████████████████████████████▊                                                                                                                                   | 224/1000 [16:17<1:00:40,  4.69s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  22%|██████████████████████████████████████▍                                                                                                                                    | 225/1000 [16:20<53:38,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|██████████████████████████████████████▋                                                                                                                                    | 226/1000 [16:24<49:57,  3.87s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|██████████████████████████████████████▊                                                                                                                                    | 227/1000 [16:27<49:33,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|██████████████████████████████████████▉                                                                                                                                    | 228/1000 [16:30<45:27,  3.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|███████████████████████████████████████▏                                                                                                                                   | 229/1000 [16:34<45:55,  3.57s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|███████████████████████████████████████▎                                                                                                                                   | 230/1000 [16:38<46:22,  3.61s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|███████████████████████████████████████▌                                                                                                                                   | 231/1000 [16:42<49:21,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|███████████████████████████████████████▋                                                                                                                                   | 232/1000 [16:45<44:29,  3.48s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|███████████████████████████████████████▊                                                                                                                                   | 233/1000 [16:50<52:26,  4.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  23%|████████████████████████████████████████                                                                                                                                   | 234/1000 [16:55<53:47,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|████████████████████████████████████████▏                                                                                                                                  | 235/1000 [16:59<53:48,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|████████████████████████████████████████▎                                                                                                                                  | 236/1000 [17:03<53:56,  4.24s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|████████████████████████████████████████▌                                                                                                                                  | 237/1000 [17:07<53:46,  4.23s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|████████████████████████████████████████▋                                                                                                                                  | 238/1000 [17:11<52:44,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|████████████████████████████████████████▊                                                                                                                                  | 239/1000 [17:16<54:13,  4.28s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████                                                                                                                                  | 240/1000 [17:19<51:20,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████▏                                                                                                                                 | 241/1000 [17:24<52:24,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████▍                                                                                                                                 | 242/1000 [17:27<47:57,  3.80s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████▌                                                                                                                                 | 243/1000 [17:29<43:01,  3.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████▋                                                                                                                                 | 244/1000 [17:34<47:38,  3.78s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  24%|█████████████████████████████████████████▉                                                                                                                                 | 245/1000 [17:37<46:59,  3.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████                                                                                                                                 | 246/1000 [17:39<38:52,  3.09s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████▏                                                                                                                                | 247/1000 [17:43<41:28,  3.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████▍                                                                                                                                | 248/1000 [17:46<42:01,  3.35s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████▌                                                                                                                                | 249/1000 [17:50<42:31,  3.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████▊                                                                                                                                | 250/1000 [17:53<42:03,  3.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|██████████████████████████████████████████▉                                                                                                                                | 251/1000 [17:57<43:08,  3.46s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|███████████████████████████████████████████                                                                                                                                | 252/1000 [18:02<49:21,  3.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|███████████████████████████████████████████▎                                                                                                                               | 253/1000 [18:06<49:57,  4.01s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  25%|███████████████████████████████████████████▍                                                                                                                               | 254/1000 [18:12<56:51,  4.57s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|███████████████████████████████████████████▌                                                                                                                               | 255/1000 [18:16<56:20,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|███████████████████████████████████████████▎                                                                                                                             | 256/1000 [18:23<1:02:02,  5.00s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|███████████████████████████████████████████▉                                                                                                                               | 257/1000 [18:25<53:14,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████                                                                                                                               | 258/1000 [18:29<50:59,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████▎                                                                                                                              | 259/1000 [18:33<52:13,  4.23s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████▍                                                                                                                              | 260/1000 [18:38<51:54,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████▋                                                                                                                              | 261/1000 [18:42<52:55,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████▊                                                                                                                              | 262/1000 [18:46<52:25,  4.26s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|████████████████████████████████████████████▉                                                                                                                              | 263/1000 [18:52<59:10,  4.82s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|█████████████████████████████████████████████▏                                                                                                                             | 264/1000 [18:57<58:41,  4.79s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  26%|█████████████████████████████████████████████▎                                                                                                                             | 265/1000 [19:01<57:19,  4.68s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|█████████████████████████████████████████████▍                                                                                                                             | 266/1000 [19:05<52:43,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|█████████████████████████████████████████████                                                                                                                            | 267/1000 [19:12<1:01:31,  5.04s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|█████████████████████████████████████████████▎                                                                                                                           | 268/1000 [19:16<1:00:14,  4.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|█████████████████████████████████████████████▉                                                                                                                             | 269/1000 [19:21<58:16,  4.78s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|██████████████████████████████████████████████▏                                                                                                                            | 270/1000 [19:24<52:25,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|██████████████████████████████████████████████▎                                                                                                                            | 271/1000 [19:27<48:09,  3.96s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|██████████████████████████████████████████████▌                                                                                                                            | 272/1000 [19:32<52:55,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|██████████████████████████████████████████████▋                                                                                                                            | 273/1000 [19:36<51:49,  4.28s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  27%|██████████████████████████████████████████████▊                                                                                                                            | 274/1000 [19:40<49:13,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████                                                                                                                            | 275/1000 [19:46<57:06,  4.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████▏                                                                                                                           | 276/1000 [19:51<56:10,  4.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████▎                                                                                                                           | 277/1000 [19:55<53:38,  4.45s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████▌                                                                                                                           | 278/1000 [20:00<56:10,  4.67s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████▋                                                                                                                           | 279/1000 [20:03<51:52,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|███████████████████████████████████████████████▉                                                                                                                           | 280/1000 [20:08<52:28,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|████████████████████████████████████████████████                                                                                                                           | 281/1000 [20:13<54:53,  4.58s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|████████████████████████████████████████████████▏                                                                                                                          | 282/1000 [20:18<56:33,  4.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|████████████████████████████████████████████████▍                                                                                                                          | 283/1000 [20:21<49:48,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|████████████████████████████████████████████████▌                                                                                                                          | 284/1000 [20:25<47:30,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  28%|████████████████████████████████████████████████▋                                                                                                                          | 285/1000 [20:29<49:51,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|████████████████████████████████████████████████▉                                                                                                                          | 286/1000 [20:32<45:54,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████                                                                                                                          | 287/1000 [20:38<51:12,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████▏                                                                                                                         | 288/1000 [20:41<48:22,  4.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████▍                                                                                                                         | 289/1000 [20:46<49:30,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████▌                                                                                                                         | 290/1000 [20:49<45:16,  3.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████▊                                                                                                                         | 291/1000 [20:53<46:18,  3.92s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|█████████████████████████████████████████████████▉                                                                                                                         | 292/1000 [20:56<44:19,  3.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|██████████████████████████████████████████████████                                                                                                                         | 293/1000 [20:59<39:38,  3.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  29%|██████████████████████████████████████████████████▎                                                                                                                        | 294/1000 [21:03<43:17,  3.68s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|██████████████████████████████████████████████████▍                                                                                                                        | 295/1000 [21:07<45:02,  3.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|██████████████████████████████████████████████████▌                                                                                                                        | 296/1000 [21:11<45:34,  3.88s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|██████████████████████████████████████████████████▊                                                                                                                        | 297/1000 [21:15<46:46,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|██████████████████████████████████████████████████▉                                                                                                                        | 298/1000 [21:20<49:07,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▏                                                                                                                       | 299/1000 [21:25<52:08,  4.46s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▎                                                                                                                       | 300/1000 [21:30<55:01,  4.72s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▍                                                                                                                       | 301/1000 [21:34<51:26,  4.42s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▋                                                                                                                       | 302/1000 [21:38<48:59,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▊                                                                                                                       | 303/1000 [21:43<52:29,  4.52s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|███████████████████████████████████████████████████▉                                                                                                                       | 304/1000 [21:47<50:05,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  30%|████████████████████████████████████████████████████▏                                                                                                                      | 305/1000 [21:51<47:08,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|████████████████████████████████████████████████████▎                                                                                                                      | 306/1000 [21:54<46:28,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|████████████████████████████████████████████████████▍                                                                                                                      | 307/1000 [21:59<48:29,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|████████████████████████████████████████████████████▋                                                                                                                      | 308/1000 [22:03<47:08,  4.09s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|████████████████████████████████████████████████████▊                                                                                                                      | 309/1000 [22:08<51:28,  4.47s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|█████████████████████████████████████████████████████                                                                                                                      | 310/1000 [22:12<50:09,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|█████████████████████████████████████████████████████▏                                                                                                                     | 311/1000 [22:17<50:08,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|█████████████████████████████████████████████████████▎                                                                                                                     | 312/1000 [22:21<49:20,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|█████████████████████████████████████████████████████▌                                                                                                                     | 313/1000 [22:25<49:25,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  31%|█████████████████████████████████████████████████████▋                                                                                                                     | 314/1000 [22:30<49:23,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|█████████████████████████████████████████████████████▊                                                                                                                     | 315/1000 [22:33<47:38,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████                                                                                                                     | 316/1000 [22:38<50:48,  4.46s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████▏                                                                                                                    | 317/1000 [22:43<52:31,  4.61s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████▍                                                                                                                    | 318/1000 [22:48<52:25,  4.61s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████▌                                                                                                                    | 319/1000 [22:53<52:13,  4.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████▋                                                                                                                    | 320/1000 [22:56<49:07,  4.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|██████████████████████████████████████████████████████▉                                                                                                                    | 321/1000 [23:00<46:00,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|███████████████████████████████████████████████████████                                                                                                                    | 322/1000 [23:03<44:34,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|███████████████████████████████████████████████████████▏                                                                                                                   | 323/1000 [23:07<44:18,  3.93s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|███████████████████████████████████████████████████████▍                                                                                                                   | 324/1000 [23:11<44:42,  3.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  32%|███████████████████████████████████████████████████████▌                                                                                                                   | 325/1000 [23:14<41:34,  3.70s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|███████████████████████████████████████████████████████▋                                                                                                                   | 326/1000 [23:20<47:09,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|███████████████████████████████████████████████████████▉                                                                                                                   | 327/1000 [23:25<51:26,  4.59s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████                                                                                                                   | 328/1000 [23:29<48:16,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████▎                                                                                                                  | 329/1000 [23:33<46:25,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████▍                                                                                                                  | 330/1000 [23:37<45:15,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████▌                                                                                                                  | 331/1000 [23:41<44:50,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████▊                                                                                                                  | 332/1000 [23:45<47:15,  4.24s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|████████████████████████████████████████████████████████▉                                                                                                                  | 333/1000 [23:52<53:46,  4.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  33%|█████████████████████████████████████████████████████████                                                                                                                  | 334/1000 [23:56<51:45,  4.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|█████████████████████████████████████████████████████████▎                                                                                                                 | 335/1000 [24:00<49:56,  4.51s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|█████████████████████████████████████████████████████████▍                                                                                                                 | 336/1000 [24:04<49:33,  4.48s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|█████████████████████████████████████████████████████████▋                                                                                                                 | 337/1000 [24:10<52:23,  4.74s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|█████████████████████████████████████████████████████████▊                                                                                                                 | 338/1000 [24:14<50:58,  4.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|█████████████████████████████████████████████████████████▉                                                                                                                 | 339/1000 [24:18<50:08,  4.55s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▏                                                                                                                | 340/1000 [24:21<43:43,  3.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▎                                                                                                                | 341/1000 [24:26<46:24,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▍                                                                                                                | 342/1000 [24:31<50:40,  4.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▋                                                                                                                | 343/1000 [24:35<48:13,  4.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▊                                                                                                                | 344/1000 [24:41<51:32,  4.71s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  34%|██████████████████████████████████████████████████████████▉                                                                                                                | 345/1000 [24:45<51:30,  4.72s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|███████████████████████████████████████████████████████████▏                                                                                                               | 346/1000 [24:51<55:21,  5.08s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|███████████████████████████████████████████████████████████▎                                                                                                               | 347/1000 [24:55<51:02,  4.69s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|███████████████████████████████████████████████████████████▌                                                                                                               | 348/1000 [24:59<47:05,  4.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|███████████████████████████████████████████████████████████▋                                                                                                               | 349/1000 [25:03<46:10,  4.26s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|███████████████████████████████████████████████████████████▊                                                                                                               | 350/1000 [25:08<49:28,  4.57s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|████████████████████████████████████████████████████████████                                                                                                               | 351/1000 [25:11<44:44,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|████████████████████████████████████████████████████████████▏                                                                                                              | 352/1000 [25:15<44:42,  4.14s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|████████████████████████████████████████████████████████████▎                                                                                                              | 353/1000 [25:18<39:59,  3.71s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  35%|████████████████████████████████████████████████████████████▌                                                                                                              | 354/1000 [25:23<43:02,  4.00s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|████████████████████████████████████████████████████████████▋                                                                                                              | 355/1000 [25:27<45:30,  4.23s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|████████████████████████████████████████████████████████████▉                                                                                                              | 356/1000 [25:32<47:12,  4.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████                                                                                                              | 357/1000 [25:35<43:06,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████▏                                                                                                             | 358/1000 [25:41<47:31,  4.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████▍                                                                                                             | 359/1000 [25:44<43:57,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████▌                                                                                                             | 360/1000 [25:49<45:11,  4.24s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████▋                                                                                                             | 361/1000 [25:53<46:39,  4.38s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|█████████████████████████████████████████████████████████████▉                                                                                                             | 362/1000 [25:58<46:20,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|██████████████████████████████████████████████████████████████                                                                                                             | 363/1000 [26:01<43:14,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|██████████████████████████████████████████████████████████████▏                                                                                                            | 364/1000 [26:04<40:38,  3.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  36%|██████████████████████████████████████████████████████████████▍                                                                                                            | 365/1000 [26:08<39:48,  3.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|██████████████████████████████████████████████████████████████▌                                                                                                            | 366/1000 [26:11<36:46,  3.48s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|██████████████████████████████████████████████████████████████▊                                                                                                            | 367/1000 [26:14<36:16,  3.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|██████████████████████████████████████████████████████████████▉                                                                                                            | 368/1000 [26:19<41:06,  3.90s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████                                                                                                            | 369/1000 [26:23<40:04,  3.81s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████▎                                                                                                           | 370/1000 [26:28<43:46,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████▍                                                                                                           | 371/1000 [26:32<43:19,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████▌                                                                                                           | 372/1000 [26:38<49:29,  4.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████▊                                                                                                           | 373/1000 [26:42<47:57,  4.59s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  37%|███████████████████████████████████████████████████████████████▉                                                                                                           | 374/1000 [26:45<43:30,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▏                                                                                                          | 375/1000 [26:49<41:03,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▎                                                                                                          | 376/1000 [26:52<37:54,  3.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▍                                                                                                          | 377/1000 [26:55<37:36,  3.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▋                                                                                                          | 378/1000 [27:00<39:51,  3.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▊                                                                                                          | 379/1000 [27:04<40:16,  3.89s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|████████████████████████████████████████████████████████████████▉                                                                                                          | 380/1000 [27:07<39:51,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|█████████████████████████████████████████████████████████████████▏                                                                                                         | 381/1000 [27:11<38:48,  3.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|█████████████████████████████████████████████████████████████████▎                                                                                                         | 382/1000 [27:14<37:12,  3.61s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|█████████████████████████████████████████████████████████████████▍                                                                                                         | 383/1000 [27:19<40:26,  3.93s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|█████████████████████████████████████████████████████████████████▋                                                                                                         | 384/1000 [27:24<44:24,  4.32s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  38%|█████████████████████████████████████████████████████████████████▊                                                                                                         | 385/1000 [27:28<43:01,  4.20s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████                                                                                                         | 386/1000 [27:31<40:25,  3.95s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████▏                                                                                                        | 387/1000 [27:35<40:22,  3.95s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████▎                                                                                                        | 388/1000 [27:39<39:47,  3.90s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████▌                                                                                                        | 389/1000 [27:43<39:33,  3.88s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████▋                                                                                                        | 390/1000 [27:47<39:40,  3.90s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|██████████████████████████████████████████████████████████████████▊                                                                                                        | 391/1000 [27:53<47:13,  4.65s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|███████████████████████████████████████████████████████████████████                                                                                                        | 392/1000 [27:58<46:35,  4.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|███████████████████████████████████████████████████████████████████▏                                                                                                       | 393/1000 [28:01<42:17,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  39%|███████████████████████████████████████████████████████████████████▎                                                                                                       | 394/1000 [28:05<42:05,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|███████████████████████████████████████████████████████████████████▌                                                                                                       | 395/1000 [28:09<41:39,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|███████████████████████████████████████████████████████████████████▋                                                                                                       | 396/1000 [28:13<41:28,  4.12s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|███████████████████████████████████████████████████████████████████▉                                                                                                       | 397/1000 [28:17<38:42,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████                                                                                                       | 398/1000 [28:19<34:36,  3.45s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████▏                                                                                                      | 399/1000 [28:22<34:26,  3.44s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████▍                                                                                                      | 400/1000 [28:25<30:10,  3.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████▌                                                                                                      | 401/1000 [28:28<32:59,  3.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████▋                                                                                                      | 402/1000 [28:32<35:01,  3.51s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|████████████████████████████████████████████████████████████████████▉                                                                                                      | 403/1000 [28:38<41:53,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|█████████████████████████████████████████████████████████████████████                                                                                                      | 404/1000 [28:42<41:17,  4.16s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  40%|█████████████████████████████████████████████████████████████████████▎                                                                                                     | 405/1000 [28:45<37:54,  3.82s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|█████████████████████████████████████████████████████████████████████▍                                                                                                     | 406/1000 [28:49<36:40,  3.70s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|█████████████████████████████████████████████████████████████████████▌                                                                                                     | 407/1000 [28:54<41:12,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|█████████████████████████████████████████████████████████████████████▊                                                                                                     | 408/1000 [28:57<38:21,  3.89s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|█████████████████████████████████████████████████████████████████████▉                                                                                                     | 409/1000 [29:02<41:13,  4.19s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|██████████████████████████████████████████████████████████████████████                                                                                                     | 410/1000 [29:06<41:22,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|██████████████████████████████████████████████████████████████████████▎                                                                                                    | 411/1000 [29:10<39:55,  4.07s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|██████████████████████████████████████████████████████████████████████▍                                                                                                    | 412/1000 [29:14<39:22,  4.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|██████████████████████████████████████████████████████████████████████▌                                                                                                    | 413/1000 [29:18<40:07,  4.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  41%|██████████████████████████████████████████████████████████████████████▊                                                                                                    | 414/1000 [29:23<40:18,  4.13s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|██████████████████████████████████████████████████████████████████████▉                                                                                                    | 415/1000 [29:27<42:33,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▏                                                                                                   | 416/1000 [29:32<41:51,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▎                                                                                                   | 417/1000 [29:35<39:11,  4.03s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▍                                                                                                   | 418/1000 [29:39<39:05,  4.03s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▋                                                                                                   | 419/1000 [29:44<40:51,  4.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▊                                                                                                   | 420/1000 [29:48<41:35,  4.30s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|███████████████████████████████████████████████████████████████████████▉                                                                                                   | 421/1000 [29:52<38:31,  3.99s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|████████████████████████████████████████████████████████████████████████▏                                                                                                  | 422/1000 [29:55<37:15,  3.87s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|████████████████████████████████████████████████████████████████████████▎                                                                                                  | 423/1000 [29:59<36:30,  3.80s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|████████████████████████████████████████████████████████████████████████▌                                                                                                  | 424/1000 [30:04<39:51,  4.15s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  42%|████████████████████████████████████████████████████████████████████████▋                                                                                                  | 425/1000 [30:07<36:55,  3.85s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|████████████████████████████████████████████████████████████████████████▊                                                                                                  | 426/1000 [30:10<36:01,  3.77s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████                                                                                                  | 427/1000 [30:15<39:03,  4.09s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████▏                                                                                                 | 428/1000 [30:19<37:55,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████▎                                                                                                 | 429/1000 [30:23<37:11,  3.91s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████▌                                                                                                 | 430/1000 [30:26<35:12,  3.71s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████▋                                                                                                 | 431/1000 [30:30<37:03,  3.91s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|█████████████████████████████████████████████████████████████████████████▊                                                                                                 | 432/1000 [30:33<33:28,  3.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|██████████████████████████████████████████████████████████████████████████                                                                                                 | 433/1000 [30:36<32:16,  3.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  43%|██████████████████████████████████████████████████████████████████████████▏                                                                                                | 434/1000 [30:39<32:03,  3.40s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|██████████████████████████████████████████████████████████████████████████▍                                                                                                | 435/1000 [30:44<34:34,  3.67s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|██████████████████████████████████████████████████████████████████████████▌                                                                                                | 436/1000 [30:47<33:27,  3.56s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|██████████████████████████████████████████████████████████████████████████▋                                                                                                | 437/1000 [30:50<31:01,  3.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|██████████████████████████████████████████████████████████████████████████▉                                                                                                | 438/1000 [30:54<32:30,  3.47s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████                                                                                                | 439/1000 [30:58<33:38,  3.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████▏                                                                                               | 440/1000 [31:01<34:30,  3.70s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████▍                                                                                               | 441/1000 [31:07<39:10,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████▌                                                                                               | 442/1000 [31:12<40:58,  4.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████▊                                                                                               | 443/1000 [31:15<38:48,  4.18s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|███████████████████████████████████████████████████████████████████████████▉                                                                                               | 444/1000 [31:20<39:32,  4.27s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  44%|████████████████████████████████████████████████████████████████████████████                                                                                               | 445/1000 [31:25<42:54,  4.64s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|████████████████████████████████████████████████████████████████████████████▎                                                                                              | 446/1000 [31:30<41:55,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|████████████████████████████████████████████████████████████████████████████▍                                                                                              | 447/1000 [31:33<38:37,  4.19s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|████████████████████████████████████████████████████████████████████████████▌                                                                                              | 448/1000 [31:36<34:08,  3.71s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|████████████████████████████████████████████████████████████████████████████▊                                                                                              | 449/1000 [31:40<35:26,  3.86s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|████████████████████████████████████████████████████████████████████████████▉                                                                                              | 450/1000 [31:43<34:32,  3.77s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|█████████████████████████████████████████████████████████████████████████████                                                                                              | 451/1000 [31:47<34:42,  3.79s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|█████████████████████████████████████████████████████████████████████████████▎                                                                                             | 452/1000 [31:52<38:05,  4.17s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|█████████████████████████████████████████████████████████████████████████████▍                                                                                             | 453/1000 [31:58<41:15,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  45%|█████████████████████████████████████████████████████████████████████████████▋                                                                                             | 454/1000 [32:02<40:06,  4.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|█████████████████████████████████████████████████████████████████████████████▊                                                                                             | 455/1000 [32:07<41:54,  4.61s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|█████████████████████████████████████████████████████████████████████████████▉                                                                                             | 456/1000 [32:11<39:13,  4.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|██████████████████████████████████████████████████████████████████████████████▏                                                                                            | 457/1000 [32:15<40:02,  4.42s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|██████████████████████████████████████████████████████████████████████████████▎                                                                                            | 458/1000 [32:20<40:19,  4.46s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|██████████████████████████████████████████████████████████████████████████████▍                                                                                            | 459/1000 [32:24<40:53,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|██████████████████████████████████████████████████████████████████████████████▋                                                                                            | 460/1000 [32:29<41:38,  4.63s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|██████████████████████████████████████████████████████████████████████████████▊                                                                                            | 461/1000 [32:34<40:39,  4.53s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|███████████████████████████████████████████████████████████████████████████████                                                                                            | 462/1000 [32:39<42:39,  4.76s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|███████████████████████████████████████████████████████████████████████████████▏                                                                                           | 463/1000 [32:43<41:47,  4.67s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|███████████████████████████████████████████████████████████████████████████████▎                                                                                           | 464/1000 [32:47<39:22,  4.41s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  46%|███████████████████████████████████████████████████████████████████████████████▌                                                                                           | 465/1000 [32:51<38:52,  4.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|███████████████████████████████████████████████████████████████████████████████▋                                                                                           | 466/1000 [32:56<40:28,  4.55s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|███████████████████████████████████████████████████████████████████████████████▊                                                                                           | 467/1000 [33:01<40:22,  4.54s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████                                                                                           | 468/1000 [33:06<42:50,  4.83s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████▏                                                                                          | 469/1000 [33:10<39:51,  4.50s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████▎                                                                                          | 470/1000 [33:17<45:04,  5.10s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████▌                                                                                          | 471/1000 [33:22<44:35,  5.06s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████▋                                                                                          | 472/1000 [33:26<42:34,  4.84s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|████████████████████████████████████████████████████████████████████████████████▉                                                                                          | 473/1000 [33:31<44:20,  5.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  47%|█████████████████████████████████████████████████████████████████████████████████                                                                                          | 474/1000 [33:37<44:20,  5.06s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|█████████████████████████████████████████████████████████████████████████████████▏                                                                                         | 475/1000 [33:42<43:57,  5.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|█████████████████████████████████████████████████████████████████████████████████▍                                                                                         | 476/1000 [33:46<42:59,  4.92s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                         | 477/1000 [33:51<43:46,  5.02s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                         | 478/1000 [33:59<49:50,  5.73s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|█████████████████████████████████████████████████████████████████████████████████▉                                                                                         | 479/1000 [34:04<49:31,  5.70s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████                                                                                         | 480/1000 [34:10<48:24,  5.59s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████▎                                                                                        | 481/1000 [34:17<52:14,  6.04s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████▍                                                                                        | 482/1000 [34:20<45:05,  5.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████▌                                                                                        | 483/1000 [34:25<44:45,  5.19s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████▊                                                                                        | 484/1000 [34:31<44:46,  5.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  48%|██████████████████████████████████████████████████████████████████████████████████▉                                                                                        | 485/1000 [34:37<48:03,  5.60s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████                                                                                        | 486/1000 [34:45<53:44,  6.27s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████▎                                                                                       | 487/1000 [34:50<51:06,  5.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████▍                                                                                       | 488/1000 [34:56<51:02,  5.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 489/1000 [35:01<48:33,  5.70s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                       | 490/1000 [35:06<45:19,  5.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|███████████████████████████████████████████████████████████████████████████████████▉                                                                                       | 491/1000 [35:11<44:14,  5.22s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|████████████████████████████████████████████████████████████████████████████████████▏                                                                                      | 492/1000 [35:16<45:18,  5.35s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|████████████████████████████████████████████████████████████████████████████████████▎                                                                                      | 493/1000 [35:23<47:27,  5.62s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  49%|████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 494/1000 [35:27<45:13,  5.36s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|████████████████████████████████████████████████████████████████████████████████████▋                                                                                      | 495/1000 [35:33<46:16,  5.50s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|████████████████████████████████████████████████████████████████████████████████████▊                                                                                      | 496/1000 [35:37<42:13,  5.03s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|████████████████████████████████████████████████████████████████████████████████████▉                                                                                      | 497/1000 [35:41<39:07,  4.67s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                                     | 498/1000 [35:46<39:30,  4.72s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                                     | 499/1000 [35:50<37:24,  4.48s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|█████████████████████████████████████████████████████████████████████████████████████▌                                                                                     | 500/1000 [35:54<36:57,  4.43s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|█████████████████████████████████████████████████████████████████████████████████████▋                                                                                     | 501/1000 [35:58<36:44,  4.42s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                     | 502/1000 [36:03<36:17,  4.37s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|██████████████████████████████████████████████████████████████████████████████████████                                                                                     | 503/1000 [36:06<33:34,  4.05s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                                    | 504/1000 [36:11<35:47,  4.33s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  50%|██████████████████████████████████████████████████████████████████████████████████████▎                                                                                    | 505/1000 [36:14<32:49,  3.98s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|██████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 506/1000 [36:18<33:15,  4.04s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|██████████████████████████████████████████████████████████████████████████████████████▋                                                                                    | 507/1000 [36:22<32:38,  3.97s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|██████████████████████████████████████████████████████████████████████████████████████▊                                                                                    | 508/1000 [36:27<35:06,  4.28s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████                                                                                    | 509/1000 [36:31<34:26,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                                   | 510/1000 [36:38<40:48,  5.00s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████▍                                                                                   | 511/1000 [36:42<37:59,  4.66s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████▌                                                                                   | 512/1000 [36:46<35:42,  4.39s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████▋                                                                                   | 513/1000 [36:49<32:28,  4.00s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  51%|███████████████████████████████████████████████████████████████████████████████████████▉                                                                                   | 514/1000 [36:52<31:53,  3.94s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  52%|████████████████████████████████████████████████████████████████████████████████████████                                                                                   | 515/1000 [36:57<34:04,  4.21s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  52%|████████████████████████████████████████████████████████████████████████████████████████▏                                                                                  | 516/1000 [37:02<34:45,  4.31s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  52%|████████████████████████████████████████████████████████████████████████████████████████▍                                                                                  | 517/1000 [37:06<34:30,  4.29s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

A:  52%|████████████████████████████████████████████████████████████████████████████████████████▌                                                                                  | 518/1000 [37:09<32:14,  4.01s/it]

input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'] input_types={} partial_variables={} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['business_model', 'excludes', 'gold_standard', 'includes', 'includes_also'], input_types={}, partial_variables={}, template="\nTASK \nYou get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.\n\nDEFINITION\n{includes} {includes_also}\n\n{excludes}\n\nHere are some examples of descriptions of these classes: \n```\n{gold_standard}\n```\n\nBUSINESS MODEL \n{business_model}\n\nINSTRUCTIONS\n - Create a business model description that is in a similar format as the examples\n - Do NOT exactly copy phrases, sentence patterns, or structure from the examples\n - Think of the examples as constraints, not templates\n - Also include terms other than those used in the sector definition to make the examples more diverse"), additional_kwargs={})]

:

:

In [130]:
topics["C"]["topics"][1]

"2. **Manufacture of dairy products:** A dairy cooperative that produces organic cheese using traditional recipes and sustainable practices, distributing through local farmer's markets and upscale grocery stores."

In [119]:
# print prompts
for k,v in generated_data.items(): 
    print(k,len(v["output"]), "_______"*20)
    for k in v["output"]: 
        print(k)
        print("_")

A 20 ____________________________________________________________________________________________________________________________________________
The company operates a pioneering rice farm that champions sustainable agricultural practices, prioritizing eco-friendly methods to cultivate high-quality organic rice. With a strong commitment to environmental stewardship, we employ innovative techniques that enhance soil health and biodiversity, ensuring our farming operations have a minimal ecological footprint. Our rice is grown in harmony with nature, utilizing natural pest control and organic fertilizers that contribute to the overall vitality of the ecosystem.

In addition to our cultivation practices, we emphasize local distribution channels, connecting directly with health-conscious consumers who value transparency and quality in their food sources. By fostering relationships with local markets and retailers, we ensure that our organic rice reaches customers at peak freshness, reinforcing our brand's reputation for excellence. Our strategic focus on community engagement not only supports local economies but also strengthens our supply chain resilience, allowing us to adapt swiftly to market demands. As we continue to expand our operations, we remain dedicated to promoting sustainable agriculture while delivering exceptional products that align with the values of our customers.
_
The company has established itself as a pioneer in urban agriculture, operating a state-of-the-art greenhouse facility dedicated to the cultivation of premium vegetables and melons. By leveraging innovative hydroponic techniques and sustainable practices, we ensure that our produce is not only fresh but also environmentally friendly. Our strategic partnerships with local restaurants and grocery chains allow us to deliver farm-to-table products that meet the growing consumer demand for quality and sustainability. This year, we expanded our crop offerings to include heirloom varieties and specialty melons, which have been well received in the market. Our commitment to reducing food miles and maintaining a transparent supply chain resonates with our customers, fostering loyalty and repeat business. Additionally, we have implemented advanced climate control systems within our greenhouses, optimizing growth conditions and significantly increasing yield per square foot, thereby enhancing our operational efficiency and profitability.
_
The company operates a family-owned dairy farm that prides itself on transforming its fresh milk into a range of artisanal cheeses and yogurts, celebrated for their rich flavors and quality. By leveraging traditional methods alongside modern techniques, the farm ensures that each product reflects the unique characteristics of its local terroir. In a bid to enhance customer convenience, the company has introduced a subscription model that allows local consumers to receive regular deliveries of its products straight to their doorsteps. This approach not only fosters a strong connection with the community but also supports sustainable practices by minimizing transportation emissions. The farm’s commitment to quality and local sourcing has positioned it as a beloved choice among consumers seeking authentic dairy products, while its innovative delivery service is designed to meet the growing demand for fresh, locally-produced food options.
_
The company operates a comprehensive agroforestry model that synergistically blends timber production with the cultivation of high-value medicinal herbs. By integrating these two sectors, we not only enhance our revenue streams but also contribute to the preservation of biodiversity within our ecosystems. Our timber operations focus on sustainable harvesting practices, ensuring that we maintain healthy forest environments while meeting market demands for quality wood products. Concurrently, our herb cultivation initiative emphasizes the growth of native and medicinal plants, tapping into the increasing consumer interest in natural wellness solutions. This dual approach not only fortifies our financial resilience but also aligns with our commitment to environmental stewardship. As we expand our operations, we are investing in advanced agricultural techniques and eco-friendly practices to optimize yield and sustainability, thus positioning ourselves as a leader in the agroforestry sector.
_
The company has established itself as a pioneering force in the organic tobacco cultivation sector, leveraging sustainable agricultural practices to produce high-quality tobacco products. Our operations are centered around cultivating premium tobacco varieties that meet the growing demand for organic and ethically sourced goods. By utilizing direct-to-consumer sales channels, we have effectively bridged the gap between our farms and discerning customers who value quality and sustainability. This approach not only enhances our brand's visibility but also fosters a deeper connection with our consumers.

In recent years, we have invested significantly in innovative growing techniques, ensuring that our crops thrive in a manner that respects both the environment and the health of our consumers. Our commitment to organic methods has allowed us to differentiate our offerings in a competitive market, appealing to a clientele that prioritizes both quality and ecological responsibility. As we continue to expand our reach, we remain focused on maintaining the integrity of our products, cultivating partnerships that align with our values, and promoting transparency throughout our supply chain. This strategic direction positions us for sustained growth while contributing positively to the communities in which we operate.
_
The company operates a diversified agricultural enterprise that seamlessly integrates livestock production with crop cultivation. By raising poultry and swine alongside the cultivation of high-quality feed crops, we have developed a robust system that maximizes resource efficiency while minimizing operational expenditures. Our strategic approach allows us to leverage the synergies between animal husbandry and crop production, ensuring a consistent supply of nutritious feed that supports the health and growth of our livestock. This dual focus not only enhances our productivity but also positions us favorably in the market, as we are able to respond swiftly to changing consumer demands. Furthermore, our commitment to sustainable practices is evident in our ongoing investments in technology and innovative farming techniques, which help us reduce our environmental footprint while maintaining profitability. As we continue to refine our operations, we remain dedicated to delivering high-quality products that meet the expectations of our customers and contribute positively to the agricultural landscape.
_
The company has established itself as an innovative leader in the vertical farming sector, utilizing advanced hydroponic systems to cultivate a variety of leafy greens throughout the year. Our operations are strategically located in urban areas, allowing us to efficiently supply local cafes and grocery chains with fresh, high-quality produce that meets the growing demand for sustainable food sources. By harnessing cutting-edge technology and sustainable practices, we optimize resource use, significantly reducing water consumption and eliminating the need for pesticides. This commitment to environmental stewardship not only enhances the flavor and nutritional value of our greens but also ensures that our supply chain remains resilient and responsive to market needs. As we continue to expand our footprint, we are dedicated to fostering partnerships with local businesses, creating a robust ecosystem that benefits both our customers and the communities we serve.
_
The company operates a unique spice farm dedicated to the cultivation of rare and high-value spice varieties, catering to the discerning tastes of food enthusiasts and gourmet chefs alike. Situated in a region known for its rich biodiversity, the farm employs sustainable agricultural practices to grow an array of exotic spices, including saffron, cardamom, and vanilla. In addition to traditional farming, the company has embraced innovation by offering educational tours that immerse visitors in the art of spice cultivation and harvesting. These tours not only enhance customer engagement but also promote awareness of the complexities involved in producing premium spices. Furthermore, the company has developed a robust online sales platform, allowing culinary professionals and home cooks to access its exclusive products year-round. This dual approach of direct-to-consumer sales and experiential learning positions the company as a leader in the niche market of specialty spices, fostering a deeper appreciation for quality and sustainability in the culinary arts.
_
The company operates a state-of-the-art aquaculture facility dedicated to the sustainable farming of freshwater fish, strategically positioned to cater to local market demands for nutritious seafood. Our commitment to environmental stewardship is reflected in our innovative practices, which prioritize ecological balance while ensuring high-quality fish production. By utilizing advanced filtration systems and recirculating aquaculture technology, we significantly reduce water usage and waste output, setting a benchmark for sustainability in the industry.

In our production process, we focus on species that thrive in our controlled environments, allowing us to maintain a consistent supply of fresh fish year-round. Our operations are designed to minimize our carbon footprint while maximizing the health benefits of our seafood offerings. We actively engage with local communities, fostering partnerships that enhance our supply chain and promote awareness of sustainable fishing practices. By aligning our business strategies with environmental goals, we not only meet consumer preferences for responsibly sourced products but also contribute to the preservation of aquatic ecosystems.
_
The company has established itself as a prominent player in the specialty oils market, leveraging the unique properties of oleaginous fruits to cater to the growing health-conscious consumer base. With a commitment to sustainability, we meticulously source our raw materials from environmentally responsible farms, ensuring that our production processes not only yield high-quality oils but also support local ecosystems. Our product line features a diverse array of oils, each crafted to enhance culinary experiences while promoting wellness.

In recent years, we have expanded our operations to include innovative extraction techniques that maximize the nutritional benefits of our oils, setting us apart in a competitive landscape. Our strategic partnerships with local growers allow us to maintain a steady supply of premium ingredients, while our investment in state-of-the-art processing facilities ensures that we meet the increasing demand for our products across various markets. By prioritizing transparency and ethical sourcing, we aim to foster a loyal customer base that values both quality and sustainability in their dietary choices.
_
The company operates a vibrant plantation dedicated to cultivating a diverse range of tropical fruits, including mangoes, pineapples, and passion fruits. Our commitment extends beyond simple cultivation; we actively collaborate with local artisans to transform these fresh produce into unique, value-added offerings such as artisanal jams, refreshing juices, and gourmet preserves. This synergy not only enhances the product line but also supports local economies by providing artisans with sustainable income opportunities.

By tapping into niche markets, we ensure that our products resonate with consumers seeking high-quality, authentic flavors. Our strategic focus on sustainable farming practices allows us to maintain the health of our ecosystems while meeting the growing demand for organic and ethically sourced products. With a robust distribution network, we are poised to deliver our exceptional offerings to both local and international markets, fostering a brand reputation built on quality and community engagement. As we look ahead, our vision is to expand our product range while remaining committed to the principles of sustainability and social responsibility that define our operations.
_
The company has established a robust community-supported agriculture (CSA) program that fosters a direct connection between consumers and local farmers. Through this initiative, subscribers receive curated boxes filled with a diverse selection of seasonal produce, showcasing the best offerings from regional farms. This model not only promotes sustainable farming practices but also empowers local agricultural communities by ensuring they receive fair compensation for their harvests. By emphasizing freshness and quality, the company has cultivated a loyal customer base that values the transparency of knowing where their food comes from. As part of its commitment to sustainability, the company actively engages in educational outreach, helping consumers understand the benefits of seasonal eating and the importance of supporting local agriculture. The CSA program has not only strengthened community ties but has also positioned the company as a leader in promoting environmentally responsible food sourcing practices.
_
The company operates as a pioneering force in the confectionery sector, harnessing solar energy to power its operations while emphasizing sustainability at every step of the production process. By partnering with local farmers, the company sources high-quality raw sugar cane, ensuring that its supply chain supports ethical agricultural practices. The crafting of organic sweets is not merely a production process but an art form that reflects the company’s commitment to quality and environmental stewardship. Each product is designed to engage consumers not just through taste, but also by educating them on the importance of sustainable practices in their everyday choices. In addition to creating a diverse range of candies, from classic favorites to innovative flavors, the company actively participates in community outreach programs that promote awareness about renewable energy and responsible sourcing. This holistic approach not only enhances brand loyalty but also positions the company as a leader in the movement towards a more sustainable future in the candy industry.
_
The company has established itself as a pioneer in the intersection of sustainable forestry and eco-tourism, creating a unique model that not only emphasizes responsible timber harvesting but also invites visitors to engage with nature. By offering immersive guided tours, the company showcases its commitment to environmentally friendly practices while educating guests on the importance of forest conservation. These tours are designed to highlight the intricate balance between resource utilization and ecological preservation, allowing participants to witness firsthand the sustainable methods employed in timber extraction.

In addition to the tours, the company operates a series of eco-friendly lodges that provide visitors with comfortable accommodations amidst breathtaking natural landscapes. This dual approach not only generates revenue through timber sales but also enhances the local economy by attracting tourists eager to experience the beauty of the region. The company is dedicated to fostering an appreciation for nature, ensuring that each aspect of its operations aligns with its sustainability goals. By integrating tourism with forestry, the company aims to create a lasting impact on both the environment and the community, ensuring that future generations can enjoy the rich resources of the land.
_
The company operates a state-of-the-art rice milling facility dedicated to transforming locally sourced rice into premium products for both restaurants and retail partners. By prioritizing quality and sustainability, the company collaborates closely with regional farmers to ensure that only the finest grains are selected for processing. This commitment to local sourcing not only supports the community but also guarantees freshness and flavor that discerning chefs and consumers have come to expect. The milling process is meticulously designed to preserve the nutritional integrity of the rice while enhancing its culinary attributes, allowing for a diverse range of products that cater to various culinary applications. As part of our growth strategy, we are expanding our distribution network to reach new markets, ensuring that our high-quality rice is accessible to a broader audience. By fostering strong relationships with local producers and maintaining rigorous quality control standards, the company is well-positioned to meet the increasing demand for premium rice products in a competitive landscape.
_
The company operates a sustainable poultry farm dedicated to raising free-range chickens, which thrive in a natural environment that promotes their well-being. By prioritizing humane practices, we ensure that our birds have ample space to roam and forage, resulting in healthier chickens and superior quality eggs. Our primary focus is on the production of pasture-raised eggs, which we distribute directly to consumers through local farmers' markets and our own online platform. This direct-to-consumer approach not only fosters a close relationship with our customers but also allows us to maintain transparency about our farming practices. As we continue to expand our presence in the community, we are committed to educating consumers on the benefits of pasture-raised products, while also implementing eco-friendly initiatives that minimize our environmental footprint. Our dedication to quality and sustainability has positioned us as a trusted source for families seeking nutritious, ethically produced eggs.
_
The company operates as a distinguished cultivator of aromatic herbs, focusing on both culinary and therapeutic applications. With a commitment to sustainable farming practices, we nurture a diverse range of herbs, including basil, rosemary, and lavender, which are meticulously grown to enhance flavor profiles and promote wellness. Our operations extend beyond cultivation; we actively engage with our community through workshops designed to educate customers on the myriad benefits of these botanicals. These interactive sessions not only foster a deeper appreciation for our products but also empower individuals to incorporate these herbs into their daily lives. By blending traditional farming techniques with modern educational initiatives, we aim to create a holistic experience that resonates with health-conscious consumers and culinary enthusiasts alike. Our strategic partnerships with local chefs and wellness experts further amplify our mission, ensuring that our herbs are not only enjoyed but also celebrated for their rich heritage and versatility.
_
The company has established itself as a prominent player in the leather goods sector, focusing on the ethical sourcing of hides from livestock raised under humane conditions. This commitment to sustainability is woven into the fabric of our operations, as we prioritize cruelty-free practices throughout our supply chain. By collaborating closely with local farmers who share our values, we ensure that the livestock is raised in a manner that respects animal welfare and promotes environmental stewardship.

Our production process is characterized by meticulous craftsmanship, where skilled artisans transform high-quality hides into a diverse range of leather products, including handbags, wallets, and accessories. We maintain a robust quality control system that guarantees each item meets our stringent standards for durability and aesthetic appeal.


In [110]:
len(v["data"])

68

In [98]:
# print prompts
for k,v in generated_data.items(): 
    print(k,"_______"*20)
    print(v["user_prompt"])

A ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats.



Here are some examples of descriptions of these classes:
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODEL
20. A firm specializing in the production of biodegradable packaging from agricultural waste, targeting eco-conscious brands and businesses.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse
C ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the physical or chemical transformation of materials, substances, or components into new products, although this cannot be used as the single universal criterion for defining manufacturing (see remark on processing of waste below). The materials, substances, or components transformed are raw materials that are products of agriculture, forestry, fishing, mining or quarrying as well as products of other manufacturing activities. Substantial alteration, renovation or reconstruction of goods is generally considered to be manufacturing.\n\nThe output of a manufacturing process may be finished in the sense that it is ready for utilisation or consumption, or it may be semi-finished in the sense that it is to become an input for further manufacturing. For example, the output of alumina refining is the input used in the primary production of aluminium; primary aluminium is the input to aluminium wire drawing; and aluminium wire is the input for the manufacture of fabricated wire products.\n\nManufacture of specialised components and parts of, and accessories and attachments to, machinery and equipment is, as a general rule, classified in the same class as the manufacture of the machinery and equipment for which the parts and accessories are intended. Manufacture of unspecialised components and parts of machinery and equipment, e.g. engines, pistons, electric motors, electrical assemblies, valves, gears, roller bearings, is classified in the appropriate class of manufacturing, without regard to the machinery and equipment in which these items may be included. However, making specialised components and accessories by moulding or extruding plastics materials is included in group 22.2.\n\nAssembly of the component parts of manufactured products is considered manufacturing. This includes the assembly of manufactured products from either self-produced or purchased components. \n\nThe recovery of waste, i.e. the processing of waste into secondary raw materials is classified in group 38.3 (Materials recovery). While this may involve physical or chemical transformations, this is not considered to be a part of manufacturing. The primary purpose of these activities is considered to be the treatment or processing of waste and they are therefore classified in Section E (Water supply; sewerage, waste management and remediation activities). However, the manufacture of new final products (as opposed to secondary raw materials) is classified in manufacturing, even if these processes use waste as an input. For example, the production of silver from film waste is considered to be a manufacturing process.\n\nSpecialised maintenance and repair of industrial, commercial and similar machinery and equipment is, in general, classified in division 33 (Repair, maintenance and installation of machinery and equipment). However, the repair of computers and personal and household goods is classified in division 95 (Repair of computers and personal and household goods), while the repair of motor vehicles is classified in division 45 (Wholesale and retail trade and repair of motor vehicles and motorcycles). \n\nThe installation of machinery and equipment, when carried out as a specialised activity, is classified in 33.20. \n\nRemark: The boundaries of manufacturing and the other sectors of the classification system can be somewhat blurry. As a general rule, the activities in the manufacturing section involve the transformation of materials into new products. Their output is a new product. However, the definition of what constitutes a new product can be somewhat subjective. As clarification, the following activities are considered manufacturing in NACE:\n- fresh fish processing (oyster shucking, fish filleting), not done on a fishing boat (see 10.20)\n- milk pasteurising and bottling (see 10.51)\n- leather converting (see 15.11)\n- wood preserving (see 16.10)\n- printing and related activities (see 18.1)\n- tyre retreading (see 22.11)\n- ready-mixed concrete production (see 23.63)\n- electroplating, plating, and metal heat treating (see 25.61)\n- rebuilding or remanufacture of machinery (e.g. automobile engines, see 29.10)\n\nConversely, there are activities that, although sometimes involving transformation processes, are classified in other sections of NACE; in other words, they are not classified as manufacturing. They include:\n- logging, classified in section A (Agriculture, forestry and fishing);\n- beneficiating of agricultural products, classified in section A (Agriculture, forestry and fishing); \n- preparation of food for immediate consumption on the premises is classified to division 56 (Food and beverage service activities);\n- beneficiating of ores and other minerals, classified in section B (Mining and quarrying); \n- construction of structures and fabricating operations performed at the site of construction, classified in section F (Construction);\n- activities of breaking bulk and redistribution in smaller lots, including packaging, repackaging, or bottling products, such as liquors or chemicals; sorting of scrap; mixing paints to customer order; and cutting metals to customer order; treatment not resulting into a different good is classified to section G (Wholesale and retail trade; repair of motor vehicles and motorcycles).



Here are some examples of descriptions of these classes:
```
Example 1:
We are a development stage biopharmaceutical company focused on discovering and developing novel and distinctive small molecule therapeutics that modulate G protein-coupled receptors, or GPCR, pathways. We are designing proprietary novel small molecule therapeutic candidates with the intent of developing best/first in class therapeutics for the treatment of metabolic, inflammatory and fibrotic diseases with significant unmet medical needs, using our integrated drug discovery platform, medicinal chemistry expertise and deep understanding of the GPCR biology.Our pipeline is currently made up of three development programs. The candidate we selected for clinical development, LMNL6511, a selective antagonist for the GPR84 receptor, is expected to commence a Phase 1 clinical trial in the second half of 2023. We are also developing potential OXER1 antagonists and GPR40 agonists, both of which are at the preclinical stage. In addition to these priority development programs, we continue to explore other development opportunities to add to our pipeline.We believe that our drug discovery platform and deep understanding of GPCRs allows us to identify small molecule candidates that can accurately target GPCRs where other drug discovery approaches have been unsuccessful. Our drug discovery platform leverages a fully integrated chemistry and biology expertise supported by our broad in vivo capabilities, which allows us to investigate our preclinical drug candidates' efficacy in a wide variety of animal models and enables us to develop small molecule therapeutic candidates for the treatment of various metabolic, inflammatory and fibrotic diseases. We aim to develop best or first-in-class therapies targeting indications with significant unmet needs, where a novel small molecule approach may be better suited using our drug discovery platform, specialized know-how and data-driven development plans.We are led by a strong, experienced team with proven track records in the discovery, development, and approval of biopharmaceuticals. Our team's extensive experience in clinical development, and regulatory success is backed by our data driven philosophy.

Example 2:
The company Biologics is a biopharma company focused on developing and commercializing innovative gene therapies for retinal neurodegenerative diseases and central nervous system disorders. The company is currently concentrating its efforts and resources on securing the upcoming LUMEVOQ validation campaign with its manufacturing partner in the US. Additionally, GenSight is discussing a financing bridge with certain existing shareholders to extend its cash runway beyond the results of the validation campaign expected in Q3 2023.

Example 3:
As a global leader in optical technologies, we harness the full spectrum of light to make life better. From product idea to tangible design through to the manufacturing process, we enable our customers to create high performance optical applications for the automotive, consumer, industrial and healthcare markets. What differentiates us, is our broad technology spectrum covering the emission of light as well as its detection through sensing and intelligent processing. We serve the value chain of optical solutions with our innovative products and solutions, which are designed for best-in class performance, size, cost and energy efficiency.We are experts in the development and integration of a wide range of optical technologies, from single components through to complex systems. This enables us to be a market and innovation leader, serve our customers as trusted partners and differentiate ourselves in the marketplace.
```

BUSINESS MODEL
20. **Manufacture of jewellery and related articles:** An artisan jeweller creating bespoke pieces using ethically sourced gemstones, targeting consumers interested in unique and sustainable jewellery.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse

#### aggregate data and split

In [26]:
generated_data["A"].keys()

dict_keys(['data'])

In [31]:
# config

config = {
    #
    # 
    "prompts": {k: v.get("user_prompt") for k, v in generated_data.items()}, 
    #"samples": num_samples * iterations_,
    #"generated_iterations": iterations_,
    "level": level,
    "head_nace_code": head_nace_code,
    "system_prompt": get_system_prompt(prompt_path), 
    "few_shot_prompting": few_shot
}

# store
import json
with open(os.path.join(store_path, "config.json"), "w") as f: 
    json.dump(config, f, indent=4)

In [32]:
df_full = []
for k, v in generated_data.items(): 
    df_temp = pd.DataFrame(v["data"], columns=["text"])
    df_temp["label"] = k
    df_full.append(df_temp)
df_full = pd.concat(df_full, axis=0)

In [33]:
df_full

                                                   text label
0     The company operates a pioneering rice farm th...     A
1     In addition to our cultivation practices, we e...     A
2     The company has established itself as a pionee...     A
3     The company operates a family-owned dairy farm...     A
4     The company operates a comprehensive agrofores...     A
...                                                 ...   ...
996   In 2023, we expanded our operations by integra...     C
997   Furthermore, we actively collaborate with arch...     C
998   At EcoModular Homes, we are redefining the lan...     C
999   Our modular units are designed with flexibilit...     C
1000  In 2023, we are excited to expand our offering...     C

[2002 rows x 2 columns]

In [34]:
# make new index from 0 to len(df_full)-1
df_full = df_full.reset_index(drop=True)
df_full

                                                   text label
0     The company operates a pioneering rice farm th...     A
1     In addition to our cultivation practices, we e...     A
2     The company has established itself as a pionee...     A
3     The company operates a family-owned dairy farm...     A
4     The company operates a comprehensive agrofores...     A
...                                                 ...   ...
1997  In 2023, we expanded our operations by integra...     C
1998  Furthermore, we actively collaborate with arch...     C
1999  At EcoModular Homes, we are redefining the lan...     C
2000  Our modular units are designed with flexibilit...     C
2001  In 2023, we are excited to expand our offering...     C

[2002 rows x 2 columns]

In [35]:
import re
clean_text = lambda x: re.sub(r'^\d+\.\s*', " ", x).strip()

In [36]:
df_full["text"] = df_full["text"].apply(clean_text)

In [37]:
df_full.to_csv(os.path.join(store_path, "synthetic_data_full.csv"), index=False)

In [38]:
# make train test split 6:2:2

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(df_full, test_size=0.4, random_state=42, stratify=df_full["label"])
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df["label"])

len(train_df), len(test_df), len(val_df)

(1201, 400, 401)

In [39]:
train_df.to_csv(os.path.join(store_path, "train_data.csv"), index=False)
test_df.to_csv(os.path.join(store_path, "test_data.csv"), index=False)
val_df.to_csv(os.path.join(store_path, "val_data.csv"), index=False)

In [ ]:
llm = ChatOllama(
            model="llama3.1:8b-instruct-fp16",
            temperature=0.1, 
            base_url="http://10.80.20.101:11434/"
        )

In [ ]:
llm.invoke("HI")

ResponseError: llama runner process has terminated: CUDA error: out of memory
  current device: 0, in function ggml_backend_cuda_device_get_memory at //ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:3238
  cudaMemGetInfo(free, total)
//ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:84: CUDA error (status code: 500)

In [ ]:
import tiktoken

tokenizer = tiktoken.encoding_for_model("gpt-4o-mini")

In [ ]:
len(tokenizer.encode("""1. Our company specializes in sustainable logging practices, focusing on the selective harvesting of timber from both natural and planted forests. We employ advanced techniques to minimize environmental impact while maximizing yield. Our operations include the use of eco-friendly machinery that reduces soil disturbance and promotes forest regeneration. Additionally, we provide firewood and charcoal products sourced from responsibly managed forests, ensuring that our offerings meet high environmental standards. By collaborating with local communities, we also support the gathering of non-wood forest products, enhancing biodiversity and fostering economic development in rural areas.

2. In our forestry operations, we prioritize silviculture techniques that enhance forest health and productivity. We implement practices such as thinning and controlled burns to promote the growth of high-quality timber. Our team conducts regular assessments to monitor forest conditions and adapt our management strategies accordingly. We also engage in the collection of non-wood products like wild mushrooms and medicinal herbs, which are harvested sustainably to ensure long-term availability. By integrating these activities, we create a diversified revenue stream while contributing to the conservation of forest ecosystems.

3. Our logging company is committed to responsible forest management, focusing on the extraction of roundwood in a way that preserves the ecological balance of the forest. We utilize state-of-the-art equipment designed to minimize waste and ensure the efficient harvesting of timber. Our operations are complemented by a robust training program for our workforce, emphasizing safety and environmental stewardship. Furthermore, we offer a range of products, including pit-props and pulpwood, which are supplied to various industries, ensuring that our timber is used effectively and sustainably.

4. We are dedicated to the gathering of wild growing non-wood forest products, which play a vital role in supporting local economies and promoting biodiversity. Our team works closely with foragers to identify and harvest edible plants, berries, and nuts in a sustainable manner. By implementing strict guidelines on harvesting practices, we ensure that these resources are available for future generations. Additionally, we provide training and resources to local communities, empowering them to participate in this industry while preserving their traditional knowledge and practices.

5. Our company offers comprehensive support services to forestry operations, including consulting on sustainable practices and forest management planning. We provide expertise in areas such as reforestation, pest management, and soil conservation, helping clients optimize their forestry activities. Our services extend to training programs for forest workers, focusing on safety protocols and sustainable harvesting techniques. By partnering with clients, we aim to enhance the productivity and sustainability of their forestry operations, contributing to the overall health of forest ecosystems.

6. We focus on the extraction of high-quality roundwood, utilizing advanced logging techniques that prioritize sustainability and efficiency. Our operations are designed to minimize waste and enhance the recovery of valuable timber products. We also engage in the production of firewood, which is sourced from our managed forests and processed to meet consumer demand. Our commitment to responsible forestry practices ensures that we not only meet market needs but also contribute positively to the environment and local communities.

7. Our forestry management firm specializes in the cultivation and maintenance of planted forests, ensuring a steady supply of timber for various applications. We implement innovative silvicultural practices that enhance growth rates and timber quality, while also focusing on biodiversity conservation. In addition to timber production, we engage in the collection of non-wood forest products, such as wild herbs and berries, which are marketed to local businesses. This dual approach allows us to maximize the economic value of our forests while promoting ecological health.

8. We are involved in the logging sector, where our operations emphasize the careful extraction of timber from both natural and managed forests. Our commitment to sustainability is reflected in our use of low-impact logging techniques, which help preserve the integrity of the forest ecosystem. We also produce charcoal and firewood, catering to the growing demand for renewable energy sources. By maintaining a focus on environmental responsibility, we strive to balance economic viability with ecological preservation.

9. Our company is dedicated to the sustainable gathering of wild growing non-wood products, which are integral to the livelihoods of many local communities. We prioritize ethical harvesting practices that ensure the long-term availability of these resources. Our team collaborates with local foragers to promote best practices and provide training on sustainable collection techniques. By creating a market for these products, we not only support local economies but also contribute to the conservation of forest biodiversity.

10. We provide essential support services to forestry operations, helping clients navigate the complexities of sustainable forest management. Our team offers expertise in areas such as land assessment, resource inventory, and compliance with environmental regulations. We also facilitate training programs focused on best practices for logging and non-wood product harvesting. By equipping forestry businesses with the knowledge and tools they need, we aim to enhance their operational efficiency and promote sustainable practices across the sector.

"""))

In [ ]:
pd.DataFrame(data, columns=[generate_nace_class])

In [ ]:
data