In [4]:
import pandas as pd
import os
import math
import numpy as np
import json
import random
import re
import copy
from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from tqdm import tqdm
import datetime

os.chdir('/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis')

from generate_synthetic_data.generate_synthetic_data_topics_level_4_best_iterate_data import generate_synthetic_data, generate_topic, split_synthetic_data, get_sublevels_df

FileNotFoundError: [Errno 2] No such file or directory: '/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis'

In [ ]:
nace_description_path = "../data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv"
nace_description_path = "data/NACE_Rev2_Structure_Explanatory_Notes_EN__1_.tsv"
nace_descriptions = pd.read_csv(nace_description_path, sep="\t")

In [ ]:
def get_zero_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_zero_shot"]

def get_few_shot_user_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["user_prompt_few_shot"]

def get_system_prompt(path): 
    with open(path, "r") as f: 
        prompt_json = json.load(f)

    return prompt_json["system_prompt"]

In [5]:
user_prompt_topic = """
TASK
For the following business sector, create short descriptions of realistic business models for exisiting companies. 

DEFINITION
{includes} {includes_also}

{excludes}

INSTRUCTION
- Create a list of {num_samples} different realistic explanations of a business model 
- The length should be one sentence
- Pick one or multiple subsections for this business model
- Do not explain what you did or what you used
- Output only a numbered list
- Do not add any introduction, explanation, or concluding text
- Start directly with item 1
- Dot invent another name
"""

In [6]:
def get_sublevels(nace_class, level): 
    nace_class_temp = nace_class
    nace_id = nace_descriptions[nace_descriptions["CODE"] == nace_class_temp]["ID"].iloc[0]
    nace_class_lvl_2 = []
    nace_class_lvl_3 = []
    nace_class_lvl_4 = []

    for _, row in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id].iterrows(): 
        nace_id_temp = row["ID"]
        nace_class_lvl_2.append(f'{row["NAME"]}')
        for _, row_2 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp].iterrows(): 
            nace_id_temp_temp = row_2["ID"]
            nace_class_lvl_3.append(f'{row["NAME"]}: {row_2["NAME"]}')
            for _, row_3 in nace_descriptions[nace_descriptions["PARENT_ID"] == nace_id_temp_temp].iterrows(): 
                nace_class_lvl_4.append(f'{row["NAME"]}: {row_2["NAME"]}: {row_3["NAME"]}')
        
    if level == 2: 
        return nace_class_lvl_2
    if level == 3: 
        return nace_class_lvl_3
    if level == 4: 
        return nace_class_lvl_4

In [7]:
#nace_descriptions[nace_descriptions["PARENT_ID"] == nace_descriptions[nace_descriptions["CODE"] == "01.1"]["ID"]]
nace_descriptions[nace_descriptions["PARENT_ID"] == "1399"]
nace_descriptions[nace_descriptions["ID"] == "1310"]

NameError: name 'nace_descriptions' is not defined

In [8]:
get_rows_under_code_at_level(nace_descriptions, nace_class="A", level=4)

NameError: name 'get_rows_under_code_at_level' is not defined

In [10]:
get_sublevels_df("01.3", level=3)

NameError: name 'get_sublevels_df' is not defined

In [11]:
generate_nace_class = "A"

includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
assert includes is not None and includes != ""
includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
includes_also = "" if pd.isna(includes_also) else includes_also
excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
excludes = "" if pd.isna(excludes) else excludes

gold_standard = []

NameError: name 'nace_descriptions' is not defined

## Generate Few-Shot Data

In [ ]:
# select gold standard data

# ds_2_desc  = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")

# ds_2_desc  = ds_2_desc[pd.notna(ds_2_desc["Description"])]

# gold_standard = []
# # 1. take one of each lvl 3 class:
# for lvl_3 in ds_2_desc[pd.notna(ds_2_desc["Description"])].groupby("NACE_lvl_3").size().index: 
#     gold_standard.append(ds_2_desc[ds_2_desc["NACE_lvl_3"] == lvl_3].iloc[0])

# df_gold_standard = pd.concat(gold_standard, axis=1).T

#df_gold_standard.to_csv("/Users/hendrikweichel/Downloads/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv")

In [12]:
#df_gold_standard = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")
#df_gold_standard = pd.read_csv("data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")
#df_gold_standard = pd.read_csv("../data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_gold_standard_descriptions_for_data_generation.csv", sep=";")
df_gold_standard = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview_with_description.csv", sep=";")
df_gold_standard = df_gold_standard[df_gold_standard["Description_clean"].notna()]

### Hyperparams

In [41]:
prompt_path = "generate_synthetic_data/prompts/prompts_5_list.json"
prompt_path = "../generate_synthetic_data/prompts/prompts_5_list.json"
prompt_path = "../generate_synthetic_data/prompts/prompts_5_list_hardcoded_few_shot.json"
print("System Prompt: ", get_system_prompt(prompt_path))
print("User Prompt: ", get_few_shot_user_prompt(prompt_path))

System Prompt:  You generate realistic paragraphs from corporate annual reports that are a presentation of the copmanies business model. The text must: - sound natural and specific - avoid textbook or definitional language - vary structure, length, and narrative style - include concrete operational details The text must NOT: - repeat industry definitions - follow a fixed template - explicitly explain what the company does in generic terms
User Prompt:  TASK
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
{includes} {includes_also}

{excludes}

Here are some examples of descriptions of other companies:
```
- The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.
- As a global leader in optical technologies, we harness the full spectrum of light to make life better. From product idea to tangible design through to the manufacturing process, we enable our customers to create high performance optical applications for the automotive, consumer, industrial and healthcare markets. What differentiates us, is our broad technology spectrum covering the emission of light as well as its detection through sensing and intelligent processing. We serve the value chain of optical solutions with our innovative products and solutions, which are designed for best-in class performance, size, cost and energy efficiency. We are experts in the development and integration of a wide range of optical technologies, from single components through to complex systems. This enables us to be a market and innovation leader, serve our customers as trusted partners and differentiate ourselves in the marketplace.
- The company is a global engineering, property and infrastructure company that provides innovative solutions and delivers sustainable developments. We have grown to become Malaysia's leading infrastructure and property developer since our founding in 1976. Gamuda's differentiated strengths and expertise underscore our growth of nearly five decades. We believe that profitability and sustainability are not mutually exclusive. This is why Environmental, Social and Governance (ESG) have long been emphasised in Gamuda's business strategy. The Gamuda Green Plan 2025 formalised our decades-long commitment to sustainability. It outlines our overarching approach to ESG, risks and opportunities, strategic priorities and plans. We are a regional player operating in Malaysia, Vietnam, Australia, Taiwan, Singapore, United Kingdom, India, Bahrain and Qatar.
```

BUSINESS MODELS
{business_model}

INSTRUCTIONS
 - For each given business model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse

 - Start directly with item 1
 - Do not use line breaks in the descriptions
 - Do not add any introduction, explanation, or concluding text
 - enumarate the descriptions

In [42]:
level = 1
head_nace_code = "1" if level > 1 else None
generated_classes = nace_descriptions[nace_descriptions["PARENT_ID"] == head_nace_code]["CODE"]
generated_classes = ["A", "B", "C", "J", "F"]
generated_classes = ["B"]

In [43]:
few_shot = True

In [44]:
# generate date 

date = datetime.datetime.now().strftime("%Y%m%d")
suffix = "__few_shot" if few_shot else "__zero_shot"
suffix += "__from_lvl_4_topics"
store_path = "data/synthetic_data/two_step/data_" + date + f"__level_{level}__subclasses_{head_nace_code}__{os.path.basename(prompt_path).replace('.json', '')}{suffix}/" 
os.makedirs(store_path, exist_ok=True)

In [45]:
generated_data = {}

In [46]:
# # load previous results
# prev_results = "projects/nace_classification/nace_report_topic_analysis/data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot/class_A.csv"
# prev_results = "data/synthetic_data/data_20251218__level_1__subclasses_None__prompts_5__few_shot"
# for class_name in generated_classes: 
#    file_path = os.path.join(prev_results, f"class_{class_name}.csv")
#    try:
#        df = pd.read_csv(file_path)
#        generated_data[class_name] = {
#            "data": df[class_name].tolist()
#        }
#    except Exception as e:
#        print(f"Could not load previous results for class {class_name}: {e}")

### Generate Topics

Here: 

- for each class get the subclasses on level 4
- for each subclass: 
    - generate k topics such that n_data topics are created

In [48]:
model = "gpt-4o-mini"
model = "llama3.1:70b"
model = "openai/gpt-oss-120b"

In [49]:
topic_prompt_path = "../generate_synthetic_data/prompts/topic_prompts_1.json"

In [50]:
n_data = 10 # total number of samples to generate per class
num_samples = 10 # number of samples per iteration (generated through one LLM call)
iterations_ = n_data // num_samples

In [51]:
topics = {}

In [53]:
for generate_nace_class in generated_classes:

    df_subsections = get_sublevels_df(generate_nace_class, level=4)

    topics_per_subsec = math.ceil(n_data / len(df_subsections))
    topic_samples = min(topics_per_subsec, 50)
    topic_iterations = math.ceil(topics_per_subsec / topic_samples)

    print("Nbr. of Subsecs. : ", len(df_subsections), ", Topics per Subclass", topics_per_subsec, ", Samples per LLM call: ", topic_samples, ", LLM calls per Subsec.: ", topic_iterations)

    examples = []

    for i, subsection in tqdm(df_subsections.head(1).iterrows()): 

        includes = subsection["Includes"]
        if pd.isna(includes):
            includes = subsection["NAME"]

        includes_also = subsection["IncludesAlso"]
        includes_also = "" if pd.isna(includes_also) else includes_also
        excludes = subsection["Excludes"]
        excludes = "" if pd.isna(excludes) else excludes

        topics_subsection = []

        for i in range(3):
        #for i in range(topic_iterations):
            res = generate_topic(num_samples=topic_samples, 
                                includes=includes, 
                                includes_also=includes_also, 
                                excludes=excludes,  
                                prompt_path=topic_prompt_path, 
                                model=model, 
                                temperature=0.8)

            topics_subsection.append(res[1])
        
        examples.append({"CODE": subsection["CODE"], "NAME": subsection["NAME"], "TOPICS": "\n".join(topics_subsection)})
    
    
    examples = pd.DataFrame(examples)

    clean_text = lambda x: re.sub(r'^\d+\.\s*', " ", x).strip()
    data = split_synthetic_data("\n\n".join(examples["TOPICS"]), num_samples * iterations_)
    data = list(map(clean_text, data))
    
    results = {
        "topics": random.sample(data, k=2),
        "topics_df": examples,
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": data,
        "few_shot": few_shot
    }

    topics[generate_nace_class] = results

Nbr. of Subsecs. :  33 , Topics per Subclass 1 , Samples per LLM call:  1 , LLM calls per Subsec.:  1

0it [00:00, ?it/s]

0it [00:00, ?it/s]

ResponseError: model 'openai/gpt-oss-120b' not found

#### Store Topics

In [25]:
all_topics = []
for class_ in topics: 
    df_temp = topics[class_]["topics_df"].copy()
    df_temp["LVL_1_CODE"] = class_
    all_topics.append(df_temp)

all_topics = pd.concat(all_topics, axis=0)
all_topics.to_csv(os.path.join(store_path, "all_topics.csv"))

In [26]:
topics_store = copy.deepcopy(topics)
for class_ in topics_store: 
    topics_store[class_]["topics_df"] = None

with open(os.path.join(store_path, "topics.json"), "w") as f: 
    json.dump(topics_store, f, indent=4)

### Generate Descriptions

In [27]:
generated_data = {}

In [28]:
for generate_nace_class in generated_classes:

    includes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Includes"].item()
    if pd.isna(includes):
        print("No description for class:", generate_nace_class)
        continue
    includes_also = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["IncludesAlso"].item()
    includes_also = "" if pd.isna(includes_also) else includes_also
    excludes = nace_descriptions[nace_descriptions["CODE"] == generate_nace_class]["Excludes"].item()
    excludes = "" if pd.isna(excludes) else excludes

    if few_shot: 
        gold_standard = df_gold_standard[df_gold_standard["NACE_letter"] == generate_nace_class]["Description_clean"].to_list()[:3] 
        gold_standard = [text.replace("\n", "") for text in gold_standard]
    else: 
        gold_standard = []

    subsections = get_sublevels(generate_nace_class, level=2)

    examples = []

    #if generated_data.get(generate_nace_class) is not None:
    #    if len(generated_data[generate_nace_class].get("data", [])) > 0:
    #        examples = generated_data[generate_nace_class]["data"]

    for i in tqdm(range(iterations_), desc=generate_nace_class):
        iteration_topics = topics[generate_nace_class]["output"][num_samples*i:num_samples*(i+1)]
        res = generate_synthetic_data(num_samples=num_samples, gold_standard=gold_standard, includes=includes, includes_also=includes_also, excludes=excludes, subsections=subsections, prompt_path=prompt_path, model=model, topic=iteration_topics)
        examples.append(res[1])
        data = split_synthetic_data("\n\n".join(examples), num_samples * iterations_, only_enumarated=True)
        pd.DataFrame(data, columns=[generate_nace_class]).to_csv(os.path.join(store_path, f"class_{generate_nace_class}.csv"), index=False)

        if i < 2: 
            [print(example) for example in examples]
            print(res[0].messages[1].content)

        if len(data) >= num_samples * iterations_:
            break

    results = {
        "data": data,
        "prompt": res[0],
        "system_prompt": res[0].messages[0].content,
        "user_prompt": res[0].messages[1].content,
        "output": examples, 
        "few_shot": few_shot
    }

    generated_data[generate_nace_class] = results

B:   0%|          | 0/1 [00:33<?, ?it/s]

Here are the business model descriptions:

1. As a leading coal mining company, Peabody Energy's operations span the entire value chain, from underground and surface mining of hard coal to processing and transportation. We employ advanced techniques such as cleaning, sizing, grading, pulverising, compressing, and transporting to enhance the quality and marketability of our coal products, which are primarily sold to electricity generators, industrial customers, and coke producers.

2. Arch Coal's business model is centered around the recovery of high-quality metallurgical coal from previously mined deposits through re-mining and re-processing techniques. By leveraging our expertise in culm bank management, we produce a range of specialty coals that cater to the specific needs of steel manufacturers, who value our products for their exceptional strength and durability.

3. Contura Energy's business model is built around the production of specialized coal products through advanced liquefaction methods. Our focus on quality and consistency enables us to supply high-performance coals to industrial customers, including activated carbon producers and silicon manufacturers, who rely on our products to drive their own manufacturing processes.

4. Alliance Resource Partners operates a lean and efficient underground mining operation that prioritizes cost control and productivity. By maintaining a relentless focus on low-cost production, we are able to supply high-quality thermal coal to power generators and industrial users in the eastern United States at competitive prices, while also delivering strong returns for our stakeholders.

5. As one of the world's largest hard coal mining companies, Peabody Energy extracts coal through a range of underground and surface mining methods. We then process the coal to enhance its quality and marketability before selling it to customers in the electricity generation and industrial sectors, who value our products for their reliability and consistency.

6. Coal India Limited has developed a robust business model that involves recovering hard coal from culm banks through advanced cleaning and sizing techniques. Our focus on domestic markets enables us to build strong relationships with power plants and steel producers, who rely on our high-quality coal products to drive their own operations.

7. Arch Coal Inc.'s business model is centered around the production of high-quality metallurgical coal for export to international steel manufacturers. By leveraging a network of global logistics partnerships, we are able to deliver our products to customers in a timely and efficient manner, while also ensuring that they meet the highest standards of quality and consistency.

8. Arch Coal Inc.'s operations span the entire coal value chain, from underground and surface mining to processing and transportation. We employ advanced techniques such as cleaning, sizing, grading, pulverising, compressing, and transporting to enhance the quality and marketability of our coal products, which are primarily sold to industrial customers who value their strength and durability.

9. Contura Energy's business model involves recovering high-quality metallurgical coal from culm banks through specialized equipment and processing techniques. Our focus on producing exceptional coals enables us to supply steel manufacturers with the high-performance products they need to drive their own manufacturing processes, while also delivering strong returns for our stakeholders.

10. Alpha Metallurgical Resources operates a diversified coal mining business that encompasses both underground and surface mining operations. By focusing on low-volatility coking coal production, we are able to supply domestic and international steel markets with high-quality products that meet the most stringent standards of quality and consistency.
TASK
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
Mining and quarrying include the extraction of minerals occurring naturally as solids (coal and ores), liquids (petroleum) or gases (natural gas). Extraction can be achieved by different methods such as underground or surface mining, well operation, seabed mining etc.\n\nThis section includes supplementary activities aimed at preparing the crude materials for marketing, for example, crushing, grinding, cleaning, drying, sorting, concentrating ores, liquefaction of natural gas and agglomeration of solid fuels. These operations are often accomplished by the units that extracted the resource and/or others located nearby.\n\nMining activities are classified into divisions, groups and classes on the basis of the principal mineral produced. Divisions 05, 06 are concerned with mining and quarrying of fossil fuels (coal, lignite, petroleum, gas); divisions 07, 08 concern metal ores, various minerals and quarry products. \n\nSome of the technical operations of this section, particularly related to the extraction of hydrocarbons, may also be carried out for third parties by specialised units as an industrial service which is reflected in division 09.

Excludes: This section excludes:\n- processing of the extracted materials, see section C (Manufacturing)\n- usage of the extracted materials without a further transformation for construction purposes, see section F (Construction)\n- bottling of natural spring and mineral waters at springs and wells, see 11.07\n- crushing, grinding or otherwise treating certain earths, rocks and minerals not carried on in conjunction with mining and quarrying, see 23.9

Here are some examples of descriptions of other companies:
```
- The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.
- As a global leader in optical technologies, we harness the full spectrum of light to make life better. From product idea to tangible design through to the manufacturing process, we enable our customers to create high performance optical applications for the automotive, consumer, industrial and healthcare markets. What differentiates us, is our broad technology spectrum covering the emission of light as well as its detection through sensing and intelligent processing. We serve the value chain of optical solutions with our innovative products and solutions, which are designed for best-in class performance, size, cost and energy efficiency. We are experts in the development and integration of a wide range of optical technologies, from single components through to complex systems. This enables us to be a market and innovation leader, serve our customers as trusted partners and differentiate ourselves in the marketplace.
- The company is a global engineering, property and infrastructure company that provides innovative solutions and delivers sustainable developments. We have grown to become Malaysia's leading infrastructure and property developer since our founding in 1976. Gamuda's differentiated strengths and expertise underscore our growth of nearly five decades. We believe that profitability and sustainability are not mutually exclusive. This is why Environmental, Social and Governance (ESG) have long been emphasised in Gamuda's business strategy. The Gamuda Green Plan 2025 formalised our decades-long commitment to sustainability. It outlines our overarching approach to ESG, risks and opportunities, strategic priorities and plans. We are a regional player operating in Malaysia, Vietnam, Australia, Taiwan, Singapore, United Kingdom, India, Bahrain and Qatar.
```

BUSINESS MODELS
1: Peabody Energy's business model involves underground and surface mining of hard coal, as well as cleaning, sizing, grading, pulverising, compressing, and transporting the coal to classify, improve quality, or facilitate storage for sale to electricity generators, industrial customers, and coke producers.
2: Arch Coal's business model focuses on recovering hard coal from culm banks through re-mining and re-processing of previously mined coal deposits to produce high-quality metallurgical coal for steel production and thermal coal for power generation.
3: Contura Energy's business model centers around mining and processing of hard coal through liquefaction methods, with a focus on producing specialty coals for industrial customers, such as activated carbon producers and silicon manufacturers.
4: Alliance Resource Partners' business model involves underground mining of hard coal, with an emphasis on efficient operations and cost control to supply low-cost thermal coal to power generators and industrial users in the eastern United States.
5: Peabody Energy operates as a hard coal mining company that extracts coal through underground and surface mining methods, processes it to improve quality, and sells it to customers in the electricity generation and industrial sectors.
6: Coal India Limited engages in the recovery of hard coal from culm banks, cleans and sizes the recovered coal, and markets it to domestic customers, such as power plants and steel producers.
7: Arch Coal Inc. focuses on underground mining of high-quality metallurgical coal, which is then pulverized and compressed for export to international steel manufacturers through a network of global logistics partnerships.
8: Arch Coal Inc.'s business model involves underground and surface mining of hard coal, as well as cleaning, sizing, grading, pulverising, compressing, and transporting coal to classify, improve quality, and facilitate storage for industrial customers.
9: Contura Energy's business model focuses on the recovery of hard coal from culm banks through specialized equipment and processing techniques to produce high-quality metallurgical coal for steel production.
10: Alpha Metallurgical Resources' business model encompasses both underground and surface mining of hard coal, with a focus on producing low-volatility coking coal for domestic and international steel markets.

INSTRUCTIONS
 - For each given business model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse
 - Start directly with item 1
 - Do not use line breaks in the descriptions
 - Do not add any introduction, explanation, or concluding text
 - enumarate the descriptions

In [29]:
data

["1. As a leading coal mining company, Peabody Energy's operations span the entire value chain, from underground and surface mining of hard coal to processing and transportation. We employ advanced techniques such as cleaning, sizing, grading, pulverising, compressing, and transporting to enhance the quality and marketability of our coal products, which are primarily sold to electricity generators, industrial customers, and coke producers.",
 "2. Arch Coal's business model is centered around the recovery of high-quality metallurgical coal from previously mined deposits through re-mining and re-processing techniques. By leveraging our expertise in culm bank management, we produce a range of specialty coals that cater to the specific needs of steel manufacturers, who value our products for their exceptional strength and durability.",
 "3. Contura Energy's business model is built around the production of specialized coal products through advanced liquefaction methods. Our focus on quality and consistency enables us to supply high-performance coals to industrial customers, including activated carbon producers and silicon manufacturers, who rely on our products to drive their own manufacturing processes.",
 '4. Alliance Resource Partners operates a lean and efficient underground mining operation that prioritizes cost control and productivity. By maintaining a relentless focus on low-cost production, we are able to supply high-quality thermal coal to power generators and industrial users in the eastern United States at competitive prices, while also delivering strong returns for our stakeholders.',
 "5. As one of the world's largest hard coal mining companies, Peabody Energy extracts coal through a range of underground and surface mining methods. We then process the coal to enhance its quality and marketability before selling it to customers in the electricity generation and industrial sectors, who value our products for their reliability and consistency.",
 '6. Coal India Limited has developed a robust business model that involves recovering hard coal from culm banks through advanced cleaning and sizing techniques. Our focus on domestic markets enables us to build strong relationships with power plants and steel producers, who rely on our high-quality coal products to drive their own operations.',
 "7. Arch Coal Inc.'s business model is centered around the production of high-quality metallurgical coal for export to international steel manufacturers. By leveraging a network of global logistics partnerships, we are able to deliver our products to customers in a timely and efficient manner, while also ensuring that they meet the highest standards of quality and consistency.",
 "8. Arch Coal Inc.'s operations span the entire coal value chain, from underground and surface mining to processing and transportation. We employ advanced techniques such as cleaning, sizing, grading, pulverising, compressing, and transporting to enhance the quality and marketability of our coal products, which are primarily sold to industrial customers who value their strength and durability.",
 "9. Contura Energy's business model involves recovering high-quality metallurgical coal from culm banks through specialized equipment and processing techniques. Our focus on producing exceptional coals enables us to supply steel manufacturers with the high-performance products they need to drive their own manufacturing processes, while also delivering strong returns for our stakeholders.",
 '10. Alpha Metallurgical Resources operates a diversified coal mining business that encompasses both underground and surface mining operations. By focusing on low-volatility coking coal production, we are able to supply domestic and international steel markets with high-quality products that meet the most stringent standards of quality and consistency.']

In [59]:
topics[generate_nace_class]["output"]

['CoalTech Inc. operates an underground hard coal mining business model that integrates cleaning, sizing, and grading processes to improve the quality of extracted coal for transportation and storage.',
 'CarbonCorp focuses on surface mining of hard coal using advanced liquefaction methods, enabling efficient extraction and processing for industrial clients.',
 'CoalRevival specializes in recovering hard coal from culm banks, utilizing innovative technologies to classify, compress, and market reclaimed coal as a supplementary energy source.',
 'EnergyPit Ltd. employs a combined underground and surface mining approach to extract hard coal, offering pulverizing services to facilitate transportation and meet customer requirements.',
 'BlackRock Mining Inc. develops and operates its own coal mines, while also providing contract mining services for other companies, including cleaning, grading, and compressing coal to enhance quality and market value.',
 "Arch Coal's business model involves surface and underground mining of hard coal, as well as cleaning, sizing, and grading to produce high-quality coal for industrial customers, while also recovering coal from culm banks to maximize resource utilization.",
 "Contura Energy's business model involves surface and underground mining of hard coal, followed by cleaning, sizing, and grading to improve quality, before selling the coal to utility companies and industrial customers for electricity generation and steel production.",
 "Arch Resources' business model focuses on underground mining of high-quality metallurgical coal, which is then pulverized and compressed for transportation to steel mills and other industrial customers, generating revenue through long-term supply contracts.",
 "Peabody Energy's business model encompasses surface mining of hard coal, recovery from culm banks, and processing to improve quality, before selling the coal to power generators and industrial users, with a focus on cost reduction and operational efficiency."]

In [33]:
topics[generate_nace_class]["topics_df"]#[num_samples*i:num_samples*(i+1)]

In [ ]:
# print prompts
for k,v in generated_data.items(): 
    print(k,len(v["output"]), "_______"*20)
    for k in v["output"]: 
        print(k)
        print("_")

C 25 ____________________________________________________________________________________________________________________________________________
1. Our company is at the forefront of innovation in the recreational vehicle sector, specializing in the design and production of collapsible trailers that redefine convenience for outdoor enthusiasts. These trailers are engineered for easy storage and transport, allowing users to maximize their adventures without the hassle of cumbersome equipment. By focusing on lightweight materials and smart engineering, we ensure that our products not only meet the demands of the modern adventurer but also enhance the overall experience of outdoor travel. Our commitment to quality and functionality has positioned us as a preferred choice among recreational vehicle users who value both practicality and design.

2. As a dedicated manufacturer of specialized equipment tailored for off-road vehicles, we cater to the growing adventure tourism market. Our products are meticulously crafted to withstand the rigors of challenging terrains while providing unmatched performance and reliability. By collaborating closely with adventure tourism companies, we continuously refine our offerings to meet their specific needs, ensuring that our equipment enhances their operational efficiency and safety. Our focus on innovation and durability has established us as a trusted partner in the adventure tourism industry, where the right equipment can make all the difference.

3. At the heart of our woodworking company is a commitment to sustainability and environmental stewardship. We specialize in producing eco-friendly wood finishes and treatments that appeal to consumers who prioritize responsible sourcing and minimal environmental impact. Our formulations are designed to enhance the natural beauty of wood while providing long-lasting protection, ensuring that our customers can enjoy their spaces with peace of mind. By leveraging sustainable practices and materials, we not only contribute to a healthier planet but also empower our customers to make environmentally conscious choices in their homes and businesses.

4. We are revolutionizing the logistics industry with our line of modular cargo ships, designed for versatility and efficiency. These ships can be easily reconfigured to accommodate varying shipping needs, allowing logistics companies to optimize their operations and reduce costs. Our innovative approach to maritime design enables seamless transitions between different cargo types, enhancing both speed and flexibility in shipping operations. As global trade continues to evolve, our commitment to adaptability and efficiency positions us as a leader in the maritime logistics sector.

5. Our company provides mobile conveyor systems that are transforming material handling for construction firms across various job sites. These rental systems are designed for quick setup and portability, allowing contractors to streamline their operations and improve productivity. By focusing on user-friendly designs and robust performance, we empower our clients to handle materials efficiently, regardless of the project scale. Our dedication to innovation in construction logistics ensures that we remain a valuable partner in the industry, helping businesses achieve their goals with ease.

6. As a manufacturer of ceramic insulators for the electrical industry, we leverage cutting-edge materials science to enhance both performance and safety in electrical applications. Our products are engineered to withstand extreme conditions while providing reliable insulation, making them essential components in various electrical systems. By investing in research and development, we continuously improve our offerings, ensuring that they meet the highest industry standards. Our commitment to quality and innovation has solidified our reputation as a trusted supplier in the electrical sector.

7. We specialize in the development of advanced polymer-based materials tailored for medical applications, prioritizing biocompatibility and compliance with stringent regulatory standards. Our innovative materials are designed to enhance patient safety and comfort, making them ideal for a range of medical devices and applications. By collaborating with healthcare professionals and regulatory bodies, we ensure that our products not only meet but exceed industry expectations. Our focus on quality and innovation positions us as a leader in the medical materials sector, dedicated to improving patient outcomes through superior technology.

8. Our company is dedicated to the extraction and purification of ethane from natural gas liquids, supplying this critical resource to the petrochemical industry for plastic production. By employing state-of-the-art technologies and processes, we ensure the highest purity levels, which are essential for the production of high-quality plastics. Our commitment to operational excellence and sustainability allows us to meet the growing demand for ethane while minimizing environmental impact. As a key player in the petrochemical supply chain, we are positioned to support the industry's evolving needs.

9. At our tobacco-processing plant, we utilize innovative fermentation techniques to enhance the flavor profiles of premium tobacco products. Our focus on quality and craftsmanship ensures that each batch meets the highest standards, appealing to discerning consumers who appreciate rich and complex flavors. By continuously refining our processes and sourcing the finest raw materials, we create products that stand out in a competitive market. Our dedication to innovation in flavor enhancement positions us as a leader in the premium tobacco segment.

10. We provide a cutting-edge digital catalog printing service that enables retailers to produce both online and printed versions of their product catalogs simultaneously. This dual approach not only streamlines the marketing process but also enhances customer engagement by providing a cohesive shopping experience. Our technology allows for real-time updates and customization, ensuring that retailers can showcase their latest offerings effectively. By integrating digital and print solutions, we empower our clients to reach their audiences more efficiently and effectively.

11. Our company specializes in the production of essential oils and natural fragrances derived from organic plant materials, catering to the cosmetics and personal care industries. We are committed to sourcing high-quality botanicals and employing sustainable extraction methods to create products that resonate with consumers seeking authenticity and purity. Our extensive portfolio of fragrances not only enhances product formulations but also aligns with the growing demand for natural and eco-friendly options. By focusing on quality and sustainability, we position ourselves as a trusted partner for brands looking to elevate their offerings.

12. We design and implement automated systems for the textile industry, focusing on reducing labor intensity while significantly increasing production rates. Our innovative solutions streamline manufacturing processes, allowing textile producers to enhance efficiency and reduce operational costs. By integrating advanced technology with industry expertise, we empower our clients to adapt to changing market demands and improve their competitiveness. Our commitment to innovation in textile automation positions us as a key player in the evolution of the industry.

13. As an established electronics firm, we produce smart home devices that seamlessly integrate with existing home networks, enhancing convenience and security for users. Our subscription service provides ongoing software updates and new features, ensuring that our customers always have access to the latest innovations. By focusing on user-friendly designs and robust functionality, we create products that not only simplify daily life but also contribute to a smarter, more connected home environment. Our dedication to quality and customer satisfaction drives our continued success in the smart home market.

14. Our luxury brand is pioneering the integration of biodegradable leather substitutes into our collections, appealing to environmentally conscious consumers who value sustainability without compromising on style. By sourcing innovative materials that mimic the look and feel of traditional leather, we create products that resonate with a modern ethos of responsible consumption. Our commitment to ethical fashion positions us as a leader in the luxury market, where consumers increasingly seek out brands that reflect their values.

15. We are a marine electronics manufacturer focused on designing smart navigation systems that enhance safety for boaters by integrating real-time weather and traffic data. Our cutting-edge technology provides users with critical information at their fingertips, allowing for informed decision-making on the water. By prioritizing user experience and reliability, we empower boaters to navigate with confidence, regardless of conditions. Our dedication to innovation in marine technology positions us as a trusted partner for both recreational and commercial boating communities.

16. As a manufacturer of plastic counter displays, we help brands effectively showcase their products in retail environments. Our designs are tailored to enhance visibility and engagement, ensuring that products stand out to consumers. By focusing on quality materials and innovative designs, we provide our clients with solutions that drive sales and elevate their brand presence. Our commitment to customer satisfaction and creativity positions us as a preferred partner for retailers looking to optimize their merchandising strategies.

17. Our wood products company specializes in offering customizable wooden signage for businesses, merging craftsmanship with branding to create unique visual identities. Each piece is meticulously crafted to reflect the essence of our clients' brands, ensuring that their message resonates with customers. By emphasizing quality and personalization, we empower businesses to make a lasting impression in their markets. Our dedication to artistry and customer collaboration positions us as a leader in the custom signage industry.

18. We are dedicated to creating a range of wooden toys made from natural materials, emphasizing safety and educational value for children. Our products are designed to inspire creativity and learning while adhering to the highest safety standards. By sourcing sustainable wood and employing eco-friendly practices, we ensure that our toys are not only fun but also contribute to a healthier planet. Our commitment to quality and education positions us as a trusted choice for parents seeking enriching play experiences for their children.

19. Our automotive technology firm is at the forefront of developing advanced driver-assistance systems (ADAS) for new vehicle manufacturers. By focusing on innovation and safety, we create solutions that enhance the driving experience while reducing risks on the road. Our systems integrate seamlessly with existing vehicle architectures, providing manufacturers with the tools they need to meet evolving safety standards and consumer expectations. Our commitment to excellence and technological advancement positions us as a leader in automotive safety technology.

20. We specialize in creating innovative chemical formulations for personal protective equipment, enhancing both safety and comfort for users. Our products are designed to meet the rigorous demands of various industries while ensuring that wearers can perform their tasks with confidence. By focusing on research and development, we continuously improve our formulations to address emerging safety challenges. Our dedication to quality and innovation positions us as a trusted partner in the field of personal protective equipment.
_
1. Our company is at the forefront of energy-efficient lighting solutions, specializing in the production of innovative light bulbs designed for the environmentally conscious consumer. By utilizing a direct-to-consumer sales strategy, we eliminate traditional retail overhead, allowing us to offer competitive pricing while maintaining high-quality standards. Our online platform not only streamlines the purchasing process but also fosters a direct relationship with our customers, enabling us to gather valuable feedback and continuously improve our product offerings. As we expand our product line, we remain committed to sustainability, ensuring that our bulbs consume less energy and have a longer lifespan, contributing positively to both consumer savings and environmental impact.

2. As a socially responsible brewery, we blend our passion for craft beer with a commitment to community engagement. A portion of our profits is dedicated to supporting local charities, creating a unique value proposition that resonates with our customers. This cause-driven approach not only enhances our brand loyalty but also encourages patrons to feel a sense of connection with our mission. Through community events and collaborative initiatives, we engage our customers in meaningful ways, fostering a culture of giving back while delivering high-quality brews that reflect our dedication to both craftsmanship and social impact.

3. Our company has revolutionized the construction tool market by designing multifunctional tools that adapt seamlessly to various tasks. This innovative approach reduces the need for extensive toolkits, making it easier for both professionals and DIY enthusiasts to tackle projects efficiently. Each tool is engineered for versatility, allowing users to switch between functions with ease, thus saving time and space. We are dedicated to continuous improvement, incorporating user feedback into our design process to ensure that our products not only meet but exceed the expectations of our diverse customer base.

4. We pride ourselves on being a leader in sustainable lumber production, sourcing our timber exclusively from certified forests that adhere to the highest environmental standards. Our commitment to eco-conscious practices resonates with builders and architects who prioritize sustainability in their projects. By offering a range of high-quality lumber products, we enable our clients to create beautiful, durable structures while minimizing their ecological footprint. Our partnerships with environmental organizations further reinforce our dedication to responsible forestry, ensuring that we contribute positively to the planet's health.

5. As a premier manufacturer of active pharmaceutical ingredients (APIs), we focus on delivering high-quality materials to leading drug companies worldwide. Our rigorous adherence to international quality standards ensures that our products meet the stringent requirements of the pharmaceutical industry. With a state-of-the-art facility and a team of experienced professionals, we are committed to innovation and excellence in every batch we produce. By fostering strong relationships with our clients, we not only provide reliable supply but also collaborate on developing tailored solutions that address their specific needs.

6. In a groundbreaking joint venture, we are collaborating with renewable energy firms to create hybrid systems that integrate solar and wind energy into traditional refining processes. This innovative approach not only enhances energy efficiency but also significantly reduces the carbon footprint associated with refining operations. By leveraging cutting-edge technology and shared expertise, we are paving the way for a more sustainable future in energy production. Our commitment to environmental stewardship drives us to explore new avenues for integrating renewable resources into our operations, ensuring long-term viability and compliance with evolving industry standards.

7. Our variable data printing service specializes in creating personalized marketing materials that resonate with individual customers. By harnessing the power of data analytics, we enable businesses to tailor their messaging, ensuring that each piece of communication is relevant and impactful. This approach not only enhances customer engagement but also drives conversion rates, making marketing efforts more effective. With a focus on innovation and quality, we continuously refine our printing techniques to deliver exceptional results that meet the dynamic needs of our clients.

8. Our subscription service offers urban dwellers the flexibility to swap vehicles on a monthly basis, catering to the evolving needs of city living. By providing access to a range of vehicles, we empower our members to choose the right car for their lifestyle, whether it's a compact for daily commutes or a spacious SUV for weekend getaways. This model not only promotes convenience but also encourages sustainable transportation choices, as members can select electric or hybrid options. Our seamless app experience ensures that vehicle selection and management are hassle-free, enhancing the overall user experience.

9. At our ceramics company, we collaborate closely with chefs to design custom dishware that elevates restaurant branding and presentation. By understanding the unique vision of each culinary artist, we create bespoke pieces that reflect their style and enhance the dining experience. Our commitment to quality craftsmanship ensures that every item not only looks stunning but also withstands the rigors of a busy kitchen. This partnership approach allows us to innovate continuously, pushing the boundaries of traditional ceramics to meet the specific needs of the food service industry.

10. We specialize in producing metal storage solutions that optimize warehouse space and enhance operational efficiency. Our customizable shelving systems are designed to adapt to various storage needs, allowing businesses to maximize their available square footage. By focusing on durability and functionality, we provide products that withstand the demands of a fast-paced environment while maintaining an organized workspace. Our commitment to customer satisfaction drives us to offer tailored solutions that meet the unique challenges faced by our clients in managing their inventory.

11. Our firm is dedicated to producing high-quality metal components specifically designed for renewable energy systems, with a focus on wind and solar power installations. By leveraging advanced manufacturing techniques, we ensure that our products meet the rigorous standards required for sustainable energy solutions. Our commitment to innovation drives us to continuously improve our processes, enhancing efficiency and reducing waste. As the demand for clean energy grows, we are proud to play a vital role in supporting the transition to a greener future.

12. As a leading chemical producer, we develop high-performance coatings tailored for the automotive industry, enhancing the durability and aesthetic appeal of vehicles. Our innovative formulations are designed to withstand harsh environmental conditions while providing a sleek finish that meets the demands of modern consumers. By investing in research and development, we stay ahead of industry trends, ensuring that our products not only meet but exceed the expectations of our clients. Our commitment to quality and performance drives our success in a competitive marketplace.


In [ ]:
# print prompts
for k,v in generated_data.items(): 
    print(k,"_______"*20)
    print(v["user_prompt"])

A ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats.



Here are some examples of descriptions of these classes:
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODEL
20. A firm specializing in the production of biodegradable packaging from agricultural waste, targeting eco-conscious brands and businesses.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse
C ____________________________________________________________________________________________________________________________________________

TASK
You get a short description of a companies' busines model and rephrase it such that it fits into a typical description within an annual report.

DEFINITION
This section includes the physical or chemical transformation of materials, substances, or components into new products, although this cannot be used as the single universal criterion for defining manufacturing (see remark on processing of waste below). The materials, substances, or components transformed are raw materials that are products of agriculture, forestry, fishing, mining or quarrying as well as products of other manufacturing activities. Substantial alteration, renovation or reconstruction of goods is generally considered to be manufacturing.\n\nThe output of a manufacturing process may be finished in the sense that it is ready for utilisation or consumption, or it may be semi-finished in the sense that it is to become an input for further manufacturing. For example, the output of alumina refining is the input used in the primary production of aluminium; primary aluminium is the input to aluminium wire drawing; and aluminium wire is the input for the manufacture of fabricated wire products.\n\nManufacture of specialised components and parts of, and accessories and attachments to, machinery and equipment is, as a general rule, classified in the same class as the manufacture of the machinery and equipment for which the parts and accessories are intended. Manufacture of unspecialised components and parts of machinery and equipment, e.g. engines, pistons, electric motors, electrical assemblies, valves, gears, roller bearings, is classified in the appropriate class of manufacturing, without regard to the machinery and equipment in which these items may be included. However, making specialised components and accessories by moulding or extruding plastics materials is included in group 22.2.\n\nAssembly of the component parts of manufactured products is considered manufacturing. This includes the assembly of manufactured products from either self-produced or purchased components. \n\nThe recovery of waste, i.e. the processing of waste into secondary raw materials is classified in group 38.3 (Materials recovery). While this may involve physical or chemical transformations, this is not considered to be a part of manufacturing. The primary purpose of these activities is considered to be the treatment or processing of waste and they are therefore classified in Section E (Water supply; sewerage, waste management and remediation activities). However, the manufacture of new final products (as opposed to secondary raw materials) is classified in manufacturing, even if these processes use waste as an input. For example, the production of silver from film waste is considered to be a manufacturing process.\n\nSpecialised maintenance and repair of industrial, commercial and similar machinery and equipment is, in general, classified in division 33 (Repair, maintenance and installation of machinery and equipment). However, the repair of computers and personal and household goods is classified in division 95 (Repair of computers and personal and household goods), while the repair of motor vehicles is classified in division 45 (Wholesale and retail trade and repair of motor vehicles and motorcycles). \n\nThe installation of machinery and equipment, when carried out as a specialised activity, is classified in 33.20. \n\nRemark: The boundaries of manufacturing and the other sectors of the classification system can be somewhat blurry. As a general rule, the activities in the manufacturing section involve the transformation of materials into new products. Their output is a new product. However, the definition of what constitutes a new product can be somewhat subjective. As clarification, the following activities are considered manufacturing in NACE:\n- fresh fish processing (oyster shucking, fish filleting), not done on a fishing boat (see 10.20)\n- milk pasteurising and bottling (see 10.51)\n- leather converting (see 15.11)\n- wood preserving (see 16.10)\n- printing and related activities (see 18.1)\n- tyre retreading (see 22.11)\n- ready-mixed concrete production (see 23.63)\n- electroplating, plating, and metal heat treating (see 25.61)\n- rebuilding or remanufacture of machinery (e.g. automobile engines, see 29.10)\n\nConversely, there are activities that, although sometimes involving transformation processes, are classified in other sections of NACE; in other words, they are not classified as manufacturing. They include:\n- logging, classified in section A (Agriculture, forestry and fishing);\n- beneficiating of agricultural products, classified in section A (Agriculture, forestry and fishing); \n- preparation of food for immediate consumption on the premises is classified to division 56 (Food and beverage service activities);\n- beneficiating of ores and other minerals, classified in section B (Mining and quarrying); \n- construction of structures and fabricating operations performed at the site of construction, classified in section F (Construction);\n- activities of breaking bulk and redistribution in smaller lots, including packaging, repackaging, or bottling products, such as liquors or chemicals; sorting of scrap; mixing paints to customer order; and cutting metals to customer order; treatment not resulting into a different good is classified to section G (Wholesale and retail trade; repair of motor vehicles and motorcycles).



Here are some examples of descriptions of these classes:
```
Example 1:
We are a development stage biopharmaceutical company focused on discovering and developing novel and distinctive small molecule therapeutics that modulate G protein-coupled receptors, or GPCR, pathways. We are designing proprietary novel small molecule therapeutic candidates with the intent of developing best/first in class therapeutics for the treatment of metabolic, inflammatory and fibrotic diseases with significant unmet medical needs, using our integrated drug discovery platform, medicinal chemistry expertise and deep understanding of the GPCR biology.Our pipeline is currently made up of three development programs. The candidate we selected for clinical development, LMNL6511, a selective antagonist for the GPR84 receptor, is expected to commence a Phase 1 clinical trial in the second half of 2023. We are also developing potential OXER1 antagonists and GPR40 agonists, both of which are at the preclinical stage. In addition to these priority development programs, we continue to explore other development opportunities to add to our pipeline.We believe that our drug discovery platform and deep understanding of GPCRs allows us to identify small molecule candidates that can accurately target GPCRs where other drug discovery approaches have been unsuccessful. Our drug discovery platform leverages a fully integrated chemistry and biology expertise supported by our broad in vivo capabilities, which allows us to investigate our preclinical drug candidates' efficacy in a wide variety of animal models and enables us to develop small molecule therapeutic candidates for the treatment of various metabolic, inflammatory and fibrotic diseases. We aim to develop best or first-in-class therapies targeting indications with significant unmet needs, where a novel small molecule approach may be better suited using our drug discovery platform, specialized know-how and data-driven development plans.We are led by a strong, experienced team with proven track records in the discovery, development, and approval of biopharmaceuticals. Our team's extensive experience in clinical development, and regulatory success is backed by our data driven philosophy.

Example 2:
The company Biologics is a biopharma company focused on developing and commercializing innovative gene therapies for retinal neurodegenerative diseases and central nervous system disorders. The company is currently concentrating its efforts and resources on securing the upcoming LUMEVOQ validation campaign with its manufacturing partner in the US. Additionally, GenSight is discussing a financing bridge with certain existing shareholders to extend its cash runway beyond the results of the validation campaign expected in Q3 2023.

Example 3:
As a global leader in optical technologies, we harness the full spectrum of light to make life better. From product idea to tangible design through to the manufacturing process, we enable our customers to create high performance optical applications for the automotive, consumer, industrial and healthcare markets. What differentiates us, is our broad technology spectrum covering the emission of light as well as its detection through sensing and intelligent processing. We serve the value chain of optical solutions with our innovative products and solutions, which are designed for best-in class performance, size, cost and energy efficiency.We are experts in the development and integration of a wide range of optical technologies, from single components through to complex systems. This enables us to be a market and innovation leader, serve our customers as trusted partners and differentiate ourselves in the marketplace.
```

BUSINESS MODEL
20. **Manufacture of jewellery and related articles:** An artisan jeweller creating bespoke pieces using ethically sourced gemstones, targeting consumers interested in unique and sustainable jewellery.

INSTRUCTIONS
 - Create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also include terms other than those used in the sector definition to make the examples more diverse

#### Aggregate data and split

In [ ]:
# config

config = {
    "prompts": {k: v.get("user_prompt") for k, v in generated_data.items()}, 
    #"samples": num_samples * iterations_,
    #"generated_iterations": iterations_,
    "level": level,
    "head_nace_code": head_nace_code,
    "system_prompt": get_system_prompt(prompt_path), 
    "few_shot_prompting": few_shot
}

# store
import json
with open(os.path.join(store_path, "config.json"), "w") as f: 
    json.dump(config, f, indent=4)

In [ ]:
df_full = []
for k, v in generated_data.items(): 
    df_temp = pd.DataFrame(v["data"], columns=["text"])
    df_temp["label"] = k
    df_full.append(df_temp)
df_full = pd.concat(df_full, axis=0)
df_full = df_full.reset_index(drop=True)
df_full

                                                  text label
0    1. Our company is at the forefront of innovati...     C
1    2. As a dedicated manufacturer of specialized ...     C
2    3. At the heart of our woodworking company is ...     C
3    4. We are revolutionizing the logistics indust...     C
4    5. Our company provides mobile conveyor system...     C
..                                                 ...   ...
995  16. We offer a fishing gear rental service tha...     A
996  17. Our woodworking school teaches students th...     A
997  18. Operating as a regenerative agriculture fa...     A
998  19. Our fishing tourism venture offers guided ...     A
999  20. We have developed a subscription model for...     A

[1000 rows x 2 columns]

In [2]:
import re
clean_text = lambda x: re.sub(r'^\d+\.\s*', " ", x).strip()

In [34]:
# add the missing C to the rest!
path_with_c = "data/synthetic_data/two_step/data_20260114__level_1__subclasses_None__prompts_5_list_hardcoded_few_shot__few_shot__from_lvl_4_topics__gpt-4o-mini/class_C.csv"
path_original = "data/synthetic_data/two_step/_data_20260114__level_1__subclasses_None__prompts_5_list_hardcoded_few_shot__few_shot__from_lvl_4_topics__gpt-4o-mini/synthetic_data_full.csv"

In [35]:
with_c = pd.read_csv(path_with_c, sep=",")
with_c["label"] = "C"
with_c = with_c.rename(columns={"C": "text"})
with_c

                                                  text label
0    1: Our cooperative farming initiative empowers...     C
1    2: As a pioneering agritech startup, we levera...     C
2    3: Our subscription-based service connects con...     C
3    4: We are at the forefront of a vertical farmi...     C
4    5: Our vertically integrated rice company comb...     C
..                                                 ...   ...
995  16: As a global manufacturer of decorative flo...     C
996  17: Our mobile welding repair service speciali...     C
997  18: We operate a full-service repair shop for ...     C
998  19: Our maintenance company focuses on the rep...     C
999  20: We operate a firearms repair business that...     C

[1000 rows x 2 columns]

In [36]:
df_full_original = pd.read_csv(path_original, sep=",")
df_full_original["label"].value_counts()

label
F    940
A    920
B    710
J    640
C     60
Name: count, dtype: int64

In [40]:
df_full_original = df_full_original[df_full_original["label"] != "C"]

In [41]:
df_full_original = pd.concat([df_full_original, with_c], axis=0)

In [45]:
df_full = df_full_original

In [46]:
df_full["text"] = df_full["text"].apply(clean_text)

In [48]:
store_path = "data/synthetic_data/two_step/_data_20260114__level_1__subclasses_None__prompts_5_list_hardcoded_few_shot__few_shot__from_lvl_4_topics__gpt-4o-mini/"

In [49]:
df_full.to_csv(os.path.join(store_path, "synthetic_data_full.csv"), index=False)

In [50]:
# make train test split 6:2:2

from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(df_full, test_size=0.4, random_state=42, stratify=df_full["label"])
test_df, val_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df["label"])

len(train_df), len(test_df), len(val_df)

(2526, 842, 842)

In [51]:
train_df.to_csv(os.path.join(store_path, "train_data.csv"), index=False)
test_df.to_csv(os.path.join(store_path, "test_data.csv"), index=False)
val_df.to_csv(os.path.join(store_path, "val_data.csv"), index=False)

In [47]:
model = "llama3.1:70b"
llm = ChatOllama(
    model=model,
    temperature=0.9, 
    base_url="http://10.80.20.101:11434/"
)

In [13]:
a =llm.invoke("""TASK 
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats. 



Here are some examples of descriptions of these classes: 
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODELS
0: A tech platform connects local wood suppliers with artisans looking for raw materials, streamlining the procurement process.
1: A company that offers consulting services to help landowners manage their forests for both timber and non-timber product extraction.
2: An organic dairy farm producing artisanal cheeses and yogurts, paired with a farm-to-table café on-site.
3: A cooperative that aggregates products from various mixed farms to sell under a single organic brand.
4: A sustainable sea cucumber farm that caters to niche markets in Asian health and culinary sectors.
5: An eco-friendly farm that integrates permaculture principles, offering educational courses and a variety of organic seasonal produce.

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse""")

ConnectTimeout: [Errno 60] Operation timed out

In [ ]:
print(a.content)

NameError: name 'a' is not defined

In [280]:
b = llm.invoke("""TASK 
You get list of short descriptions of a companies' business models. Use these descriptions to formulate it into a typical description within an annual report.

DEFINITION
This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops, raising and breeding of animals, harvesting of timber and other plants, animals or animal products from a farm or their natural habitats. 



Here are some examples of descriptions of these classes: 
```
Example 1:
The company, together with its subsidiaries, operates as one of the largest vertically integrated agricultural groups in Ukraine, engaging in the production, storage, processing, and sale of agricultural products. The company's key activities include breeding pigs, processing pork, and producing wheat and sunflower. The Group focuses on three winter crops and two summer crops, maintaining a crop ratio of 60% winter crops (wheat, barley, rapeseed) and 40% summer crops (sunflower, corn). This strategy is designed to ensure a steady supply of basic food products, which remain in high demand, especially during wartime. The Group has also secured additional financing to cover key production costs and maintain strategic reserves of essential supplies.

Example 2:
The company initially focused on the business activities of catching skipjack and red snapper with a target of export sales. Over time, in 1983, the Company started its first production operations which was marked by the establishment of its factory in Kendari, Southeast Sulawesi.Furthermore, in order to expand its market share, the Company expanded into the integrated fish processing industry which includes processing activities. Since then, the Company has been able to produce processed marine products that contain high protein and added value, such as fish filets, tuna, octopus, squid, and other value-added products.In managing its business, the Company is committed to always consider sustainability values in all aspects. Not merely focusing on financial performance, the Company also promotes business alignment and harmonization as well as provides optimal benefits to stakeholders. The Company believes that by establishing a mutually beneficial business ecosystem, long-term business continuity will be maintained.

Example 3:
The company is the global leader in the full cycle breeding, production and sale of Yellowtail Kingfish and is renowned world-wide for its exceptionally high quality fish. Our company is recognised for innovation and its high degree of expertise in the farming of Yellowtail Kingfish. We are the largest producer of aquaculture Yellowtail Kingfish outside of Japan. Our diverse customer base has long appreciated the consistently high quality of our fish and our reliability in supplying our fresh and frozen range to markets all over the world 52 weeks of the year.
```

BUSINESS MODELS
0: A tech platform connects local wood suppliers with artisans looking for raw materials, streamlining the procurement process.
1: A company that offers consulting services to help landowners manage their forests for both timber and non-timber product extraction.
2: An organic dairy farm producing artisanal cheeses and yogurts, paired with a farm-to-table café on-site.
3: A cooperative that aggregates products from various mixed farms to sell under a single organic brand.
4: A sustainable sea cucumber farm that caters to niche markets in Asian health and culinary sectors.
5: An eco-friendly farm that integrates permaculture principles, offering educational courses and a variety of organic seasonal produce.
6: A mixed operation that incorporates agro-tourism, allowing visitors to experience crop harvesting while selling farm products on-site.
7: A forestry management consultancy that assists landowners in optimizing timber yield while maintaining ecological health in their forests.
8: A boutique retail shop that curates and sells handcrafted goods made from roundwood and wild forest products.
9: An organic vineyard that not only produces wine but also operates a farm-to-glass restaurant, providing farm tours and tastings.
10: A timber construction company specializing in homes built from locally sourced roundwood, emphasizing energy efficiency.
11: A community-supported fishery (CSF) that offers subscription boxes of seasonal, wild-caught fish directly from local fishermen to households.
12: A multi-generational family business that has been producing firewood and charcoal using traditional methods for decades.
13: A farm specializing in heirloom vegetables, providing seed shares to local gardeners and running seasonal pop-up markets.
14: A mixed farming operation that grows vegetables alongside specialty mushrooms, supplying local chefs with unique ingredients.
15: An online marketplace for niche forest products, connecting small producers of non-timber goods with a broader audience.
16: A permaculture farm that integrates tree crops, vegetables, and livestock to create a self-sustaining ecosystem.
17: An agribusiness that raises goats for milk and cheese production, selling to local markets and hosting farm visits for educational purposes.
18: A specialty farm that produces organic spices and herbs, targeting gourmet chefs and health food stores with unique offerings.
19: A cooperative that brings together mushroom growers and crop farmers to enhance biodiversity and offer unique farm products.

INSTRUCTIONS
 - For each given Business Model, create a business model description that is in a similar format as the examples
 - Do NOT exactly copy phrases, sentence patterns, or structure from the examples
 - Think of the examples as constraints, not templates
 - Also use terms other than those used in the sector definition to make the examples more diverse""")

In [281]:
print(b.content)

### Business Model Descriptions

**Business Model 0:**
The company operates a cutting-edge digital platform that serves as a bridge between local timber suppliers and artisans in need of raw materials. By streamlining the procurement process, the platform enhances efficiency and fosters direct connections among stakeholders, ensuring that artisans can access quality wood sustainably sourced from nearby regions. This innovative approach not only supports local economies but promotes responsible forestry practices.

**Business Model 1:**
This organization specializes in providing expert consulting services to landowners, focusing on sustainable forest management practices. The firm aids clients in maximizing both timber and non-timber product yields, while prioritizing ecological preservation. Through tailored management plans and ongoing support, the company empowers landowners to achieve economic benefits alongside environmental stewardship.

**Business Model 2:**
Located on a picturesque organic dairy farm, the company is dedicated to crafting artisanal cheeses and yogurts from high-quality milk. Complementing its production facilities is a charming farm-to-table café that highlights the farm's offerings, allowing visitors to savor fresh dairy products. This dual approach not only serves the community with delicious food but also educates consumers about sustainable agricultural practices.

**Business Model 3:**
Operating as a cooperative, this entity aggregates diverse products from a network of small mixed farms to market them under a unified organic brand. By bringing together various producers, the cooperative enhances visibility and accessibility of organic goods, catering to consumers who seek quality and sustainability in their food choices. This collective model fosters collaboration and strengthens the local agricultural community.

**Business Model 4:**
The company runs a sustainable sea cucumber farm, catering to niche markets in the health and culinary sectors across Asia. By adhering to environmentally friendly farming practices, the business not only provides a premium product but also contributes to the preservation of marine ecosystems. This focus on quality and sustainability positions the company as a leader in the specialty seafood market.

**Business Model 5:**
This eco-friendly farm embraces permaculture principles, creating a self-sustaining ecosystem that flourishes with organic seasonal produce. In addition to cultivation, the farm offers hands-on educational courses, empowering individuals to learn sustainable farming techniques. By integrating agriculture with education, the farm promotes a holistic approach to food production and environmental stewardship.

**Business Model 6:**
This innovative mixed farming operation combines traditional agriculture with agro-tourism, inviting visitors to participate in the crop harvesting experience. On-site, the farm sells its fresh produce directly to consumers, fostering a connection between people and the land. The immersive nature of the experience enhances community engagement while generating additional revenue streams for the business.

**Business Model 7:**
The company operates a forestry management consultancy, dedicated to assisting landowners in optimizing timber production while ensuring ecological integrity. With a focus on sustainable practices, the consultancy provides strategic insights and management solutions that enhance forest health and productivity. This balanced approach supports both economic viability and environmental care.

**Business Model 8:**
With a focus on artisan craftsmanship, this boutique retail shop curates a selection of handcrafted goods made from locally sourced roundwood and wild forest products. By showcasing the talents of local artisans, the shop serves as a platform for unique products while promoting the sustainable use of natural resources. This commitment to quality and locality resonates with environmentally conscious consumers.

**Business Model 9:**
This organic vineyard is dedicated to the craft of winemaking, producing a range of exceptional wines that reflect the terroir of its land. Additionally, the vineyard features a farm-to-glass restaurant, where guests can enjoy meals paired with wines from the estate. Offering farm tours and tastings, the business provides an immersive experience that connects visitors to the winemaking process and the natural environment.

**Business Model 10:**
Specializing in timber construction, the company builds energy-efficient homes using locally sourced roundwood. This commitment to sustainable building practices not only enhances the quality and durability of the homes but also supports local forestry initiatives. The company’s focus on environmentally friendly design aligns with the growing consumer demand for sustainable housing solutions.

**Business Model 11:**
Operating a community-supported fishery (CSF), the company provides subscription boxes of seasonal, wild-caught fish directly from local fishermen to households. This model fosters a direct connection between consumers and their food sources, promoting sustainable fishing practices while ensuring fresh, high-quality seafood. The CSF approach builds a community around shared values of sustainability and support for local fishers.

**Business Model 12:**
This multi-generational family business has been producing firewood and charcoal through traditional methods for decades. With a strong commitment to quality and craftsmanship, the company not only meets local demand but also champions sustainable practices in biomass production. The enduring legacy of the family business reinforces its reputation within the community.

**Business Model 13:**
Specializing in heirloom vegetables, this farm offers seed shares to local gardeners and actively participates in seasonal pop-up markets. By promoting biodiversity and encouraging community gardening, the farm not only enriches local food systems but also fosters a connection to heritage crops. This focus on local engagement supports sustainable agriculture and cultivates appreciation for diverse food sources.

**Business Model 14:**
This innovative mixed farming operation grows a variety of vegetables in tandem with specialty mushrooms, supplying local chefs with unique and high-quality ingredients. By enhancing biodiversity on the farm, the operation not only boosts resilience but also meets the increasing demand for unique culinary products. The commitment to local sourcing strengthens ties within the culinary community.

**Business Model 15:**
An online marketplace specializing in niche forest products, this company connects small producers of non-timber goods with a broader audience. By leveraging digital technology, the marketplace enhances visibility for unique offerings while promoting sustainable resource use. This platform empowers local artisans and producers, fostering economic opportunities in the forest products sector.

**Business Model 16:**
This permaculture farm integrates tree crops, vegetables, and livestock to create a self-sustaining ecosystem. Through holistic management practices, the farm promotes biodiversity and resilience while providing a diverse array of products. The emphasis on sustainable practices not only enhances productivity but educates consumers on the benefits of integrated farming systems.

**Business Model 17:**
Focused on raising goats for milk and cheese production, this agribusiness serves local markets while hosting educational farm visits. By engaging the community, the company enhances awareness of sustainable dairy practices and fosters a connection between consumers and their food sources. This dual approach not only drives sales but also promotes a culture of transparency in food production.

**Business Model 18:**
This specialty farm is committed to producing organic spices and herbs, targeting gourmet chefs and health-conscious consumers with unique offerings. By focusing on quality and sustainability, the farm positions itself at the intersection of culinary excellence and health trends. The emphasis on organic practices underscores the company's dedication to both quality and environmental responsibility.

**Business Model 19:**
As a cooperative, this organization unites mushroom growers and crop farmers to enhance biodiversity and create distinctive farm products. By facilitating collaboration among producers, the cooperative not only increases product diversity but also fosters sustainable agricultural practices. This synergistic approach benefits both the environment and the local economy, reinforcing community connections.

In [61]:
llm = ChatOllama(
            model=model,
            temperature=0.8, 
            base_url="http://10.80.20.101:11434/"
    )

prompt = ChatPromptTemplate.from_messages([
    ("system", ""),
    ("human", user_prompt_topic)
])


if excludes != "": 
    excludes = "Excludes: " + excludes

chain = prompt | llm

input = {
    "num_samples": num_samples,
    "includes": includes,
    "includes_also": includes_also,
    "excludes": excludes,
    }
formatted_prompt = prompt.invoke(input)

response = chain.invoke(input)

In [63]:
print(response.content)

1. AgriCorp specializes in growing and exporting high-quality wheat to bakeries and food manufacturers worldwide.
2. GreenEarth Farm produces and sells organic soybeans to health food stores and supplement companies.
3. CerealPro is a contract farming business that grows barley, oats, and rye for breweries and animal feed producers.
4. Legume Delights cultivates and processes chickpeas, lentils, and peas for the production of hummus, falafel, and other value-added products.
5. Sunflower Oil Co. grows sunflowers and extracts oil for use in food, cosmetics, and biofuels.
6. GrainMaster operates a large-scale farm growing corn, wheat, and sorghum for the animal feed and ethanol industries.
7. Healthy Harvest produces and markets quinoa, amaranth, and other nutritious grains to upscale grocery stores and restaurants.
8. Oilseed Solutions provides customized oilseed production services to food companies and biodiesel manufacturers.
9. FarmFresh Beans grows and exports high-quality kidney beans, black beans, and pinto beans to international markets.
10. Rapeseed Ranch produces rapeseed for the production of vegetable oils, animal feed, and industrial applications.
11. Sorghum Sweet Farm specializes in growing sweet sorghum syrup for use as a natural sweetener.
12. Broadacre Farms grows broad beans, peas, and lupins for human consumption and animal feed.
13. Linseed Logistics cultivates linseed for the production of linseed oil, flaxseed meal, and other industrial products.
14. Mustard Seed India produces mustard seeds for use in spices, condiments, and cooking oils.
15. Sesame Seeds Inc. grows sesame seeds for use in baking, snack foods, and cosmetics.
16. Cereal Growers Cooperative is a farmer-owned cooperative that pools resources to grow wheat, barley, oats, and rye for domestic markets.
17. Groundnut Growers Association supports smallholder farmers in growing groundnuts for the production of peanut butter, oil, and other value-added products.
18. Soybean Solutions provides genetic research and development services to improve soybean yields and disease resistance.
19. Millet Farm grows various types of millets for use in traditional foods, animal feed, and brewing applications.
20. Castor Bean Co. produces castor beans for the extraction of castor oil used in pharmaceuticals, cosmetics, and industrial lubricants.

In [8]:
%pwd

'/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/generate_synthetic_data'

In [2]:
os.chdir('/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3')
from NACE_helper import NACE_helper

NameError: name 'os' is not defined

In [28]:
generate_nace_class = "B"

In [41]:
nace_level = NACE_helper.get_nace_level(generate_nace_class)
if nace_level != 1: 
    nace_class_gold_standard = NACE_helper.get_level_1_nace(generate_nace_class)
elif nace_level == 1: 
    nace_class_gold_standard = generate_nace_class
gold_standard = df_gold_standard[df_gold_standard["NACE_letter"] == nace_class_gold_standard]["Description_clean"].to_list()[:3] 
gold_standard = [text.replace("\n", "") for text in gold_standard]

In [13]:
df_gold_standard

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Symbol,Description_page,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,...,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description,Description_clean,Tested_Class
2,2,2,2,ID1000167901,NaN,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,...,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,## Riwayat Singkat Perseroan\n\nThe Company at...,PT Dharma Samudera Fishing Industries Tbk or '...,True
11,11,11,11,LU0611262873,NaN,KSG Agro SA,1,2010.0,POL,L5903L107,...,1,SHARE,B42XFB0,A,KSG Agro SA1.pdf,1.5,1,"## PRINCIPAL ACTIVITIES\n\nKSG Agro S.A., sepa...","KSG Agro S.A., together with its subsidiaries,...",False
21,21,21,21,AU000000CSS3,NaN,Clean Seas Seafood Limited,1,2000.0,AUS,Q2508T119,...,1,SHARE,B0PFW92,A,Clean Seas Seafood Limited2.pdf,3.2,3,For personal use only\n\n<!-- image -->\n\n## ...,Clean Seas is the global leader in the full cy...,True
85,85,85,85,KR7086060001,5.0,"Gene Bio Tech Co., Ltd.",1,2000.0,KOR,Y2684U105,...,1,SHARE,B11R103,A,"Gene Bio Tech Co., Ltd.1.pdf",1.6,1,## WHO WE ARE\n\nBio-Gene is an Australian ...,Bio-Gene is an Australian agtech development c...,False
95,95,95,95,CA89154B1022,NaN,Total Energy Services Inc.,1,1996.0,CAN,89154B102,...,0,SHARE,BF2HFP3,B,Total Energy Services Inc.3.pdf,9.1,9,NaN,1.1 TotalEnergies at a glance\n1.1.1 A multi-e...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1202,1202,1202,1202,BMG8766E1093,NaN,Textainer Group Holdings Limited,1,1979.0,USA,G8766E109,...,0,SHARE,BKDZ8P2,N,Textainer Group Holdings Limited1.pdf,77.3,77,<!-- image -->\n\n## About Us\n\nTextainer Gro...,Textainer Group Holdings Limited (NYSE: TGH) i...,False
1223,1223,1223,1223,AU000000MMS5,NaN,Mcmillan Shakespeare Limited,1,1988.0,AUS,Q58998107,...,1,SHARE,B00G1Q0,N,Mcmillan Shakespeare Limited1.pdf,77.1,77,MMS ANNUAL REPORT 2022\n\nB\n\n## Annual Gene...,The McMillan Shakespeare Group is a provider o...,False
1238,1238,1238,1238,US10948C1071,NaN,"BrightView Holdings, Inc.",1,2013.0,USA,10948C107,...,1,SHARE,BG0ZML1,N,"BrightView Holdings, Inc.1.pdf",81.3,81,## General Risk Factors\n\n- Natural disasters...,"BrightView Holdings, Inc. is a holding company...",False
1241,1241,1241,1241,US23204X1037,NaN,Custom Truck One Source Inc,1,1996.0,USA,23204X103,...,1,SHARE,BL66YS4,N,Custom Truck One Source Inc1.pdf,77.3,77,## Item 1. Business\n\n## Company Overview...,"Custom Truck One Source, Inc. is engaged in th...",False
1671,1671,1671,1671,AU0000193666,NaN,Allkem Limited,1,2005.0,AUS,Q0226L103,...,0,SHARE,BMFLDX5,B,Allkem Limited1.pdf,8.9,8,NaN,About Allkem Allkem is a highly successful spe...,False