In [15]:
import matplotlib.pyplot as plt
import pymupdf4llm
import pymupdf
import glob
import sys
import os
import re
import pandas as pd
import tqdm

sys.path.append("../src")
import text_extraction
import fitz
import tqdm
import os
import glob
import pandas as pd
import pymupdf

In [3]:
reports = glob.glob("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/*.pdf")
reports

['/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Lufthansa AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hermes International SCA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RWE AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nordea Bank Abp1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Knorr-Bremse AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rolls-Royce Holdings plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BAE Systems plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SCOR SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Danone SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Terna S.p.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swissquote Group Holding Ltd.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Acciona SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Baloise-Holding AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Lotus Bakeries NV1.pdf',
 "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/L'Oreal S.A.1.pdf",
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Kemira Oyj1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sartorius Stedim Biotech SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Kering SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Merck KGaA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Plus500 Ltd.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Universal Music Group N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/LEG Immobilien SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wienerberger AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/IMI plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Porsche AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nokia Oyj2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ConvaTec Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vidrala SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nordnet AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Umicore SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Signify NV3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Associated British Foods plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ANDRITZ AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aurubis AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Boerse AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Azelis Group N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Zurich Insurance Group Ltd2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/PUMA SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ashtead Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/InterContinental Hotels Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aalberts N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Euronext NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Fresenius SE & Co. KGaA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Auto Trader Group PLC3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Accor SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Gerresheimer AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Airbus SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Avanza Bank Holding AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banco de Sabadell SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BANK POLSKA KASA OPIEKI SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Coca-Cola HBC AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bucher Industries AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Anglo American plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Next PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Compass Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Burberry Group plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Compagnie de Saint-Gobain SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Derwent London PLC REIT1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Pennon Group Plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/InPost S.A1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Poste Italiane SpA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nexans SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SEB SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Land Securities Group PLC2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Haleon PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rentokil Initial plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vestas Wind Systems AS1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Bank Aktiengesellschaft1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Technip Energies NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Thales SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Valmet Corp.2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Subsea 7 S.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ringkjobing Landbobank AS2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Enagas SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Howden Joinery Group PLC2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tate & Lyle PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swedish Orphan Biovitrum AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Accelleron Industries AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/J Sainsbury plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Totalenergies EP Gabon1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Pernod Ricard SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ASM International N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/AstraZeneca PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tritax Big Box REIT Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Eni S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Siemens Energy AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Intertek Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Interpump Group S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hannover Rueck SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Groupe Bruxelles Lambert SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Anheuser-Busch InBev SANV3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Scout24 SE3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bridgepoint Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/PSP Swiss Property AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Credit Agricole SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Financiere de Tubize SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SalMar ASA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Severn Trent Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ferrari NV2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bakkafrost PF2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sika AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swiss Prime Site AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sandvik AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Neste Corporation2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Heidelberg Materials AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Temenos AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Antofagasta plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Partners Group Holding AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Siemens Aktiengesellschaft2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tesco PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hera S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Just Eat Takeaway.com N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BPER Banca S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/GSK PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vonovia SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/QinetiQ Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rexel SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Soitec SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Alstom SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ITV plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/TUI AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Legal & General Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Telia Company AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Yara International ASA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/COMET Holding AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RELX PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wendel SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banca Popolare di Sondrio S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aviva plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ipsen SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Stellantis N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/UniCredit S.p.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BASF SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rubis SCA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Allfunds Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Renault SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/British American Tobacco p.l.c.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vistry Group PLC3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Akzo Nobel N.V.2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RATIONAL Aktiengesellschaft3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Barry Callebaut AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Randstad NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ASR Nederland N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wihlborgs Fastigheter AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/argenx SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banque Cantonale Vaudoise1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swiss Life Holding AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/EQT AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Volkswagen AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/London Stock Exchange Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Halma plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Eurofins Scientific SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/UNITE Group plc3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nexi S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sartorius AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Enel SpA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Getlink SE2.pdf',

In [4]:
text_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_no_tables"
text_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_one_font_size"
text_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_heuristik"
text_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi"

In [5]:
def is_block_within(block1, block2):
    """
    Returns True if block1 is fully inside block2's bounding box.
    Each block must have a 'bbox' key: [x0, y0, x1, y1]
    """
    x0_1, y0_1, x1_1, y1_1 = block1
    x0_2, y0_2, x1_2, y1_2 = block2
    
    return (
        x0_1 >= x0_2 and
        y0_1 >= y0_2 and
        x0_1 <= x1_2 and
        y0_1 <= y1_2
    )

In [6]:
def get_paragraphs(pdf_path: str):

    doc = pymupdf.open(pdf_path)
    uniform_blocks = []
    temp_text = ""
    temp_font_size = 0

    for i, page in enumerate(doc): 

        if i == 50: 
            break

        blocks = page.get_text("dict")["blocks"]
        for block in blocks:
            if "lines" in block.keys(): 
                for line in block["lines"]: 
                    for span in line["spans"]:
                        if span["text"].strip():
                            if span["size"] == temp_font_size:
                                temp_text += span["text"]
                            else:
                                if temp_text.strip() and any(char.isalpha() for char in temp_text):
                                    temp_dict = {"text": temp_text, "page": page.number, "font_size": temp_font_size}
                                    uniform_blocks.append(temp_dict)
                                temp_text = span["text"]
                                temp_font_size = span["size"]
    df = pd.DataFrame(uniform_blocks)

    return df

In [7]:
def get_paragraphs_max_font_size(pdf_path: str):

    doc = pymupdf.open(pdf_path)
    uniform_blocks = []
    temp_text = ""
    temp_font_size = 0

    for page in doc:
        blocks = page.get_text("dict")["blocks"]
        for block in blocks:
            if "lines" in block.keys(): 
                for line in block["lines"]: 
                    for span in line["spans"]:
                        if span["text"].strip():
                            if span["size"] == temp_font_size:
                                temp_text += span["text"]
                            else:
                                if temp_text.strip() and any(char.isalpha() for char in temp_text):
                                    temp_dict = {"text": temp_text, "page": page.number, "font_size": temp_font_size}
                                    uniform_blocks.append(temp_dict)
                                temp_text = span["text"]
                                temp_font_size = span["size"]
    df = pd.DataFrame(uniform_blocks)

    return df

In [8]:
def get_paragraphs_without_table(pdf_path: str) -> pd.DataFrame:

    doc = pymupdf.open(pdf_path)
    uniform_blocks = []
    temp_text = ""
    temp_font_size = 0

    for i, page in tqdm.tqdm(enumerate(doc)): 
            
        tabs = page.find_tables()
        blocks = page.get_text("dict")["blocks"]
        
        if i == 50: 
            break

        for block in blocks:
            if block["type"] == 0:  # Nur Textblöcke (nicht Bilder)
                if not any([is_block_within(block["bbox"], tab.bbox) for tab in tabs]):             
                    if "lines" in block.keys(): 
                        for line in block["lines"]: 
                            for span in line["spans"]:
                                if span["text"].strip(): 
                                    if span["size"] == temp_font_size:
                                        temp_text += span["text"]
                                    else:
                                        if temp_text.strip() and any(char.isalpha() for char in temp_text):
                                            temp_dict = {"text": temp_text, "page": page.number, "font_size": temp_font_size}
                                            uniform_blocks.append(temp_dict)
                                        temp_text = span["text"]
                                        temp_font_size = span["size"]

    df = pd.DataFrame(uniform_blocks)

    df["len"] = df["text"].apply(len)
    df["share"] = df["len"] / df["len"].sum()    
    return df

In [9]:
def get_font_sizes(path): 
    df = get_paragraphs_without_table(path)
    df["len"] = df["text"].apply(len)
    df["share"] = df["len"] / df["len"].sum()    
    return df.groupby("font_size").sum().sort_values(by="share", ascending=False)

In [10]:
def extract_all_sizes(block):
    sizes = []
    for line in block.get("lines", []):
        for span in line.get("spans", []):
            if "size" in span:
                sizes.append(span["size"])
    return sizes

In [11]:
def extract_block_text(block):
    spans = []
    for line in block.get("lines", []):
        for span in line.get("spans", []):
            if span["text"].strip():
                spans.append(span["text"])
    text = " ".join(spans)
    text = re.sub(r' +', ' ', text)
    return " ".join(spans)

In [12]:
def heuristik_text(text: str) -> bool: 
    # remove all numbers like 1.234 or 500.000
    text = re.sub(r'\b\d+\.\d+\b', '', text)

    text = re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", "", text)
    
    if len(text.split(" ")) > 10 and len(text) > 30 and "." in text: 
            return True
    
    return False

In [47]:
def check_font_sizes(max_font_size: float, font_sizes_block: list): 
    for font_size_block in font_sizes_block: 
        if font_size_block < max_font_size * 1.02 and font_size_block > max_font_size * 0.98: 
            return True

In [48]:
def check_nummerical_block(text: str, p: float = 0.5):
    text = text.strip()

    if len(text) == 0: 
        return False

    count = sum(c.isdigit() for c in text)
    return count/len(text) > p

In [49]:
reports

['/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Lufthansa AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hermes International SCA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RWE AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nordea Bank Abp1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Knorr-Bremse AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rolls-Royce Holdings plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BAE Systems plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SCOR SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Danone SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Terna S.p.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swissquote Group Holding Ltd.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Acciona SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Baloise-Holding AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Lotus Bakeries NV1.pdf',
 "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/L'Oreal S.A.1.pdf",
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Kemira Oyj1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sartorius Stedim Biotech SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Kering SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Merck KGaA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Plus500 Ltd.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Universal Music Group N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/LEG Immobilien SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wienerberger AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/IMI plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Porsche AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nokia Oyj2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ConvaTec Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vidrala SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nordnet AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Umicore SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Signify NV3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Associated British Foods plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ANDRITZ AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aurubis AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Boerse AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Azelis Group N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Zurich Insurance Group Ltd2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/PUMA SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ashtead Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/InterContinental Hotels Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aalberts N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Euronext NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Fresenius SE & Co. KGaA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Auto Trader Group PLC3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Accor SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Gerresheimer AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Airbus SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Avanza Bank Holding AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banco de Sabadell SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BANK POLSKA KASA OPIEKI SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Coca-Cola HBC AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bucher Industries AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Anglo American plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Next PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Compass Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Burberry Group plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Compagnie de Saint-Gobain SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Derwent London PLC REIT1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Pennon Group Plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/InPost S.A1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Poste Italiane SpA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nexans SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SEB SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Land Securities Group PLC2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Haleon PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rentokil Initial plc2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vestas Wind Systems AS1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Deutsche Bank Aktiengesellschaft1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Technip Energies NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Thales SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Valmet Corp.2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Subsea 7 S.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ringkjobing Landbobank AS2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Enagas SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Howden Joinery Group PLC2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tate & Lyle PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swedish Orphan Biovitrum AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Accelleron Industries AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/J Sainsbury plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Totalenergies EP Gabon1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Pernod Ricard SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ASM International N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/AstraZeneca PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tritax Big Box REIT Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Eni S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Siemens Energy AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Intertek Group PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Interpump Group S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hannover Rueck SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Groupe Bruxelles Lambert SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Anheuser-Busch InBev SANV3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Scout24 SE3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bridgepoint Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/PSP Swiss Property AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Credit Agricole SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Financiere de Tubize SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/SalMar ASA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Severn Trent Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ferrari NV2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Bakkafrost PF2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sika AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swiss Prime Site AG2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sandvik AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Neste Corporation2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Heidelberg Materials AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Temenos AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Antofagasta plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Partners Group Holding AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Siemens Aktiengesellschaft2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Tesco PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Hera S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Just Eat Takeaway.com N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BPER Banca S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/GSK PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vonovia SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/QinetiQ Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rexel SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Soitec SA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Alstom SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ITV plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/TUI AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Legal & General Group Plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Telia Company AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Yara International ASA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/COMET Holding AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RELX PLC1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wendel SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banca Popolare di Sondrio S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Aviva plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Ipsen SA2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Stellantis N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/UniCredit S.p.A.3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/BASF SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Rubis SCA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Allfunds Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Renault SA3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/British American Tobacco p.l.c.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Vistry Group PLC3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Akzo Nobel N.V.2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/RATIONAL Aktiengesellschaft3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Barry Callebaut AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Randstad NV1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/ASR Nederland N.V.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Wihlborgs Fastigheter AB2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/argenx SE1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Banque Cantonale Vaudoise1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Swiss Life Holding AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/EQT AB1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Volkswagen AG1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/London Stock Exchange Group plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Halma plc1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Eurofins Scientific SE2.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/UNITE Group plc3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Nexi S.p.A.1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Sartorius AG3.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Enel SpA1.pdf',
 '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Getlink SE2.pdf',

In [50]:
import fitz  # PyMuPDF
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import io

# --- Helper function ---
def is_block_within(block_bbox, table_bbox):
    bx0, by0, bx1, by1 = block_bbox
    tx0, ty0, tx1, ty1 = table_bbox
    return bx0 >= tx0 and by0 >= ty0 and bx1 <= tx1 and by1 <= ty1

# --- Load PDF ---

record_font_sizes = {}

for path in tqdm.tqdm(reports):
    doc = fitz.open(path)

    df = get_paragraphs(path)
    df["len"] = df["text"].apply(len)
    df["share"] = df["len"] / df["len"].sum()    
    font_sizes =  df.groupby("font_size").sum().sort_values(by="share", ascending=False)
    record_font_sizes[os.path.basename(path)] = font_sizes
    max_font_size =  font_sizes.iloc[0].name

    images = []

    i = 0

    # --- Iterate over all pages ---
    for page in doc.pages():
        
        i += 1
        if i == 50:
            break

        # Get image of the page
        pix = page.get_pixmap(dpi=150)
        img_bytes = pix.tobytes("ppm")
        img = Image.open(io.BytesIO(img_bytes))

        # Setup figure and axes
        fig, ax = plt.subplots(figsize=(10, 12))
        ax.imshow(img)
        ax.axis("off")
        
        # DPI scaling factor
        scale = 150 / 72

        # Table and block detection
        tables = page.find_tables()
        blocks = page.get_text("dict")["blocks"]

        # Draw block bounding boxes
        for b in blocks:
            if b["type"] == 0:
                
                x0, y0, x1, y1 = b["bbox"]

                text_block = extract_block_text(b)

                font_sizes_block = extract_all_sizes(b)

                if any([is_block_within(b["bbox"], tab.bbox) for tab in tables]): 
                    color = "red"
                elif check_nummerical_block(text_block): 
                    color = "brown"
                elif check_font_sizes(max_font_size=max_font_size, font_sizes_block=font_sizes_block):
                    color = "yellow"
                elif heuristik_text(text_block): 
                    color = "blue"
                else: 
                    color = "black"

                rect = patches.Rectangle(
                    (x0 * scale, y0 * scale), (x1 - x0) * scale, (y1 - y0) * scale,
                    linewidth=1.5, edgecolor=color, facecolor='none'
                )
                ax.add_patch(rect)

        # Save figure to in-memory image
        buf = io.BytesIO()
        plt.savefig(buf, format='png', bbox_inches='tight', dpi=150)
        buf.seek(0)
        images.append(Image.open(buf).convert("RGB"))
        plt.close(fig)

    # --- Save all images into a single PDF ---

    save_path = os.path.join(text_path, os.path.basename(path))

    if images:
        images[0].save(save_path, save_all=True, append_images=images[1:])

    print(f"Saved {save_path} successfully.")

  0%|          | 1/275 [00:27<2:07:26, 27.91s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Deutsche Lufthansa AG1.pdf successfully.

  1%|          | 2/275 [00:50<1:53:36, 24.97s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Hermes International SCA2.pdf successfully.

  1%|          | 3/275 [01:12<1:46:55, 23.59s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/RWE AG1.pdf successfully.

  1%|▏         | 4/275 [01:37<1:48:36, 24.05s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Nordea Bank Abp1.pdf successfully.

  2%|▏         | 5/275 [02:02<1:49:42, 24.38s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Knorr-Bremse AG1.pdf successfully.

  2%|▏         | 6/275 [02:36<2:03:14, 27.49s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Rolls-Royce Holdings plc1.pdf successfully.

  3%|▎         | 7/275 [03:13<2:16:48, 30.63s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/BAE Systems plc1.pdf successfully.

  3%|▎         | 8/275 [03:40<2:11:39, 29.58s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/SCOR SE2.pdf successfully.

  3%|▎         | 9/275 [04:10<2:11:40, 29.70s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Danone SA1.pdf successfully.

  4%|▎         | 10/275 [04:35<2:04:13, 28.13s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Terna S.p.A.3.pdf successfully.

  4%|▍         | 11/275 [05:05<2:06:18, 28.70s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Swissquote Group Holding Ltd.1.pdf successfully.

  4%|▍         | 12/275 [05:42<2:17:28, 31.36s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Acciona SA2.pdf successfully.

  5%|▍         | 13/275 [06:03<2:03:09, 28.21s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Baloise-Holding AG2.pdf successfully.

  5%|▌         | 14/275 [06:25<1:54:05, 26.23s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Lotus Bakeries NV1.pdf successfully.

  5%|▌         | 15/275 [06:37<1:35:16, 21.99s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/L'Oreal S.A.1.pdf successfully.

  6%|▌         | 16/275 [07:01<1:37:22, 22.56s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Kemira Oyj1.pdf successfully.

  6%|▌         | 17/275 [07:23<1:36:32, 22.45s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Sartorius Stedim Biotech SA1.pdf successfully.

  7%|▋         | 18/275 [07:43<1:32:42, 21.65s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Kering SA1.pdf successfully.

  7%|▋         | 19/275 [08:11<1:41:28, 23.78s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Merck KGaA2.pdf successfully.

  7%|▋         | 20/275 [11:39<5:35:07, 78.85s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Plus500 Ltd.1.pdf successfully.

  8%|▊         | 21/275 [12:14<4:39:03, 65.92s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Universal Music Group N.V.1.pdf successfully.

  8%|▊         | 22/275 [12:35<3:40:37, 52.32s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/LEG Immobilien SE1.pdf successfully.

  8%|▊         | 23/275 [13:01<3:06:39, 44.44s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Wienerberger AG2.pdf successfully.

  9%|▊         | 24/275 [13:35<2:53:18, 41.43s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/IMI plc1.pdf successfully.

  9%|▉         | 25/275 [14:01<2:32:45, 36.66s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Porsche AG1.pdf successfully.

  9%|▉         | 26/275 [14:44<2:40:44, 38.73s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Nokia Oyj2.pdf successfully.

 10%|▉         | 27/275 [15:43<3:05:06, 44.79s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/ConvaTec Group Plc1.pdf successfully.

 10%|█         | 28/275 [16:06<2:37:00, 38.14s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Vidrala SA3.pdf successfully.

 11%|█         | 29/275 [16:34<2:24:24, 35.22s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Nordnet AB1.pdf successfully.

 11%|█         | 30/275 [17:23<2:40:26, 39.29s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Umicore SA1.pdf successfully.

 11%|█▏        | 31/275 [17:50<2:24:28, 35.53s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Signify NV3.pdf successfully.

 12%|█▏        | 32/275 [18:46<2:48:19, 41.56s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Associated British Foods plc1.pdf successfully.

 12%|█▏        | 33/275 [19:29<2:50:17, 42.22s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/ANDRITZ AG1.pdf successfully.

 12%|█▏        | 34/275 [19:42<2:14:11, 33.41s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Aurubis AG3.pdf successfully.

 13%|█▎        | 35/275 [19:48<1:41:01, 25.26s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Deutsche Boerse AG3.pdf successfully.

 13%|█▎        | 36/275 [19:59<1:22:52, 20.81s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Azelis Group N.V.1.pdf successfully.

 13%|█▎        | 37/275 [20:26<1:29:38, 22.60s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Zurich Insurance Group Ltd2.pdf successfully.

 14%|█▍        | 38/275 [20:49<1:29:45, 22.72s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/PUMA SE1.pdf successfully.

 14%|█▍        | 39/275 [21:20<1:39:34, 25.32s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Ashtead Group plc1.pdf successfully.

 15%|█▍        | 40/275 [21:51<1:45:58, 27.06s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/InterContinental Hotels Group PLC1.pdf successfully.

 15%|█▍        | 41/275 [22:23<1:51:02, 28.47s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Aalberts N.V.1.pdf successfully.

 15%|█▌        | 42/275 [22:51<1:49:58, 28.32s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Euronext NV1.pdf successfully.

 16%|█▌        | 43/275 [23:17<1:46:33, 27.56s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Fresenius SE & Co. KGaA1.pdf successfully.

 16%|█▌        | 44/275 [23:49<1:51:20, 28.92s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Auto Trader Group PLC3.pdf successfully.

 16%|█▋        | 45/275 [24:29<2:03:57, 32.34s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Accor SA1.pdf successfully.

 17%|█▋        | 46/275 [25:00<2:01:50, 31.92s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Gerresheimer AG1.pdf successfully.

 17%|█▋        | 47/275 [25:28<1:56:52, 30.76s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Airbus SE1.pdf successfully.

 17%|█▋        | 48/275 [25:56<1:53:18, 29.95s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Avanza Bank Holding AB1.pdf successfully.

 18%|█▊        | 49/275 [26:21<1:47:15, 28.48s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Banco de Sabadell SA1.pdf successfully.

 18%|█▊        | 50/275 [26:44<1:40:23, 26.77s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/BANK POLSKA KASA OPIEKI SA1.pdf successfully.

 19%|█▊        | 51/275 [27:14<1:43:44, 27.79s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Coca-Cola HBC AG2.pdf successfully.

 19%|█▉        | 52/275 [27:39<1:39:34, 26.79s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Bucher Industries AG1.pdf successfully.

 19%|█▉        | 53/275 [28:04<1:38:04, 26.51s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Anglo American plc1.pdf successfully.

 20%|█▉        | 54/275 [28:30<1:36:06, 26.09s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Next PLC1.pdf successfully.

 20%|██        | 55/275 [28:57<1:36:40, 26.37s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Compass Group PLC1.pdf successfully.

 20%|██        | 56/275 [29:21<1:34:09, 25.80s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Burberry Group plc2.pdf successfully.

 21%|██        | 57/275 [29:48<1:34:48, 26.10s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Compagnie de Saint-Gobain SA2.pdf successfully.

 21%|██        | 58/275 [30:21<1:41:34, 28.08s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Derwent London PLC REIT1.pdf successfully.

 21%|██▏       | 59/275 [30:49<1:41:26, 28.18s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Pennon Group Plc2.pdf successfully.

 22%|██▏       | 60/275 [31:33<1:58:31, 33.08s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/InPost S.A1.pdf successfully.

 22%|██▏       | 61/275 [32:01<1:52:31, 31.55s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Poste Italiane SpA2.pdf successfully.

 23%|██▎       | 62/275 [32:25<1:43:53, 29.26s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Nexans SA3.pdf successfully.

 23%|██▎       | 63/275 [32:38<1:25:16, 24.14s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/SEB SA2.pdf successfully.

 23%|██▎       | 64/275 [33:04<1:27:04, 24.76s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Land Securities Group PLC2.pdf successfully.

 24%|██▎       | 65/275 [33:37<1:35:30, 27.29s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Haleon PLC1.pdf successfully.

 24%|██▍       | 66/275 [34:07<1:37:50, 28.09s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Rentokil Initial plc2.pdf successfully.

 24%|██▍       | 67/275 [34:10<1:11:02, 20.49s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Vestas Wind Systems AS1.pdf successfully.

 25%|██▍       | 68/275 [34:44<1:25:22, 24.75s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Deutsche Bank Aktiengesellschaft1.pdf successfully.

 25%|██▌       | 69/275 [35:16<1:31:38, 26.69s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Technip Energies NV1.pdf successfully.

 25%|██▌       | 70/275 [35:26<1:14:02, 21.67s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Thales SA1.pdf successfully.

 26%|██▌       | 71/275 [35:54<1:20:34, 23.70s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Valmet Corp.2.pdf successfully.

 26%|██▌       | 72/275 [35:54<56:30, 16.70s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Subsea 7 S.A.3.pdf successfully.

 27%|██▋       | 73/275 [35:55<39:48, 11.82s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Ringkjobing Landbobank AS2.pdf successfully.

 27%|██▋       | 74/275 [36:27<59:44, 17.83s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Enagas SA1.pdf successfully.

 27%|██▋       | 75/275 [37:00<1:14:53, 22.47s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Howden Joinery Group PLC2.pdf successfully.

 28%|██▊       | 76/275 [37:34<1:26:14, 26.00s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Tate & Lyle PLC1.pdf successfully.

 28%|██▊       | 77/275 [37:49<1:14:15, 22.50s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Swedish Orphan Biovitrum AB1.pdf successfully.

 28%|██▊       | 78/275 [38:24<1:26:49, 26.45s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Accelleron Industries AG1.pdf successfully.

 29%|██▊       | 79/275 [38:49<1:24:53, 25.99s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/J Sainsbury plc1.pdf successfully.

 29%|██▉       | 80/275 [39:12<1:21:39, 25.13s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Totalenergies EP Gabon1.pdf successfully.

 29%|██▉       | 81/275 [39:39<1:23:19, 25.77s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Pernod Ricard SA2.pdf successfully.

 30%|██▉       | 82/275 [40:09<1:26:28, 26.88s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/ASM International N.V.1.pdf successfully.

 30%|███       | 83/275 [40:43<1:33:21, 29.17s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/AstraZeneca PLC1.pdf successfully.

 31%|███       | 84/275 [41:12<1:32:21, 29.01s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Tritax Big Box REIT Plc1.pdf successfully.

 31%|███       | 85/275 [41:37<1:28:26, 27.93s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Eni S.p.A.1.pdf successfully.

 31%|███▏      | 86/275 [42:02<1:24:45, 26.91s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Siemens Energy AG1.pdf successfully.

 32%|███▏      | 87/275 [42:26<1:21:20, 25.96s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Intertek Group PLC1.pdf successfully.

 32%|███▏      | 88/275 [42:48<1:17:49, 24.97s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Interpump Group S.p.A.1.pdf successfully.

 32%|███▏      | 89/275 [43:08<1:12:50, 23.50s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Hannover Rueck SE1.pdf successfully.

 33%|███▎      | 90/275 [43:09<51:05, 16.57s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Groupe Bruxelles Lambert SA1.pdf successfully.

 33%|███▎      | 91/275 [43:35<59:53, 19.53s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Anheuser-Busch InBev SANV3.pdf successfully.

 33%|███▎      | 92/275 [44:03<1:06:39, 21.86s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Scout24 SE3.pdf successfully.

 34%|███▍      | 93/275 [44:34<1:14:46, 24.65s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Bridgepoint Group Plc1.pdf successfully.

 34%|███▍      | 94/275 [44:36<54:21, 18.02s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/PSP Swiss Property AG2.pdf successfully.

 35%|███▍      | 95/275 [44:50<50:19, 16.77s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Credit Agricole SA1.pdf successfully.

 35%|███▍      | 96/275 [44:51<35:23, 11.86s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Financiere de Tubize SA2.pdf successfully.

 35%|███▌      | 97/275 [44:59<32:30, 10.96s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/SalMar ASA1.pdf successfully.

 36%|███▌      | 98/275 [45:32<51:20, 17.41s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Severn Trent Plc1.pdf successfully.

 36%|███▌      | 99/275 [45:54<55:07, 18.80s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Ferrari NV2.pdf successfully.

 36%|███▋      | 100/275 [46:17<58:15, 19.98s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Bakkafrost PF2.pdf successfully.

 37%|███▋      | 101/275 [46:23<45:41, 15.75s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Sika AG3.pdf successfully.

 37%|███▋      | 102/275 [47:29<1:29:31, 31.05s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Swiss Prime Site AG2.pdf successfully.

 37%|███▋      | 103/275 [47:31<1:03:56, 22.30s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Sandvik AB2.pdf successfully.

 38%|███▊      | 104/275 [47:51<1:01:27, 21.56s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Neste Corporation2.pdf successfully.

 38%|███▊      | 105/275 [48:19<1:06:10, 23.36s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Heidelberg Materials AG1.pdf successfully.

 39%|███▊      | 106/275 [48:47<1:10:00, 24.86s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Temenos AG1.pdf successfully.

 39%|███▉      | 107/275 [49:18<1:14:42, 26.68s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Antofagasta plc1.pdf successfully.

 39%|███▉      | 108/275 [49:32<1:03:36, 22.85s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Partners Group Holding AG1.pdf successfully.

 40%|███▉      | 109/275 [49:56<1:04:20, 23.25s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Siemens Aktiengesellschaft2.pdf successfully.

 40%|████      | 110/275 [50:31<1:13:41, 26.79s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Tesco PLC1.pdf successfully.

 40%|████      | 111/275 [50:38<56:50, 20.80s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Hera S.p.A.1.pdf successfully.

 41%|████      | 112/275 [50:57<54:55, 20.22s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Just Eat Takeaway.com N.V.1.pdf successfully.

 41%|████      | 113/275 [51:20<57:05, 21.15s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/BPER Banca S.p.A.1.pdf successfully.

 41%|████▏     | 114/275 [51:51<1:04:52, 24.18s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/GSK PLC1.pdf successfully.

 42%|████▏     | 115/275 [52:23<1:10:20, 26.38s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Vonovia SE1.pdf successfully.

 42%|████▏     | 116/275 [53:13<1:28:47, 33.51s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/QinetiQ Group plc1.pdf successfully.

 43%|████▎     | 117/275 [53:42<1:24:41, 32.16s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Rexel SA1.pdf successfully.

 43%|████▎     | 118/275 [54:03<1:15:26, 28.83s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Soitec SA1.pdf successfully.

 43%|████▎     | 119/275 [54:14<1:00:57, 23.45s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Alstom SA2.pdf successfully.

 44%|████▎     | 120/275 [54:47<1:07:52, 26.28s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/ITV plc1.pdf successfully.

 44%|████▍     | 121/275 [55:40<1:28:24, 34.45s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/TUI AG1.pdf successfully.

 44%|████▍     | 122/275 [56:07<1:22:01, 32.17s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Legal & General Group Plc1.pdf successfully.

 45%|████▍     | 123/275 [56:21<1:07:39, 26.71s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Telia Company AB2.pdf successfully.

 45%|████▌     | 124/275 [56:45<1:05:19, 25.96s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Yara International ASA2.pdf successfully.

 45%|████▌     | 125/275 [57:11<1:04:26, 25.77s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/COMET Holding AG1.pdf successfully.

 46%|████▌     | 126/275 [57:45<1:10:34, 28.42s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/RELX PLC1.pdf successfully.

 46%|████▌     | 127/275 [58:10<1:07:41, 27.44s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Wendel SE2.pdf successfully.

 47%|████▋     | 128/275 [58:37<1:06:37, 27.19s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Banca Popolare di Sondrio S.p.A.1.pdf successfully.

 47%|████▋     | 129/275 [59:00<1:03:10, 25.96s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Aviva plc1.pdf successfully.

 47%|████▋     | 130/275 [59:26<1:02:42, 25.95s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Ipsen SA2.pdf successfully.

 48%|████▊     | 131/275 [59:48<59:27, 24.77s/it]

Saved /Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/results/german_annual_reports_text_combi/Stellantis N.V.1.pdf successfully.

:

In [14]:
heuristik_text("€m1,509– 1,666EBIT€m1,231– 2,316Net profit/loss€m791– 2,191Key balance sheet and cash flow statement figuresTotal assets€m43,33542,5382Equity ratio%19.610.69.0 ptsNet indebtedness€m6,8719,023– 24Pension provisions€m2,0696,676– 69Operating cash flow ")

True

In [ ]:
for r in record_font_sizes: 
    plt.bar(r.index, r["share"])
    plt.show()

In [42]:
def get_text_spans_without_tables(pdf_path: str) -> pd.DataFrame:

    doc = pymupdf.open(pdf_path)
    uniform_blocks = []

    block_nr = 0
    i = 0
    for page in doc:
        i += 1
        if i == 10: 
            break
        blocks = page.get_text("dict")["blocks"]
        tables = page.find_tables()
        print(i)
        for tab in tables: 
            print(tab.to_pandas())
        for block in blocks:
            if not any([is_block_within(block["bbox"], tab.bbox) for tab in tables]) and "lines" in block.keys(): 
                for line in block["lines"]: 
                    for span in line["spans"]:
                        span_text = ""
                        span_font_size = 0
                        if span["text"].strip():
                            span_text += span["text"]
                            span_font_size = span["size"]
                        if span_text.strip():                                        
                            temp_dict = {"text": span_text, "page": page.number, "font_size": span_font_size, "block_nr": block_nr}
                            uniform_blocks.append(temp_dict)
            block_nr += 1
        
    df = pd.DataFrame(uniform_blocks)

    return df

In [129]:
reports[0] = '/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/PDF_stoxx600/Lotus Bakeries NV1.pdf'

In [130]:
df_spans = get_text_spans_without_tables(reports[0])

1
2
3
4
5
6
7
8
9

In [131]:
df_spans["len"] = df_spans["text"].apply(len)
df_spans["share"] = df_spans["len"] / df_spans["len"].sum()    
font_sizes =  df_spans.groupby("font_size").sum().sort_values(by="share", ascending=False)
max_font_size =  font_sizes.iloc[0].name

In [132]:
blocks = df_spans.groupby("block_nr").agg({
    "page": lambda x: x.mean(), 
    "text" : lambda x: " ".join(x), 
    "font_size": lambda x: x.to_list(),
})

In [133]:
blocks

,page,text,font_size
block_nr,,,
0,0.0,ANNUAL REPORT 2022,[20.0]
3,1.0,OUR MISSION IS TO CREATE SMALL MOMENTS OF JOY ...,"[20.0, 20.0, 20.0, 20.0, 20.0, 20.0]"
4,2.0,Lotus Bakeries - 5,[10.0]
5,2.0,A MESSAGE FROM OUR CEO AND CHAIRMAN,"[28.0, 28.0]"
6,2.0,It is not outlandish to say that the entire wo...,[7.971750259399414]
...,...,...,...
241,8.0,"stake in IQBAR, an American producer of",[8.0]
242,8.0,a plant-based nutrition bars containing six,[8.0]
243,8.0,ingredients with benefits for the body and,[8.0]
244,8.0,the mind.,[8.0]
245,8.0,16 - Lotus Bakeries Highlights 2022,"[10.0, 10.0]"

In [134]:
import re

def is_block_within(block_bbox, table_bbox):
    bx0, by0, bx1, by1 = block_bbox
    tx0, ty0, tx1, ty1 = table_bbox
    return bx0 >= tx0 and by0 >= ty0 and bx1 <= tx1 and by1 <= ty1

def extract_all_sizes(block):
    sizes = []
    for line in block.get("lines", []):
        for span in line.get("spans", []):
            if "size" in span:
                sizes.append(span["size"])
    return sizes

def extract_block_text(block):
    spans = []
    for line in block.get("lines", []):
        for span in line.get("spans", []):
            if span["text"].strip():
                spans.append(span["text"])
    text = " ".join(spans)
    text = re.sub(r' +', ' ', text)
    return " ".join(spans)

def heuristik_text(text: str) -> bool: 
    # remove all numbers like 1.234 or 500.000
    text = re.sub(r'\b\d+\.\d+\b', '', text)

    text = re.sub(r"[^a-zA-ZäöüÄÖÜß.\s]", "", text)
    
    if len(text.split(" ")) > 10 and len(text) > 30 and "." in text: 
            return True
    
    return False
def check_font_sizes(max_font_size: float, font_sizes_block: list): 
    for font_size_block in font_sizes_block: 
        if font_size_block < max_font_size * 1.02 and font_size_block > max_font_size * 0.98: 
            return True
    return False

def check_nummerical_block(text: str, p: float = 0.5):
    text = text.strip()

    if len(text) == 0: 
        return False

    count = sum(c.isdigit() for c in text)
    return count/len(text) > p

In [135]:
## filter blocks
blocks["accept"] = None
for idx, block in blocks.iterrows(): 
    blocks.loc[idx, "accept"] = not check_nummerical_block(block["text"]) and (check_font_sizes(max_font_size, block["font_size"]) or heuristik_text(block["text"]))

In [136]:
blocks

,page,text,font_size,accept
block_nr,,,,
0,0.0,ANNUAL REPORT 2022,[20.0],False
3,1.0,OUR MISSION IS TO CREATE SMALL MOMENTS OF JOY ...,"[20.0, 20.0, 20.0, 20.0, 20.0, 20.0]",True
4,2.0,Lotus Bakeries - 5,[10.0],False
5,2.0,A MESSAGE FROM OUR CEO AND CHAIRMAN,"[28.0, 28.0]",False
6,2.0,It is not outlandish to say that the entire wo...,[7.971750259399414],True
...,...,...,...,...
241,8.0,"stake in IQBAR, an American producer of",[8.0],True
242,8.0,a plant-based nutrition bars containing six,[8.0],True
243,8.0,ingredients with benefits for the body and,[8.0],True
244,8.0,the mind.,[8.0],True
245,8.0,16 - Lotus Bakeries Highlights 2022,"[10.0, 10.0]",False

In [137]:
# join (take other example pdf!)d

In [138]:
import copy

In [139]:
blocks["font_size_set"] = blocks["font_size"].apply(set)

In [140]:
blocks_2 = []

for page in set(blocks["page"]): 
    blocks_temp = copy.copy(blocks[blocks["page"] == page])
    
    
    for i, row in blocks_temp.iterrows(): 
        if row["accept"] and len(row["font_size_set"]) == 1: 
            temp_text = row["text"]
            temp_font_size = list(row["font_size_set"])[0]
            start_index = i
            break

    for i, row in blocks_temp.loc[start_index:].iterrows(): 
        if row["accept"] and len(row["font_size_set"]) == 1 and temp_font_size == list(row["font_size_set"])[0]: 
            temp_text += row["text"]
        elif row["accept"] and len(row["font_size_set"]) > 1: 
            blocks_2.append({"text": temp_text, "font_size": temp_font_size})
            temp_text = ""
            temp_font_size = 
        else: 
            blocks_2.append({"text": temp_text, "font_size": temp_font_size})

SyntaxError: invalid syntax (4034761042.py, line 20)

In [141]:
start_index

174

In [142]:
blocks_temp.iloc[0]["font_size_set"]

{9.0}

In [ ]:
blocks_temp["font_size_set"] = blocks_temp["font_size"].apply(set)

'|   block_nr |   page | text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | font_size                                                                        | accept   | font_size_set            |\n|-----------:|-------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------|:---------|:-------------------------|\n|        174 |      8 | and operating decisions. In particular, it provided regular reports on the Company’s economic  position and on the operational challenges in this financial year. Throughout the year, the  Executive Board provided the Supervisory Board with regular reports on the current course   of business. As Chairman of the Supervisory Board, I read the minutes of the Executive Board  meetings and discussed the current situation and the course of business with the Chairman of  the Executive Board and other members of the Executive Board on an ongoing basis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [9.0, 9.0, 9.0, 9.0, 9.0, 9.0]                                                   | True     | {9.0}                    |\n|        175 |      8 | In 2022, the Supervisory Board held a total of five meetings. At its plenary sessions and   committee meetings, the Supervisory Board had sufficient opportunity to discuss the reports  and proposals for resolutions from the Executive Board. When doing so, the Supervisory  Board and its committees also met regularly without the members of the Executive Board.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | [9.0, 9.0, 9.0, 9.0]                                                             | True     | {9.0}                    |\n|        176 |      8 | https://investor-relations.lufthansagroup.com/en/corporate-governance/supervisory-board.html.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | [8.0]                                                                            | False    | {8.0}                    |\n|        177 |      8 | Key topics discussed by the Supervisory Board  Our meetings focused on the economic development of Deutsche Lufthansa AG and its  associated companies. In particular, the tough operational situation, the impact of Russia’s  invasion of Ukraine, the competitive environment and sustainability issues were discussed   on an ongoing basis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | [9.0, 9.0, 9.0, 9.0, 9.0]                                                        | True     | {9.0}                    |\n|        178 |      8 | At its meeting on 9 May 2022, the Supervisory Board approved the acquisition of seven   Boeing 787-9 long-haul aircraft including a replacement engine, three Boeing 777 cargo   aircraft (777F) and seven Boeing 777-8F cargo aircraft including a replacement engine.   At the same meeting, the Supervisory Board also approved the extension of two 777F leases  for a period of 84 months.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | [9.0, 9.0, 9.0, 9.0, 9.0]                                                        | True     | {9.0}                    |\n|        179 |      8 | At its extraordinary meeting held on 6 July 2022, the Supervisory Board considered in   particular the tough operational situation at the Passenger Airlines as a result of the build-up  of flight delays and cancellations. The situation has since stabilised noticeably.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | [9.0, 9.0, 9.0]                                                                  | True     | {9.0}                    |\n|        180 |      8 | The meeting of 23 September 2022 – which was held in Zurich and thus at a Group company  location for the first time since the coronavirus pandemic – considered the Group’s strategic  development and discussed this in detail with the Executive Board. The corporate strategy  was updated on this basis and then approved at the Supervisory Board meeting on 8 Decem- ber 2022.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | [9.0, 9.0, 9.0, 9.0, 9.0]                                                        | True     | {9.0}                    |\n|        181 |      8 | Moreover, on 8 December 2022 the Supervisory Board approved the 2023 budget and the  medium-term financial planning for 2024 to 2026 and authorised investments in order to                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | [9.0, 9.0]                                                                       | True     | {9.0}                    |\n|        182 |      8 | upgrade 17 Airbus A350-900s and twelve Boeing 777-300s with the future cabin product  generation. At this meeting the Supervisory Board also discussed reports on ESG (environ- mental, social & governance) issues, risk management including Internal Control Systems,  cybersecurity and compliance.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | [9.0, 9.0, 9.0, 9.0]                                                             | True     | {9.0}                    |\n|        183 |      8 | Exercising their right as agreed with the ESF to attend meetings of the Supervisory Board   of Deutsche Lufthansa AG, Annette Olschinka-Rettig, Head of Department for Equity   Investments and ESF at Bundesrepublik Deutschland – Finanzagentur GmbH or her deputy  Michael Haas joined the Supervisory Board’s meetings of 2 March, 9 May and 6 July 2022 as  well as the meetings of the Audit Committee held on 24 February, 28 April and 28 July 2022.  Following the German government’s sale of its remaining Lufthansa shares on 13 September  2022, the ESF’s right to attend meetings of the Supervisory Board and its committees has  now expired.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | [9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0]                                         | True     | {9.0}                    |\n|        184 |      8 | Executive Board remuneration At its meeting held on 2 March 2022, in the context of the equity interest still held by the  German government at this time and the remuneration restrictions thus applicable under the  framework agreement with the Economic Stabilisation Fund (ESF) the Supervisory Board  resolved once again to cancel the commitment to pay Executive Board members an annual  bonus and long-term variable remuneration for the 2022 financial year. At the same time,   the Supervisory Board set concrete targets for the Executive Board members in the context  of the Company’s management as in the previous year, both for the 2022 financial year   and for the current four-year period up to and including 2025. In view of the challenges, in  deviation from the remuneration system approved by the 2020 Annual General Meeting for  the year 2022 these targets are based on operating cash flow and net debt (instead of the  Adjusted EBIT margin and Adjusted ROCE). In line with the remuneration system, the Adjusted  ROCE over the four-year period and the relative total shareholder return by comparison with  DAX companies were the key criteria for the long-term target. The remuneration system  approved by the Annual General Meeting will therefore once again be temporarily suspended  for the 2022 financial year. | [9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0] | True     | {9.0}                    |\n|        185 |      8 | Following full repayment of the stabilisation funding in Germany in 2021 and the ESF’s sale  of its remaining equity interest in Deutsche Lufthansa AG in September, the conditions  imposed by the ESF – including a ban on payment of variable remuneration to the Executive  Board – no longer apply. In the context of the stabilisation of the Company’s economic   situation, at its meeting held on 8 December 2022 the Supervisory Board therefore decided  to return to the Executive Board remuneration system approved by the Annual General                                                                                                                                                                                                                                                                                                                

In [118]:
print(blocks[30:40].to_markdown())

|   block_nr |   page | text                                                                                                                                                                                                                  | font_size                 | accept   | font_size_set            |
|-----------:|-------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------|:---------|:-------------------------|
|         33 |      1 | Last page viewed                                                                                                                                                                                                      | [9.0]                     | True     | {9.0}                    |
|         34 |      1 | Internet   references                                                                                                                                                                                                 | [9.0, 9.0]                | True     | {9.0}                    |
|         35 |      1 | Cross references                                                                                                                                                                                                      | [9.0]                     | True     | {9.0}                    |
|         36 |      1 | LUFTHANSA GROUP ANNUAL REPORT 2022 1                                                                                                                                                                                  | [5.800000190734863, 7.5]  | False    | {5.800000190734863, 7.5} |
|         37 |      2 | The Lufthansa Group                                                                                                                                                                                                   | [13.5]                    | False    | {13.5}                   |
|         38 |      2 | The Lufthansa Group is an aviation group with operations worldwide.  |  It consists of the business segments   Passenger Airlines, Logistics, MRO and Catering, as well as Additional Businesses and Group Functions. | [14.0, 14.0]              | True     | {14.0}                   |
|         39 |      2 | T001   KEY FIGURES LUFTHANSA GROUP                                                                                                                                                                                    | [7.0, 7.0]                | False    | {7.0}                    |
|         41 |      2 | 2022  2021  Change  in %                                                                                                                                                                                              | [7.0, 7.0, 7.0, 7.0]      | False    | {7.0}                    |
|         42 |      2 | Revenue and result                                                                                                                                                                                                    | [7.0]                     | False    | {7.0}                    |
|         43 |      2 | Total revenue €m 32,770 16,811 95                                                                                                                                                                                     | [7.0, 7.0, 7.0, 7.0, 7.0] | False    | {7.0}                    |

In [143]:

import pandas as pd

def merge_runs(df,
               text_col="text",
               font_set_col="font_size_set",
               accept_col="accept",
               keep_cols=("row_id", "page")):
    """
    Merge consecutive rows that have:
      • accept == True
      • len(font_size_set) == 1
      • identical font_size_set values
    Concatenates the text of such runs (separated by a single space) and
    retains the first values encountered for all other columns
    listed in `keep_cols`.
    """
    if df.empty:
        return df

    # Make sure the DataFrame is in the original order
    df = df.reset_index(drop=True)

    merged_rows = []          # collect collapsed records here
    buffer = df.iloc[0].copy()  # row we are currently building

    for _, row in df.iloc[1:].iterrows():
        can_merge = (
            buffer[accept_col]                               # both rows accepted …
            and row[accept_col]
            and len(buffer[font_set_col]) == 1               # … each has one font size …
            and len(row[font_set_col]) == 1
            and buffer[font_set_col] == row[font_set_col]    # … and the size is the same
        )

        if can_merge:
            # Glue the texts together
            buffer[text_col] = f"{buffer[text_col]} {row[text_col]}"
            # Optional: accumulate the raw font-size list if you need it
            if "font_sizes" in df.columns:
                buffer["font_sizes"] = buffer.get("font_sizes", []) + row["font_sizes"]
        else:
            merged_rows.append(buffer)
            buffer = row.copy()         # start a new run

    merged_rows.append(buffer)          # add the final buffered record
    result = pd.DataFrame(merged_rows)

    # Keep only desired columns plus the ones we modified/need
    wanted = list(keep_cols) + [text_col, "font_sizes", font_set_col, accept_col]
    return result[[c for c in wanted if c in result.columns]].reset_index(drop=True)

In [144]:
blocks_merged = merge_runs(blocks)

In [1]:
blocks_merged

NameError: name 'blocks_merged' is not defined