In [1]:
import pandas as pd
import os
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

In [2]:
system_prompt_format = "You are a NLP assistant that cleans text that was extracted via OCR. Only return text that is in the output!"
prompt_format = "The following text was extracted via OCR. Please only extract the paragraph in it that describes the companies busines model. No Headers, tables, or text that does not contain information about the busines model.\n\nText: {text}"

In [3]:
def clean_description(
        text: str,
        temperature: float = 0.1
): 

    # Initialize LLM
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=temperature
    )

    # Prompt
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt_format),
        ("human", prompt_format)
    ])
    
    # Chain
    chain = prompt | llm

    # inputs
    input = {
        "text": text,
        }

    formatted_prompt = prompt.invoke(input)

    # Run
    response = chain.invoke(input)

    return formatted_prompt, response.content

In [4]:
ds_2_desc  = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview_with_description.csv")

In [5]:
ds_2_desc[pd.notna(ds_2_desc["Description"])].groupby("NACE_letter").size()

NACE_letter
A     4
C    17
F    32
J    18
K    20
N     4
dtype: int64

In [20]:
ds_2_desc.loc[pd.notna(ds_2_desc["Description"]), "Description_clean"] = ds_2_desc.loc[pd.notna(ds_2_desc["Description"]), "Description"].apply(clean_description)

In [22]:
ds_2_desc

,Unnamed: 0,Symbol,Description_page,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description,Description_clean
0,0,CA05335P1099,NaN,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1,NaN,NaN
1,1,JP3947800003,NaN,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1,NaN,NaN
2,2,ID1000167901,NaN,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,## Riwayat Singkat Perseroan\n\nThe Company at...,(messages=[SystemMessage(content='You are a NL...
3,3,JP3843250006,NaN,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1,NaN,NaN
4,4,VN000000VTQ6,NaN,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,3109,KYG4707P1054,NaN,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98,NaN,NaN
3110,3110,ZAE000015277,NaN,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,BRT-ZA,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3,NaN,NaN
3111,3111,NO0011013765,NaN,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,GIGA-NO,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3,NaN,NaN
3112,3112,FR0010776617,NaN,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,ALMER-FR,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3,NaN,NaN
3113,3113,ZAE000240198,NaN,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,SHG-ZA,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3,NaN,NaN

In [ ]:
ds_2_desc.loc[pd.notna(ds_2_desc["Description"]), "Description"]

In [27]:
ds_2_desc.loc[pd.notna(ds_2_desc["Description"]), "Description_clean"] = ds_2_desc.loc[pd.notna(ds_2_desc["Description"]), "Description_clean"].apply(lambda x: x[1])

In [ ]:
ds_2_desc

,Unnamed: 0,Symbol,Description_page,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description,Description_clean
0,0,CA05335P1099,NaN,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1,NaN,NaN
1,1,JP3947800003,NaN,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1,NaN,NaN
2,2,ID1000167901,NaN,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,## Riwayat Singkat Perseroan\n\nThe Company at...,PT Dharma Samudera Fishing Industries Tbk or '...
3,3,JP3843250006,NaN,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1,NaN,NaN
4,4,VN000000VTQ6,NaN,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,3109,KYG4707P1054,NaN,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98,NaN,NaN
3110,3110,ZAE000015277,NaN,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,BRT-ZA,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3,NaN,NaN
3111,3111,NO0011013765,NaN,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,GIGA-NO,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3,NaN,NaN
3112,3112,FR0010776617,NaN,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,ALMER-FR,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3,NaN,NaN
3113,3113,ZAE000240198,NaN,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,SHG-ZA,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3,NaN,NaN

In [29]:
ds_2_desc.to_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview_with_description.csv")