In [2]:
import pandas as pd
import glob
import os

In [29]:
ds_1 = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_1/reports_subset_from_full_data_1_overview.csv")

In [30]:
full_ds = pd.read_csv("fatimas-data/Security Data as of 2023-05-22.txt", sep="\t")

In [31]:
new_pdf_path = "projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_3"

In [32]:
pdfs_path = "fatimas-data/PDF"

In [33]:
pdfs = glob.glob(pdfs_path + "/*.pdf")

In [34]:
def get_level_1_nace(x):
    x = float(x)
    
    if 1 <= x <= 3.22:
        return 'A'
    elif 5 <= x <= 9.9:
        return 'B'
    elif 10 <= x <= 33.20:
        return 'C'
    elif 35 <= x <= 35.30:
        return 'D'
    elif 36 <= x <= 39:
        return 'E' 
    elif 41 <= x <= 43.99:
        return 'F'
    elif 45 <= x <= 47.99:
        return 'G'
    elif 49 <= x <= 53.2:
        return 'H'
    elif 55 <= x <= 56.3:
        return 'I'
    elif 58 <= x <= 63.99:
        return 'J'
    elif 64 <= x <= 66.3:
        return 'K'
    elif 68 <= x <= 68.32:
        return 'L'
    elif 69 <= x <= 75:
        return 'M' 
    elif 77 <= x <= 82.99:
        return 'N'
    elif 84 <= x <= 84.3:
        return 'O'
    elif 85 <= x <= 85.6:
        return 'P'
    elif 86 <= x <= 88.99:
        return 'Q'
    elif 90 <= x <= 93.29:
        return 'R'
    elif 94 <= x <= 96.09:
        return 'S' 
    elif 97 <= x <= 98.2:
        return 'T'
    elif x == 99:
        return 'U'
    else:
        return None

In [35]:
full_ds = full_ds[full_ds["Entity NACE Code"] != "@NA"]

In [36]:
full_ds["NACE_Letter"] = full_ds["Entity NACE Code"].apply(get_level_1_nace)

In [37]:
ds_1

,Unnamed: 0,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report
0,5789,ZW0009011041,Ariston Holdings Ltd.,1,1947.0,ZWE,V97772103,20090317.0,ZWE,@NA,...,ZW0009011041,603408,Ariston Holdings Ltd.,1.0,ARIS-ZW,1,SHARE,6034081,A,Ariston Holdings Ltd.1.pdf
1,35816,INE978A01027,Heritage Foods Limited,1,1992.0,IND,Y3179H146,20020117.0,IND,06FQLY-E,...,INE978A01027,BF2F40,Heritage Foods Limited,1.0,519552-IN,1,SHARE,BF2F405,A,Heritage Foods Limited1.pdf
2,80373,MYL7854OO002,Timberwell Bhd.,1,1996.0,MYS,Y88399103,19970516.0,MYS,05JH15-E,...,MYL7854OO002,690556,Timberwell Bhd.,1.0,7854-MY,1,SHARE,6905563,A,Timberwell Bhd.1.pdf
3,49813,MYQ0189OO009,Matang Bhd.,1,2015.0,MYS,Y58347108,20170117.0,MYS,@NA,...,MYQ0189OO009,BYYQB5,Matang Bhd.,1.0,0189-MY,1,SHARE,BYYQB53,A,Matang Bhd.2.pdf
4,73064,MYL4316OO005,Sin Heng Chan (Malaya) Bhd.,1,1962.0,MYS,Y80178109,19880324.0,MYS,05YMQ5-E,...,MYL4316OO005,681088,Sin Heng Chan (Malaya) Bhd.,1.0,4316-MY,1,SHARE,6810883,A,Sin Heng Chan (Malaya) Bhd.1.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1557,5783,US0404432025,Aristocrat Group Corp.,0,2011.0,USA,040443202,20120313.0,USA,00DDP9-E,...,US0404432025,04044320,Aristocrat Group Corp.,1.0,ASCC-US,1,SHARE,BWX6257,S,Aristocrat Group Corp.1.pdf
1558,73228,KYG816BW1095,Sino-Life Group Limited,1,2005.0,HKG,G816BW109,20090909.0,HKG,00C60C-E,...,KYG816BW1095,B409GR,Sino-Life Group Limited,1.0,8296-HK,1,SHARE,B409GR3,S,Sino-Life Group Limited1.pdf
1559,86319,KYG9477E1070,Water Oasis Group Limited,1,1998.0,HKG,G9477E107,20070905.0,HKG,00610B-E,...,KYG9477E1070,651233,Water Oasis Group Limited,1.0,WOSSF-US,0,SHARE,B02V9Q9,S,Water Oasis Group Limited1.pdf
1560,66027,US76119X1054,"Reservoir Media, Inc.",1,2007.0,USA,76119X105,20210105.0,USA,0NVYZ2-E,...,US76119X1054,76119X10,"Reservoir Media, Inc.",1.0,RSVR-US,1,SHARE,BP0B9H7,S,"Reservoir Media, Inc.1.pdf"
1561,38190,KYG4707P1054,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,@NA,...,KYG4707P1054,BJYFY1,Icon Culture Global Company Limited,1.0,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf

In [38]:
new_ds = full_ds.copy()

In [39]:
new_ds["Name"].apply(lambda x: x not in list(ds_1["Name"]))

0         True
1         True
2         True
3         True
4         True
          ...
113852    True
113853    True
113854    True
113855    True
113856    True
Name: Name, Length: 112801, dtype: bool

In [40]:
new_ds = new_ds[new_ds["Name"].apply(lambda x: x not in list(ds_1["Name"]))]

In [41]:
pdfs

['fatimas-data/PDF/&Do Holdings Co.Ltd.1.pdf',
 'fatimas-data/PDF/&Do Holdings Co.Ltd.3.pdf',
 'fatimas-data/PDF/01 Communique Laboratory Inc.2.pdf',
 'fatimas-data/PDF/01Cyberaton Proenergy SA1.pdf',
 'fatimas-data/PDF/1&1 AG2.pdf',
 'fatimas-data/PDF/1-800-FLOWERS.COM, Inc.1.pdf',
 'fatimas-data/PDF/10X Genomics, Inc.1.pdf',
 'fatimas-data/PDF/10X Genomics, Inc.2.pdf',
 'fatimas-data/PDF/11 88 0 Solutions AG1.pdf',
 'fatimas-data/PDF/11 Bit Studios SA1.pdf',
 'fatimas-data/PDF/11 Bit Studios SA2.pdf',
 'fatimas-data/PDF/11 PLC2.pdf',
 'fatimas-data/PDF/111, Inc.2.pdf',
 'fatimas-data/PDF/111, Inc.3.pdf',
 'fatimas-data/PDF/1414 Degrees Ltd.1.pdf',
 'fatimas-data/PDF/1606 Corp1.pdf',
 'fatimas-data/PDF/17 Education & Technology Group, Inc.1.pdf',
 'fatimas-data/PDF/1844 Resources Inc1.pdf',
 'fatimas-data/PDF/1867 Western Financial Corp.2.pdf',
 'fatimas-data/PDF/1895 Bancorp of Wisconsin Inc1.pdf',
 'fatimas-data/PDF/1911 Gold Corp.1.pdf',
 'fatimas-data/PDF/1933 Industries, Inc.1.pdf',
 'fatimas-data/PDF/1957 & Co. (Hospitality) Limited1.pdf',
 'fatimas-data/PDF/1957 & Co. (Hospitality) Limited2.pdf',
 'fatimas-data/PDF/1nKemia IUCT Group SA1.pdf',
 'fatimas-data/PDF/1Spatial PLC1.pdf',
 'fatimas-data/PDF/1Spatial PLC2.pdf',
 'fatimas-data/PDF/1st Group Ltd.1.pdf',
 'fatimas-data/PDF/1stdibs.com, Inc.1.pdf',
 'fatimas-data/PDF/1stdibs.com, Inc.2.pdf',
 'fatimas-data/PDF/1stdibs.com, Inc.3.pdf',
 'fatimas-data/PDF/20 Microns Limited1.pdf',
 'fatimas-data/PDF/2020 Bulkers Ltd.1.pdf',
 'fatimas-data/PDF/21Lady Co., Ltd.1.pdf',
 'fatimas-data/PDF/21Lady Co., Ltd.2.pdf',
 'fatimas-data/PDF/235 Holdings EAD1.pdf',
 'fatimas-data/PDF/23andMe Holding Co.1.pdf',
 'fatimas-data/PDF/24SevenOffice Group AB1.pdf',
 'fatimas-data/PDF/79 Resources Ltd1.pdf',
 'fatimas-data/PDF/79North Inc2.pdf',
 'fatimas-data/PDF/7C Solarparken AG1.pdf',
 'fatimas-data/PDF/7NR Retail Ltd.3.pdf',
 'fatimas-data/PDF/7Road Holdings Limited1.pdf',
 'fatimas-data/PDF/7Seas Entertainment Limited2.pdf',
 'fatimas-data/PDF/88 Energy Limited1.pdf',
 'fatimas-data/PDF/888 Holdings Plc1.pdf',
 'fatimas-data/PDF/8VI Holdings Ltd.1.pdf',
 'fatimas-data/PDF/8VI Holdings Ltd.2.pdf',
 'fatimas-data/PDF/8VI Holdings Ltd.3.pdf',
 'fatimas-data/PDF/9 Meters Biopharma, Inc.2.pdf',
 'fatimas-data/PDF/9 Spokes International Ltd.1.pdf',
 'fatimas-data/PDF/9 Spokes International Ltd.2.pdf',
 'fatimas-data/PDF/9 Spokes International Ltd.3.pdf',
 'fatimas-data/PDF/908 Devices Inc.2.pdf',
 'fatimas-data/PDF/91APP, Inc.1.pdf',
 'fatimas-data/PDF/9R Limited1.pdf',
 'fatimas-data/PDF/9R Limited3.pdf',
 'fatimas-data/PDF/A & S Group (Holdings) Limited1.pdf',
 'fatimas-data/PDF/A & S Group (Holdings) Limited3.pdf',
 'fatimas-data/PDF/A Brown Co., Inc.1.pdf',
 'fatimas-data/PDF/A Metaverse Company1.pdf',
 'fatimas-data/PDF/A Metaverse Company2.pdf',
 'fatimas-data/PDF/A SPAC II Acquisition Corp.1.pdf',
 'fatimas-data/PDF/A&D HOLON Holdings Company. Limited1.pdf',
 'fatimas-data/PDF/A&D HOLON Holdings Company. Limited2.pdf',
 "fatimas-data/PDF/A'ayan Leasing & Investment Co.3.pdf",
 "fatimas-data/PDF/A'ayan Real Estate Company2.pdf",
 "fatimas-data/PDF/A'ayan Real Estate Company3.pdf",
 "fatimas-data/PDF/A'Saffa Foods SAOG1.pdf",
 'fatimas-data/PDF/A-1 Acid Ltd.1.pdf',
 'fatimas-data/PDF/24SevenOffice Group AB3.pdf',
 'fatimas-data/PDF/29metals Ltd.1.pdf',
 'fatimas-data/PDF/29metals Ltd.2.pdf',
 'fatimas-data/PDF/29metals Ltd.3.pdf',
 'fatimas-data/PDF/2cureX AB1.pdf',
 'fatimas-data/PDF/2cureX AB2.pdf',
 'fatimas-data/PDF/2cureX AB3.pdf',
 'fatimas-data/PDF/2G ENERGY AG3.pdf',
 'fatimas-data/PDF/2S Metal Public Co. Ltd.3.pdf',
 'fatimas-data/PDF/3-D Matrix, Ltd.1.pdf',
 'fatimas-data/PDF/3-D Matrix, Ltd.2.pdf',
 'fatimas-data/PDF/333D Limited1.pdf',
 'fatimas-data/PDF/360 Capital Group1.pdf',
 'fatimas-data/PDF/360 Ludashi Holdings Limited1.pdf',
 'fatimas-data/PDF/361 Degrees International Ltd.1.pdf',
 'fatimas-data/PDF/37 Capital Incorporated1.pdf',
 'fatimas-data/PDF/374Water Inc1.pdf',
 'fatimas-data/PDF/3Cnergy Limited1.pdf',
 'fatimas-data/PDF/3Cnergy Limited3.pdf',
 'fatimas-data/PDF/3D Medicines, Inc.1.pdf',
 'fatimas-data/PDF/3D Oil Limited2.pdf',
 'fatimas-data/PDF/3D Oil Limited3.pdf',
 'fatimas-data/PDF/3D Systems Corporation1.pdf',
 'fatimas-data/PDF/3DX Industries Incorporated1.pdf',
 'fatimas-data/PDF/3i Infotech Limited1.pdf',
 'fatimas-data/PDF/3P Learning Ltd1.pdf',
 'fatimas-data/PDF/3P Learning Ltd2.pdf',
 'fatimas-data/PDF/3Power Energy Group Incorporated1.pdf',
 'fatimas-data/PDF/A-1 Group Incorporated1.pdf',
 'fatimas-data/PDF/A-JIN INDUSTRY CO.,LTD2.pdf',
 'fatimas-data/PDF/A-Living Smart City Services Co., Ltd.1.pdf',
 'fatimas-data/PDF/A-Mark Precious Metals, Inc.2.pdf',
 'fatimas-data/PDF/A-Rank Bhd.1.pdf',
 'fatimas-data/PDF/A-Rank Bhd.2.pdf',
 'fatimas-data/PDF/A-Smart Holdings Ltd.1.pdf',
 'fatimas-data/PDF/A-Smart Holdings Ltd.3.pdf',
 'fatimas-data/PDF/A-Sonic Aerospace Limited1.pdf',
 'fatimas-data/PDF/A-Sonic Aerospace Limited2.pdf',
 'fatimas-data/PDF/A. O. Smith Corporation1.pdf',
 'fatimas-data/PDF/A. Soriano Corp.1.pdf',
 'fatimas-data/PDF/A.B.P. Nocivelli S.p.A.1.pdf',
 'fatimas-data/PDF/A.D.Works Group Co.Ltd1.pdf',
 'fatimas-data/PDF/3SBio, Inc.1.pdf',
 'fatimas-data/PDF/3U HOLDING AG1.pdf',
 'fatimas-data/PDF/3U HOLDING AG2.pdf',
 'fatimas-data/PDF/3U HOLDING AG3.pdf',
 'fatimas-data/PDF/4 Global Plc1.pdf',
 'fatimas-data/PDF/40 Investment and Construction JSC1.pdf',
 'fatimas-data/PDF/40 Investment and Construction JSC2.pdf',
 'fatimas-data/PDF/4AIM SICAF S.p.A.1.pdf',
 'fatimas-data/PDF/4basebio PLC1.pdf',
 'fatimas-data/PDF/4C Group AB2.pdf',
 'fatimas-data/PDF/4DMedical Ltd.1.pdf',
 'fatimas-data/PDF/4DS Memory Ltd.1.pdf',
 'fatimas-data/PDF/4Front Ventures Corp.1.pdf',
 'fatimas-data/PDF/4Front Ventures Corp.3.pdf',
 'fatimas-data/PDF/4imprint Group plc1.pdf',
 'fatimas-data/PDF/4Science S.P.A.1.pdf',
 'fatimas-data/PDF/4Science S.P.A.2.pdf',
 'fatimas-data/PDF/A.G. BARR p.l.c.1.pdf',
 'fatimas-data/PDF/A.I. Champdany Industries Ltd.1.pdf',
 'fatimas-data/PDF/A.J. Plast Public Co., Ltd.1.pdf',
 'fatimas-data/PDF/A.J. Plast Public Co., Ltd.2.pdf',
 'fatimas-data/PDF/A.J. Plast Public Co., Ltd.3.pdf',
 'fatimas-data/PDF/a.k.a. Brands Holding Corp.2.pdf',
 'fatimas-data/PDF/A.L Prochoice Group Public Limited3.pdf',
 'fatimas-data/PDF/A.P. Moller - Maersk AS1.pdf',
 'fatimas-data/PDF/A.S. Creation Tapeten AG1.pdf',
 'fatimas-data/PDF/a2 Milk Company Limited1.pdf',
 'fatimas-data/PDF/a2 Milk Company Limited3.pdf',
 'fatimas-data/PDF/a2 Milk Company Ltd.1.pdf',
 'fatimas-data/PDF/a2 Milk Company Ltd.2.pdf',
 'fatimas-data/PDF/a2 Milk Company Ltd.3.pdf',
 'fatimas-data/PDF/A2B Australia Limited1.pdf',
 'fatimas-data/PDF/A2Z Smart Technologies Corp1.pdf',
 'fatimas-data/PDF/4Sight Holdings Ltd.1.pdf',
 'fatimas-data/PDF/51 Credit Card Inc.1.pdf',
 'fatimas-data/PDF/51 Credit Card Inc.2.pdf',
 'fatimas-data/PDF/51 Credit Card Inc.3.pdf',
 'fatimas-data/PDF/51Talk Online Education Group1.pdf',
 'fatimas-data/PDF/52 Weeks Entertainment Ltd.2.pdf',
 'fatimas-data/PDF/55 North Mining Inc.1.pdf',
 'fatimas-data/PDF/55 North Mining Inc.2.pdf',
 'fatimas-data/PDF/577 Investment Corporation1.pdf',
 'fatimas-data/PDF/5E Advanced Materials, Inc.2.pdf',
 'fatimas-data/PDF/5E Advanced Materials, Inc.3.pdf',
 'fatimas-data/PDF/5E Resources Limited1.pdf',
 'fatimas-data/PDF/5E Resources Limited3.pdf',
 'fatimas-data/PDF/5N Plus Inc.3.pdf',
 'fatimas-data/PDF/5th Planet Games AS2.pdf',
 'fatimas-data/PDF/5th Planet Games AS3.pdf',
 'fatimas-data/PDF/600 Group PLC1.pdf',
 'fatimas-data/PDF/7-Eleven Malaysia Holdings Bhd1.pdf',
 'fatimas-data/PDF/77 Bank, Ltd.1.pdf',
 'fatimas-data/PDF/77 Bank, Ltd.2.pdf',
 'fatimas-data/PDF/AAA Technologies Ltd.3.pdf',
 'fatimas-data/PDF/AAC Technologies Holdings Incorporated2.pdf',
 'fatimas-data/PDF/AAC Technologies Holdings Incorporated3.pdf',
 'fatimas-data/PDF/Aadhaar Ventures India Limited1.pdf',
 'fatimas-data/PDF/Aadi Industries Limited1.pdf',
 'fatimas-data/PDF/Aadi Industries Limited2.pdf',
 'fatimas-data/PDF/Aadi Industries Limited3.pdf',
 'fatimas-data/PDF/AAEON Technology Inc.1.pdf',
 'fatimas-data/PDF/AAGES S.A2.pdf',
 'fatimas-data/PDF/AAK AB1.pdf',
 'fatimas-data/PDF/AAK AB2.pdf',
 'fatimas-data/PDF/Aalberts N.V.1.pdf',
 'fatimas-data/PDF/Aallon Group Oyj1.pdf',
 'fatimas-data/PDF/Aallon Group Oyj2.pdf',
 'fatimas-data/PDF/AAN digital services Co.2.pdf',
 'fatimas-data/PDF/Aanchal Ispat Ltd.2.pdf',
 'fatimas-data/PDF/AAON, Inc.1.pdf',
 'fatimas-data/PDF/aap Implantate AG2.pdf',
 'fatimas-data/PDF/AAP, Inc.1.pdf',
 'fatimas-data/PDF/AAP, Inc.2.pdf',
 'fatimas-data/PDF/AAPICO Hitech Public Co. Ltd.1.pdf',
 'fatimas-data/PDF/AAR CORP.3.pdf',
 'fatimas-data/PDF/Aardvark Ventures, Inc.1.pdf',
 'fatimas-data/PDF/Aareal Bank AG1.pdf',
 'fatimas-data/PDF/Aareal Bank AG2.pdf',
 'fatimas-data/PDF/Aareal Bank AG3.pdf',
 'fatimas-data/PDF/Aarey Drugs & Pharmaceuticals Ltd.1.pdf',
 'fatimas-data/PDF/Aastamangalam Finance Limited1.pdf',
 'fatimas-data/PDF/Aayush Food & Herbs Ltd.2.pdf',
 'fatimas-data/PDF/AB Bank Limited1.pdf',
 'fatimas-data/PDF/AB Bank Limited3.pdf',
 'fatimas-data/PDF/AB Builders Group Limited2.pdf',
 'fatimas-data/PDF/AB Builders Group Limited3.pdf',
 'fatimas-data/PDF/Africa Energy Corporation2.pdf',
 'fatimas-data/PDF/Africa Prudential Plc1.pdf',
 'fatimas-data/PDF/Africa Prudential Plc3.pdf',
 'fatimas-data/PDF/Africa Resources AB1.pdf',
 'fatimas-data/PDF/African Alliance Insurance PLC1.pdf',
 'fatimas-data/PDF/African Alliance Insurance PLC2.pdf',
 'fatimas-data/PDF/African and Overseas Enterprises Limited1.pdf',
 'fatimas-data/PDF/African and Overseas Enterprises Limited2.pdf',
 'fatimas-data/PDF/African and Overseas Enterprises Limited3.pdf',
 'fatimas-data/PDF/African Dawn Capital Limited1.pdf',
 'fatimas-data/PDF/African Distillers Ltd.1.pdf',
 'fatimas-data/PDF/African Distillers Ltd.3.pdf',
 'fatimas-data/PDF/African Energy Metals Inc1.pdf',
 'fatimas-data/PDF/African Equity Empowerment Investments Limited3.pdf',
 'fatimas-data/PDF/African Export-Import Bank1.pdf',
 'fatimas-data/PDF/African Export-Import Bank2.pdf',
 'fatimas-data/PDF/African Export-Import Bank3.pdf',
 'fatimas-data/PDF/African Gold Acquisition Corp.1.pdf',
 'fatimas-data/PDF/African Gold Ltd.1.pdf',
 'fatimas-data/PDF/African Media Entertainment Limited1.pdf',
 'fatimas-data/PDF/African Minerals Limited1.pdf',
 'fatimas-data/PDF/African Minerals Limited3.pdf',
 'fatimas-data/PDF/African Pioneer PLC2.pdf',
 'fatimas-data/PDF/African Rainbow Capital Investments Ltd.1.pdf',
 'fatimas-data/PDF/African Rainbow Capital Investments Ltd.3.pdf',
 'fatimas-data/PDF/African Rainbow Minerals Limited1.pdf',
 'fatimas-data/PDF/African Rainbow Minerals Limited2.pdf',
 'fatimas-data/PDF/African Sun Limited1.pdf',
 'fatimas-data/PDF/African Sun Limited2.pdf',
 'fatimas-data/PDF/Africure Pharmaceuticals Ltd.1.pdf',
 'fatimas-data/PDF/Alerion CleanPower2.pdf',
 'fatimas-data/PDF/Alerus Financial Corporation1.pdf',
 'fatimas-data/PDF/Alexander & Baldwin, Inc.2.pdf',
 'fatimas-data/PDF/Alexander Forbes Group Holdings Limited1.pdf',
 'fatimas-data/PDF/Alexander Forbes Group Holdings Limited2.pdf',
 'fatimas-data/PDF/Alexander Stamps & Coin Ltd.1.pdf',
 "fatimas-data/PDF/Alexander's, Inc.1.pdf",
 'fatimas-data/PDF/Alexanderwerk AG1.pdf',
 'fatimas-data/PDF/Alexanderwerk AG2.pdf',
 'fatimas-data/PDF/Alexanderwerk AG3.pdf',
 'fatimas-data/PDF/Alexandria Pharmaceuticals1.pdf',
 'fatimas-data/PDF/Alexandria Containers & Goods1.pdf',
 'fatimas-data/PDF/Alexandria New Medical Center Company1.pdf',
 'fatimas-data/PDF/Alexandria Real Estate Equities, Inc.1.pdf',
 'fatimas-data/PDF/Alexium International Group Limited1.pdf',
 'fatimas-data/PDF/Alexium International Group Limited3.pdf',
 'fatimas-data/PDF/Alfa Ica (India) Limited1.pdf',
 'fatimas-data/PDF/Alfa Laval AB1.pdf',
 'fatimas-data/PDF/Alfa Laval AB2.pdf',
 'fatimas-data/PDF/Alfa Plam AD2.pdf',
 'fatimas-data/PDF/Alfa Plam AD3.pdf',
 'fatimas-data/PDF/ALFA Transformers Limited2.pdf',
 'fatimas-data/PDF/ALFA Transformers Limited3.pdf',
 'fatimas-data/PDF/Astro Resources NL1.pdf',
 'fatimas-data/PDF/Astro S.A.1.pdf',
 'fatimas-data/PDF/Astro S.A.2.pdf',
 'fatimas-data/PDF/Astrocast SA1.pdf',
 'fatimas-data/PDF/Astrocast SA2.pdf',
 'fatimas-data/PDF/Astron Corporation Ltd1.pdf',
 'fatimas-data/PDF/Astron Corporation Ltd3.pdf',
 'fatimas-data/PDF/Astronics Corporation2.pdf',
 'fatimas-data/PDF/Astronics Corporation3.pdf',
 'fatimas-data/PDF/AstroNova, Inc.1.pdf',
 'fatimas-data/PDF/Astrotech Corporation1.pdf',
 'fatimas-data/PDF/Astrum Financial Holdings Limited1.pdf',
 'fatimas-data/PDF/ASTURIANA DE LAMINADOS S.A1.pdf',
 'fatimas-data/PDF/ASTURIANA DE LAMINADOS S.A2.pdf',
 'fatimas-data/PDF/ASX Limited1.pdf',
 'fatimas-data/PDF/ASX Limited2.pdf',
 'fatimas-data/PDF/ASX Limited3.pdf',
 'fatimas-data/PDF/Asymchem Laboratories (Tianjin) Co., Ltd.1.pdf',
 'fatimas-data/PDF/Asymchem Laboratories (Tianjin) Co., Ltd.2.pdf',
 'fatimas-data/PDF/Austal Limited1.pdf',
 'fatimas-data/PDF/Austal Limited2.pdf',
 'fatimas-data/PDF/Austar Lifesciences Ltd.1.pdf',
 'fatimas-data/PDF/AustAsia Group Limited.2.pdf',
 'fatimas-data/PDF/AustChina Holdings Limited1.pdf',
 'fatimas-data/PDF/Austco Healthcare Limited1.pdf',
 'fatimas-data/PDF/Austco Healthcare Limited2.pdf',
 'fatimas-data/PDF/Austevoll Seafood ASA1.pdf',
 'fatimas-data/PDF/Austevoll Seafood ASA2.pdf',
 'fatimas-data/PDF/Austin Engineering Co. Ltd.1.pdf',
 'fatimas-data/PDF/Austin Engineering Co. Ltd.2.pdf',
 'fatimas-data/PDF/Austin Engineering Limited1.pdf',
 'fatimas-data/PDF/Austin Engineering Limited2.pdf',
 'fatimas-data/PDF/Austin Gold Corp.1.pdf',
 'fatimas-data/PDF/Austin Laz & Co. Plc2.pdf',
 'fatimas-data/PDF/Austin Metals Limited1.pdf',
 'fatimas-data/PDF/Austin Metals Limited2.pdf',
 'fatimas-data/PDF/Austpac Resources N.L.1.pdf',
 'fatimas-data/PDF/Austin Resources Limited1.pdf',
 'fatimas-data/PDF/Austin Resources Limited2.pdf',
 'fatimas-data/PDF/Austpac Resources N.L.2.pdf',
 'fatimas-data/PDF/Austral Gold Limited1.pdf',
 'fatimas-data/PDF/Austral Group SAA1.pdf',
 'fatimas-data/PDF/Austral Group SAA3.pdf',
 'fatimas-data/PDF/Austral Resources Australia Limited1.pdf',
 'fatimas-data/PDF/Australasian Metals Limited3.pdf',
 'fatimas-data/PDF/Australia & International Holdings Ltd1.pdf',
 'fatimas-data/PDF/Australia & International Holdings Ltd3.pdf',
 'fatimas-data/PDF/Australia United Mining Limited1.pdf',
 'fatimas-data/PDF/Australian Adventure Tourism Group Ltd.1.pdf',
 'fatimas-data/PDF/Australian Agricultural Company Limited1.pdf',
 'fatimas-data/PDF/Autins Group Plc1.pdf',
 'fatimas-data/PDF/Auto Hall SA1.pdf',
 'fatimas-data/PDF/Auto Hall SA2.pdf',
 'fatimas-data/PDF/Auto Italia Holdings Limited3.pdf',
 'fatimas-data/PDF/Auto Nejma1.pdf',
 'fatimas-data/PDF/Auto Partner SA2.pdf',
 'fatimas-data/PDF/Auto Parts 4Less Group, Inc.1.pdf',
 'fatimas-data/PDF/Auto Parts 4Less Group, Inc.2.pdf',
 'fatimas-data/PDF/Auto Pins (India) Ltd2.pdf',
 'fatimas-data/PDF/Auto Trader Group PLC1.pdf',
 'fatimas-data/PDF/Auto Trader Group PLC3.pdf',
 'fatimas-data/PDF/Auto Trader Group Plc1.pdf',
 'fatimas-data/PDF/Auto Trader Group Plc3.pdf',
 'fatimas-data/PDF/auto.de AG3.pdf',
 'fatimas-data/PDF/AUTO1 Group SE1.pdf',
 'fatimas-data/PDF/AUTO1 Group SE2.pdf',
 'fatimas-data/PDF/AutoCanada Inc.1.pdf',
 'fatimas-data/PDF/AutoCanada Inc.2.pdf',
 'fatimas-data/PDF/Autodesk, Inc.1.pdf',
 'fatimas-data/PDF/Autodesk, Inc.2.pdf',
 'fatimas-data/PDF/AB Klaipedos Nafta2.pdf',
 'fatimas-data/PDF/AB Sagax1.pdf',
 'fatimas-data/PDF/AB Science SA3.pdf',
 'fatimas-data/PDF/AB&T Financial Corporation2.pdf',
 'fatimas-data/PDF/Abacus Property Group1.pdf',
 'fatimas-data/PDF/Abacus Property Group3.pdf',
 'fatimas-data/PDF/Abalance Corp1.pdf',
 'fatimas-data/PDF/ABATE AS Industries Limited2.pdf',
 'fatimas-data/PDF/ABATE AS Industries Limited3.pdf',
 'fatimas-data/PDF/ABB India Limited1.pdf',
 'fatimas-data/PDF/ABB India Limited2.pdf',
 'fatimas-data/PDF/ABB Ltd.2.pdf',
 'fatimas-data/PDF/Abbey Mortgage Bank PLC1.pdf',
 'fatimas-data/PDF/Abbey Mortgage Bank PLC2.pdf',
 'fatimas-data/PDF/Abbisko Cayman Limited1.pdf',
 'fatimas-data/PDF/Abbott Laboratories Pakistan Limited3.pdf',
 'fatimas-data/PDF/AbbVie, Inc.2.pdf',
 'fatimas-data/PDF/ABC Motors Co. Ltd.1.pdf',
 'fatimas-data/PDF/abc Multiactive Limited2.pdf',
 'fatimas-data/PDF/ABC Technologies Holdings, Inc.1.pdf',
 'fatimas-data/PDF/ABC Technologies Holdings, Inc.2.pdf',
 'fatimas-data/PDF/ABC Transport Plc1.pdf',
 'fatimas-data/PDF/ABCAM PLC1.pdf',
 'fatimas-data/PDF/ABCAM PLC2.pdf',
 'fatimas-data/PDF/Abcam PLC1.pdf',
 'fatimas-data/PDF/Abcam PLC2.pdf',
 'fatimas-data/PDF/Acceler8 Ventures Plc2.pdf',
 'fatimas-data/PDF/Accelerate Diagnostics Corporation2.pdf',
 'fatimas-data/PDF/Accelerate Diagnostics Corporation3.pdf',
 'fatimas-data/PDF/Accelerate Property Fund Ltd.1.pdf',
 'fatimas-data/PDF/Accelerate Property Fund Ltd.2.pdf',
 'fatimas-data/PDF/Accelerate Resources Ltd.1.pdf',
 'fatimas-data/PDF/Accelerate Resources Ltd.2.pdf',
 'fatimas-data/PDF/Accelerate Resources Ltd.3.pdf',
 'fatimas-data/PDF/Acceleware Ltd.2.pdf',
 'fatimas-data/PDF/Accelleron Industries AG1.pdf',
 'fatimas-data/PDF/Accelleron Industries AG3.pdf',
 'fatimas-data/PDF/Accelya Solutions India Ltd.1.pdf',
 'fatimas-data/PDF/Accent Group Ltd1.pdf',
 'fatimas-data/PDF/Accent Group Ltd3.pdf',
 'fatimas-data/PDF/Accent Resources NL2.pdf',
 'fatimas-data/PDF/Accent Resources NL3.pdf',
 'fatimas-data/PDF/Accentis nv1.pdf',
 'fatimas-data/PDF/Accentis nv2.pdf',
 'fatimas-data/PDF/Accentro Real Estate AG1.pdf',
 'fatimas-data/PDF/Accentro Real Estate AG2.pdf',
 'fatimas-data/PDF/Accenture Plc1.pdf',
 'fatimas-data/PDF/Accenture Plc3.pdf',
 'fatimas-data/PDF/Accenture PLC1.pdf',
 'fatimas-data/PDF/Accenture PLC3.pdf',
 'fatimas-data/PDF/Access Bank Botswana Ltd.1.pdf',
 'fatimas-data/PDF/Access Bank Botswana Ltd.3.pdf',
 'fatimas-data/PDF/Access Bank Ghana PLC2.pdf',
 'fatimas-data/PDF/Access Co., Ltd.2.pdf',
 'fatimas-data/PDF/Access Engineering PLC2.pdf',
 'fatimas-data/PDF/Access Financial Services Ltd.1.pdf',
 'fatimas-data/PDF/Azkoyen, S.A.2.pdf',
 'fatimas-data/PDF/Azrieli Group Ltd.1.pdf',
 'fatimas-data/PDF/Azrieli Group Ltd.3.pdf',
 'fatimas-data/PDF/Aztech Global Ltd.1.pdf',
 'fatimas-data/PDF/Azucar Minerals Ltd.2.pdf',
 'fatimas-data/PDF/Azur Selection Plc1.pdf',
 'fatimas-data/PDF/Azur Selection Plc3.pdf',
 'fatimas-data/PDF/Azure Minerals Limited1.pdf',
 'fatimas-data/PDF/Azure Power Global Limited1.pdf',
 'fatimas-data/PDF/Azure Power Global Limited2.pdf',
 'fatimas-data/PDF/Azure Power Global Limited3.pdf',
 'fatimas-data/PDF/AZZ Inc.1.pdf',
 'fatimas-data/PDF/Abico Avy Co., Ltd.2.pdf',
 'fatimas-data/PDF/Abico Avy Co., Ltd.3.pdf',
 'fatimas-data/PDF/ABICO NetCom Co., Ltd.2.pdf',
 'fatimas-data/PDF/Ability Enterprise Co., Ltd.1.pdf',
 'fatimas-data/PDF/Ability Enterprise Co., Ltd.2.pdf',
 'fatimas-data/PDF/Ability, Inc.1.pdf',
 'fatimas-data/PDF/Ability, Inc.2.pdf',
 'fatimas-data/PDF/Abingdon Health PLC1.pdf',
 'fatimas-data/PDF/Abirami Financial Services (India) Limited3.pdf',
 'fatimas-data/PDF/Abitare In SpA1.pdf',
 'fatimas-data/PDF/Abitare In SpA2.pdf',
 'fatimas-data/PDF/ABL Diagnostics SA1.pdf',
 'fatimas-data/PDF/ABL Group ASA1.pdf',
 'fatimas-data/PDF/Able Energy, Inc.2.pdf',
 'fatimas-data/PDF/Able Engineering Holdings Ltd.2.pdf',
 'fatimas-data/PDF/Able Engineering Holdings Ltd.3.pdf',
 'fatimas-data/PDF/AbleGroup Bhd1.pdf',
 'fatimas-data/PDF/Abliva AB1.pdf',
 'fatimas-data/PDF/Abliva AB3.pdf',
 'fatimas-data/PDF/AbCellera Biologics, Inc.1.pdf',
 'fatimas-data/PDF/ABCO Energy, Inc.1.pdf',
 'fatimas-data/PDF/Abcourt Mines, Inc.1.pdf',
 'fatimas-data/PDF/Abdul Mohsen Al-Hokair Group for Tourism & Development Co.2.pdf',
 'fatimas-data/PDF/Abdullah Saad Mohammed Abo Moati for Bookstores Co.1.pdf',
 'fatimas-data/PDF/Abeona Therapeutics, Inc.2.pdf',
 'fatimas-data/PDF/Abera Bioscience AB1.pdf',

In [42]:
pdfs_names = [os.path.basename(pdf)[:-5] for pdf in pdfs]
pdfs_names

['&Do Holdings Co.Ltd.',
 '&Do Holdings Co.Ltd.',
 '01 Communique Laboratory Inc.',
 '01Cyberaton Proenergy SA',
 '1&1 AG',
 '1-800-FLOWERS.COM, Inc.',
 '10X Genomics, Inc.',
 '10X Genomics, Inc.',
 '11 88 0 Solutions AG',
 '11 Bit Studios SA',
 '11 Bit Studios SA',
 '11 PLC',
 '111, Inc.',
 '111, Inc.',
 '1414 Degrees Ltd.',
 '1606 Corp',
 '17 Education & Technology Group, Inc.',
 '1844 Resources Inc',
 '1867 Western Financial Corp.',
 '1895 Bancorp of Wisconsin Inc',
 '1911 Gold Corp.',
 '1933 Industries, Inc.',
 '1957 & Co. (Hospitality) Limited',
 '1957 & Co. (Hospitality) Limited',
 '1nKemia IUCT Group SA',
 '1Spatial PLC',
 '1Spatial PLC',
 '1st Group Ltd.',
 '1stdibs.com, Inc.',
 '1stdibs.com, Inc.',
 '1stdibs.com, Inc.',
 '20 Microns Limited',
 '2020 Bulkers Ltd.',
 '21Lady Co., Ltd.',
 '21Lady Co., Ltd.',
 '235 Holdings EAD',
 '23andMe Holding Co.',
 '24SevenOffice Group AB',
 '79 Resources Ltd',
 '79North Inc',
 '7C Solarparken AG',
 '7NR Retail Ltd.',
 '7Road Holdings Limited',
 '7Seas Entertainment Limited',
 '88 Energy Limited',
 '888 Holdings Plc',
 '8VI Holdings Ltd.',
 '8VI Holdings Ltd.',
 '8VI Holdings Ltd.',
 '9 Meters Biopharma, Inc.',
 '9 Spokes International Ltd.',
 '9 Spokes International Ltd.',
 '9 Spokes International Ltd.',
 '908 Devices Inc.',
 '91APP, Inc.',
 '9R Limited',
 '9R Limited',
 'A & S Group (Holdings) Limited',
 'A & S Group (Holdings) Limited',
 'A Brown Co., Inc.',
 'A Metaverse Company',
 'A Metaverse Company',
 'A SPAC II Acquisition Corp.',
 'A&D HOLON Holdings Company. Limited',
 'A&D HOLON Holdings Company. Limited',
 "A'ayan Leasing & Investment Co.",
 "A'ayan Real Estate Company",
 "A'ayan Real Estate Company",
 "A'Saffa Foods SAOG",
 'A-1 Acid Ltd.',
 '24SevenOffice Group AB',
 '29metals Ltd.',
 '29metals Ltd.',
 '29metals Ltd.',
 '2cureX AB',
 '2cureX AB',
 '2cureX AB',
 '2G ENERGY AG',
 '2S Metal Public Co. Ltd.',
 '3-D Matrix, Ltd.',
 '3-D Matrix, Ltd.',
 '333D Limited',
 '360 Capital Group',
 '360 Ludashi Holdings Limited',
 '361 Degrees International Ltd.',
 '37 Capital Incorporated',
 '374Water Inc',
 '3Cnergy Limited',
 '3Cnergy Limited',
 '3D Medicines, Inc.',
 '3D Oil Limited',
 '3D Oil Limited',
 '3D Systems Corporation',
 '3DX Industries Incorporated',
 '3i Infotech Limited',
 '3P Learning Ltd',
 '3P Learning Ltd',
 '3Power Energy Group Incorporated',
 'A-1 Group Incorporated',
 'A-JIN INDUSTRY CO.,LTD',
 'A-Living Smart City Services Co., Ltd.',
 'A-Mark Precious Metals, Inc.',
 'A-Rank Bhd.',
 'A-Rank Bhd.',
 'A-Smart Holdings Ltd.',
 'A-Smart Holdings Ltd.',
 'A-Sonic Aerospace Limited',
 'A-Sonic Aerospace Limited',
 'A. O. Smith Corporation',
 'A. Soriano Corp.',
 'A.B.P. Nocivelli S.p.A.',
 'A.D.Works Group Co.Ltd',
 '3SBio, Inc.',
 '3U HOLDING AG',
 '3U HOLDING AG',
 '3U HOLDING AG',
 '4 Global Plc',
 '40 Investment and Construction JSC',
 '40 Investment and Construction JSC',
 '4AIM SICAF S.p.A.',
 '4basebio PLC',
 '4C Group AB',
 '4DMedical Ltd.',
 '4DS Memory Ltd.',
 '4Front Ventures Corp.',
 '4Front Ventures Corp.',
 '4imprint Group plc',
 '4Science S.P.A.',
 '4Science S.P.A.',
 'A.G. BARR p.l.c.',
 'A.I. Champdany Industries Ltd.',
 'A.J. Plast Public Co., Ltd.',
 'A.J. Plast Public Co., Ltd.',
 'A.J. Plast Public Co., Ltd.',
 'a.k.a. Brands Holding Corp.',
 'A.L Prochoice Group Public Limited',
 'A.P. Moller - Maersk AS',
 'A.S. Creation Tapeten AG',
 'a2 Milk Company Limited',
 'a2 Milk Company Limited',
 'a2 Milk Company Ltd.',
 'a2 Milk Company Ltd.',
 'a2 Milk Company Ltd.',
 'A2B Australia Limited',
 'A2Z Smart Technologies Corp',
 '4Sight Holdings Ltd.',
 '51 Credit Card Inc.',
 '51 Credit Card Inc.',
 '51 Credit Card Inc.',
 '51Talk Online Education Group',
 '52 Weeks Entertainment Ltd.',
 '55 North Mining Inc.',
 '55 North Mining Inc.',
 '577 Investment Corporation',
 '5E Advanced Materials, Inc.',
 '5E Advanced Materials, Inc.',
 '5E Resources Limited',
 '5E Resources Limited',
 '5N Plus Inc.',
 '5th Planet Games AS',
 '5th Planet Games AS',
 '600 Group PLC',
 '7-Eleven Malaysia Holdings Bhd',
 '77 Bank, Ltd.',
 '77 Bank, Ltd.',
 'AAA Technologies Ltd.',
 'AAC Technologies Holdings Incorporated',
 'AAC Technologies Holdings Incorporated',
 'Aadhaar Ventures India Limited',
 'Aadi Industries Limited',
 'Aadi Industries Limited',
 'Aadi Industries Limited',
 'AAEON Technology Inc.',
 'AAGES S.A',
 'AAK AB',
 'AAK AB',
 'Aalberts N.V.',
 'Aallon Group Oyj',
 'Aallon Group Oyj',
 'AAN digital services Co.',
 'Aanchal Ispat Ltd.',
 'AAON, Inc.',
 'aap Implantate AG',
 'AAP, Inc.',
 'AAP, Inc.',
 'AAPICO Hitech Public Co. Ltd.',
 'AAR CORP.',
 'Aardvark Ventures, Inc.',
 'Aareal Bank AG',
 'Aareal Bank AG',
 'Aareal Bank AG',
 'Aarey Drugs & Pharmaceuticals Ltd.',
 'Aastamangalam Finance Limited',
 'Aayush Food & Herbs Ltd.',
 'AB Bank Limited',
 'AB Bank Limited',
 'AB Builders Group Limited',
 'AB Builders Group Limited',
 'Africa Energy Corporation',
 'Africa Prudential Plc',
 'Africa Prudential Plc',
 'Africa Resources AB',
 'African Alliance Insurance PLC',
 'African Alliance Insurance PLC',
 'African and Overseas Enterprises Limited',
 'African and Overseas Enterprises Limited',
 'African and Overseas Enterprises Limited',
 'African Dawn Capital Limited',
 'African Distillers Ltd.',
 'African Distillers Ltd.',
 'African Energy Metals Inc',
 'African Equity Empowerment Investments Limited',
 'African Export-Import Bank',
 'African Export-Import Bank',
 'African Export-Import Bank',
 'African Gold Acquisition Corp.',
 'African Gold Ltd.',
 'African Media Entertainment Limited',
 'African Minerals Limited',
 'African Minerals Limited',
 'African Pioneer PLC',
 'African Rainbow Capital Investments Ltd.',
 'African Rainbow Capital Investments Ltd.',
 'African Rainbow Minerals Limited',
 'African Rainbow Minerals Limited',
 'African Sun Limited',
 'African Sun Limited',
 'Africure Pharmaceuticals Ltd.',
 'Alerion CleanPower',
 'Alerus Financial Corporation',
 'Alexander & Baldwin, Inc.',
 'Alexander Forbes Group Holdings Limited',
 'Alexander Forbes Group Holdings Limited',
 'Alexander Stamps & Coin Ltd.',
 "Alexander's, Inc.",
 'Alexanderwerk AG',
 'Alexanderwerk AG',
 'Alexanderwerk AG',
 'Alexandria Pharmaceuticals',
 'Alexandria Containers & Goods',
 'Alexandria New Medical Center Company',
 'Alexandria Real Estate Equities, Inc.',
 'Alexium International Group Limited',
 'Alexium International Group Limited',
 'Alfa Ica (India) Limited',
 'Alfa Laval AB',
 'Alfa Laval AB',
 'Alfa Plam AD',
 'Alfa Plam AD',
 'ALFA Transformers Limited',
 'ALFA Transformers Limited',
 'Astro Resources NL',
 'Astro S.A.',
 'Astro S.A.',
 'Astrocast SA',
 'Astrocast SA',
 'Astron Corporation Ltd',
 'Astron Corporation Ltd',
 'Astronics Corporation',
 'Astronics Corporation',
 'AstroNova, Inc.',
 'Astrotech Corporation',
 'Astrum Financial Holdings Limited',
 'ASTURIANA DE LAMINADOS S.A',
 'ASTURIANA DE LAMINADOS S.A',
 'ASX Limited',
 'ASX Limited',
 'ASX Limited',
 'Asymchem Laboratories (Tianjin) Co., Ltd.',
 'Asymchem Laboratories (Tianjin) Co., Ltd.',
 'Austal Limited',
 'Austal Limited',
 'Austar Lifesciences Ltd.',
 'AustAsia Group Limited.',
 'AustChina Holdings Limited',
 'Austco Healthcare Limited',
 'Austco Healthcare Limited',
 'Austevoll Seafood ASA',
 'Austevoll Seafood ASA',
 'Austin Engineering Co. Ltd.',
 'Austin Engineering Co. Ltd.',
 'Austin Engineering Limited',
 'Austin Engineering Limited',
 'Austin Gold Corp.',
 'Austin Laz & Co. Plc',
 'Austin Metals Limited',
 'Austin Metals Limited',
 'Austpac Resources N.L.',
 'Austin Resources Limited',
 'Austin Resources Limited',
 'Austpac Resources N.L.',
 'Austral Gold Limited',
 'Austral Group SAA',
 'Austral Group SAA',
 'Austral Resources Australia Limited',
 'Australasian Metals Limited',
 'Australia & International Holdings Ltd',
 'Australia & International Holdings Ltd',
 'Australia United Mining Limited',
 'Australian Adventure Tourism Group Ltd.',
 'Australian Agricultural Company Limited',
 'Autins Group Plc',
 'Auto Hall SA',
 'Auto Hall SA',
 'Auto Italia Holdings Limited',
 'Auto Nejma',
 'Auto Partner SA',
 'Auto Parts 4Less Group, Inc.',
 'Auto Parts 4Less Group, Inc.',
 'Auto Pins (India) Ltd',
 'Auto Trader Group PLC',
 'Auto Trader Group PLC',
 'Auto Trader Group Plc',
 'Auto Trader Group Plc',
 'auto.de AG',
 'AUTO1 Group SE',
 'AUTO1 Group SE',
 'AutoCanada Inc.',
 'AutoCanada Inc.',
 'Autodesk, Inc.',
 'Autodesk, Inc.',
 'AB Klaipedos Nafta',
 'AB Sagax',
 'AB Science SA',
 'AB&T Financial Corporation',
 'Abacus Property Group',
 'Abacus Property Group',
 'Abalance Corp',
 'ABATE AS Industries Limited',
 'ABATE AS Industries Limited',
 'ABB India Limited',
 'ABB India Limited',
 'ABB Ltd.',
 'Abbey Mortgage Bank PLC',
 'Abbey Mortgage Bank PLC',
 'Abbisko Cayman Limited',
 'Abbott Laboratories Pakistan Limited',
 'AbbVie, Inc.',
 'ABC Motors Co. Ltd.',
 'abc Multiactive Limited',
 'ABC Technologies Holdings, Inc.',
 'ABC Technologies Holdings, Inc.',
 'ABC Transport Plc',
 'ABCAM PLC',
 'ABCAM PLC',
 'Abcam PLC',
 'Abcam PLC',
 'Acceler8 Ventures Plc',
 'Accelerate Diagnostics Corporation',
 'Accelerate Diagnostics Corporation',
 'Accelerate Property Fund Ltd.',
 'Accelerate Property Fund Ltd.',
 'Accelerate Resources Ltd.',
 'Accelerate Resources Ltd.',
 'Accelerate Resources Ltd.',
 'Acceleware Ltd.',
 'Accelleron Industries AG',
 'Accelleron Industries AG',
 'Accelya Solutions India Ltd.',
 'Accent Group Ltd',
 'Accent Group Ltd',
 'Accent Resources NL',
 'Accent Resources NL',
 'Accentis nv',
 'Accentis nv',
 'Accentro Real Estate AG',
 'Accentro Real Estate AG',
 'Accenture Plc',
 'Accenture Plc',
 'Accenture PLC',
 'Accenture PLC',
 'Access Bank Botswana Ltd.',
 'Access Bank Botswana Ltd.',
 'Access Bank Ghana PLC',
 'Access Co., Ltd.',
 'Access Engineering PLC',
 'Access Financial Services Ltd.',
 'Azkoyen, S.A.',
 'Azrieli Group Ltd.',
 'Azrieli Group Ltd.',
 'Aztech Global Ltd.',
 'Azucar Minerals Ltd.',
 'Azur Selection Plc',
 'Azur Selection Plc',
 'Azure Minerals Limited',
 'Azure Power Global Limited',
 'Azure Power Global Limited',
 'Azure Power Global Limited',
 'AZZ Inc.',
 'Abico Avy Co., Ltd.',
 'Abico Avy Co., Ltd.',
 'ABICO NetCom Co., Ltd.',
 'Ability Enterprise Co., Ltd.',
 'Ability Enterprise Co., Ltd.',
 'Ability, Inc.',
 'Ability, Inc.',
 'Abingdon Health PLC',
 'Abirami Financial Services (India) Limited',
 'Abitare In SpA',
 'Abitare In SpA',
 'ABL Diagnostics SA',
 'ABL Group ASA',
 'Able Energy, Inc.',
 'Able Engineering Holdings Ltd.',
 'Able Engineering Holdings Ltd.',
 'AbleGroup Bhd',
 'Abliva AB',
 'Abliva AB',
 'AbCellera Biologics, Inc.',
 'ABCO Energy, Inc.',
 'Abcourt Mines, Inc.',
 'Abdul Mohsen Al-Hokair Group for Tourism & Development Co.',
 'Abdullah Saad Mohammed Abo Moati for Bookstores Co.',
 'Abeona Therapeutics, Inc.',
 'Abera Bioscience AB',
 'Abera Bioscience AB',
 'Abera Bioscience AB',
 'Aberdeen International Incorporated',
 'ABG Sundal Collier Holding ASA',
 'ABG Sundal Collier Holding ASA',
 'Abhinav Leasing & Finance Ltd.',
 'Abhishek Corp. Ltd.',
 'Abhishek Corp. Ltd.',
 'Abhishek Finlease Ltd.',
 'ABN Systems International SA',
 'ABO Wind AG',
 'ABO-Group Environment NV',
 'Aboitiz Power Corp.',
 'Abraj Energy Services SAOG',
 'AbraSilver Resource Corp',
 'abrdn Property Income Trust Limited',
 'Abri SPAC I, Inc.',
 'ABS-CBN Holdings Corporation',
 'Absa Bank Botswana Limited',
 'Amanat Holding PJSC',
 'Amani Gold Limited',
 'Amani Gold Limited',
 'Amar Finance & Leasing Co. KSCC',
 'Amara Holdings Limited',
 'Amarc Resources Ltd.',
 'Amarin Corporation Plc',
 'Amarin Printing & Publishing Public Co., Ltd.',
 'Amarin Printing & Publishing Public Co., Ltd.',
 'Amarnath Securities Ltd.',
 'Amaroq Minerals Ltd',
 'Amaroq Minerals Ltd',
 'Amasse Capital Holdings Ltd.',
 'Amata Corp. Public Co., Ltd.',
 'Amata Summit Growth Freehold and Leasehold Real Estate Investment Trust',
 'Amata Vn Public Company Ltd',
 'Amata Vn Public Company Ltd',
 'Amatheon Agri Holding NV',
 'Amatheon Agri Holding NV',
 'Amazing Microelectronic Corp.',
 'Amazing Microelectronic Corp.',
 'Birla Precision Technologies Limited',
 'Birla Precision Technologies Limited',
 'Birla Tyres Ltd',
 'Birlasoft Limited',
 'Birmingham Sports Holdings Limited',
 'Birmingham Sports Holdings Limited',
 'Bisalloy Steel Group Limited',
 'Bison Electronics Inc.',
 'Bison Finance Group Limited',
 'Bit Brother Limited',
 'BIT Mining Limited',
 'BIT Mining Limited',
 'Bitcoin Group SE',
 'Bitcoin Group SE',
 'Bitcoin Well Inc',
 'Absa Bank Kenya Plc',
 'ABSA Bank Ltd.',
 'ABSA Bank Ltd.',
 'Absa Group Limited',
 'Absolute Clean Energy PCL',
 'Absolute Software Corporation',
 'Absolute Health & Fitness Incorporated',
 'Abu Dhabi Aviation',
 'Abu Dhabi Commercial Bank',
 'Abu Dhabi Commercial Bank',
 'Abu Dhabi National Oil Company for Distribution PJSC',
 'Abu Dhabi National Oil Company for Distribution PJSC',
 'Abu Dhabi National Takaful Company - P S C - Takaful',
 'Abu Dhabi National Takaful Company - P S C - Takaful',
 'Abu Dhabi National Takaful Company - P S C - Takaful',
 'Abundance International Limited',
 'Abundance International Limited',
 'ABVC BioPharma, Inc.',
 'ABVC BioPharma, Inc.',
 'ABVC BioPharma, Inc.',
 'ABx Group Limited',
 'ABx Group Limited',
 'ABx Group Limited',
 'Abyaar Real Estate Development Co. (K.S.C.)',
 'Anhui Sunhere Pharmaceutical Excipients Co., Ltd.',
 'Anhui Tongguan Copper Foil Group Co., Ltd.',
 'Bitfarms Ltd',
 'Bittium Oyj',
 'Bittium Oyj',
 'Bittnet Systems SA',
 'BiVictriX Therapeutics PLC',
 'BizLink Holding Inc.',
 "BJ's Restaurants, Inc.",
 "BJ's Restaurants, Inc.",
 "BJ's Wholesale Club Holdings, Inc.",
 "BJ's Wholesale Club Holdings, Inc.",
 'BJC Heavy Industries Public Company Ltd',
 'BJC Heavy Industries Public Company Ltd',
 'Bjorn Borg AB',
 'Bjorn Borg AB',
 'Bjorn Borg AB',
 'AC Immune SA',
 'AC Partners, Inc.',
 'Academies Australasia Group Limited',
 'Academy of Learning Co.',
 'Academy Press PLC',
 'Academy Sports and Outdoors, Inc.',
 'Acadia Healthcare Company, Inc.',
 'ACADIA Pharmaceuticals Inc.',
 'Acadian Timber Corp.',
 'Acanthe Developpement SA',
 'Acarix AB',
 'Acarix AB',
 'Acast AB',
 'Acast AB',
 'Acasti Pharma Inc.',
 'AcBel Polytech Inc.',
 'Accedere Ltd',
 'Accedere Ltd',
 'Accel Entertainment, Inc.',
 'Accel Group Holdings Limited',
 'BK Technologies Corp.',
 'BKV Industries Limited',
 'BKW AG',
 'BKW AG',
 'BKW AG',
 'Black Bird Biotech Inc',
 'Black Box Limited',
 'Black Cat Syndicate Ltd.',
 'Black Diamond Group Limited',
 'Black Diamond Group Limited',
 'Black Diamond Therapeutics, Inc.',
 'Black Dragon Resource Cos Incorporated',
 'Black Mammoth Metals Corporation',
 'Black Mountain Acquisition Corp.',
 'Black Mountain Energy Ltd.',
 'Black Pearl Group Limited',
 'Black Pearl SA',
 'Black Pearl SA',
 'Black Rock Mining Limited',
 'Black Rock Mining Limited',
 'Black Rock Petroleum Co',
 'Carrols Restaurant Group Inc',
 'Cars.com, Inc.',
 'Carsales.Com Limited',
 'Carsales.Com Limited',
 'CARsgen Therapeutics Holdings Ltd.',
 'Carter Bankshares, Inc.',
 "Carter's Incorporated",
 "Carter's Incorporated",
 'Cartier Resources Incorporated',
 'Cartier Silver Corporation',
 'Carvana Co.',
 'Carvana Co.',
 'Carver Bancorp Inc.',
 'Carzo Holdings Bhd.',
 'CDON AB',
 'CDRL S.A.',
 'CDTi Advanced Materials, Inc.',
 'CDW Corporation',
 'CDW Corporation',
 'CDW Holding Limited',
 'CE Technology Bhd.',
 'Ceapro Inc.',
 'Ceapro Inc.',
 'CEAT Limited',
 'Cebu Landmasters, Inc.',
 'CECEP Techand Ecology and Environment Co., Ltd.',
 'Bank Millennium SA',
 'Bank Muscat SAOG',
 'Bank Nizwa SAOG',
 'Bank Ochrony Srodowiska S.A.',
 'Bank of Africa - Benin SA',
 'Bank of Africa - Benin SA',
 'Bank of Africa - Benin SA',
 "Bank of Africa Cote d'Ivoire",
 'Bank of Africa Mali',
 'Bank of Africa Mali',
 'Bank of Africa Mali',
 'Bank of Africa Niger',
 'Bank of Africa Niger',
 'Bank of Africa Niger',
 'Bank of Africa Senegal',
 'Bank of Africa Senegal',
 'Bank of Africa-Burkina Faso SA',
 'Bank of Africa-Burkina Faso SA',
 'Bank of America Corp',
 'Bank of America Corp',
 'Bank of Baghdad',
 'Bank of Baroda (Uganda) Ltd.',
 'Bank of Baroda (Uganda) Ltd.',
 'Bank of Beijing Co., Ltd.',
 'Bank of Beijing Co., Ltd.',
 'Bank of Beijing Co., Ltd.',
 'Bank of Beirut sal',
 'Bank of Changsha Co., Ltd.',
 'Bank of Changsha Co., Ltd.',
 'Bank of Chengdu Co., Ltd.',
 'Bank of Chengdu Co., Ltd.',
 'Bank of Chengdu Co., Ltd.',
 'Bank of China Limited',
 'Bank of China Limited',
 'Bank of Chongqing Co., Ltd.',
 'Bank of Commerce',
 'Bank of Communications Co., Ltd.',
 'Bank of Communications Co., Ltd.',
 'Bank of Communications Co., Ltd.',
 'Bank of East Asia Ltd.',
 'Casa Holdings Limited',
 'Casa Holdings Limited',
 'Casa Minerals, Inc.',
 'Casablanca Group Ltd.',
 'Cascade Copper Corp.',
 'Cascade Copper Corp.',
 'Cascadero Copper Corp.',
 'Cascades Inc.',
 'Cascades Inc.',
 'Cascadia Acquisition Corp.',
 'Cascadia Acquisition Corp.',
 'Cascadia Blockchain Group Corp.',
 'Case Group AB',
 'Case Group AB',
 'Cash Converters International Limited',
 'CASH Financial Services Group Ltd',
 'Cashbuild Limited',
 'Cashbuild Limited',
 'China Biotech Services Holdings Limited',
 'China BlueChemical Ltd.',
 'CHINA BOHAI BANK CO., LTD.',
 'China Boqi Environmental (Holding) Co. Ltd.',
 'China Boqi Environmental (Holding) Co. Ltd.',
 'China Boton Group Co., Ltd.',
 'China Bozza Development Holdings Limited',
 'China Bright Culture Group',
 'China Brilliant Global Limited',
 'China Carbon Graphite Group Incorporated',
 'China Carbon Neutral Development Group Limited',
 'China Catalyst Holding Co., Ltd.',
 'China Chang Jiang Mining & New Energy Co. Ltd.',
 'China Chemical & Pharmaceutical Co., Ltd.',
 'China Chemical & Pharmaceutical Co., Ltd.',
 'China Chemical Corporation',
 'China Chemical Corporation',
 'China Chemical Corporation',
 'China Chunlai Education Group Co., Ltd.',
 'Bank First Corp',
 'China Cinda Asset Management Co., Ltd.',
 'China CITIC Bank Corporation Ltd',
 'China City Infrastructure Group Limited',
 'China City Infrastructure Group Limited',
 'China Environment Limited',
 'China Environment Limited',
 'China Environmental Energy Investment Limited',
 'China Environmental Energy Investment Limited',
 'China Environmental Resources Group Limited',
 'China Environmental Technology and Bioenergy Holdings Limited',
 'China Environmental Technology Holdings Limited',
 'China Environmental Technology Holdings Limited',
 'China Ever Grand Financial Leasing Group Co., Ltd.',
 'China Ever Grand Financial Leasing Group Co., Ltd.',
 'China Everbright Bank Co., Ltd.',
 'China Everbright Environment Group Limited',
 'China Everbright Environment Group Limited',
 'China Everbright Greentech Ltd.',
 'China Everbright Greentech Ltd.',
 'China Everbright Limited',
 'China Everbright Water Limited',
 'China Evergrande Group',
 'China Evergrande Group',
 'China Evergrande Group',
 'China Evergrande New Energy Vehicle Group Ltd.',
 'China Evergrande New Energy Vehicle Group Ltd.',
 'China Express Airlines Co., Ltd.',
 'China Express Airlines Co., Ltd.',
 'China Fangda Group Co., Ltd.',
 'China Feihe Limited',
 'China Film Co., Ltd.',
 'China Finance Investment Holdings Limited',
 'China Finance Online Co., Ltd.',
 'China Finance Online Co., Ltd.',
 'China Finance Incorporated',
 'China Financial International Investments Limited',
 'China Financial Leasing Group Ltd',
 'China Financial Services Holdings Limited',
 'China First Capital Group Ltd.',
 'China First Heavy Industries',
 'Ceridian HCM Holding, Inc.',
 'Ceridian HCM Holding, Inc.',
 'Cerillion Plc',
 'Cerrado Gold Inc',
 'Cerrado Gold Inc',
 'Cerro Grande Mining Corporation',
 'Cerus Corporation',
 'CES Energy Solutions Corp',
 'CES Energy Solutions Corp',
 'CES Synergies Incorporated',
 'CES Synergies Incorporated',
 'Cessatech AS',
 'Cessatech AS',
 'Cessatech AS',
 'Cetc Potevio Science & Technology Co., Ltd.',
 'Cettire Ltd.',
 'Cettire Ltd.',

In [43]:
"Heritage Foods Limited" in pdfs_names

True

In [44]:
new_ds["Name"]

0                  &Do Holdings Co.Ltd.
1                   (I.Z.) Queenco Ltd.
2                           00NATION AS
3         01 Communique Laboratory Inc.
4         01 Communique Laboratory Inc.
                      ...
113852                              @NA
113853                              @NA
113854                              @NA
113855                              @NA
113856                              @NA
Name: Name, Length: 109897, dtype: object

In [45]:
f = lambda x: (x in pdfs_names)
new_ds = new_ds[new_ds["Name"].apply(f)]

In [46]:
new_ds

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,Entity NACE Code,...,FE Ticker,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_Letter
0,JP3765420009,&Do Holdings Co.Ltd.,1,1991.0,JPN,J23362106,20150325.0,JPN,08ZVB2-E,68.31,...,3457-JP,JP3765420009,BVF9ZF,&Do Holdings Co.Ltd.,1.0,3457-JP,1,SHARE,BVF9ZF8,L
3,CA67088Q1063,01 Communique Laboratory Inc.,1,1992.0,CAN,67088Q106,20120731.0,CAN,@NA,58.29,...,@NA,CA67088Q1063,256289,01 Communique Laboratory Inc.,1.0,OONEF-US,0,SHARE,B3BJBF8,J
4,CA67088Q1063,01 Communique Laboratory Inc.,1,1992.0,CAN,67088Q106,20000308.0,CAN,@NA,58.29,...,ONE-CA,CA67088Q1063,256289,01 Communique Laboratory Inc.,1.0,ONE-CA,1,SHARE,2562898,J
6,PLVCAOC00015,01Cyberaton Proenergy SA,1,2007.0,POL,X989BK101,20080701.0,POL,@NA,69.20,...,@NA,PLVCAOC00015,B2QVXT,01Cyberaton Proenergy SA,1.0,01C-PL,1,SHARE,B2QVXT0,M
10,DE0005545503,1&1 AG,1,2002.0,DEU,D5934B101,19980423.0,DEU,@NA,61.20,...,1U1-DE,DE0005545503,573467,1&1 AG,1.0,1U1-DE,1,SHARE,5734672,J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90634,FDS21G19,Zymeworks Inc.,1,2003.0,USA,FDS21G196,NaN,USA,@NA,21.20,...,@NA,@NA,98985Y10,Zymeworks Inc.,1.0,@NA,0,SHARE,@NA,C
90635,US98985Y1082,Zymeworks Inc.,1,2003.0,USA,98985Y108,20170428.0,USA,@NA,21.20,...,ZYME-US,US98985Y1082,98985Y10,Zymeworks Inc.,1.0,ZYME-US,1,SHARE,BPCQZY9,C
90637,US98986M1036,"Zynex, Inc.",1,1996.0,USA,98986M103,20000613.0,USA,002LCW-E,26.60,...,ZYXI-US,US98986M1036,98986M10,"Zynex, Inc.",1.0,ZYXI-US,1,SHARE,2226042,C
90641,GB0006971013,Zytronic plc,1,1999.0,GBR,G98997102,20000706.0,GBR,05JDZN-E,26.20,...,ZYT-GB,GB0006971013,069710,Zytronic plc,1.0,ZYT-GB,1,SHARE,0697101,C
90643,US98880P2020,"ZZLL Information Technology, Inc.",1,2005.0,USA,98880P202,20070920.0,HKG,008CLG-E,47.91,...,@NA,US98880P2020,98880P20,"ZZLL Information Technology, Inc.",1.0,ZZLL-US,1,SHARE,BYZ2H41,G

In [47]:
new_ds.groupby("NACE_Letter").count()

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,Entity NACE Code,Exchange Name (FS),FE Ticker,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL
NACE_Letter,,,,,,,,,,,,,,,,,,,,
A,274,274,274,271,274,274,255,274,274,274,274,274,274,274,274,274,274,274,274,274
B,3443,3443,3443,3304,3443,3443,3292,3443,3443,3443,3443,3443,3443,3443,3443,3443,3443,3443,3443,3443
C,10672,10672,10672,10522,10672,10672,10027,10672,10672,10672,10672,10672,10672,10672,10672,10672,10672,10672,10672,10672
D,544,544,544,541,544,544,492,544,544,544,544,544,544,544,544,544,544,544,544,544
E,102,102,102,101,102,102,94,102,102,102,102,102,102,102,102,102,102,102,102,102
F,667,667,667,655,667,667,629,667,667,667,667,667,667,667,667,667,667,667,667,667
G,1810,1810,1810,1782,1810,1810,1704,1810,1810,1810,1810,1810,1810,1810,1810,1810,1810,1810,1810,1810
H,704,704,704,698,704,704,653,704,704,704,704,704,704,704,704,704,704,704,704,704
I,340,340,340,331,340,340,322,340,340,340,340,340,340,340,340,340,340,340,340,340
J,2633,2633,2633,2594,2633,2633,2406,2633,2633,2633,2633,2633,2633,2633,2633,2633,2633,2633,2633,2633
K,3927,3927,3927,3776,3927,3927,3604,3927,3927,3927,3927,3927,3927,3927,3927,3927,3927,3927,3927,3927
L,1914,1914,1914,1853,1914,1914,1782,1914,1914,1914,1914,1914,1914,1914,1914,1914,1914,1914,1914,1914
M,591,591,591,573,591,591,548,591,591,591,591,591,591,591,591,591,591,591,591,591
N,522,522,522,513,522,522,491,522,522,522,522,522,522,522,522,522,522,522,522,522
P,74,74,74,70,74,74,69,74,74,74,74,74,74,74,74,74,74,74,74,74
Q,235,235,235,223,235,235,228,235,235,235,235,235,235,235,235,235,235,235,235,235
R,113,113,113,109,113,113,106,113,113,113,113,113,113,113,113,113,113,113,113,113
S,43,43,43,43,43,43,38,43,43,43,43,43,43,43,43,43,43,43,43,43

In [48]:
a = lambda x: [os.path.basename(pdf) for pdf in pdfs if x in pdf][0]
new_ds["Report"] = new_ds["Name"].apply(a)
new_ds

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,Entity NACE Code,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_Letter,Report
0,JP3765420009,&Do Holdings Co.Ltd.,1,1991.0,JPN,J23362106,20150325.0,JPN,08ZVB2-E,68.31,...,JP3765420009,BVF9ZF,&Do Holdings Co.Ltd.,1.0,3457-JP,1,SHARE,BVF9ZF8,L,&Do Holdings Co.Ltd.1.pdf
3,CA67088Q1063,01 Communique Laboratory Inc.,1,1992.0,CAN,67088Q106,20120731.0,CAN,@NA,58.29,...,CA67088Q1063,256289,01 Communique Laboratory Inc.,1.0,OONEF-US,0,SHARE,B3BJBF8,J,01 Communique Laboratory Inc.2.pdf
4,CA67088Q1063,01 Communique Laboratory Inc.,1,1992.0,CAN,67088Q106,20000308.0,CAN,@NA,58.29,...,CA67088Q1063,256289,01 Communique Laboratory Inc.,1.0,ONE-CA,1,SHARE,2562898,J,01 Communique Laboratory Inc.2.pdf
6,PLVCAOC00015,01Cyberaton Proenergy SA,1,2007.0,POL,X989BK101,20080701.0,POL,@NA,69.20,...,PLVCAOC00015,B2QVXT,01Cyberaton Proenergy SA,1.0,01C-PL,1,SHARE,B2QVXT0,M,01Cyberaton Proenergy SA1.pdf
10,DE0005545503,1&1 AG,1,2002.0,DEU,D5934B101,19980423.0,DEU,@NA,61.20,...,DE0005545503,573467,1&1 AG,1.0,1U1-DE,1,SHARE,5734672,J,1&1 AG2.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90634,FDS21G19,Zymeworks Inc.,1,2003.0,USA,FDS21G196,NaN,USA,@NA,21.20,...,@NA,98985Y10,Zymeworks Inc.,1.0,@NA,0,SHARE,@NA,C,Zymeworks Inc.1.pdf
90635,US98985Y1082,Zymeworks Inc.,1,2003.0,USA,98985Y108,20170428.0,USA,@NA,21.20,...,US98985Y1082,98985Y10,Zymeworks Inc.,1.0,ZYME-US,1,SHARE,BPCQZY9,C,Zymeworks Inc.1.pdf
90637,US98986M1036,"Zynex, Inc.",1,1996.0,USA,98986M103,20000613.0,USA,002LCW-E,26.60,...,US98986M1036,98986M10,"Zynex, Inc.",1.0,ZYXI-US,1,SHARE,2226042,C,"Zynex, Inc.2.pdf"
90641,GB0006971013,Zytronic plc,1,1999.0,GBR,G98997102,20000706.0,GBR,05JDZN-E,26.20,...,GB0006971013,069710,Zytronic plc,1.0,ZYT-GB,1,SHARE,0697101,C,Zytronic plc1.pdf
90643,US98880P2020,"ZZLL Information Technology, Inc.",1,2005.0,USA,98880P202,20070920.0,HKG,008CLG-E,47.91,...,US98880P2020,98880P20,"ZZLL Information Technology, Inc.",1.0,ZZLL-US,1,SHARE,BYZ2H41,G,"ZZLL Information Technology, Inc.1.pdf"

In [49]:
result = new_ds.groupby("NACE_Letter").apply(
    lambda x: x.sample(n=min(len(x), 50), random_state=42)
).reset_index(drop=True)

/tmp/ipykernel_3678182/3216994446.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = new_ds.groupby("NACE_Letter").apply(

In [50]:
result.groupby("NACE_Letter").count()

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,Entity NACE Code,...,FE Ticker,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,Report
NACE_Letter,,,,,,,,,,,,,,,,,,,,,
A,50,50,50,49,50,50,46,50,50,50,...,50,50,50,50,50,50,50,50,50,50
B,50,50,50,47,50,50,46,50,50,50,...,50,50,50,50,50,50,50,50,50,50
C,50,50,50,49,50,50,49,50,50,50,...,50,50,50,50,50,50,50,50,50,50
D,50,50,50,50,50,50,43,50,50,50,...,50,50,50,50,50,50,50,50,50,50
E,50,50,50,50,50,50,48,50,50,50,...,50,50,50,50,50,50,50,50,50,50
F,50,50,50,49,50,50,47,50,50,50,...,50,50,50,50,50,50,50,50,50,50
G,50,50,50,50,50,50,49,50,50,50,...,50,50,50,50,50,50,50,50,50,50
H,50,50,50,49,50,50,45,50,50,50,...,50,50,50,50,50,50,50,50,50,50
I,50,50,50,47,50,50,49,50,50,50,...,50,50,50,50,50,50,50,50,50,50
J,50,50,50,50,50,50,47,50,50,50,...,50,50,50,50,50,50,50,50,50,50
K,50,50,50,46,50,50,44,50,50,50,...,50,50,50,50,50,50,50,50,50,50
L,50,50,50,47,50,50,45,50,50,50,...,50,50,50,50,50,50,50,50,50,50
M,50,50,50,50,50,50,45,50,50,50,...,50,50,50,50,50,50,50,50,50,50
N,50,50,50,50,50,50,44,50,50,50,...,50,50,50,50,50,50,50,50,50,50
P,50,50,50,46,50,50,46,50,50,50,...,50,50,50,50,50,50,50,50,50,50
Q,50,50,50,46,50,50,47,50,50,50,...,50,50,50,50,50,50,50,50,50,50
R,50,50,50,47,50,50,47,50,50,50,...,50,50,50,50,50,50,50,50,50,50
S,43,43,43,43,43,43,38,43,43,43,...,43,43,43,43,43,43,43,43,43,43

In [51]:
result

,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,Entity Credit Parent,Entity NACE Code,...,ISIN,Primary Equity Listing,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_Letter,Report
0,CA05335P1099,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,003V9K-E,01.30,...,CA05335P1099,BDGMQB,Auxly Cannabis Group Inc.,1.0,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf
1,JP3947800003,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,0833Y1-E,01.41,...,JP3947800003,B3ZC07,"MEGMILK SNOW BRAND Co., Ltd.",1.0,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf"
2,ID1000167901,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,@NA,03.12,...,ID1000167901,BMBMZG,PT Cilacap Samudera Fishing Industry Tbk,1.0,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf
3,JP3843250006,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,05HY7N-E,01.30,...,JP3843250006,643271,Hokuto Corporation,1.0,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf
4,VN000000VTQ6,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,@NA,02.30,...,VN000000VTQ6,BMCR2W,Viet Trung Quang Binh Joint Stock Co,1.0,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,DE000A1X3WW8,KHD Humboldt Wedag Vermogensverwaltungs-AG,1,1989.0,DEU,D4S00Z100,19900621.0,DEU,@NA,96.09,...,DE000A1X3WW8,BCRY6D,KHD Humboldt Wedag Vermogensverwaltungs-AG,1.0,HETA-DE,1,SHARE,BCRY6D3,S,KHD Humboldt Wedag Vermogensverwaltungs-AG1.pdf
889,SE0003909282,Dedicare AB,1,1995.0,SWE,W2483Q109,20110504.0,SWE,09G8G3-E,96.09,...,SE0003909282,B67VNT,Dedicare AB,1.0,DEDI-SE,1,SHARE,B67VNT7,S,Dedicare AB1.pdf
890,AU000000EVS3,EnviroSuite Ltd,1,1995.0,AUS,Q3541Y107,20220407.0,AUS,070J7P-E,96.09,...,AU000000EVS3,BY9C52,EnviroSuite Ltd,1.0,EVSSF-US,0,SHARE,BNNXZX4,S,EnviroSuite Ltd1.pdf
891,CA60365X1006,Miniluxe Holding Corp.,1,2021.0,CAN,60365X100,20210601.0,USA,0PQR2T-E,96.02,...,CA60365X1006,BNYMN7,Miniluxe Holding Corp.,1.0,MNLX-CA,1,SHARE,BNYMN70,S,Miniluxe Holding Corp.1.pdf
892,IT0003814537,Servizi Italia S.p.A.,1,2000.0,ITA,T82886101,20110512.0,ITA,06PXF9-E,96.01,...,IT0003814537,B1VMLV,Servizi Italia S.p.A.,1.0,0NJ3-GB,0,SHARE,B2900K4,S,Servizi Italia S.p.A.1.pdf

In [101]:
import shutil

src = "/path/to/source/file.txt"
dst = "/path/to/destination/file.txt"

#shutil.copy(src, dst)
for report in result["Report"]: 
    shutil.copy(os.path.join(pdfs_path, report)  , os.path.join(new_pdf_path, "PDFs",report))

In [52]:
result = result.rename(columns ={"Entity NACE Code": "NACE"})

In [53]:
result.to_csv(os.path.join(new_pdf_path, "reports_subset_from_full_data_3" + "_overview.csv"))

# Copy JSON to TXT

In [3]:
import json

In [4]:
jsons_path = "projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_3/JSONs"
jsons_paths = glob.glob(jsons_path + "/*.json")

In [5]:
for i in range(len(jsons_paths)): 
    with open(jsons_paths[i], "r") as f: 
        json_report = json.load(f)

    text = "\n".join([page["markdown"] for page in json_report["pages"]])
    text_path = jsons_paths[i].replace("JSONs", "TXTs").replace(".json", ".txt")

    with open(text_path, "w") as f:
        f.write(text)

In [6]:
text_path

'projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_3/TXTs/Cizzle Biotechnology Holdings PLC1.txt'