### Create Training data for binary classification: description of business sector - True False

In [2]:
import pandas as pd
import glob
import os
import ast
import json

import numpy as np
import pandas as pd
import os
import sys
import glob
import tqdm
import re
import random
from typing import List
from sklearn.model_selection import train_test_split

# sys.path.append("../../")
# from sentence_splitter import split_text_into_sentences
from __future__ import annotations

import os
from pathlib import Path

import fitz  # PyMuPDF

from docling.datamodel.accelerator_options import AcceleratorDevice, AcceleratorOptions
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions, TableFormerMode
from docling.document_converter import DocumentConverter, PdfFormatOption

#from BERT_classifier.Classify_report_with_BERT import classification_report_BERT
#from transformers import AutoModelForSequenceClassification, AutoTokenizer

#### Load Positives

In [12]:
positives_json_path = "/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/JSONs"
positives_json_path = "projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_3/JSONs"
positives_pdfs_path = "projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/PDFs"
description_page_path = "projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions"

In [6]:
#df_overview = pd.read_csv("/Users/hendrikweichel/projects/NaceCodeClassification/nace_report_topic_analysis_3/data/datasets/stoxx_600/stoxx_600_overview.csv", sep=";")
df_overview_3 = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_3/reports_subset_from_full_data_3_for_backtracking.csv", sep=";")
df_overview_3 = df_overview_3[df_overview_3["description_page"].notna()]
df_overview_3

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Symbol,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,...,Sec is Primary Issue,Sec Type,SEDOL,NACE_Letter,Report,NACE_lvl_3,description_page,Unnamed: 25,Description,LLM_summary
0,0,0,103,FR0013183985,Gensight Biologics SA,1,2012.0,FRA,F4374K117,20160713.0,...,1,SHARE,BD07M05,C,Gensight Biologics SA1.pdf,21.2,1,NaN,<!-- image -->\n\n## GenSight Biologics Report...,GenSight Biologics focuses on developing and c...
1,1,1,462,GB00BYN5BY03,Hybrid Software Group PLC,1,2013.0,BEL,G3971B107,20010417.0,...,1,SHARE,BYN5BY0,J,Hybrid Software Group PLC1.pdf,58.2,2,NaN,## CONTENTS\n\n| Hybrid Software Group ...,Hybrid Software Group PLC is a public company ...
2,2,2,651,BMG8766E1093,Textainer Group Holdings Limited,1,1979.0,USA,G8766E109,20191211.0,...,0,SHARE,BKDZ8P2,N,Textainer Group Holdings Limited1.pdf,77.3,2,NaN,<!-- image -->\n\n## About Us\n\nTextainer Gro...,Textainer Group Holdings Limited is a leading ...
3,3,3,539,AEA005901011,Amanat Holding PJSC,1,2014.0,ARE,M08598100,20141201.0,...,1,SHARE,BSZM277,K,Amanat Holding PJSC1.pdf,64.9,3,NaN,## About Amanat\n\nAmanat Holdings ( Amanat or...,Amanat Holdings is the largest investment comp...
4,4,4,530,US13738M1036,Cancer Capital Corp.,1,1997.0,USA,13738M103,20111017.0,...,1,SHARE,B6TVP88,K,Cancer Capital Corp.2.pdf,64.9,3,NaN,2\n\n2\n\n<!-- image -->\n\n## Cancer Care Wes...,Cancer Care West provides free community-based...
5,5,5,21,AU000000CSS3,Clean Seas Seafood Limited,1,2000.0,AUS,Q2508T119,20051212.0,...,1,SHARE,B0PFW92,A,Clean Seas Seafood Limited2.pdf,3.2,3,NaN,For personal use only\n\n<!-- image -->\n\n## ...,Clean Seas specializes in the full cycle breed...
6,6,6,532,US27579R1041,"East West Bancorp, Inc.",1,1998.0,USA,27579R104,19990208.0,...,1,SHARE,2487407,K,"East West Bancorp, Inc.1.pdf",64.1,3,NaN,<!-- image -->\n\nE ast West Banking Corporat...,EastWest Banking Corporation is a major univer...
7,7,7,115,MYQ0128OO007,Frontken Corp. Bhd.,1,1996.0,MYS,Y26510100,20060711.0,...,1,SHARE,B18TLC4,C,Frontken Corp. Bhd.1.pdf,26.1,13,NaN,## CHAPTER 1.0 INTRODUCTION ## 1.1 ABOUT FRONT...,Frontken Group's business model focuses on int...
8,8,8,672,AU000000MMS5,Mcmillan Shakespeare Limited,1,1988.0,AUS,Q58998107,20040315.0,...,1,SHARE,B00G1Q0,N,Mcmillan Shakespeare Limited1.pdf,77.1,3,NaN,MMS ANNUAL REPORT 2022\n\nB\n\n## Annual Gene...,McMillan Shakespeare Group provides salary pac...
9,9,9,496,US6075251024,"Model N, Inc.",1,1999.0,USA,607525102,20130320.0,...,1,SHARE,B94Z434,J,"Model N, Inc.1.pdf",58.2,3,NaN,## Introduction\n\nActivities that impact reve...,The business model focuses on optimizing reven...
10,10,10,537,SG1E32850828,New Toyo International Holdings Ltd,1,1975.0,SGP,Y6304R103,19970404.0,...,1,SHARE,6635547,K,New Toyo International Holdings Ltd1.pdf,64.2,3,NaN,"## INTRODUCTION\n\nNew Toyo, established in...","New Toyo, founded in 1975, specializes in prod..."
11,11,11,540,AU000000SWF8,SelfWealth Ltd.,1,2012.0,AUS,Q8458X109,20171123.0,...,1,SHARE,BFBFBD8,K,SelfWealth Ltd.2.pdf,66.1,3,NaN,"## A Leading, Australian Fintech\n\n## The Sto...",Selfwealth is an Australian fintech platform e...
12,12,12,520,FR0000121204,Wendel SE,1,NaN,FRA,F98370103,20040513.0,...,0,SHARE,B030RN8,K,Wendel SE2.pdf,64.9,3,NaN,<!-- image -->\n\nThe French language version ...,The Wendel Group operates as a professional sh...
13,13,13,497,CA00510L1067,AcuityAds Holdings Inc,1,2009.0,CAN,00510L106,20120720.0,...,1,SHARE,BP9P4Z3,J,AcuityAds Holdings Inc1.pdf,58.2,4,NaN,outlook and future-oriented financial informat...,AcuityAds is a technology company that facilit...
14,14,14,486,INE898S01029,Aurum Proptech Limited,1,2013.0,IND,Y5400E107,20150819.0,...,1,SHARE,BYW6D26,J,Aurum Proptech Limited2.pdf,58.2,4,NaN,## Aurum ProPtech\n\n## ecosystem snAPshot\n\n...,Aurum ProPtech operates a data-driven ecosyste...
15,15,15,512,GB00BNG2VN02,Cizzle Biotechnology Holdings PLC,1,2007.0,GBR,G1264V137,20070323.0,...,1,SHARE,BNG2VN0,K,Cizzle Biotechnology Holdings PLC1.pdf,64.9,4,NaN,## Cizzle Biotechnology Holdings PLC\n\n## Cha...,Cizzle Biotechnology Holdings PLC is focused o...
16,16,16,283,DE000A0STWH9,Deutsche Eigenheim Union AG,1,2007.0,DEU,D5S20K106,20211230.0,...,1,SHARE,BPCK369,F,Deutsche Eigenheim Union AG1.pdf,41.2,4,NaN,## D A S G E S C H Ä F T S M O D E L L\n\nBe...,Die Eigenheim Union Gruppe bietet bezahlbaren ...
17,17,17,531,US42727E1038,Heritage Global Inc.,1,1983.0,USA,"4,2727E+107",19890707.0,...,1,SHARE,BD6HJQ4,K,Heritage Global Inc.2.pdf,66.1,4,NaN,## Introduction\n\nThe concept of the circular...,Heritage Global Inc. (HG) focuses on transform...
18,18,18,460,GB00BDFDLT01,i-nexus Global plc,1,2018.0,GBR,G4768Y102,20180621.0,...,1,SHARE,BDFDLT0,J,i-nexus Global plc1.pdf,58.2,4,NaN,## STRATEGIC REPORT: Company Overview\n\ni-nex...,i-nexus provides strategy software to large or...
19,19,19,11,LU0611262873,KSG Agro SA,1,2010.0,POL,L5903L107,20110505.0,...,1,SHARE,B42XFB0,A,KSG Agro SA1.pdf,1.5,4,NaN,"## PRINCIPAL ACTIVITIES\n\nKSG Agro S.A., sepa...",KSG Agro S.A. is a major vertically integrated...
20,20,20,527,AU000000PAC7,Pacific Current Group Ltd,1,1987.0,AUS,Q7209G100,20100922.0,...,0,SHARE,BYV0NC9,K,Pacific Current Group Ltd1.pdf,64.9,4,NaN,## ABOUT US\n\nPacific Current Group Limited (...,Pacific Current Group Limited is a global mult...
21,21,21,272,MYL5219OO000,Pestech International Bhd.,1,2011.0,MYS,Y6801F107,20120530.0,...,1,SHARE,B8095F2,F,Pestech International Bhd.1.pdf,42.9,4,NaN,<!-- image -->\n\n## About PESTECH\n\nPESTECH ...,PESTECH International Berhad is a Malaysian el...
22,22,22,478,NZVHTE0001S6,Volpara Health Technologies Ltd.,1,2009.0,AUS,Q9479B118,20180116.0,...,0,SHARE,BFN4H02,J,Volpara Health Technologies Ltd.1.pdf,58.2,4,NaN,"ABOUT VOLPARA HEALTH\n\n## Joining together, s...",Volpara Health focuses on improving breast can...
23,23,23,687,US10948C1071,"BrightView Holdings, Inc.",1,2013.0,USA,10948C107,20180628.0,...,1,SHARE,BG0ZML1,N,"BrightView Holdings, Inc.1.pdf",81.3,5,NaN,## General Risk Factors\n\n- Natural disasters...,"BrightView Holdings, Inc. is the largest provi..."
24,24,24,690,US23204X1037,Custom Truck One Source Inc,1,1996.0,USA,23204X103,20171006.0,...,1,SHARE,BL66YS4,N,Custom Truck One Source Inc1.pdf,77.3,5,NaN,## Item 1. Business\n\n## Company Overview...,"Custom Truck One Source, Inc. provides a compr..."
25,25,26,299,TW0009906008,Hsin Ba Ba Corporation,1,1967.0,TWN,Y1754R109,19910920.0,...,1,SHARE,6224547,F,Hsin Ba Ba Corporation1.pdf,41.2,5,NaN,## Chapter I. Letter to Shareholders\n\n## Dea...,"In 2022, the Company increased raw material im..."
26,26,27,287,IT0005339160,PLC S.p.A.,1,2006.0,ITA,T5R88H130,20071123.0,...,0,SHARE,BGDSQ15,F,PLC S.p.A.2.pdf,42.2,5,NaN,"- ENERGY TRANSFORMS US, WE TRANSFORM ENERGY\n\...",PLC Group operates in the renewable energy mar...
27,27,28,119,US0326541051,"Analog Devices, Inc.",0,1965.0,USA,32654105,19981201.0,...,0,SHARE,5579130,C,"Analog Devices, Inc.1.pdf",26.1,6,NaN,"## ITEM 1. BUSINESS\n\n## Company Overview,...","Analog Devices, Inc. is a leading semiconducto..."
28,28,29,483,CA26885W1041,ePlay Digital Inc.,1,2013.0,CAN,26885W104,20150921.0,...,0,SHARE,BYWRDS5,J,ePlay Digital Inc.3.pdf,58.2,6,NaN,I\n\n## who we are\n\n<!-- image -->\n\n## G.O...,Devolver is a digital video games publisher an...
29,29,31,470,GB00BYXH8F66,Pelatro Plc,1,2017.0,GBR,G6993D100,20171219.0,...,1,SHARE,BYXH8F6,J,Pelatro Plc1.pdf,58.2,6,NaN,## Strategic Report - About Pelatro\n\nFor the...,Pelatro specializes in providing software solu...
30,30,32,258,AU0000032914,SRG Global Limited,1,1961.0,AUS,Q8661T101,20200408.0,...,0,SHARE,BL1MSJ6,F,SRG Global Limited1.pdf,41.2,6,NaN,## The most sought-after asset maintenance cap...,"SRG Global specializes in asset maintenance, p..."
31,31,33,252,JP3100320005,URBAN LiKE INC.,1,2008.0,JPN,J94435104,20210728.0,...,1,SHARE,BP5D4T5,F,URBAN LiKE INC.1.pdf,41.2,6,NaN,## AT A GLANCE\n\nThe UK faces a structural mi...,Urban Logistics REIT plc focuses on investing ...
32,32,34,528,FDS1GBVT,Ares Acquisition Corp.,1,2020.0,USA,FDS1GBVT6,NaN,...,0,SHARE,@NA,K,Ares Acquisition Corp.2.pdf,64.9,7,NaN,## PART I\n\nReferences in this annual report ...,Ares Acquisition Corporation is a blank check ...
33,33,35,259,FDS0FNU4,China Energy Engineering Corp. Ltd.,1,2014.0,HKG,FDS0FNU49,NaN,...,0,SHARE,@NA,F,China Energy Engineering Corp. Ltd.1.pdf,42.2,7,NaN,<!-- image -->\n\n## COMPANY PROFILE AND CORPO...,"The company, established in 2014 and co-sponso..."
34,34,36,509,JP3502200003,Daiwa Securities Group Inc.,0,1902.0,JPN,J11718111,19930913.0,...,0,SHARE,4276830,K,Daiwa Securities Group Inc.3.pdf,66.1,7,NaN,## (ii) Status by category described in segmen...,"The business model involves multiple segments,..."
35,35,37,253,VN000000HC37,HaiPhong Construction Joint Stock Corporation No3,0,1993.0,VNM,Y2985N107,20191212.0,...,1,SHARE,BD5DK26,F,HaiPhong Construction Joint Stock Corporation ...,41.1,7,NaN,Mr. LE CAO QUYEN Chairman of the Board\n\n<!--...,Power Engineering Consulting Joint Stock Compa...
36,36,38,107,FDS0SZ3K,Kiniksa Pharmaceuticals Ltd.,1,2015.0,USA,FDS0SZ3K2,NaN,...,0,SHARE,@NA,C,Kiniksa Pharmaceuticals Ltd.1.pdf,21.2,7,NaN,## SUMMARY RISK FACTORS\n\nOur business is sub...,"The business model faces significant risks, in..."
37,37,39,286,PLBUDMX00013,Budimex SA,1,1968.0,POL,X0788V103,20081106.0,...,0,SHARE,B28FKZ5,F,Budimex SA1.pdf,41.2,8,NaN,2.\n\n## About the Budimex Group\n\n## 2.1. A...,The Budimex Group operates as a general contra...
38,38,40,546,FDS1FOUG,CF Acquisition Corp. IV,1,2020.0,USA,FDS1FOUG8,NaN,...,0,SHARE,@NA,K,CF Acquisition Corp. IV1.pdf,64.9,8,NaN,"## Note 1-Description of Organization, Busines...",CF Acquisition Corp. IV is a Delaware-incorpor...
39,39,41,297,TW0003703005,Continental Holdings Corp.,1,1941.0,TWN,Y1753K105,19950427.0,...,1,SHARE,B58DQK7,F,Continental Holdings Corp.1.pdf,41.2,8,NaN,## Key Subsidiaries and History\n\n## Continen...,The business model of CHC encompasses three ke...
40,40,42,10,"331091024,00 ARP",Cresud SA,1,1936.0,ARG,P3311R127,19850102.0,...,1,SHARE,2233387,A,Cresud SA1.pdf,1.6,8,NaN,## CORPORATE PROFILE\n\n## LEADERS IN THE AGRI...,The company is a leading Argentine agribusines...
41,41,43,513,KR7448830000,Mirae Asset Vision Special Purpose Acquisition...,0,NaN,KOR,Y6S4F8108,20230407.0,...,0,SHARE,BMBN9V5,K,Mirae Asset Vision Special Purpose Acquisition...,64.9,8,NaN,## Company Overview\n\nAs a Korea's leading fi...,Mirae Asset Securities is a leading South Kore...
42,42,44,511,KYG7255W1096,Prinx Chengshan Holdings Limited,1,2015.0,HKG,G7255W109,20181009.0,...,1,SHARE,BDVPJ63,K,Prinx Chengshan Holdings Limited1.pdf,64.9,8,NaN,## Overview of the Group\n\nThe business of Pr...,"Prinx Chengshan Holdings Limited, established ..."
43,43,45,267,ID1000122609,PT Bekasi Fajar Industrial Estate Tbk,1,1989.0,IDN,Y711C5100,20210813.0,...,0,SHARE,BMH4138,F,PT Bekasi Fajar Industrial Estate Tbk1.pdf,41.2,8,NaN,## Sekilas BeFa\n\nBeFa at A Glance\n\nPersero...,BeFa operates primarily in the management of i...
44,44,46,541,DE0006201403,PEH Wertpapier AG,1,1990.0,DEU,D6007P100,19981119.0,...,1,SHARE,5572203,K,PEH Wertpapier AG1.pdf,66.3,9,NaN,<!-- image -->\n\n## 1 Grundlagen des Konzerns...,Der PEH Konzern ist ein Wertpapierinstitut mit...
45,45,47,499,US92337U2033,"Verb Technology Company, Inc.",1,2012.0,USA,92337U203,20141119.0,...,1,SHARE,BN4JPD1,J,"Verb Technology Company, Inc.1.pdf",58.2,10,NaN,## 1. DESCRIPTION OF BUSINESS\n\n## Our Busine...,"Verb Technology Company, Inc. operates as a Sa..."
46,46,48,106,AT0000A18XM4,ams-OSRAM AG,1,1981.0,CHE,A0400Q115,20080423.0,...,0,SHARE,BPFJ772,C,ams-OSRAM AG1.pdf,26.1,12,NaN,## Our company\n\nams OSRAM is a global leader...,ams OSRAM is a global leader in optical soluti...
47,47,50,533,US01446U1034,Alerus Financial Corporation,1,1879.0,USA,01446U103,19901228.0,...,1,SHARE,2679141,K,Alerus Financial Corporation1.pdf,64.1,13,NaN,- our success at managing the risks involved w...,Alerus Financial Corporation operates as a div...
48,48,51,468,GB00BFM6WC61,KRM22 Plc,1,2018.0,GBR,G53173103,20180430.0,...,1,SHARE,BFM6WC6,J,KRM22 Plc1.pdf,58.2,13,NaN,## OUR PRODUCTS\n\nBuilt on the Global Risk Pl...,KRM22 offers a cloud-based Global Risk Platfor...
49,49,52,475,FI0009007728,Teleste Corporation,1,1954.0,FIN,X89488104,19990330.0,...,1,SHARE,5653937,J,Teleste Corporation1.pdf,61.1,13,NaN,## Teleste Networks\n\nWe offer broadband netw...,Teleste Networks provides broadband and video ...
50,50,53,543,KZ000A0Q5HK5,First Heartland Jusan Bank JSC,1,1992.0,KAZ,Y8T74N105,20090519.0,...,0,SHARE,B132NR7,K,First Heartland Jusan Bank JSC1.pdf,64.1,14,NaN,<!-- image -->\n\n<!-- image -->\n\nABOUT THE ...,First Heartland Jusan Bank JSC is a private ba...
51,51,54,508,MYL03029O005,GPP Resources Bhd.,1,2018.0,MYS,Y2839L109,20191004.0,...,1,SHARE,BK7ZBG0,K,GPP Resources Bhd.2.pdf,64.9,14,NaN,<!-- image -->\n\n## MANAGEMENT DISCUSSION AND...,Analabs Resources Berhad operates as an invest...
52,52,55,544,US26942G1004,"Eagle Bancorp Montana, Inc.",1,1922.0,USA,26942G100,20000405.0,...,1,SHARE,B57M9P1,K,"Eagle Bancorp Montana, Inc.1.pdf",64.1,15,NaN,## ITEM 1. DESCRIPTION OF BUSINESS.\n\n## Over...,"Eagle Bancorp Montana, Inc. is a bank holding ..."
53,53,56,503,INE414G01012,Muthoot Finance Limited,1,1939.0,IND,Y6190C103,20110506.0,...,1,SHARE,B40MFF3,K,Muthoot Finance Limited3.pdf,64.9,22,NaN,<!-- image -->\n\n## BUSINESS REVIEW\n\n## Div...,Muthoot Finance is India's largest gold loan c...
54,54,57,456,SI0031101247,Grad d.d.,0,1990.0,SVN,X3206N109,20210520.0,...,0,SHARE,B04DSR7,J,Grad d.d.3.pdf,58.2,27,NaN,<!-- image -->\n\n<!-- image -->\n\nFor more i...,UNIOR d.d. is the parent company of the UNIOR ...
55,55,58,273,ID1000104003,PT Total Bangun Persada Tbk,1,1970.0,IDN,Y7136Z107,20230512.0,...,0,SHARE,BMGCH68,F,PT Total Bangun Persada Tbk3.pdf,41.1,33,NaN,<!-- image -->\n\nPT Total Bangun Persada ...,PT Total Bangun Persada Tbk is the largest and...
56,56,59,292,INE291R01011,Athena Constructions Ltd.,0,2011.0,IND,Y0R7X4104,20150416.0,...,0,SHARE,BWWYV33,F,Athena Constructions Ltd.1.pdf,41.2,45,NaN,## ATHENA CONSTRUCTIONS LIMITED\n\n## Notes to...,"Athena Constructions Limited, incorporated in ..."
57,57,60,485,US29259X1046,Encompass Compliance Corp.,0,1991.0,USA,29259X104,20000301.0,...,1,SHARE,BZ07DY0,J,Encompass Compliance Corp.1.pdf,58.2,45,NaN,## EXECUTIVE COMPENSATION\n\n## Compensation D...,Encompass Health's business model focuses on p...
58,58,61,2,ID1000167901,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,...,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,45,NaN,## Riwayat Singkat Perseroan\n\nThe Company at...,PT Dharma Samudera Fishing Industries Tbk init...

In [7]:
df_overview_2 = pd.read_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview.csv", sep=",")
df_overview_2

,Symbol,Description_page,Unnamed: 0,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Proper Name,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2
0,CA05335P1099,NaN,0,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,Auxly Cannabis Group Inc.,1.0,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1
1,JP3947800003,NaN,1,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,"MEGMILK SNOW BRAND Co., Ltd.",1.0,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1
2,ID1000167901,NaN,2,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,PT Cilacap Samudera Fishing Industry Tbk,1.0,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3
3,JP3843250006,NaN,3,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,Hokuto Corporation,1.0,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1
4,VN000000VTQ6,NaN,4,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,Viet Trung Quang Binh Joint Stock Co,1.0,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,KYG4707P1054,NaN,3278,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,Icon Culture Global Company Limited,1.0,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98
3110,ZAE000015277,NaN,12259,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,Brimstone Investment Corporation Limited,1.0,BRT-ZA,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3
3111,NO0011013765,NaN,31130,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,Gigante Salmon AS,1.0,GIGA-NO,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3
3112,FR0010776617,NaN,68675,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,Sapmer SA,1.0,ALMER-FR,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3
3113,ZAE000240198,NaN,69396,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,Sea Harvest Group Ltd.,1.0,SHG-ZA,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3

In [ ]:
# for i, row in df_overview_2.iterrows(): 
#     if pd.isna(row["Description_page"]):
#         continue

#     # if (row["Description_page"].strip() == ""):
#     #     continue

#     path = row["Report"].replace(".pdf", ".json")
    
#     with open(os.path.join(positives_json_path, path), "r") as f: 
#         report_json = json.load(f)
    
#     description_pages = [int(row["Description_page"])]

#     description_text = ""
#     for description_page in description_pages:
#         description_text += list(filter(lambda x: x["page"] == description_page + 1, report_json["pages"]))[0]["markdown"]

#     print(row["Report"])
#     print(description_text)
#     print("-----" * 5 + "\n"*6)

#     df_positives.loc[i, "Description"] = description_text

## Load description pages with docling

In [8]:
pipeline_options = PdfPipelineOptions(
    # your current options
)
# choose GPU device
pipeline_options.accelerator_options = AcceleratorOptions(
    num_threads=8, 
    device=AcceleratorDevice.CUDA 
)
pipeline_options = PdfPipelineOptions(do_table_structure=True)
#pipeline_options.table_structure_options.mode = TableFormerMode.FAST

# assume you already built pipeline_options above
doc_converter = DocumentConverter(
    format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)}
)

In [28]:
def convert_via_single_page_pdf(
    pdf_path: str,
    page: int,
    out_dir: str = "single_pages",
    *,
    overwrite: bool = False,
):
    """
    1) Copies exactly one page from `pdf_path` into a new PDF saved under `out_dir`
    2) Converts that new single-page PDF with Docling (converting the full PDF, which is only that page)

    Args:
        pdf_path: Path to source PDF
        page: Page number to extract (1-based)
        out_dir: Folder to store single-page PDFs
        overwrite: If False, raise if output file already exists

    Returns:
        (docling_conversion_result, single_page_pdf_path)
    """
    if page < 1:
        raise ValueError("`page` must be >= 1 (1-based indexing).")

    src_path = Path(pdf_path)
    if not src_path.exists():
        raise FileNotFoundError(f"PDF not found: {src_path}")

    Path(out_dir).mkdir(parents=True, exist_ok=True)

    # Build output filename: <stem>__p0005.pdf
    out_path = Path(out_dir) / f"{src_path.stem}__p{int(page)}.pdf"
    if out_path.exists() and not overwrite:
        print(f"Output already exists: {out_path} (set overwrite=True to replace)")
        return None, None
    

    # --- 1) Copy one page into new PDF ---
    try:
        with fitz.open(src_path) as src:
            if page > src.page_count:
                raise ValueError(f"Requested page {page} exceeds page_count={src.page_count} for {src_path}")

            dst = fitz.open()  # new empty PDF
            # insert_pdf uses 0-based indices for pages
            dst.insert_pdf(src, from_page=page - 1, to_page=page - 1)
            dst.save(out_path)
            dst.close()
    except:
        return None, None


    # --- 2) Convert the new single-page PDF (no page_range needed) ---
    pipeline_options = PdfPipelineOptions()  # default: parse full PDF (which is only one page)
    doc_converter = DocumentConverter(
        format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)}
    )

    conversion_result = doc_converter.convert(str(out_path))

    md = conversion_result.document.export_to_markdown()
    return md, str(out_path)

In [21]:
def convert_single_pdf_page(pdf_path: str, page: int):
    """
    Convert a single page of a PDF using docling.

    Args:
        pdf_path: Path to the PDF file
        page: Page number to extract (1-based indexing)

    Returns:
        Converted docling Document object containing only the selected page
    """
    if page < 1:
        raise ValueError("Page number must be >= 1 (1-based indexing).")

    pipeline_options = PdfPipelineOptions(
        page_range=(page, page)
    )

    doc_converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(
                pipeline_options=pipeline_options
            )
        }
    )

    return doc_converter.convert(pdf_path)

In [29]:
for i, row in df_overview_2.iterrows(): 

    if pd.isna(row["Description_page"]):
        continue

    path = os.path.join(positives_pdfs_path, row["Report"])

    description_text, _ = convert_via_single_page_pdf(path, int(row["Description_page"]), description_page_path)
    if description_text is None: 
        continue

    print(row["Report"])
    print(description_text)
    print("-----" * 5 + "\n"*6)

    df_overview_2.loc[i, "Description"] = description_text

Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Cryomass Technologies Inc.1__p2.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Gene Bio Tech Co., Ltd.1__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Liminal BioSciences Inc.1__p56.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Gensight Biologics SA1__p1.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/ams-OSRAM AG1__p12.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Hua Medicine Ltd.1__p9.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Frontken Corp. Bhd.1__p13.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Analog Devices, Inc.1__p6.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Processa Pharmaceuticals, Inc.2__p4.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Transcenta Holding Limited1__p12.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Day One Biopharmaceuticals, Inc.1__p4.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Cell Source, Inc.1__p13.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Kingboard Laminates Holdings Limited1__p6.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Hansoh Pharmaceutical Group Company Limited1__p3.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/IDEX Biometrics ASA1__p3.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Malaysian Pacific Industries Bhd.1__p12.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Global Lighting Technologies Inc.1__p9.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/SolarWorld AG1__p6.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/URBAN LiKE INC.1__p2.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/SRG Global Limited1__p2.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/China Energy Engineering Corp. Ltd.1__p7.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/M.D.C. Holdings, Inc.1__p19.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Beijing Enterprises Water Group Limited2__p16.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Pestech International Bhd.1__p4.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Sitios Latinoamerica SAB de CV1__p7.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Deutsche Eigenheim Union AG1__p4.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Budimex SA1__p8.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/PLC S.p.A.2__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Tai Kam Holdings Limited1__p7.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Athena Constructions Ltd.1__p4.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Continental Holdings Corp.1__p7.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Hsin Ba Ba Corporation1__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Gamuda Bhd.1__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/BV Land Holdings Bhd.1__p16.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Kedge Construction Co., Ltd.1__p8.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Great Lakes Dredge & Dock Corporation1__p11.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Corre Energy B.V.1__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Able Engineering Holdings Ltd.2__p7.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/Three Sixty Solar Ltd2__p5.pdf (set overwrite=True to replace)
Output already exists: projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/company_descriptions/De.mem Ltd.1__p7.pdf (set overwrite=True to replace)
MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

MuPDF error: limit error: exception stack overflow!

MuPDF error: exception stack overflow!

2025-12-18 10:35:29,880 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:35:29,882 - INFO - Going to convert document batch...
2025-12-18 10:35:29,883 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:35:29,884 - INFO - Accelerator device: 'cpu'
2025-12-18 10:35:31,344 - INFO - Accelerator device: 'cpu'
2025-12-18 10:35:32,618 - INFO - Accelerator device: 'cpu'
2025-12-18 10:35:32,864 - INFO - Processing document Boustead Singapore Limited1__p3.pdf
2025-12-18 10:35:37,737 - INFO - Finished converting document Boustead Singapore Limited1__p3.pdf in 7.86 sec.
2025-12-18 10:35:37,760 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:35:37,762 - INFO - Going to convert document batch...
2025-12-18 10:35:37,762 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:35:37,763 - INFO - Accelerator device: 'cpu'

Boustead Singapore Limited1.pdf
## Corporate Profile

Established in 1828, Boustead Singapore Limited (SGX:F9D) is a progressive global InfrastructureRelated Engineering and Technology Group listed on the SGX Mainboard.

As Singapore's oldest continuous business organisation, we focus on the niche engineering and development of key infrastructure to support sustainable shared socio-economic growth. Our strong suite of engineering services under our Energy Engineering Division and Real Estate Division centres on energy infrastructure and smart, eco-sustainable and futureready real estate developments.

In addition, we provide technologydriven transformative solutions to improve the quality of life for all walks of life. Our Geospatial Division provides professional services and exclusively distributes Esri ArcGIS technology - the world's leading geographic information system, smart mapping and location analytics enterprise platform - to major markets in the Asia Pacific. The enterprise platform creates digital infrastructure solutions and digital twins that enable smart nations, smart cities and smart communities to solve the world's most complex problems by improving human wellbeing and ecosystems, and helping in the effective planning and management of key infrastructure and resources. Our Healthcare Division provides innovative medical solutions that address age-related chronic diseases and mobility issues, with a focus on rehabilitative care and sports science in the Asia Pacific.

With a vast global network stretching across Asia, Australia, Europe, Africa and the Americas, we are ready to serve the world. To date, we have undertaken projects in 91 countries and territories globally.

Over the years, we have been a recipient of many reputable awards including the prestigious Forbes Asia 200 Best Under A Billion Award. In 2019, we were awarded the Most Transparent Company Award and Sustainability Award (Runner-Up) by the Securities Investors Association (Singapore). From 2020 to 2022, we also ranked among Singapore's Best Employers, Singapore's Fastest Growing Companies and Asia-Pacific High-Growth Companies. We were also honoured with the Corporate Excellence &amp; Resilience Award at the Singapore Corporate Awards 2021 Special Edition.

Visit us at www.boustead.sg .

<!-- image -->

## Contents

| Overview                                      |     |
|-----------------------------------------------|-----|
| 10                                            |     |
| Refreshing a Global Icon                      | 10  |
| Mission, Vision & Business Model              | 12  |
| Global Presence                               | 16  |
| Group at a Glance                             |     |
| - Overall Financial Performance               | 18  |
| - Division Financial Performance              | 20  |
| - Socio-Economic & Sustainability Performance | 22  |
| Chairman's Message                            | 28  |
| Strategic Review                              |     |
| 32                                            |     |
| Energy Engineering                            | 32  |
| Real Estate                                   | 38  |
| Geospatial                                    | 46  |
| Healthcare                                    | 56  |
| Quality, Safety &                             |     |
| Sustainability Awards                         | 60  |
| Board of Directors                            | 62  |
| Key Management Team                           | 64  |
| Stakeholder Relations                         | 66  |
| Corporate Information                         | 68  |
| Financial Statements                          |     |
| 69                                            |     |
| Directors' Statement                          | 70  |
| Corporate Governance                          | 74  |
| Independent Auditor's Report                  | 105 |
| Consolidated Financial                        |     |
| Statements & Notes                            | 109 |
| Management & Principal Activities             | 217 |
| Statistics of Shareholdings                   | 221 |
| Notice of Annual General Meeting              | 223 |
| Proxy Form                                    | 231 |
-------------------------

2025-12-18 10:35:39,220 - INFO - Accelerator device: 'cpu'
2025-12-18 10:35:40,321 - INFO - Accelerator device: 'cpu'
2025-12-18 10:35:40,573 - INFO - Processing document JGC Holdings Corporation1__p18.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:36:01,095 - INFO - Finished converting document JGC Holdings Corporation1__p18.pdf in 23.34 sec.
2025-12-18 10:36:01,153 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:01,155 - INFO - Going to convert document batch...
2025-12-18 10:36:01,156 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:01,157 - INFO - Accelerator device: 'cpu'

JGC Holdings Corporation1.pdf
Other business

1.4%

## JGC Group at a Glance

Through business focused on Total engineering and Functional materials manufacturing, the JGC Group is aiming to realize our purpose in 'Enhancing planetary health,' and ensuring continued growth of corporate value.

## Breakdown of Sales (Fiscal 2021)

<!-- image -->

|                                     | Segment                                                                                    | Covered Sectors                                                                                                                                                                                                                                                                                                                                                          |
|-------------------------------------|--------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Total engineering business 88.2 %   | JGC Corporation (Overseas business)                                                        | Energy Solutions Sector Engineering, procurement, and construction of plants and facilities in sectors such as LNG, CCS, refinery, chemicals, gas processing, crude oil and gas gathering, non-ferrous metal smelting, hydrogen, fuel ammonia, nuclear energy, etc.                                                                                                      |
| engineering business                | JGC Corporation (Overseas business)                                                        | Facility Infrastructure Solutions Sector Engineering, procurement, and construction of infrastructure facilities focused on renewable energy power generation (solar, biomass, wind), battery energy storage, LNG / LPG terminals, waste power generation, pharmaceuticals and food factories, hospitals, airports, transportation infrastructure, water treatment, etc. |
| Total engineering business 88.2 %   | JGC Japan Corporation (Domestic business)                                                  | Domestic Sector Engineering, procurement, construction, and maintenance of plants and facilities for oil & gas, power generation, chemicals, pharmaceuticals and laboratories, healthcare (medical and welfare), renewable energy power generation, hydrogen / fuel ammonia, resource recycling, nuclear energy- related, etc.                                           |
| material business                   | JGC Catalysts and Chemicals Ltd.                                                           | Catalysts and Fine Chemicals Sector Development and production of catalysts used in petroleum refining, chemical, and environmental conservation and of fine chemical products used as materials in semiconductor, IT / electronics, optics, cosmetics, and other applications                                                                                           |
| Functional                          | Japan Fine Ceramics Co., Ltd.                                                              | Fine Ceramics Sector Development and production of ceramic materials for semiconductor, automotive, telecommunications, industrial, medical, and aerospace applications                                                                                                                                                                                                  |
| Functional material business 10.3 % | Main operating companies Japan NUS Co., Ltd. and other domestic / overseas Group companies | Energy and environmental consulting, other business                                                                                                                                                                                                                                                                                                                      |
-------------------------

2025-12-18 10:36:02,613 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:03,716 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:03,968 - INFO - Processing document Balfour Beatty plc1__p2.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:36:06,974 - INFO - Finished converting document Balfour Beatty plc1__p2.pdf in 5.82 sec.
2025-12-18 10:36:06,994 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:06,995 - INFO - Going to convert document batch...
2025-12-18 10:36:06,996 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:06,997 - INFO - Accelerator device: 'cpu'

Balfour Beatty plc1.pdf
Balfour Beatty is a leading international infrastructure group with 25,000 employees driving the delivery of powerful new solutions, shaping thinking, creating skylines and inspiring a new generation of talent to be the change-makers of tomorrow.

We finance, develop, build, maintain and operate the increasingly complex and critical infrastructure that supports national economies and deliver projects at the heart of local communities.

<!-- image -->

## Innovation everywhere

Across Balfour Beatty, we are harnessing the power of digital and cutting-edge technology to drive productivity, improve safety and develop sustainable solutions. Look out for this icon in the report to read about our best innovations which are helping to transform the infrastructure and construction industry.

## Infrastructure opportunities

Our chosen markets show strong underlying drivers and continue to deliver significant opportunities to the Group.

650bn UK £

## Positive outlook for the UK

The infrastructure market outlook is positive and is boosted by the Infrastructure and Projects Authority's £650bn pipeline, providing the highest levels of investment in decades.

<!-- image -->

## Strong infrastructure stimulus in the US

Driven by the US$1.2 trillion Infrastructure Investment &amp; Jobs Act, infrastructure growth in the US will experience a significant boost in Balfour Beatty's chosen states.

<!-- image -->

## Stable spend in Hong Kong

1tn HK $

The outlook is positive, supported by the Government's plan to increase land supply, speed up railway development projects and rehabilitate the city's ageing buildings.

<!-- image -->

## Infrastructure expertise

<!-- image -->

A breadth of in-house capability

<!-- image -->

Better, faster, greener through modern methods of construction

<!-- image -->

Towards a zero carbon construction site

<!-- image -->

<!-- image -->

<!-- image -->

FRONT COVER: Jay Saddington, Survey &amp; Product Communications Support and Kasia Renc, Graduate Digital Project Delivery Engineer, with Balfour Beatty's robotic dog 'Spot' which documents construction progress using autonomous 3D data capture on site.
-------------------------

2025-12-18 10:36:08,449 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:09,620 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:09,874 - INFO - Processing document Beazer Homes USA, Inc.1__p9.pdf
2025-12-18 10:36:10,623 - INFO - Finished converting document Beazer Homes USA, Inc.1__p9.pdf in 3.63 sec.
2025-12-18 10:36:10,644 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:10,645 - INFO - Going to convert document batch...
2025-12-18 10:36:10,646 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:10,647 - INFO - Accelerator device: 'cpu'

Beazer Homes USA, Inc.1.pdf
## Item 1. Business

We are a geographically diversified homebuilder with active operations in 13 states within three geographic regions in the United States: the West, East, and Southeast. Our homes are designed to appeal to homeowners at different price points across various demographic segments and are generally offered for sale in advance of their construction. Our objective is to provide our customers with homes that incorporate extraordinary value and quality, at affordable prices, while seeking to maximize our return on invested capital over the course of a housing cycle.

Beazer Homes USA, Inc. was incorporated in Delaware in 1993. Our principal executive offices are located at 1000 Abernathy Road, Suite 260, Atlanta, Georgia  30328,  and  our  main  telephone  number  is  (770)  829-3700.  We  also  provide  information  about  our  company,  including  active  communities, through our Internet website located at www.beazer.com. Information on our website is not a part of this Form 10-K and shall not be deemed incorporated by reference.

## Business Strategy

We continue to execute against our long-term balanced growth strategy, which we define as the expansion of earnings at a faster rate than our revenue growth, supported by a less-leveraged and return-driven capital structure. This strategy provides us with the flexibility to reduce leverage and increase return of capital, or increase investment in land and other operating assets in response to changing market conditions.

We remain committed to this strategy, which is designed to increase shareholder value by improving our r eturn on assets while reducing operational risk and  debt.  Our  objectives  at  the  beginning  of  fiscal  2022  included  growing  our  lot  position  through  land  spending  and  increased  use  of  lot  option agreements,  improving  profitability  while  reducing  our  total  debt  below  $1.0  billion,  delivering  extraordinary  customer  experience,  and  encouraging employee well-being. We have successfully achieved our goals as following:

- As of September 30, 2022, our land position included 25,170 controlled lots,  up 14.5% from 21,987 a year ago. Through expansion of our use of lot option agreements, 54.6% of our total active lots  were under option agreements as of September 30, 2022 compared to 46.6%  a year ago.
- For fiscal 2022, we recorded net income of $220.7 million, or $7.17 per diluted share, compared to net income of $122.0 million, or $4.01 per diluted share, for fiscal 2021. Adjusted EBITDA was $370.1 million in fiscal 2022, compared to $262.7 million in the prior year, an increase of $107.4 million, or 40.9%. Over the past five years, we have achieved a compound annual growth rate (CAGR) of 15.7% for Adjusted EBITDA.
- We have successfully reached our deleveraging goal of reducing total debt to below $1.0 billion. During fiscal 2022, we repurchased $24.4 million of  our  Senior  Notes  and  retired  our  Senior  Unsecured  Term  Loan  by  repaying  the  final  $50.0  million.  As  of  September  30,  2022,  we  had outstanding debt of $983.4 million. During fiscal 2022, we also repurchased $8.2 million of outstanding common stock.
- In April 2022, Beazer Homes was ranked first among construction companies in Newsweek's inaugural list of America's Most Trusted Companies 2022, which were identified based on an independent survey of approximately 50,000 U.S. residents who rated companies they knew from the perspective of customers, investors and employees. This award demonstrated recognition for our efforts to create and sustain a strong reputation among employees, shareholders, customers and other partners.

For fiscal 2023, our objectives include investing strategically in our land position, upholding operating margin, activating new communities, reducing cycle time, and delivering extraordinary customer experience.

## PART I
-------------------------

2025-12-18 10:36:12,100 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:13,229 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:13,483 - INFO - Processing document Yunnan Water Investment Co., Limited1__p11.pdf
2025-12-18 10:36:14,177 - INFO - Finished converting document Yunnan Water Investment Co., Limited1__p11.pdf in 3.53 sec.
2025-12-18 10:36:14,199 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:14,201 - INFO - Going to convert document batch...
2025-12-18 10:36:14,202 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:14,202 - INFO - Accelerator device: 'cpu'

Yunnan Water Investment Co., Limited1.pdf
## 3. Segment information

The executive directors of the Company are the chief operating decision-maker of the Group. Management has determined the operating segments based on reports reviewed by the executive directors of the Company for the purpose of allocating resources and assessing performance.

The  executive  directors  of  the  Company  consider  the  business  from  product  and  service perspective. The Group is organised into five business segments as below:

- (a)  Wastewater treatment;
- (b)  Water supply;
- (c)  Construction and sales of equipment;
- (d)  Solid waste treatment;
- (e)  Others, including operation and maintenance services and other businesses.

Management  monitors  the  results  of  the  Group's  operating  segments  separately  for  the purpose of making decisions about resources allocation and performance assessment. Segment performance is evaluated based on reportable segment results, which is a measure of revenue and gross profit of each operating segment.

The amounts provided to the executive directors of the Company with respect to total assets and total liabilities are measured in a manner consistent with that of the financial statements. These assets and liabilities are allocated based on the operations of the segment.

Unallocated  assets  mainly  represented  cash  and  cash  equivalents,  restricted  cash,  certain prepayments  and  certain  receivables  of  the  group  entities  engaging  in  multiple  business segments.  Management  considered  that  it  is  impracticable  or  not  meaningful  in  allocating  to different segments.

Unallocated  liabilities  mainly  represented  certain  borrowings,  certain  payables  and  deferred income of the group entities engaging in multiple business segments. Management considered that it is impracticable or not meaningful in allocating to different segments.
-------------------------

2025-12-18 10:36:15,673 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:16,801 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:17,052 - INFO - Processing document GEK Terna Holding Real Estate Construction SA1__p74.pdf
2025-12-18 10:36:17,780 - INFO - Finished converting document GEK Terna Holding Real Estate Construction SA1__p74.pdf in 3.58 sec.
2025-12-18 10:36:17,798 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:17,800 - INFO - Going to convert document batch...
2025-12-18 10:36:17,800 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:17,801 - INFO - Accelerator device: 'cpu'

GEK Terna Holding Real Estate Construction SA1.pdf
and ninety one (103,423,291) common registered shares with a nominal value of euro fifty seven cents (0.57 euro) each.

The main activity of the Company is the development and management of investment property, the construction of any kind of projects, the management of self-financed or co-financed projects, the construction and operation of energy projects, as well as its participation in companies having similar activities.

The Group has a significant and specialized presence in construction, the production and trading of energy as well as in the development, management and exploitation of investment property having a strong capital base.

The  activities  of  the  Group  mainly  take  place  in  Greece,  while  at  the  same  time  it  has  significant presence in the Balkans, the Middle East, the Eastern Europe and the North America. The Group's operations focus on the following operating segments:

- Constructions : almost exclusively, technical construction contracts.
- Electric  energy  from  RES :  production  of  electric  energy  arising  from  wind  parks,  solar  and hydropower and biomass.
- Thermal energy trading in electric energy and natural gas : production of electric energy through fuels and natural gas and trading in electric energy and natural gas.
- Industry : refers to the production of quarry products and the exploitation of magnesite quarries.
- Real Estate : acquisition, development and exploitation of real estate as well as investments for the purposes of acquisition of surplus value from the increase in the real estate items prices.
- Concessions : construction and operation of infrastructure (e.g. motorways), other public interest projects (Unified Automatic Collection System and municipal waste treatment plant) and other facilities (e.g. parking stations, etc.) in exchange for provision of long-term exploitation services to the public.
- Holdings :  supporting  the  Group's  operating  segments  and  trial  operation  of  new  operating segments.

The consolidated companies included in the consolidated Financial Statements and their unaudited FYs are analytically recorded in Note 4 to the Financial Statements.

The attached interim condensed separate and consolidated Financial Statements for the period ended 30 th June 2022 were approved by the Board of Directors on 29 th September 2022.

## 2 BASIS FOR THE PREPARATION OF FINANCIAL STATEMENTS

## 2.1 Basis for the Presentation of financial statements

The Interim Condensed Separate and Consolidated Financial Statements of the Company as of June 30 th , 2022, which cover the six-month period from January 1 st to June 30 th 2022 have been prepared according  to  the  International  Financial  Reporting  Standards  (IFRS),  which  were  published  by  the International Accounting Standards Board (IASB) and according to their interpretations, which have been published by the International Financial Reporting Interpretations Committee (IFRIC) and have
-------------------------

2025-12-18 10:36:19,254 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:20,384 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:20,636 - INFO - Processing document Tri Pointe Homes, Inc.1__p2.pdf
2025-12-18 10:36:21,326 - INFO - Finished converting document Tri Pointe Homes, Inc.1__p2.pdf in 3.53 sec.
2025-12-18 10:36:21,354 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:21,356 - INFO - Going to convert document batch...
2025-12-18 10:36:21,356 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:21,357 - INFO - Accelerator device: 'cpu'

Tri Pointe Homes, Inc.1.pdf
## Who we are

One of the largest homebuilders in the U.S., Tri Pointe Homes (NYSE: TPH) is a publicly traded company and a recognized leader in customer experience, innovative design, and environmentally responsible business practices. The company builds premium homes and communities in 10 states with deep ties to the communities it servessome for as long as a century.

Tri Pointe Homes combines the financial resources, technology platforms and proven leadership of a national organization with the regional insights, longstanding community connections and agility of empowered local teams.

<!-- image -->
-------------------------

2025-12-18 10:36:22,812 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:23,945 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:24,201 - INFO - Processing document i-nexus Global plc1__p4.pdf
2025-12-18 10:36:25,012 - INFO - Finished converting document i-nexus Global plc1__p4.pdf in 3.66 sec.
2025-12-18 10:36:25,052 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:25,054 - INFO - Going to convert document batch...
2025-12-18 10:36:25,055 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:25,056 - INFO - Accelerator device: 'cpu'

i-nexus Global plc1.pdf
## STRATEGIC REPORT: Company Overview

i-nexus provides strategy software to the world's largest organisations who want to achieve more of their goals with less e ff ort, using i-nexus as the place to plan, execute, and track their strategic, transformational, and operational e ff orts so that they can deliver the change they want to see.

## Our purpose

We're  driven  by  our  passion  to  help organisations  thrive  and  deliver  the change they want to see.

Through our intuitive, powerful strategy software, we align everyone and everything in an organisation to help our customers achieve more of their goals with less e ff ort.

## Who we are

Founded in 2001, i-nexus was created from a vision that a learning culture is the foundation for organisational success.

Beginning with operational excellence at the core of the software, industryleading practitioners drove adoption in global  organisations,  soon  leading  to key  Hoshin  Kanri  functionality  -  the x-matrix and bowling chart.

In 2018 the company was admitted to AIM,  marking  a  key  milestone  in  its mission  to  help  organisations  thrive and deliver change.

Today,  i-nexus  is  a  G2  award-winning software provider, powering strategies around the world across manufacturing, industrial engineering, life sciences, and automotives.

## What we value

To  ensure  we  live  and  breathe  our purpose, i-nexus believes that everyone has their PLACE.

Every  i-nexus  employee  represents these values, and it's what helps us to support our customers in delivering the change they want to see:

## · Partnership

We work with the spirit of partnership, seeing our colleagues, customers, and vendors  as  part  of  i-  nexus,  working with  a  common  cause  to  learn  and succeed.

- Leadership

We act with courage to lead by example to shape a better future.

## · Agility

We  strive  for  early  and  continuous delivery, breaking the complex down to the simple so that we can change with our customers.

## · Curiosity

We  are  open  minded  and  actively understand, explore, and try new approaches, with data and learning at the heart of our e ff orts.

- Empathy

We appreciate that there is a person behind every organisation, so we take extra e ff ort to understand and support our colleagues, customers, and vendors.

## The problem we solve

A survey of more than 400 global CEOs found that the ability to execute their goals - both strategic and operational is  the  number  one  challenge  facing leaders.

This reality is crystallized with Gartner's estimates that two thirds of well formulated strategies fail in their delivery phase.

At the heart of the problem is a lack of a single source of truth.

Organisations don't have a place where the  entire  business  can  plan  goals, execute  portfolios  of  projects  tightly aligned  to  these  goals,  and  not  only track, but measure, report, and replicate this across the organisation to create a culture of achievement.

Getting everyone and everything focused and collaborating on goals isn't easy.

This iceberg exists for leaders in every business. Underneath the surface are issues  in  building  shared  purpose, aligning operational work to strategic portfolios,  replicating  best  practices, bringing business and operating systems to life, over-engineering, and proving  the  impact  and  bene fi ts  of programs and projects.

The misalignment, planning silos, disconnected  delivery  of  work,  and manual tracking and reporting is worsened with the use of a patchwork of tools not fi t for purpose.

Taking a strategy-to-action is hard.

## How we solve it

With solutions for the whole organisation, from shop fl oor to c-suite, i-nexus helps customers embrace  the  challenges  of  strategy execution and operational excellence.

## · Strategy execution

i-nexus helps everyone focus and collaborate on delivering the strategy. Designed for strategy o ffi ces and transformation  teams,  i-nexus  links plans, portfolios, and performance metrics for a simpler strategy execution experience whether using Hoshin Kanri, Balanced Scorecard, or a custom business system.
-------------------------

2025-12-18 10:36:26,510 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:27,642 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:27,894 - INFO - Processing document Hybrid Software Group PLC1__p2.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:36:34,653 - INFO - Finished converting document Hybrid Software Group PLC1__p2.pdf in 9.60 sec.
2025-12-18 10:36:34,676 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:34,678 - INFO - Going to convert document batch...
2025-12-18 10:36:34,678 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:34,679 - INFO - Accelerator device: 'cpu'

Hybrid Software Group PLC1.pdf
## CONTENTS

| Hybrid Software Group                                                    |     |
|--------------------------------------------------------------------------|-----|
| Hybrid Software Group                                                    | 1   |
| Digital revolution in print manufacturing                                | 2   |
| The year in review                                                       | 6   |
| Our markets                                                              | 8   |
| Business segments                                                        | 16  |
| Company strategic report                                                 |     |
| Company strategic report                                                 | 23  |
| Chairman's statement                                                     | 24  |
| CEO's review                                                             | 26  |
| CFO's review                                                             | 28  |
| Governance                                                               |     |
| Board of directors                                                       | 44  |
| Directors' report                                                        | 46  |
| Corporate governance report                                              | 52  |
| Audit committee report                                                   | 54  |
| Directors' remuneration report                                           | 55  |
| Independent auditor's report to the members of Hybrid Software Group PLC | 64  |
| Consolidated financial statements                                        |     |
| Notes to the consolidated financial statements                           | 72  |
| Company financial statements                                             | 113 |
| Notes to the Company financial statements                                | 114 |
| Other information                                                        |     |
| Glossary                                                                 | 121 |

Hybrid Software Group

## Hybrid Software Group

Courtesy of HP PageWide

<!-- image -->

Copyright © ABB Company

Financial statements

Copyright © Xaar Plc

Hybrid Software Group PLC  is a public limited-liability company registered in England and Wales with its shares traded on Euronext Brussels under stock code HYSG. It is headquartered near Cambridge, UK.  The Company employs approximately 300 employees worldwide and has a pedigree stretching back more than 30 years.

Hybrid Software Group develops innovative technology for industrial print manufacturing processes which use inkjet and other printing techniques.  The technology is critical because efficiency and sustainability concerns are driving the conversion of manufacturing processes from traditional analogue methods to just-in-time digital production using inkjet printing.  Applications for inkjet printing include a diverse range of goods, from labels and packaging, to textiles, tiles, laminates, wall coverings, additive manufacturing and 3D printing applications.

## Industrial print manufacturing is when printing technology is used in broader manufacturing processes where it isn't the print itself that is being sold.

## Our investment case

- Inkjet adoption is increasing rapidly across multiple industry sectors.
- Analogue markets are converting to digital production.
- Hybrid Software Group enables customers to migrate their traditional manufacturing processes to digital inkjet.
- Hybrid Software Group  is the only vertically integrated supplier to this market.
- Operating companies are awardwinning technology leaders.
- Synergies between companies in the Group, following strategic acquisitions made during the past 3 years, will accelerate innovation and revenue growth.

The Company is the only full stack supplier of all the critical core technologies needed for inkjet printing. Our principal customers are Original Equipment Manufacturers (OEMs) of digital printing equipment, including high-speed digital production presses, professional colour proofing devices, wide format colour printers, and industrial inkjet printers for ceramic tiles, packaging, textiles and additive manufacturing, as well as end users, primarily printing companies who purchase these devices to print and convert labels and packaging materials.

Hybrid Software Group has traditionally provided software components and printhead drive electronics to OEMs to enable them to build their own solutions.  However, the strategic acquisitions made over the last several years now enable the Company to provide full turnkey solutions for OEMs which enable them to bring new digital printing devices to market faster and with higher quality .  These solutions are higher value and provide more revenue to the Company per device installed.  Furthermore, the OEM business is synergistic with the Company's end-user products, accelerating revenue growth and increasing the Company's market share in the inkjet space.

Governance
-------------------------

2025-12-18 10:36:36,136 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:37,272 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:37,528 - INFO - Processing document KRM22 Plc1__p13.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:36:45,448 - INFO - Finished converting document KRM22 Plc1__p13.pdf in 10.77 sec.
2025-12-18 10:36:45,477 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:45,481 - INFO - Going to convert document batch...
2025-12-18 10:36:45,482 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:45,483 - INFO - Accelerator device: 'cpu'

KRM22 Plc1.pdf
## OUR PRODUCTS

Built on the Global Risk Platform, KRM22 offer products addressing risk management challenges across Corporate and Trading risk.  By layering on data from throughout a customer's environment, customers are now able to better assess, monitor and manage the increasing correlation between these risk areas.

## The Global Risk Platform

The KRM22 Global Risk Platform is a cloud-based SaaS service for Corporate and Trading risk that securely connects and integrates into existing and new client portals from one integrated system.

<!-- image -->

## Corporate Risk

## Risk Cockpit

The Risk Cockpit is a digital risk register that brings risk policies and operational controls to life through a proven risk assessment workflow

- Enforce risk controls
- Capture, assess and remediate events
- Track and understand metrics
- Generate regulatory and historic reporting

<!-- image -->
-------------------------

2025-12-18 10:36:46,959 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:48,056 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:48,312 - INFO - Processing document Pelatro Plc1__p6.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:36:54,998 - INFO - Finished converting document Pelatro Plc1__p6.pdf in 9.52 sec.
2025-12-18 10:36:55,022 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:36:55,025 - INFO - Going to convert document batch...
2025-12-18 10:36:55,026 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:36:55,026 - INFO - Accelerator device: 'cpu'

Pelatro Plc1.pdf
## Strategic Report - About Pelatro

For the year ended 31 December 2022

Pelatro is a focused and specialised solution provider predominantly in the telecom marketing space but with an increasing presence in non-telco sectors where 'Big Data' is increasingly seen as an under-exploited resource. We enable data-rich companies  across  the  globe  to  increase  revenue  and  reduce  customer  churn  through  our  enterprise  grade  software solutions.  Telecom  operators,  for  example,  can  analyse  the  behaviour  of  the  subscribers  within  their  network,  create individual  profiles  to  suggest  appropriate  products  and  promotions  in  a  segment  of  one  manner  to  enable  higher consumption and an increased level of customer satisfaction.

## Technology

Our solutions employ Big Data technology to collect and process data in real time. Our technologically advanced products are telco-grade with significant scalability, security and high availability. As data is processed in real time, the output from our solutions is also in real time and is relevant and contextual, leading to similarly relevant, contextual and personalised interventions in real time, in the form of marketing campaigns and promotions to subscribers, resulting in improved results as  compared  to  legacy  solutions.  In  order  to  provide  high  quality  marketing  campaigns  and  promotions,  our  solutions employ AI/ML techniques coupled with various algorithms, models etc. This results in a high level of predictive, descriptive and prescriptive analytics in our solutions.

## Products

The  mViva  Customer  Engagement  Hub  is  a  suite  of  solutions  designed  for  deep  engagement  between  telcos  and  its customers to increase revenue and reduce churn. The mViva suite offers solutions for Contextual Campaign Management, Loyalty Management, and Data Monetisation in a single integrated tool that enables teams to deliver effective customer interactions that maximize value, at high work velocity. Its ready-to-use propensity models and data analytics functionality is optimised for Campaign Analysts to anatomise customer data, to launch precisely targeted campaigns not just to microsegments but to segments-of-one. The seamless, intuitive, and concise campaign management workflow enables teams to easily extend campaign management services to enterprise customers and monetize subscriber data.

The mViva suite empowers Customer Value Management ('CVM') teams to rapidly design and deploy campaigns, launch loyalty  programs  to  reduce  churn  of  customers  and  provide  omni-channel  communication.  The  mViva  Customer Engagement Hub offers three key solutions tailor-made for CVM Teams:

<!-- image -->

<!-- image -->

mViva Contextual Campaign Management Solution - a comprehensive tool to design, configure and run campaigns to manage the entire lifecycle for subscribers, retailers and enterprises mViva  Loyalty  Management  Solution  -  enables  design  and  launch  of  loyalty  programs  to  reward  and  retain customers

mViva Data Monetisation Platform Solution - enables teams to easily extend campaign management services to other B2C enterprises and brands in order for the telco to monetise subscriber data
-------------------------

2025-12-18 10:36:56,483 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:57,635 - INFO - Accelerator device: 'cpu'
2025-12-18 10:36:57,888 - INFO - Processing document ePlay Digital Inc.3__p6.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:37:11,080 - INFO - Finished converting document ePlay Digital Inc.3__p6.pdf in 16.06 sec.
2025-12-18 10:37:11,103 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:11,105 - INFO - Going to convert document batch...
2025-12-18 10:37:11,105 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:11,106 - INFO - Accelerator device: 'cpu'

ePlay Digital Inc.3.pdf
I

## who we are

<!-- image -->

## G.O.D. FOUNDED

Devolver's founders have a long track record of innovating together in the video games industry. In 1998 Harry Miller, Rick Stults and Mike Wilson co-founded the video games publishing brand Gathering of Developers, also known as G.O.D. Games.

1998

1999

## GAMECOCK MEDIA GROUP ESTABLISHED

Harry, Rick and Mike reunited in 2007 to found video games publisher Gamecock Media Group ('Gamecock'). Devolver co-founders Graeme Struthers and Nigel Lowrie later joined Gamecock, working on their first venture with Harry, Rick and Mike.

## 2000 2001 2002 2003 2004 2005 2006

G.O.D. ACQUIRED BY TAKE-TWO INTERACTIVE

Devolver is an award-winning digital video games publisher and developer in the indie games space.

Recently awarded 'Best Publisher' by Games Village Awards 2022, Devolver has one of the most recognisable labels in the indie market. Built over a decade by highly experienced industry veterans with deep, wide-ranging relationships in the gaming sector, Devolver has a back catalogue of over 100 games, including a number of indie cult classics.

## DEVOLVER FOUNDED

Devolver was formed as a digital-only developer-first publisher, which principally released titles on PC via Steam. Working with original developer Croteam and other small studios, Devolver successfully published several games in the Serious Sam series for release on PC and mobile.

2007

2008

GAMECOCK WAS SOLD TO SOUTHPEAK GAMES

<!-- image -->

<!-- image -->

2009

2010 2011

2012

## HOTLINE MIAMI RELEASED

Following the early financial success of the Serious Sam series, the Group branched out and began collaborating on new franchises and titles with other development studios. Devolver's first breakout hit was Hotline Miami in 2012. It received critical acclaim, putting Devolver in the indie spotlight.
-------------------------

2025-12-18 10:37:12,562 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:13,702 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:13,956 - INFO - Processing document AI Conversation Systems Ltd1__p18.pdf
2025-12-18 10:37:16,179 - INFO - Finished converting document AI Conversation Systems Ltd1__p18.pdf in 5.08 sec.
2025-12-18 10:37:16,204 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:16,205 - INFO - Going to convert document batch...
2025-12-18 10:37:16,206 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:16,207 - INFO - Accelerator device: 'cpu'

AI Conversation Systems Ltd1.pdf
## in Singapore)

Systems  Africa  for  Information  Technologies  (Pty.)  Ltd.,  a  limited  liability  company  incorporated  in  the Republic of South Africa on July 28, 2022, for the purpose of sale of software services and trading software licenses in the region.

Systems Limited acquired 100% stake in National Data Consultants (Pvt.) Limited 'NdcTech'. NdcTech has been a leading core banking implementation service provider for the past 22 years and has a rich set of clients in Pakistan, Middle East, Africa and Asia Pacific region.

## Associated companies of Group:

SalesFlo (Private) Limited (formerly Retailistan (Private) Limited) provides a leading Sales and  Distribution Platform called SalesFlo that is trusted by a number of large FMCG manufacturers. It's a SaaS B2B platform that  allows  stores  to  place  orders  directly  to  manufacturers/wholesalers/authorized  distributors  on the platform. The platform covers Distribution Management System, Digital Merchandising and Instore Marketing tool, and Data science solutions (Data Analytics). Currently used by around 15,000 distributor agents  through  FMCGs.  Retailistan  has  a  wholly  owned  subsidiary  called  Jugnu,  which  is  an  online marketplace accessible through a mobile app to enable retailers to buy a variety of products. Jugnu buys from manufacturers and distributors, stores in their warehouses and deliver next day based on orders received from retailers. So it's a B2B E-commerce play. Systems Ventures holds 20% in Retailistan.

E-Processing Systems B.V. (EPS), a private limited Company registered in Netherlands, is a 44.60% owned associate of Systems Limited. EPS is currently engaged in the business of purchase and sale of teleco's airtime and related services. The product of the Company is called OneLoad. The Company is in the process of launching OneZap under E-Money license from State Bank of Pakistan (SBP).

The financial statements of the Company and the Group truly reflect the state of Company's affairs and fair review of their business.

## ACTIVITIES:

The Company's revenue comes primarily from Digital/Data/Cloud Services, Managed Services, Consulting Services, IT outsourcing and Business Process Outsourcing/Contact Center. The Company generates over 80% of it's revenue from export of Services to various geographies such as North America, Europe and Middle East, Africa and others and less than 20% from domestic market. The Company is well diverisified into various business verticals such as Telco, Retail, CPG, Pharma, Banking and Public sector.

## FINANCIAL PERFORMANCE OF THE COMPANY AND THE GROUP DURING 2022

## Unconsolidated:

The Company's financial results for FY22 have maintained a strong trajectory. Operating revenues for the year in local currency were Rs. 20,644.7 million showing a growth of 73% over the previous year. Profit after tax for the year was Rs. 6,299.8 million showing a growth of 90%. Gross profit and operating profit increased by 69% and 73% respectively. Since FY18, the Company has delivered a Compounded Annual Growth Rate (CAGR) in revenues of 53%. The revenue growth has been mainly driven by IT services and profitability growth has been driven by demand and growth across all geographies and all verticals. Revenue in USD also showed a growth of 38% and profit growth of 51%.

| Unconsolidated               | Unconsolidated   | Unconsolidated   | Unconsolidated   |
|------------------------------|------------------|------------------|------------------|
| Particulars                  | FY 2022          | FY 2021          | Y/Y              |
| Revenue                      | 20,644,764,716   | 11,903,583,911   | 73%              |
| Gross profit                 | 6,755,105,438    | 3,991,141,283    | 69%              |
| Operating Profit             | 4,871,976,394    | 2,816,512,795    | 73%              |
| Profit before taxation       | 6,624,487,917    | 3,352,565,630    | 98%              |
| Profit after taxation        | 6,299,836,945    | 3,320,691,476    | 90%              |
| Earnings per share (basic)   | 22.44            | 12.06            | 86%              |
| Earnings per share (diluted) | 22.29            | 11.98            | 86%              |

<!-- image -->
-------------------------

2025-12-18 10:37:17,769 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:18,903 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:19,160 - INFO - Processing document Encompass Compliance Corp.1__p45.pdf
2025-12-18 10:37:20,813 - INFO - Finished converting document Encompass Compliance Corp.1__p45.pdf in 4.61 sec.
2025-12-18 10:37:20,838 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:20,840 - INFO - Going to convert document batch...
2025-12-18 10:37:20,841 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:20,841 - INFO - Accelerator device: 'cpu'

Encompass Compliance Corp.1.pdf
## EXECUTIVE COMPENSATION

## Compensation Discussion and Analysis

This section presents the key components of our executive compensation program. We explain why we compensate our executives in the manner we do and how these philosophies guide the individual compensation decisions for our named executive officers, or 'NEOs.' Our 2022 compensation decisions were directed by our board of directors and its Compensation and Human Capital Committee, which we refer to as the 'Committee' in this section only. Our NEOs for 2022, whose compensation arrangements are discussed in this proxy statement, are:

| Name                                                                                                                                      | Title                                                                                                                                     |
|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| Mark J. Tarr                                                                                                                              | President and Chief Executive Officer                                                                                                     |
| Douglas E. Coltharp                                                                                                                       | Executive Vice President and Chief Financial Officer                                                                                      |
| Patrick Darby                                                                                                                             | Executive Vice President, General Counsel and Secretary                                                                                   |
| Elissa J. Charbonneau                                                                                                                     | Chief Medical Officer                                                                                                                     |
| Andrew L. Price                                                                                                                           | Chief Accounting Officer                                                                                                                  |
| Barbara A. Jacobsmeyer 1                                                                                                                  | Chief Executive Officer, Home Health and Hospice                                                                                          |
| Note: Ms. Jacobsmeyer ceased serving as an officer of Encompass Health upon the spin off of Enhabit Home Health& Hospice on July 1, 2022. | Note: Ms. Jacobsmeyer ceased serving as an officer of Encompass Health upon the spin off of Enhabit Home Health& Hospice on July 1, 2022. |

## EXECUTIVE SUMMARY

## Strategy and Business Overview

Encompass Health is a leading provider of inpatient rehabilitation healthcare services, offering facility-based patient care through our network of inpatient rehabilitation hospitals. As of December 31, 2022, our national footprint spans 36 states and Puerto Rico and includes 153 hospitals. We are committed to delivering high-quality, cost effective patient care. Until July 1, 2022, we managed our operations in two operating segments: (1) inpatient rehabilitation and (2) home health and hospice ('HHH'). On July 1, 2022, we separated the HHH business from Encompass Health into an independent public company through a spin-off distribution. In connection with the spin off, the HHH business rebranded and now operates under the name Enhabit Home Health &amp; Hospice.

## 2022 Business Highlights and Recent Track Record

Our clinicians have consistently provided high quality, compassionate care to patients in need of our services. The dedication of our team members allowed us to make significant operational and strategic progress and to generate strong financial results in 2022:

## Operational Achievements

- ü We completed the spin-off distribution of the HHH business unit (Enhabit).
- ü Our overall patient discharges and 'same store' discharges increased by 6.8% and 3.1%, respectively.
- ü Inpatient net operating revenues increased 8.3% over 2021.
- ü Our hospital teams delivered high-quality outcomes in a cost-effective manner.
- ü We entered new markets and enhanced our geographic coverage in existing markets in 2022 by adding nine new hospitals. We also expanded existing hospitals by 87 beds.

## Quality of Care and Outcomes for Our Patients

- ü We continued to outperform the industry averages in the inpatient rehabilitation quality of care measures of discharge to community and discharge to skilled nursing.
- ü 131 of our hospitals hold one or more Joint Commission specialty accreditations in rehabilitation.
- ü We improved our ability to deliver quality care to more patients as a result of 427 net same-store RN hires in a challenging labor market.
-------------------------

2025-12-18 10:37:22,293 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:23,454 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:23,703 - INFO - Processing document Aurum Proptech Limited2__p3.pdf
/data/resources/weichel-llama3/work/projects/nace_classification/nace_report_topic_analysis/nace_git/lib/python3.10/site-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
2025-12-18 10:37:46,633 - INFO - Finished converting document Aurum Proptech Limited2__p3.pdf in 25.80 sec.
2025-12-18 10:37:46,657 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:46,660 - INFO - Going to convert document batch...
2025-12-18 10:37:46,661 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:46,661 - INFO - Accelerator device: 'cpu'

Aurum Proptech Limited2.pdf
## Across the PAges

## Company Overview 01-36

| Aurum PropTech Ecosystem Snapshot                                 |   2 |
|-------------------------------------------------------------------|-----|
| Aurum Group:                                                      |   3 |
| Aurum Group's Inspiring Growth Journey                            |   4 |
| Group CEO 's Communique                                           |   6 |
| A Journey of Growth                                               |  10 |
| Aurum Ecosystem                                                   |  11 |
| Catalyzing the Growth of Real Estate through PropTech Innovations |  12 |
| The Aurum Approach                                                |  13 |
| Value Creation Model                                              |  14 |
| Our GRC Framework                                                 |  15 |
| Business Overview                                                 |  18 |
| Unleashing Purpose Beyond Profit                                  |  30 |
| Board of Directors                                                |  34 |
| Company Information                                               |  36 |

## Management Review 37-45

Management Discussion &amp; Analysis

Technology, Capital &amp; Services

Governance, Risk and Compliance

## Governance

Board's Report

Corporate Governance Report

## Financial Statements 96-215

Standalone

Consolidated

Notice

37

40

41

46

68

96

154

217

## 46-94

## Click the link below for more information:

https://www.aurumproptech.in/

## Or scan this QR code:

<!-- image -->

## Investor Information

| CIN            | L72300MH2013PLC244874   |
|----------------|-------------------------|
| BSE Code       | 539289                  |
| NSE Symbol     | AURUM                   |
| Bloomberg Code | AURUM:IN                |
| AGMDate        | September 28, 2023      |
| AGMVenue       | Video Conferencing      |

Disclaimer: This document contains statements about expected future  events  and  financials  of  Aurum  Proptech  Limited  ('The Company'), which are forward-looking. By their nature, forwardlooking  statements  require  the  Company  to  make  assumptions and  are  subject  to  inherent  risks  and  uncertainties.  There  is  a significant  risk  that  the  assumptions,  predictions,  and  other forward-looking statements  may  not  prove  to be accurate. Readers are cautioned not to place undue reliance on forwardlooking statements as several factors could cause assumptions, actual future results, and events to differ materially from those expressed  in  the  forward-looking  statements.  Accordingly,  this document is subject to the disclaimer and qualified in its entirety by the assumptions, qualifications, and risk factors referred to in the Management Discussion and Analysis section of this annual report.

## Unleashing Potential: igniting growth

Aurum PropTech ('Aurum' or 'The Company') is a new-age PropTech company  dedicated  to  revolutionizing the  real  estate  industry.  The  Company is  building  a  comprehensive  PropTech ecosystem that combines tech expertise with  a  real  estate  domain  journey  that elevates  the  experience  for  creators, consumers,  and  capital  allocators.  At the nexus of technology and innovation lies  Aurum  PropTech,  where  we  are diligently crafting an integrated PropTech  ecosystem that spans the entire  spectrum  of  real  estate  value creation.

We build and operate PropTech products, services, and platforms catering to the intricacies of the B2B, B2C, B2B2C, and D2C Real Estate  Value  Chains.  Our  comprehensive  suite  of  integrated ecosystems  incorporates  cutting-edge  technologies  such  as Artificial Intelligence, Machine Learning, Blockchain, Augmented Reality, and Virtual  Reality.  This  robust  portfolio addresses the needs of both individual consumers and enterprises, providing a holistic array of services.

Driving  this  vision  forward  is  a  seasoned  leadership  team  that boasts an impressive track record of leveraging strategic technological integrations to reshape the real estate landscape. At Aurum PropTech, we are firm believers that anchoring people at the core of technological advancements is the pivotal approach to ushering in a brighter tomorrow. We believe that putting people at the heart of technology is the way to prepare them for a better future.
-------------------------

2025-12-18 10:37:48,116 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:49,301 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:49,556 - INFO - Processing document Telekom Srpske AD2__p10.pdf
2025-12-18 10:37:50,301 - INFO - Finished converting document Telekom Srpske AD2__p10.pdf in 3.64 sec.
2025-12-18 10:37:50,320 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:50,322 - INFO - Going to convert document batch...
2025-12-18 10:37:50,323 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:50,324 - INFO - Accelerator device: 'cpu'

Telekom Srpske AD2.pdf
## Telekom Srbija a.d. Beograd mts.rs

Telekom  Srbija  is  one  of  the  leading  telecommunications  operators  in  the territory of Serbia in all business segments. It was set up on 23 May 1997 in the process of the structural and ownership transformation of the PTT system of Serbia, as a single-member joint stock company. From June that same year, it was owned by three shareholders: JP PTT saobraćaja 'Srbija' (present-day JP 'Pošta Srbije'), Telecom Italia and OTE Greece. In 1998, it began to provide mobile services. In 2006, we introduced 3G technology and the provision of ADSL Internet services.

As  early  as  in  2007,  Telekom  Srbija  became  the  leader  in  the  sphere  of telecommunications  and  began  to  expand  to  the markets  of  BosniaHerzegovina and Montenegro. This is how Telekom Srbija Group was set up. In the following years, it successfully kept abreast of market demands and also recognized the importance of introducing fresh services, creating the potential for entering new markets. Apart from the basic telecommunications services, at  present  it  is  substantially  focused  on  the  development  and  provision  of multimedia, financial and digital products and services, as well as projects of exceptional importance for all people in the diaspora. Telekom Srbija has no branches.

The ownership structure of Telekom Srbija is detailed on the website of the Central  Securities  Depository  and  Clearing  Registry.  Telekom  Srbija  has ownership in the following subsidiaries:

## Telekom Srpske a.d. Banja Luka mtel.ba

One of the three national telecom operators in Bosnia-Herzegovina, it offers unique  communications  solutions  integrated  under  the  corporate  brand  of m:tel. The following subsidiaries are owned by it:

-  MTEL d.o.o. Podgorica (49% ownership)
-  MTEL Global d.o.o. Beograd (41% ownership)
-  Logosoft  d.o.o.  Sarajevo,  100%  it  owns  Mts  Sistemi  i  integracije,  Beograd (100% share)
-  Blicnet d.o.o. Banja Luka (100% stake)
-  Financ d.o.o. Banja Luka (100% stake)

## mtel d.o.o. Podgorica mtel.me

In April 2007, mtel Podgorica  obtained a third-operator licence in the territory of Montenegro. Its ownership structure is as follows: 51% Telekom Srbija, 49% Mtel Banja Luka.

After obtaining the licence for the operation of the mobile network, a stateof-the-art mobile network was built within a period of only 77 days, a period unrecorded so far.

## ARENA CHANNELS GROUP d.o.o. Beograd tvarenasport.com

Arena Channels Group is a company dealing with cable telecommunciations via the Arena Sport TV channel and is the holder of the broadcasting rights for sports channels in the territory of the Republic of Serbia, Bosnia-Herzegovina, Montenegro, North Macedonia, Croatia and Slovenia.

Arena Channels Group broadcasts the signal of Euronews Serbia, which is a branded affiliation of Euronews and which broadcasts local, regional, national and international news on TV and digital platforms produced by its own team of journalists and correspondents. Euronews Serbia is an information channel committed to objective, impartial and accurate reporting, which the Euronews family and its media promote wherever they are present.

Thanks to the successful cooperation between Bloomberg Media and Arena Channels  Group,  launched  was  Bloomberg  Adria,  the  first  pan-regional multiplatform  business  news  network  in  Southeast  Europe,  with  centers in Serbia, Croatia, Slovenia, Bosnia-Herzegovina and North  Macedonia. Bloomberg  Adria  covers  business  and  financial  news,  analysis  and  data  on the growing community of business decision-makers and future leaders in the region, via electronic (TV), print and digital media as well as mobile and social networks. Bloomberg Adria relies on the strength of Bloomberg journalists and analysts around the world in the creation and successful operation of the new platform,  which  combines  local  reporting  and  coverage  of  the  broad  global economy and markets.

Arena Channels Group owns the following subsidiaries:

-  MTEL Swiss SA Ženeva (63,24% stake)
-  HD WIN Arena sport d.o.o. Zagreb (100% stake)
-  Arena News Channels d.o.o. Beograd (100% stake)
-  Arena sport d.o.o. Ljubljana (50% stake)
-  ACG d.o.o.  Sarajevo,  100%  it  owns  Arena  Sport  BH  doo  Sarajevo  (100% stake).

## Mtel Global d.o.o. Beograd mtel.global

Mtel Global was created by integrating the companies which belong to Telekom
-------------------------

2025-12-18 10:37:51,770 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:52,894 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:53,150 - INFO - Processing document AcuityAds Holdings Inc1__p4.pdf
2025-12-18 10:37:53,886 - INFO - Finished converting document AcuityAds Holdings Inc1__p4.pdf in 3.57 sec.
2025-12-18 10:37:53,906 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:53,908 - INFO - Going to convert document batch...
2025-12-18 10:37:53,908 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:53,909 - INFO - Accelerator device: 'cpu'

AcuityAds Holdings Inc1.pdf
outlook and future-oriented financial information contained herein should not be used for purposes other than those for which it is disclosed herein.

Readers are cautioned not to place undue reliance on these forward-looking statements, which speak only as of the date of the MD&amp;A or as of the date otherwise specifically indicated herein. Due to risks and uncertainties, including the risks and uncertainties elsewhere in this MD&amp;A, actual events may differ materially from current expectations. These risks and uncertainties include, among other things, the factors discussed in 'Risk Factors' section of this MD&amp;A and under the 'Risk Factors' section of the  Annual  Information  Form  for  the  year  ended  December  31,  2021  available  on  SEDAR  at www.sedar.com. The Company disclaims any intention or obligation to update or revise any forwardlooking statements, whether as a result of new information, future events or otherwise. All forwardlooking statements contained in the MD&amp;A are expressly qualified in their entirety by this cautionary statement.

## OVERVIEW

AcuityAds is a technology company that enables marketers to connect intelligently with audiences across  video,  mobile,  social  and  online  display  advertising  campaigns.  AcuityAds'  Programmatic Marketing Platform, powered by proprietary machine learning technology, is at the core of its business, accompanied by patented solutions for analytics-led video and mobile targeting that leverages data. AcuityAds  empowers  marketers  by  offering  near  real-time  reporting and analytics, bringing accountability to programmatic advertising to deliver business results and help solve the key challenges that digital advertisers face. AcuityAds is headquartered in Toronto and has offices in the U.S., Canada, Spain, France, Brazil, Chile, Mexico, Colombia and Argentina. Its key customers include both agencies and brands, including large Fortune 500 enterprises and small to mid-sized businesses. AcuityAds' technology enables programmatic advertising, which is the automated buying and selling of advertising inventory electronically. The platform is based on proprietary machine learning technology, the branch of artificial intelligence involving systems that learn from data inputs and outputs and can perform actions without the need for explicit programming.  The platform has the capability to process billions of bid requests on a daily basis. AcuityAds' Programmatic Marketing Platform allows advertisers to manage their purchasing of online display advertising in real-time using programmatic ad buying, a method of buying online display advertising in which ad spots (called impressions) are released in an auction  that  occurs  in  milliseconds.  AcuityAds  purchases  impressions  for  advertisers  through agreements with publishers, ad networks and ad exchanges. Its technology platform benefits advertisers by enabling them to target specific audiences based on demographic and psychographic parameters as well as manage their bid amounts to purchase the advertising inventory that is most relevant for their campaigns. Real-time reporting enables advertisers to monitor specific performance metrics and react and pivot quickly to optimize campaigns to help ensure they achieve consumer targeting goals and key performance  indicators.  On  October  1,  2020,  the  Company  officially  launched  its  advertising automation platform, illumin™. illumin is an advertising automation technology that offers planning, buying  and  omnichannel  intelligence  from  a  single  platform,  allowing  advertisers  to  map  their consumer journey playbooks across screens and execute in real-time using programmatic technology. illumin  enables  creation  of  consumer  journeys  with  custom  messages  tied  to  propensity-scored audiences, increasing efficiency and return on advertising investments. For the three and six months ended June 30, 2022, revenue derived from illumin was $10,244,059 and $18,106,807 compared to $5,223,396 and $8,429,555 revenue in the comparable 2021 period.
-------------------------

2025-12-18 10:37:55,356 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:56,701 - INFO - Accelerator device: 'cpu'
2025-12-18 10:37:56,954 - INFO - Processing document Verb Technology Company, Inc.1__p10.pdf
2025-12-18 10:37:57,728 - INFO - Finished converting document Verb Technology Company, Inc.1__p10.pdf in 3.82 sec.
2025-12-18 10:37:57,746 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:37:57,748 - INFO - Going to convert document batch...
2025-12-18 10:37:57,749 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:37:57,750 - INFO - Accelerator device: 'cpu'

Verb Technology Company, Inc.1.pdf
## 1. DESCRIPTION OF BUSINESS

## Our Business

References in this Quarterly Report to the 'Company,' 'Verb,' 'we,' 'us,' or 'our' are to Verb Technology Company, Inc., together with its consolidated subsidiaries unless the context otherwise requires. Throughout this Quarterly Report, the terms 'client' and 'customer' are used interchangeably.

The Company is a SaaS applications platform developer. Our platform is comprised of a suite of interactive video-based sales enablement business software products marketed on a subscription basis. Our applications, available in both mobile and desktop versions, are offered as a fully integrated suite, as well as on a standalone basis, and include verbCRM, our Customer Relationship Management ('CRM') application, verbLEARN, our Learning Management System application, verbLIVE, our Live Stream eCommerce application, verbPULSE, our business/augmented intelligence notification and sales coach application, and verbTEAMS, our self-onboarding videobased CRM and content management application for professional sports teams, small business and solopreneurs, with seamless synchronization with Salesforce, that also comes bundled with verbLIVE, and verbMAIL, our interactive video-based sales communication tool integrated into Microsoft Outlook. MARKET.live is our multivendor, multi-presenter, livestream social shopping platform that combines ecommerce and entertainment.

The Company also provides certain non-digital services to some of its enterprise clients such as printing and fulfillment services.

## Economic Disruption

Our business is dependent in part on general economic conditions. Many jurisdictions in which our customers are located and our products are sold have experienced and could continue to experience unfavorable general economic conditions, such as inflation, increased interest rates and recessionary concerns, which could negatively affect demand for our products. Under difficult economic conditions, customers may seek to cease spending on our current products or fail to adopt our new products, which could negatively affect our financial performance. We cannot predict the timing or magnitude of an economic slowdown or the timing or strength of any economic recovery. These and other economic factors could have a material adverse effect on our business, financial condition, and results of operations.

## COVID-19

As of the date of this filing, there continues to be concern regarding the ongoing impacts and disruptions caused by the COVID-19 pandemic in the regions in which the Company operates. Although the impacts of the pandemic on our business have not been material to date, a prolonged downturn in economic conditions as a result of the pandemic could have a material adverse effect on our customers and demand for our products. At this time, it is not possible for the Company to predict the duration or magnitude of the impacts of the pandemic, or other outbreaks of communicable diseases, on the Company's business, financial condition and results of operations.

## 2. SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES AND SUPPLEMENTAL DISCLOSURES

## Basis of Presentation

The  accompanying  condensed  consolidated  financial  statements  are  unaudited.  These  unaudited  interim  condensed  consolidated  financial  statements  have  been prepared in accordance with accounting principles generally accepted in the United States of America ('GAAP') and applicable rules and regulations of the Securities and Exchange Commission ('SEC') regarding interim financial reporting. Certain information and note disclosures normally included in the financial statements prepared in accordance with GAAP have been condensed or omitted pursuant to such rules and regulations. Accordingly, these interim condensed consolidated financial statements should be read in conjunction with the consolidated financial statements and notes thereto contained in the Company's Annual Report on Form 10-K for the fiscal year ended December 31, 2021 filed with the SEC on March 31, 2022 (the '2021 Annual Report'). The consolidated balance sheet as of December 31, 2021 included herein was derived from the audited consolidated financial statements as of that date.

In  the  opinion  of  management,  the  accompanying  unaudited  condensed  consolidated  financial  statements  contain  all  adjustments  necessary  to  fairly  present  the Company's financial position and results of operations for the interim periods reflected. Except as noted, all adjustments contained herein are of a normal recurring nature. Results of operations for the fiscal periods presented herein are not necessarily indicative of fiscal year-end results.

## Principles of Consolidation

The condensed consolidated financial statements have been prepared in accordance with GAAP and include the accounts of Verb, Verb Direct, LLC, Verb Acquisition Co., LLC, and verbMarketplace, LLC. All intercompany accounts have been eliminated in the consolidation.

## VERB TECHNOLOGY COMPANY, INC.

## Notes to Condensed Consolidated Financial Statements For the Three and Nine Months Ended September 30, 2022 and 2021 (in thousands, except share and per share data) (unaudited)
-------------------------

2025-12-18 10:37:59,196 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:00,340 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:00,596 - INFO - Processing document Blackbird PLC1__p3.pdf
2025-12-18 10:38:01,292 - INFO - Finished converting document Blackbird PLC1__p3.pdf in 3.55 sec.
2025-12-18 10:38:01,312 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:38:01,313 - INFO - Going to convert document batch...
2025-12-18 10:38:01,314 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:38:01,315 - INFO - Accelerator device: 'cpu'

Blackbird PLC1.pdf
- o Net loss after tax £1,917k (12 months to 31 December 2021: net loss after tax £2,135k) due to a worse EBITDA pre LTIP provision and share option costs offset by the LTIP movement and a higher R&amp;D tax credit in 2022 compared to the prior year
- o Net cash outflow, ignoring proceeds from share issues and transfers into short-term deposits, increased to £2,746k (12 months to 31 December 2021: £1,468k) due to £793k costs associated with our Blackbird SaaS platform and £491k increase in trade debtors due to timing of payments from a few customers (these balances were settled in 2023)
- o At 31 December 2022 the Company had cash and short-term deposits of £10,099k (2021: £12,839k) and no debt

## Enquiries:

## Blackbird plc

Tel: +44 (0)20 8879 7245

Ian McDonough, Chief Executive Officer Stephen White, Chief Operating and Financial Officer

## Allenby Capital Limited (Nominated Adviser and Broker)

Tel: +44 (0)20 3328 5656

Nick Naylor / Piers Shimwell (Corporate Finance)

Amrit Nahal (Equity Sales)

## About Blackbird plc

Blackbird plc operates in the fast-growing SaaS and cloud video market. It has created Blackbird®, the world's most advanced suite of cloud-native computing applications for video, all underpinned by its lightning-fast codec. Blackbird plc's patented technology allows for frame accurate navigation, playback, viewing and editing in the cloud. Blackbird® enables multiple applications, which are used by rights holders, broadcasters, sports and news video specialists, esports, live events and content owners, post-production houses, other mass market digital video channels and corporations.

Since it is cloud-native, Blackbird® removes the need for costly, high-end workstations and can be used from almost anywhere on almost any device. It also allows full visibility on multi-location digital content, improves time to market for live content such as video clips and highlights for digital distribution, and ultimately results in much more effective monetisation.

Blackbird plc is a licensor of its core video technology under its 'Powered by Blackbird' licensing model. Enabling video companies to accelerate their path to true cloud business models, licensees benefit from power and carbon reductions, cost and time savings, less hardware and bandwidth requirements and easy scalability.
-------------------------

2025-12-18 10:38:02,761 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:03,892 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:04,146 - INFO - Processing document Expensify, Inc.1__p10.pdf
2025-12-18 10:38:04,900 - INFO - Finished converting document Expensify, Inc.1__p10.pdf in 3.59 sec.
2025-12-18 10:38:04,919 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2025-12-18 10:38:04,921 - INFO - Going to convert document batch...
2025-12-18 10:38:04,922 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e647edf348883bed75367b22fbe60347
2025-12-18 10:38:04,922 - INFO - Accelerator device: 'cpu'

Expensify, Inc.1.pdf
## Part I.

## Item 1. Business

## OVERVIEW

Expensify is a cloud-based expense management software platform that helps the smallest to the largest businesses simplify the way they manage money. Every day, people from all walks of life in organizations around the world use Expensify to scan and reimburse receipts from flights, hotels, coffee shops, office supplies and ride shares. Since our founding in 2008, we have added over 11 million members to our community, and processed and automated over 1.2 billion expense transactions on our platform, freeing people to spend less time managing expenses and more time doing the things they love. For the quarter ended December 31, 2021, an average of 711,000 paid members across 53,000 companies and over 200 countries and territories used Expensify to make money easy.

Small and medium businesses ('SMBs') are the cornerstone of the global economy, making up almost all businesses and the majority of employment in OECD countries. Despite their significance, the vast majority of SMBs still rely on manual, inefficient processes to manage the critical back office functions that power their businesses every day. Expense management, which refers to the collection, processing, auditing and reimbursement of employee expenses, is one of the last great holdouts of paper-based back office processes, with employees stuffing actual physical receipts into an envelope and handing it to their accountant. As SMBs seek to modernize back office functions like expense management to better compete in today's digital economy, we believe they will look for comprehensive technologies that are easy to discover, implement, purchase, manage and use. At the same time, individual employees are becoming a powerful source of change as they increasingly expect to bring their own choice of technology into the workplace.

Since the beginning of Expensify, our North Star has been improving the experience of the actual end users of expense management software: everyday employees. We designed Expensify to be easy to set up, integrate, configure and use from any device, which has enabled us to serve employees of all types and organizations of all sizes, industries and geographies. Our first breakthrough was revolutionizing receipt tracking with our patented scanning technology, SmartScan, which allows anyone to simply take a photo of any receipt - no matter the currency or quality of handwriting - for fast, automatic and accurate transcription of a receipt with just one tap. After removing the need for people to keep a pocket full of crumbled receipts and spend hours manually tracking expenses, we moved on to automating the entire expense journey, from the initial receipt scan all the way through to categorization, expense approval, reconciliation and next-day reimbursement. Since then, we have expanded our platform to include features that help businesses manage corporate credit cards, generate and send invoices, pay bills and book travel, all from our single, easy-to-use mobile application. We intend to continue adding complementary features to retain and add value to existing customers and attract new members.

Our intense focus on improving the everyday experience of regular employees with an easy-to-use but powerful platform has enabled a viral, 'bottom-up' business model that is capital efficient and extremely scalable. By allowing people to spend less time managing receipts and more time pursuing their real goals, our members have adopted, championed and spread Expensify to their colleagues, managers and friends. We believe our happy members are the best form of marketing, and our self-service, bottom-up approach takes advantage of strong, organic word-of-mouth adoption.

Behind our platform is a company with passionate people and a unique culture that guides everything we do. Our company operates with a flat, generalist organizational structure united by a robust set of common values that foster the long-term happiness and retention of our employees. The efficiency of our business model allows us to prioritize attracting, retaining and inspiring talented, ambitious and humble people committed to a long-term vision. We are a team that likes to solve real problems, and
-------------------------

2025-12-18 10:38:06,369 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:07,494 - INFO - Accelerator device: 'cpu'
2025-12-18 10:38:07,727 - INFO - Processing document Gamelancer Media Corp1__p6.pdf
2025-12-18 10:38:08,418 - INFO - Finished converting document Gamelancer Media Corp1__p6.pdf in 3.50 sec.

Gamelancer Media Corp1.pdf
<!-- image -->

## GENERAL DEVELOPMENT OF THE BUSINESS

Gamelancer is a media and entertainment company that structures and builds creative marketing campaigns for brands and owns and operates a social media network of over 54 channels across TikTok,  Snapchat  and  Instagram  where  it  sells  direct  advertising  for  clients  and  partners ( Gamelancer Media ). Gamelancer develops brand, agency and creator relationships through its strategic partnerships with TikTok North America and Snap Inc., and operates a business with Snapchat where it creates Snapchat Discover shows which generate monthly recurring revenue.

## Three-Year History

## Acquisitions:

## Wondr Gaming Corporation (May 3, 2021):

In  connection  with  the  listing  of  the  Company's  Common  Shares  on  the  CSE,  the  Company completed  a  three-cornered  amalgamation  (the  ' Wondr  Transaction ')  with  Wondr  Gaming Corporation, formerly 1Wondr Gaming Corporation (' Wondr '),  pursuant  to  which  the  Company acquired all of the issued and outstanding common shares of Wondr in exchange for Common Shares of the Company.  The Wondr Transaction was carried out in accordance with the terms and conditions of an amalgamation agreement dated October 20, 2020 between the Company, Wondr and 2778533 Ontario Inc. (the ' Wondr Agreement ').    Pursuant  to  the  Wondr  Agreement,  the Company issued an aggregate of 134,735,966 Common Shares to the former Wondr shareholders, such that upon completion of the Wondr Transaction the total issued and outstanding Common Shares  of  the  Company  was  151,348,045,  with  the  former  Wondr  shareholders  holding approximately 89% of the total number of the issued and outstanding Common Shares and the original  shareholders  of  the  Company  following  the  consolidation  (as  described  below)  holding approximately 11% of the outstanding Common shares.

Prior to the completion of the Wondr Transaction, the Company consolidated its Common Shares on the basis of 30 pre-consolidation shares for one post-consolidation Common Share and the Company changed its name from 'Transglobe Internet and Telecom Co., Ltd.' to 'Wondr Gaming Corp.'

## Enterprise Gaming Canada Inc. (June 1, 2021):

The Company completed the acquisition of Enterprise Gaming Canada Inc. (' Enterprise '), owner of a proprietary Non-Fungible Token (' NFT ') platform, pursuant to a binding agreement dated May 17, 2021.  Pursuant to the agreement, the Company issued an aggregate of 4,000,000 Common Shares at a deemed price of $0.25 per Common Share, to the shareholders of Enterprise on a prorata basis.

The Common Shares issued in connection with the acquisition of Enterprise were subject to a fourmonth  resale  restriction  and  an  18-month  voluntary  escrow  agreement  between  the  selling shareholders of Enterprise and the Company.
-------------------------

In [ ]:
df_overview_2 = df_overview_2.rename({"Description_page": "description_page"})

In [31]:
df_overview_2[pd.notna(df_overview_2["Description"])]

,Symbol,Description_page,Unnamed: 0,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description
85,KR7086060001,5.0,97,"Gene Bio Tech Co., Ltd.",1,2000.0,KOR,Y2684U105,20060428.0,KOR,...,1.0,086060-KR,1,SHARE,B11R103,A,"Gene Bio Tech Co., Ltd.1.pdf",1.6,1,## WHO WE ARE\n\nBio-Gene is an Australian ...
186,CA53272L2021,56.0,200,Liminal BioSciences Inc.,1,1994.0,USA,53272L202,20120515.0,CAN,...,1.0,LMNL-US,1,SHARE,BQXLM50,C,Liminal BioSciences Inc.1.pdf,21.1,21,## B. Business Overview\n\nWe are a developmen...
189,FR0013183985,1.0,203,Gensight Biologics SA,1,2012.0,FRA,F4374K117,20160713.0,FRA,...,1.0,SIGHT-FR,1,SHARE,BD07M05,C,Gensight Biologics SA1.pdf,21.2,21,<!-- image -->\n\n## GenSight Biologics Report...
192,AT0000A18XM4,12.0,206,ams-OSRAM AG,1,1981.0,CHE,A0400Q115,20080423.0,AUT,...,1.0,AUKUF-US,0,SHARE,BPFJ772,C,ams-OSRAM AG1.pdf,26.1,26,## Our company\n\nams OSRAM is a global leader...
194,KYG4644K1022,9.0,208,Hua Medicine Ltd.,1,2009.0,HKG,G4644K102,20180914.0,CHN,...,1.0,2552-HK,1,SHARE,BF3S3D9,C,Hua Medicine Ltd.1.pdf,21.2,21,## Business overview\n\nWe are a China-based d...
201,MYQ0128OO007,13.0,215,Frontken Corp. Bhd.,1,1996.0,MYS,Y26510100,20060711.0,MYS,...,1.0,0128-MY,1,SHARE,B18TLC4,C,Frontken Corp. Bhd.1.pdf,26.1,26,## CHAPTER 1.0 INTRODUCTION\n\n## 1.1 ABOUT FR...
205,US0326541051,6.0,219,"Analog Devices, Inc.",0,1965.0,USA,032654105,19981201.0,USA,...,1.0,ANL-DE,0,SHARE,5579130,C,"Analog Devices, Inc.1.pdf",26.1,26,"## ITEM 1. BUSINESS\n\n## Company Overview,..."
241,US74275C2052,4.0,255,"Processa Pharmaceuticals, Inc.",1,2011.0,USA,74275C205,20131113.0,USA,...,1.0,PCSA-US,1,SHARE,BL3SW90,C,"Processa Pharmaceuticals, Inc.2.pdf",21.2,21,## PROSPECTUS SUMMARY\n\nThis summary highligh...
243,KYG9005B1041,12.0,257,Transcenta Holding Limited,1,NaN,HKG,G9005B104,20210929.0,CHN,...,1.0,6628-HK,1,SHARE,BMHT0W5,C,Transcenta Holding Limited1.pdf,21.2,21,## OVERVIEW\n\nWe are a clinical stage biophar...
244,US23954D1090,4.0,258,"Day One Biopharmaceuticals, Inc.",1,2018.0,USA,23954D109,20210527.0,USA,...,1.0,DAWN-US,1,SHARE,BLB0YH0,C,"Day One Biopharmaceuticals, Inc.1.pdf",21.2,21,## Item 1. Business.\n\n## Overview\n\nDay One...
253,US15114L1044,13.0,267,"Cell Source, Inc.",1,2012.0,USA,15114L104,20140313.0,USA,...,1.0,CLCS-US,1,SHARE,BNN83Y6,C,"Cell Source, Inc.1.pdf",21.1,21,"## CELL SOURCE, INC. AND SUBSIDIARY\n\n## NOTE..."
255,KYG5257K1076,6.0,269,Kingboard Laminates Holdings Limited,1,1988.0,HKG,G5257K107,20161205.0,HKG,...,1.0,@NA,0,SHARE,BD8NKK1,C,Kingboard Laminates Holdings Limited1.pdf,26.1,26,## Condensed Consolidated Statement of Changes...
267,KYG549581067,3.0,281,Hansoh Pharmaceutical Group Company Limited,1,2015.0,HKG,G54958106,20190911.0,CHN,...,1.0,@NA,0,SHARE,BKLJN73,C,Hansoh Pharmaceutical Group Company Limited1.pdf,21.2,21,## Corporate Overview\n\nThe Company is one of...
270,NO0003070609,3.0,284,IDEX Biometrics ASA,1,1996.0,NOR,R33736100,20101116.0,NOR,...,1.0,0MTP-GB,0,SHARE,B43BZJ1,C,IDEX Biometrics ASA1.pdf,26.1,26,## REPORT FROM THE BOARD OF DIRECTORS\n\nWe we...
271,MYL3867OO008,12.0,285,Malaysian Pacific Industries Bhd.,1,1962.0,MYS,Y56939104,19880323.0,MYS,...,1.0,3867-MY,1,SHARE,6556693,C,Malaysian Pacific Industries Bhd.1.pdf,26.1,26,OVERVIEW\n\n<!-- image -->\n\nMalaysian Pacifi...
281,KYG3931M1024,9.0,295,Global Lighting Technologies Inc.,1,2000.0,TWN,G3931M102,20110728.0,TWN,...,1.0,4935-TW,1,SHARE,B6QH3G3,C,Global Lighting Technologies Inc.1.pdf,26.1,26,## 2. Company Profile\n\n## 2.1 Company and Gr...
283,DE000A1YCMM2,6.0,297,SolarWorld AG,0,1998.0,DEU,D7045Y145,20071116.0,DEU,...,1.0,0QJC-GB,0,SHARE,BJFLSH3,C,SolarWorld AG1.pdf,26.1,26,## Contents\n\n## Our purpose\n\nWe improve co...
440,JP3100320005,2.0,502,URBAN LiKE INC.,1,2008.0,JPN,J94435104,20210728.0,JPN,...,1.0,2992-JP,1,SHARE,BP5D4T5,F,URBAN LiKE INC.1.pdf,41.2,41,## CONTENTS\n\n| STRATEGICREPORT pages 1 to 55...
446,AU0000032914,2.0,508,SRG Global Limited,1,1961.0,AUS,Q8661T101,20200408.0,AUS,...,1.0,SRGGF-US,0,SHARE,BL1MSJ6,F,SRG Global Limited1.pdf,41.2,41,## WHEN IT HAS TO BE DONE RIGHT\n\nSRG Global ...
447,FDS0FNU4,7.0,509,China Energy Engineering Corp. Ltd.,1,2014.0,HKG,FDS0FNU49,NaN,CHN,...,1.0,@NA,0,SHARE,@NA,F,China Energy Engineering Corp. Ltd.1.pdf,42.2,42,<!-- image -->\n\n## COMPANY PROFILE AND CORPO...
450,US5526761086,19.0,512,"M.D.C. Holdings, Inc.",1,1972.0,USA,552676108,20180129.0,USA,...,1.0,0JW5-GB,0,SHARE,BYZH843,F,"M.D.C. Holdings, Inc.1.pdf",41.2,41,## Notes to the Consolidated Financial Stateme...
454,BMG0957L1090,16.0,516,Beijing Enterprises Water Group Limited,1,1992.0,HKG,G0957L109,20040831.0,HKG,...,1.0,HUN2-DE,0,SHARE,B020H51,F,Beijing Enterprises Water Group Limited2.pdf,42.2,42,## MANAGEMENT DISCUSSION AND ANALYSIS\n\n## 1....
461,MYL5219OO000,4.0,522,Pestech International Bhd.,1,2011.0,MYS,Y6801F107,20120530.0,MYS,...,1.0,5219-MY,1,SHARE,B8095F2,F,Pestech International Bhd.1.pdf,42.9,42,<!-- image -->\n\n## About PESTECH\n\nPESTECH ...
463,MX01LA080009,7.0,524,Sitios Latinoamerica SAB de CV,1,NaN,MEX,P87026103,20220929.0,MEX,...,1.0,LASITEB.1-MX,1,SHARE,BNTFDQ3,F,Sitios Latinoamerica SAB de CV1.pdf,42.2,42,## General Information About Us\n\nSitios Lati...
472,DE000A0STWH9,4.0,533,Deutsche Eigenheim Union AG,1,2007.0,DEU,D5S20K106,20211230.0,DEU,...,1.0,JZ6-DE,1,SHARE,BPCK369,F,Deutsche Eigenheim Union AG1.pdf,41.2,41,## D A S G E S C H Ä F T S M O D E L L\n\nBe...
475,PLBUDMX00013,8.0,536,Budimex SA,1,1968.0,POL,X0788V103,20081106.0,POL,...,1.0,0LRV-GB,0,SHARE,B28FKZ5,F,Budimex SA1.pdf,41.2,41,2.\n\n## About the Budimex Group\n\n## 2.1. A...
476,IT0005339160,5.0,537,PLC S.p.A.,1,2006.0,ITA,T5R88H130,20071123.0,ITA,...,1.0,0MMX-GB,0,SHARE,BGDSQ15,F,PLC S.p.A.2.pdf,42.2,42,"- ENERGY TRANSFORMS US, WE TRANSFORM ENERGY\n\..."
479,KYG8661K1013,7.0,540,Tai Kam Holdings Limited,1,2016.0,HKG,G8661K101,20161028.0,HKG,...,1.0,8321-HK,1,SHARE,BDFT8F3,F,Tai Kam Holdings Limited1.pdf,42.9,42,## MANAGEMENT DISCUSSION AND ANALYSIS\n\n## BU...
481,INE291R01011,4.0,542,Athena Constructions Ltd.,0,2011.0,IND,Y0R7X4104,20150416.0,IND,...,1.0,539099-IN,0,SHARE,BWWYV33,F,Athena Constructions Ltd.1.pdf,41.2,41,NOTICE is hereby given that the Eleventh Annua...
486,TW0003703005,7.0,547,Continental Holdings Corp.,1,1941.0,TWN,Y1753K105,19950427.0,TWN,...,1.0,3703-TW,1,SHARE,B58DQK7,F,Continental Holdings Corp.1.pdf,41.2,41,## Company Overview\n\n## Founding and History...
487,TW0009906008,5.0,549,Hsin Ba Ba Corporation,1,1967.0,TWN,Y1754R109,19910920.0,TWN,...,1.0,9906-TW,1,SHARE,6224547,F,Hsin Ba Ba Corporation1.pdf,41.2,41,## Chapter I. Letter to Shareholders\n\n## Dea...
489,MYL5398OO002,5.0,551,Gamuda Bhd.,1,1976.0,MYS,Y2679X106,20171031.0,MYS,...,1.0,GMUAF-US,0,SHARE,B02GQV8,F,Gamuda Bhd.1.pdf,42.1,42,## OVERVIEW OF GAMUDA\n\n## Our Vision\n\nWe ...
491,MYL03042O008,16.0,554,BV Land Holdings Bhd.,1,2019.0,MYS,Y1028X106,20210409.0,MYS,...,1.0,03042-MY,1,SHARE,BL6CN29,F,BV Land Holdings Bhd.1.pdf,41.2,41,<!-- image -->\n\n## Notes to the consolidated...
492,TW0002546009,8.0,556,"Kedge Construction Co., Ltd.",1,1982.0,TWN,Y4629Y101,20000107.0,TWN,...,1.0,2546-TW,1,SHARE,6122555,F,"Kedge Construction Co., Ltd.1.pdf",41.2,41,## Notes to the Consolidated Financial Stateme...
493,US3906071093,11.0,557,Great Lakes Dredge & Dock Corporation,1,1890.0,USA,390607109,20061227.0,USA,...,1.0,GLDD-US,1,SHARE,B1LDZK9,F,Great Lakes Dredge & Dock Corporation1.pdf,42.9,42,"## Item 1. Business.\n\nThe terms 'we,' 'our,'..."
497,NL0015000DY3,5.0,561,Corre Energy B.V.,1,2021.0,IRL,N2281Q103,20210923.0,NLD,...,1.0,CORRE-IE,1,SHARE,BK80W50,F,Corre Energy B.V.1.pdf,42.2,42,## Energy storage\n\nProven technology: Compre...
498,KYG0R8151046,7.0,562,Able Engineering Holdings Ltd.,1,1976.0,HKG,G0R815104,20170220.0,HKG,...,1.0,1627-HK,1,SHARE,BYMXJK7,F,Able Engineering Holdings Ltd.2.pdf,41.2,41,## NOTES TO THE CONDENSED CONSOLIDATED INTERIM...
500,CA88577D1096,5.0,564,Three Sixty Solar Ltd,1,1994.0,CAN,88577D109,20161230.0,CAN,...,1.0,VSOLF-US,0,SHARE,BNNGYV4,F,Three Sixty Solar Ltd2.pdf,42.2,42,## Business Activities\n\nDESIGN / BUILD / INS...
505,AU000000DEM4,7.0,569,De.mem Ltd.,1,2013.0,AUS,Q32195101,20220729.0,AUS,...,1.0,DEMEF-US,0,SHARE,BJP55Y1,F,De.mem Ltd.1.pdf,42.2,42,## De.mem Limited Directors' report 31 Decembe...
507,SG1X13940751,3.0,571,Boustead Singapore Limited,1,1828.0,SGP,V12756165,19850102.0,SGP,...,1.0,F9D-SG,1,SHARE,6207076,F,Boustead Singapore Limited1.pdf,41.1,41,"## Corporate Profile\n\nEstablished in 1828, B..."
509,JP3667600005,18.0,572,JGC Holdings Corporation,1,1928.0,JPN,J26945105,20080605.0,JPN,...,1.0,JGCCF-US,0,SHARE,B3BHSP1,F,JGC Holdings Corporation1.pdf,42.2,42,Other business\n\n1.4%\n\n## JGC Group at a Gl...
511,GB0000961622,2.0,574,Balfour Beatty plc,1,1909.0,GBR,G3224V108,20031119.0,GBR,...,1.0,BAFBF-US,0,SHARE,B02SQJ2,F,Balfour Beatty plc1.pdf,42.1,42,Balfour Beatty is a leading international infr...
520,US07556Q8814,9.0,585,"Beazer Homes USA, Inc.",1,1985.0,USA,07556Q881,19940223.0,USA,...,1.0,BZH-US,1,SHARE,B8KHZT0,F,"Beazer Homes USA, Inc.1.pdf",41.2,41,## Item 1. Business\n\nWe are a geographically...
528,FDS0ABX8,11.0,593,"Yunnan Water Investment Co., Limited",1,2011.0,HKG,FDS0ABX88,NaN,CHN,...,1.0,@NA,0,SHARE,@NA,F,"Yunnan Water Investment Co., Limited1.pdf",42.2,42,## 3. Segment information\n\nThe executive dir...
529,GRS145003000,74.0,594,GEK Terna Holding Real Estate Construction SA,1,1959.0,GRC,X3125P102,20151022.0,GRC,...,1.0,GKTRF-US,0,SHARE,BRGWDY3,F,GEK Terna Holding Real Estate Construction SA1...,41.1,41,"and ninety one (103,423,291) common registered..."
534,US87265H1095,2.0,599,"Tri Pointe Homes, Inc.",1,2009.0,USA,87265H109,20130131.0,USA,...,1.0,TPH-US,1,SHARE,B92CQF3,F,"Tri Pointe Homes, Inc.1.pdf",41.2,41,## Who we are\n\nOne of the largest homebuilde...
820,GB00BDFDLT01,4.0,910,i-nexus Global plc,1,2018.0,GBR,G4768Y102,20180621.0,GBR,...,1.0,INX-GB,1,SHARE,BDFDLT0,J,i-nexus Global plc1.pdf,58.2,58,## STRATEGIC REPORT: Company Overview\n\ni-nex...
822,GB00BYN5BY03,2.0,912,Hybrid Software Group PLC,1,2013.0,BEL,G3971B107,20010417.0,GBR,...,1.0,HYSG-BE,1,SHARE,BYN5BY0,J,Hybrid Software Group PLC1.pdf,58.2,58,## CONTENTS\n\n| Hybrid Software Group ...
828,GB00BFM6WC61,13.0,918,KRM22 Plc,1,2018.0,GBR,G53173103,20180430.0,GBR,...,1.0,KRM-GB,1,SHARE,BFM6WC6,J,KRM22 Plc1.pdf,58.2,58,## OUR PRODUCTS\n\nBuilt on the Global Risk Pl...
830,GB00BYXH8F66,6.0,920,Pelatro Plc,1,2017.0,GBR,G6993D100,20171219.0,GBR,...,1.0,PTRO-GB,1,SHARE,BYXH8F6,J,Pelatro Plc1.pdf,58.2,58,## Strategic Report - About Pelatro\n\nFor the...
843,CA26885W1041,6.0,933,ePlay Digital Inc.,1,2013.0,CAN,26885W104,20150921.0,CAN,...,1.0,EPYFF-US,0,SHARE,BYWRDS5,J,ePlay Digital Inc.3.pdf,58.2,58,I\n\n## who we are\n\n<!-- image -->\n\n## G.O...
844,IL0001690119,18.0,934,AI Conversation Systems Ltd,1,1978.0,ISR,M6825X103,19941207.0,ISR,...,1.0,AICS-IL,1,SHARE,6570864,J,AI Conversation Systems Ltd1.pdf,58.2,58,## in Singapore)\n\nSystems Africa for Info...
845,US29259X1046,45.0,935,Encompass Compliance Corp.,0,1991.0,USA,29259X104,20000301.0,USA,...,1.0,ENCC-US,1,SHARE,BZ07DY0,J,Encompass Compliance Corp.1.pdf,58.2,58,## EXECUTIVE COMPENSATION\n\n## Compensation D...
846,INE898S01029,3.0,936,Aurum Proptech Limited,1,2013.0,IND,Y5400E107,20150819.0,IND,...,1.0,539289-IN,1,SHARE,BYW6D26,J,Aurum Proptech Limited2.pdf,58.2,58,## Across the PAges\n\n## Company Overview 01-...
853,BA100TLKMRA2,10.0,944,Telekom Srpske AD,1,1996.0,BIH,X89741106,20080415.0,BIH,...,1.0,TLKM.R.A-BA,1,SHARE,B4W3Y02,J,Telekom Srpske AD2.pdf,61.2,61,## Telekom Srbija a.d. Beograd mts.rs\n\nTelek...
856,CA00510L1067,4.0,947,AcuityAds Holdings Inc,1,2009.0,CAN,00510L106,20120720.0,CAN,...,1.0,ILLM-CA,1,SHARE,BP9P4Z3,J,AcuityAds Holdings Inc1.pdf,58.2,58,outlook and future-oriented financial informat...
858,US92337U2033,10.0,949,"Verb Technology Company, Inc.",1,2012.0,USA,92337U203,20141119.0,USA,...,1.0,VERB-US,1,SHARE,BN4JPD1,J,"Verb Technology Company, Inc.1.pdf",58.2,58,## 1. DESCRIPTION OF BUSINESS\n\n## Our Busine...
864,GB0004740477,3.0,955,Blackbird PLC,1,1998.0,GBR,G1312H106,20210211.0,GBR,...,1.0,BBRDF-US,0,SHARE,B07J8K5,J,Blackbird PLC1.pdf,58.2,58,"- o Net loss after tax £1,917k (12 months to 3..."
884,FDS1P4X5,10.0,975,"Expensify, Inc.",1,2008.0,USA,FDS1P4X52,NaN,USA,...,1.0,@NA,0,SHARE,@NA,J,"Expensify, Inc.1.pdf",58.2,58,## Part I.\n\n## Item 1. Business\n\n## OVERVI...
888,CA36468M1005,6.0,979,Gamelancer Media Corp,1,1999.0,CAN,36468M100,20210507.0,CAN,...,1.0,GMNG-CA,1,SHARE,BLCXNS2,J,Gamelancer Media Corp1.pdf,58.1,58,<!-- image -->\n\n## GENERAL DEVELOPMENT OF TH...

In [38]:
df_overview_2_with_description = pd.merge(df_overview_2, df_overview_3[["Symbol", "Description"]], on="Symbol", how="left")

In [39]:
df_overview_2_with_description

,Symbol,Description_page,Unnamed: 0,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description_x,Description_y
0,CA05335P1099,NaN,0,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1,NaN,NaN
1,JP3947800003,NaN,1,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1,NaN,NaN
2,ID1000167901,NaN,2,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,NaN,## Riwayat Singkat Perseroan\n\nThe Company at...
3,JP3843250006,NaN,3,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1,NaN,NaN
4,VN000000VTQ6,NaN,4,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,KYG4707P1054,NaN,3278,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98,NaN,NaN
3110,ZAE000015277,NaN,12259,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,BRT-ZA,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3,NaN,NaN
3111,NO0011013765,NaN,31130,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,GIGA-NO,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3,NaN,NaN
3112,FR0010776617,NaN,68675,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,ALMER-FR,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3,NaN,NaN
3113,ZAE000240198,NaN,69396,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,SHG-ZA,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3,NaN,NaN

In [45]:
len(df_overview_2_with_description[pd.notna(df_overview_2_with_description["Description_x"])]), len(df_overview_2_with_description[pd.notna(df_overview_2_with_description["Description_y"])])

KeyboardInterrupt:

In [44]:
len(df_overview_2_with_description[pd.notna(df_overview_2_with_description["Description_x"]) & pd.notna(df_overview_2_with_description["Description_y"])])

23

In [48]:
df_overview_2_with_description

,Symbol,Description_page,Unnamed: 0,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description_x,Description_y,Description
0,CA05335P1099,NaN,0,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1,NaN,NaN,NaN
1,JP3947800003,NaN,1,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1,NaN,NaN,NaN
2,ID1000167901,NaN,2,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,NaN,## Riwayat Singkat Perseroan\n\nThe Company at...,NaN
3,JP3843250006,NaN,3,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1,NaN,NaN,NaN
4,VN000000VTQ6,NaN,4,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,KYG4707P1054,NaN,3278,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98,NaN,NaN,NaN
3110,ZAE000015277,NaN,12259,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3,NaN,NaN,NaN
3111,NO0011013765,NaN,31130,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3,NaN,NaN,NaN
3112,FR0010776617,NaN,68675,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3,NaN,NaN,NaN
3113,ZAE000240198,NaN,69396,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3,NaN,NaN,NaN

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
00{"name":"Exception","message":"not_supported","stack":["Traceback \u001b[1;36m(most recent call last)\u001b[0m:\n","\u001b[0m  File \u001b[0;32m<string>:174\u001b[0m in \u001b[0;35m__DW_DEBUG_WRAPPER__\u001b[0m\n","\u001b[1;36m  File \u001b[1;32m<string>:165\u001b[1;36m in \u001b[1;35m__DW_GET_EXPRESSION_VARIABLE__\u001b[1;36m\n","\u001b[1;31mException\u001b[0m\u001b[1;31m:\u001b[0m not_supported\n"]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}

In [ ]:
df_overview_2_with_description["Description"] = df_overview_2_with_description["Description_x"]
pd.notna(df_overview_2_with_description["Description"]).sum()

60

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}

In [58]:
df_overview_2_with_description.loc[pd.isna(df_overview_2_with_description["Description"]),"Description"] = df_overview_2_with_description[pd.isna(df_overview_2_with_description["Description"])]["Description_y"]

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}

In [59]:
pd.notna(df_overview_2_with_description["Description"]).sum()

95

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}

In [ ]:
df_overview_2

,Symbol,Description_page,Unnamed: 0,Name,Company is Active,Company Founded Date,Country of Primary Listing Iso3,CUSIP,Date Of First Trade,Entity Country HQ,...,Public Company,Region Ticker,Sec is Primary Issue,Sec Type,SEDOL,NACE_letter,Report,NACE_lvl_3,NACE_lvl_2,Description
0,CA05335P1099,NaN,0,Auxly Cannabis Group Inc.,1,1987.0,CAN,05335P109,19960301.0,CAN,...,1.0,XLY-CA,1,SHARE,BDGMQB3,A,Auxly Cannabis Group Inc.2.pdf,1.3,1,NaN
1,JP3947800003,NaN,1,"MEGMILK SNOW BRAND Co., Ltd.",1,2009.0,JPN,J41966102,20220727.0,JPN,...,1.0,MMSBF-US,0,SHARE,BKQN701,A,"MEGMILK SNOW BRAND Co., Ltd.2.pdf",1.4,1,NaN
2,ID1000167901,NaN,2,PT Cilacap Samudera Fishing Industry Tbk,0,1999.0,IDN,Y129H6108,20220527.0,IDN,...,1.0,ASHA-ID,0,SHARE,BMBMZG9,A,PT Cilacap Samudera Fishing Industry Tbk3.pdf,3.1,3,NaN
3,JP3843250006,NaN,3,Hokuto Corporation,1,1964.0,JPN,J2224T102,19941202.0,JPN,...,1.0,1379-JP,1,SHARE,6432715,A,Hokuto Corporation1.pdf,1.3,1,NaN
4,VN000000VTQ6,NaN,4,Viet Trung Quang Binh Joint Stock Co,0,1961.0,VNM,Y937XS108,NaN,VNM,...,1.0,VTQ-VN,0,SHARE,BMCR2W8,A,Viet Trung Quang Binh Joint Stock Co3.pdf,2.3,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,KYG4707P1054,NaN,3278,Icon Culture Global Company Limited,1,2019.0,HKG,G4707P105,20200114.0,CHN,...,1.0,8500-HK,1,SHARE,BJYFY12,T,Icon Culture Global Company Limited2.pdf,98.1,98,NaN
3110,ZAE000015277,NaN,12259,Brimstone Investment Corporation Limited,1,1995.0,ZAF,S13750112,19980708.0,ZAF,...,1.0,BRT-ZA,0,SHARE,6119966,A,Brimstone Investment Corporation Limited1.pdf,3.1,3,NaN
3111,NO0011013765,NaN,31130,Gigante Salmon AS,1,2001.0,NOR,R2724U105,20210705.0,NOR,...,1.0,GIGA-NO,1,SHARE,BMC4Z19,A,Gigante Salmon AS1.pdf,3.1,3,NaN
3112,FR0010776617,NaN,68675,Sapmer SA,1,1989.0,FRA,F7887Q109,20090708.0,FRA,...,1.0,ALMER-FR,1,SHARE,B3LS274,A,Sapmer SA2.pdf,3.1,3,NaN
3113,ZAE000240198,NaN,69396,Sea Harvest Group Ltd.,1,1964.0,ZAF,S74706102,20170323.0,ZAF,...,1.0,SHG-ZA,1,SHARE,BDFBTP6,A,Sea Harvest Group Ltd.1.pdf,3.1,3,NaN

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
00{"name":"Exception","message":"not_supported","stack":["Traceback \u001b[1;36m(most recent call last)\u001b[0m:\n","\u001b[0m  File \u001b[0;32m<string>:174\u001b[0m in \u001b[0;35m__DW_DEBUG_WRAPPER__\u001b[0m\n","\u001b[1;36m  File \u001b[1;32m<string>:165\u001b[1;36m in \u001b[1;35m__DW_GET_EXPRESSION_VARIABLE__\u001b[1;36m\n","\u001b[1;31mException\u001b[0m\u001b[1;31m:\u001b[0m not_supported\n"]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}

In [61]:
df_overview_2_with_description.to_csv("projects/nace_classification/nace_report_topic_analysis/data/datasets/reports_subset_from_full_data_2/reports_subset_from_full_data_2_overview_with_description.csv", sep=",")

10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}
10{"stdout":"[{\"variableName\": \"ID_TO_MEANING\", \"type\": \"dictionary\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"builtins.dict\"}, {\"variableName\": \"NULL\", \"type\": \"unknown\", \"supportedEngines\": [\"pandas\"], \"isLocalVariable\": true, \"rawType\": \"_pydevd_bundle.pydevd_constants.Null\"}]\n","stderr":"","mime":[]}